syndesisio/syndesis

.gitmodules, README.md
@rhuss @chirino @zregvart FYI...
=> Add submodules

pom.xml
Add a top level pom.xml for syndesis monorepo.
=> Add a top level pom.xml for syndesis monorepo.

patch_pr.sh
Use it within this directory with
```
./patch_pr.sh <module> <pr number>
```
After this, a branch "pr/<pr number>" is created and locally committed.
Please create a new PR then on Syndesis on your own, possibly copying
over all relevant comments from the old PR.
This script should be used *after* the move to the monorepo
=> feat: Script for fetching and applying a PR patch added

Jenkinsfile
This reverts commit 50c0b6a55f9b0297893eefec925d1170f0000a2c.
This pull request had issues and merging that will completly break CI.
=> Revert "feat: simplify Jenkinsfile."

ui/src/app/app.component.html, ui/src/app/approuting.module.ts, ui/src/app/customizations/api-connectors/api-connector-list.component.html, ui/src/app/customizations/api-connectors/api-connector-list.component.scss, ui/src/app/customizations/api-connectors/api-connector-list.component.spec.ts, ui/src/app/customizations/api-connectors/api-connector-list.component.ts, ui/src/app/customizations/customizations.component.html, ui/src/app/customizations/customizations.component.scss, ui/src/app/customizations/customizations.component.ts, ui/src/app/customizations/customizations.module.ts
For API Connectors and Technical Extensions.
=> #294 Customizations Page

rest/dao/pom.xml, rest/dao/src/main/java/io/syndesis/dao/extension/ExtensionDataManager.java, rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftConfigurationProperties.java, rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java, rest/project-generator/src/main/java/io/syndesis/project/converter/DefaultProjectGenerator.java, rest/project-generator/src/main/java/io/syndesis/project/converter/ProjectGeneratorConfiguration.java, rest/project-generator/src/main/java/io/syndesis/project/converter/ProjectGeneratorProperties.java, rest/project-generator/src/main/resources/io/syndesis/project/converter/s2i/assemble, rest/project-generator/src/test/resources/io/syndesis/project/converter/test-loader.properties, rest/project-generator/src/test/resources/io/syndesis/project/converter/test-s2i-assemble, rest/runtime/src/main/java/io/syndesis/runtime/ExtensionConfiguration.java
This PR address some issues related to deployment of tech extensions modules related to how spring-boot works.
@syndesisio/backend please review.
=> tech extension: deployment

.circleci/config.yml, build.sh, deploy/generator/syndesis-template.go, deploy/syndesis-ci.yml, deploy/syndesis-dev-restricted.yml, deploy/syndesis-dev.yml, deploy/syndesis-ephemeral-restricted.yml, deploy/syndesis-restricted.yml, deploy/syndesis.yml, s2i/pom.xml
Also get the s2i/pom.xml to actually build the docker image.
=> feat: use the syndesis/syndesis-s2i builder image for faster builds.

rest/pom.xml, rest/syndesis-annotation-processor/src/main/java/io/syndesis/maven/annotation/processing/SyndesisExtensionActionProcessor.java, rest/syndesis-maven-plugin/src/main/java/io/syndesis/maven/GenerateMetadataMojo.java, runtime/runtime-api/src/main/java/io/syndesis/integration/runtime/api/SyndesisActionProperties.java, runtime/runtime-api/src/main/java/io/syndesis/integration/runtime/api/SyndesisActionProperty.java
This fixes #394 
@iocanel, @rhuss, I needed to switch to version 1.2-SNAPSHOT of the runtime-api from the annotation processor. Hope this will not affect the CI.
=> Add annotation for action properties

rest/model/src/main/java/io/syndesis/model/extension/ExtensionDetail.java, rest/rest/src/main/java/io/syndesis/rest/v1beta1/handler/extension/ExtensionHandler.java, rest/runtime/src/test/java/io/syndesis/runtime/ExtensionsITCase.java
Added two more endpoints:
- `/extensions/details`
- `/extensions/{id}/details`
Returning all the data needed by ui.
=> Fixes #410: additional endpoints for extension details

.circleci/config.yml, build.sh, pom.xml, rest/runtime/pom.xml, s2i/pom.xml, ui/.gitignore, ui/docker/Dockerfile, ui/pom.xml, verifier/pom.xml
Consolidate some of the config into the parent pom.
=> Build the ui’s docker image with mvn too.

deploy/generator/04-syndesis-oauth-proxy.yml.mustache
Fixes syndesisio/syndesis-project#101
=> chore: Use reencrypt routes on OpenShift to get e2e TLS

ui/package.json, ui/yarn.lock
=> fix: Incompatibility in atlasmap/ui and atlasmap/runtime

ui/src/app/customizations/customizations.module.ts, ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.html, ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.scss, ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.ts, ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.scss, ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.ts, ui/src/app/customizations/tech-extensions/index.ts, ui/src/app/customizations/tech-extensions/tech-extension-delete-modal.component.html, ui/src/app/customizations/tech-extensions/tech-extension-delete-modal.component.ts, ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html, ui/src/app/customizations/tech-extensions/tech-extensions-list.component.ts, ui/src/app/store/extension/extension.service.ts, ui/src/app/store/extension/extension.store.ts
fixes #267 
relates to #262 and #263
=> feat: Connect update and delete buttons, implement delete flow

ui/pom.xml
=> fix(ui): Fix angular-cli definition in pom.xml

project/proposals/181-tech-extension.adoc
Forgot to port the proposal doc from syndesis-project to monorepo, I need to update the rest endpoint but any feedback would be really appreciated
=> proposal doc: tech extension #181

ui/src/app/connections/list/list.component.ts
reduces the amount of delay for automatically dismissing notifications generated by the list component
addresses issue [234](https://github.com/syndesisio/syndesis/issues/234)
=> fix(notification): reduce list component notification dismissal delay

project/proposals/119-custom-connectors.md
This is the initial design proposal for custom connectors.
=> feat: Design proposal for custom connectors

ui/src/app/integrations/detail-page/detail.component.html, ui/src/app/integrations/edit-page/current-flow.service.ts, ui/src/app/integrations/edit-page/flow-view/flow-view-step.component.ts, ui/src/app/integrations/edit-page/step-configure/step-configure.component.ts, ui/src/app/integrations/edit-page/step-select/step-select.component.html, ui/src/app/integrations/edit-page/step-select/step-select.component.ts, ui/src/app/integrations/integrations.module.ts, ui/src/app/store/step/step.store.ts
Also adds in the toolbar for filtering steps and implements the 'Custom Step' selector thingie.
fixes #266
fixes #284
@lburgazzoli FYI
=> feat: Fetch extensions in the editor on the step select page

build.sh
Uses `~` as delimiter in `project_lock_data()` to be certain that the
fields are parsed according to their positions, as using ` ` would lead
to fields being parsed out of order.
Sets the project/namespace annotation on the secret used for locking to
make sure that the `newallocator` check passes to confirm that the lock
has been taken.
=> fix: ci locking

rest/rest/src/main/java/io/syndesis/rest/v1/handler/integration/IntegrationHandler.java, rest/rest/src/main/java/io/syndesis/rest/v1/handler/integration/IntegrationSupportHandler.java
=> feat: Import integration in draft status.

ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.html, ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html, ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.ts, ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html, ui/src/app/store/extension/extension.service.ts, ui/src/app/store/extension/extension.store.ts
=> feat: implement updating a technical extension

.mention-bot
=> chore: add .mention-bot configuration file

ui/src/app/integrations/components/integrationViewBase.component.ts, ui/src/app/integrations/detail-page/detail.component.ts, ui/src/app/integrations/list/list.component.ts
=> feat: Integrations list: add export action to kebab menu.

ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.html, ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.ts, ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html, ui/src/app/customizations/tech-extensions/tech-extensions-list.component.ts
=> feat: show uses column on extension list

app/deploy/README.md
Updates links to OpenShift templates, also updates the `oc new-app`
parameters.
=> fix: links to OpenShift templates

app/build.sh
Run build.sh -h to see the new shortcuts
=> feat: Add shortcuts to build.sh

app/connectors/connectors/sql/sql-common/pom.xml, app/connectors/examples/sql-stored-example/pom.xml, app/connectors/examples/sql-stored-example/src/main/java/io/syndesis/example/SampleStoredProcedures.java, app/connectors/examples/sql-stored-example/src/main/java/io/syndesis/example/SqlStoredApplication.java
Wonder btw whether we shouldnt disable exampls by default ?
=> fix: Remove test dependencies of compile scope deps.

.circleci/config.yml
=> ci(circleci): Simplify concatenating poms for cache key checksum

app/build.sh
This is useful if the docker mode is used for creating images
(and the dev template)
Also: --docker and --openshift are now shortcuts for --image-mode docker
and --image-mode openshift
=> feature: Add option --kill-pods (-k) for killing pods at the end of build

app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorHandler.java
=> feat(rest): Enable updating Connectors to handle updating custom connectors

app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorHandler.java
=> feat(rest): Enable deleting of Connectors

app/connectors/connectors/jms/activemq-connectors/activemq-model/src/main/java/io/syndesis/connector/jms/ActiveMQConnectorVerifierExtension.java, app/verifier/src/main/java/io/syndesis/verifier/impl/ActiveMQVerifier.java, app/verifier/src/main/resources/application.yml
=> Fixed AMQ connection verification

app/ui/src/app/connections/common/configuration/configuration.service.ts
Otherwise Validate button does not display.
fix #673 
cc @KurtStam
=> Update ID for DB connector

app/ui/src/app/integrations/edit-page/step-select/step-select.component.html
[#600 Integrations - unify "Add a Step"/"Choose a Step" labels](https://github.com/syndesisio/syndesis/issues/600)
=> fix: #600 Integrations - unify "Add a Step"/"Choose a Step" labels

app/rest/rest/src/main/java/io/syndesis/rest/v1/SyndesisRestException.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/exception/SyndesisRestExceptionMapper.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/extension/ExtensionHandler.java, app/rest/runtime/src/test/java/io/syndesis/runtime/ExtensionsITCase.java
=> Fix message in extension upload error

app/rest/model/src/main/java/io/syndesis/model/extension/Extension.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/extension/ExtensionHandler.java, app/rest/runtime/src/test/java/io/syndesis/runtime/ExtensionsITCase.java
=> Add missing metadata to tech extensions

app/rest/pom.xml
https://issues.jboss.org/browse/ENTESB-7438
=> ENTESB-7438 Align syndesis-rest to iharder base64 version 2.3.8

app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.html, app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html
=> Tech extension: wrong ID shown on import/update page #683

app/rest/pom.xml
Required as part of Support Page feature.
Needs more than even feedback from CI since I haven't run the complete test suite, but only `rest` and `runtime` modules.
=> Upgraded Kubernetes client versions

app/ui/src/app/common/ui-patternfly/notification-service.ts, app/ui/src/app/customizations/api-connector/api-connector.service.ts
=> API Connector List Endpoint

app/rest/rest/src/main/java/io/syndesis/rest/util/ReflectiveFilterer.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/extension/ExtensionHandler.java, app/rest/runtime/src/test/java/io/syndesis/runtime/ExtensionsITCase.java
Fixes #739 and fixes #754 .
Had to change the query filtering because it did not support enumerations and non-string objects.
=> Fix extension backend issues

app/rest/pom.xml
This reverts commit 2e100b19bda186af68c96b35159234520c01671d.
=> Revert "Upgraded Kubernetes client versions"

app/deploy/generator/03-syndesis-ui.yml.mustache, app/deploy/generator/04-syndesis-rest.yml.mustache, app/deploy/generator/04-syndesis-verifier.yml.mustache, app/deploy/generator/04-todo-example.yml.mustache
=> Enforced ordering in pods activation

app/ui/src/app/customizations/customizations.component.html, app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.html, app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html, app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.ts, app/ui/src/app/customizations/tech-extensions/tech-extension-delete-modal.component.html, app/ui/src/app/customizations/tech-extensions/tech-extension-delete-modal.component.ts, app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html, app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.ts
Fixes #801
@syndesisio/ui-api may you have a look ?
=> Change user visible instances of "technical extension" to "extension"

app/rest/pom.xml, app/rest/runtime/pom.xml, app/verifier/pom.xml, tools/bin/commands/release
This takes care of the maven release part of the release.
Pushing images to dockerhub or other artifacts to their corresponding repositories hasn't been automated yet.
=> feat: First draft of release script.

app/s2i/pom.xml, app/s2i/src/main/docker/Dockerfile, app/s2i/src/main/resources/settings.xml
This is an attempt to solve #695 - we're getting an error building s2i inside the pipeline once alignments are made because the camel artifacts needed here are on the ea repository, and in the Dockerfile mvn build, there's no repository for ea.
=> Need to add a custom settings.xml for the s2i image so we can resolve artifacts from SNAPSHOTs and from the ea repository.

tools/bin/commands/build
=> fix: Fix order of backend modules

app/rest/project-generator/src/main/java/io/syndesis/project/converter/DefaultProjectGenerator.java, app/rest/project-generator/src/main/java/io/syndesis/project/converter/ProjectGeneratorConfiguration.java, app/rest/project-generator/src/main/java/io/syndesis/project/converter/mvn/MavenGav.java, app/rest/project-generator/src/main/java/io/syndesis/project/converter/visitor/GeneratorContext.java, app/rest/project-generator/src/main/java/io/syndesis/project/converter/visitor/StepVisitorContext.java, app/rest/project-generator/src/test/java/io/syndesis/project/converter/DefaultProjectGeneratorTest.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/CustomConnectorHandler.java, app/rest/runtime/src/test/java/io/syndesis/runtime/ConnectorsITCase.java, app/runtime/model/src/main/java/io/syndesis/integration/model/steps/ChildSteps.java, app/runtime/model/src/main/java/io/syndesis/integration/model/steps/Endpoint.java
This adds appropriate `@SuppressWarnings` annotations, removes unused
imports, declares methods that can be used as static and removes
unneeded `else` when the body of `if` returns from method.
=> refactor: cleanup

app/deploy/generator/04-syndesis-oauth-proxy.yml.mustache, app/deploy/syndesis-dev-restricted.yml, app/deploy/syndesis-dev.yml, app/deploy/syndesis-restricted.yml, app/deploy/syndesis.yml
=> Modified oauth proxy probes

tools/bin/commands/build
Once again, but this time it' the one... @zregvart Merry Christmas 🎁
=> fix: Fix order of modules

app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorHandler.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorIconHandler.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/CustomConnectorHandler.java, app/rest/rest/src/test/java/io/syndesis/rest/v1/handler/connection/CustomConnectorHandlerTest.java, app/rest/runtime/src/test/java/io/syndesis/runtime/connector/CustomConnectorITCase.java
=> feat: Create multipart handler to handle uploading icon at the same time as creating custom connector

app/connectors/connectors/rest/rest-swagger-connector/src/main/java/io/syndesis/connector/swagger/AuthenticationType.java, app/connectors/connectors/rest/rest-swagger-connector/src/main/java/io/syndesis/connector/swagger/SwaggerConnectorComponent.java, app/connectors/connectors/rest/rest-swagger-connector/src/main/java/io/syndesis/connector/swagger/springboot/SwaggerConnectorConnectorConfigurationCommon.java, app/connectors/connectors/rest/rest-swagger-connector/src/main/resources/camel-connector-schema.json, app/connectors/connectors/rest/rest-swagger-connector/src/main/resources/camel-connector.json, app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/PropertyGenerators.java, app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/SupportedAuthenticationTypes.java, app/rest/connector-generator/src/test/java/io/syndesis/connector/generator/swagger/BaseSwaggerGeneratorExampleTest.java, app/rest/connector-generator/src/test/java/io/syndesis/connector/generator/swagger/SwaggerActionParamsGeneratorExampleTests.java, app/rest/connector-generator/src/test/java/io/syndesis/connector/generator/swagger/SwaggerUnifiedShapeGeneratorExampleTests.java, app/rest/connector-generator/src/test/java/io/syndesis/connector/generator/swagger/TestHelper.java, app/rest/connector-generator/src/test/resources/swagger/basic_auth.param_connector.json, app/rest/connector-generator/src/test/resources/swagger/basic_auth.swagger.yaml, app/rest/connector-generator/src/test/resources/swagger/basic_auth.unified_connector.json, app/rest/connector-generator/src/test/resources/swagger/petstore.param_connector.json, app/rest/connector-generator/src/test/resources/swagger/petstore.unified_connector.json, app/rest/connector-generator/src/test/resources/swagger/reverb.param_connector.json, app/rest/dao/src/main/resources/io/syndesis/dao/deployment.json
Adds support for HTTP Basic Authentication (not digest!) in REST Swagger connector generator.
Fixes #436
=> feat: Support HTTP Basic Authentication in REST Swagger connector generator

app/ui/src/app/common/editable/editable-tags.component.ts, app/ui/src/app/common/editable/editable-text.component.ts, app/ui/src/app/common/editable/editable-textarea.component.ts
Seems that changing `*ngIf` to `[ngIf]` helped. Wonder what would be idiomatic Angular solution to this issue?
Fixes #430
=> fix(ui): display integration name and description

app/verifier/src/main/java/io/syndesis/verifier/v1/MetadataEndpoint.java
Stored Procedure metadata is different then SQL metadata.
=> fix: Verifier - Switch to fetch metadata specific to an action #561

doc/integrating_applications/topics/adding_amq_connection_finish.adoc, doc/integrating_applications/topics/adding_amq_connection_middle.adoc, doc/integrating_applications/topics/adding_amq_connection_start.adoc, doc/integrating_applications/topics/adding_api_connectors.adoc, doc/integrating_applications/topics/adding_extensions.adoc, doc/integrating_applications/topics/making_extensions_available.adoc, doc/integrating_applications/topics/managing_extensions.adoc
This is preliminary doc that needs to be reviewed. But it would be good to merge it so it can be published on the Pantheon site and available to all for review as a whole.
=> Draft doc for #853, #854 #855

app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html
=> fix: Correct links for extension import page on cancel and breadcrumbs

app/s2i/copy_mvn_repo.sh
=> Small improvement in s2i copy_mvn_repo.sh

app/ui/src/app/integrations/edit-page/action-configure/action-configure.component.html, app/ui/src/app/integrations/edit-page/action-configure/action-configure.component.ts
=> fix: don't proceed to the next page until the verifier returns no errors

app/ui/package.json, app/ui/src/app/customizations/customizations.module.ts, app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.ts, app/ui/src/app/integrations/integrations.module.ts, app/ui/src/app/integrations/list-page/list-page.component.ts, app/ui/yarn.lock
=> fix: Switch ng2-file-upload dependency version

app/ui/src/app/customizations/customizations.module.ts, app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.html, app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.ts, app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html
Fixes #812 
Warning: For some reason my local data fixture does not yield any values for the `extensionId` or `name` properties, so I could not test this at full.
Perhaps @lburgazzoli might want to test this in his local dev env.
=> fix: extension id field replaced by extensionId instead

app/ui/src/app/customizations/customizations.module.ts, app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.html, app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.ts, app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html
Reverts syndesisio/syndesis#816
=> Revert "fix: extension id field replaced by extensionId instead"

app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html, app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.ts
=> fix: Display correct extension details on import extension page

app/ui/src/app/integrations/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
Mapper was getting initialized before precomputed inspections were loaded sometimes since they were being loaded async.  We now wait for those to load first if needed.
=> Fix: Class inspection for twitter4j.Status not found intermittent error.

app/README.md
fixes: https://github.com/syndesisio/syndesis/issues/88
=> [chore] adding readme on development tips

app/ui/src/app/customizations/customizations.component.html, app/ui/src/app/customizations/customizations.module.ts, app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html, app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.ts, app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html
=> chore: Rename extensions path to /customizations/extensions

app/ui/src/app/common/forms.service.ts, app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.ts, app/ui/src/app/integrations/edit-page/action-configure/action-configure.component.html, app/ui/src/app/integrations/edit-page/action-configure/action-configure.component.ts
fixes #908 
fixes #909 
fixes #912 
Also fixes some unrelated lint errors that crept into the `tech-extensions-import.component.ts`
=> fix: proceed if there's no form, also ensure validation isn't enabled for hidden fields

app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/BaseSwaggerConnectorGenerator.java, app/rest/core/src/main/java/io/syndesis/core/immutable/ImmutablesStyle.java, app/rest/credential/src/test/java/io/syndesis/credential/OAuth1CredentialProviderTest.java, app/rest/credential/src/test/java/io/syndesis/credential/OAuth2CredentialProviderTest.java, app/rest/credential/src/test/java/io/syndesis/credential/salesforce/SalesforceApplicatorTest.java, app/rest/model/src/main/java/io/syndesis/model/connection/ConnectorSummary.java, app/rest/model/src/test/java/io/syndesis/model/connection/ConnectorSummaryTest.java, app/rest/model/src/test/java/io/syndesis/model/connection/DynamicActionMetadataTest.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorHandler.java
=> fix: Add in connector summary details to connector rest api

app/deploy/generator/03-syndesis-ui.yml.mustache, app/deploy/syndesis-ci.yml, app/deploy/syndesis-dev-restricted.yml, app/deploy/syndesis-dev.yml, app/deploy/syndesis-restricted.yml, app/deploy/syndesis.yml, app/ui/src/app/core/providers/api-http-provider.service.ts
=> fix: missing api endpoints node added to OpenShift template

doc/integrating_applications/topics/about_copying_integrations.adoc, doc/integrating_applications/topics/add_advanced_filter_step.adoc, doc/integrating_applications/topics/add_custom_step.adoc, doc/integrating_applications/topics/add_data_mapping_step.adoc, doc/integrating_applications/topics/adding_api_connectors.adoc, doc/integrating_applications/topics/connecting_to_rest_apis.adoc, doc/integrating_applications/topics/creating_api_connectors.adoc, doc/integrating_applications/topics/creating_integrations.adoc, doc/integrating_applications/topics/exporting_integrations.adoc, doc/integrating_applications/topics/importing_integrations.adoc, doc/integrating_applications/topics/procedure_for_creating_an_integration.adoc
This is ready to merge. The content has already been reviewed and is mostly changes based on feedback.
=> Updates to TP3 doc based on feedback #921

app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html
=> Typo in API Client Connectors

app/connectors/connectors/sql/sql-common/src/main/java/io/syndesis/connector/sql/SqlStatementParser.java
=> fix (#924): Validation message now correctly list valid keywords.

app/deploy/generator/03-syndesis-ui.yml.mustache, app/deploy/syndesis-ci.yml, app/deploy/syndesis-dev-restricted.yml, app/deploy/syndesis-dev.yml, app/deploy/syndesis-restricted.yml, app/deploy/syndesis.yml
=> fix(templates): Adapt syndesis-ui config.json to new properties scheme

app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/BaseSwaggerConnectorGenerator.java, app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/SwaggerHelper.java, app/rest/connector-generator/src/test/java/io/syndesis/connector/generator/swagger/SwaggerHelperTest.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/CustomConnectorHandler.java, app/rest/runtime/pom.xml, app/rest/runtime/src/test/java/io/syndesis/runtime/connector/CustomConnectorITCase.java, app/rest/runtime/src/test/java/io/syndesis/runtime/connector/CustomSwaggerConnectorITCase.java, app/rest/runtime/src/test/resources/io/syndesis/runtime/test-swagger.json
@deeleman This should sort you out.
=> fix: Properly handle uploaded swagger specification

app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-auth/api-connector-auth.component.ts
=> fix: Auth form degrades gracefully when no OAuth information is provided

app/rest/connector-generator/pom.xml, app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/SwaggerHelper.java, app/rest/connector-generator/src/test/java/io/syndesis/connector/generator/swagger/SwaggerHelperTest.java, app/rest/connector-generator/src/test/resources/swagger/todo.swagger.yaml
Adds support for validation of Swagger specifications in YAML format.
Fixes #929
=> fix(swagger): Support Swagger YAML validation

app/ui/src/app/app.component.html, app/ui/src/app/app.component.ts
=> fix: Update documentation links

app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html, app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.ts
=> fix: ensure the page properly detects it's an update vs an import

app/deploy/generator/04-syndesis-oauth-proxy.yml.mustache, app/deploy/syndesis-dev-restricted.yml, app/deploy/syndesis-dev.yml, app/deploy/syndesis-restricted.yml, app/deploy/syndesis.yml
Improvement based on discussion here: https://github.com/openshift/oauth-proxy/issues/39
Fixes #742
=> OCP Templates, improved probes

app/ui/src/app/integrations/edit-page/current-flow.service.ts, app/ui/src/app/integrations/edit-page/step-configure/step-configure.component.ts
=> fix: look for extensions with data shapes too, also ensure the step config page updates itself properly

app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.html
=> fix(UI): Wrong CTA text replaced - #997

doc/integrating_applications/topics/add_data_mapping_step.adoc, doc/integrating_applications/topics/available-transformations.adoc, doc/integrating_applications/topics/combine_multiple_source_fields_into_one_target_field.adoc, doc/integrating_applications/topics/map_one_source_field_to_one_target_field.adoc, doc/integrating_applications/topics/mapping-data.adoc, doc/integrating_applications/topics/separate_one_source_field_into_multiple_target_fields.adoc, doc/integrating_applications/topics/transforming_target_data.adoc
Relates to GitHub issue #994 
Add data mapper steps to documentation.
=> FUSEDOC-1633 - add data mapping steps

app/ui/src/app/integrations/edit-page/step-configure/step-configure.component.ts
=> fix: clear out values that get set to 'null'

app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html, app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.ts
=> fix: actually link the extension list page help link

app/ui/src/app/integrations/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integrations/edit-page/flow-view/flow-view-step.component.ts, app/ui/src/app/integrations/edit-page/flow-view/flow-view.component.html, app/ui/src/app/integrations/edit-page/flow-view/flow-view.component.ts
=> fix: simplify the delete modal handling for steps

app/ui/src/app/connections/create-page/create-page.component.ts
restricts the display of the next button in the review step
Fixes https://github.com/syndesisio/syndesis/issues/1006
=> fix(next-btn): do not show the next button on the review page

app/rest/pom.xml
=> chore: Bump AtlasMap to 1.32.2

doc/integrating_applications/master.adoc, doc/integrating_applications/topics/adding_s3_connection_finish.adoc, doc/integrating_applications/topics/adding_s3_connection_middle.adoc, doc/integrating_applications/topics/adding_s3_connection_start.adoc, doc/integrating_applications/topics/adding_s3_connections.adoc, doc/integrating_applications/topics/connecting_to_amazon_s3.adoc, doc/integrating_applications/topics/create_s3_connection.adoc, doc/integrating_applications/topics/how_you_use.adoc, doc/integrating_applications/topics/prerequisites_for_creating_s3_connection.adoc, doc/tutorials/master.adoc
This is ready to merge. It mostly contains updates to the doc for the S3 connector. Doc was reviewed by Andrea. Thanks in advance for merging.
=> User doc for TP3 #921. S3 doc was reviewed by Andrea.

app/ui/src/app/integrations/edit-page/step-configure/step-configure.component.ts
fixes #1047 
Also gets rid of `Object.keys()` to make @kahboom happy :-)
@dsimansk FYI
=> fix: best to check the values and make sure there's some

app/ui/src/app/integrations/components/index.ts, app/ui/src/app/integrations/components/integrationViewBase.component.ts, app/ui/src/app/integrations/components/status.component.ts, app/ui/src/app/integrations/detail-page/detail.component.ts, app/ui/src/app/integrations/detail-page/index.ts, app/ui/src/app/integrations/integrations.module.ts, app/ui/src/app/integrations/list-page/index.ts, app/ui/src/app/integrations/list-page/list-page.component.ts, app/ui/src/app/integrations/list/index.ts, app/ui/src/app/integrations/list/list.component.ts, app/ui/src/app/integrations/list/list.module.ts
Since the editor went so swimmingly I went and fixed up the rest of the imports in the integration module
=> chore: rework the imports throughout the integrations module

app/connectors/connectors-maven-plugin/pom.xml, app/core/pom.xml, app/pom.xml
=> refactor(atlasmap): Added atlasmap.version to top-level parent

app/core/model/src/main/java/io/syndesis/model/Schema.java, app/core/model/src/main/java/io/syndesis/model/extension/Extension.java, app/rest/jsondb/pom.xml, app/rest/jsondb/src/main/java/io/syndesis/jsondb/GetOptions.java, app/rest/jsondb/src/main/java/io/syndesis/jsondb/impl/Index.java, app/rest/jsondb/src/main/java/io/syndesis/jsondb/impl/JsonRecordConsumer.java, app/rest/jsondb/src/main/java/io/syndesis/jsondb/impl/JsonRecordSupport.java, app/rest/jsondb/src/main/java/io/syndesis/jsondb/impl/SqlJsonDB.java, app/rest/jsondb/src/main/java/io/syndesis/jsondb/rest/JsonDBResource.java, app/rest/jsondb/src/test/java/io/syndesis/jsondb/impl/JsonDBTest.java, app/rest/runtime/src/main/java/io/syndesis/runtime/DataStoreConfiguration.java, app/rest/runtime/src/main/java/io/syndesis/runtime/SchemaCheck.java, app/rest/runtime/src/test/java/io/syndesis/runtime/BaseITCase.java
They must be configured up front when you start the jsondb instance but you should get good performance when you look for records in a collection that have a specific field value.
=> JsonDB: +secondary indexes, +query depth option, +query limit option, +query after option

doc/sdh/workflow/development.adoc
You know, for folks that might want to do that kind of thing...
=> Add details to the developer doc on how to connect pgadmin to the DB

app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html, app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html
=> fix: hide the toolbar import/add button when the list is empty

app/extension/annotation-processor/src/main/java/io/syndesis/maven/annotation/processing/SyndesisExtensionActionProcessor.java
=> [TechExt] Fixed support for html form hints

app/ui/src/app/integration/list/list.component.ts
fixes #1196 
not really sure what's causing the issue, but that modification fixes the problem
=> UI, IntegrationListComponent fix injection

app/ui/src/app/integration/list/list.component.html, app/ui/src/app/integration/list/list.component.ts
=> (fix) Stop generating action config from a function

app/core/core/src/main/java/io/syndesis/core/CollectionsUtils.java, app/core/model/src/main/java/io/syndesis/model/connection/Connector.java, app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentProxyComponent.java, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerate/integration.json, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/ConnectorStepHandler.java, app/integration/runtime/src/test/java/io/syndesis/integration/component/proxy/ComponentProxyGlobalCustomizerTest.java, app/integration/runtime/src/test/resources/syndesis/integration/component/proxy/ComponentProxyGlobalCustomizerTest.json
=> Connectors should support global customizers #1206

app/ui/scripts/minishift-setup.sh
=> UI, local dev script. Improved script to suppoort both xip and nip

app/ui/src/app/customizations/api-connector/api-connector.service.ts
=> UI, fixed api-connector refactoring

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRuntimeAutoConfiguration.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/OutMessageCaptureInterceptStrategy.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/OutMessageCaptureInterceptStrategyTest.java
=> feat: Adding an out message capture intercept strategy.

app/deploy/generator/02-syndesis-image-streams.yml.mustache, app/deploy/generator/04-syndesis-rest.yml.mustache, app/deploy/generator/syndesis-template.go, app/deploy/syndesis-ci.yml, app/deploy/syndesis-dev-restricted.yml, app/deploy/syndesis-dev.yml, app/deploy/syndesis-restricted.yml, app/deploy/syndesis.yml
This was always set to 'latest' and not the syndesis version number
=> fix(deploy): Fixed reference to s2i images

app/pom.xml, app/s2i/copy_mvn_repo.sh, app/s2i/pom.xml, doc/sdh/cli/cmd_doc.adoc, doc/sdh/cli/cmd_release.adoc, tools/bin/commands/doc, tools/bin/commands/release
This is a backport from the 1.2.x branch
=> feature: Reworked release command

doc/integrating_applications/topics/how_tooling_items_map.adoc, doc/shared/create_sf_connection.adoc, doc/shared/create_twitter_connection.adoc, doc/shared/register_with_sf.adoc, doc/tutorials/master-docinfo.xml, doc/tutorials/topics/sf2db_add_mapping_step.adoc, doc/tutorials/topics/sf2db_confirm_works.adoc, doc/tutorials/topics/sf2db_intro.adoc, doc/tutorials/topics/t2sf_add_mapping_step.adoc, doc/tutorials/topics/t2sf_choose_start.adoc, doc/tutorials/topics/t2sf_confirm_working.adoc, doc/tutorials/topics/t2sf_intro.adoc
This is ready to merge.  Updates are based on review comments. Thanks in advance.
=> Updates to tutorials based on comments from Michael Coker. For TP3 #921

app/integration/component-proxy/pom.xml, app/pom.xml, app/rest/syndesis-builder-image-generator/pom.xml, app/verifier/pom.xml
Cleans the dependencies in `syndesis-verifier` predominately and in `syndesis-builder-image-generator` and `component-proxy` as a result of excludiong commons-logging in the parent.
=> Dependency cleanup

app/ui/src/app/app.component.ts, app/ui/src/app/connections/create-page/connection-basics/connection-basics.component.ts, app/ui/src/app/connections/create-page/review/review.component.ts, app/ui/src/app/dashboard/dashboard.component.ts, app/ui/src/app/dashboard/emptystate.component.ts, app/ui/src/app/integrations/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/integrations/edit-page/action-select/action-select.component.ts, app/ui/src/app/integrations/edit-page/connection-select/connection-select.component.ts, app/ui/src/app/integrations/edit-page/flow-view/flow-view.component.ts, app/ui/src/app/integrations/edit-page/integration-basics/integration-basics.component.ts, app/ui/src/app/integrations/edit-page/save-or-add-step/save-or-add-step.component.ts, app/ui/src/app/integrations/list/list.component.html, app/ui/src/app/integrations/list/list.component.ts, app/ui/src/app/settings/oauth-apps/oauth-apps.component.ts
=> (fix) disable tour and fix list menu

app/deploy/generator/syndesis-template.go, tools/bin/commands/release, tools/ignite-cluster/migrate-images.pl
This is a backport from the 1.2.x branch
=> fix(release): Re-Add image migration script + update templates

app/ui/src/app/core/providers/form-factory-provider.service.ts
=> fix: turn off autocomplete for password fields

doc/sdh/cli/cmd_install.adoc, tools/bin/commands/install, tools/bin/commands/minishift, tools/bin/commands/util/openshift_funcs
for some reason that makes sense. use --yes if you do want to have it automatically.
=> fix(syndesis install): Add security question before deleting a project

app/extension/bom/pom.xml, app/extension/example/log-step/pom.xml, app/pom.xml, tools/bin/commands/release
+ some fixes related to missing data in extension poms
=> Backports from 1.2.x

project/DevelopersGuide.md
:notebook_with_decorative_cover:
=> Devguide, added api invocation from command line

app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/application.properties.mustache, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerate/application.properties
=> Reduce the number of spring-boot actuators endpoint on integration runtime

app/verifier/src/main/java/io/syndesis/verifier/impl/SqlVerifier.java
=> SQL verifier not being detected

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
=> UI, fix for empty collections and connectors

app/connectors/connector-verifier/pom.xml, app/connectors/connector-verifier/src/main/java/io/syndesis/verifier/api/SyndesisMetadata.java, app/connectors/connector-verifier/src/main/java/io/syndesis/verifier/api/support/SyndesisMetadataConverter.java, app/connectors/connector-verifier/src/test/java/io/syndesis/verifier/api/SyndesisMetadataTest.java, app/connectors/connector-verifier/src/test/java/io/syndesis/verifier/api/support/SyndesisMetadataConverterTest.java, app/connectors/connectors/sql/sql-common/pom.xml, app/connectors/connectors/sql/sql-common/src/main/java/io/syndesis/connector/sql/stored/JSONBeanUtil.java, app/pom.xml, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionActionHandler.java, app/verifier/pom.xml, app/verifier/src/test/java/io/syndesis/verifier/v1/metadata/SqlMetadataAdapterTest.java, app/verifier/src/test/resources/sql/demo_add_metadata.json, app/verifier/src/test/resources/sql/name_sql_metadata.json
You might want to look at #1359 if it's merged first.
=> Backport fix for #1295 to 1.2.x

app/ui/src/app/config.service.ts
fixes #1010 for TP3
@rhuss FYI
=> fix: ensure options that have a  default value don't cause errors

.circleci/config.yml, app/ui/package.json, app/ui/pom.xml, app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.spec.ts, app/ui/src/app/config.service.spec.ts, app/ui/src/app/connections/list/list.component.spec.ts, app/ui/src/app/core/providers/user-provider.service.spec.ts, app/ui/src/app/dashboard/dashboard.component.spec.ts, app/ui/src/app/integration/edit-page/current-flow.service.spec.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.spec.ts, app/ui/yarn.lock
=> fix: enable lint and tests for CI

README.md, tools/bin/commands/build, tools/bin/commands/dev, tools/bin/commands/install, tools/bin/commands/minishift, tools/bin/commands/util/maven_funcs, tools/bin/commands/util/openshift_funcs
if oc is not found in the path, but minishift. Also updated README
to refer to the doc.syndsis.io + a super short quickstart.
=> feature(syndesis minishift): Pick up oc from minishift

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
=> fix: avoid npe when checking response

doc/integrating_applications/topics/about_connection_validation.adoc, doc/integrating_applications/topics/about_creating_connections.adoc, doc/integrating_applications/topics/map_one_source_field_to_one_target_field.adoc, doc/integrating_applications/topics/overview_of_creating_connections.adoc, doc/integrating_applications/topics/viewing_and_editing_connection_information.adoc
This is ready to merge. It adds doc for viewing, editing and validating connections. Zoran reviewed the new doc. This will be the last chunk of doc for TP3. ccutil runs successfully on both books.
=> Added doc about validating, viewing, editing connections. For TP3 #921.

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.spec.ts, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
Mind that to have the unit test to compile, I have copied code desperately here and here, so that test module configuration part is  a mess.
Also, @gashcrumb , you might want to add further input cases
fixes #1371
=> UI, empty collections bug

app/connectors/connectors/sql/sql-common/src/main/java/io/syndesis/connector/sql/SqlStatementMetaData.java
issue https://github.com/syndesisio/syndesis/issues/1346
=> User should be able to use lowercase table names

app/pom.xml
wip until circleci could resolve 1.33.1 artifacts
=> chore: Update atlasmap to 1.33.1

app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
=> chore: Add Action with input/output DataShape for datamapper step

app/ui/src/app/integration/detail-page/detail.component.html, app/ui/src/app/integration/detail-page/detail.component.ts, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/integration/integration-actions-provider.service.ts, app/ui/src/app/integration/integration-support-provider.service.ts, app/ui/src/app/platform/types/integration/integration-actions.service.ts, app/ui/src/app/platform/types/integration/integration-support.service.ts, app/ui/src/app/platform/types/integration/integration.models.ts, app/ui/src/app/store/entity/entity.store.ts, app/ui/src/app/store/entity/rest.service.ts
This gets the deployment table back and wires up some actions but I've a few questions, so opening this up as a WIP PR...
fixes #1461 
fixes #1263 
fixes #242
related to #1069
=> Add back in deployment table, wire up some actions

app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
From issue https://github.com/syndesisio/syndesis/issues/1246, editing the integration name doesn't match PF's inline edit interaction. Attempting to bring it closer to that pattern.
=> update editing the integration name to match PF pattern

app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java
=> [Extension] If more than a single extension is used, the integration fails to start

app/connectors/connectors/sql/src/main/resources/META-INF/syndesis/connector/sql.json, app/connectors/connectors/twitter-connector/src/main/resources/META-INF/syndesis/connector/twitter.json, app/rest/dao/src/main/resources/io/syndesis/dao/deployment.json, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html, app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.ts, app/ui/src/app/integration/integration-actions-provider.service.ts, app/ui/src/app/settings/oauth-apps/oauth-app-form.component.html, app/ui/src/app/store/step/step.store.ts
I think I managed to get all of the text from #1519 updated, @michael-coker and @TovaCohen can you take a look?
Fixes #1519
=> fix: Spelling and grammatical errors

app/ui/src/app/integration/edit-page/connection-select/connection-select.component.html, app/ui/src/app/integration/edit-page/connection-select/connection-select.component.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts
=> fix: filter connections by position in flow for connection select pages

app/connectors/connectors/sql/src/main/resources/META-INF/syndesis/connector/sql.json
Fixes additional spelling and grammatical errors.
Fixes #1519
=> fix: Spelling and grammatical errors (II)

app/connectors/connectors-catalog/pom.xml, app/connectors/connectors/ftp/ftp-connector/pom.xml, app/connectors/connectors/ftp/ftp-connector/src/main/java/io/syndesis/connector/ftp/FtpVerifier.java, app/connectors/connectors/ftp/ftp-connector/src/main/java/io/syndesis/connector/ftp/FtpVerifierAutoConfiguration.java, app/connectors/connectors/ftp/ftp-connector/src/main/java/io/syndesis/connector/ftp/FtpVerifierExtension.java, app/connectors/connectors/ftp/ftp-connector/src/main/resources/META-INF/spring.factories, app/connectors/connectors/ftp/ftp-connector/src/main/resources/META-INF/syndesis/connector/ftp.json, app/connectors/connectors/ftp/ftp-connector/src/main/resources/META-INF/syndesis/connector/verifier/ftp, app/connectors/connectors/ftp/pom.xml, app/connectors/connectors/ftp/sftp-connector/pom.xml, app/connectors/connectors/ftp/sftp-connector/src/main/java/io/syndesis/connector/sftp/SftpVerifier.java, app/connectors/connectors/ftp/sftp-connector/src/main/java/io/syndesis/connector/sftp/SftpVerifierAutoConfiguration.java, app/connectors/connectors/ftp/sftp-connector/src/main/java/io/syndesis/connector/sftp/SftpVerifierExtension.java, app/connectors/connectors/ftp/sftp-connector/src/main/resources/META-INF/spring.factories, app/connectors/connectors/ftp/sftp-connector/src/main/resources/META-INF/syndesis/connector/sftp.json, app/connectors/connectors/ftp/sftp-connector/src/main/resources/META-INF/syndesis/connector/verifier/sftp, app/connectors/pom.xml, app/rest/dao/src/test/java/io/syndesis/dao/DataManagerTest.java, app/verifier/pom.xml
=> fix: FTP and SFTP connectors

doc/tutorials/topics/amq2api_confirm_works.adoc, doc/tutorials/topics/amq2api_create_custom_step.adoc, doc/tutorials/topics/amq2api_intro.adoc, doc/tutorials/topics/amq2api_upload_todo_app_icon.adoc, doc/tutorials/topics/comparison_of_sample_integrations.adoc
This content has been reviewed. ccutil runs successfully. 
This is ready to merge and then I can bring it downstream to stage the documents for TP3. 
Thanks in advance!
=> Updates to new tutorial based on feedback from David. #921

app/connectors/connectors/sql/src/main/resources/META-INF/syndesis/connector/sql.json, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-auth/api-connector-auth.component.html, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html, app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.html, app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.html
Updates API connector wizard titles and fixes additional spelling errors.
Fixes #1519 #1561
=> fix(ui): Correct the labels for the main steps for creating an API connector

app/ui/src/app/integration/detail-page/detail.component.ts, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.spec.ts, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/integration/edit-page/action-select/action-select.component.html, app/ui/src/app/integration/edit-page/action-select/action-select.component.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts, app/ui/src/app/platform/types/platform.models.ts
=> fix: store fetched data shapes on steps, related cleanup

app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/support/SupportUtil.java
Note that the semantics are different
=> Support, restore correct code after wrong checkstyle lead modification

app/connectors/connectors/sql/src/main/java/io/syndesis/connector/sql/common/DatabaseMetaDataHelper.java, app/rest/controllers/src/main/java/io/syndesis/controllers/integration/online/OnlineHandlerProvider.java, app/rest/controllers/src/main/java/io/syndesis/controllers/integration/online/PublishHandler.java, app/rest/controllers/src/main/java/io/syndesis/controllers/integration/online/UnpublishHandler.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/integration/IntegrationHandler.java
This pull request tries to address the inconsistent data that are stored in the DB. For example:
1. multiple published deployments.
2. integration version not matching with the actual deployment version.
3. inconsistency between db and ui.
and so on...
Big part of the problem is that certain assumptions have been made that aren't somehow enforced and are do not reflect the way things work.
This PR does not modify the behavior, it just removes these assumptions, which doesn't offer anything and make things fragile.
=> Lifecycle fixes

app/ui/src/app/common/ui-patternfly/ui-patternfly.module.ts, app/ui/src/app/support/support.component.html, app/ui/src/app/support/support.component.scss, app/ui/src/app/support/support.component.ts, app/ui/src/app/vendor/vendor.module.ts
fixes  #334,  #1288
@michael-coker   I might use your help in aligning the spinner and the notification box
=> Support, incorporated feedback from UX

app/ui/src/app/support/support.component.html, app/ui/src/app/support/support.component.scss, app/ui/src/app/support/support.component.ts
=> Support, improved alignment and integration loading logic

app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts, app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
A demo for #700 until design is finalized
=> chore: Show DataShape name and mismatch indicator in tooltip

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
=> fix: don't automatically transition out of action config if there's no config

app/pom.xml, app/ui/package.json, app/ui/yarn.lock
which contains a fix for atlasmap/atlasmap#290
=> chore: Update to atlasmap-1.33.4

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/describe-data/describe-data.component.html, app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts, app/ui/src/app/integration/edit-page/describe-data/index.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integration/edit-page/index.ts, app/ui/src/app/integration/integration.module.ts, app/ui/src/app/platform/types/platform.models.ts
Initial impl for #1229 
No file upload or fetch from URL, form is driven from the data shape object.
@igarashitm FYI
=> feat: add describe data page to editor page flow

tools/bin/commands/minishift
No more need to add the delegator role "add_auth_delegator_role"
=> No need to add delegator role

app/ui/src/app/support/support.component.html
https://github.com/syndesisio/syndesis/issues/1617
=> Adding ID to syndesis version paragraph

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts, app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
Fixes #1614 
Fixes #1578 
@paoloantinori FYI
=> fix: tidy up setting actions vs descriptors vs data shapes

doc/tutorials/topics/amq2api_add_damage_reporter_step.adoc, doc/tutorials/topics/amq2api_confirm_works.adoc
This is ready to merge. David reviewed these last two updates to the third tutorial. This is the last merge for TP3. Thanks in advance for approving it.
=> Two small updates to AMQ-REST-API tutorial. That's it for TP3. #921

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
match the look and feel of the other editor workflow steps.
=> bring layout for actions with no configurable properties inline with rest of editor workflow

app/ui/src/scss/README.md
As more developers join the project, some organization and reference guidance seems to be required.
No project without a firm architecture has ever succeded in the history of software craftmanship. Never, ever.
=> chore: formalized the CSS architecture in a README

app/ui/package.json, app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts, app/ui/yarn.lock
Show error message when initialization fails (#1621)
=> fix: Better error handling on datamapper initialization

app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.ts, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.ts, app/ui/src/app/integration/import-export/import/integration-import.component.html, app/ui/src/app/integration/import-export/import/integration-import.component.ts, app/ui/src/app/integration/import-export/import/integration-import.models.ts, app/ui/src/app/integration/import-export/import/integration-import.module.ts, app/ui/src/app/integration/import-export/integration-import-export.component.html, app/ui/src/app/integration/import-export/integration-import-export.module.ts
cc @chirino This is the latest. Will resolve lint issues shortly and add aesthetic changes. fix #1153 Only a WIP because of the lint issues, as the feature works fine. 
Redux architecture is mostly set up, though not 100% correct, but not in use due to prioritizing for the demo. This is another thing I will open up a separate issue for. I didn't remove it because I don't it to get lost on another branch and a lot of work went into it, so it will be done pretty soon. Thanks!
=> Import Single Integrations

app/core/model/src/main/java/io/syndesis/model/DataShapeKinds.java, app/core/model/src/main/java/io/syndesis/model/Kind.java, app/core/model/src/main/java/io/syndesis/model/buletin/ConnectionBulletinBoard.java, app/core/model/src/main/java/io/syndesis/model/buletin/IntegrationBulletinBoard.java, app/core/model/src/main/java/io/syndesis/model/buletin/LeveledMessage.java, app/rest/dao/src/main/java/io/syndesis/dao/ConnectionBulletinBoardDao.java, app/rest/dao/src/main/java/io/syndesis/dao/IntegrationBulletinBoardDao.java, app/rest/dao/src/main/java/io/syndesis/dao/manager/DataAccessObject.java, app/rest/dao/src/main/java/io/syndesis/dao/manager/DataManager.java, app/rest/jsondb/src/main/java/io/syndesis/jsondb/dao/JsonDbDao.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionHandler.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/integration/IntegrationHandler.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/integration/model/IntegrationOverview.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/integration/support/IntegrationSupportHandler.java
We now validate connections and if any of it’s properties are null, we post a buletin.
=> feat: Support storing bulletins of messages associated with integrations and connections.  Part of issues #1052

app/ui/src/app/integration/import-export/import/integration-import.component.html
=> Support for multiple file import

app/ui/src/app/platform/types/integration/integration.effects.ts
=> fix: avoid npe in detail page after publishing

tools/bin/commands/system-test
Sets proper Maven profiles for system tests.
=> fix(build): system-test needs to use flash,image

app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html
=> fix: delete button removed for custom connectors in API Client Connectors Page

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
A request from @kcbabo in https://github.com/syndesisio/syndesis/issues/1672
Got feedback and sign-off from @amysueg and @dongniwang
=> decrease vertical space between steps in the integration editor left sidebar

app/ui/package.json, app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts, app/ui/yarn.lock
=> chore: Show source documents collapsed if there're multiple

app/connectors/connectors/ftp/ftp-connector/src/main/resources/META-INF/syndesis/connector/ftp.json, app/connectors/connectors/ftp/sftp-connector/src/main/resources/META-INF/syndesis/connector/sftp.json
=> FTP connector: datashape definition display errors in UI

app/core/model/src/main/java/io/syndesis/model/Ordered.java, app/core/model/src/main/java/io/syndesis/model/connection/ConfigurationProperty.java, app/core/model/src/test/java/io/syndesis/model/connection/OrderedConfigurationPropertiesTest.java
=> Add 'order' attribute alongside connector form definitions

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/describe-data/describe-data.component.html, app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts
=> (fix) rework button text across pages

app/ui/src/app/common/ui-patternfly/duration-form-control.component.html
=> (chore) Add id to duration select field

app/ui/src/app/integration/integration_detail/integration-detail.component.html, app/ui/src/app/platform/types/integration/integration.models.ts
=> (chore) add support for showing messages field from an integration

app/connectors/connectors/sql/src/main/resources/META-INF/syndesis/connector/sql.json, app/connectors/connectors/sql/src/test/java/io/syndesis/connector/sql/stored/SqlStoredConnectorWitDefaultsTest.java, app/connectors/connectors/sql/src/test/java/io/syndesis/connector/sql/util/SqlConnectorTestSupport.java, app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java, app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGeneratorHelper.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/ConnectorStepHandler.java
=> NPE in DB2StoredProc Integration

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
=> fix: bring back mouseover tooltip in collapsed IVP

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.spec.ts, app/ui/src/app/integration/edit-page/current-flow.service.spec.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.spec.ts, app/ui/src/app/store/step/step.store.ts
=> feat: add a link that creates a datamapper step in front of whatever step has a mismatch indicator

app/ui/src/app/dashboard/dashboard.component.scss, app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.html, app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.scss, app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.ts, app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html, app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.scss, app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.html, app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.scss, app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.ts
Fixes https://github.com/syndesisio/syndesis/issues/1716
General approvements to the UI from the UXD design team, and some structural markup changes.
@seanforyou23
=> Dashboard UI improvements

app/connectors/connectors-catalog/pom.xml, app/connectors/connectors/mqtt/pom.xml, app/connectors/connectors/mqtt/src/main/java/io/syndesis/connector/mqtt/MqttVerifier.java, app/connectors/connectors/mqtt/src/main/java/io/syndesis/connector/mqtt/MqttVerifierAutoConfiguration.java, app/connectors/connectors/mqtt/src/main/java/io/syndesis/connector/mqtt/MqttVerifierExtension.java, app/connectors/connectors/mqtt/src/main/resources/META-INF/spring.factories, app/connectors/connectors/mqtt/src/main/resources/META-INF/syndesis/connector/mqtt.json, app/connectors/connectors/mqtt/src/main/resources/META-INF/syndesis/connector/verifier/paho, app/connectors/pom.xml, app/rest/dao/src/test/java/io/syndesis/dao/DataManagerTest.java, app/verifier/pom.xml
=> fix: MQTT Connector

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationSchedulerTest.java
=> DataBuckets exception - Incompatible Source Document 'null'

tools/bin/commands/minishift, tools/bin/syndesis
=> Scripts, added logging

app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
fixes #1744 and a yet undiscovered sekret NPE
@lburgazzoli FYI
=> fix: I suppose people want to add steps sometimes

app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts
=> chore: update field labels a bit for #1229

app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
=> chore: add link to previous step's describe output data shape page for shapeless thingies

app/ui/src/app/integration/integration_detail/integration-detail.component.scss, app/ui/src/app/integration/integration_detail/integration-history.component.scss
Fixes https://github.com/syndesisio/syndesis/issues/1774
* Fix alignment issue with checkbox in history tab list
* design for reference https://github.com/syndesisio/syndesis/blob/master/ux/designs/integration_details/integration_details_page.md
* Remove scrollbar from title area
=> Integration details UI

app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java
Adds a simple prefix (`i-`) to builds, deployment configurations, pods and secrets so the user provided integration name doesn't collide with any of the platform resource names.
Fixes #1438
=> chore(openshift): prefix to openshift resources

app/connectors/connectors/sql/src/test/java/io/syndesis/connector/sql/common/SqlConnectionRule.java
Hopefully fixing issue https://github.com/syndesisio/syndesis/issues/1769 for good.
=> fix: adding close statements

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
Fixes https://github.com/syndesisio/syndesis/issues/1792
=> align step name/icon, add title attribute for long/truncated step names

app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts
=> chore: use new relation support to disable the specification, name and description field

app/server/jsondb/src/test/java/io/syndesis/server/jsondb/impl/JsonDBTest.java
=> fix(jsondb): use in-memory database for tests

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/integration/edit-page/action-select/action-select.component.html, app/ui/src/app/integration/edit-page/action-select/action-select.component.ts, app/ui/src/app/integration/edit-page/connection-select/connection-select.component.html, app/ui/src/app/integration/edit-page/connection-select/connection-select.component.ts, app/ui/src/app/integration/edit-page/describe-data/describe-data.component.html, app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts, app/ui/src/app/integration/edit-page/edit-page.component.scss, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss, app/ui/src/app/integration/edit-page/integration-basics/integration-basics.component.html, app/ui/src/app/integration/edit-page/integration-basics/integration-basics.component.ts, app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.html, app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.ts, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts, app/ui/src/app/integration/edit-page/step-select/step-select.component.html, app/ui/src/app/integration/edit-page/step-select/step-select.component.ts, app/ui/src/app/integration/integration-common-toolbar.scss, app/ui/src/app/integration/integration-common.scss, app/ui/src/app/integration/integration_detail/integration-detail.component.html, app/ui/src/app/integration/integration_detail/integration-detail.component.scss, app/ui/src/app/integration/integration_detail/integration-detail.component.ts, app/ui/src/scss/base/_mixins.scss, app/ui/src/scss/utils/_helpers.scss
fixes https://github.com/syndesisio/syndesis/issues/1802 and https://github.com/syndesisio/syndesis/issues/1470
=> general improvements to integration UI, add mixin/helper class for toolbar

app/ui/src/app/integration/list/status.component.ts
Fixes https://github.com/syndesisio/syndesis/issues/1710
=> When publishing an integration, change pending state wording from "in progress" to "publishing"

app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
=> fix: ensure the start/finish step indices update properly

app/server/runtime/pom.xml
=> fix(runtime): reintroduce H2 as runtime dependency

app/server/logging/jsondb/pom.xml, app/server/metrics/jsondb/pom.xml, app/server/metrics/prometheus/pom.xml
Fix relative parent locations - I'm getting errors building the snapshot without these fixes.
https://fusesource-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/ipaas-tp4/27/console
=> Fix relative parent locations.

app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html
=> fix: debugger tracer element removed

app/ui/src/app/integration/integration_detail/integration-description.component.html, app/ui/src/app/integration/integration_detail/integration-description.component.scss, app/ui/src/app/integration/integration_detail/integration-detail.component.html
fixes https://github.com/syndesisio/syndesis/issues/1860
=> updates to integration details panel and tab name

app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackVerifier.java, app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackVerifierAutoConfiguration.java, app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackVerifierExtension.java, app/connector/slack/src/main/resources/META-INF/spring.factories, app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json, app/meta/pom.xml
=> feat(connector): Added Slack Verifier

app/ui/src/app/platform/types/integration/integration.effects.ts
Fixes #1824 
Behold the beauty of Redux, humans! Now it just takes a simple line to readapt an entire application data consumption logic after a relevant change in the API response schema.
=> fix: integration monitoring metrics updated to reflect new API response schema

app/ui/src/app/integration/integration_detail/integration-detail.component.html, app/ui/src/app/integration/integration_detail/integration-detail.component.ts
=> fix: rework integration renaming, remove toast popup

app/ui/src/app/integration/import-export/import/integration-import.component.html, app/ui/src/app/integration/import-export/import/integration-import.component.scss, app/ui/src/app/integration/import-export/import/integration-import.component.ts, app/ui/src/app/integration/import-export/import/integration-import.models.ts
Implements the Review page and other Import/Export additional features.
fix #1646
=> Import/Export UI: Review, Redirect

app/connector/sql/src/main/java/io/syndesis/connector/sql/common/JSONBeanUtil.java
Previous fix did not completely solve #1923.
=> fix: filter null keys and values before adding them to the properties.

app/ui/src/app/common/common.module.ts, app/ui/src/app/common/duration-diff.pipe.ts, app/ui/src/app/common/duration.pipe.ts, app/ui/src/app/common/index.ts, app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.html, app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.spec.ts, app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.html, app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.ts, app/ui/src/app/integration/integration_detail/integration-metrics.component.html, app/ui/src/app/platform/types/integration/integration.models.ts
=> feature: integration activity steps logs

app/ui/src/app/integration/integration-actions-provider.service.ts, app/ui/src/app/integration/integration_detail/integration-detail.component.ts, app/ui/src/app/integration/list/action-menu.component.ts
fixes https://github.com/syndesisio/syndesis/issues/1909
=> Replace instances of activate/deactivate with publish/unpublish

app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
=> fix: prefer the step name over prettifying the step kind

app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DatabaseMetaDataHelper.java
https://github.com/syndesisio/syndesis/issues/1769
=> fix: Closing resultSets explicitly

app/extension/maven-plugin/pom.xml, app/server/builder/maven-plugin/pom.xml
I tried importing the project to eclipse and it goes crazy over these. So let's add them to keep everyone happy.
=> feat: add missing goals from plugin execution phases.

app/ui/src/app/integration/edit-page/current-flow.service.ts
came out of discussion in #1961
=> fix: reset the data shape if the incoming type is kind=none

app/connector/sql/src/main/java/io/syndesis/connector/sql/common/SqlStatementParser.java, app/connector/sql/src/test/java/io/syndesis/connector/sql/common/SqlParserTest.java, app/connector/sql/src/test/resources/test-options.properties
=> fix: support for lowercase SQL #1853

app/ui/src/app/connections/detail-page/breadcrumb.component.ts, app/ui/src/scss/base/_mixins.scss, app/ui/src/scss/utils/_helpers.scss
fixes https://github.com/syndesisio/syndesis/issues/1968
=> Update connection details toolbarUI

app/connector/ftp/src/main/resources/META-INF/syndesis/connector/ftp.json, app/connector/sftp/src/main/resources/META-INF/syndesis/connector/sftp.json
=> SFTP and FTP descriptions

app/ui/src/app/common/duration.pipe.ts, app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.html, app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.ts
=> fix(monitoring): Duration formatting fixed for Integration activity logs

app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java
=> Extension input labels using description

app/ui/src/app/api/providers/api-http-provider.service.ts, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/platform/types/platform.models.ts
=> fix: ensure the error response can make it back to the requesting code

.github/ISSUE_TEMPLATE.md
=> chore: add req/resp section to issue template

app/ui/src/app/integration/list/status.component.ts
Relates to issue discussed in #1982
=> fix: show a more specific action when the state changes

app/ui/src/app/connections/list/list.component.html, app/ui/src/app/integration/edit-page/connection-select/connection-select.component.html
fixes https://github.com/syndesisio/syndesis/issues/255
=> update wording on start/finish connection steps

app/pom.xml
=> fix(connectors): Duplicate version declarations in "slack connector"

app/ui/src/app/connections/create-page/create-page.component.html
fixes https://github.com/syndesisio/syndesis/issues/256
=> change "select connection type" to "select connector"

tools/bin/commands/release
and don't revert back to snapshots as this is not pushed anyway.
=> fix: Proper commit of pom.xml files

app/meta/src/main/fabric8-includes/run-env.sh
and supports spaces in file names
=> fix(meta): set-env.sh works now also with -e

app/ui/src/app/settings/settings-root.component.html
fixes https://github.com/syndesisio/syndesis/issues/258
=> remove tab from settings page

app/ui/src/app/connections/create-page/current-connection.ts, app/ui/src/app/connections/detail-page/info.component.ts
=> fix: remove connection tags and don't set them

app/pom.xml
=> chore: Update Fabric8 Maven Plugin to version 3.5.38

app/ui/.angular-cli.json
fixes #1445 (sorta in a doesn't fix it but hide it kinda way)
=> chore: suppress circular reference warnings

app/ui/src/app/connections/create-page/create-page.component.html, app/ui/src/app/connections/create-page/create-page.component.ts, app/ui/src/app/connections/create-page/current-connection.ts, app/ui/src/app/connections/create-page/review/review.component.ts
=> fix: disable create button when the review form is invalid, suppress duplicate clicks too

app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html
fixes https://github.com/syndesisio/syndesis/issues/1988
and is dependent upon this PR from the atlasmap repo https://github.com/atlasmap/atlasmap/pull/350
=> Fix overflow issues on data mapper page

app/ui/src/app/settings/oauth-apps/oauth-apps.component.html, app/ui/src/app/settings/oauth-apps/oauth-apps.component.ts
fixes https://github.com/syndesisio/syndesis/issues/214
=> update settings description, add callback url

app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/PodLogMonitor.java, app/server/logging/jsondb/src/test/resources/logs-controller-db.json, app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.html, app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.scss, app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.ts
(cherry picked from commit 87f6843d508c3e21481a9e4919861bd0c6305995)
=> fix: Order steps in the activity view fix: Don’t show error on log messages fix: use pre formatting for step output

app/ui/src/app/settings/oauth-apps/oauth-apps.component.html, app/ui/src/app/settings/oauth-apps/oauth-apps.component.scss
fixes https://github.com/syndesisio/syndesis/issues/2046
=> clean up settings page markup/css, remove persistent scrollbar

app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
=> fix: set mapping config the same way we set other configured properties

install/generator/04-syndesis-db.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml
=> fix: syndesis-db never comes up again on restart #2057

app/ui/src/app/integration/list/action-menu.component.ts
fixes https://github.com/syndesisio/syndesis/issues/1994
=> move "export" from kebab to a toolbar button on integration details page

app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html
=> fix: dynamic select inputs will be disabled when configured as read only

app/ui/src/app/customizations/api-connector/api-connector.effects.ts
=> fix: Redux effect will refresh Custom API Connectors graph upon Integration status update

app/ui/src/app/integration/edit-page/action-select/action-select.component.ts
Reverts syndesisio/syndesis#2053
Given that this has created #2071 #2062 
fixes #2062 
relates to #1993
=> Revert "feat: action filtering now takes into consideration output data shape…"

app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html, app/ui/src/app/common/ui-patternfly/syndesis-form-control.scss, app/ui/src/app/integration/list/action-menu.component.ts, install/generator/04-syndesis-db.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml
Fixes https://github.com/syndesisio/syndesis/issues/1817 but we still need to re-order the form fields so that a username row comes before the password row.
cc @seanforyou23
=> Hide syndesis-form-control rows that have a hidden input field, remove padding from read-only input/textarea

app/ui/src/app/settings/oauth-apps/oauth-app-form.component.html, app/ui/src/app/settings/oauth-apps/oauth-apps.component.html
* add a period to the success message
* enable clicking on the row to expand it
* fix save/cancel button alignment in smaller screens
fixes https://github.com/syndesisio/syndesis/issues/1248
=> Settings page UI improvements

tools/bin/commands/install, tools/bin/commands/minishift, tools/bin/commands/util/openshift_funcs
This would make QE's lives a little bit easier.
=> Add --test-support option to syndesis install scripts

doc/sdh/cli/cmd_install.adoc, doc/sdh/cli/cmd_minishift.adoc, tools/bin/commands/install, tools/bin/commands/minishift
@rhuss, in https://github.com/syndesisio/syndesis/pull/2077#issuecomment-374538562 I think these are valid points, so I updated the docs and removed the "-s" param
=> chore: Add install scripts docs

doc/sdh/cli/cmd_install.adoc, tools/bin/commands/install, tools/bin/commands/util/openshift_funcs, tools/bin/install-syndesis
- Just add detect route if not provided as argument
- Added it to "syndesis install", too (not only the standalone install  script)
- Added error handling
- Update documentation
=> chore: Refinement of route detection

app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java
=> Fixes #2075: override dependencies from bom if present in extension json

app/server/docs/design/datamapper.md
=> chore: Add datamapper doc

app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.component.html
=> fix: (integrations) initial basic filter condition can now be deleted if there's more than one

app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
=> fix: Setting the default period to 1 minute

app/ui/src/app/connections/create-page/current-connection.ts
=> fix: protect against missing properties object when creating a connection

app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html, app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.ts, app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.component.html, app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.model.ts, app/ui/src/app/integration/edit-page/step-configure/filter-steps/filter.interface.ts
fixes https://github.com/syndesisio/syndesis/issues/2091
cc @seanforyou23
=> Basic filter UI updates

app/connector/odata/create-entity/src/main/resources/camel-connector.json, app/connector/odata/delete-entity/src/main/resources/camel-connector.json, app/connector/odata/replace-entity/src/main/resources/camel-connector.json, app/connector/odata/retrieve-entity/src/main/resources/camel-connector.json, app/connector/odata/update-entity/src/main/resources/camel-connector.json, app/connector/rest-swagger/src/main/resources/camel-connector.json, app/extension/bom/pom.xml, app/integration/pom.xml, app/pom.xml
=> Upgrade Camel to version 2.21.0

app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html
=> fix: always use done on the step config page

app/ui/src/app/integration/list-page/list-page.component.html, app/ui/src/app/integration/list-page/list-page.component.scss
fixes https://github.com/syndesisio/syndesis/issues/2118
=> clean up integration list CSS including making body scrollable, fix padding issue in firefox

app/ui/src/app/integration/import-export/import/integration-import.component.html, app/ui/src/app/integration/import-export/import/integration-import.component.ts
- Review page now populating data for both single and multiple imported integrations.
- Redirect to Integration list page for multiple imports and to the detail page for single imports.
- Resolves conflicts between drag and drop and file select vs multiple and single imports.
- Do not auto redirect on upload, even for multiple the user will have to select the 'Done' button for consistency. The buttons will not appear until the user has successfully uploaded a file.
Please note that there are a few minor things missing that will come in much smaller, separate PRs.
- Need to determine how/when to display 'Configuration Required' for Connections within Integrations, as I don't get validation information from `/v1/integration-support`. Is it just if the name is missing, or do I need …
=> Adds review step for import/export in the UI, fixes conflicts

app/ui/src/app/connections/create-page/current-connection.ts
=> fix: set the connectorId when creating a connection

app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html, app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.scss, app/ui/src/app/customizations/customizations.component.html, app/ui/src/app/customizations/customizations.component.scss, app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html, app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.scss
fixes https://github.com/syndesisio/syndesis/issues/2129
=> Customizations body scrollable

app/ui/src/app/integration/integration_detail/integration-detail.component.html, app/ui/src/app/integration/integration_detail/integration-detail.component.scss
fixes https://github.com/syndesisio/syndesis/issues/2142
=> Make toolbar on integration details page fixed with content below it scrollable

app/ui/src/app/integration/integration_detail/integration-detail.component.html, app/ui/src/app/integration/integration_detail/integration-detail.component.scss
fixes https://github.com/syndesisio/syndesis/issues/2147
=> Message area overlaid with tabs on integration detail page

checkstyle.xml, ruleset.xml
=> chore: checkstyle task about NewlineAtEndOfFile and FileTabcharacter

doc/integrating_applications/topics/about_extensions.adoc, doc/integrating_applications/topics/adding_extensions.adoc, doc/integrating_applications/topics/connecting_to_databases.adoc, doc/integrating_applications/topics/connecting_to_proprietary_databases.adoc, doc/integrating_applications/topics/create_database_connection.adoc, doc/integrating_applications/topics/creating_connections_from_custom_connectors.adoc, doc/integrating_applications/topics/creating_jdbc_driver_library_extensions.adoc, doc/integrating_applications/topics/making_extensions_available.adoc, doc/integrating_applications/topics/obtaining_authorization_to_access_applications.adoc
@KurtStam, I'm going to ask you to review this. The more recent of the two commits in this PR contains all the updates for documenting the JDBC driver library extensions. Previously, I have not asked for a user doc review in this interface because you will be reviewing asciidoc source, and I am not sure that is the best way to review user doc. So if you prefer, you can immediately approve this PR and then after it is merged upstream, I will bring it downstream and point you to the new doc in the format that the book will have in the customer portal, and you can review that. 
The earlier commit contains updates that Luca already reviewed.
=> 1623 03232018 New user doc for JDBC driver library extensions

app/connector/dropbox/pom.xml, app/connector/dropbox/src/main/resources/META-INF/syndesis/connector/dropbox.json
I fixed two typos and change the wording of a hint. 
Hope I did this right!
=> fix: Changed two instances of DropBox to Dropbox. Clarified a field hint. 

app/ui/src/app/api/providers/api-http-provider.service.ts, app/ui/src/app/core/providers/integration-support-provider.service.ts
=> fix: use remaining parameters as query params when building URLs

doc/integrating_applications/topics/about_mapping_data.adoc, doc/integrating_applications/topics/connecting_to_databases.adoc, doc/integrating_applications/topics/connecting_to_proprietary_databases.adoc, doc/integrating_applications/topics/creating_jdbc_driver_library_extensions.adoc, doc/integrating_applications/topics/finding_data_field_you_want_to_map.adoc
This is ready to merge. Each update has already been reviewed and approved.
=> User doc updates based on reviews of data mapper doc and proprietary DB wording

app/ui/src/app/integration/list/list.component.html
=> feat: show config required indicator on integration list if an integration has messages

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java
=> fix(endpoint): include board when fetching connection by id

doc/integrating_applications/topics/adding_dropbox_connection_finish.adoc, doc/integrating_applications/topics/adding_dropbox_connection_middle.adoc, doc/integrating_applications/topics/adding_dropbox_connection_start.adoc
This is ready to merge. It's all been reviewed. I thought I already pushed this. *Sigh*
=> user doc: Updates that I thought I pushed, but apparently I didn't (1623)

app/ui/src/app/core/providers/integration-support-provider.service.ts, app/ui/src/app/integration/integration_detail/integration_activity/integration-activity.component.ts
=> fix(monitoring): activity names fetched from integration deployments

app/server/dao/src/main/java/io/syndesis/server/dao/manager/DataManager.java, app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java, app/server/runtime/pom.xml, app/server/runtime/src/test/java/io/syndesis/server/runtime/DataManagerITCase.java
Serverside check to make sure the name does not exists
=> fix: Able to create duplicate connections #1538

app/ui/src/app/integration/integration_detail/integration-detail.component.html, app/ui/src/app/integration/integration_detail/integration-detail.component.ts
=> fix: tabs in the integration detail page can now be hotlinked

doc/integrating_applications/topics/adding_ftp_connections.adoc, doc/integrating_applications/topics/connecting_to_applications.adoc, doc/integrating_applications/topics/connecting_to_ftp.adoc, doc/integrating_applications/topics/creating_ftp_connections.adoc, doc/shared/specifying_connection_input_output_types.adoc
This is ready to merge.  I'm planning to approve it myself (Paolo says I can!) so I can move it along and get it downstream. Luca will review the content next week.
=> User doc for FTP and SFTP connectors

doc/integrating_applications/topics/adding_http_connections.adoc, doc/integrating_applications/topics/adding_slack_connections.adoc, doc/integrating_applications/topics/available_transformations.adoc, doc/integrating_applications/topics/connecting_to_applications.adoc, doc/integrating_applications/topics/connecting_to_http.adoc, doc/integrating_applications/topics/connecting_to_slack.adoc, doc/integrating_applications/topics/create_amq_connection.adoc, doc/integrating_applications/topics/create_amqp_connection.adoc, doc/integrating_applications/topics/creating_ftp_connections.adoc, doc/integrating_applications/topics/creating_http_connections.adoc, doc/integrating_applications/topics/creating_jdbc_driver_library_extensions.adoc, doc/integrating_applications/topics/creating_slack_connections.adoc, doc/integrating_applications/topics/making_extensions_available.adoc, doc/integrating_applications/topics/register_with_dropbox.adoc, doc/shared/create_sf_connection.adoc, doc/tutorials/topics/amq2api_create_custom_step.adoc
This is ready to merge. I need to bring it downstream so it will be in the TP4 doc. Thanks in advance for making sure this merges!
=> New doc for HTTP/S and Slack connectors and some other updates

app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.html
=> fix: align active deployment status with integration status

app/connector/ftp/src/main/resources/META-INF/syndesis/connector/ftp.json
I corrected some typos, and updated display names and hints. If these updates are approved then I'll also update the SFTP json file.
=> user doc: FTP connector, fix typos and update text hints and labels.

app/pom.xml, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/atlas/SyndesisJavaService.java, app/ui/package.json, app/ui/yarn.lock
=> chore: Update AtlasMap to 1.34.0

app/connector/sftp/src/main/resources/META-INF/syndesis/connector/sftp.json
I updated the json file for the SFTP connector in the same way that I updated the json file for the FTP connector. Someone should review this to make sure I did not introduce any typos or incorrect information.
=> fix: Correct typos, improve clarity and grammar in labels and hints

app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftConfigurationProperties.java, app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java, app/server/runtime/src/main/resources/application.yml
=> Removing an exception that can take place while building an integration

app/ui/src/app/connections/list-page/list-page.component.html, app/ui/src/app/connections/list-page/list-page.component.scss, app/ui/src/app/connections/list/list.component.html, app/ui/src/app/connections/list/list.component.scss, app/ui/src/scss/base/_mixins.scss, app/ui/src/scss/utils/_helpers.scss
fixes https://github.com/syndesisio/syndesis/issues/2149
=> Connection card alert styling

app/common/model/src/main/java/io/syndesis/common/model/action/Action.java, app/connector/activemq/src/main/resources/META-INF/syndesis/connector/activemq.json, app/ui/src/app/integration/edit-page/action-select/action-select.component.ts, app/ui/src/app/platform/types/platform.models.ts
terminal actions. Classify amq request/response actions as a 'pipe'.
=> fix (#1993): Introduce new action pattern 'pipe' to describe non

app/ui/src/app/app.component.html, app/ui/src/app/app.component.scss
Make the header links collapse and display in vertical nav in a narrow viewport. Fixes https://github.com/syndesisio/syndesis/issues/2235
=> Header responsive updates

app/connector/ftp/src/main/resources/META-INF/syndesis/connector/ftp.json, app/connector/sftp/src/main/resources/META-INF/syndesis/connector/sftp.json
=> refactor(ftp and sftp connector): Add order fields to JSON definition

app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationOverview.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
=> Imported integration has no status

app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/AbstractResourceUpdateHandler.java
=> Newly created salesforce connection requires configuration

app/ui/src/app/dashboard/dashboard.component.scss, app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.html, app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.scss, app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html, app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.scss, app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.html, app/ui/src/app/integration/list/list.component.html, app/ui/src/app/integration/list/list.component.scss
fixes https://github.com/syndesisio/syndesis/issues/2225
=> Improve dashboard and integration list responsive views

app/meta/src/main/fabric8-includes/run-env.sh
=> Use relative paths in spring-boot loader.path

app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
=> fix(slack connector): correct username parameter

app/ui/src/app/integration/integration_detail/integration-detail.component.html, app/ui/src/app/integration/integration_detail/integration_activity/integration-activity.component.ts
=> feat(ui): integration activity logs are refetched incrementally upon checking its view

app/ui/src/app/integration/list/list.component.html
After talking to @dongniwang as it doesn't actually convey anything meaningful.
=> chore: remove green check related to 'statusMessage' field

app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.html, app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.scss
fixes https://github.com/syndesisio/syndesis/issues/2274
=> dashboard code/ui tweaks

doc/developing_customizations/docinfo.xml, doc/developing_customizations/master.adoc, doc/integrating_applications/topics/adding_amq_connection_finish.adoc, doc/integrating_applications/topics/adding_amq_connection_middle.adoc, doc/integrating_applications/topics/adding_amq_connection_start.adoc, doc/integrating_applications/topics/adding_amq_connections.adoc, doc/integrating_applications/topics/adding_amqp_connection_finish.adoc, doc/integrating_applications/topics/adding_amqp_connection_middle.adoc, doc/integrating_applications/topics/adding_amqp_connection_start.adoc, doc/integrating_applications/topics/adding_amqp_connections.adoc, doc/integrating_applications/topics/adding_database_connections.adoc, doc/integrating_applications/topics/adding_dropbox_connection_finish.adoc, doc/integrating_applications/topics/adding_dropbox_connection_middle.adoc, doc/integrating_applications/topics/adding_dropbox_connection_start.adoc, doc/integrating_applications/topics/adding_dropbox_connections.adoc, doc/integrating_applications/topics/adding_s3_connection_finish.adoc, doc/integrating_applications/topics/adding_s3_connection_middle.adoc, doc/integrating_applications/topics/adding_s3_connection_start.adoc, doc/integrating_applications/topics/adding_s3_connections.adoc, doc/managing_environments/docinfo.xml, doc/managing_environments/master.adoc, doc/tutorials/topics/clean_up.adoc
I'll merge this myself. Straightforward updates to improve the doc. Some updates are in files we do not use yet, but just keeping them up to date so they are ready when we need them.
=> Updates for readability, ready to merge

doc/integrating_applications/topics/adding_amq_connection_finish.adoc, doc/integrating_applications/topics/adding_dropbox_connection_finish.adoc, doc/integrating_applications/topics/adding_dropbox_connection_start.adoc, doc/integrating_applications/topics/adding_ftp_connections.adoc, doc/integrating_applications/topics/adding_ftp_finish_middle_connection.adoc, doc/integrating_applications/topics/adding_ftp_start_connection.adoc, doc/integrating_applications/topics/creating_ftp_connections.adoc, doc/integrating_applications/topics/understanding.adoc
Also adds a conditional reference to the topic about the product name. This content will appear only downstream. I'll merge this myself.
=> User doc - updates for info about FTP and SFTP connectors mostly

install/generator/03-syndesis-ui.yml.mustache
=> fix(install): Fix product icon path

app/common/model/src/main/java/io/syndesis/common/model/action/ActionDescriptor.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
Fixes #2247
... hem, it should fix it
=> Integration data mapper issue

app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationDeployment.java
=> Missing jsondb index ?

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/user/UserHandler.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/user/UserHandlerTest.java, app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftService.java, app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java, app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceNoOp.java
This PR sets the OpenShift User that is logged in based on the UserPrincipal.
=> fix: Username should be displayed in header #2269

app/ui/src/app/support/support.component.html
=> UI, Fix typo in Support page

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRuntimeAutoConfiguration.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/StepDoneTracker.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/T3stSupportITCase.java
=> Activity Tab not showing step details (activity status steps)

doc/integrating_applications/topics/adding_http_connections.adoc, doc/integrating_applications/topics/adding_mqtt_connection_finish_middle.adoc, doc/integrating_applications/topics/adding_mqtt_connection_start.adoc, doc/integrating_applications/topics/adding_mqtt_connections.adoc, doc/integrating_applications/topics/adding_slack_connections.adoc, doc/integrating_applications/topics/connecting_to_amq.adoc, doc/integrating_applications/topics/connecting_to_amqp.adoc, doc/integrating_applications/topics/connecting_to_applications.adoc, doc/integrating_applications/topics/connecting_to_http.adoc, doc/integrating_applications/topics/connecting_to_mqtt.adoc, doc/integrating_applications/topics/create_amq_connection.adoc, doc/integrating_applications/topics/creating_http_connections.adoc, doc/integrating_applications/topics/creating_mqtt_connections.adoc, doc/integrating_applications/topics/creating_slack_connections.adoc, doc/integrating_applications/topics/making_extensions_available.adoc, doc/integrating_applications/topics/preparing_to_create_an_integration.adoc, doc/integrating_applications/topics/unpublishing_integrations.adoc, doc/integrating_applications/topics/viewing_log_information.adoc
Mostly new and updated content for third-party connectors. Some other small updates. Ready to merge.
=> New doc for MQTT connector. Updates for Slack/HTTP connectors. (#2141)

app/connector/ftp/src/main/resources/META-INF/syndesis/connector/ftp.json, app/connector/sftp/src/main/resources/META-INF/syndesis/connector/sftp.json
=> refactor(ftp and sftp connector): Reordered the connector options

app/ui/src/app/integration/integration_detail/integration-detail.component.ts
=> fix: rename stop integration menu item

doc/integrating_applications/topics/adding_ftp_finish_middle_connection.adoc, doc/integrating_applications/topics/adding_mqtt_connection_start.adoc, doc/integrating_applications/topics/adding_slack_connections.adoc, doc/integrating_applications/topics/connecting_to_slack.adoc, doc/integrating_applications/topics/creating_slack_connections.adoc, doc/integrating_applications/topics/making_extensions_available.adoc
Mostly based on comments from Luca and Andrea. Also added a cllarification about icons for connectors provided in extensions. Ready to merge.
=> user doc: Updates to third party connector doc

doc/integrating_applications/topics/add_log_step.adoc
Updated based on comments from Paolo. Ready to merge.
=> user doc: update description of log step configuration

doc/integrating_applications/topics/add_log_step.adoc
Forgot this from the previous commit.
=> user doc: another small update to description of log step

app/ui/src/app/common/wizard_progress_bar/wizard-progress-bar.component.ts, app/ui/src/scss/utils/_overrides.scss
fixes https://github.com/syndesisio/syndesis/issues/2321
=> improve styling of wizard progress bar

app/ui/src/app/app.component.scss
fixes https://github.com/syndesisio/syndesis/issues/2350
=> bring header spacing inline with PF default

app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html, app/ui/src/app/customizations/api-connector/api-connector-detail/api-connector-detail.component.html, app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.html, app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html
fixes https://github.com/syndesisio/syndesis/issues/2354
=> Update customizations breadcrumbs to be consistent

app/ui/src/app/app.component.html, app/ui/src/app/support/support.component.html, app/ui/src/assets/dictionary/en-GB.json
=> fix(ui): let's centralize the contact email address definition in a single location 📧

app/ui/src/app/connections/create-page/current-connection.ts
fixes #2358
Also tidied up the imports
=> fix: tidy up verbose connection logging

app/ui/src/app/common/ui-patternfly/syndesis-form-control.scss, app/ui/src/app/settings/oauth-apps/oauth-app-form.component.html
fixes https://github.com/syndesisio/syndesis/issues/2370 and https://github.com/syndesisio/syndesis/issues/2230
=> .hint-icon placement in syndesis-form-control, settings page responsive update

app/ui/src/app/integration/integration_detail/integration-detail.component.html, app/ui/src/app/integration/integration_detail/integration-detail.component.ts, app/ui/src/app/integration/integration_detail/integration_activity/integration-activity.component.ts
=> fix: rework how the detail tabs are hidden

app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html, app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.scss
fixes https://github.com/syndesisio/syndesis/issues/2374
=> remove horizontal scrollbar from integration board when it resizes/overflows

app/ui/src/app/connections/create-page/create-page.component.html, app/ui/src/app/connections/create-page/create-page.component.ts, app/ui/src/scss/utils/_overrides.scss
fixes https://github.com/syndesisio/syndesis/issues/2356
=> Create connection wizard ui

app/server/connector-generator/src/test/resources/swagger/basic_auth.unified_connector.json, app/server/connector-generator/src/test/resources/swagger/complex_xml.unified_connector.json, app/server/connector-generator/src/test/resources/swagger/petstore.unified_connector.json, app/server/connector-generator/src/test/resources/swagger/petstore_xml.unified_connector.json, app/server/connector-generator/src/test/resources/swagger/reverb.unified_connector.json, app/server/connector-generator/src/test/resources/swagger/todo.unified_connector.json, app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json, app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.html, app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.html, app/ui/yarn.lock
=> chore: api connector ui tidbits

app/ui/src/app/integration/edit-page/connection-select/connection-select.component.scss, app/ui/src/app/support/support.component.scss
fixes https://github.com/syndesisio/syndesis/issues/2294
=> wrap :ng-deep in :host to keep those styles from affecting other areas of the app

app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
=> fix: save the right config object in the integration

app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.html
=> fix: sort the integration versions properly

app/ui/src/app/support/support.component.html
for better element location in tests and to prevent failures in case of page redesign
=> Adding IDs to support page elements

app/ui/src/app/integration/list/list.component.html
=> chore: remove Draft indicator in list

tools/upgrade/Dockerfile, tools/upgrade/build.sh
=> Upgradedb, refactored yum dependencies

app/connector/mqtt/src/main/java/io/syndesis/connector/mqtt/MqttVerifierExtension.java, app/connector/mqtt/src/main/resources/META-INF/syndesis/connector/mqtt.json
=> chore(mqtt connector): Added username,password and clientId options

app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html
=> chore: use the complete list view on the dashboard

tools/bin/commands/release, tools/upgrade/Dockerfile
* --no-moving-tag-update to prevent updating the moving tag
* Adding syndesis-cli.jar to Dockerfile dir before building upgrade image
* Minor upgrade dockerfile tuning
* Disabling of 'warmup' maven build
=> chore(release): Updates to the release process

tools/bin/commands/release, tools/upgrade/steps/upgrade_50_replace_template
(+ minor fix for release script)
=> fix(upgrade): Update version only if different than before

doc/sdh/cli/cmd_release.adoc, tools/upgrade/common.sh, tools/upgrade/steps/upgrade_20_stop_all, tools/upgrade/steps/upgrade_40_update_resources
also, don't force replace deploymentconfigs anymore
=> fix(upgrade): Wait until all pods are gone when scaling down to 0

app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/PrometheusMetricsProviderImpl.java
=> fix(prometheus): Added missing label

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/support/SupportUtil.java
=> Fix, Support page when no integrations are selected

install/generator/04-syndesis-oauth-proxy.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml
=> fix(install): Add openshift-sar to restrict access to namespace

app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java
This should fix the exception about invalid characters, reported by @dsimansk.
However, there are probably still other hidden issues, which atm I can't identify/resolve, as integrations seem to be crashing and restarting for no apparent reason (which makes it really hard to test).
=> fix: Remove invalid characters from steps performed.

doc/integrating_applications/master.adoc, doc/tutorials/master.adoc, doc/tutorials/topics/amq2api_confirm_works.adoc, doc/tutorials/topics/one_active_integration.adoc, doc/tutorials/topics/sf2db_confirm_works.adoc, doc/tutorials/topics/t2sf_confirm_working.adoc
Clarified unpublishing in order to publish a new sample integration. Ready to merge.
=> user doc: Removed refs to technology preview. 

app/ui/src/app/support/support.component.html
=> Fix, support page text

doc/integrating_applications/topics/about_api_connectors.adoc, doc/integrating_applications/topics/about_swagger_content.adoc, doc/integrating_applications/topics/access_token_strategy.adoc, doc/integrating_applications/topics/adding_api_connectors.adoc, doc/integrating_applications/topics/creating_api_connectors.adoc, doc/integrating_applications/topics/providing_client_credentials.adoc, doc/integrating_applications/topics/refreshing_access_tokens.adoc, doc/shared/attributes.adoc, doc/shared/create_sf_connection.adoc
This is just an initial draft and I have questions and it needs to be reviewed, but I need to bring it downstream so I can see if conditionalizaton of "technology preview" notes work right.
=> user doc: Draft doc for OAuth2 Swagger vendor extensions 

doc/integrating_applications/topics/add_log_step.adoc, doc/integrating_applications/topics/adding_s3_connection_start.adoc, doc/integrating_applications/topics/creating_slack_connections.adoc, doc/integrating_applications/topics/deleting_integrations.adoc, doc/integrating_applications/topics/importing_integrations.adoc
A bunch of small updates based on reviews. Ready to merge.
=> user doc: Various updates based on review comments

doc/integrating_applications/topics/adding_database_connections.adoc, doc/integrating_applications/topics/adding_db_connection_finish_middle.adoc, doc/integrating_applications/topics/adding_db_connection_start.adoc, doc/integrating_applications/topics/create_database_connection.adoc
Updated according to comments from Stefan Veres. Ready to merge.
=> user doc: Updates to SQL db connection info based on feedback from QE

app/connector/salesforce/src/main/resources/META-INF/syndesis/connector/salesforce.json
This fixes the order, marks all properties as required and hides the
refresh token property.
Fixes #2492
=> chore(connector): tidier salesforce properties

app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackChannelCustomizer.java, app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackPlainMessage.java, app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackVerifierExtension.java, app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
=> fix(connector): Add a Java wrapper for plain Slack input

tools/upgrade/steps/upgrade_10_migrate_db
Temporary removed call to syndesis-cli.jar until #1512 is fully done
=> [UpgradeDB] Comment out call to syndesis-cli.jar

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
=> No activity log shown

app/pom.xml, app/ui/package.json, app/ui/yarn.lock
Contains fixes for:
* atlasmap/atlasmap#412
* atlasmap/atlasmap#408
@mmelko - FYI
=> chore: Update to atlasmap-1.34.3

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/credential/CredentialITCase.java, app/ui/src/app/connections/detail-page/configuration.component.html, app/ui/src/app/connections/detail-page/configuration.component.ts
This implements re-authorization of OAuth-based connections.
Fixes #2531
=> feat: re-authorization of oauth connections

tools/upgrade/common.sh, tools/upgrade/steps/upgrade_10_migrate_db, tools/upgrade/upgrade.sh
fixes #1512 
Sample output:
```
...
syndesis-upgrade-1.3 upgrade === * Process new template to extract update resources (prep_40_process_template)
syndesis-upgrade-1.3 upgrade       - Current Syndesis version "latest"
syndesis-upgrade-1.3 upgrade       - Not updating syndesis-server-config
syndesis-upgrade-1.3 upgrade === * Migrate database (upgrade_10_migrate_db)
syndesis-upgrade-1.3 upgrade 16:09:04.677 Current database schema version: 26
syndesis-upgrade-1.3 upgrade 16:09:04.774 Migration done
syndesis-upgrade-1.3 upgrade === * Stop all deployments (upgrade_20_stop_all)
syndesis-upgrade-1.3 upgrade       - Stopping deployments syndesis-db
syndesis-upgrade-1.3 upgrade syndesis-meta
syndesis-upgrade-1.3 upgrade syndesis-oauthproxy
syndesis-upgrade-1.3 upgrade syndesis-prometheus …
```
=> Fix, upgradedb, uses correct user and password

install/generator/01-header.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml
=> Peformance, bump Prometheus memory limits

app/meta/pom.xml, app/s2i/pom.xml, app/server/runtime/pom.xml
https://github.com/syndesisio/syndesis/issues/2553
=> Remove docker-maven-plugin and fabric8-maven-plugin changes.

app/pom.xml, app/ui/package.json, app/ui/yarn.lock
This contains a fix for: atlasmap/atlasmap#415
=> chore: Update to AtlasMap 1.34.4

doc/integrating_applications/topics/about_connection_validation.adoc, doc/integrating_applications/topics/about_creating_connections.adoc, doc/integrating_applications/topics/adding_api_connectors.adoc, doc/integrating_applications/topics/available_transformations.adoc, doc/integrating_applications/topics/creating_api_connectors.adoc, doc/integrating_applications/topics/general_procedure_for_obtaining_authorization.adoc, doc/integrating_applications/topics/managing_integrations.adoc, doc/integrating_applications/topics/obtaining_authorization_to_access_applications.adoc, doc/integrating_applications/topics/overview_of_creating_connections.adoc, doc/integrating_applications/topics/troubleshooting_integration_execution.adoc, doc/integrating_applications/topics/understanding_integration_states.adoc
I also reorganized the info about OAuth applications and added a troubleshooting section at the end of Managing Integrations, and added info about the Reconnect button. Ready to merge.
=> 2141 user doc - Lots of updates based on QE reviews

doc/integrating_applications/topics/about_connections.adoc, doc/integrating_applications/topics/about_integrations.adoc, doc/integrating_applications/topics/about_steps.adoc
=> user doc: Updates based on Stefan's review of the highlevel overview chapter

doc/integrating_applications/topics/adding_db_connection_finish_middle.adoc
=> user doc: Update SQL connection doc based on QE feedback from Stefan

app/ui/src/app/api/providers/api-http-provider.service.ts
=> chore: Force Accept header to application/json since that's all we use

app/ui/src/app/store/step/step.store.ts
=> fix: ensure we check that steps have actions before iterating through 'em

app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html
=> refactor(ui): change wording on connector delete confirmation

doc/integrating_applications/topics/adding_db_connection_finish_middle.adoc, doc/integrating_applications/topics/available_transformations.adoc, doc/integrating_applications/topics/creating_http_connections.adoc, doc/integrating_applications/topics/creating_jdbc_driver_library_extensions.adoc, doc/integrating_applications/topics/creating_mqtt_connections.adoc, doc/integrating_applications/topics/importing_integrations.adoc, doc/integrating_applications/topics/obtaining_authorization_to_access_applications.adoc, doc/integrating_applications/topics/register_with_dropbox.adoc, doc/integrating_applications/topics/updating_extensions.adoc, doc/shared/register_with_sf.adoc, doc/shared/register_with_twitter.adoc
=> user doc: Updates based on QE reviews.

doc/integrating_applications/topics/deleting_api_connectors.adoc
=> user doc: 2141 update about deleting api connectors

doc/integrating_applications/topics/create_amq_connection.adoc, doc/integrating_applications/topics/importing_integrations.adoc
=> user doc: 2141 Added example AMQ broker URL. Fixed format.

doc/integrating_applications/master.adoc, doc/tutorials/master.adoc, doc/tutorials/topics/amq2api_confirm_works.adoc, doc/tutorials/topics/one_active_integration.adoc, doc/tutorials/topics/sf2db_confirm_works.adoc, doc/tutorials/topics/t2sf_confirm_working.adoc
Updates were approved by Keith and Roland.
=> user doc: 2141 remove text about strict restriction of one running integration

doc/integrating_applications/topics/about_connection_validation.adoc, doc/integrating_applications/topics/about_connections.adoc, doc/integrating_applications/topics/about_steps.adoc, doc/integrating_applications/topics/add_api_client_connection.adoc, doc/integrating_applications/topics/adding_db_connection_finish_middle.adoc, doc/integrating_applications/topics/adding_db_connection_start.adoc, doc/integrating_applications/topics/adding_sf_connections.adoc, doc/integrating_applications/topics/adding_twitter_connections.adoc, doc/integrating_applications/topics/connecting_to_amqp.adoc, doc/integrating_applications/topics/separate_one_source_field_into_multiple_target_fields.adoc, doc/sdh/development/ui.adoc, doc/system-tests/README.adoc, install/README.md, project/DevelopersGuide.md, project/proposals/002-filter-data.md, project/proposals/013-global-settings.md, project/proposals/016-dynamic-properties.md, project/proposals/042-health-checks.adoc, project/proposals/044-integration-model.md, project/proposals/119-custom-connectors.md, project/proposals/181-tech-extension.adoc
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> Fix several typos

app/extension/api/src/main/java/io/syndesis/extension/api/annotations/DataShape.java, app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java
=> extension : extension's default in/out kind should be 'none'

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/state/ClientSideState.java
If when creating OAuth connections the user cancels or gets an error the
client side state cookie might remain, this is an issue if many of these
cookies are present in the browser as there are limits on HTTP header
sizes in the browser and the server.
This adds default max-age and expiry to the cookie so it will be removed
from the browser at the same time as it times-out on the server.
Fixes #2443
=> chore(server): set default max-age and expiry on client state cookies

tools/upgrade/migration/preflight.sh
Only check up to the minor version number in the preflight check.
=> chore(upgrade): Relax preflight check

app/ui/src/app/common/ui-patternfly/duration-form-control.component.html
=> fix: Ensure there's a default lower limit for durations

app/connector/aws-s3/src/main/java/io/syndesis/connector/aws/s3/AWSS3CopyObjectCustomizer.java, app/connector/aws-s3/src/main/resources/META-INF/syndesis/connector/aws-s3.json
=> chore(feat): AWS S3 Component - set CamelAwsS3Key header

app/extension/maven-plugin/pom.xml, app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java, app/extension/maven-plugin/src/resources/META-INF/spring.factories, app/extension/maven-plugin/src/test/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojoTest.java, app/extension/maven-plugin/src/test/resources/logback-test.xml
=> OutputDataShape annotation disregarded by maven plugin

install/syndesis-dev.yml, install/syndesis.yml
=> chore(install): regenerate templates

app/pom.xml, app/ui/package.json, app/ui/src/app/app.module.ts, app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts, app/ui/src/app/integration/integration.module.ts, app/ui/yarn.lock
This update contains:
* Update to Angular6
* Drag&Drop ordering of Separate/Combine fields
* Allow selecting multiple fields with Ctrl-mouseclick for Separate/Combine
* etc
=> chore: Update to AtlasMap 1.35.0

app/extension/api/src/main/resources/syndesis/syndesis-extension-definition-schema.json
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
I don't understand why it is marking everything as modified, linux end of line should be used on my branch.
=> #2719 - update json schema

app/connector/aws-s3/src/main/java/io/syndesis/connector/aws/s3/AWSS3DeleteObjectCustomizer.java, app/connector/aws-s3/src/main/resources/META-INF/syndesis/connector/aws-s3.json
=> feat(aws-s3 connector): AWS S3 delete object connector

app/ui/src/app/connections/common/configuration/configuration.service.ts, app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.ts, app/ui/src/app/connections/detail-page/configuration.component.ts
fixes #2720 
Also refactors the code a bit and also reworks the readonly mode works for the detail page so it works across all the controls.
=> (fix): Update how the connection config form gets its values from the connection object

app/server/cli/src/main/java/io/syndesis/server/cli/command/migrate/MigrateCommand.java, app/server/jsondb/src/main/java/io/syndesis/server/jsondb/dao/Migrator.java, app/server/runtime/src/main/java/io/syndesis/server/runtime/DefaultMigrator.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/MigrationsITCase.java
Original: up-50.js bundled in syndesis-cli.jar
```
java -jar syndesis-cli.jar migrate -t 99 --url="jdbc:postgresql://localhost:5432/syndesis" --user="syndesis" --password="FkGPHgdx8x5nvY0S"
10:44:14.708 Current database schema version: 26
10:44:14.714 Starting migration to version: 99
10:44:15.088 Migrating to schema: 50
Starting migration to schema 50
Migration to schema 50 completed
10:44:16.524 Migration done
```
up-50.js bundled in syndesis-cli.jar and up-98.js and up-99.js in external folder:
```
java -jar syndesis-cli.jar migrate -t 99 --url="jdbc:postgresql://localhost:5432/syndesis" --user="syndesis" --password="oB3IV5kakdyOUwyi" -f /tmp/upgrade
10:45:58.053 Current database schema version: 26
10:45:58.057 Starting migration to version: 99
10:45:58.235 Migrating to schema: 50 …
```
=> [closes #2608] Get migrate DB scripts also from external folder

app/ui/src/app/connections/detail-page/configuration.component.html, app/ui/src/app/connections/detail-page/detail-page.component.scss, app/ui/src/app/connections/detail-page/detail-page.component.ts, app/ui/src/app/connections/detail-page/info.component.scss, app/ui/src/app/connections/detail-page/info.component.ts, app/ui/src/app/integration/integration_detail/integration-metrics.component.html
fixes https://github.com/syndesisio/syndesis/issues/2227
Improving the responsiveness of cards on the metrics tab in a a small viewport.
=> Integrations metrics responsiveness

app/ui/src/app/connections/detail-page/configuration.component.html, app/ui/src/app/connections/detail-page/detail-page.component.scss, app/ui/src/app/connections/detail-page/detail-page.component.ts, app/ui/src/app/connections/detail-page/info.component.scss, app/ui/src/app/connections/detail-page/info.component.ts
fixes https://github.com/syndesisio/syndesis/issues/2742
=> improve connection details UI

app/ui/src/app/customizations/api-connector/api-connector-detail/api-connector-detail.component.html, app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.html, app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.scss, app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.html, app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html, app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.ts, app/ui/src/app/integration/import-export/import/integration-import.component.html, app/ui/src/scss/utils/_helpers.scss
Fixes https://github.com/syndesisio/syndesis/issues/2229
To verify, go through the view, create, edit pages of both customizations panels.
Also added the hover/active state to the extension import upload area when you've uploaded a valid file.
=> improve responsiveness of customizations pages, add hover/active class to extension import drag/drop zone on successful upload

app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html, app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.ts, app/ui/src/app/integration/import-export/import/integration-import.component.html, app/ui/src/app/integration/import-export/import/integration-import.component.ts
Fixes https://github.com/syndesisio/syndesis/issues/2761
=> Remove hover state from drag and drop uploader after file is uploaded

app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.html, app/ui/src/app/connections/create-page/connection-basics/connection-basics.component.html, app/ui/src/app/connections/create-page/review/review.component.html
fixes https://github.com/syndesisio/syndesis/issues/1520
=> add .card-pf-heading class to card title in create connection workflow

app/common/util/src/main/java/io/syndesis/common/util/CollectionsUtils.java, app/server/endpoint/pom.xml, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/MetadataCommand.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/DefaultVerifierExtensionUploader.java, app/server/metrics/prometheus/pom.xml, app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/HttpClient.java, app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/PrometheusMetricsProviderImpl.java, app/server/verifier/pom.xml, app/server/verifier/src/main/java/io/syndesis/server/verifier/ExternalVerifierService.java
=> Possible resources leak

app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html
fixes https://github.com/syndesisio/syndesis/issues/2784
=> change extension file uploader wording from "import" to "upload"

app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.html
=> chore: add timestamp display

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
=> fix: toggle loading state when the user clicks 'next'

app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.html, app/ui/src/app/connections/list/list.component.html, app/ui/src/app/core/providers/i18n-provider.service.ts, app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html, app/ui/src/assets/dictionary/en-GB.json
fixes #2778 
Also updates the extension list page to use the dictionary and has some dictionary additions too.
=> chore: tokenize project name in templates, add app name override to i18n service

app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html, app/ui/src/app/core/providers/form-factory-provider.service.ts, app/ui/src/app/store/step/step.store.ts
=> fix: add advanced filter placeholder; add support for more advanced tooltip formatting

app/ui/src/app/integration/import-export/import/integration-import.component.html, app/ui/src/app/integration/import-export/import/integration-import.component.scss
fixes https://github.com/syndesisio/syndesis/issues/2799
=> refactor integration import results area

app/connector/gmail/src/main/java/io/syndesis/connector/gmail/GmailReceiveEmailCustomizer.java, app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json, app/connector/odata/create-entity/src/main/resources/camel-connector.json, app/connector/odata/delete-entity/src/main/resources/camel-connector.json, app/connector/odata/replace-entity/src/main/resources/camel-connector.json, app/connector/odata/retrieve-entity/src/main/resources/camel-connector.json, app/connector/odata/update-entity/src/main/resources/camel-connector.json, app/connector/rest-swagger/src/main/resources/camel-connector.json, app/extension/bom/pom.xml, app/extension/example/log-step/pom.xml, app/integration/pom.xml, app/pom.xml, app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java
related to #2636 
Bump the Camel version to 2.21.0.fuse-000094
=> feature(gmail-connector): Gmail Stream Consumer connector

app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.html
fix https://github.com/syndesisio/syndesis/issues/2519
=> remove "last published" in draft integration detail history

app/connector/gmail/src/main/java/io/syndesis/connector/gmail/GmailMessageModel.java, app/connector/gmail/src/main/java/io/syndesis/connector/gmail/GmailSendEmailCustomizer.java, app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json, app/server/runtime/src/test/java/io/syndesis/server/runtime/SetupITCase.java
=> OAuth Gmail

doc/connecting/docinfo.xml, doc/connecting/master.adoc, doc/connecting/topics/supported_connectors.adoc, doc/developing_customizations/docinfo.xml, doc/developing_customizations/master.adoc, doc/integrating_applications/docinfo.xml, doc/integrating_applications/master.adoc, doc/managing_environments/docinfo.xml, doc/managing_environments/master.adoc, doc/master.adoc, doc/shared/attributes-links.adoc, doc/shared/attributes.adoc, doc/tutorials/master-docinfo.xml, doc/tutorials/master.adoc, doc/tutorials/topics/amq2api_create_rest_api_connector.adoc, doc/tutorials/topics/amq2api_upload_todo_app_icon.adoc, doc/tutorials/topics/sf2db_confirm_works.adoc
Updated master.adoc files. Updated docinfo files.
=> user doc: Add explanation of To Do app. Change feedback email. 

doc/developing_customizations/master.adoc, doc/developing_customizations/topics/developing_extensions.adoc, doc/developing_customizations/topics/developing_other_connectors.adoc
This is a rough draft of the development guide for extension and while I'm adding more content, it would be nice if @TovaCohen / @fbolton could have a look an give me some hint for a better structure, and so on.
=> documentation: add documentation about extension development 

app/connector/pom.xml, app/connector/servicenow/pom.xml, app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/ServiceNowMetaDataAutoConfiguration.java, app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/ServiceNowMetaDataExtension.java, app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/ServiceNowMetadataRetrieval.java, app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/ServiceNowVerifierAutoConfiguration.java, app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/customizers/ServiceNowImportSetCustomizer.java, app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/customizers/ServiceNowTableGetCustomizer.java, app/connector/servicenow/src/main/resources/META-INF/spring.factories, app/connector/servicenow/src/main/resources/META-INF/syndesis/connector/servicenow.json, app/connector/support/catalog/pom.xml, app/connector/support/verifier/src/main/java/io/syndesis/connector/support/verifier/api/SyndesisMetadata.java, app/meta/pom.xml, app/pom.xml, app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java
Fixes #1190
This PR implements a basic ServiceNow connector which lacks support for pagination for starting connectors.
=> Create a simple ServiceNow Connector

app/ui/src/app/settings/oauth-apps/oauth-app-form.component.html
fix https://github.com/syndesisio/syndesis/issues/2798
=> align oauth form labels/fields to left

app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-auth/api-connector-auth.component.html, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html
fix https://github.com/syndesisio/syndesis/issues/2798
=> improve spacing/nesting of upload radio form, always select first authentication type radio

app/ui/src/app/support/support.component.html, app/ui/src/app/support/support.component.scss
fix https://github.com/syndesisio/syndesis/issues/2798
=> improve ui of support radio buttons and progressive disclosure

app/ui/package.json, app/ui/src/app/app.component.html, app/ui/src/app/common/wizard_progress_bar/wizard-progress-bar.component.spec.ts, app/ui/src/app/common/wizard_progress_bar/wizard-progress-bar.component.ts, app/ui/src/app/customizations/tech-extensions/tech-extension-delete-modal.component.html, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html, app/ui/src/app/integration/edit-page/action-select/action-select.component.html, app/ui/src/app/integration/edit-page/connection-select/connection-select.component.html, app/ui/src/app/integration/edit-page/describe-data/describe-data.component.html, app/ui/src/app/integration/edit-page/integration-basics/integration-basics.component.html, app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.html, app/ui/src/app/integration/edit-page/step-select/step-select.component.html, app/ui/src/scss/utils/_overrides.scss, app/ui/yarn.lock
main issue https://github.com/syndesisio/syndesis/issues/2820
Includes https://github.com/syndesisio/syndesis/issues/2829, https://github.com/syndesisio/syndesis/issues/2830, https://github.com/syndesisio/syndesis/issues/2831, https://github.com/syndesisio/syndesis/issues/2832, https://github.com/syndesisio/syndesis/issues/2833
=> Upgrade patternfly 3.49.0

app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html, app/ui/src/scss/components/_forms.scss
fix https://github.com/syndesisio/syndesis/issues/2875
=> remove .control-label override style

app/ui/src/app/error-handler/http-error.interceptor.ts
=> chore: suppress the HTTP error toast notification in favor of a console.error message

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
=> fix: ensure we toggle loading off when there's an error response

app/ui/src/app/error-handler/http-error.interceptor.ts, app/ui/src/app/store/entity/entity.store.ts, app/ui/src/assets/dictionary/en-GB.json
=> fix: show a more user freindly error message when the backend is unavailable

app/ui/package.json, app/ui/yarn.lock
fixes https://github.com/syndesisio/syndesis/issues/2913
=> update to patternfly 3.51.2

app/ui/src/app/common/delete_confirmation_modal/delete-confirmation-modal.component.ts, app/ui/src/app/common/modal/modal.component.html, app/ui/src/app/common/modal/modal.component.ts, app/ui/src/app/common/modal/modal.service.ts, app/ui/src/app/connections/list/list.component.html, app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html, app/ui/src/app/customizations/tech-extensions/tech-extension-delete-modal.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html, app/ui/src/app/integration/integration-actions-provider.service.ts, app/ui/src/app/integration/integration_detail/integration-detail.component.html, app/ui/src/app/integration/integration_detail/integration-detail.component.ts, app/ui/src/app/integration/list/list.component.html, app/ui/src/app/integration/list/list.component.ts, app/ui/src/app/platform/types/integration/integration-actions.service.ts, app/ui/src/app/settings/oauth-apps/oauth-app-modal.component.html
add support for modal type, update UI for delete confirmation modals.
fix https://github.com/syndesisio/syndesis/issues/2879
=> modal message dialog updates

app/ui/src/app/connections/detail-page/info.component.scss, app/ui/src/app/integration/integration_detail/integration-detail.component.html, app/ui/src/app/integration/integration_detail/integration-detail.component.scss
fix https://github.com/syndesisio/syndesis/issues/2918
=> improve layout of editable names on integration and connection details pages

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.spec.ts, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/platform/types/integration/integration.models.ts
=> feat: skip the action config if there's no properties

app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.html, app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.ts, app/ui/src/app/connections/create-page/current-connection.ts, app/ui/src/app/store/connector/connector.service.ts, app/ui/src/assets/dictionary/en-GB.json
=> fix: display error messages when acquiring credentials fails

app/ui/angular.json, app/ui/package.json
fixes #2942 
@seanforyou23 FYI
=> fix: use glob config to include config.json

app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.html, app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.ts
fix https://github.com/syndesisio/syndesis/issues/2934
one thing I couldn't figure out was how to reset the form to the default/original values if you edit the form and click "cancel"
=> change api connector details from inline editor

app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.html, app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.ts
=> fix: remove unused field-level error messaging for now

app/connector/sql/pom.xml, app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/application.properties.mustache, app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/redhat/application.properties.mustache, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/application.properties, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/redhat/application.properties
=> [Meta] No suitable driver found for jdbc:postgresql://syndesis-db:5432/sampledb. Unable to fetch and process metadata

app/ui/src/app/common/modal/modal.component.html, app/ui/src/app/common/modal/modal.component.ts, app/ui/src/app/connections/list-page/list-page.component.spec.ts, app/ui/src/app/connections/list/list.component.html, app/ui/src/app/connections/list/list.component.spec.ts, app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html, app/ui/src/app/customizations/tech-extensions/tech-extension-delete-modal.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html, app/ui/src/app/integration/integration-actions-provider.service.ts, app/ui/src/app/integration/integration_detail/integration-detail.component.html, app/ui/src/app/integration/integration_detail/integration-detail.component.ts, app/ui/src/app/integration/list/list.component.html, app/ui/src/app/integration/list/list.component.ts, app/ui/src/app/platform/types/integration/integration-actions.service.ts, app/ui/src/app/settings/oauth-apps/oauth-app-modal.component.html, app/ui/src/assets/dictionary/en-GB.json
fix https://github.com/syndesisio/syndesis/issues/2920
=> update modal message dialogs

app/ui/src/app/common/ui-patternfly/duration-form-control.component.ts
=> fix: get property value from the group object

app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html, app/ui/src/app/core/providers/form-factory-provider.service.ts
=> fix: don't bind the checked property

app/ui/src/app/settings/oauth-apps/oauth-apps.component.html, app/ui/src/app/settings/oauth-apps/oauth-apps.component.ts
=> fix: move link handler to an inner element

app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.ts
fix https://github.com/syndesisio/syndesis/issues/2991
=> fix submit handler for saving api connector details form when in create mode

app/ui/src/app/common/modal/modal.component.html, app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html, app/ui/src/app/customizations/tech-extensions/tech-extension-delete-modal.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.spec.ts, app/ui/src/app/integration/integration-actions-provider.service.ts, app/ui/src/app/settings/oauth-apps/oauth-app-modal.component.html, app/ui/src/assets/dictionary/en-GB.json
fix https://github.com/syndesisio/syndesis/issues/2988
=> Move message dialog text into dictionary file

app/common/model/src/main/java/io/syndesis/common/model/Kind.java, app/common/model/src/main/java/io/syndesis/common/model/monitoring/IntegrationDeploymentDetailedState.java, app/common/model/src/main/java/io/syndesis/common/model/monitoring/IntegrationDeploymentStateDetails.java, app/pom.xml, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/monitoring/MonitoringProvider.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/monitoring/MonitoringProviderImpl.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/monitoring/NoopMonitoringProviderImpl.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/monitoring/IntegrationDeploymentStateDetailsHandler.java, app/server/monitoring/pom.xml, app/server/monitoring/src/main/java/io/syndesis/server/monitoring/DeploymentStateMonitor.java, app/server/monitoring/src/main/java/io/syndesis/server/monitoring/DeploymentStateMonitorController.java, app/server/monitoring/src/main/java/io/syndesis/server/monitoring/MonitoringConfiguration.java, app/server/monitoring/src/main/java/io/syndesis/server/monitoring/PublishingStateMonitor.java, app/server/monitoring/src/main/java/io/syndesis/server/monitoring/StateHandler.java, app/server/monitoring/src/main/resources/META-INF/spring.factories, app/server/monitoring/src/test/java/io/syndesis/server/monitoring/DeploymentStateMonitorControllerTest.java, app/server/pom.xml, app/server/runtime/pom.xml, app/server/runtime/src/main/resources/application.yml, app/server/runtime/src/test/resources/application-test.yml
=> Initial version of publishing status monitoring endpoint, fixes 2619 See comment in issue for details.

app/ui/src/app/settings/oauth-apps/oauth-app-form.component.html
=> fix: add a space

app/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts
=> chore(ui): Tidy up OAuth settings page

app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/BaseSwaggerConnectorGenerator.java, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html
I updated some other text strings as well. Hope this is all okay.
=> Text fixes: Changed "a OpenAPI" to "an OpenAPI and a few other updates.

app/ui/src/app/integration/list/status-detail.component.ts, app/ui/src/app/store/integration/integration.service.ts
Noticed on the detail page the detailed status wasn't updating properly, this PR sorts that.
=> chore: tidy up fetching a single integration, fix up status on detail page

doc/connecting/topics/connecting_to_gmail.adoc, doc/connecting/topics/register_with_gmail.adoc, doc/connecting/topics/supported_connectors.adoc
Added Gmail to list of supported connectors. Filled in missing registration steps that I forgot to paste in.
=> user doc: Updates to doc for Gmail connector

app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
fix https://github.com/syndesisio/syndesis/issues/3029
=> fix integration name edit in firefox (in integration editor workflow)

app/ui/src/app/connections/create-page/create-page.component.ts
=> fix: bit 'o refactoring and use specific step indices

app/ui/jsconfig.json, app/ui/src/app/connections/create-page/create-page.component.ts
Tweak to jsconfig.json to get vscode to stop complaining, and also noticed some subscriptions that weren't being unsubscribed in the create connection component.
=> chore: close subscriptions, also exclude node_modules folder in jsconfig.json

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
=> chore: show the step name if available

app/ui/src/app/integration/integration_detail/integration-detail.component.scss
fix https://github.com/syndesisio/syndesis/issues/3014
=> dont allow integration name area to shrink

app/ui/src/app/integration/list/status-detail.component.ts, app/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts, app/ui/src/app/store/integration/integration.service.ts
fixes #3045
Can't see a good way to sort the height issue mentioned though, currently the detailed status when it shows makes the row a little bigger.
Also adds a little type info in the oauth settings, was getting a compile error locally.
=> chore: fix width of detailed status

app/connector/log/pom.xml, app/connector/log/src/main/resources/META-INF/syndesis/connector/log.json, app/connector/pom.xml, app/connector/support/catalog/pom.xml, app/integration/bom/pom.xml, app/meta/pom.xml, app/pom.xml
=> feature(connector-log): Add log connector to Syndesis from Extensions

app/connector/pom.xml, app/connector/support/catalog/pom.xml, app/connector/telegram/pom.xml, app/connector/telegram/src/main/resources/META-INF/syndesis/connector/telegram.json, app/integration/bom/pom.xml, app/meta/pom.xml, app/pom.xml
=> feature(connector): add telegram connector to Syndesis from Extensions

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
fix https://github.com/syndesisio/syndesis/issues/3057
cc @seanforyou23
=> fix expanded IVP UI with long step/connection name

tools/misc/extract_javathreads.sh
Hi team. Please review and merge this PR.
If it's better to file a new issue ticket for this PR, please let me know.
Thx
=> shell script to extract Java thred dumps with CPU usage from target POD.

app/ui/package.json, app/ui/pom.xml
=> chore: ensure dev config.json file is nuked when building

app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
fix https://github.com/syndesisio/syndesis/issues/3083
=> increase bottom padding of expanded IVP

app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
fix https://github.com/syndesisio/syndesis/issues/3082
=> move IVP add step/connection popover below plus button, adjust paddings

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
=> fix: make the icon in the editor clickable too

app/ui/src/assets/dictionary/en-GB.json
=> chore: update placeholder text in oauth settings

app/ui/src/app/integration/import-export/import/integration-import.component.html, app/ui/src/app/integration/import-export/import/integration-import.component.ts, app/ui/src/app/integration/import-export/integration-import-export.component.html, app/ui/src/app/integration/import-export/integration-import-export.component.ts, app/ui/src/assets/dictionary/en-GB.json
fixes #3101
Also removes the 'Cancel' button, as there's no 'Cancel' the way the API is currently designed.
=> fix: ensure the integration and connection names are displayed properly

app/ui/angular.json, app/ui/src/main.ts, app/ui/src/tsconfig.app.json
fix https://github.com/syndesisio/syndesis/issues/3040
=> set preserveWhitespaces = true for JIT and AOT

app/ui/src/tsconfig.json
Prevents some errors and info popups from showing up.
=> fix: add tsconfig.json back and just inherit from tsconfig.app.json so vscode behaves

app/pom.xml, app/ui/package.json, app/ui/yarn.lock
Contains:
- fix/feat: atlasmap/atlasmap#46, atlasmap/atlasmap#278, atlasmap/atlasmap#508, #2858
- update to patternfly-ng 4.0
- and housekeeping
=> chore: Update to AtlasMap 1.35.5

app/ui/src/app/common/cancel_confirmation_modal/cancel-confirmation-modal.component.ts, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html, app/ui/src/assets/dictionary/en-GB.json
fix https://github.com/syndesisio/syndesis/issues/3060
=> update api connector cancel modal dialog

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandler.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandlerTest.java
=> fix: Specify mapping definition file encoding on camel-atlasmap endpoint

app/ui/src/app/dashboard/dashboard.component.html, app/ui/src/app/dashboard/dashboard.component.ts, app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html, app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.ts, app/ui/src/app/store/entity/entity.store.ts
fixes #3135
Less loading spinners, required some tweaks to the dashboard.
=> fix: update the stores so they only fetch on-demand the first time

app/ui/src/app/api/providers/api-http-provider.service.ts, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
=> fix: consistently display the error response from the meta service

app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json
I added field hints with more descriptive information. I standardized capitalization. Some other text updates too.
=> enhancement: Clarified labels and hints for Gmail connector

app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html, app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.ts
=> fix: sort fetched integrations in dashboard by updatedAt/createdAt

app/ui/src/app/connections/create-page/create-page.component.html, app/ui/src/app/connections/create-page/create-page.component.ts, app/ui/src/assets/dictionary/en-GB.json
fix https://github.com/syndesisio/syndesis/issues/3060
=> have cancel button in create connection wizard prompt the user via modal to confirm cancellation

doc/integrating_applications/topics/description_of_integration_states.adoc, doc/integrating_applications/topics/overview_of_managing_integrations.adoc
A few updates for the doc that changes "Publish" to "Start". Ready to merge.
=> user doc: Updates based on QA review of Publish/Start change. (Issue 2715)

app/integration/bom/pom.xml, app/pom.xml, app/ui/package.json, app/ui/yarn.lock
Fixes: #2858
Contains:
* #2858 - 1.35.5 was supposed to have this fixed, but slipped by mistake
* atlasmap/atlasmap#504
* atlasmap/atlasmap#499
* atlasmap/atlasmap#505
=> chore: Update to AtlasMap 1.35.6

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/util/JsonSimplePredicate.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/FilterStepHandlerTest.java
Fixes #3149
@zregvart I've added an additional catch block to catch json parsing exceptions and lowered the log level used to trace such condition.
=> Advanced filter throws exception when message body is plaintext 

app/connector/timer/src/main/resources/META-INF/syndesis/connector/timer.json
=> Timer connector fix

app/ui/src/app/connections/create-page/connection-basics/connection-basics.component.ts, app/ui/src/app/connections/create-page/create-page.component.ts, app/ui/src/app/connections/create-page/current-connection.ts
=> fix: ensure the step indicator is driven by the route, also better property checking

app/ui/src/app/integration/integration-actions-provider.service.ts, app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.html, app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.ts, app/ui/src/app/integration/list/action-menu.component.ts, app/ui/src/app/platform/types/integration/integration-actions.service.ts
=> fix: show/hide relevant menu entries; disable publish/edit when publishing

doc/connecting/topics/add_gmail_connection_finish_middle.adoc, doc/connecting/topics/alternatives_for_populating_email_to_send.adoc
Ready to merge. I just added information about precedence if you populate a Send Email field both by action configuration and by mapping. The action configuration value has precedence.
=> user doc: Update Gmail connector doc based on QE review

app/ui/src/assets/dictionary/en-GB.json
fix https://github.com/syndesisio/syndesis/issues/3060
=> update wording in cancel modals in api connector and connection create wizards

app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html
=> fix: enable the done button on the data mapper page

app/ui/src/app/dashboard/dashboard.component.html, app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html, app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.ts, app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.html
=> fix: refactor the integration list on the dashboard; make the buttons show appropriately

app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html
=> fix: correct time format in last updated tab

app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/platform/types/integration/integration.models.ts
=> fix: ensure IDs are set on all steps before saving

app/ui/src/app/common/card-tech-preview.component.scss, app/ui/src/app/common/card-tech-preview.component.ts, app/ui/src/app/connections/list/list.component.html, app/ui/src/app/connections/list/list.component.scss, app/ui/src/assets/dictionary/en-GB.json
re: https://github.com/syndesisio/syndesis/issues/3201
=> refactor position of technical preview component, update dictionary case

app/ui/src/app/common/card-tech-preview.component.ts, app/ui/src/app/common/common.module.ts, app/ui/src/app/connections/list/list.component.html, app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.html, app/ui/src/assets/dictionary/en-GB.json
=> refactor(ui): use popover for tech preview

app/ui/src/app/app.component.html, app/ui/src/assets/dictionary/en-GB.json
=> feat(ui): help menu link to Connectors Guide

app/ui/src/app/settings/oauth-apps/oauth-app-modal.component.ts, app/ui/src/app/settings/oauth-apps/oauth-apps.component.ts
=> fix: check an oauth app's config to see if it's configured

app/ui/src/app/common/card-tech-preview.component.scss, app/ui/src/app/common/card-tech-preview.component.ts
fix https://github.com/syndesisio/syndesis/issues/3227
=> update technical preview popover placement

app/connector/servicenow/pom.xml, app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/ServiceNowMetaDataExtension.java, app/connector/servicenow/src/test/java/io/syndesis/connector/servicenow/ServiceNowMetaDataExtensionTest.java, app/connector/servicenow/src/test/resources/logback-test.xml
=> Servicenow - can't retrieve data from custom table

app/ui/src/app/common/card-tech-preview.component.ts, app/ui/src/assets/dictionary/en-GB.json
fix https://github.com/syndesisio/syndesis/issues/3201#issuecomment-408424977
=> link "technology previews" text in popover

tools/bin/commands/build, tools/bin/commands/minishift
=> fix(syndesis): Issue with directory when doing the full build run

doc/sdh/cli/cmd_build.adoc, doc/sdh/cli/cmd_install.adoc, doc/sdh/cli/cmd_minishift.adoc, tools/bin/commands/build, tools/bin/commands/install, tools/bin/commands/minishift, tools/bin/commands/release, tools/bin/commands/util/openshift_funcs, tools/bin/commands/util/operator_funcs
Please review the docs, too. There will be tons of typos as I just have written it down.
If you find errors in the documentation feel free to fix them and push directly to
this branch.
=> feature: Tuned UX of syndesis according to suggestion and added docs.

app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.ts
=> Resubmit the edited spec for validation to the backend

app/pom.xml
=> Error 500 when deleting integrations

app/ui/src/polyfills.ts
Fix lint errors introduced with #3288
=> Fix lint errors

app/ui/src/app/integration/integration_detail/integration-detail.component.ts, app/ui/src/app/store/entity/entity.store.ts
=> fix: ensure errors get propogated properly from the store; ensure the detail page reacts to deleted integration

app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.html, app/ui/src/assets/dictionary/en-GB.json
follow on from #3288 
related to #3174
=> chore: update tooltip for disabled API connector edit button

app/ui/src/app/app.component.html
=> fix: remove text brand element

tools/bin/commands/util/common_funcs, tools/bin/commands/util/openshift_funcs, tools/bin/install-syndesis
=> fix(syndesis): Fix broken --cluster option

tools/bin/commands/install
=> Fix minor glitch with install script

app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.html
=> fix: set the index and make it's usage more apparent

install/operator/deploy/syndesis-operator.yml, tools/bin/commands/install, tools/bin/commands/release, tools/bin/commands/util/operator_funcs
This is a backport for #3340. Should be safe now as it has been tested on master.
Sorry, took a bit (and I burned 1.5.1 and 1.5.2)
=> fix: Release syndesis-operator.yml with the proper version (#3334)

install/generator/01-header.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml
=> fix: ROUTE_HOST_NAME must not be required if used with the operator.

app/ui/src/app/connections/create-page/review/review.component.ts
fixes https://github.com/syndesisio/syndesis/issues/3342
=> allow user to navigate back to connection-basics step from review step when creating connection

app/ui/src/app/integration/list/list.component.html, app/ui/src/app/integration/list/list.component.ts
Fixes #3121.
This requires patternfly/patternfly-ng/pull/435 to be merged and released to work.
=> fix: integration list re-rendering when polling

install/operator/pkg/apis/syndesis/v1alpha1/types.go, install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go, tools/bin/commands/minishift
=> fix(operator): stateCheckInterval was not properly picked up by the operator [backport]

app/connector/kafka/src/main/resources/META-INF/syndesis/connector/kafka.json
This is ready to merge. It should be backported to the branch for 7.1. 
I updated labels and hints to be consistent with other message broker connectors.
=> enhancement: Updated text strings for Kafka connection configuration

app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/support/SupportUtilTest.java, app/server/logging/jsondb/pom.xml, app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java, app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/KubernetesSupport.java, app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/PodLogMonitor.java, app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingControllerTest.java, app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/KubernetesSupportIT.java, app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/TestPodLogMonitor.java
I found a lot of issues with activities, please review thoroughly, details are in the commit messages.
Fundamental change is that we no longer keep 1 days worth of activities, but 50 entries (by default).
Fixes #3337
=> Activity fixes

app/server/logging/jsondb/pom.xml, app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java, app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/KubernetesSupport.java, app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/PodLogMonitor.java, app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingControllerTest.java, app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/KubernetesSupportIT.java, app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/TestPodLogMonitor.java
=> Backport activity fixes

doc/connecting/topics/connecting_to_twitter.adoc, doc/shared/register_with_twitter.adoc, doc/tutorials/topics/t2sf_prereqs.adoc
This is ready for a QA review. Not yet ready to merge.
Keith and Gary reviewed these updates. You can see the updated content in this Google document:
https://docs.google.com/document/d/1qW5X1uQ8NoKaOAOp0_XX5oQuOW2Gme9To84zjEEZuIs/edit#heading=h.6mz88k2e3fnq 
I updated the content in the connector guide, and I also updated the prerequisites in the tutorial. 
Let me know what needs to change. 
Thanks!
=> Update doc to state requirement for Twitter developer account

doc/connecting/topics/register_with_dropbox.adoc
=> user doc: Corrects a reference to an image

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandlerTest.java
Refactors the test and makes sure to handle `Optional<Connection>` in `Integration` `Step` as optional.
Fixes #3384
=> fix(server): don't try to count steps without connections

doc/integrating_applications/topics/about_mapping_data.adoc, doc/integrating_applications/topics/combine_multiple_source_fields_into_one_target_field.adoc, doc/integrating_applications/topics/example_missing_unwanted_data.adoc, doc/integrating_applications/topics/finding_data_field_you_want_to_map.adoc, doc/integrating_applications/topics/map_one_source_field_to_one_target_field.adoc, doc/integrating_applications/topics/mapping_data.adoc, doc/integrating_applications/topics/separate_one_source_field_into_multiple_target_fields.adoc, doc/integrating_applications/topics/transforming_target_data.adoc, doc/tutorials/topics/sf2db_add_mapping_step.adoc, doc/tutorials/topics/t2sf_add_mapping_step.adoc
This is ready for an SME review. It is not ready to merge. 
@pleacu - please review these updates and let me know what needs to change. 
Thanks!
=> user doc: Data mapper doc update for combining and separating, and identifying gaps

doc/connecting/topics/about_implementing_integrations_with_concur.adoc
Ready to merge.
Updates the general procedure for connecting to Concur to clarify that you edit the imported integration in the production environment. You do not create a new integration.
=> user doc: updates procedure after importing a Concur integration

app/connector/rest-swagger/src/main/resources/camel-connector.json, app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackVerifierExtension.java, app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json, app/extension/bom/pom.xml, app/integration/bom/pom.xml, app/pom.xml
Related to #3313 
What I've done:
- Released a 7.2 Fuse Camel and pinned the repo in EA, the version is 2.21.0.fuse-720007
- Same story for CXF stuff: version is 3.1.11.fuse-720009 and cxf-xjc-utils-3.2.3.fuse-720010
- Updated the camel version in Syndesis and use the latest Slack component with consumer
=> feature(slack-connector): Add consumer action

app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/util/SwaggerHelper.java
This is a followup on the JSON detection via regex in #3373 raised in
review (on IRC).
=> refactor(server): followup on the JSON detection

app/connector/telegram/src/main/resources/META-INF/syndesis/connector/telegram.json
=> Fix #3444: making telegram tech preview

app/connector/telegram/src/main/resources/META-INF/syndesis/connector/telegram.json
=> Fix #3444: making telegram tech preview (on 1.4.x)

doc/connecting/master.adoc, doc/connecting/topics/add_servicenow_connection_finish.adoc, doc/connecting/topics/add_servicenow_connection_start.adoc, doc/connecting/topics/add_servicenow_connections.adoc, doc/connecting/topics/connecting_to_servicenow.adoc, doc/connecting/topics/create_servicenow_connection.adoc, doc/connecting/topics/identify_concur_fields_for_mapping.adoc, doc/connecting/topics/supported_connectors.adoc
Ready to merge. 
SME and QE review are both complete. 
For convenience, the new content is in this Google document:
https://docs.google.com/document/d/10ncO_l2IERUjQNfl2Jtof8O7KtosBKjz6m1j9c2qfg0/edit?usp=sharing
The related doc Jira: 
https://issues.jboss.org/browse/FUSEDOC-2632
=> user doc: user doc for ServiceNow connector

tools/upgrade/Dockerfile, tools/upgrade/migration/resource/1.1/02_db_config_map.sh, tools/upgrade/migration/resource/1.1/03_server_config_map_upgrade.sh, tools/upgrade/migration/resource/1.1/04_label_updates.sh, tools/upgrade/migration/resource/1.1/05_annotation_updates.sh
* chore(upgrade): migration scripts for 1.4.x
This adds migration scripts for OpenShift resources from version 1.3.x
to 1.4.x.
Fixes #3443.
=> chore(upgrade): migration scripts for 1.4.x (#3447)

doc/connecting/topics/add_concur_connection.adoc, doc/connecting/topics/connecting_to_concur.adoc, doc/connecting/topics/triggering_integrations_with_http_requests.adoc
Also, I added "(Webhook)" to the title of the page that starts the Webhook content.
=> user doc: Mark Concur as tech preview. 

doc/connecting/topics/connecting_to_concur.adoc, doc/connecting/topics/identify_concur_fields_for_mapping.adoc, doc/connecting/topics/obtain_concur_oauth_credentials_implementation.adoc
And an update in the wording about obtaining credentials.
=> user doc: Say what Concur is, offset param not required.

app/ui/src/app/connections/list/list.component.html, app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.html, app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html
fixes https://github.com/syndesisio/syndesis/issues/3508
=> bug(blank-slate): update blank slate primary action button

app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/store/step/step.store.ts
=> fix: avoid NPE and hide basic filter if there's no output data shape in any previous connection

app/ui/src/app/connections/list/list.component.scss
fix https://github.com/syndesisio/syndesis/issues/3489
=> bug(connections): fix "configuration required" spacing in connection list

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/integration/edit-page/action-select/action-select.component.ts, app/ui/src/app/integration/edit-page/common/cancel-add-step.component.ts, app/ui/src/app/integration/edit-page/connection-select/connection-select.component.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts, app/ui/src/app/integration/edit-page/edit-page.component.ts, app/ui/src/app/integration/edit-page/flow-page.service.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.ts, app/ui/src/app/integration/edit-page/integration-basics/integration-basics.component.ts, app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.ts, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts, app/ui/src/app/integration/edit-page/step-select/step-select.component.ts, app/ui/src/app/integration/integration.module.ts
As eventually we'll need to do this anyways when we further adjust the routes to add the choose operation page.
=> feat: add the flow ID to the route instead of using the fragment

app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
=> Unable to edit imported integrations

doc/shared/create_sf_connection.adoc, doc/shared/register_with_sf.adoc, doc/shared/register_with_twitter.adoc, doc/tutorials/master-docinfo.xml, doc/tutorials/topics/amq2api_add_damage_reporter_step.adoc, doc/tutorials/topics/amq2api_add_mapping_step.adoc, doc/tutorials/topics/amq2api_choose_finish.adoc, doc/tutorials/topics/amq2api_choose_start.adoc, doc/tutorials/topics/amq2api_confirm_works.adoc, doc/tutorials/topics/amq2api_create_connection_to_broker.adoc, doc/tutorials/topics/amq2api_intro.adoc, doc/tutorials/topics/amq2api_name_and_publish.adoc, doc/tutorials/topics/amq2api_start_the_broker.adoc, doc/tutorials/topics/clean_up.adoc, doc/tutorials/topics/comparison_of_sample_integrations.adoc, doc/tutorials/topics/sf2db_add_mapping_step.adoc, doc/tutorials/topics/sf2db_choose_finish.adoc, doc/tutorials/topics/sf2db_choose_start.adoc, doc/tutorials/topics/sf2db_create_db_connection.adoc, doc/tutorials/topics/sf2db_name_and_publish.adoc, doc/tutorials/topics/sf2db_prereqs.adoc, doc/tutorials/topics/t2sf_add_filter_step.adoc, doc/tutorials/topics/t2sf_add_mapping_step.adoc, doc/tutorials/topics/t2sf_choose_finish.adoc, doc/tutorials/topics/t2sf_choose_start.adoc, doc/tutorials/topics/t2sf_confirm_working.adoc, doc/tutorials/topics/t2sf_name_and_publish.adoc, doc/tutorials/topics/t2sf_prereqs.adoc
Adds more data to the sample integration comparison table. 
Ensures that it is clear that you are logged in to Syndesis and in the Syndesis UI.
=> user doc: Updates for ease of use based on feedback in the minimalism review.

app/ui/src/app/core/providers/form-factory-provider.service.ts
=> feat: enable date support for dynamic form input

install/generator/03-syndesis-ui.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml
Hi @rhuss, it seems run.sh in install/generator worked for me, could you just double check if it's not missing anything?
=> chore: Enable AtlasMap Data Preview in openshift template

app/ui/src/app/platform/types/form-factory/form-factory.service.ts
=> fix: unset empty password strings

app/ui/src/app/api/api.module.ts, app/ui/src/app/api/providers/api-http-provider.service.ts, app/ui/src/app/common/editable/index.ts, app/ui/src/app/connections/common/configuration/configuration.service.ts, app/ui/src/app/core/providers/i18n-provider.service.ts, app/ui/src/app/core/providers/integration-support-provider.service.ts, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.ts, app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.ts, app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.ts, app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.ts, app/ui/src/app/integration/api-provider/operations.component.ts, app/ui/src/app/integration/edit-page/current-flow.service.spec.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/edit-page.component.ts, app/ui/src/app/integration/edit-page/flow-page.service.ts, app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts, app/ui/src/app/integration/integration_detail/integration-detail.component.ts, app/ui/src/app/platform/types/i18n/i18n.effects.ts, app/ui/src/app/platform/types/integration/integration.reducer.ts, app/ui/src/app/settings/settings-root.component.ts, app/ui/src/app/store/connection/connection.store.ts, app/ui/src/app/store/connector/connector.service.ts, app/ui/src/app/store/entity/entity.store.ts, app/ui/src/app/store/integration/integration.service.ts, app/ui/src/tsconfig.app.json
I noticed quite a bit of unused code around the app. I enabled the relative tsconfig option to get an error when this happens, and fixed what I found.
=> chore: turn on Typescript's noUnusedLocals

app/ui/src/app/common/loading/loading.component.html, app/ui/src/app/common/loading/loading.component.ts, app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.html, app/ui/src/app/connections/detail-page/detail-page.component.ts, app/ui/src/app/connections/list/list.component.html, app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html, app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.html, app/ui/src/app/customizations/tech-extensions/tech-extension-delete-modal.component.html, app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html, app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.html, app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html, app/ui/src/app/integration/api-provider/operations.component.html, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html, app/ui/src/app/integration/edit-page/action-select/action-select.component.html, app/ui/src/app/integration/edit-page/connection-select/connection-select.component.html, app/ui/src/app/integration/edit-page/describe-data/describe-data.component.html, app/ui/src/app/integration/edit-page/edit-page.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html, app/ui/src/app/integration/edit-page/list-actions/list-actions.component.html, app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.html, app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.component.html, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html, app/ui/src/app/integration/edit-page/step-select/step-select.component.html, app/ui/src/app/integration/integration_detail/integration-detail.component.html, app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.html, app/ui/src/app/integration/list-page/list-page.component.html, app/ui/src/app/settings/oauth-apps/oauth-apps.component.html, app/ui/src/app/support/support.component.html
and update all the code using it.
fixes #3587 now code can pass a template ref to `syndesis-loading` using the `content` input:
```
<syndesis-loading [loading]="whatevs" [content]="ref">
<ng-template #ref>
<span>Hello! {{ stuff("world!") }}</span>
</ng-template>
</syndesis-loading>
```
In this case `stuff()` doesn't get called until `whatevs` is false.
=> fix: update syndesis-loading to accept a TemplateRef too

app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationBase.java
=> Deprecate methods in Integration Builder

install/generator/01-header.yml.mustache
=> chore(install): Remove SYNDESIS_REGISTRY for productised templates

app/connector/google-calendar/pom.xml, app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarGetEventCustomizer.java, app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarMetaDataAutoConfiguration.java, app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarMetaDataExtension.java, app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarMetaDataRetrieval.java, app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarSendEventCustomizer.java, app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarUpdateEventCustomizer.java, app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarVerifier.java, app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarVerifierAutoConfiguration.java, app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarVerifierExtension.java, app/connector/google-calendar/src/main/resources/META-INF/spring.factories, app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json, app/connector/google-calendar/src/test/resources/logback-test.xml, app/connector/pom.xml, app/connector/rest-swagger/src/main/resources/camel-connector.json, app/connector/support/catalog/pom.xml, app/extension/bom/pom.xml, app/integration/bom/pom.xml, app/meta/pom.xml, app/pom.xml, app/server/runtime/src/test/java/io/syndesis/server/runtime/SetupITCase.java
Related to #3454 
The connector works fine, we still need to add additional options to the create and update operation, but the basic stuff is done.
I noticed that Atlasmap repors warning while parsing the Event model class from Google API, this is something to check for @igarashitm , a part the warnings and some options the connector is done.
=> feat(connectors): New Google-Calendar connector

app/ui/src/app/integration/api-provider/operations.component.html, app/ui/src/app/integration/api-provider/operations.component.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/step-select/step-select.component.html, app/ui/src/app/integration/edit-page/step-select/step-select.component.ts, app/ui/src/app/settings/oauth-apps/oauth-apps.component.html, app/ui/src/app/settings/oauth-apps/oauth-apps.component.ts
=> fix: update oauth apps and operations page to use the syndesis toolbar wrapper

app/ui/src/app/integration/edit-page/step-select/step-select.component.html
=> fix: revert some unintended template changes

doc/integrating_applications/topics/about_steps.adoc, doc/integrating_applications/topics/add_steps.adoc, doc/integrating_applications/topics/add_template_step.adoc
* Updates to the user handbook on details of the template step
=> (docs) Update documentation to include explanation of template step

app/connector/webhook/src/main/resources/META-INF/syndesis/connector/webhook.json
Related to:
https://issues.jboss.org/browse/ENTESB-9509
=> refactor(webhook): Updated the action text

app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.html, app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.scss, app/ui/src/assets/dictionary/en-GB.json
* Changes legends to labels
* Refactors label text to i18n
fixes #3630
=> fix(template-step): Correct UX elements of template step page

app/common/model/src/main/java/io/syndesis/common/model/metrics/IntegrationMetricsSummary.java, app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/HttpQuery.java, app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/PrometheusConfigurationProperties.java, app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/PrometheusMetricsProviderImpl.java, app/ui/karma.conf.js, app/ui/src/app/dashboard/dashboard.component.html, app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html, app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.ts, app/ui/src/app/platform/types/integration/integration.models.ts, app/ui/src/app/platform/types/integration/integration.reducer.ts
=> Add top 5 integrations map of ids to total messages to Prometheus total metrics summary

app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.html, app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.scss, app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.ts, app/ui/src/assets/dictionary/en-GB.json
fix https://github.com/syndesisio/syndesis/issues/3660
@phantomjinx I changed [L15 in templater.component.ts](https://github.com/michael-coker/syndesis/blob/2b5d67cb58b0c306e35e3c658814887f8b04c321/app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.ts#L115) to address the default selected radio button issue. Can you verify that didn't negatively impact anything else?
=> fix(templateStep): match template step UI to UXD designs

app/server/api-generator/pom.xml, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelper.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelperTest.java
=> fix: sanitize operation tags in OpenAPI

app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
=> fix: avoid NPE if there's no available datashape for the step config page

app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.ts
=> fix: time formatting location aware

app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/customizers/ServiceNowImportSetCustomizer.java, app/pom.xml, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/dto/MetaData.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/api/ApiHandler.java, ruleset.xml
=> refactor: remove `/apis/generator/save` endpoint

doc/sdh/development/comms.adoc, doc/sdh/development/index.adoc
Section to be included in the developer handbook dealing with github issues/notifications.
=> First draft github issues introduction

app/ui/src/app/connections/common/configuration/configuration.service.ts, app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.ts
=> fix: ensure any initial default values are set as config properties

app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java
=> fix(server): NPE in API provider Integration generation

app/common/model/src/main/java/io/syndesis/common/model/action/Action.java, app/common/model/src/main/java/io/syndesis/common/model/action/ConnectorAction.java, app/common/model/src/main/java/io/syndesis/common/model/action/ConnectorDescriptor.java, app/common/model/src/main/java/io/syndesis/common/model/action/StepAction.java, app/common/model/src/main/java/io/syndesis/common/model/action/StepDescriptor.java, app/common/model/src/main/java/io/syndesis/common/model/bulletin/LeveledMessage.java, app/common/model/src/main/java/io/syndesis/common/model/connection/Connection.java, app/common/model/src/main/java/io/syndesis/common/model/connection/Connector.java, app/common/model/src/main/java/io/syndesis/common/model/extension/Extension.java, app/common/model/src/main/java/io/syndesis/common/model/integration/Flow.java, app/common/model/src/main/java/io/syndesis/common/model/integration/Integration.java, app/common/model/src/main/java/io/syndesis/common/model/integration/Step.java, app/common/model/src/main/java/io/syndesis/common/model/support/EquivContext.java, app/common/model/src/main/java/io/syndesis/common/model/support/EquivPair.java, app/common/model/src/main/java/io/syndesis/common/model/support/Equivalencer.java, app/common/model/src/test/java/io/syndesis/common/model/support/EquivalencerTest.java, app/common/util/src/main/java/io/syndesis/common/util/StringConstants.java, app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java, app/server/update-controller/src/test/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandlerTest.java
* Refactors equivalence into single Equivalencer class to allow for
better control and maintenance;
* Adds detail element to LeveledMessage
* Equivalencer
* Builds a tree of objects while testing equivalence then converts the
tree into a single message should the equivalence fail.
* IntegrationUpdateHandler
* Adds the equivalencer message to the detail field of the LeveledMessage.
* Provides the detail for a future component to display without disturbing
current functionality in the UI (expects message to be null if a code is
included).
fixes #3667
=> fix(notifications): Extract reasoning for artifacts differing

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
=> refactor IVP code 

app/connector/rest-swagger/src/main/resources/camel-connector.json, app/extension/bom/pom.xml, app/integration/bom/pom.xml, app/pom.xml
=> fix(connector): fix the delay option on slack connector

app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/BaseSwaggerConnectorGenerator.java
This fixes two more places where we need to sanitize tags from the
received Swagger.
Fixes #3688
=> fix(server): Swagger tags sanitization

app/connector/http/pom.xml, app/connector/http/src/main/java/io/syndesis/connector/http/HttpConnectorFactories.java
=> fix(connector): Http Connector - HTTP Consumer fails to follow redirect.

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
fixes https://github.com/syndesisio/syndesis/issues/3794
=> refactor(IVP): remove alert from data mismatch icon popover

app/integration/bom/pom.xml, app/pom.xml, app/ui/package.json, app/ui/yarn.lock
Contains:
* atlasmap/atlasmap#606
* atlasmap/atlasmap#618 - Cc: @johnpoth 
* atlasmap/atlasmap#588
* atlasmap/atlasmap#77
* atlasmap/atlasmap#77
* atlasmap/atlasmap#609
* atlasmap/atlasmap#77
* atlasmap/atlasmap#556
* atlasmap/atlasmap#600
* atlasmap/atlasmap#77
* atlasmap/atlasmap#550
=> chore: Update to AtlasMap 1.38.0

app/ui/src/app/common/openapi/editor/editor.component.scss, app/ui/src/app/integration/edit-page/flow-view/flow-view-multiflow.component.scss, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
fixes https://github.com/syndesisio/syndesis/issues/3811, fixes https://github.com/syndesisio/syndesis/issues/3816
=> refactor(IVP): fix the lines and overlapping with the api multistep icon in the IVP

.circleci/config.yml
=> chore: Add update pod building to circleci build

app/ui/src/app/common/openapi/uploader/uploader.component.html, app/ui/src/app/common/openapi/uploader/uploader.component.ts, app/ui/src/assets/dictionary/en-GB.json
=> fix: allow uploading openapi specs as yaml

app/ui/src/app/common/common.module.ts, app/ui/src/app/common/date.pipe.ts, app/ui/src/app/common/index.ts, app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html, app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.ts, app/ui/src/app/integration/integration_detail/integration-metrics.component.html, app/ui/src/app/integration/integration_detail/integration-metrics.component.ts, app/ui/src/app/integration/integration_detail/integration_activity/integration-activity.component.html, app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.html, app/ui/src/app/integration/integration_logs/integration-logs.component.html
Drop Angular's date pipe usage in favor of synDate, which uses moment for the date formatting
Closes #2500
=> fix: consistent date formatting across the UI

app/ui/src/app/common/openapi/editor/editor.component.scss, app/ui/src/app/integration/edit-page/flow-view/flow-view-multiflow.component.scss, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
fixes https://github.com/syndesisio/syndesis/issues/3830
=> fix(API/Apicurio): fix z-index issue with apicurio editor when creating API integration

app/ui/src/app/integration/integration_detail/integration-description.component.html, app/ui/src/app/integration/integration_detail/integration-description.component.scss, app/ui/src/app/integration/list/list.component.html, app/ui/src/app/integration/list/list.component.scss
fixex https://github.com/syndesisio/syndesis/issues/3601
=> bug(badge): fix oval shape for api flow count badge, add tooltip

app/ui/src/app/integration/integration_detail/integration-description.component.html, app/ui/src/app/integration/integration_detail/integration-description.component.scss
fixes https://github.com/syndesisio/syndesis/issues/3843
=> feat(integrationdetails): add support for step icons

app/ui/src/app/integration/edit-page/flow-page.service.ts, app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.html, app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.ts
=> fix: save the integration when going back to the operation list

.circleci/config.yml, doc/sdh/cli/cmd_build.adoc, tools/bin/commands/build
See also help page. Also switched circle build to use "syndesis" for
creating the upgrade pod.
Fixes #3463.
=> feature(syndesis): Add '-m upgrade' for creating the upgrade pod

app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-page.component.html
Proper page scrolling with many operations. Also, doesn't log errors in the console
=> fix: proper page scrolling with many operations.

app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/BaseSwaggerConnectorGenerator.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/OperationDescription.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelper.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGeneratorTest.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelperOperationDescriptionGenerationTest.java, app/server/api-generator/src/test/resources/swagger/empty-summary.json
=> Empty first column in the integration flow view

app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderStartEndpointCustomizer.java
This removes all non-Syndesis Camel message headers that have been introduced via the HTTP request arriving at the REST endpoint.
Fixes #3865
=> fix(connector): remove all non-Syndesis headers

app/ui/src/app/store/step/step.store.ts
=> fix: only allow the data mapper to be used if the next step that has a datashape is not none/any

app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
=> fix: add IVP titles for the API Provider pages

app/ui/src/app/integration/integration-actions-provider.service.ts, app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.html, app/ui/src/app/platform/types/integration/integration-actions.service.ts
=> fix: ensure the publish draft button is available for a running integration

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
=> fix: hide flow name in the IVP when creating a new integration

app/ui/src/app/app.component.ts, app/ui/src/app/integration/edit-page/action-select/action-select.component.ts, app/ui/src/app/integration/edit-page/connection-select/connection-select.component.ts
=> fix: handle redirect to the api provider creation page when hitting the browser's back button

app/ui/src/app/integration/edit-page/current-flow.service.ts
Part of #3546 CC @nicolaferraro
=> fix: hide API Provider from the list of end connections

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
=> fix: swap ngif blocks from likely bad merge

app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
=> fix: manually trigger data mapper line machine component after init

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/integration/edit-page/common/cancel-add-step.component.ts, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
=> fix: check the metadata map for a step when canceling to ensure we don't delete steps that have no config

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss, app/ui/src/app/integration/integration_detail/integration-description.component.scss
fix https://github.com/syndesisio/syndesis/issues/3903
=> fix(integration-details): fix off-center connection/step icons

doc/shared/log_in.adoc, doc/tutorials/topics/amq2api_choose_start.adoc, doc/tutorials/topics/amq2api_create_integration.adoc, doc/tutorials/topics/amq2api_intro.adoc, doc/tutorials/topics/comparison_of_sample_integrations.adoc, doc/tutorials/topics/sf2db_choose_start.adoc, doc/tutorials/topics/sf2db_create_integration.adoc, doc/tutorials/topics/sf2db_intro.adoc, doc/tutorials/topics/t2sf_choose_start.adoc, doc/tutorials/topics/t2sf_intro.adoc
This is a format update for modularizing the tutorials.
=> user doc: Replace <<id>> style xrefs with full path xrefs.

app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/BaseDataShapeGenerator.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java, app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.ts
Fix #3780.
I've tried to implement also the FE side.. so, better taking a look ;)
=> Fix #3780: use default return code on edit

app/connector/webhook/src/main/java/io/syndesis/connector/webhook/WebhookConnectorCustomizer.java, app/connector/webhook/src/test/java/io/syndesis/connector/webhook/WebhookConnectorCustomizerTest.java
This places the removal of `Exchange.HTTP_URI` header before the next
processor (consumer) after the Webhook connector so that the existence
of that header doesn't override the URL configured on a subsequent HTTP
based component that would take preference of `Exchange.HTTP_URI` header
over the configured endpoint/component properties.
Fixes #3729
=> chore(connector): remove `Exchange.HTTP_URI` header

doc/tutorials/master.adoc, doc/tutorials/topics/amq2api_intro.adoc, doc/tutorials/topics/comparison_of_sample_integrations.adoc, doc/tutorials/topics/sf2db_intro.adoc, doc/tutorials/topics/t2sf_intro.adoc
=> user doc: Prefix xrefs with "link:"

app/common/util/src/main/java/io/syndesis/common/util/Names.java, app/common/util/src/test/java/io/syndesis/common/util/NamesTest.java
This appends or replaces the last non alphanumeric character with `0`. It should replace only if the string is at the maximum length of 63, and append otherwise.
Fixes #3925
=> fix(server): make sure the sanitized name has a last alphanumeric character

doc/tutorials/topics/amq2api_intro.adoc, doc/tutorials/topics/comparison_of_sample_integrations.adoc
Small small fixes to link formats.
=> user doc: Correcting link format

app/ui/src/app/integration/integration_detail/integration-description.component.html, app/ui/src/app/integration/list/list.component.html
fixes https://github.com/syndesisio/syndesis/issues/3942
=> fix(integration): remove flow count from api integration icon

app/ui/src/app/integration/edit-page/flow-view/flow-view.component.ts
fixes https://github.com/syndesisio/syndesis/issues/3875
=> fix(integration-editor): fix "add a step" disappearing from IVP popover menus

install/operator/.gitignore, install/operator/pkg/syndesis/configuration/configuration_test.go, install/operator/pkg/util/resources_test.go, install/operator/test/resources/dep.json, tools/bin/commands/build, tools/bin/commands/util/operator_funcs
1. ran `go fmt`
2. add `go fmt` `pre-commit` hook
3. fixed tests
4. tests are now run with `syndesis` script
=> Several cleanups for the operator

app/ui/src/app/settings/oauth-apps/oauth-apps.component.html
fixes https://github.com/syndesisio/syndesis/issues/3963
=> chore(settings): remove blue border from oauth app icons

app/integration/bom/pom.xml, app/pom.xml, app/ui/package.json, app/ui/yarn.lock
Contains 18 bug fixes:
* atlasmap/atlasmap#617
* atlasmap/atlasmap#504
* atlasmap/atlasmap#621
* atlasmap/atlasmap#385
* atlasmap/atlasmap#632
* atlasmap/atlasmap#566
* atlasmap/atlasmap#624
* atlasmap/atlasmap#622
* atlasmap/atlasmap#631
* atlasmap/atlasmap#601
* atlasmap/atlasmap#581
* atlasmap/atlasmap#565
* atlasmap/atlasmap#647
* atlasmap/atlasmap#633
* atlasmap/atlasmap#652
* atlasmap/atlasmap#653
* atlasmap/atlasmap#655
* atlasmap/atlasmap#657
=> chore: Update to AtlasMap 1.38.1

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
fixes https://github.com/syndesisio/syndesis/issues/3973
=> bug(integration): Wrong position for warning icon on steps in IVP

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
fixes https://github.com/syndesisio/syndesis/issues/397
=> fix(integration): show return path icon as end connection in API integration

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
from these PR's
* https://github.com/syndesisio/syndesis/pull/3979
* https://github.com/syndesisio/syndesis/pull/3978
=> fix(integration): move data mismatch warning icon on steps in IVP, update API integration return path icon in IVP

.circleci/config.yml, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
=> fix: avoid NPE

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts, app/ui/src/app/store/step/step.store.ts
=> fix: rework datashape testing logic, also fix an NPE in the flow view step component

app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
The code currently treats the password as required.
=> password should be marked as required

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts, app/ui/src/app/store/step/step.store.ts
=> fix: rework datashape testing logic, also fix an NPE in the flow view step component (1.5.x)

app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.html, app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.scss
fixes https://github.com/syndesisio/syndesis/issues/3989
=> fix(customizations): remove nested card, unused css in api client connector review step.

install/generator/07-syndesis-upgrade.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml
=> Fix #4010: remove unneeded subpath

doc/sdh/cli/cmd_build.adoc, doc/sdh/cli/cmd_install.adoc, doc/sdh/cli/index.adoc, doc/sdh/development/local.adoc, doc/sdh/introduction.adoc
Fixed some typos in Software developer handbook. Added some small improvements. Also converted markdown headings to AsciiDoc headings.
=> Developer handbook fixes

app/ui/src/app/settings/oauth-apps/oauth-app-form.component.html, app/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts, app/ui/src/app/settings/oauth-apps/oauth-apps.component.html, app/ui/src/app/settings/oauth-apps/oauth-apps.component.ts
=> fix: fetch from the backend after a save & validate form

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html, app/ui/src/app/integration/edit-page/action-select/action-select.component.html, app/ui/src/app/integration/edit-page/connection-select/connection-select.component.html, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/describe-data/describe-data.component.html, app/ui/src/app/integration/edit-page/edit-page.component.ts, app/ui/src/app/integration/edit-page/integration-basics/integration-basics.component.html, app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.html, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html, app/ui/src/app/integration/edit-page/step-select/step-select.component.html
=> fix: only provide a link when the target integration is created, also cleanup editor state

app/integration/project-generator/pom.xml, app/pom.xml
=> fix(version): upgrade commons-compress to version 1.18

app/connector/rest-swagger/src/main/resources/META-INF/spring.factories
Fixes #4073
(cherry picked from commit 625474679e05860e86978ff1ef30c93637ecdd15)
=> fix(connector): include Spring configuration (1.5.x backport)

app/connector/rest-swagger/src/main/resources/META-INF/spring.factories
=> fix(connector): include Spring configuration

app/connector/fhir/pom.xml, app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirReadCustomizer.java, app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirReadMessageModel.java
=> Fix #4034: Resource id value cannot be passed for fhir read action

app/pom.xml
=> fix(dependencies): Upgrade Spring to version 4.3.17.RELEASE

tools/upgrade/migration/resource/1.2/01_server_config_map_upgrade.sh
=> chore(upgrade): upgrade image stream tag in the syndesis-server-config ConfigMap

app/ui/src/app/integration/integration_detail/integration_activity/integration-activity.component.html
=> [fix] Correct date format in integration activity log

app/connector/ftp/src/main/resources/META-INF/syndesis/connector/ftp.json, app/connector/http/src/main/resources/META-INF/syndesis/connector/http4.json, app/connector/http/src/main/resources/META-INF/syndesis/connector/https4.json
=> more sensible defaults

install/operator/deploy/syndesis-operator.yml, tools/bin/commands/minishift, tools/bin/commands/util/openshift_funcs
This _should_ fix the issues caused by the OAuthClient change. Would like to hear feedback if it works for your use cases.
Fixes #4093
=> Fixes for OAuthClient caused issues

tools/bin/commands/util/openshift_funcs
We need to use the `syndesis-privileged.yml` template with `--local`, fix a typo in the script.
=> Syndesis tool fixes

tools/bin/commands/install
=> fix: fix unbound variable error

doc/sdh/cli/cmd_build.adoc, tools/bin/commands/build
In response to https://github.com/syndesisio/syndesis/pull/4110#discussion_r234896225
=> Fix #4109: Add missing docs

install/operator/deploy/syndesis-operator.yml
=> fix: add ${NAMESPACE} to cluster wide resources

app/connector/gmail/src/main/java/io/syndesis/connector/gmail/GmailReceiveEmailCustomizer.java, app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json, app/connector/google-calendar/pom.xml, app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarEventsCustomizer.java, app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarGetEventCustomizer.java, app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarMetaDataExtension.java, app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarSendEventCustomizer.java, app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarUpdateEventCustomizer.java, app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/utils/GoogleCalendarUtils.java, app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json, app/connector/google-calendar/src/test/resources/logback-test.xml
Found some improvements for google-calendar and gmail connectors.
- fixed gmail related references in google-calendar connector
- removed obsolete javax.mail dependency in google-calendar connector
- set input/output data shape names in order to improve display in data mapper
=> Google connector improvements

app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/stream/GoogleSheetsStreamComponent.java, app/meta/pom.xml, app/server/runtime/src/test/java/io/syndesis/server/runtime/SetupITCase.java
Incorporated review comments for PR #4129
=> Google sheets connector basics reviewed

doc/connecting/master.adoc, doc/connecting/topics/add_slack_connection_start.adoc, doc/connecting/topics/add_telegram_connection_middle_finish.adoc, doc/connecting/topics/add_telegram_connection_start.adoc, doc/connecting/topics/connecting_to_telegram.adoc, doc/connecting/topics/creating_telegram_connections.adoc, doc/connecting/topics/supported_connectors.adoc
This is the new content for the Telegram connector
=> user doc: Initial draft of doc for Telegram connector

tools/upgrade/migration/preflight.sh
=> [closes #4173] Fix parsing minor version

app/ui/src/assets/dictionary/en-GB.json
=> chore: update version in dictionary

app/ui/src/assets/dictionary/en-GB.json
=> chore: update version in dictionary - 1.5.x

doc/connecting/topics/add_gmail_connection_start.adoc, doc/connecting/topics/add_telegram_connection_middle_finish.adoc, doc/connecting/topics/creating_telegram_connections.adoc, doc/connecting/topics/supported_connectors.adoc, doc/integrating_applications/topics/create_api_provider_integration.adoc
Outstanding questions about the Telegram connector were answered by Michael Cada.
I noticed a few other updates that were helpful while I was doing this. 
Ready to merge.
=> user doc: Updates to Telegram connector doc and two other updates.

app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsAddChartCustomizer.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesCustomizer.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/CellCoordinate.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/GoogleChart.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/GoogleValueRange.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/RangeCoordinate.java, app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsAddChartCustomizerTest.java, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesCustomizerTest.java, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesSplitResultsCustomizerTest.java, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/model/CellCoordinateTest.java, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/model/RangeCoordinateTest.java
Adding pie chart support and simplify range to cell coordinate conversion
=> Update #3620 Google sheets: Add pie chart support

doc/integrating_applications/topics/how_to_specify_data_shapes.adoc
Ready to merge. 
This is an update to the info about specifying data shapes in extensions.
=> user doc: Clarify how to obtain Java inspection result.

app/pom.xml, app/ui/package.json, app/ui/yarn.lock
Please have a look at the versions, some of them have small some of them have large jumps. I've tested locally and it seems to be OK.
=> Several upgrades to address issues reported by Snyk

app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsAddPivotTableCustomizer.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/CellCoordinate.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/GooglePivotTable.java, app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsAddPivotTableCustomizerTest.java
Add capability to create pivot tables on google sheets connector
=> Update #3620: Add pivot table support in Google sheets

doc/connecting/topics/adding_amq_connection_middle.adoc, doc/connecting/topics/adding_amq_connection_start.adoc, doc/connecting/topics/adding_amqp_connection_middle.adoc, doc/connecting/topics/adding_amqp_connection_start.adoc, doc/tutorials/topics/amq2api_confirm_works.adoc, doc/tutorials/topics/sf2db_confirm_works.adoc, doc/tutorials/topics/t2sf_confirm_working.adoc
Ready to merge. 
These updates should not be merged to the 1.5.x branch since they did not make it into the 7.2 user doc that is on the customer portal.
=> Post release updates

install/generator/03-syndesis-ui.yml.mustache
=> chore: update productized app name

install/generator/03-syndesis-ui.yml.mustache
=> chore: update productized app name (1.5.x)

app/ui/src/app/integration/edit-page/current-flow.service.spec.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/flow-functions.ts, app/ui/src/app/integration/edit-page/index.ts, app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.ts
fixes #4294
@riccardo-forina FYI
This covers the rest of the functions, mainly all the step accessor functions that components use to look at data shapes etc.  Now it's all in one big file, but I figure we can break up that file soon enough when needed.
=> chore: Additional current flow refactoring

app/extension/bom/pom.xml, app/integration/bom/pom.xml, app/pom.xml
=> fix(build) Build on master fails with an empty m2 repository

app/meta/pom.xml, app/meta/src/main/java/io/syndesis/connector/meta/EndpointMetricsFilter.java, app/meta/src/main/resources/application.yml, app/pom.xml
fix #4292 
Note: I tried hard to unit test `EndpointMetricsFilter.java` but had to give up due to the ridiculous amount of mocking required.
=> fix(meta): Monitoring - Instrument Syndesis Meta API

app/connector/fhir/src/test/java/io/syndesis/connector/fhir/processor/FhirResourceProcessorTest.java, app/connector/support/maven-plugin/src/main/java/io/syndesis/connector/support/maven/GenerateResourceInspectionsMojo.java, app/integration/bom/pom.xml, app/pom.xml, app/ui/package.json, app/ui/yarn.lock
This update contains topmost collection support for JSON document
=> chore: Update to AtlasMap 1.39.0

app/server/runtime/pom.xml, app/server/runtime/src/main/java/io/syndesis/server/runtime/EndpointMetricsFilter.java, app/server/runtime/src/main/resources/application.yml
=> fix(server): Monitoring - Instrument Syndesis Server API

app/ui/src/app/support/support.component.html
Remove 1GB attachment limit on Help -> Support page #4208
=> [fix] Remove 1GB attachment limit on Help -> Support page #4208

app/connector/fhir/pom.xml, app/connector/fhir/src/main/java/io/syndesis/connector/fhir/verifier/FhirVerifierExtension.java, app/connector/fhir/src/main/resources/META-INF/syndesis/connector/fhir.json, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirCreateTest.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirCreateWithBasicAuthTest.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirCreateWithBearerTokenAuthTest.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirDeleteTest.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirDeleteWithBasicAuthTest.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirDeleteWithBearerTokenAuthTest.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirReadTest.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirReadWithBasicAuthTest.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirReadWithBearerTokenAuthTest.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirTestBase.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirUpdateTest.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirUpdateWithBasicAuthTest.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirUpdateWithBearerTokenAuthTest.java, app/connector/fhir/src/test/resources/io/syndesis/connector/fhir/metadata_response.xml
I have an issue with building this locally with checks enabled. It fails due to:
`[WARNING] /home/rafal/.m2/repository/io/syndesis/common/common-model/1.6-SNAPSHOT/common-model-1.6-SNAPSHOT.jar(/io/syndesis/common/model/WithConfigurationProperties.class):[-1,-1] Cannot find annotation method 'value()' in type 'edu.umd.cs.findbugs.annotations.SuppressFBWarnings': class file for edu.umd.cs.findbugs.annotations.SuppressFBWarnings not found`
It started to happen after adding tests.
I have no idea why it happens. Does anyone have a clue?
=> Fix #4278 Support basic and bearer token authentication in FHIR

app/ui/src/app/common/date.pipe.ts
=> fix: Show n/a if there's no lastProcessed value for an integration

tools/upgrade/migration/resource/1.6/01_db_metrics_config_map.sh
=> fix: Add upgrade script to create ConfigMap for postgres exporter

app/integration/runtime-springboot/src/test/java/io/syndesis/integration/runtime/sb/capture/OutMessageCaptureProcessorTest.java
The last message capture processor is placed after the mock endpoint. Following from that there is a racing condition between `mock.assertIsSatisfied();` and the message capture processor to add the message to the exchange.
I have added a check to wait for the exchanges to be completed. This makes sure that the last message capture processor has been completed before doing some assertions.
This flaky behavior just occurred in the two unit tests that are using a scheduler. All other tests use `template.sendBody(...)` to trigger the test route which per definition waits for exchanges to be completed before returning.
=> Fix #4389 flaky message capture processor unit test

app/ui/src/app/integration/integration_detail/integration-detail.component.ts
=> fix: Filter undefined values in detail page

app/ui/src/app/integration/edit-page/edit-page.component.ts
Spotted an issue switching flows that I introduced when refactoring while looking at the operations page, this sorts it.
=> fix: ensure the flow ID is set properly

app/ui/src/app/common/ui-patternfly/list-toolbar/list-toolbar.component.ts, app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-page.component.html, app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-page.component.ts
in support of #4318
It only gets the ball rolling at least by reworking the columns as suggested by the design, adding the buttons, changing the default sort etc. but I did also find some issues with the toolbar component that needed to be dealt with.
=> chore: juggle around the columns and misc toolbar component fixes

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/BodyLogger.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/logging/BodyLoggerTest.java
Add proper toString conversion of list and array elements in body logger.
Fixes #4407
=> Fix #4407 Log step does not show body properly

app/server/runtime/src/main/java/io/syndesis/server/runtime/EndpointMetricsFilter.java, install/addons/syndesis-server-rest-api-dashboard.yml
=> feat(monitoring): Show Syndesis Server REST API metrics in a Grafana dashboard

install/addons/syndesis-jdbc-dashboard.yml
=> feat(monitoring): Show Syndesis Server JDBC metrics in a Grafana dashboard

app/connector/support/maven-plugin/src/main/java/io/syndesis/connector/support/maven/GenerateConnectorInspectionsMojo.java, app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java, app/integration/bom/pom.xml, app/pom.xml, app/ui/package.json, app/ui/yarn.lock
This contains Java topmost collection support and several bug fixes
Cc: @lburgazzoli
=> chore: Update to AtlasMap 1.39.1

app/ui/src/app/integration/edit-page/flow-view/flow-view.component.ts, app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.ts, app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
fixes #4444
I got tired of hitting the expander manually to get to the trash icon to test it.
=> fix: make the trash button work again, also expand the IVP at the save/add step page

app/ui/src/app/common/icon-path.pipe.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/flow-functions.ts, app/ui/src/app/integration/list/list.component.html
=> feat: allow steps in the finish position in an integration

app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGeneratorHelper.java, app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/TestConstants.java, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/integration.json
I'm simply pruning all actions from the integration that is about to be generated to address #4309.
=> fix: reduce integration definition size #4309

app/ui/src/app/common/editable/editable-tags.component.ts, app/ui/src/app/common/editable/editable-text.component.ts, app/ui/src/app/common/editable/editable-textarea.component.ts, app/ui/src/app/common/editable/editable.component.spec.ts, app/ui/src/app/common/editable/editable.component.ts, app/ui/src/app/common/openapi/editor/editor.component.html, app/ui/src/app/common/openapi/editor/editor.component.scss, app/ui/src/app/common/openapi/editor/editor.component.ts, app/ui/src/app/integration/api-provider/creation-page/integration-api-provider-creation-page.component.html, app/ui/src/app/integration/api-provider/creation-page/step-editor/step-editor.component.html, app/ui/src/app/integration/api-provider/creation-page/step-editor/step-editor.component.ts, app/ui/src/app/integration/api-provider/creation-page/step-name/step-name.component.html, app/ui/src/app/integration/api-provider/creation-page/step-upload/step-upload.component.html, app/ui/src/app/integration/api-provider/creation-page/step-validate/step-validate.component.html, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/edit-page.component.html, app/ui/src/app/integration/edit-page/edit-page.component.scss, app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss, app/ui/src/scss/components/_breadcrumb.scss, app/ui/src/scss/components/_module.scss
* new breadcrumbs
* updated toolbar, now built using PF3 toolbar
* updated api provider creation pages to use cards
* openapi editor reworked to be compatible with an in-card usage (might be broken elsewhere)
* reworked the main editor html/css structure to ease building full height scrollable panels
=> Feat(ui): integration editor UI tweaks

app/common/model/src/main/java/io/syndesis/common/model/connection/ConfigurationProperty.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java, app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html, app/ui/src/app/core/providers/form-factory-provider.service.ts, app/ui/src/app/platform/types/platform.models.ts
https://github.com/syndesisio/syndesis/issues/4429
=> Fixes #4429 Suppport multi-selection for form fields

install/addons/syndesis-db-servicemonitor.yml, install/addons/syndesis-meta-servicemonitor.yml, install/addons/syndesis-server-servicemonitor.yml, install/generator/04-syndesis-db-metrics.yml.mustache, install/generator/04-syndesis-meta.yml.mustache, install/generator/04-syndesis-server.yml.mustache, install/syndesis.yml
=> feat(monitoring): Create Prometheus ServiceMonitor resources for Syndesis infrastructure components

app/server/runtime/pom.xml, app/ui/package.json, app/ui/proxy.conf.js, app/ui/src/config.json.local, doc/sdh/development/local.adoc
Adds the option to develop without a running OpenShift.
=> feat: local development

app/common/util/pom.xml, app/common/util/src/main/java/io/syndesis/common/util/MavenProperties.java, app/common/util/src/main/java/io/syndesis/common/util/Resources.java, app/connector/aws-s3/pom.xml, app/connector/aws-s3/src/test/java/io/syndesis/connector/aws/s3/AWSS3RawOptionsTest.java, app/connector/support/test/src/main/java/io/syndesis/connector/support/test/ConnectorTestSupport.java, app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/IntegrationRuntimeAutoConfiguration.java, app/integration/runtime-springboot/src/test/java/io/syndesis/integration/runtime/sb/IntegrationTestSupport.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java, app/integration/runtime/src/main/resources/META-INF/services/io.syndesis.integration.runtime.IntegrationStepHandler, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteBuilderTest.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteTest.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationStepHandlersTest.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationTestSupport.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/SplitStepHandlerJsonTest.java, app/server/builder/image-generator/src/main/java/io/syndesis/server/builder/image/generator/Application.java, app/server/builder/image-generator/src/main/java/io/syndesis/server/builder/image/generator/SpringMavenProperties.java, app/server/runtime/src/main/java/io/syndesis/server/runtime/Application.java, app/server/runtime/src/main/java/io/syndesis/server/runtime/SpringMavenProperties.java
Segregated Spring dependencies as much as possible
Implemented and consolidated ServiceLocator to discover IntegrationStepHandlers
=> [refactoring] as part of #4232

app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html, app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.ts
Fixes https://github.com/syndesisio/syndesis/issues/4429#issuecomment-461497708
=> Fixes 4429 Support multi-selection follow up fix

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationSpecificationHandler.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationSpecificationHandlerTest.java
This makes sure that specification changes that do not change any flow definitions are saved. Previously only changes that would affect flows resulted in the OpenAPI specification resource being stored.
Fixes #4480
=> fix(server): store the updated OpenAPI specification even for non-flow changes

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
Fixes https://github.com/syndesisio/syndesis/issues/4486
=> Fixes #4486 Please check your sorting arguments

app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java
=> fix(server): NPE in ActivityTrackingController::stop

app/common/util/src/main/java/io/syndesis/common/util/thread/Threads.java, app/common/util/src/test/java/io/syndesis/common/util/thread/ThreadsTest.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/UnifiedXmlDataShapeGeneratorShapeValidityTest.java, app/server/runtime/src/main/java/io/syndesis/server/runtime/Migrations.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/MigrationsITCase.java
=> feat(server): run migrations on separate thread at startup

install/addons/syndesis-db-prometheus-rule.yml, install/addons/syndesis-jvm-prometheus-rule.yml, install/addons/syndesis-rest-api-prometheus-rule.yml
=> feat(monitoring): Create PrometheusRule resources for alerting on Syndesis infrastructure components

app/ui/src/app/integration/api-provider/creation-page/integration-api-provider-creation-page.component.ts, app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.html, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/edit-page.component.html, app/ui/src/app/integration/edit-page/edit-page.models.ts, app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html, app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.ts
=> fix: connect toolbar buttons better, hide them for api provider wizard

app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html
=> bugfix(ui): make the customization api editor visible

app/ui/src/app/core/providers/integration-support-provider.service.ts, app/ui/src/app/integration/api-provider/api-provider.effects.ts, app/ui/src/app/integration/api-provider/creation-page/integration-api-provider-creation-page.component.ts, app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-page.component.ts, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/integration/edit-page/action-select/action-select.component.ts, app/ui/src/app/integration/edit-page/current-flow.service.spec.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts, app/ui/src/app/integration/edit-page/edit-page.models.ts, app/ui/src/app/integration/edit-page/flow-functions.ts, app/ui/src/app/integration/edit-page/flow-page.service.ts, app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.ts, app/ui/src/app/integration/edit-page/integration-basics/integration-basics.component.ts, app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.ts, app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts, app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.ts, app/ui/src/app/integration/edit-page/step-select/step-select.component.ts, app/ui/src/app/platform/types/integration/integration-support.service.ts, app/ui/src/app/platform/types/integration/integration.api.ts, app/ui/src/app/platform/types/integration/integration.models.ts
fixes #4406
Using a connector that returns an array (using the code in #4547 running in the backend):
=>  feat: fetch descriptors for split/aggregate steps

app/connector/servicenow/pom.xml, app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/ServiceNowMetadataRetrieval.java, app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/customizers/ServiceNowTableGetCustomizer.java
Servicenow connector now using json-schema array collection type
=> Servicenow connector returning collection data shape

app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrieval.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrievalTest.java
OData connector now using json-schema array collection type where applicable
=> OData connector returns collection data shape

app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsMetadataRetrieval.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizer.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/meta/GoogleSheetsMetaDataHelper.java, app/connector/google-sheets/src/test/resources/meta/append_columns_metadata.json, app/connector/google-sheets/src/test/resources/meta/append_rows_metadata.json, app/connector/google-sheets/src/test/resources/meta/get_columns_metadata.json, app/connector/google-sheets/src/test/resources/meta/get_columns_split_metadata.json, app/connector/google-sheets/src/test/resources/meta/get_rows_metadata.json, app/connector/google-sheets/src/test/resources/meta/get_rows_split_metadata.json, app/connector/google-sheets/src/test/resources/meta/update_columns_metadata.json, app/connector/google-sheets/src/test/resources/meta/update_rows_metadata.json
Google sheets connector now using json-schema array collection type as output data shape
=> Google Sheets connector return collection data shape

app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/flow-functions.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
=> feat(ui): add a suggested step hint over unclosed split steps

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts, app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
=> fix: ensure the data mapper can't see beyond a split step

app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.html
Noticed it was broken in the editor toolbar
=> fix: fix link to view/edit api spec

doc/managing_environments/topics/alerting_sop.adoc, install/addons/syndesis-db-prometheus-rule.yml, install/addons/syndesis-rest-api-prometheus-rule.yml
=> feat(monitoring): Reference SOP documentation from alerts

app/ui/src/app/core/providers/integration-support-provider.service.ts, app/ui/src/app/integration/list/list.component.spec.ts, app/ui/src/app/integration/list/list.module.ts, app/ui/src/app/integration/list/tag-cicd-modal.component.html, app/ui/src/app/integration/list/tag-cicd-modal.component.scss, app/ui/src/app/integration/list/tag-cicd-modal.component.ts
fixes #4494 
Well, almost.  The rename function doesn't work, I'm not sure if I just don't have the request data set up or what.  For example I wound up making myself an environment literally named `\{ "environment": "foo", "newEnvironment": "bar" \}`, oops.  But from what I can see the API expects just a string, but I send it that and it's rejected.
The "remove" functionality works I think as described.  The "add" button next to the dialog kinda didn't make sense to me but I think the way it behaves is as described.
Anyhoo, @riccardo-forina @dhirajsb if you get a chance to play with it that'd be awesome, it's like 90% there I think...
=> feat: finish up ci/cd dialog functions (almost)

install/operator/Dockerfile, install/operator/Gopkg.lock, install/operator/cmd/syndesis-operator/main.go, install/operator/pkg/controller/syndesis/syndesis_controller.go, install/operator/pkg/syndesis/action/action.go, install/operator/pkg/syndesis/action/checkupdates.go, install/operator/pkg/syndesis/action/initialize.go, install/operator/pkg/syndesis/action/install.go, install/operator/pkg/syndesis/action/startup.go, install/operator/pkg/syndesis/action/upgrade.go, install/operator/pkg/syndesis/action/upgradebackoff.go, install/operator/pkg/syndesis/action/upgradelegacy.go, install/operator/pkg/syndesis/addons/install.go, install/operator/pkg/syndesis/configuration/configuration.go, install/operator/pkg/syndesis/operation/utils.go, install/operator/pkg/util/resources.go, tools/bin/commands/util/operator_funcs
Fixes #4381.
We may want to either:
* Add an option to deactivate add-on by default
* Or do not fail-fast on add-on resource creation error
=> feat(install): Support for addon resources in syndesis-operator

app/integration/api/src/main/java/io/syndesis/integration/api/IntegrationResourceManager.java
This is more like a personal excercise in learning functional style. To all the functional gurus out there, is this the right way to do it ? I.e. if the method reference ok, even when connector can be null (but then I guess that flatMap's consumer wouldn't be called anyway). Sure, I could have written a test, but I haven't :) (as I couldn't find test classes in this module anyway)
=> refactor: Moved conditional to a functional

doc/integrating-applications/topics/p_add-template-step.adoc, doc/shared/attributes.adoc
Ready to merge. 
Paul reviewed an approved. Typo update by Zoran.
Approved by QE - Martin.
=> user doc: Update template step doc for Velocity and Freemarker support.

app/pom.xml
Upgrades immutables to a version that resolves the Eclipse issue.
Ref https://github.com/immutables/immutables/issues/891
Fixes #4624
=> chore: upgrade immutables

app/integration/bom/pom.xml, app/pom.xml, app/ui/package.json, app/ui/yarn.lock
No big addition for Syndesis though, better to sync up with latest at the beginning of bug fix sprint.
=> chore: Update to AtlasMap 1.39.3

app/ui/src/app/app.component.html, app/ui/src/scss/utils/_overrides.scss
fixes https://github.com/syndesisio/syndesis/issues/4596
=> fix(masthead): add separator in masthead dropdown, align nav text with hamburger

tools/bin/commands/minishift
Other fixes will be send in a later PR.
=> fix(minishift): Fix issue with context

app/common/model/src/main/java/io/syndesis/common/model/connection/ConfigurationProperty.java, app/connector/fhir/pom.xml, app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirMetadataRetrieval.java, app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirResourceQuery.java, app/connector/fhir/src/main/java/io/syndesis/connector/fhir/customizer/FhirCreateUpdateBaseCustomizer.java, app/connector/fhir/src/main/java/io/syndesis/connector/fhir/customizer/FhirCustomizerHelper.java, app/connector/fhir/src/main/java/io/syndesis/connector/fhir/customizer/FhirPatchCustomizer.java, app/connector/fhir/src/main/java/io/syndesis/connector/fhir/customizer/FhirReadDeleteBaseCustomizer.java, app/connector/fhir/src/main/java/io/syndesis/connector/fhir/customizer/FhirSearchCustomizer.java, app/connector/fhir/src/main/java/io/syndesis/connector/fhir/customizer/FhirTransactionCustomizer.java, app/connector/fhir/src/main/java/io/syndesis/connector/fhir/processor/FhirResourcesProcessor.java, app/connector/fhir/src/main/resources/META-INF/syndesis/connector/fhir.json, app/connector/fhir/src/main/resources/META-INF/syndesis/schemas/dstu3/transaction.xsd, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirMetadataRetrievalTest.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirPatchTest.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirSearchTest.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirTestBase.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirTransactionTest.java, app/pom.xml
Fixes https://github.com/syndesisio/syndesis/issues/4552
=> Fixes #4552 Support FHIR patch, search and transaction actions

app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
=> fix: untangle the subsequent step selection slightly

app/ui/src/app/integration/list/tag-cicd-modal.component.html, app/ui/src/app/integration/list/tag-cicd-modal.component.ts
fixes #4617
Also rework the edit buttons to match patternfly's inline-edit pattern better
=> fix: Prevent submitting the same name

app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.html
=> chore: add label to operations dropdown

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
=> fix: hide the start/finish delete icons for API provider flows
