syndesisio/syndesis

patch_pr.sh
`git co` was causing an error on my end:
git: 'co' is not a git command. See 'git --help'.
=> refactor: use `git checkout` instead of `git co`

build.sh
`MAVEN_OPTS` variable is used by Maven to pass arguments to JVM, we
should use another variable for parameters passed to maven.
Based on #18
=>  refactor: use MAVEN_PARAMS instead of MAVEN_OPTS

.gitignore
The original purpose was to ensure that no Mac OS system file will make it to the repo, but decided to extend ignore to system files generated by IDEs other than IntelliJ and stuff...
=> chore(tools): IDE and System files added to git ignore manifest

ui/package.json
So for me this change just worked to retrieve latest 1.32.0 SNAPSHOT while it was always retrieving `20171018190510` before. @syndesisio/ui-api WDYT?
=> chore: use latest 1.32.0 SNAPSHOT of datamapper

ui/.gitignore, ui/scripts/generate-ts.js, ui/src/app/customizations/customizations.component.html, ui/src/app/customizations/customizations.module.ts, ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.html, ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.ts, ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html, ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.ts, ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html, ui/src/app/customizations/tech-extensions/tech-extensions-list.component.ts, ui/src/app/integrations/edit-page/integration-basics/integration-basics.component.ts, ui/src/app/integrations/list-page/list-page.component.html, ui/src/app/model.ts, ui/src/app/store/extension/extension.service.ts, ui/src/app/store/extension/extension.store.ts, ui/src/app/store/store.module.ts, ui/yarn.lock
Also adds some updates to the generated model file.
Changed the generator code so it no longer will overwrite model.ts since changes have been manually added in past commits.  Added `Extension` and related types to the model.
Relates to #264 #262 and #263
=> feat: Add technical extensions page to customizations, stub in import and detail page

ui/src/app/common/ui-patternfly/syndesis-form-control.component.html, ui/src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.model.ts
supply hint properties to the basic filter model and bind those hints as tooltips
A limitation I realized while working through this story was that ng-dynamic-forms does not have out of the box support for configuring tooltips and their placement.
Right now the tooltips are placed at "top" by default, we can add support for making this configurable if/when it becomes necessary.
=> feat(filter-step-tooltips): add tooltip hints in the basic filter model

connectors/pom.xml, rest/pom.xml, s2i/pom.xml, ui/pom.xml, verifier/pom.xml
We should have relativePath for syndesis-parent parent POM as it allows
Maven to find it when running a _resume-from_ (`-rf`) or building from
a submodule.
=> chore: add relativePath to pom.xmls

project/tools/minishift-build/atlasmap.sh, project/tools/minishift-build/build-all.sh, project/tools/minishift-build/integration-runtime.sh, project/tools/minishift-build/rest.sh, project/tools/minishift-build/ui.sh, project/tools/minishift-build/vars.sh, project/tools/minishift-build/verifier.sh
Scripts worked when invoked individually but not when invoked via
`build-all.sh` script. This I've tested with `./build-all.sh` individual
scripts and symlinked `build-all.sh` and individual scripts, so it
should be much better.
=> fix: script path resolution

Jenkinsfile
Seems that our builds are failing as the syndesis-parent POM cannot be
resolved. This adds a stage to install just the syndesis-parent POM in
the local Maven repository.
=> fix: install syndesis-parent POM

ui/src/app/customizations/customizations.module.ts, ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.html, ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.ts, ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html, ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.ts, ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html, ui/src/app/customizations/tech-extensions/tech-extensions-list.component.scss, ui/src/app/customizations/tech-extensions/tech-extensions-list.component.ts, ui/src/app/integrations/list/list.component.scss, ui/src/app/store/extension/extension.service.ts, ui/src/app/store/extension/extension.store.ts, ui/src/scss/_overrides.scss
Makes it possible to upload a tech extension via the UI and import it, fixes the list so it works properly, also adds some of the detail page.  Need to implement deleting and updating tech extensions, as well as fetch them via the step store (or somehow) in the integration editor.
Relates to #262 #263 
Fixes #264 
=> feat: implement tech extension upload and most of the detail page

Jenkinsfile, build.sh, create-lock.sh, pom.xml, rest/pom.xml, tests/pom.xml, tests/src/test/resources/arquillian.xml, tests/src/test/resources/setup.sh
This pull request completely changes our Jenkins pipeline to be `kubernetes-less`.
The pipeline now use plain old jenkins tools, to require and setup the build environment and the actual build is performed in a single step by invoking the build.sh script.
The build.sh script has been updated to also execute the system-tests. For the needs of system testing, we now use a `pool of projects`. For each project in the pool, we have a secret that contains credentials to access the project and also locking information. Whenever a test project is needed a secret is marked in the pool, and a new connection to the project is made using the token read.
Pool handling and system tests rely on `oc` and they are skipped if `oc` is not present in the PATH.
=> refactor: build and pipelines

rest/dao/src/main/resources/io/syndesis/dao/deployment.json, rest/dao/src/test/java/io/syndesis/dao/DeploymentDescriptorIT.java, rest/pom.xml, s2i/src/main/docker/project/pom.xml
Fixes the DeploymentDescriptorIT test to look for properties also within
connector properties. Updates `deployment.json` to match connector JSON
schema in 1.2-SNAPSHOT.
**Updates connectors version to 1.2-SNAPSHOT. With this it will be
difficult to run on minishift as -SNAPSHOT version cannot be resolved
from any Maven repository (we don't publish -SNAPSHOTs), and if merged
without the upgrade to 1.2-SNAPSHOT the test will fail as the connector
JSON schema differs in 0.5.8 vs 1.2-SNAPSHOT.**
Fixes #476
=> fix: Connector descriptors with update to 1.2-SNAPSHOT

pom.xml, ui/package.json, ui/pom.xml
Using 6.x means we have to do `npm rebuild` whenever we rebuild the whole repo.  Since we're using 8.x for dev we should align to this.  And no need to install angular-cli globally, can just use the existing `build:ci` task for this.
=> Update build command and bump node version to align with development

pom.xml
As none of the Java modules require it to be built first and it takes forever to compile.
=> Build the UI last

rest/model/src/main/java/io/syndesis/model/action/Action.java, rest/model/src/main/java/io/syndesis/model/action/ConnectorAction.java, rest/model/src/main/java/io/syndesis/model/action/ExtensionAction.java
We're missing `actionType` when Jackson deserializes Action's from JSON
the correct class instances are created but tye `actionType` remains to
be `null`. This adds default value for `actionType` property.
Fixes #482
=> refactor: add default discriminator values to Action subclasses

rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/SwaggerConnectorGenerator.java, rest/connector-generator/src/main/java/io/syndesis/connector/generator/util/ActionComparator.java, rest/connector-generator/src/test/java/io/syndesis/connector/generator/util/ActionComparatorTest.java
**Based on #495 please review that first**
Adds sorting to actions based on tags and then on names of actions. NULL
or empty tags/actions are placed last.
Fixes #105
=>  feat: Order actions in Swagger connector generator

runtime/runtime/src/main/java/io/syndesis/integration/runtime/stephandlers/ChoiceHandler.java
Seems that the `javac` reports a warning if generics are not specified
(but could be inferred, which is odd).
```
[ERROR] [...]syndesis/runtime/runtime/src/main/java/io/syndesis/integration/runtime/stephandlers/ChoiceHandler.java:[47,58] incompatible types: inferred type does not conform to upper bound(s)
[ERROR]     inferred: java.util.List<? extends java.lang.Object>
[ERROR]     upper bound(s): java.util.List<io.syndesis.integration.model.steps.Filter>,java.lang.Object
[ERROR] [...]/syndesis/runtime/runtime/src/main/java/io/syndesis/integration/runtime/stephandlers/ChoiceHandler.java:[57,67] incompatible types: inferred type does not conform to upper bound(s)
```
=> fix: be explicit about Supplier type not to trigger a warning

project/proposals/119-custom-connectors.md, rest/connector-generator/pom.xml, rest/connector-generator/src/main/java/io/syndesis/connector/generator/ActionsSummary.java, rest/connector-generator/src/main/java/io/syndesis/connector/generator/ConnectorGenerator.java, rest/connector-generator/src/main/java/io/syndesis/connector/generator/ConnectorSummary.java, rest/connector-generator/src/main/java/io/syndesis/connector/generator/package-info.java, rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/SwaggerConnectorGenerator.java, rest/connector-generator/src/test/java/io/syndesis/connector/generator/swagger/SwaggerConnectorGeneratorTest.java, rest/model/src/main/java/io/syndesis/model/Violation.java, rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorSettingsHandler.java, rest/rest/src/main/java/io/syndesis/rest/v1/handler/exception/ConstraintViolationExceptionMapper.java, rest/rest/src/main/java/io/syndesis/rest/v1/handler/extension/ExtensionHandler.java, rest/rest/src/main/java/io/syndesis/rest/v1/handler/integration/IntegrationSupportHandler.java, rest/rest/src/main/java/io/syndesis/rest/v1/operations/Validating.java, rest/rest/src/test/java/io/syndesis/rest/v1/handler/connection/ConnectorSettingsHandlerTest.java, rest/rest/src/test/java/io/syndesis/rest/v1/handler/connection/ConnectorTemplateHandlerTest.java, rest/runtime/src/test/java/io/syndesis/runtime/ConnectionsITCase.java, rest/runtime/src/test/java/io/syndesis/runtime/ExtensionsITCase.java, rest/runtime/src/test/java/io/syndesis/runtime/IntegrationsITCase.java, rest/runtime/src/test/java/io/syndesis/runtime/connector/CustomConnectorITCase.java
**Based on #495 and #500 please review that first**
This removes `/api/v1/custom/connectors/{id}/validation` endpoint and changes the response from `/api/v1/custom/connectors/{id}/info` to be a bit simpler and in the same time to contain errors and warnings.
//cc @deeleman
=> Simplify /info endpoint for custom connectors

app/connectors/connectors/sql/sql-start-connector/src/test/java/io/syndesis/connector/sql/SqlStartConnectorComponentTest.java
By not specifiying ORDER BY, the order of the rows in the result from
the SQL statement needs not be deterministic as the assert requires it
to be.
=> fix: flaky test in SQL start connector

app/build.sh
By default the template with the openshift imagestreams (syndesis-restricted.yml) is deployed. With '-i docker' this can be switched to syndesis-dev-restricted.yml
=> feat: Allow to switch templates when installing with -i docker / openshift

app/build.sh, app/deploy/generator/04-syndesis-rest.yml.mustache, app/deploy/generator/04-syndesis-verifier.yml.mustache, app/deploy/generator/run.sh, app/deploy/generator/syndesis-template.go, app/deploy/syndesis-dev-restricted.yml, app/deploy/syndesis-dev.yml
This sets the environment variable `JAVA_DEBUG` to `true` for
`syndesis-rest` and `syndesis-verifier` pods in `syndesis-dev-*.yml`
templates.
With that environment variable set the Java process is launched with
remote debugging enabled and debugger interface on port `5005`.
Next one can port forward that port via
oc port-forward syndesis-rest-... 5005:5005
and use the debugger to connect to `localhost:5005`.
=> feature: enable debugging in -dev templates

app/rest/runtime/pom.xml
This configures `cleanup` property of fabric8-maven-plugin to `remove`.
I was having issues deploying fresh versions to development environment
on minishift. Adding `cleanup` property seemed to have helped.
=> feat(build): add cleanup to fabric8-maven-plugin

app/ui/src/app/integrations/detail-page/detail.component.html
=> fix: display connection name instead of id

app/connectors/connectors/rest/rest-swagger-connector/src/main/java/io/syndesis/connector/swagger/AuthenticationType.java, app/connectors/connectors/rest/rest-swagger-connector/src/main/java/io/syndesis/connector/swagger/SwaggerConnectorComponent.java, app/connectors/connectors/rest/rest-swagger-connector/src/main/java/io/syndesis/connector/swagger/springboot/SwaggerConnectorConnectorConfigurationCommon.java, app/connectors/connectors/rest/rest-swagger-connector/src/main/resources/camel-connector-schema.json, app/connectors/connectors/rest/rest-swagger-connector/src/main/resources/camel-connector.json, app/connectors/connectors/rest/rest-swagger-connector/src/test/java/io/syndesis/connector/swagger/SwaggerConnectorComponentTest.java
Adds support for setting the `Authorization` header for OAuth2
authentication. Also adds support for `basePath` component property.
Fixes #606
=> chore(rest-swagger): add support for OAuth2

app/rest/connector-generator/src/test/resources/swagger/concur.connector.json, app/rest/connector-generator/src/test/resources/swagger/petstore.connector.json, app/rest/connector-generator/src/test/resources/swagger/reverb.connector.json, app/rest/dao/src/main/resources/io/syndesis/dao/deployment.json
Missed this when refactoring, the GAV for REST Swagger connector points
to a wrong artifact.
=> fix: use proper GAV for REST Swagger connector

.circleci/config.yml
This adds test summary to CircleCI builds (see [build 1224](https://circleci.com/gh/syndesisio/syndesis/1224)):
=> chore(ci): store test metadata in circleci

app/pom.xml, app/rest/syndesis-builder-image-generator/src/main/java/io/syndesis/image/Application.java
We need to add artifacts for connectors that can be generated from
connector templates. This generates an ad hoc action and adds a step
with it to the integration being stubbed for the project generator in
order to accomplish that.
=> chore(image-generator): add support for connector templates

.circleci/config.yml, app/.mvn/jvm.config, app/pom.xml, app/rest/connector-generator/pom.xml, app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/SupportedAuthenticationTypes.java, app/rest/pom.xml, app/rest/project-generator/src/main/java/io/syndesis/project/converter/ProjectGeneratorConfiguration.java, app/rest/rest/pom.xml, app/s2i/pom.xml
Seems that we lost checks from being run, this reinstates the checks.
- Makes the license plugin non-inheritable so its not run on modules, only on parent build.
- We should rely on `basepom.check.skip-all` set from parent and the profile configuration there, not in individual modules
-  fixes reported dependency checks/codestyle checks
=> The return of the checks

tools/bin/commands/build, tools/bin/commands/dev, tools/bin/commands/doc, tools/bin/commands/minishift, tools/bin/commands/system-test, tools/bin/syndesis
Each command is now moved into an own scripts from `commands/`.
Also support for `syndesis <command>` has been added, but old syntax
still works.
Re-organized help message to be be more context sensitive and hence
shorter normally:
syndesis -h ---> global usage
syndesis build -h --> only build relevant options
=> refactor(synesis): Split up monolythic script into commands

app/rest/dao/src/main/resources/io/syndesis/dao/demo-data.json, app/rest/rest/pom.xml, app/rest/rest/src/main/java/io/syndesis/rest/util/FilterOptionsParser.java, app/rest/rest/src/main/java/io/syndesis/rest/util/ReflectionUtils.java, app/rest/rest/src/main/java/io/syndesis/rest/util/ReflectiveFilterer.java, app/rest/rest/src/main/java/io/syndesis/rest/util/ReflectiveSorter.java, app/rest/rest/src/main/java/io/syndesis/rest/util/SortOptions.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/operations/FilterOptionsFromQueryParams.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/operations/Lister.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/operations/SortOptionsFromQueryParams.java, app/rest/rest/src/test/java/io/syndesis/rest/v1/handler/connection/ConnectorHandlerTest.java, app/rest/runtime/src/test/java/io/syndesis/runtime/ConnectorsITCase.java, app/rest/runtime/src/test/java/io/syndesis/runtime/connector/CustomConnectorITCase.java, app/runtime/model/src/main/java/io/syndesis/integration/support/Strings.java, project/proposals/119-custom-connectors.md
This enables generic filtering via the REST API, especially important for custom connector listing.
Fixes #660.
=> feat(rest): Enable filtering of lists through REST API

app/tests/src/test/resources/arquillian.xml
With this configuration change, all logs should be kept under `surefire-reports`.
=> feat: keep the system test pod logs.

app/rest/rest/src/main/java/io/syndesis/rest/util/FilterOptionsParser.java, app/rest/rest/src/test/java/io/syndesis/rest/util/FilterOptionsParserTest.java
Changes the regular expression that determines if a given `query`
parameter for list filtering is a valid filter expression to include
printable values.
Fixes #724
=> fix(rest): allow printable characters in filter value

app/rest/dao/src/main/java/io/syndesis/dao/manager/DataManager.java, app/rest/model/src/main/java/io/syndesis/model/connection/Connector.java, app/rest/model/src/main/java/io/syndesis/model/integration/Integration.java, app/rest/rest/src/main/java/io/syndesis/rest/util/ReflectiveFilterer.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorHandler.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/CustomConnectorHandler.java, app/rest/rest/src/test/java/io/syndesis/rest/v1/handler/connection/ConnectorHandlerTest.java, app/rest/runtime/src/test/java/io/syndesis/runtime/connector/CustomConnectorITCase.java
This adds a uses counter to Connector that counts the number of integrations that make use of a particular connector.
This in turn means that endpoints for getting and listing connectors need to load all integrations
Fixes #666
=> chore(rest): adds `uses` counter to Connector

app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/extension/ExtensionHandler.java
Fixes #735 .
It does not happen for draft integrations. Statuses were filtered incorrectly.
=> Report tech extension usage if integration is deactivated

app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorHandler.java, app/rest/rest/src/test/java/io/syndesis/rest/v1/handler/connection/ConnectorHandlerTest.java
With #666 the `uses` property would not be set on a Connector if the
Connector was not used by any Integration. This changes that to set it
to `0` if it's unused to make it simpler for the UI to use the property.
=> refactor(rest): set uses to 0 if not used

app/rest/runtime/pom.xml
This adds the REST Swagger connector as a dependency of the syndesis-build-helper Maven plugin when invoked in runtime module to generate the `/META-INF/camel/camel-meta.json` that includes it.
=> chore(rest): add REST Swagger connector to syndesis-build-helper

app/rest/model/src/main/java/io/syndesis/model/connection/Connector.java, app/rest/runtime/src/test/java/io/syndesis/runtime/ConnectorsITCase.java, app/rest/runtime/src/test/java/io/syndesis/runtime/connector/CustomConnectorITCase.java
The Connector::summary method needs to be called getSummary in order to be serialized by Jackson to JSON.
=> fix(rest): use getter syntax for connector symmary

app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/CustomConnectorHandler.java
This was missed in previous commits.
@zregvart Could you take a look please? Thanks!
=> fix: Remove redundant endpoint for listing custom connectors

app/connectors/connectors/salesforce/salesforce-delete-sobject-connector/pom.xml, app/connectors/connectors/salesforce/salesforce-delete-sobject-with-id-connector/pom.xml, app/connectors/connectors/salesforce/salesforce-get-sobject-connector/pom.xml, app/connectors/connectors/salesforce/salesforce-get-sobject-with-id-connector/pom.xml
In the Salesforce connector refactor (#817) renamed dependency `salesforce-model` (replaced by `salesforce-common`) was left behind in some of the connector POMs. This removes those.
=> fix(connectors): removes refactored salesforce-model dependency

app/verifier/pom.xml
In the Salesforce connector refactor (#817) `salesforce-upsert-contact-connector` connector artifact was removed, this replaces that dependency with Camel Salesforce component.
=> fix(verifier): replace dependency on `salesforce-upsert-contact-connector`

app/ui/src/app/app.module.ts, app/ui/src/app/core/core.module.ts, app/ui/src/app/core/index.ts, app/ui/src/app/core/providers/api-http-provider.service.ts, app/ui/src/app/core/providers/index.ts, app/ui/src/app/platform/types/api/api-http.service.ts, app/ui/src/app/platform/types/api/api.models.ts, app/ui/src/app/platform/types/api/index.ts, app/ui/src/app/platform/types/index.ts, app/ui/src/config.json.minishift, app/ui/src/config.json.staging
Fixes #834 
Please refer to the linked issue for a comprehensive explanation on the rationale for this new class. This new internal service is designed for sending Http calls straight to our REST API through a more intuitive and flexible interface, allowing for replacing Restangular in the Api Connectors implementation or even on any other feature module in the future.
Please pay special attention to the new config nodes created at the config files. Ideally, we should go porting all URLs hardcoded in services and components to a centralized location and those files seem the right place until we come up with a more approppiate solution.
This PR welcomes `CoreModule` into our project, which is the module of choice for service providers, according to the official Angular recommendations for …
=> feat: New API HTTP Client for UI with composable REST interface

app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java
Seems that turning of incremental build helps with having a working
integration pod build the second time it's invoked. Lets start with this
and see if we can optimize it better in the future.
Fixes #761
=> fix(openshift): turn off incremental build

app/ui/src/app/customizations/api-connector/api-connector-list.component.html
=> fix: Disable API connector delete button if API connector is in use by any integrations

app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java
Seems that we should be looking at `availableReplicas` instead of
`readyReplicas` to determine if the integration pod is running.
Looking at kubernetes reference[1] seems more appropriate for our use
case.
Tested on minishift with integration pod that was happy to run and a
integration that was not so happy to run, seems to reflect what we want
to achieve.
Fixes #625
[1] https://v1-8.docs.kubernetes.io/docs/api-reference/v1.8/#deploymentstatus-v1beta2-apps
=> fix(openshift): look at `availableReplicas` instead of `readyReplicas`

app/ui/src/app/dashboard/integrations.component.ts
I traced the ever-repainting kebab menu to chart component triggering
change event, seems that ng-chart is adding functions to array and that
in change detection triggers repaint of other directives.
I know I explain this wrong, I'm a Angular newb, though it seems to
work with this change. Perhaps there is a better way of doing this, not
sure.
Fixes #733
=> fix(ui): stop ng-chart from initiating change storm

app/ui/src/app/common/forms.service.ts, app/ui/src/app/connections/common/configuration/configuration.service.ts
fixes #886 
Also adds a client-side tweak for now that at least organizes the broker connection configuration page a little better.
=> fix: Add a means to control the order of form elements via an external 'controls' array

app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.ts
Introduces a fix for resetting the form state upon switching between options, so the button remains disabled when the user selects a new choice but no information has been introduced.
=> Fix: better swagger upload form validation

app/ui/src/app/common/validation/validation-error.component.scss
Sets the fixed height for error icon block so it doesn't expand with the
content to form an ellipse.
Before:
After:
=> fix(ui): Make error icon not show up as ellipse

app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/BaseSwaggerConnectorGenerator.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorHandler.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/CustomConnectorHandler.java, app/rest/runtime/src/test/java/io/syndesis/runtime/ConnectorsITCase.java, app/rest/runtime/src/test/java/io/syndesis/runtime/connector/CustomConnectorITCase.java, app/rest/runtime/src/test/java/io/syndesis/runtime/connector/CustomSwaggerConnectorITCase.java
This adds support for uploading specification in a mime part of a
multipart upload for the `POST /connectors/custom` endpoint. Also
renames `swaggerSpecification` part to just `specification` to keep it
in line with the `ConnectorSettings` naming.
=> fix(rest): adds support for multipart upload of specification

app/rest/model/src/main/java/io/syndesis/model/connection/Connector.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorHandler.java, app/rest/runtime/src/test/java/io/syndesis/runtime/connector/CustomConnectorITCase.java
This, somewhat crudely, replaces the `summary` property of a `Connector`
of type `ConnectorSummary` with `actionsSummary` property of type
`ActionSummary`.
Fixes #898
=> fix(rest): provide actionsSummary instead of summary

app/rest/project-generator/src/main/java/io/syndesis/project/converter/visitor/FilterStepVisitor.java
When generating `syndesis.yaml` it's important that the index of the
step is in line with the generated `application.properties` in
`/controllers/src/main/java/io/syndesis/controllers/integration/IntegrationSupport.java`
In the case when the filter step is followed by two or more steps the
nested steps are created with the same context, and thus share the same
index.
This tracks the context that needs to be used to maintain the index.
Fixes #888
=> fix(project-generator): Filter step skips an index

app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/SwaggerHelper.java, app/rest/connector-generator/src/test/java/io/syndesis/connector/generator/swagger/BaseSwaggerGeneratorExampleTest.java, app/rest/connector-generator/src/test/java/io/syndesis/connector/generator/swagger/SwaggerUnifiedShapeGeneratorExampleTests.java, app/rest/connector-generator/src/test/resources/swagger/todo.swagger.yaml, app/rest/connector-generator/src/test/resources/swagger/todo.unified_connector.json
The fix for #929 only fixed validation of Swagger specifications in YAML
format, this fixes both validation and generation.
Fixes #996
=> fix(swagger-generator): proper YAML support

app/rest/project-generator/src/main/java/io/syndesis/project/converter/visitor/ConnectorStepVisitor.java
Swagger custom API connectors set endpoint property `operationId` in the
action descriptor's configuredProperties, these need to be included in
the properties of the endpoint created by the project generator.
Fixes #1000
=> fix(project-generator): include configured properties from action descriptor in endpoint properties

app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.ts
The current value of `host` and `basePath` properties is stored in
`configuredProperties` of the Connector, if the value there is not
present fall back to the `defaultValue` from `properties`
Fixes #999
=> fix(ui): use values from configuredProperties

app/ui/src/app/connections/common/configuration/configuration.service.ts
We should use `configuredProperties` from Connector to setup the form to
create the new Connection. These still can be overridden with values
from `Connection.configuredProperties` if those are specified.
Fixes #999
=> fix(ui): use values from configuredProperties in new connection wizard

app/ui/package.json, app/ui/yarn.lock
@kahboom @gashcrumb @seanforyou23 I'd need some help from you guys. Could you pull these changes and help me test that the AtlasMapper instance works as expected? I do not seem to be able to create connections in my dev env.
Creating a data mapper step when creating a new connection or editing an existing connection will bring up the AtlasMapper widget. Checking that the AtlasMapper component can be mounted is enough.
=> chore(NG5 upgrade): AtlasMapper dependency upgraded - #380

app/connectors/connectors/salesforce/salesforce-common/src/main/java/io/syndesis/connector/salesforce/AdaptObjectForUpdateProcessor.java, app/connectors/connectors/salesforce/salesforce-common/src/main/java/io/syndesis/connector/salesforce/UpdatingSalesforceConnector.java
Since connector options don't include endpoint parameters we need to
fetch the external id property name from the endpoint URI in the
exchange. Otherwise we would end up using the default (Id) field as
external property identifier.
=> fix(salesforce): access external id for upsert from endpoint URI

app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorHandler.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorIconHandler.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/CustomConnectorHandler.java, app/rest/runtime/src/test/java/io/syndesis/runtime/connector/CustomConnectorITCase.java
When reading the submitted icon stream we should be used the buffered
stream that was reset to the initial position, otherwise we just store
the icon data after first 1024 bytes (or the length of the buffer in
BufferInputStream).
=> fix(rest): use buffered streams for icon upload

app/s2i/src/main/docker/Dockerfile
Upgrading the base image for Syndesis s2i images enabled the Promtheus JMX exporter javaagent by
default.
=> feat: Enable Prometheus metrics exporter in integration containers

app/ui/src/app/connections/detail-page/info.component.ts, app/ui/src/app/connections/list/list.component.html, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-auth/api-connector-auth.component.html, app/ui/src/app/customizations/api-connector/api-connector-detail/api-connector-detail.component.html, app/ui/src/app/dashboard/connections.component.html, app/ui/src/app/integrations/detail-page/detail.component.html, app/ui/src/app/integrations/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integrations/list/list.component.html, app/ui/src/app/settings/oauth-apps/oauth-apps.component.html, app/ui/src/scss/_common.scss
Sets labes for OAuth as in the documentation, defines three new CSS clases (syn-icon-[large|medium|small]) and uses those instead of width/height img attributes, and adds API connector icon to OAuth settings list.
=> Labels, consistant icon sizing and OAuth settings icon for API connectors

app/s2i/src/main/docker/Dockerfile
Since the move to latest java-s2i base image, Jolokia was no longer serving over https by default.
This re-enables it so the OpenShift JVM console works again.
=> fix(s2i): Ensure Jolokia is serving over https

doc/sdh/index.adoc
Little type preventing a bunch of information showing up in the developer handbook.
=> Fix reference to dev workflow pages

app/core/model/src/main/java/io/syndesis/model/extension/Extension.java, app/rest/jsondb/src/main/java/io/syndesis/jsondb/impl/SqlJsonDB.java
fixes #1075
Currently Tech Extension behavior is broken.
The reason for that is that commit https://github.com/syndesisio/syndesis/commit/8fa6e4f6c23daef46d8590a1f3d04c63269d40e2 introduces a new optimized SQL query based on indexes.
The problem with that commit is that it indexes only properties that are annotated as `@UniqueProperty`.
When a query that should use non indexed properties is used, the code log the problem as a WARNING but it also throws a blocking exception, breaking previous behavior.
That commit also introduced a UNIQUE constraint on a field in Extension model that is not correct, since that field is only part of the primary key, and it breaks update functionality.
Current PR introduces a fallback logic to the old behevior, in case of not indexed properties, without …
=> TechExt added fallback behavior for not optimized queries

app/ui/src/app/common/icon-path.pipe.ts, app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.html, app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.scss, app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.ts, app/ui/src/app/customizations/api-connector/api-connector.actions.ts, app/ui/src/app/customizations/api-connector/api-connector.effects.ts
Fixes #1080 
In edit mode the thumbnail is not updated, since the image will be uploaded as soon as it is selected by the end user so no preview features are required.
When creating a new connector, the preview is enabled though, since the image will not be uploaded until the user submits the form. 
The icon preview area will crop and center the icon whenever its size exceeds the allocated size for that.
Since there is still no support for fetching icons after validating the swagger file, the cross icon has been replaced by an upload icon.
The following links allow for seeing an actual recoding of the implementation:
- https://app.hyfy.io/v/abuHAYOMw7n/
- https://app.hyfy.io/v/abuHAYOMw7n/
=> feature(API connectors): File browser now allows for thumb preview when in create mode.

app/rest/runtime/pom.xml
We seem to be referencing AWS connector GAVs before refactor in #1163.
=> fix(rest): AWS connector dependency

app/ui/src/app/store/integration/integration.store.ts
Not bound to any particular issue, but just a quick fix for some methods that broke statical typing in the Integration "store".
Details: The statement `JSON.parse(JSON.stringify(i))` turned the`Integration` instance object input into a non-typed literal object (typed as `any`). That's why the compiler and the CI never complained when `integration.desiredStatus` was populated with a non valid value ('Activated' instead of the allowed primitive string `Active`).
TypeScript is a huge safety net when it comes to ensure that function payloads are consistent and testable... unless static typing is removed from the picture. Let's commit to ensure consistent typing at all times ;)
=> fix: static typing restored for Integration instance object

app/ui/src/app/api/providers/api-http-provider.service.ts, app/ui/src/app/customizations/api-connector/api-connector.service.ts, app/ui/src/app/platform/types/api/api-http.service.ts, app/ui/src/app/platform/types/api/api.models.ts
This is a WIP to double check if, despite TypeScript requirements for type inference, we can define our own custom `HttpHeaders`, URL params and response types.
In a nutshell, the request methods from `ApiHttpService` now support a new `options` parameter in its signature that represents an object whose properties match the options parameters of the `HttpClient` class  in Angular. Basically we can now define an options object like this (see Angular's official API docs for more insights on `HttpHeaders` and `HttpParams` - all object properties are optional):
```
{
headers?: HttpHeaders;
params?: HttpParams;
responseType?: 'arraybuffer' | 'blob' | 'json' | 'text';
withCredentials?: boolean;
}
```
and pass it on to `ApiHttpService` calls like this:
```typescript
apiHttpService …
```
=> Added support for custom headers, response types and params to to ApiHttpService

app/rest/dao/src/main/java/io/syndesis/dao/manager/EncryptionComponent.java
This should help with this error I encountered the other day:
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded
=> chore: Handle errors that occur if we can’t decrypt stored values.

app/ui/src/assembly/unix-dist.xml
Changes for the purposes of prod builds
- Maven assembly to only build .tar.gz
- Strip the original directory structure required for Caddy (not needed for nginx) 
- Copy license from parent pom
=> Ui assembly

app/deploy/generator/04-syndesis-oauth-proxy.yml.mustache, app/deploy/syndesis-ci.yml, app/deploy/syndesis-dev-restricted.yml, app/deploy/syndesis-dev.yml, app/deploy/syndesis-restricted.yml, app/deploy/syndesis.yml, app/rest/runtime/src/main/java/io/syndesis/runtime/SecurityConfiguration.java, tools/bin/commands/util/openshift_funcs
We need to allow non UI clients to access our backend APIs as for some of them it is cumbersome to use OAuth flow and Cookies. This is difficult for our IDE integration to do, for example.
oauth-proxy can be configured to also check if the `Authorization` header of the incoming request contains an OAuth bearer token and check if that token is valid to pass on the request to the API.
This configures oauth-proxy when running a _restricted_ variant of the templates to that end.
Caveat is that in this configuration oauth-proxy is not pasing the `X-Forwarded-Access-Token` header, and we will loose OpenShift OAuth token that we require (for some endpoints).
When `Authentication` with `null` credentials is passed on to the `PreAuthenticatedAuthenticationProvider` it fails to authenticate the …
=> Allow OAuth bearer token authentication against the backend API

app/rest/pom.xml
We need to declare RESTeasy dependencies we use, otherwise dependency
versions declared in Spring BOMs will be used, and those might differ
from the ones we want to use.
=> chore(rest): make RESTeasy version consistent

app/deploy/generator/syndesis-template.go, tools/bin/commands/util/openshift_funcs, tools/bin/install-syndesis
Productised templates use a different name, as they include also the
tag in the name (so that multiple template version can coexist
and a provisioning script can decide which of the templates to apply).
BTW, this might be also a good solution in general, too allow more
smooth upgrads.
=> fix(syndesis install): Support installation of productised templates

app/ui/src/app/common/ui-patternfly/duration-form-control.component.html, app/ui/src/app/common/ui-patternfly/duration-form-control.component.ts, app/ui/src/app/common/ui-patternfly/duration-form-control.model.ts, app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html, app/ui/src/app/common/ui-patternfly/ui-patternfly.module.ts, app/ui/src/app/core/providers/form-factory-provider.service.ts
@KurtStam FYI, note you'll want to update the `description` attribute on that field now that the user can select a time unit, currently it refers to milliseconds.
fixes #717 
Marked WIP as there's currently an override that forces this particular field to be a duration, can take that out when the connector can set `duration` for relevant fields that require this control.
=> (feat) add support for a duration form control

app/extension/converter/pom.xml, app/rest/rest/pom.xml
@rhuss this should be sufficient.. I don't see camel anymore in rest/runtime `dependency:tree`
=> (chore) remove dependency on camel-core from rest

app/deploy/generator/04-amq-example.yml.mustache, app/deploy/support/syndesis-amq.yml, app/deploy/syndesis-ci.yml, app/deploy/syndesis-dev-restricted.yml, app/deploy/syndesis-dev.yml, app/deploy/syndesis-restricted.yml, app/deploy/syndesis.yml
This PR adds AMQ broker to a default deployment with replica count set to 0. Also I've upgraded AMQ image tag to `1.3`. There's hardcoded username and password for broker to keep it simple.
It's part of example scenario from https://github.com/syndesisio/syndesis/issues/1324
=> chore(1.2.x): Include AMQ deployment in templates

app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
Follow up for #1135, fixed bugs to look at output DataShape for the previous steps and input DataShape for the subsequent steps, with tiny cleanup. Also fixed to display 1-based step index while internal index is 0-based.
=> fix: Look at right side of DataShape (input/output)

app/rest/controllers/src/main/java/io/syndesis/controllers/integration/online/PublishHandler.java, app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftService.java, app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java, app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceNoOp.java
fixes #1460 
It remains out that the list integration page never live reload its data, so to see an integration marked as fail, you still have to:
- let some time to pass, so that the executor service re-check the progress
- reload/re-enter the integration list page
=> Lifecycle, identify failed integration based on Build success

app/deploy/generator/04-syndesis-oauth-proxy.yml.mustache, app/deploy/syndesis-ci.yml, app/deploy/syndesis-dev-restricted.yml, app/deploy/syndesis-dev.yml, app/deploy/syndesis-restricted.yml, app/deploy/syndesis.yml
so that we can still install on clusters with restricted permissions.
=> chore: Removed --pass-user-bearer-token for now

app/rest/controllers/src/main/java/io/syndesis/controllers/integration/online/PublishHandler.java, app/rest/metrics-collector/src/main/java/io/syndesis/rest/metrics/collector/MetricsCollector.java, app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftService.java
The label turns to lowercase, which is a problem. Case needs to be preserved to find the camel context in the integration pod.
=> [fix] adding syndesis.io/integration-name annotation

app/connectors/connectors/sql/sql-common/src/main/java/io/syndesis/connector/sql/DatabaseMetaDataHelper.java, app/core/model/src/main/java/io/syndesis/model/integration/IntegrationDeployment.java, app/pom.xml, app/rest/controllers/src/main/java/io/syndesis/controllers/integration/IntegrationController.java, app/rest/controllers/src/main/java/io/syndesis/controllers/integration/online/OnlineHandlerProvider.java, app/rest/controllers/src/main/java/io/syndesis/controllers/integration/online/PublishHandler.java, app/rest/jsondb/src/main/java/io/syndesis/jsondb/impl/JsonRecordConsumer.java, app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java, app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/integration/support/IntegrationSupportHandler.java, ruleset.xml
This switches PMD and pmd-maven-plugin versions to 5.8.1 - the version
used by Codacy in order to eliminate the stack trace shown at build.
Fixes #1449
=> fix(codestyle): downgrade PMD

app/ui/src/app/support/support.component.html, app/ui/src/app/support/support.component.scss, app/ui/src/app/support/support.component.ts, app/ui/src/scss/base/_vendors.scss
Updates to /support to bring more inline with design from UXD with some deviations from the design signed off on by the UXD team.
https://raw.githubusercontent.com/syndesisio/syndesis/master/ux/designs/support-page/img/supportpage-landing.png
=> Bring support UI inline with design from UXD

app/ui/src/app/integration/edit-page/step-configure/step-configure.component.scss
There is a horizontal scroll coming from a negative horizontal margin on the toolbar. Looks like the negative margin is just to counteract the horizontal padding on the toolbar.
Removed them both - the page looks the same, and horizontal scroll is gone.
=> remove horizontal scroll on data mapper step

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html, app/ui/src/app/integration/edit-page/action-select/action-select.component.html, app/ui/src/app/integration/edit-page/connection-select/connection-select.component.html, app/ui/src/app/integration/edit-page/integration-basics/integration-basics.component.html, app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.html, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html, app/ui/src/app/integration/edit-page/step-select/step-select.component.html
Some pages had this and others didn't. Checked with UXD and looks like it's safe to pull it out.
From @sjcox-rh:
> @mcoker I honestly couldnt tell you why that was introduced. Im looking back through my designs now and now sure where it came from. Maybe a miscommunication with dev? Not sure.  I think it’s safe to just stick with the PF version.
=> remove fa-angle-double-left from "home" link in breadcrumbs

app/ui/src/app/integration/edit-page/connection-select/connection-select.component.html
From https://github.com/syndesisio/syndesis/issues/1262 match the text in the breadcrumbs to the text in the `<h1>` on the page.
=> change breadcrumbs to "Choose a" when choosing a start/finish connection in an integration

app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
This PR forces a round of change detection on the after view init lifecycle hook. This is not ideal but does unbreak the UI. It's a sign of a larger design flaw but that could be addressed at a later point.
@deeleman setting these values in an async fashion didn't work, unfortunately, so I opted for ChangeDetectorRef. Let me know if there's a better way for the short term.
Should help https://github.com/syndesisio/syndesis/issues/1481
update missed event bindings from ng-dynamic-form upgrade
force change detection after view init for editor
=> fix(editor): update event bindings and force change detection

app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-auth/api-connector-auth.component.ts, app/ui/src/app/customizations/api-connector/api-connector.models.ts
`tokenEndpoint` from endpoint `POST /api/v1/connectors/custom/info` is
not taken into account and set as default value when creating API
connector that has `tokenEndpoint` defined.
This adds the `tokenEndpoint` property to `ApiConnectorData` and maps
that the returned value from the endpoint in
`ApiConnectorAuthComponent`.
=> fix(ui): show suggested tokenEndpoint parameter for API connector

app/core/model/src/main/java/io/syndesis/model/metrics/IntegrationDeploymentMetrics.java
Hey guys, On a different - non metrics - page we list the number of messages per integration deployment. I'm proposing the following change. It is backwards compatible with the current metrics api.
=> [feat] Adding IntegrationDeploymentMetrics to the API

app/ui/package.json, app/ui/src/app/common/ui-patternfly/list-toolbar/list-toolbar.component.ts, app/ui/src/app/store/entity/entity.store.ts, app/ui/src/app/store/entity/events.service.ts, app/ui/src/polyfills.ts, app/ui/tslint.json, app/ui/yarn.lock
The details page of custom API connector wasn't loading as the
`combineLatest` RxJS operator wasn't imported.
This follows the best practice in the blog post by Christian Liebel[1]
on how to properly import RxJS by only loading parts that are needed
from a centrally managed imports file.
This adds `rxjs.imports.ts` that should hold all RxJS imports needed and
adds a lint rule from `rxjs-tslint-rules` to enforce its use.
[1] https://christianliebel.com/2017/07/import-rxjs-correctly/
=> chore(ui): import RxJS like a pro

app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/BaseSwaggerConnectorGenerator.java, app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/util/OperationDescription.java, app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/util/SwaggerHelper.java, app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/util/IconGenerator.java, app/rest/connector-generator/src/test/resources/swagger/basic_auth.unified_connector.json, app/rest/connector-generator/src/test/resources/swagger/petstore.unified_connector.json, app/rest/connector-generator/src/test/resources/swagger/reverb.unified_connector.json, app/rest/jsondb/src/test/java/io/syndesis/jsondb/impl/JsonDBTest.java, app/rest/runtime/src/test/java/io/syndesis/runtime/MigrationsITCase.java
Introduces `OperationDescription` and a helper method in `SwaggerHelper`
to determine name/description.
Fixes #1489
=> fix(rest): Blank action for API Client connectors

app/core/pom.xml
Add some ignoreUsedDependencies that are needed in the build, and add a plugin repository statement for SNAPSHOTS because the syndesis-build-helper-maven-plugin is used and I'm getting errors when running mvn clean and it can't resolve the plugin.
=> Add some ignoreUsedDependencies that are needed in the build

tools/bin/commands/dev
`setup_oc` is undefined unless we source openshift_funcs.
=> fix(tooling): sources `openshift_funcs` for dev command

app/core/model/src/main/java/io/syndesis/model/metrics/IntegrationDeploymentMetrics.java, app/rest/metrics-collector/pom.xml, app/rest/metrics-collector/src/main/java/io/syndesis/rest/metrics/collector/IntegrationMetricsHandler.java, app/rest/metrics-collector/src/main/java/io/syndesis/rest/metrics/collector/JsonDBRawMetrics.java, app/rest/metrics-collector/src/main/java/io/syndesis/rest/metrics/collector/PodMetricsReader.java, app/rest/metrics-collector/src/main/java/io/syndesis/rest/metrics/collector/RawMetrics.java, app/rest/metrics-collector/src/test/java/io/syndesis/rest/metrics/collector/MetricsCollectorTest.java, app/rest/metrics-collector/src/test/java/io/syndesis/rest/metrics/collector/PodMetricsReaderTest.java, app/rest/runtime/src/main/resources/application.yml
Example:
https://syndesis.192.168.64.24.nip.io/api/v1/metrics/integrations/-L5BM_0teut7ispMOjyE
```
{
messages: 551,
errors: 0,
start: 1518479066000,
lastProcessed: 1518479159000,
integrationDeploymentMetrics: [
{
version: "1",
messages: 458,
errors: 0,
lastProcessed: 1518478994000
},
{
version: "2",
messages: 93,
errors: 0,
start: 1518479066000,
lastProcessed: 1518479159000
}
],
id: "-L5BM_0teut7ispMOjyE"
}
```
=> [feat] Adding metrics split out by deployment version

app/ui/src/app/core/providers/form-factory-provider.service.ts
This PR allows the value string 'true' to set the checkboxes default checked state through our form factory service provider.
[This issue](https://github.com/syndesisio/syndesis/issues/991) was put on hold while many UI upgrades were in the works, now that this has settled we'd like to resume.
Notice in the attached image, the defaultValue property has the value string "true", instead of boolean true. This is the cause of the default value not being set correctly.
Ideally, this PR can be dismissed and the fix be applied to the back end, so we don't have to perform this type of check in the UI - it really shouldn't be there. The value is set properly (boolean true) in deployment.json, so something seems to be changing this value before its exposed via rest service.
No idea what's involved …
=> fix(checkbox): allow string "true" to set checked state by default

app/rest/runtime/pom.xml
Hi @syndesisio/backend , can we do this? it seems rest/runtime integration tests have been failing with OOM, and this could avoid the OOM for me.
=> chore: increase heap size for rest/runtime IT

app/pom.xml, app/rest/runtime/pom.xml
Since we're using basepom[1], the best way to set the heap size for
integration tests is to modify `basepom.it.memory` property, as when we
modify the `argLine` configuration property of surefire/failsafe Maven
plugins we can loose configuration parameters such as default encoding
or Jacoco agent command line parameters needed for code coverage.
[1] https://github.com/basepom/basepom
=> refactor(rest): setup integration test memory

app/ui/src/app/platform/types/integration/integration.reducer.ts
Fixes an issue that evolves into a browser exception when no integrations exist, since the reducer and related components do expect at least an empty array returned from the backend.
=> fix: collections fallback to empty arrays when the API returns no data under Http 200

app/ui/src/app/support/support.component.html, app/ui/src/app/support/support.component.scss, app/ui/src/scss/utils/_overrides.scss
Just some cleanup on the support page.
Also creating some space before the first label applied in the PT toolbar filter (global change)
Before
After
=> Clean up support page HTML/CSS, global CSS for PF toolbar labels

app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftConfigurationProperties.java, app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java
I think we could benefit from having the debug level higher for
integration builds. The default of `0` will give us just one line in the
build log:
```
Receiving source from STDIN as archive ...
```
This increases default to `1`, giving the following lines in the log:
```
Receiving source from STDIN as archive ...
Image "172.30.1.1:5000/syndesis/syndesis-s2i@sha256:c64b875d33a..." not available locally, pulling ...
Receiving source from STDIN as archive ...
Image "172.30.1.1:5000/syndesis/syndesis-s2i@sha256:c64b875d33a..." not available locally, pulling ...
Preparing to build syndesis/test-23:31a71c7a
Preparing to build syndesis/test-23:31a71c7a
Copying sources from "/tmp/s2i-build381774301/upload/src" to "/tmp/s2i-build381774301/upload/src"
Running "assemble" in …
```
=> refactor(openshift): debug option for build

app/ui/src/app/core/providers/form-factory-provider.service.ts, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts, app/ui/src/app/platform/types/form-factory/form-factory.service.ts
This PR corrects a bug in the UI where the forms service doesn't correctly handle values for setting the initial state of the checkbox in our model driven forms. It also cleans up some messy checks in the UI for the string "null" by actualling checking for null values where appropriate.
Should help:
https://github.com/syndesisio/syndesis/issues/1560 and
https://github.com/syndesisio/syndesis/issues/1250
add helper method to form factory service for suppressing null values
accept string 'false' as a falsey value for checkbox config
remove checks for string 'null' as they are no longer needed
=> fix(forms): correct and cleanup handling of form values

app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionActionHandler.java
SQL connector returns kind='none' if there's no parameter for the target SQL (#1621)
=> fix: Respect DataShapes returned via DynamicActionMetadata

app/ui/src/app/connections/create-page/create-page.component.html, app/ui/src/app/connections/create-page/create-page.component.scss, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html, app/ui/src/app/integration/edit-page/action-select/action-select.component.html, app/ui/src/app/integration/edit-page/connection-select/connection-select.component.html, app/ui/src/app/integration/edit-page/describe-data/describe-data.component.html, app/ui/src/app/integration/edit-page/edit-page.component.scss, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss, app/ui/src/app/integration/edit-page/integration-basics/integration-basics.component.html, app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.html, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html, app/ui/src/app/integration/edit-page/step-select/step-select.component.html, app/ui/src/scss/base/_mixins.scss, app/ui/src/scss/utils/_helpers.scss
Added 2 mixins `syn-scrollable-parent` and `syn-scrollable-body`, and 2 helpers `.syn-scrollable` and `.syn-scrollable--body` to support parts of the app where a main area should have an internal scrollable area.
Also updated the integration editor workflow, and connection creation workflow to utilize the new scss.
=> add mixin and helper class for scrollable body areas in app

tools/bin/commands/system-test
Removes `--server` parameter to `oc` command, bit of cleanup.
=> fix(build): system-test misc fixes

app/ui/src/app/integration/import-export/import/integration-import.component.html, app/ui/src/app/integration/import-export/import/integration-import.component.scss, app/ui/src/app/integration/import-export/import/integration-import.component.ts
Worked with UXD to bring this page inline with their original designs.
@kahboom the parts I'm not able to address are
1. Displaying the specific error message associated with each imported file beside that file. Currently I just display a generic error if the item in the uploader queue has `isSuccess = true`
2. The import review list at the bottom with details about the integration.
3. Adding a "done" button.
Are those parts you can work on, and pass back when the base functionality is there and I'll address the styling? Or would you like to handle it some other way?
=> Bring integration importer inline with UXD designs

app/ui/src/app/common/modal/modal.service.ts
Fixes #1662 
TL;DR : Overlays cannot be closed anymore by clicking outside the modal element.
Unfortunately it took me nearly 4 hours to figure out what was happening, since the state of the `ModalService` and the behavior of the client consumers is scattered across too many places. Ideally we should be able to close the modals by clicking outside by using a combination of `@HostListener('document:click')` and the `event.target` element of the clicked element. This way we can trigger/dispatch modal `hide()` and `show()` behaviors in confidence.
Unfortunately the current layout of `<ng-templates>` found in the component element makes this impossible. One day we should rule out the current implementation and use a router-based one whose state is managed by the application store instead, so …
=> fix: clicks on modal backdrop will not trigger undesired actions anymore

app/rest/controllers/src/main/java/io/syndesis/controllers/integration/IntegrationController.java, app/rest/controllers/src/main/java/io/syndesis/controllers/integration/online/PublishHandler.java, app/rest/openshift/pom.xml, app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java, tools/bin/commands/minishift
Hi, with the code change in this PR we are now supporting **both** OpenShift `3.6` and `3.7.1`.
`3.7.1` is now the new default in our companion scripts.
My test have been performed **manually** publishing and deleting a new Integration, and the test has proved to be successful on both the 2 versions.
The only thing I'm not sure, and I need your feedback is my removal of `ConfigChange` in the rebuild triggers. Do we need that? should I restore it?
Other than that, this is good to go.
=> Support OpenShift 3.7

.github/ISSUE_TEMPLATE.md, app/ui/.github/ISSUE_TEMPLATE.md
This PR summarizes what @paoloantinori, @rhuss and me discussed over the F2F regarding having a template model for new GH issues that would serve as a centralized point of reference for issues/bugs combining UI/API/Backend input.
The proposed template tries to cater with both bugs and new features. GitHub provides support for handling several issue templates in a single repository. However, I'd suggest to begin with this one and refine its content. In the future we can provide more than one template (new feature, bugs, etc), which we can trigger by means of custom browser script bookmarks (or even a custom browser extension).
=> GitHub issue template for new features and bugs

app/ui/src/app/connections/create-page/create-page.component.ts, app/ui/src/app/core/providers/form-factory-provider.service.ts, app/ui/src/app/platform/types/connection/connection.models.ts, app/ui/src/app/platform/types/form-factory/form-factory.service.ts, app/ui/src/app/platform/types/platform.models.ts
fixes #1204 
@lburgazzoli am I right that the property name is `order`?  I didn't see this property after updating my local instance, even with a full rebuild, but am guessing it's because by default no order is set currently on anything yet.
Also corrects some type info in the model.
=> (chore) add support for the 'order' property when connector/action form config specifies it

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss, app/ui/src/scss/utils/_helpers.scss
fixes #1682 
fixes #1138 
Initial work for getting the data buckets-related indicators in place for the data buckets epic, mostly so I can share with @michael-coker and get his help :-)
current design:
https://github.com/syndesisio/syndesis/blob/master/ux/designs/data-buckets/data-buckets.md#visualizing-step-id-and-showing-data-type-information-integration-visualization-panel-ivp
WIP because while the text for the step name is broken up now into different elements there's still a fair bit of layout work that needs cleanup.  The trash icon originally was using absolute positioning and outside of the step name, I've changed that and added the info icon, put them to the right for now.
Also the popovers used for showing the data mismatch text and the datashape details for connections aren't …
=> (chore) rework elements for step index, tooltips, datamapper required indicator

app/ui/src/app/integration/edit-page/flow-page.service.ts, app/ui/src/app/store/entity/entity.store.ts
We should use the error message backend supplied when handling errors.
This checks if the backend returned an error like:
```json
[
{
"error": "UniqueProperty",
"message": "Value 'test' is not unique",
"property": "update.obj.name"
}
]
```
And displays all error messages present.
Then the error message when saving integration with a non unique name presents the following error message:
Fixes #1464
=> fix(ui): display error from the backend

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
fixes #1781 
Also ensures the popovers for the data mapper alert go away when you click the link.
=> fix: use the right fake link for the datamapper popover

app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html, app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.ts, app/ui/src/app/core/providers/form-factory-provider.service.ts, app/ui/src/app/platform/types/platform.models.ts
#This PR adds support in the UI for the `relation` property from ng-dynamic-forms. The relation property allows one to supply structured logic in JSON format to control enabling/disabling form controls based on another form controls value.
This is part 1 of 2 toward making https://github.com/syndesisio/syndesis/issues/887 possible.
While ENABLE/DISABLE is currently supported all the way through the view layer, VISIBLE/HIDDEN are only supported at the model level, meaning you cannot (yet) supply VISIBLE/HIDDEN action values. For that, we will need to further augment `syndesis-form-control.component.html`. Partial support here is better than no support so I wanted to go ahead and get this in.
One expected regression is that the oauth forms in the settings section of the app will no longer …
=> feat(forms): add basic support for relation property

.gitignore, app/deploy/generator/04-syndesis-rest.yml.mustache, app/deploy/generator/04-syndesis-verifier.yml.mustache, app/deploy/generator/06-syndesis-prometheus.yml.mustache, app/deploy/syndesis-dev.yml, app/deploy/syndesis.yml, doc/.gitignore
This is necessary since i.e. syndesis-rest has been grown so that it infers with the liveness probe which would kill the pod when it doesnt startup in 200s
=> fix(templates): Increase livenessProbe initialDelay for Java apps

app/common/model/src/main/java/io/syndesis/common/model/Dependency.java, app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json, app/connector/support/test/src/main/java/io/syndesis/connector/support/test/ConnectorTestSupport.java, app/integration/api/src/main/java/io/syndesis/integration/api/IntegrationResourceManager.java, app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/TestResourceManager.java, app/server/builder/image-generator/src/main/java/io/syndesis/server/builder/image/generator/Application.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/ExtensionHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/support/IntegrationSupportHandler.java, app/server/runtime/src/main/java/io/syndesis/server/runtime/IntegrationConfiguration.java
This adds support for EXTENSION_TAG dependencies. A connector that depends on a extension tag will automatically include all extension with that tag on the classpath.
This is needed to automatically import all jdbc drivers.
=> Related to #1752: add extension-tag dependency type

app/ui/src/app/integration/integration_detail/integration-detail.component.html, app/ui/src/app/integration/integration_detail/integration-detail.component.scss
This fix is a workaround for a regression detected on the integration detail view, where the body of the detail view does not resize vertically anymore to cover up the screen half
=> fix: CSS bugfix to force integration detail page span 100% vertically

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/EndpointStepHandler.java
We should be using the scheme-index endpoint URI for all endpoint URIs
regardless of the configured properties being component properties or
not.
Fixes #1832
=> fix(integration): use the scheme-index endpoint URI

app/common/model/src/main/java/io/syndesis/common/model/connection/DynamicActionMetadata.java, app/connector/support/verifier/src/main/java/io/syndesis/connector/support/verifier/api/MetadataRetrieval.java, app/meta/src/main/java/io/syndesis/connector/meta/VerifierExceptionMapper.java, app/meta/src/main/java/io/syndesis/connector/meta/v1/ConnectorEndpoint.java, app/meta/src/main/java/io/syndesis/connector/meta/v1/metadata/SalesforceMetadataRetrieval.java, app/server/endpoint/pom.xml, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/dto/Meta.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/dto/Mixed.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/MetadataCommand.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/exception/Errors.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/dto/MixedTest.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java, app/server/runtime/src/main/resources/application.yml, app/server/runtime/src/test/java/io/syndesis/server/runtime/BaseITCase.java, app/server/runtime/src/test/resources/application-test.yml, app/server/verifier/src/main/java/io/syndesis/server/verifier/AlwaysOkVerifier.java, app/server/verifier/src/main/java/io/syndesis/server/verifier/ExternalVerifierService.java, app/server/verifier/src/main/java/io/syndesis/server/verifier/MetadataConfigurationProperties.java, app/server/verifier/src/main/java/io/syndesis/server/verifier/VerifierConfiguration.java, app/ui/src/app/api/api.module.ts, app/ui/src/app/api/providers/api-http-interceptor.service.ts, app/ui/src/app/api/providers/index.ts, ruleset.xml
There is much more details in the commit messages.
In nutshell this adds hystrix when invoking the `syndesis-meta` for dynamic metadata. This way we can guarantee if an error or no response within 1.5s is  received from `syndesis-meta` that it can be properly handled.
The handling part uses a new mixin for the API responses, by which we can add `_meta` property to any API response. This `_meta` property consists (currently) of only two properties (type & message).
Adds an interceptor for HTTP responses in the UI, that checks if the `_meta` property is present in the response and displays a toast notification with the provided content.
Fixes #1659
=> Nicer error handling when fetching dynamic metadata

app/extension/maven-plugin/pom.xml, app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java, app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/RepackageExtensionMojo.java
This allows to:
- use repositories declared in the pom.xml when building and
- use the correct order of override for metadata generation
@lhein the order is:
1. plugin xml configuration (max priority)
2. json fragment
3. project pom.xml data
I think this is what you are expecting in #1833, right?
=> Fix syndesis extension plugin

app/ui/src/app/common/cancel_confirmation_modal/cancel-confirmation-modal.component.ts, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html
Fixes #1270 - this was a bit confusing since the reference issue didn't formalize a final set of requirements or acceptance criteria in its abstract, so I picked what I thought was the expected DoD from the comments thread, which is not very accurate unfortunately.
Typos on the cancel modal has been addressed as well and the cancel modal now feature fully configurable labels on its buttons, in addition to swap their location.
=> fix: cancel action modal CTAs enhanced according to UXD requirement

app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.html, app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.ts
Fixes #1818 
On a side note, this PR also entails two additional enhancements, derived from side discussions held at #1597:
- Activity records now show a time data detailed to the second
- Pagination nav will only be displayed and enabled when the activity recordset exceeds the minimum page size, remaining hidden otherwise.
=> feat: integration activity list sorted by date

app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java
Relates to  #1813
Fixes #1841
For anyone looking into this, mind that after this is fixed there is another unrelated bug preventing an integration to deploy successfully:
https://github.com/syndesisio/syndesis/issues/1859
=> Server, sanitize ids in labels

app/common/util/src/main/java/io/syndesis/common/util/KeyGenerator.java
This change, which preservers all characteristics of the keys, makes is possible to use ids directly as k8s label values.
Fixes #1868
=> refactor(keygenerator): Changed to make it possible to use ids as label values

app/connector/support/test/src/main/java/io/syndesis/connector/support/test/ConnectorTestSupport.java, app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java, app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGeneratorAutoConfiguration.java, app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGeneratorConfiguration.java, app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/ProjectGeneratorTest.java, app/server/builder/image-generator/src/main/java/io/syndesis/server/builder/image/generator/Application.java, project/DevelopersGuide.md
Support for external Maven repos was broken, since a new instance of `MavenProperties` object was used, instead of asking DI container to provide the one bound to the external properties.
This PR fixes it.
Manually tested locally.
See also detailed manual step to apply the configuration in the modified `DeveloperGuide.md`
=> ProjectGenerator, fix support for external Maven repos

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/dto/Meta.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/dto/MetaData.java
IDEA doesn't work with immutables defined on inner interfaces.
That's the only reason for this change.
=> chore: Move inner class of Meta to top-level

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/dto/Meta.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java, app/server/verifier/src/main/java/io/syndesis/server/verifier/MetadataConfigurationProperties.java
This increases the timeout to fetch metadata to 15 seconds (from 1.5 seconds) and adds a warning in case of timeouts.
Fixes #1886, #1867, #1842, #1865
=> fix(meta): increased timeout to 15 seconds and added warning

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts
=> fix: don't overwrite data shapes if the new ones don't have a specification

app/common/model/src/main/java/io/syndesis/common/model/connection/ConfigurationProperty.java, app/connector/activemq/src/main/resources/META-INF/syndesis/connector/activemq.json, app/connector/amqp/src/main/resources/META-INF/syndesis/connector/amqp.json, app/connector/aws-s3/src/main/resources/META-INF/syndesis/connector/aws-s3.json, app/connector/dropbox/src/main/resources/META-INF/syndesis/connector/dropbox.json, app/connector/ftp/src/main/resources/META-INF/syndesis/connector/ftp.json, app/connector/http/src/main/resources/META-INF/syndesis/connector/http4.json, app/connector/http/src/main/resources/META-INF/syndesis/connector/https4.json, app/connector/mqtt/src/main/resources/META-INF/syndesis/connector/mqtt.json, app/connector/sftp/src/main/resources/META-INF/syndesis/connector/sftp.json, app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json, app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json, app/connector/twitter/src/main/resources/META-INF/syndesis/connector/twitter.json, app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentDefinition.java, app/ui/src/app/core/providers/form-factory-provider.service.ts, app/ui/src/app/platform/types/platform.models.ts
This PR utilizes a new property name "labelHint" which used to be referred to as "description". It also adds a new property "placeholder" to allow our model driven forms to add placeholder text to text inputs to illustrate syntax for a given field. This also makes use of the new "relation" property for the brokerCertificate and clientCertificate fields in the amq connection config.
Should help https://github.com/syndesisio/syndesis/issues/992 and https://github.com/syndesisio/syndesis/issues/250
utilize new labelHint property in form field definitions
add new placeholder property in forms service
add form relation for amq client,broker certificate
=> feat(forms): add support for placeholder text in form controls

app/test/src/test/resources/setup.sh, install/README.md, install/staging/README.md, tools/bin/commands/util/openshift_funcs, tools/bin/install-syndesis
Using "oc new-app <foo> " may not work for some oc client versions (at least oc 3.6) if <foo> is also a name of a directory in the current working directory:
"error: Unable to connect to the server: first path segment in URL cannot contain colon"
Using --template=<foo> works even if <foo> exists as a directory in CWD.
=> Use --template param explicitly with oc new-app

app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlStartConnectorCustomizer.java
Adds a bit more robustness to post processing by not throwing an
exception if the result is empty or null.
Fixes #1894
=> refactor(connector): make the empty bodies a no-op

app/common/util/src/main/java/io/syndesis/common/util/Names.java, app/common/util/src/test/java/io/syndesis/common/util/NamesTest.java
This replaces all underscore (`_`) characters with dashes (`-`), and also enforces that the start of the name is a alphanumeric.
Refactors the use of regular expressions to use compiled Pattern instead of compiling the pattern on each regular expression use.
Fixes #1921
=> fix(common): names should not include underscore

app/connector/activemq/src/main/resources/META-INF/syndesis/connector/activemq.json, app/connector/http/src/main/resources/META-INF/syndesis/connector/http4.json, app/connector/http/src/main/resources/META-INF/syndesis/connector/https4.json, app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.ts
This PR is mostly cleanup, removing "draft" from the dashboard donut counter to improve simplicity and clarity around what users actually have in their environment. Left support for it inside getLabelClass in case any of the other dashboard widgets need it.
removed draft state from dashboard integrations counter
tweak form properties for activemq connector
=> fix(donut): remove draft state from dashboard integrations donut

app/common/pom.xml, app/pom.xml, app/server/pom.xml, app/test/pom.xml, app/test/src/test/java/io/syndesis/systests/DeploymentTest.java, app/test/src/test/resources/arquillian.xml, app/test/src/test/resources/setup.sh
This upgrades versions of Arquillian, Arquillian Cube, Fabric8
Kubernetes Client and cleans up Maven POMs. Path to OpenShift templates
was fixed and if $WORKSPACE is not defined relative path to `/install`
is used. Test for UI readiness is enabled again.
Tested locally.
=> refactor(system-tests): upgrades and cleanup

app/meta/pom.xml, app/meta/src/main/fabric8-includes/run-env.sh, app/meta/src/main/java/io/syndesis/connector/meta/v1/DriverUploadEndpoint.java, app/meta/src/test/java/io/syndesis/connector/meta/v1/DriverUploadTest.java, app/pom.xml, install/generator/04-syndesis-verifier.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml
This allows to add uploaded drivers in the loader path without having to unpack them. LOADER_HOME and LOADER_PATH are now used consistently in meta pod and integration pods. 
Requires template reinstall, as a env variable in the meta template is changed.
=> Fix driver upload management

app/ui/src/app/common/ui-patternfly/duration-form-control.component.html, app/ui/src/app/common/ui-patternfly/duration-form-control.component.ts, app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html, app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.spec.ts, app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.ts
This PR corrects the event bindings for our model driven forms, and in turn allows the correct callbacks to fire when the duration control's value has changed.
The same fix has been applied for all form controls.
bind to and declare appropriate event names
remove dom id from duration control that's no longer needed
remove unneeded @Input
update test
fixes #1930
=> fix(forms): update event bindings

app/ui/src/app/common/delete_confirmation_modal/delete-confirmation-modal.component.ts, app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html, app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.ts
Fixes #1827 
Behold humans, the beauty of deleting things...
=> fix: Custom API Connector delete button is back with a repurposed confirmation modal

install/generator/01-header.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml
The requirement is related to an AWS limitation for EBS that would anyhow allocate 1Gi chunks, even if a pvc asks for less, wasting space and adding it from sight.
=> Templates, bumped verifier pvc demands to 1Gi

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/dto/MetaData.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
When metadata call to `syndesis-meta` fails we should provide the UI with status 400 in addition to the `_meta` property being added.
=> refactor(server): return status 400 for errors from meta

tools/bin/install-syndesis
Allows to omit explicit "route" parameters when OpenShift default configuration is enough.
Permits to be run like this:
```bash
bin/install-syndesis --project "$(oc project -q)" --route auto --tag 1.3.0 
```
fixes #1661
=> Install script, add support for route auto discovery

.circleci/config.yml, app/ui/karma.conf.js
This changes the configuration of Karma test runner to output JUnit test
XML result file to `target` directory when the tests are run.
This in turn will be picked up by CircleCI so we can see what tests
failed without rummaging through the step console output.
=> chore(build): add test reports from UI to CircleCI

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorIconHandler.java
The `InputStream` set on the Icon was not closed and as a result
database resources were never freed. This makes sure that the resources
are freed by wrapping their use in try-with-resources block.
Fixes #2015
=> fix(server): fix connection leak

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/action/DynamicActionSalesforceITCase.java
**Builds on PR #1979, have a look at that one.**
With this if the result of metadata invocation for data shapes that
should contain specification/type, i.e. all that don't have their kind
defined as `none` or `any, and do not in fact contain those, for
instance if the meta data invocation fails or returns an erroneous data
shape, the resulting data shape will be set to `kind=any`.
Fixes #1967
=> fix(server): try to use correct input/output shapes

app/connector/activemq/src/main/resources/META-INF/syndesis/connector/activemq.json, app/connector/amqp/src/main/resources/META-INF/syndesis/connector/amqp.json
This PR applies some tweaks to the amq/amqp connection configuration to improve the language around setting or skipping a certificate check.
Outstanding question - should the amqp connection also use the same description for the type of broker/client certificate that's used?
@TovaCohen @dongniwang let me know if you see any issues!
switch language around so that amq connection config flow is more intuitive
=> fix(amq-connection): tweak forms to avoid double negative

app/common/pom.xml, app/integration/project-generator/pom.xml, app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/connector/pom.xml.mustache, app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/TestConstants.java, app/integration/project-generator/src/test/resources/test.properties, app/server/connector-generator/src/test/resources/swagger/basic_auth.unified_connector.json, app/server/connector-generator/src/test/resources/swagger/complex_xml.unified_connector.json, app/server/connector-generator/src/test/resources/swagger/petstore.unified_connector.json, app/server/connector-generator/src/test/resources/swagger/petstore_xml.unified_connector.json, app/server/connector-generator/src/test/resources/swagger/reverb.unified_connector.json, app/server/connector-generator/src/test/resources/swagger/todo.unified_connector.json, app/server/pom.xml
This replaces `syndesis-connectors.version` for `project.version` or
`syndesis.version` where appropriate.
Fixes #750
=> refactor(server): use proper property name

app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.html, app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.ts
Fixes #2065 
Whenever no steps are returned in the activity logs, the listview degrades gracefully and shows a default message, as depicted below:
=> fix: activity table now degrades gracefully when no steps data is available

app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/UnpublishHandler.java, app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftService.java, app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java, app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceNoOp.java, app/ui/src/app/integration/integration_detail/integration-detail.component.html
We no long block until integration is scaled down. We set the status to pending and return. Followup calls to the Unpublish handler will determine when the integration is actually unpublished and set the correct status then. This allows the "Unpublishing" text to appear in the ui.
=> fix: (#1892) Unpublishing is now displayed as a status when unpublishing an integration.

doc/sdh/cli/cmd_install.adoc, doc/sdh/cli/cmd_minishift.adoc, install/generator/01-header.yml.mustache, install/generator/04-syndesis-meta.yml.mustache, install/generator/04-syndesis-server.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml, tools/bin/commands/install, tools/bin/commands/minishift, tools/bin/commands/util/openshift_funcs
* New defaults: 800Mi (server) and 512Mi (meta)
* 'syndesis minishift' and 'syndesis install' now has options --memory-rest and --memory-meta
* Updated documentation
* Streamlined scripts a bit
=> feature: Parameterised memory limit for 'sever' and 'meta'

install/support/syndesis-amq.yml
There's forgotten whitespace that prevent proper recognition of params.
=> fix: Fix AMQ template param definition

app/ui/src/app/common/ui-patternfly/duration-form-control.component.ts
=> fix: Use the higher value unit when the division result is 1 too

doc/sdh/development/labels.adoc
Update SDH's label descriptions for pr/approve, pr/wip and pr/review-requested
There is a slight update of the label related to PR to reflect the update pull request better. 
This PR updates the documentation and is just a small heads up. Happy for any feedback how refine the PR process further.
=> chore: Update SDH's label descriptions for pr related labels

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java, app/server/filestore/src/main/java/io/syndesis/server/filestore/impl/SqlFileStore.java, app/ui/src/app/common/icon-path.pipe.ts, app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.ts
1. Browser API incompatibility: replace `event.srcElement` with `event.target`
We should not use `event.srcElement` it's proprietary, we should use the standard `event.target`. Too bad that the type definitions are not up to date for `EventTarget`.
2. Updated icon not showing up in Firefox: make icons reflect changes
As the URL of the icon never changes when modifying the icons of API connectors the old icon is not replaced with the newly uploaded one regardless of `Cache-Control` headers in Firefox.
This adds the icon id, from the database, as a query parameter to the icon URL which will make it reload the icon when it's changed.
Also adds `iconFile` property as it is set at first icon submission in on the `CustomConnectorRequest`. This makes the icon change show up immediately. Very …
=> Fix several issues with icon handling

tools/bin/commands/release
and removed the reverting to the developer versions, as we are
pushing the tags directly (not the branches) we don't need to revert anything.
=> chore(syndesis): Fix creation of productised templates

doc/integrating_applications/topics/adding_dropbox_connection_finish.adoc, doc/integrating_applications/topics/adding_dropbox_connection_middle.adoc, doc/integrating_applications/topics/adding_dropbox_connection_start.adoc, doc/integrating_applications/topics/adding_dropbox_connections.adoc, doc/integrating_applications/topics/connecting_to_applications.adoc, doc/integrating_applications/topics/connecting_to_dropbox.adoc, doc/integrating_applications/topics/create_dropbox_connection.adoc, doc/integrating_applications/topics/making_extensions_available.adoc, doc/integrating_applications/topics/register_with_dropbox.adoc, doc/shared/register_with_sf.adoc, doc/shared/register_with_twitter.adoc
This is the initial draft of the user doc for using the Dropbox connector. If you could review this so that I have your feedback by the start of my day on Wednesday, that would be great. You might want to review the Dropbox files in this order:
topics/connecting_to_dropbox.adoc
topics/register_with_dropbox.adoc
topics/create_dropbox_connection.adoc
topics/adding_dropbox_connections.adoc
topics/adding_dropbox_connection_start.adoc
topics/adding_dropbox_connection_finish.adoc
topics/adding_dropbox_connection_middle.adoc
The other files make a few other updates.
=> user doc: Create doc for Dropbox connector (#1623 #1189)

app/common/model/src/main/java/io/syndesis/common/model/bulletin/LeveledMessage.java, app/server/update-controller/src/main/java/io/syndesis/server/update/controller/ResourceUpdateHelper.java, app/server/update-controller/src/main/java/io/syndesis/server/update/controller/impl/ConnectorUpdateHandler.java, app/server/update-controller/src/test/java/io/syndesis/server/update/controller/ResourceUpdateHelperTest.java
See #2151
@gashcrumb I've squashed messages so:
* In case of simple a property gets updated:
```json
{
"board": {
"targetResourceId": "i-L8czqFBPC1QT7GAqG5iz",
"notices": 1,
"warnings": 0,
"errors": 0,
"id": "i-L8czqGkPC1QT7GAqG5jz",
"metadata": {
"connector-id": "ext-io-syndesis-extensions-syndesis-connector-telegram",
"connector-version-latest": "2",
"connector-version-connection": "1"
},
"messages": [
{
"level": "INFO",
"code": "SYNDESIS001"
}
],
"createdAt": 1522179990640,
"updatedAt": 1522180068211
}
}
```
* In case of a new required field:
```json
{
"board": {
"targetResourceId": "i-L8czqFBPC1QT7GAqG5iz",
"notices": 0,
"warnings": 1,
"errors": 0,
"id": "i-L8czqGkPC1QT7GAqG5jz",
"metadata": {
"connector-id": "ext-io-syndesis-extensions-syndesis-connector-telegram", …
```
=> fix(endpoint): squash LeveledMessage

app/pom.xml, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/state/ClientSideState.java
When unable to deserialize client side state cookie the log contains the
full stack trace. This changes the logging to log the full exception
only when DEBUG level is enabled.
Fixes #2045
=> refactor(server): terser log message

app/pom.xml, app/server/endpoint/pom.xml, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/state/ClientSideState.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/state/StaticEdition.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/state/StaticEditionTest.java, install/generator/01-header.yml.mustache, install/generator/02-syndesis-secrets.yml.mustache, install/generator/04-syndesis-db.yml.mustache, install/generator/04-syndesis-server.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml
In order to address #1949 this changes few things around:
- increases client side state timeout from 15min to 30min, so cookies holding client state will be considered valid up until they're 30mins old
- places the configuration of the client side state implementation in the OpenShift template and the keys used in the Secret, this allows the syndesis-server pod to validate/decrypt client side state cookies after restarts
This also tidies up the template header and removes some trailing whitespace from the templates.
Fixes #1949
=> More robustness in handling client side state

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/LogStepHandler.java
when "message context logging" is enabled.
=> fix (#2177): LogStepHander now adds message headers to the expression

app/ui/src/app/app.component.html
This PR better exposes navigation links and their current state (expanded/collapsed) for the primary menus to screen readers.
Fixes #2201 
define role attributes for banner, navigation, and main to ensure these regions are exposed as landmarks in VoiceOver
use proper division element for navigation container
tie in aria-* attributes so user and help dropdown's properly express expanded/collapsed state in VoiceOver
use proper nav element for sidebar navigation
=> fix(navigation): make navigations more accessible

app/ui/src/app/common/common.module.ts, app/ui/src/app/common/index.ts, app/ui/src/app/common/inline-alert/index.ts, app/ui/src/app/common/inline-alert/inline-alert.component.html, app/ui/src/app/common/inline-alert/inline-alert.component.ts, app/ui/src/app/connections/detail-page/detail-page.component.ts, app/ui/src/app/connections/detail-page/info.component.ts, app/ui/src/app/core/core.module.ts, app/ui/src/app/core/providers/index.ts, app/ui/src/app/core/providers/status-code-decoder-provider.service.ts, app/ui/src/app/integration/integration_detail/integration-detail.component.html, app/ui/src/app/platform/types/connection/connection.models.ts, app/ui/src/app/platform/types/index.ts, app/ui/src/app/platform/types/integration/integration.models.ts, app/ui/src/app/platform/types/platform.models.ts, app/ui/src/app/platform/types/status-code-decoder/index.ts, app/ui/src/app/platform/types/status-code-decoder/status-code-decoder.service.ts
fixes #2151 
Also syncs up some type interfaces with the backend a bit and adds an initial spike for a service to decode backend status codes to a string message with some TODOs in there.
Also adds an inline alert component to help cut down on the copypasta for leveled messages from the backend.
=> feat: add inline notifications to connection detail page

app/server/dao/src/main/java/io/syndesis/server/dao/manager/DataManager.java
Fixes #2186.
@KurtStam, @chirino , the check for duplicate name was applied to all `WithName` objects, but then verified against the set of `Connections` in the jsondb. For this reason I couldn't create a `Extension` with the same name of a existing `Connection`.
This PR limits duplicate name checks to connections only.
An alternative would have been to extend check to every entity, but I already know that it cannot be applied e.g. to `Extension`: two extensions with the same name can coexist (one in status installed, the other inactive).
cc: @gashcrumb
=> Restrict duplicate name check to connections only

app/common/model/src/main/java/io/syndesis/common/model/bulletin/ConnectionBulletinBoard.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java
Fixes #2200. If a BulletinBoard object is present in jsondb, syndesis failed at startup because of a classloading cycle leaving a uninitialized static variable.
=> Break classloading cycle on startup

app/ui/src/app/app.component.html, app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts, app/ui/src/app/settings/oauth-apps/oauth-apps.component.html
This PR adjusts the language used in the select dropdown in the describe data component form, making it clearer to the user what selecting that option does.
Also removes the period at the end of a sentance on the oauth settings page so users don't accidentally copy it along with their callback url.
Adding the role attribute for anchor links ensures older version of JAWS screen reader acknowledges those as available links.
fixes https://github.com/syndesisio/syndesis/issues/1940
ux language tweaks for describe data step
remove period form end of callback url for easy copy/paste
set explicit roles on anchors for links
=> feat(describe-data): improve language used around describe data form

app/connector/http/src/main/java/io/syndesis/connector/http/HttpConnectorFactories.java, app/connector/http/src/main/java/io/syndesis/connector/http/HttpConnectorVerifierExtension.java, app/connector/salesforce/src/main/java/io/syndesis/connector/salesforce/customizer/DataShapeCustomizer.java, app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java, app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/layout/ModuleLayoutFactory.java, app/meta/src/main/java/io/syndesis/connector/meta/Application.java, app/meta/src/main/java/io/syndesis/connector/meta/v1/DriverUploadEndpoint.java, app/pom.xml, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/support/IntegrationSupportHandler.java, app/server/jsondb/src/main/java/io/syndesis/server/jsondb/impl/JsonRecordConsumer.java, ruleset.xml
This upgrades PMD Maven plugin to 3.9.0 and PMD version to 6.2.0 in an
attempt to try to fix a race issue when running PMD check from Maven
multiple times without performing a clean.
This unfortunately does not help to resolve the issue, and I had to
disable PMD cache.
This fixes PMD issues brought about with the PMD upgrade. Seems that
some of the issues were not reported with the previous version.
Removes the `break` that would prevent any additional integrations in
the submitted export ZIP file from being imported.
Fixes #2209, #2240
=> chore(build): upgrade PMD

app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.html, app/ui/src/app/integration/list/list.component.html, app/ui/src/app/integration/list/status.component.ts, app/ui/src/app/platform/types/integration/integration.models.ts
relates to #2245 
Also cleans up some past search/replace/copypasta
=> fix: align the draft area property to the returned integration object add a separate draft indicator to the list

app/ui/src/app/app.component.html
Since this wasn't happening for quite awhile:
=> fix: make the home link highlight properly when at the dashboard

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/activity/Activity.java, app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/service/DBActivityTrackingService.java
fixes #2065
This is quick and dirty, and one of the narrowest scope I could find to implement this.
Feel free to improve it but consider merging this to close this current blocker.
It would also deserve a unit test to avoid regressions in future.
=> Activity: fix for serialization strategy and empty collections

app/server/runtime/src/main/resources/application.yml, app/server/update-controller/src/main/java/io/syndesis/server/update/controller/ResourceUpdateConfiguration.java, app/server/update-controller/src/main/java/io/syndesis/server/update/controller/ResourceUpdateController.java
The update-controller can now be configured to perform an intial check for updated resources and then react to events instead of having also a background periodic task
=> chore(server): improve update-controller

doc/integrating_applications/docinfo.xml, doc/integrating_applications/master.adoc, doc/integrating_applications/topics/about_extensions.adoc, doc/integrating_applications/topics/how_you_use.adoc, doc/master.adoc, doc/shared/attributes.adoc, doc/tutorials/master-docinfo.xml, doc/tutorials/master.adoc, doc/tutorials/topics/amq2api_create_custom_step.adoc
I should have made these updates in a new branch with an appropriate name. But I forgot. 
This is ready to merge. And I believe I can merge it myself. There are just doc updates for:
- Use attributes in place of explicit URLs. 
- Use "Syndesis" as the product name upstream only. 
- Remove references to "technology preview".
=> user doc: Updates to use attributes in place of hardcoded URLs. 

app/ui/src/app/api/api.module.ts, app/ui/src/app/api/providers/api-xsrf-interceptor.service.ts, app/ui/src/app/api/providers/index.ts, app/ui/src/environments/environment.prod.ts, app/ui/src/environments/environment.ts
This PR covers up the UI parts for #2104
###
This PR leverages Angular's `HttpClientXsrfModule` and also implements a custom `HttpInterceptor` middleware that will incorporate the following functionality to Syndesis:
- The server can now send a XSFR token cookie to the frontend. The name for the cookie is fully configurable.
- Such token will be fetched from said cookie and appended in a custom header on every outgoing request made to the API. The name for the header is fully configurable.
- If no XSRF cookie is sent to the client, no XSFR token header will be sent back.
**Please note:** The token header is NOT appended on non-mutating requests (GET, HEAD).
The UI [environments](https://github.com/syndesisio/syndesis/tree/master/app/ui/src/environments) folder contains the development and …
=> feat(ui): Prevent XSRF exploit by appending token to custom headers from server cookie

app/ui/src/app/connections/list/list.component.html, app/ui/src/app/integration/integration_detail/integration-description.component.html, app/ui/src/app/integration/integration_detail/integration-description.component.scss
fixes https://github.com/syndesisio/syndesis/issues/2249
also snuck in a fix for a small bug where the empty state card for connections when you're creating an integration doesn't share the same bootstrap `col-*` classes as the rest of the cards so it was misaligned.
=> truncate long connection names under integration details icons

app/connector/support/maven-plugin/src/main/java/io/syndesis/connector/support/maven/GenerateConnectorInspectionsMojo.java
Seems that Atlasmap inspections embedded in connector JSON files are
causing the the Connection/Connector objects to be quite large. This is
mainly due to the use of pretty-printing when generating those embedded
JSON specifications.
By not using a pretty-printing JSON serialization this can be greatly
reduced, for 5 test connections the JSON payload for is reduced from
1.2M (1248066) to 685K (700638), i.e. 44% decrease in size.
=> fix: slimmer inspections in connectors

doc/integrating_applications/topics/creating_api_connectors.adoc, doc/integrating_applications/topics/register_with_dropbox.adoc, doc/integrating_applications/topics/registering_with_rest_api.adoc, doc/shared/register_with_sf.adoc, doc/shared/register_with_twitter.adoc
Updated instructions for obtaining the callback URL. Ready to merge.
=> user doc: Update references to callback URL to use URL at top of OAuth mgmt page

app/ui/src/app/app.component.html, app/ui/src/app/app.component.ts, app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html, app/ui/src/app/settings/oauth-apps/oauth-apps.component.html, app/ui/src/assets/dictionary/en-GB.json
Fixes #2278 
@seanforyou23 Please note how the dictionary file is also a pretty convenient place to store information such as email and links, so those can be localized and embedded into some other more complex strings without having to pass those as pipe parameters.
=> chore(ui): Customer portal user doc links updated and and managed thru i18n

app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlConnectorTest.java, app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/util/OperationDescription.java, app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/util/SwaggerHelper.java, app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/BaseSwaggerConnectorGeneratorTest.java, app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/util/SwaggerHelperOperationDescriptionGenerationTest.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/IntegrationsITCase.java
Swagger parser interprets empty strings as literal `"null"` strings.
This results in having the string `"null"` as a name or description of a
operation. This checks if the parsed string is literal `"null"` string
and generates the proper name/description as if it was literal `null`
value.
The two other commits are adding tests and cleaning.
Fixes #2223
=> fix(server): operation summaries not shown as null

app/pom.xml, ruleset.xml
This reverts PMD version upgrade as in 6.x PMD started using
unsynchronized access `WeakHashMap`, which can lead to endless loops.
=> fix(build): revert PMD version upgrade

app/ui/src/app/core/providers/i18n-provider.service.ts, app/ui/src/app/platform/types/i18n/README.md, app/ui/src/polyfills.ts
This fixes the `I18NService.getValue(dictionaryKey: string, args?: any[]): Observable<string>` method available at the `I18NService` injectable service class, allowing for harnessing the features of the I18N implementation imperatively within component controllers and services.
=> fix(UI): i18n string fetching can now be performed imperatively support i18n provider

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorIconHandler.java
Fix #2289
There was a input stream left behind that caused ultimately a connection leak.
Syndesis became unresponsive after reaching ~100 open connections.
=> Fix connection leak in extension icon retrieval

app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.ts
When no tags are provided `actionCountByTags` property might be
undefined and we need to support that for Swagger specifications that do
not offer any tags.
Fixes #2308
=> fix(ui): handle swagger specifications with no tags

app/pom.xml
This adds a Maven enforcer rule to check if the JVM running the Maven
process has an imposed limit to cryptography.
=> chore(build): enforce unlimited cryptography JVM

app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.html, app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.scss
fixes https://github.com/syndesisio/syndesis/issues/2199
**Please note** - this will just fix the spinner placement for the connection area on the dashboard. I also created another branch, [loader-ui](https://github.com/michael-coker/syndesis/tree/loader-ui), that contains the spinner icon within the `<syndesis-loading>` element across the app. This will change the position of the icon in a lot of places - not sure if that's good or bad. If you prefer the other approach, I can submit a PR for that branch instead.
=> Dashboard connection spinner positioning

app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/BaseSwaggerConnectorGenerator.java, app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/PropertyGenerators.java, app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/SyndesisSwaggerValidationRules.java, app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/AbstractSwaggerConnectorTest.java, app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/BaseSwaggerConnectorGeneratorTest.java, app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/PropertyGeneratorsTest.java, app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/TestHelper.java, app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/util/SwaggerHelperTest.java
This replaces throwing exceptions from property generators to Swagger
specification validation thereby increases the robustness of Swagger
specification parsing/handling.
With this for minimal valid Swagger files we should be able to present
the user with issues that are identified in the validation of the
Swagger specification.
Fixes #2307
=> chore(server): swagger specification parsing robustness

app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/ConnectionUpdateHandler.java, app/server/update-controller/src/test/java/io/syndesis/server/update/controller/bulletin/ConnectionUpdateHandlerTest.java
This merges configured properties from the connector and the connection
when considering if properties that are required are defined.
Fixes #2362
=> fix(server): consider properties configured on connector

app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/SwaggerConnectorComponent.java, app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/SwaggerConnectorComponentTest.java
This fixes Base64 encoding of basic authentication in the
`Authorization` header for the `connector-rest-swagger` connector.
Fixes #2369
=> fix(connector): proper basic authentication encoding

app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/PropertyGenerators.java, app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/BaseSwaggerConnectorGeneratorTest.java, app/server/connector-generator/src/test/resources/swagger/concur.swagger.json, app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json
This adds support for `x-token-strategy` and
`x-authorize-using-parameters` vendor extensions. These control how the
OAuth2 flow is executed:
- setting `x-token-strategy` vendor extension to:
- AUTHORIZATION_HEADER (default): indicates that the access token
should be carried in the Authorization header as an OAuth2 Bearer
token
- ACCESS_TOKEN_PARAMETER: indicates that the access token should be
carried as a query parameter named "access_token"
- OAUTH_TOKEN_PARAMETER: indicates that the access token should be
carried as a query parameter named "oauth_token"
- setting `x-authorize-using-parameters` to `true` (`false` is
default) will pass client credentials to the provider as parameters
instead of using HTTP Basic authentication.
Example Swagger specification:
```yaml
securityDefinitions: …
```
=> feat(server): additional oauth2 properties via vendor extensions

app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationDeployment.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/IntegrationController.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/UnpublishHandler.java
What it actually does, is that it periodically polls for the actual state of all integrations (not just the ones triggered by a change event.
As a result, any integration externally modfied (dc deleted or scaled down) will be redeployed by the system.
=> This pull request is supposed to provide a fix for #1641.

app/ui/src/app/api/providers/api-http-provider.service.ts
Since many components and services do not handle Http exceptions right, [this PR ](https://github.com/syndesisio/syndesis/pull/2349) introduced a new Http interceptor that offered a convenient toast notification when API errors (500, 401, etc) occur, catching all those exceptions and not allowing them to propagate.
But Redux effects do expect those exceptions to be propagated since that is the way that `XXXX_ERROR` actions are triggered. Therefore this PR reinstates Http exception propagation which, ultimately, is supposed to be harmless.
So long and thanks for the all fish!
https://youtu.be/ojydNb3Lrrs
=> chore(ui): always propagate http exceptions

app/connector/aws-s3/src/main/resources/META-INF/syndesis/connector/aws-s3.json
This PR changes the type of form control that's used for the delay field when configuring an S3 connection.
fixes https://github.com/syndesisio/syndesis/issues/2312
take advantage of new duration control when specifying amount of delay when polling an S3 bucket
=> feat(s3): use duration control type for delay form field

app/server/endpoint/pom.xml, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/Version.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/VersionEndpoint.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/VersionITCase.java
This adds a endpoint that in addition to the existing plain text version
information adds a more detailed version information. The response JSON
might contain the following:
- `version` - same as the existing plain text version
- `commit-id` - git commit id of the version
- `branch` - git branch being built
- `build-time` - time of the build
- `build-id` - identifier of the build
Only the `version` property is guaranteed to be present, other
properties depend on how the build performed.
=> feat(server): detailed version endpoint

app/ui/src/app/support/support.component.html, app/ui/src/app/support/support.component.ts
This uses the plain text endpoint at `/api/v1/version` to display the
correct version on the support page.
Fixes #2384
=> feat(ui): display correct version on support page

app/common/util/src/main/java/io/syndesis/common/util/Json.java, app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/BaseDataShapeGenerator.java, app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/BaseSwaggerConnectorGenerator.java, app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/DataShapeGenerator.java, app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/SwaggerModelInfo.java, app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/SwaggerUnifiedShapeConnectorGenerator.java, app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/SyndesisSwaggerValidationRules.java, app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/UnifiedDataShapeGenerator.java, app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/UnifiedJsonDataShapeGenerator.java, app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/UnifiedXmlDataShapeGenerator.java, app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/util/DummyStreamHandler.java, app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/util/JsonSchemaHelper.java, app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/util/SwaggerHelper.java, app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/BaseSwaggerConnectorGeneratorTest.java, app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/SwaggerUnifiedShapeGeneratorExampleTests.java, app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/SyndesisSwaggerValidationRulesTest.java, app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/UnifiedXmlDataShapeGeneratorRequestShapeTest.java, app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/UnifiedXmlDataShapeGeneratorShapeValidityTest.java, app/server/connector-generator/src/test/resources/swagger/expected-pet-schema.json, app/server/connector-generator/src/test/resources/swagger/kie-server.swagger.json, app/server/connector-generator/src/test/resources/swagger/kie-server.unified_connector.json, app/server/connector-generator/src/test/resources/swagger/petstore.unified_connector.json, app/server/connector-generator/src/test/resources/swagger/petstore_xml.unified_connector.json, app/server/connector-generator/src/test/resources/swagger/reverb.unified_connector.json, app/server/connector-generator/src/test/resources/swagger/todo.unified_connector.json
This optimizes the way API connectors based on Swagger specifications are generated by greatly reducing the number of serialization/deserializations performed to or from JSON.
Also fixes a number of smaller edge cases, and cleans up the implementation to remove unnecessary JSON schema properties, such as duplicate schema declarations on merged input data shapes.
Also allows for certain, not entirely valid, Swagger specifications might define operation ids in a non-unique way. We can tolerate that and make them unique by adding a suffix on the operation id equal to the non-unique occurrence.
Fixes #2319
=> chore(server): support diverse swagger specifications

app/ui/src/app/support/support.component.html, app/ui/src/app/support/support.component.ts, app/ui/src/assets/dictionary/en-GB.json
fixes #2384 though @zregvart did all the real work :-)
Example (fake build/commit ID):
build/commit IDs only appear if they're in the response
=> chore: rework version formatting on support page

app/pom.xml, tools/bin/commands/release
This does not slow down the build considerably and is required
for getting git information into the version API endpoint.
Also, adapt the 'daily' release mode to run in flash, without tests,
to avoid sporadic test failures.
The rational is that its better to have daily releases which might have
some issues than having no such release because of test failures
(which might or might not be due to real errors)
=> chore(build): Allow git plugin in "flash" profile

app/server/runtime/src/main/java/io/syndesis/server/runtime/SecurityConfiguration.java, app/server/runtime/src/main/java/io/syndesis/server/runtime/SyndesisCsrfRepository.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/BaseITCase.java, app/ui/src/app/api/providers/api-xsrf-interceptor.service.ts, app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.ts, app/ui/src/app/integration/import-export/import/integration-import.component.ts, app/ui/src/app/integration/list-page/list-page.component.ts, app/ui/src/environments/environment.prod.ts, app/ui/src/environments/environment.ts
Adding xsrf protection using spring security.
I changed the ui part to use the token on each request (also `GET` and `TRACE`) and to use the `awesome` token value by default unless the server asks to use a different one (the server will not, for now).
Multipart requests were ok, the problem was in the angular FileUploader that required a ad hoc config (fixed it).
Spring-security validates the token header twice under the hood, so I used a shared constant value for ui and server.
This can be merged. I put the wip flag until we decide if we want to protect Atlasmap endpoints too (cc: @igarashitm).
=> Add Xsrf protection in syndesis backend

app/server/credential/src/main/java/io/syndesis/server/credential/CredentialConfiguration.java, app/server/credential/src/main/java/io/syndesis/server/credential/Credentials.java, app/server/credential/src/test/java/io/syndesis/server/credential/CredentialsTest.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/credential/CredentialITCase.java
This encrypts secret connection properties that are defined when the
OAuth flow completes by invoking the
`EncryptionComponent::encryptPropertyValues` when applying client side
state to the newly created Connection.
Fixes #2441
=> fix(server): encrypt connection properties from oauth flow

app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DatabaseMetaDataHelper.java, app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DatabaseProduct.java, app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlMetadataAdapterTest.java, app/connector/sql/src/test/resources/test-options.properties
Fixes https://github.com/syndesisio/syndesis/issues/2482. For MySQL a pattern of "%" should be used instead of null.
=> fix: On MySQL - Table name pattern can not be NULL or empty #2482

app/server/update-controller/src/main/java/io/syndesis/server/update/controller/ResourceUpdateAutoConfiguration.java, install/generator/04-syndesis-server.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml
This declares the `Accept: text/plain` for the liveness probe and with that removes the messages in the log as now the handler that produces `text/plain` for `/api/v1/version` is narrowly selected.
Fixes #2423
=> chore(install): declare accept header for liveness probe

tools/upgrade/steps/prep_40_process_template, tools/upgrade/steps/upgrade_40_update_resources
Supposed to fix #2462
As discussed in #2475, we make an update with 0 replicas. This works for me
locally, so hopefully also in general.
=> fix(upgrade): Scale replicas to 0 before updating DeploymentConfigs

app/connector/mqtt/src/main/resources/META-INF/syndesis/connector/mqtt.json
This set the input/output data shape kind to `any` for the mqtt
connector, previously it was erroneously set to `kind: 'java'` and
`type: 'java.lang.String'`.
Fixes #2476
=> fix(connector): proper data shape kind for mqtt

app/pom.xml
This upgrades swagger-core from 1.5.9-SNAPSHOT to 1.5.9 released version.
Fixes #2477
=> chore(server): upgrade swagger-core

app/ui/src/app/customizations/api-connector/api-connector.service.ts
When the user provides a URL to the Swagger specification and tries to
upload the icon the logic would not upload the icon. This refactors the
logic that decides what multipart types to upload to make it easier to
understand and corrects that issue.
Fixes #2287
=> fix(ui): api connector icon upload when providing url for swagger

app/ui/src/app/core/providers/form-factory-provider.service.ts
Adds condition so that the property that is both hidden and secret is
not displayed.
Fixes #2494
=> fix(ui): don't show properties that are hidden and secret

app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java
When generating OpenShift Secret we used the latest version of the
Integration. That meant that if we modified the order or added steps the
Secret would be misaligned with the image build used. For instance if we
removed a logging step (at position 2) between the two existing steps:
start at positon 1 and stop at position 3 steps, the id of the last step
would changed from 3 to 2, but the generated `application.properties` in
the Secret would still have the key with `-3`.
This prevented deployments of previous versions or deployments of newer
versions.
Fixes #2432
=> fix(server): use proper integration version

app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/ConnectionUpdateHandler.java
For Salesforce Connector Connections we support multiple ways of
configuring the properties, when the connection is configured without
OAuth settings set, i.e. manually, the username and password fields are
required; with OAuth settings, i.e. using OAuth flow, username and
password are not set and not required.
Given that the warning SYNDESIS006 is issued if a required property is
not configured, a warning will be shown on Salesforce connections
created from OAuth flow. We can distinguish those by having their
`derived` flag set and filter out this warning.
Fixes #2532
=> fix(server): don't warn about missing properties on derived connections

doc/sdh/cli/cmd_release.adoc, install/generator/04-syndesis-server.yml.mustache, install/generator/run.sh, install/generator/syndesis-template.go, tools/bin/commands/release, tools/bin/install-syndesis
These will be hosted in fuse-ignite-install repo for OSO and OCP
installations.
* Replaced --productize for the template generator with --oso and --ocp for the different environments.
* Added no limits wrt integrations for the OCP case
=> chore(install): Moved out generation of productised templates

app/ui/src/app/connections/create-page/create-page.component.ts, app/ui/src/app/store/connector/connector.service.ts
When landing from the OAuth callback we would present the
_Name Connection_ form and the wizard would highlight
_Configure Connection_ step.
This replaces the `returnUrl` and massages the logic into displaying the
proper step for the form.
Fixes #2543
=> fix(ui): highlight step 3 in new connection wizard

.gitignore, app/common/model/src/main/java/io/syndesis/common/model/bulletin/LeveledMessage.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java, app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java, app/ui/src/app/core/providers/status-code-decoder-provider.service.ts, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/integration_detail/integration-description.component.html, app/ui/src/app/platform/types/status-code-decoder/status-code-decoder.service.ts, app/ui/src/assets/dictionary/en-GB.json
This PR is related to #2524 and:
- fixes the NPE thrown by syndesis-server when an integration with deleted connector is invoked
- introduces additional checks on integration level warn about inconsistent state of extensions or deleted connectors, @gashcrumb related codes are:
```java
SYNDESIS009, // Connection has been deleted
SYNDESIS010, // Multiple extension installed
```
The integration page now shows a warning on the impacted connection:
Going to integration summary, the following is shown:
There are some remaining issues I cannot fix on backend side
1. when an integration with deleted connections is edited, UI invokes the following endpoint
/api/v1/connections/undefined/actions/${actionId}
Here _undefined_ if obviously wrong and happens because the actualized connection does not …
=> Deleting a connection which is used by an integration leads to inconsistent state (backend)

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java, app/ui/src/app/integration/integration-actions-provider.service.ts
almost fixes #2540
The UI uses a PATCH request to update the `steps` attribute, however it also tries to update `isDraft` as well but that doesn't seem to be persisted.  So this halfway fixes the issue.
=> fix: correct the values being passed to patch and fix how it's being called

install/generator/01-header.yml.mustache, install/generator/04-syndesis-server.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml
wdyt? If it's not against some of the conventions, I think this would be an easier way to specify the maximum number of integrations. 
I just didn't like that much the server config-map update, as described in [the documentation.](https://access.qa.redhat.com/documentation/en-us/red_hat_fuse/7.0/html-single/integrating_applications_with_ignite/#installing-on-ocp)
=> feat: add MAX_INTEGRATIONS_PER_USER parameter to syndesis-server configs

app/ui/src/app/connections/common/configuration/configuration.service.ts, app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.ts, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts, app/ui/src/app/platform/types/form-factory/form-factory.service.ts, app/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts
fixes #2510 
Adds support for a `trim` field in config property definitions to control if a string value should be trimmed or not, also ensures that all the spots where the form factory is used sanitizes the data coming back from the form.
=> fix: trim strings by default except for secret fields

app/ui/src/app/app.component.html, app/ui/src/app/support/support.component.html, app/ui/src/assets/dictionary/en-GB.json
=> fix: update 'contact us' link and update link on support page to use dictionary

app/ui/src/app/api/providers/api-http-provider.service.ts, app/ui/src/app/support/support.component.ts
This removes setting the default `Accept` header to `application/json`,
thus the `Accept` header by default will be
`Accept: application/json, text/plain, */*`.
Also for `/api/v1/version` endpoint the `Accept` header is explicitly
set to `Accept: application/json`.
Fixes #2604
=> fix(ui): send accept header with application/json for /version endpoint

app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/PropertyGenerators.java, app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/PropertyGeneratorsTest.java
This adds missing support for hosts URIs that contain port numbers.
Fixes #2680
=> fix(server): support ports in swagger host

install/generator/01-header.yml.mustache, install/generator/02-syndesis-image-streams.yml.mustache, install/generator/02-syndesis-secrets.yml.mustache, install/generator/03-syndesis-ui.yml.mustache, install/generator/04-amq-example.yml.mustache, install/generator/04-syndesis-db.yml.mustache, install/generator/04-syndesis-meta.yml.mustache, install/generator/04-syndesis-oauth-proxy.yml.mustache, install/generator/04-syndesis-server.yml.mustache, install/generator/04-todo-example.yml.mustache, install/generator/05-syndesis-security.yml.mustache, install/generator/06-syndesis-prometheus.yml.mustache, install/generator/07-syndesis-upgrade.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml
This change reverts the change introduced in https://github.com/syndesisio/syndesis/commit/7027e646ac75af9548b34c557b0ade3d63f81fa6 where other labels has been moved to a 'syndesis.io' prefix.
The change for 'app' was by accident.
=> chore: Moved label 'syndesis.io/app' back to 'app' as it has a meaning for OpenShift

app/ui/src/app/integration/import-export/import/integration-import.component.html, app/ui/src/app/integration/import-export/import/integration-import.component.ts, app/ui/src/assets/dictionary/en-GB.json
Re-add toast notifications to import/export. Some improvements will be made for failed imports in an upcoming PR.
- i18n support (still need to remove text from component as well, done for template)
- Non-persistent notifications on success and fail
fix #1956
=> Toast notifications import/export

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandlerTest.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/ConnectorsITCase.java, app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html
When a Connector is deleted it makes little sense in having Connections
of that Connector remaining. This removes all Connections of a Connector
when it's deleted.
Fixes #2586
=> Deleting API connector should delete it's connections

doc/sdh/development/labels.adoc
It's just a little thing I noticed reading the handbook.
=> Fix typo in labels.adoc

.circleci/config.yml
This change runs the system tests only for the branch `system-test` this
will help us fix the system tests but maintain the OK status on the
`master` branch.
Fixes #2746
=> chore(build): disable system tests

tools/bin/commands/release
Sets the version of the documentation to be the same as in the
application also builds the documentation as a part of the release.
I made the change blindly, so please review if I missed something.
Fixes #2558
=> chore(release): set version & build documentation

tools/bin/commands/dev
This adds `--cleanse` option to `syndesis dev` subcommand that deletes
pods that are in 'Completed' state.
=> chore(tools): add syndesis dev --cleanse tool

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthApp.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthAppHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthConnectorFilter.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthConnectorFilterTest.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/BaseITCase.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/SetupITCase.java, app/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts, app/ui/src/app/settings/oauth-apps/oauth-app-modal.component.ts, app/ui/src/app/store/entity/entity.store.ts
This allows editing of scopes, token and authorization endpoints.
Also adds a check to see if the resolved value from `service::delete` is
`null` and uses the given `entity` instead for the resolved value.
Fixes #2767, #2718
=> chore: editing of scopes, token and authorization endpoints

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/ActivityTrackingInterceptStrategy.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/IntegrationLoggingListener.java, app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java, app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/PodLogMonitor.java
I just discovered that one of my log parsing assumptions was wrong. I assumed that all log entries from the API server started with a fix length time prefix that looked like:
2018-01-12T21:22:02.068338027Z { ..... }
Turns out that that time prefix is actually variable length.
=> fixes: #2095 missing log entries.

app/pom.xml, doc/tools/pom.xml, doc/tools/syndesis-documentation-maven-plugin/pom.xml, doc/tools/syndesis-documentation-maven-plugin/src/main/java/io/syndesis/maven/TooltipExtractorMojo.java
Switches the parent of `doc/tools` - documentation module to use
`syndesis-parent` and adds it as a module to the `syndesis-parent`.
This way the documentation tooling is using the same base-pom version
and Maven configuration as the rest of Syndesis Maven modules.
Fixes #297
=> chore(build): use base-pom for documentation

app/pom.xml, doc/connecting/topics/shared, doc/pom.xml, doc/tools/syndesis-documentation-maven-plugin/pom.xml, doc/tools/syndesis-documentation-maven-plugin/src/main/java/io/syndesis/maven/TooltipExtractorMojo.java
This changes the parent of the documentation POM to the Syndesis parent
and the parent of the documentation maven plugin to the documentation
parent in an effort to help the release build find the documentation
plugin and have all POMs inherit from Syndesis parent.
Also fixes dependency/codestyle issues in the Maven documentation plugin
and makes one of the links relative to the rest of the documentation.
=> fix(build): use proper parent for documentation

app/pom.xml, app/server/endpoint/pom.xml, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/atlas/SyndesisAtlasService.java, app/ui/package.json, app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts, app/ui/src/config.json.example, app/ui/src/config.json.minishift, app/ui/src/config.json.staging, app/ui/yarn.lock
This update contains:
* Gap control for separate/combine index (atlasmap/atlasmap#449)
* A prototype of data preview mode for single mapping (atlasmap/atlasmap#451)
=> chore: Update to AtlasMap 1.35.4

app/ui/package.json, app/ui/src/app/app.component.spec.ts, app/ui/src/app/app.module.ts, app/ui/src/app/connections/create-page/current-connection.ts, app/ui/src/app/connections/list-page/list-page.component.spec.ts, app/ui/src/app/connections/list/list.component.spec.ts, app/ui/src/app/dashboard/dashboard.component.spec.ts, app/ui/src/app/dashboard/dashboard.module.ts, app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html, app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.ts, app/ui/src/app/integration/list-page/list-page.component.spec.ts, app/ui/src/app/integration/list/list.component.spec.ts, app/ui/src/app/vendor/vendor.module.ts, app/ui/yarn.lock
should hopefully fix #2941 as with patternfly 3.x we pull in an old version of ngx-bootstrap, which causes the runtime issue seen in #2941
=> chore: upgrade to patternfly-ng 4.x (partial)

app/meta/src/main/resources/application.yml
=> Meta pod doesn't start because: Cannot determine embedded database driver class for database type NONE

app/connector/webhook/pom.xml, app/connector/webhook/src/main/java/io/syndesis/connector/webhook/WebhookConnectorCustomizer.java
Fixes #2902 
This PR add initial support for webhooks headers averaging a specific json schema to define the headers that have to be included, the proposed schema template is:
```json
{
"$schema": "http: //json-schema.org/schema#",
"id": "io:syndesis:webhook",
"type": "object",
"properties": {
"parameters": {
"type": "object",
"properties": {
}
},
"body": {
"type": "object",
"properties": {
}
}
}
}
```
The webhook connector wraps the payload only if:
- the data shape is of type `JSON Schema`
- the schema id is `io:syndesis:webhook`
=> Allow to specify http headers for datamapper step in Webhooks

app/ui/pom.xml
This helps avoid any issues when doing local dev and running `syndesis build`, `--force` ensures that any native modules will get rebuilt using the same node version that the maven frontend plugin uses.
=> chore: use --force to ensure node-saas gets rebuilt as needed

app/ui/angular.json, app/ui/docker/nginx-syndesis.conf, app/ui/src/app/core/providers/user-provider.service.ts, app/ui/src/logout.html, install/generator/04-syndesis-oauth-proxy.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml
This adds a `/logout` endpoint backed by nginx and static logout.html
file.
When `/logout` endpoint is requested with the `SYNDESIS_XSRF_TOKEN` set
to `awesome` the response will expire the `_oauth_proxy` cookie. In any
case it will serve the `logout.html`.
The UI when performing the logout will replace the `window.document`
with the response of the `/logout` endpoint and will set the URL to
`/logout`.
This design protects the denial of service if the `/logout` endpoint is
invoked cross origin and allows for the served page to be reloaded
making it deterministic and thus safer.
The `logout.html` embeds the used CSS and just displays a simple _You
have been logged out_ message offering to Login again by linking to `/`.
Fixes #2561
=> chore(ui): logout endpoint

app/ui/src/app/core/providers/integration-support-provider.service.ts, app/ui/src/app/integration/integration_detail/integration-detail.component.html, app/ui/src/app/integration/list/index.ts, app/ui/src/app/integration/list/list.module.ts, app/ui/src/app/integration/list/status-detail.component.ts, app/ui/src/app/integration/list/status.component.ts, app/ui/src/app/platform/types/integration/integration-support.service.ts, app/ui/src/app/platform/types/integration/integration.api.ts, app/ui/src/app/platform/types/integration/integration.models.ts, app/ui/src/app/store/entity/entity.store.ts, app/ui/src/app/store/integration/integration.service.ts, app/ui/src/assets/dictionary/en-GB.json
fixes #2620
I've added a fallback in the detailed status component so that if the detailed status returns null like it is for me currently it'll just show the old spinner + stopping/starting text.  But when it does return the expected response:
=> UI work for fetching the detailed status

install/generator/04-syndesis-server.yml.mustache, install/generator/07-syndesis-upgrade.yml.mustache, install/generator/syndesis-template.go
Fixes #2639
A new flag --early-access has been introduced for the generator so
that the EA Maven repos can be added for the productised builds.
Otherwise, and by default, the 'real' repos are used:
EA-Repos:
02_redhat_ea_repository: https://maven.repository.redhat.com/earlyaccess/all
03_jboss_ea: https://repository.jboss.org/nexus/content/groups/ea
GA Repos:
02_redhat_ea_repository: https://maven.repository.redhat.com/ga/
03_jboss_ea: https://repository.jboss.org/
Please only merge together with https://github.com/syndesisio/fuse-ignite-install/pull/28
=> chore: Remove workarounds used for GA release

app/pom.xml, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/support/SupportUtil.java
At a point we stopped using labels on integration pods, so we need to
use annotations to identify individual integrations. This changes this
behavior only for fetching logs of integration pods.
`kubernetes-model` needed to be updated to include fix for
fabric8io/kubernetes-model/issues/296[1]
Fixes #2386
[1] https://github.com/fabric8io/kubernetes-model/issues/296
=> fix(server): gather integration logs for support

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthApp.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthAppHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/package-info.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthAppTest.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/SetupITCase.java, app/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts, app/ui/src/app/settings/oauth-apps/oauth-apps.models.ts
This changes the model of OAuthApp so it no longer has fixed properties.
Now the model is backed by properties/configuredProperties convention we
use for Connectors/Connections/..., allowing the properties as defined
by the Connector.
The properties used/exposed are determined by tag values, and those are
preexisting tags that are already used within the credentials module and
the Connector definitions.
Fixes #2990
=> chore: OAuth app settings backed by configurati on from the backend

app/ui/src/app/integration/edit-page/edit-page.component.html, app/ui/src/app/integration/edit-page/edit-page.component.scss, app/ui/src/app/integration/edit-page/edit-page.component.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.ts
fix https://github.com/syndesisio/syndesis/issues/2993
Outstanding issues I need code/design help with.
1. To get the "add step/connection" popover to display outside of the scrollable IVP (overflow hidden), I appended the popover to `body`. Then the `mouseover`/`mouseout` events on the "+" icon that would display/hide the popover no longer worked - as you hovered off the icon and into the popover, it would disappear. So I changed the popover to fire on click. I wonder if this is OK as is?
* Another workaround this could be to display the popover below the "+" icon (`placement="bottom"`) when the IVP is collapsed, and to the right (`placement="right"`) when the IVP is expanded. Then the popover wouldn't overflow the IVP.
* Or figure out how to keep the popover open when you hover over …
=> Simplified IVP

app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.ts
relates to #2617 but also the nav should be collapsed anyways like we do for the create connection wizard.
=> chore: collapse nav when entering the client connector wizard

app/ui/src/app/core/providers/i18n-provider.service.ts
=> chore: use both possible key references for config.json substitution

install/generator/04-syndesis-db.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml
This adds a CronJob backed by ConfigMap that contains a shell script to
run periodical database maintenance.
Currently it runs `VACUUM ANALYSE jsondb` and `REINDEX TABLE jsondb` at
04:15 each day.
Fixes #2912
=> chore(db): add scheduled database maintenance

tools/upgrade/Dockerfile, tools/upgrade/migration/preflight.sh, tools/upgrade/steps/upgrade_40_update_resources
@rhuss I've done some changes to fix the upgrade pod issues I've encountered:
- fixed script error
- upgraded `oc` client to 3.9 (requires EPEL repo)
- added rolebinding to "skip" list (until we figure out how to give proper permissions to the service account)
=> Fix upgrade pod issues for operator

app/ui/src/app/app.component.html, app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.html, app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.scss, app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html, app/ui/src/app/settings/oauth-apps/oauth-apps.component.html
This PR cleans up the lack of accessible names and inconsistent markup used in a couple places within the UI. Small but impactful changes we were hoping to get in before end of sprint.
Should help close https://github.com/syndesisio/syndesis/issues/3075
assign accessible name for main nav toggle
use same size heading as other dashboard cards
use more appropriate markup for showing time
associate register button with client app
accessible name for inline edit integration name control
accessible name for IVP details collapse/expand btn
=> fix(a11y-cleanup): improve router navigation experience

app/ui/src/app/integration/edit-page/flow-page.service.ts
* When the publish operation fails, the publish button is left disabled and
the spinner is displayed. By setting publishInProgress to false in the
event of an error will reset both of these and allow the name to be
re-edited and the publish be re-attempted with the new name.
=> Issue #2693: resuming after publish of integration violates same name

install/generator/04-syndesis-db.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml
Removes the mount of `syndesis-db-data` volume, it's not required and
prevents the creation of the pod as the `syndesis-db` maintains a lock
on `syndesis-db-data` volume.
=> fix: don't try to mount syndesis-db-data volume

app/ui/scripts/minishift-restore.sh, app/ui/scripts/minishift-setup.sh
* Can use the same scripts and configuration as running yarn with
minishift. Couple of small modifications to the pertinent scripts.
* minishift-setup.sh
* Provides an openshift-implementation independent mechanism to return the
openshift console url
* minishift-restore.sh
* Fixes the restoration of the syndesis-ui service and endpoint including
extra labels and ensuring both are added back separately.
* Effectively reverses/undoes the effect of minishift-setup.sh
=> Running yarn with Openshift using oc cluster up

app/server/controller/src/main/java/io/syndesis/server/controller/integration/IntegrationController.java, app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/ConnectionUpdateHandler.java, app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java
Copy paste from the commits:
**fix(server): don't perform updates without changes**
When we compare periodically state of objects in controllers we run for integration deployments, integrations, connections and connectors we should not generate updates of the JsonDB or emit changes via WebSockets if the state did not change.
This checks if the previous state is equal to the current state and only performs the database update end emits the WebSocket event if the change has occurred. Thusly it increases our performance by reducing the number of refreshes in the UI and decreasing the database load for updates and fetches initiated by the emitted change to the UI.
**fix(ui): consider refreshing the store only for events of the stores kind**
Events that are not related to the store should not …
=> Unecessary requests to `/api/v1/integrations`

app/ui/src/app/store/action/action.service.ts, app/ui/src/app/store/connection/connection.service.ts, app/ui/src/app/store/connector/connector.service.ts, app/ui/src/app/store/entity/rest.service.ts, app/ui/src/app/store/extension/extension.service.ts, app/ui/src/app/store/integration/integration.service.ts, app/ui/src/app/store/oauthApp/oauth-app.service.ts
fixes #2925
This just bumps up the item limit to 50 by default on the UI side, this can be controlled in `config.json` by adding a `perPage` attribute to the root object with a numeric value.
@rhuss FYI
Should probably create an epic for proper pagination as a future enhancement for all pages, what's there now I don't think will be suitable long term.
=> fix: fetch more things from the backend, add a config parameter

app/pom.xml
I was getting the following errors:
[INFO] --- duplicate-finder-maven-plugin:1.2.1:check (default) @ connector-activemq ---
[INFO] Checking compile classpath
[INFO] Checking runtime classpath
[INFO] Checking test classpath
[WARNING] Found duplicate and different resources in [io.syndesis.connector:connector-support-util:1.4-SNAPSHOT, io.syndesis.connector:connector-support-verifier:1.4-SNAPSHOT]:
[WARNING]   git.properties
[WARNING] Found duplicate classes/resources in compile classpath.
[WARNING] Found duplicate and different resources in [io.syndesis.connector:connector-support-test:1.4-SNAPSHOT, io.syndesis.connector:connector-support-util:1.4-SNAPSHOT, io.syndesis.connector:connector-support-verifier:1.4-SNAPSHOT]:
[WARNING]   git.properties
[WARNING] Found duplicate classes/resources …
=> fix: Found duplicate and different resources: git.properties

app/connector/timer/src/main/resources/META-INF/syndesis/connector/timer.json
Timer connector is used at the start of the integration (_pattern=From_)
at that point the only body possible as it is a new exchange is `null`,
so defining a shape of `null` body doesn't make sense and leads to
errors.
Fixes #3034
=> fix(connector): set Timer's output shape to none

app/connector/salesforce/src/main/java/io/syndesis/connector/salesforce/customizer/DataShapeCustomizer.java, app/connector/salesforce/src/test/java/io/syndesis/connector/salesforce/customizer/DataShapeCustomizerTest.java
The Salesforce connector was trying to unmarshall the outgoing exchange
message where it should have used the incoming message. This caused
the output of the Salesforce connector for create/create-or-update and
notifications (starting) actions to be `null` instead of the expected
type populated with data from the Salesforce response.
Fixes #2853
=> fix(connector): Salesforce output unmarshalling

tools/bin/commands/tests/test-oc-version.sh, tools/bin/commands/util/openshift_funcs
* Since 3.9.0 version of oc is required, check the version during the setup
of oc stage of running syndesis commands.
=> Enforce the minimum version of oc

app/integration/bom/pom.xml
We need to update AtlasMap to 1.35.5 in Integration BOM as well,
otherwise our integrations run with older version.
cc @igarashitm
=> chore: Update to AtlasMap 1.35.5 in Integration BOM

app/connector/odata/create-entity/pom.xml, app/connector/sql/src/main/java/io/syndesis/connector/sql/common/JSONBeanUtil.java, app/connector/sql/src/test/java/io/syndesis/connector/sql/common/JSONBeanUtilTest.java
* JSONBeanUtil
* Checks the json parameter and returns if empty
* Check the jdbcTypeMap and assigns VARCHAR if null
* JSONBeanUtilTest
* Test to check what happens if parameters are null
=> Issue #2706 - sql connector should not parse body when no parameters

install/generator/06-syndesis-prometheus.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml
=> fix: add initialDelaySeconds to readyness/liveness checks for prometheus

app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.component.html, app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.component.ts, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
This PR fixes issues with the basic filter form, where the value for the predicate field was not correctly reflected in the UI, and the done button was incorrectly available on initial display of the form, before users entered valid data.
Should fix https://github.com/syndesisio/syndesis/issues/3073
ensure predicate value is reflected in the ui
ensure done button is disabled until form is in a valid state
=> fix(basic-filter-form): update form bindings for default state

app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.component.html
This PR restores autocomplete functionality that was lost as part of recent upgrade work.
Should help https://github.com/syndesisio/syndesis/issues/3087
utilize list attribute and datalist element to fulfill autocomplete functions
=> fix(basic-filter-form): add back autocomplete for property name field

app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
I fixed one typo. And I added a few articles to make the text easier to understand.
=> bug fix: Typo in slack json file fixed

app/connector/telegram/pom.xml, app/connector/telegram/src/main/java/io/syndesis/connector/telegram/TelegramSendMessageCustomizer.java, app/connector/telegram/src/main/resources/META-INF/syndesis/connector/telegram.json
Fix #3168.
I've removed the `chatId` property in the receive action because that was a producer-only option and it's not supported consumer side (also by Telegram API).
On the producer side, I've set the following priorities:
- Chat ID in the outgoing message field has highest priority
- Chat ID set in the action configuration comes next
- If nothing else is set, the TelegramChatId header is used (when the integration starts from telegram, replies are sent to the same chat)
=> Fix #3168: adjust priority and remove chatId from telegram consumer

app/connector/irc/src/main/resources/META-INF/syndesis/connector/irc.json, app/ui/src/app/common/card-tech-preview.component.scss, app/ui/src/app/common/card-tech-preview.component.ts, app/ui/src/app/common/common.module.ts, app/ui/src/app/connections/list/list.component.html, app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.html, app/ui/src/app/platform/types/connection/connection.models.ts, app/ui/src/assets/dictionary/en-GB.json
Adds a new tag `tech-preview` that can be added to connectors that are provided for early access technology preview.
First such Connector is the IRC Connector.
Visually when Connection is displayed the top of the Connection card will contain `Technology preview` text, which is also displayed during connection creation.
Fixes #3201
=> feat: mark Connectors provided as tech preview

app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-auth/api-connector-auth.component.html, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-auth/api-connector-auth.component.ts
This presets the default value for `authenticationType` so that it's `input[type=radio]` is `checked` before the dependent child is checked by Angular change management. So that `ExpressionChangedAfterItHasBeenCheckedError` is not raised on initial
render.
Fixes #3042
=> fix(ui): mutation order in API Client connector wizard OAuth settings

tools/bin/commands/release
=> fix(release): Filter out non-three digit version when calculating snapshot name

app/pom.xml
* spring-social-salesforce requires logback-classic as a compile scope
dependency. The server-endpoint module reduces logback-classic to test
scope only
** Results in build error:
[ERROR] Found a problem with test-scoped dependency ...
Scope compile was expected by artifact ...
~~* Since logback-classic is expected by spring-social-salesforce it is
probably better to leave it included rather than have the library
complaining at runtime.~~
* Excludes logback-classic from spring-social-salesforce as not required
for logging.
=> Fixes error while building with tests

app/ui/docker/nginx-syndesis.conf
This adds HTTP headers to prevent the browser from using cached versions of `/` and `/logout` endpoints and thus bypassing the login or the logout.
Fixes #3016
=> fix(ui): explicitly forbid caching / and /logout

tools/bin/commands/build, tools/bin/commands/util/operator_funcs
This is performed via rsync the source to minishift, run the docker build there, and rsyncing back the generated binary.
Fixes #3260.
=> feature(build): Add support for building the operator on the Minishift docker daemon.

install/operator/Dockerfile, install/operator/cmd/syndesis-operator/main.go
If we try to mount `syndesis-template.yml` via volume it needs not reside in `/`, so this changes the path to `/conf`.
=> refactor(operator): load syndesis-template.yml from /conf

app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.ts
If changes made in the editor, the spec name and description are updated in the request so that the last page of wizard shows the correct API name and description if they were changed.
=> Last Page Of ApiCurio Editor Wizard Does Not Have Updated Title and Description

app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.ts, app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.html, app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.ts
Fixes #3174 
~Maybe it would be better to disable the Review/edit button instead of hiding it, showing the reason why it has been disabled.~ Done this, the reason for the disabled state is shown in a tooltip when hovering the button.
But I think it would be even better if we could change the backend to return the spec after the validation.
=> Hide the Review/edit button if the provided URL to the spec file is unfetchable

tools/bin/commands/util/openshift_funcs
Now when we build with `--local` operator uses the template it was built with and it is contained in the image of the operator.
This introduces a `syndesis-template` ConfigMap that contains the content of the local `syndesis.yml` OpenShift template. The `syndesis-operator` DeploymentConfig is patched to mount this template from the ConfigMap into the `/conf` directory and to use that template when creating Syndesis resources.
=> refactor(build): when installing with --local use provide the operator with local template

install/generator/04-syndesis-db.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml
It's difficult for us to use the CronJob as the container image used would need to be productized. Seems that as CronJob is a non-OpenShift resource referencing the same PostgreSQL image we use for the database pod -- referencing via lookup image stream from other namespace (in this case openshift) is currently not possible.
With this we loose `FULL ANALYSE` from `VACUUM` and `REINDEX TABLE` for `jsondb` table, the hope is that a more aggressive autovacuum configuration will be good enough.
See https://dba.stackexchange.com/questions/21068/aggressive-autovacuum-on-postgresql
Fixes #3252
=> refactor(db): replace database maintenance CronJob with aggressive autovacuum configuration

app/ui/src/app/connections/create-page/review/review.component.html, app/ui/src/app/connections/create-page/review/review.component.ts
With this OAuth error received via callback will be displayed in the UI.
This basically copies the error display logic from `../configure-fields` page. Not sure why we never added it to this page, the redirectUrl is set to return at this point at the end of the OAuth flow, so we should display any OAuth errors here as well.
Fixes #3294
=> fix(ui): display error handling to OAuth /connections/create/review page

app/common/model/src/main/java/io/syndesis/common/model/connection/ConnectorSummary.java, app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/BaseSwaggerConnectorGenerator.java, app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/BaseSwaggerConnectorGeneratorTest.java, app/server/runtime/pom.xml, app/server/runtime/src/test/java/io/syndesis/server/runtime/connector/CustomSwaggerConnectorITCase.java
This adds `configuredProperties` to the `ConnectorSummary` model with the `specification` populated when Custom API connector summary is generated on the `POST /api/v1/connectors/custom/info` endpoint.
cc @kahboom
Ref #3174
=> feat(server): add `specification` `configuredProperty` to the `../info` endpoint

app/ui/src/app/connections/create-page/review/review.component.html, app/ui/src/app/connections/create-page/review/review.component.ts
Displays error message only if the error is reported, not if the
connection supports OAuth.
Fixes #3329
=> fix(ui): error handling with OAuth connections

app/common/model/src/main/java/io/syndesis/common/model/EmptyListResult.java, app/common/model/src/main/java/io/syndesis/common/model/connection/Connection.java, app/common/model/src/main/java/io/syndesis/common/model/connection/ConnectionBase.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandlerTest.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/support/SupportUtilTest.java
* Adds an augment mechanism to the ConnectionHandler which finds the
integrations that utilise the connections and logs their total in a
'uses' property. Works in the same manner as used by the Connectors.
Fixes #3098
=> feat(server): Provides uses element to Connections API

app/ui/package.json, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts, app/ui/src/app/integration/integration_detail/integration-description.component.html, app/ui/src/app/integration/integration_detail/integration-description.component.scss, app/ui/src/app/integration/integration_detail/integration-description.component.ts, app/ui/src/app/integration/integration_detail/integration-metrics.component.ts, app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.ts, app/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts, app/ui/src/app/settings/oauth-apps/oauth-app-modal.component.ts, app/ui/src/app/settings/oauth-apps/oauth-apps.component.html, app/ui/src/app/settings/oauth-apps/oauth-apps.component.ts, app/ui/src/assets/dictionary/en-GB.json, app/ui/yarn.lock
This PR fixes an issue where previously we couldn't use the tooltips feature of copy to clipboard component because there was a namespace conflict over the "tooltip" input property. Now that we've addressed this, and other styling alignments for copy to clipboard, we'd like to pull in the latest and use that instead.
upgrade to latest pfng 4.5.0
use new input properties for copy to clipboard components
remove oncopy notification handlers
remove unused imports
=> fix(copy-component): fix copy to clipboard component to accepts tooltips

app/pom.xml
syndesis-parent currently sets a hibernate.validator.version but does not respect it because there is no dependency-management entry.
=> Add a dependency-management version for hibernate-validator.   

app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.scss, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.ts, app/ui/src/assets/dictionary/en-GB.json
- See issue #2850 
- ApiConnectorSwaggerUploadComponent is now using the same file upload component as in other places in app that allow DND
- Added code in api-connector-create.component.html that does not allow a file to be DND'd in the ApiCurio wizard unless in a drop zone.
- i18n'd files that were touched
@michael-coker please take a look at CSS change to see if what I did is OK
@TovaCohen please take a look at the i18n file for any changes you might want to make
=> Enables drag/drop UI for API connector upload to be similar as rest of app

app/server/dao/src/main/java/io/syndesis/server/dao/manager/DataManager.java, app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java
On startup `io.syndesis.server.runtime.Migrations::run` is invoking `DataManager::resetDeploymentData`, we need to make sure that the configuredProperties` of the Connector are not overwriten by the loaded Connector definition.
Fixes #3386
(cherry picked from commit 934f44f9cb1e75cbbbadda493864950ce55572f4)
=> fix(server): don't destroy Connector's configuredProperties on second startup (1.4.x backport)

app/server/dao/src/main/java/io/syndesis/server/dao/manager/DataManager.java, app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java
On startup `io.syndesis.server.runtime.Migrations::run` is invoking `DataManager::resetDeploymentData`, we need to make sure that the `configuredProperties` of the Connector are not overwriten by the loaded Connector definition.
Fixes #3386
=> fix(server): don't destroy Connector's configuredProperties on second startup

app/common/util/src/main/java/io/syndesis/common/util/KeyGenerator.java, app/common/util/src/test/java/io/syndesis/common/util/KeyGeneratorTest.java, app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java
We were missing descending ordering of the `path` column. The `path` column contains the key generated when the activity is persisted, the key is chronologically ordered -- so newer keys are lexically greater than older keys. That means we should have ordered in descending order (`ORDER BY path DESC`) instead of the default, which is ascending.
Fixes #3396
(cherry picked from commit 1bb91ef3963a42d1c3fac68df4b3708836d23d5b)
=> fix(server): when discarding activity logs leave the newest entries (1.4.x backport)

app/common/util/src/main/java/io/syndesis/common/util/KeyGenerator.java, app/common/util/src/test/java/io/syndesis/common/util/KeyGeneratorTest.java, app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java
We were missing descending ordering of the `path` column. The `path` column contains the key generated when the activity is persisted, the key is chronologically ordered -- so newer keys are lexically greater than older keys. That means we should have ordered in descending order (`ORDER BY path DESC`) instead of the default, which is ascending.
Fixes #3396
=> fix(server): when discarding activity logs leave the newest entries

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/capture/OutMessageCaptureProcessor.java
When a copy of the Camel message is created some implementations of `Message` don't copy over the `Exchange`; without `Exchange` set on the message type conversion can't work.
This sets the `Exchange` from the original message on the copy so that type conversion is possible.
Fixes #3382
=> fix(connector): set exchange if missing

app/connector/webhook/pom.xml, app/connector/webhook/src/main/java/io/syndesis/connector/webhook/WebhookConnectorCustomizer.java, app/connector/webhook/src/main/java/io/syndesis/connector/webhook/WrapperProcessor.java, app/connector/webhook/src/test/java/io/syndesis/connector/webhook/WebhookConnectorCustomizerTest.java, app/connector/webhook/src/test/java/io/syndesis/connector/webhook/WrapperProcessorTest.java
The webhook connector mandated that the JSON schema specifies the `body` and that the HTTP request contains a non-empty body. This does not hold true for HTTP GET requests.
This changes the JSON schema `body` property to optional and skips over empty body of HTTP requests.
Fixes #3389
=> fix(connector): allow for schema/payloads with only parameters

app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html
- the Save button tooltip in the ApiCurio editor wizard page now displays much nicer
- the file chooser dialog in the upload API now only allows *.json files to be selected
- See #3411 and #3412
=> Address problems identified in Issues 3411 and 3412

doc/connecting/topics/adding_db_connection_finish_middle.adoc
In the 7.0 release, adding a database connection as a middle connection had a limitation that you could SELECT only one record. With 7.1, this limitation is removed. 
This doc update updates the content accordingly.
=> user doc: remove limitation of one record on SQL SELECT in a middle connection

install/generator/07-syndesis-upgrade.yml.mustache, install/generator/syndesis-template.go, install/operator/cmd/syndesis-operator/main.go, install/operator/pkg/syndesis/action/upgrade.go, install/operator/pkg/syndesis/configuration/configuration.go, install/operator/pkg/syndesis/template/upgrade.go, install/syndesis-dev.yml, install/syndesis.yml
Now the operator can be called with a `-registry <registry>` argument for using that registry when instantiation the upgrade pod
A productised Dockerfile should use this option to point the target registry.
Also, the template generator has an options `--upgrade-tag` to directly specify the upgrade tag.
Fixes #3440
=> feature(upgrade): Adapte templates and operator for referencing a registry

doc/integrating_applications/topics/about_api_connectors.adoc, doc/integrating_applications/topics/creating_api_connectors.adoc, doc/integrating_applications/topics/guidelines_for_openapi_specifications.adoc, doc/integrating_applications/topics/updating_api_connectors.adoc
SME review done.
I am merging this so that I can bring it downstream and get the content into the 7.1 staging site for doc. We can still update it based on QE feedback. But need to move this along.
=> user doc: Adds doc about using Apicurio to edit OpenAPI spec.

app/common/model/src/main/java/io/syndesis/common/model/action/Action.java, app/common/model/src/main/java/io/syndesis/common/model/action/ConnectorAction.java, app/common/model/src/main/java/io/syndesis/common/model/action/ConnectorDescriptor.java, app/common/model/src/main/java/io/syndesis/common/model/action/StepAction.java, app/common/model/src/main/java/io/syndesis/common/model/action/StepDescriptor.java, app/common/model/src/main/java/io/syndesis/common/model/bulletin/LeveledMessage.java, app/common/model/src/main/java/io/syndesis/common/model/connection/Connection.java, app/common/model/src/main/java/io/syndesis/common/model/connection/ConnectionBase.java, app/common/model/src/main/java/io/syndesis/common/model/connection/Connector.java, app/common/model/src/main/java/io/syndesis/common/model/extension/Extension.java, app/common/model/src/main/java/io/syndesis/common/model/integration/Integration.java, app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationBase.java, app/common/model/src/main/java/io/syndesis/common/model/integration/Step.java, app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java, app/server/update-controller/src/test/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandlerTest.java, app/ui/src/assets/dictionary/en-GB.json
When a connection is modified, checks are performed comparing the new
connection against the cached versions inside any draft integrations and
deployed integrations. If an integration is found to not be equivalent,
ie. its metadata is out-of-date, then a message is logged accordingly.
* app/common/model...
* Adds default equivalence methods to model interfaces that test only
selected properties of instances. Thus, weaker than equality but does
not produce irritating false-positives.
* app/common/model.../ConnectionBase
* app/common/model.../Connector
* app/common/model.../Extension
* Adds the Version.Auxiliary annotation to certain methods. This stops
them from being added, by Immutables library, to hashcode and equals
methods. The properties behind these methods are only populated on …
=> fix(server): Notifies of stale integration after connection update

app/integration/bom/pom.xml, app/pom.xml, app/ui/package.json, app/ui/src/config.json.example, app/ui/src/config.json.minishift, app/ui/src/config.json.staging, app/ui/yarn.lock
Contains:
* Data Preview with final design (atlasmap/atlasmap#451)
* Support receiving FieldActions metadata from outside (atlasmap/atlasmap#483)
* Create GenerateFieldActionsMojo (atlasmap/atlasmap#482)
* bug fixes
* atlasmap/atlasmap#544
* atlasmap/atlasmap#495
* atlasmap/atlasmap#375
* atlasmap/atlasmap#515
* atlasmap/atlasmap#521
* atlasmap/atlasmap#491
=> chore: Update to AtlasMap 1.36.0

install/operator/deploy/syndesis-operator.yml
Fix #3515.
Sync dev master branch (only, no need to sync 1.4 as the file is not used directly) with changes in fuse-online-install: https://github.com/syndesisio/fuse-online-install/commit/37e9d548ac56ee37cfbb876d136652f0b533e9b0
=> Fix #3515: do not override command from operator image

doc/tutorials/topics/amq2api_choose_start.adoc, doc/tutorials/topics/amq2api_intro.adoc, doc/tutorials/topics/amq2api_start_the_broker.adoc, doc/tutorials/topics/comparison_of_sample_integrations.adoc, doc/tutorials/topics/sf2db_prereqs.adoc, doc/tutorials/topics/t2sf_prereqs.adoc
Added a prereq to each tutorial that you must have logged in to Syndesis.
Make the tutorial names links in the comparison.
Updates some headers to clarify content. 
Tried to create one link that would open in a new tab. I don't expect this to work. This link is in the AMQ to REST API tutorial, Start the broker, topic.
=> user doc: Tweaks to tutorials to make them easier to use

app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.ts, app/ui/src/polyfills.ts
Remove the workaround to fetch a remote OpenAPI file and use the spec as returned by the backend instead.
=> fix: remove the workaround to fetch a remote OpenAPI file

install/operator/Dockerfile-with-build, tools/bin/commands/build, tools/bin/commands/util/operator_funcs
Multistage build were ideal for remote Docker daemon like for the Minishift exposed
Docker daemon.
Unfortunately the Docker daemon included in the latest Minishift images is too old and does
not support multi stage build ;-(
Still I keep it for the time when minishift updates the Docker daemon to at least 17.05
This PR also contains a fix for building the operator image when running on Minishift and is relateted to #3516
=> feature(syndesis): Multistage build for operator + fix for minishift docker build

app/common/model/src/main/java/io/syndesis/common/model/integration/Flow.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/APIGenerator.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/IntegrationHandlerTest.java
Fix #3547.
This addresses the issues outlined in #3547.
- *Ensure the original schema is present in the response of the validation endpoint (needed if the user wants to go back and edit the integration)*
**Solution:** The implementation follows what is implemented in API consumer and the OpenAPI spec is already included.
- *Provide a endpoint to upload the schema via URL, to overcome browser restrictions*
**Solution:** like for the API consumer, just upload a URL instead of a openapi spec in the "specification" field of the form and it will be downloaded by the backend (and returned back from the call to /apis/info)
- *Add a field to the Flow object that contains the last column seen in the list of flows when editing a integration (the one reporting the current HTTP return code)* …
=> Various api provider endpoint improvements

app/ui/src/app/core/providers/form-factory-provider.service.ts
Follow on for #3577 enables all the other input types for the regular text input from ng-dynamic-forms.
@oscerd FYI
=> feat: enable all the other input field types from ng-dynamic-forms

install/generator/01-header.yml.mustache, install/generator/04-syndesis-oauth-proxy.yml.mustache, install/operator/pkg/apis/syndesis/v1alpha1/types.go, install/operator/pkg/syndesis/configuration/configuration.go, install/syndesis-dev.yml, install/syndesis.yml
Allow the custom resource to accept a `USER_NAMESPACE` env var. This allows us to specify the user's namespace where the Syndesis service instance is provisioned in and use it for the `subjectAccessReview` to check for the user's authorization.
**Use Case:**
To provide a managed Syndesis installation, we would like to deploy the syndesis operator and deployment configs into a non-user controlled namespace, separate from the user's namespace. The user's namespace will only have the Syndesis service instance with the Syndesis dashboard URL.
At the moment, the `subjectAccessReview` is set to check against the OpenShift namespace where the operator and the deployment configs are deployed in. Due to this, the user who provisioned the Syndesis service will not have access to the Syndesis …
=> add user namespace to use for the subjecAccessReview in oauthproxy

app/ui/package.json, app/ui/src/app/app.component.ts, app/ui/src/app/config.service.ts, app/ui/src/app/connections/create-page/current-connection.ts, app/ui/src/app/connections/create-page/review/review.component.ts, app/ui/src/app/connections/list/list.component.ts, app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.ts, app/ui/src/app/integration/edit-page/action-select/action-select.component.ts, app/ui/src/app/integration/edit-page/connection-select/connection-select.component.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.component.ts, app/ui/src/app/integration/integration-actions-provider.service.ts, app/ui/src/app/logging.ts, app/ui/src/app/store/entity/entity.store.ts, app/ui/yarn.lock
* fixed the way we read the `logLevel` key from the `localStorage`
* `typescript-logging` upgraded to v0.6.2 from v0.4.0
* renamed the deprecated methods with the new names
Closes #3617
=> fix: restore broken console logging functionality

tools/bin/syndesis
When `tools/bin/syndesis` is invoked without arguments the default
`build` command is not invoked but an error is reported:
bin/syndesis: line 17: $1: unbound variable
This is caused by `set -eu` on the preceding line. This moves the
`set -eu` after the check if `$1` is defined.
=> fix: invoking syndesis without arguments

app/ui/docker/nginx-syndesis.conf
This changes the Nginx configuration to introduce two location blocks
one for the `/` (`/index.html`) and one for all other static resources
under `/`. Seems that `always` option is required for our use case in
the `add_header` directive.
The overall logic is that we can't let the browser to cache `/`, if it
does it will immediately show the Syndesis chrome instead of issuing the
request and this will result in bypassing the `oauth_proxy`
authentication check, i.e. not mandating the user to re-login.
I've found the easiest way to test is to test with a separate Firefox
profile (`firefox --P test`) and in that profile set the History
preference to custom and configure _Clear history when Firefox closes_
option.
Fixes #3016
=> fix(ui): logout on firefox

app/pom.xml
Using a version property without a corresponding dependency referencing it has caused alignment problems in the past. If this property is no longer used, can we remove the property entirely?
See https://issues.jboss.org/browse/ENTESB-9440
=> Removed camel-atlasmap.version property

doc/integrating_applications/topics/combine_multiple_source_fields_into_one_target_field.adoc, doc/integrating_applications/topics/separate_one_source_field_into_multiple_target_fields.adoc, doc/tutorials/topics/amq2api_confirm_works.adoc, doc/tutorials/topics/amq2api_create_rest_api_connection.adoc, doc/tutorials/topics/amq2api_create_rest_api_connector.adoc, doc/tutorials/topics/amq2api_start_the_broker.adoc
Update the AMQ to REST API tutorial to simplify one of the steps for confirming that the tutorial works as defined and to correct the steps for starting the AMQ broker. 
This PR also fixes two xrefs that were broken because of a missing character.
=> Fusedoc 2841 amq tutorial

tools/bin/commands/dev
This adds cleanup of additional stale objects to the
`syndesis dev --cleanup` command, in addition to removing stale pod
objects, this also adds:
- removal of stale builds
- removal of stale deployments
- removal of stale images (for this exposing the registry is performed)
=> chore: more leftover bits to cleanup

app/ui/src/app/settings/oauth-apps/oauth-apps.component.ts, app/ui/src/app/store/entity/entity.store.ts, app/ui/src/app/store/oauthApp/oauth-app.store.ts
fixes #3672
Also renames some class variables and forces a re-fetch of oauth clients when visiting the settings page, since updates to this endpoint doesn't appear to trigger change events.
=> fix: ignore hidden required fields on the oauth settings page

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthApp.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthAppTest.java
We should not send `type=hidden` properties to the UI for the OAuth
setup, it makes little sense as the UI will not be able to anything
meaningful with them.
Fixes #3674
=> fix(server): don't consider hidden OAuth properties

app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json, app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthApp.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthAppTest.java
When we made the change in #3674 (PR #3678) not to send hidden properties to the UI -- the UI stopped caring about the values of those properties (it simply wasn't aware of them). So when the OAuth settings were changed by the user the value of the property was set to `null` overriding the previously set `configuredProperty`.
This changes the descriptors of gmail and google-calendar connectors so that the values needed to be set in `configuredProperties` are defined as `defaultValue` of the property and the logic was implemented to set the `defaultValue` to the `configuredProperty` if the recived value from the UI is `null`. Exactly as it functioned when the UI was aware of the hidden properties.
Also we were missing a tag in the tags to consider when setting `configuredProperties` of a …
=> fix(oauth): handle hidden properties defultValue

app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json, app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthApp.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthAppTest.java
With this we can configure in the Connector metadata hidden `configuredProperties` or give `defaultValue`s where appropriate. The change makes the OAuth-tagged `properties` that have `type=hidden` and for which values from the UI are not received (as the UI has no knowledge of them, from #3674 (PR #3678)) take values from `configuredProperties` of the connector or from `defaultValue` of the `property`, whichever is defined first (in that order).
=> refactor: handling of hidden OAuth connector properties

app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.ts, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html, app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.ts, app/ui/src/assets/dictionary/en-GB.json
- See #3578
- removed accepted mime type of json from file chooser as there was no way to add YAML files
- added *.yaml and *.yml files to the DND accepted files
- changed helper text and invalid file message
=> Updated OpenAPI spec upload to also accept YAML files

tools/bin/commands/dev
Removes the quotes around $old_pods so that the list of pods is not
given as a single argument. Fixing the issue when there are more than
one stale pods to remove.
=> fix(tools): fix pod list passing

app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
I updated some display names and help hints for the Slack connector. 
For "username", the correct English spelling is "user name", two words. So even thought internally, it might be one word, we should display it as two words when we can. 
If you think these updates are all good, then you can merge this. Thanks!
=> ui text update: Update Slack connector display names to be consistent with other connectors

app/integration/bom/pom.xml, app/pom.xml, app/ui/package.json, app/ui/yarn.lock
Contains
* import/export mapping/document for standalone (disabled in Syndesis)
* Allow field actions to receive whole collection (atlasmap/atlasmap#338)
* Update to Angular 6.1 (atlasmap/atlasmap#568)
* fixed infinite loop on recursive type in XML schema inspection (atlasmap/atlasmap#573)
* and more bug fixes
Cc: @johnpoth
=> chore: Update to AtlasMap 1.37.0

app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/HttpRequestWrapperProcessor.java, app/connector/support/processor/src/test/java/io/syndesis/connector/support/processor/WrapperProcessorTest.java
This replaces the message on the exchange not only the body, so the type of the message is no longer `HttpMessage` and when copies of the message are attempted the HTTP request stream is not read the second time. At which point the HTTP request stream might be closed.
Fixes #3727
=> fix: UT010029: Stream is closed with WebHook connector

app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/SwaggerConnectorComponent.java
=> fix: Remove `Exchange.HTTP_URI` header before HTTP request in rest-swagger connector

app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationBase.java, app/common/model/src/test/java/io/syndesis/common/model/integration/IntegrationBaseTest.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/customizer/ExposureDeploymentDataCustomizer.java, app/server/controller/src/test/java/io/syndesis/server/controller/integration/online/customizer/ExposureDeploymentDataCustomizerTest.java
With this WebHook integrations will not be exposed via 3scale even if the exposure via 3scale is enabled (see #3504). I.e. WebHook integrations will allways be exposed via OpenShift Route and will not participate in 3scale service discovery.
Fixes #3731
=> refactor: don't expose WebHook integrations via 3scale

app/common/model/src/main/java/io/syndesis/common/model/Kind.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/support/IntegrationSupportHandler.java
Changes the response from `POST /api/v1/integration-support/import` to return the objects that were imported. Imported objects are returned in JSON object with the keys being the plural forms of the object kind, and the values an JSON array of imported objects grouped by kind.
Fixes #3167
=> refactor(api): POST /api/v1/integration-support/import response

app/ui/package.json
Only run the snyk tooling if the OFFLINE_BUILD environment variable hasn't been set. So snyk will still be run in the ci builds, but can be turned off in the prod environment where calls to external sites are prohibited.
Thanks to @zregvart for this solution.
=> ENTESB-9439: Prevent snyk being run in prod environment

app/common/model/src/main/java/io/syndesis/common/model/connection/ConnectionBase.java, app/common/model/src/main/java/io/syndesis/common/model/connection/Connector.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/ExtensionHandler.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandlerTest.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/extension/ExtensionHandlerTest.java
We counted Connections and Extensions of deleted Integrations, this should fix it at a penalty of loading all Integrations when counting Extensions.
ref #2871
=> Fixes usage count for Connections and Extensions

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
fixes #3745.
- Step icon and warning icon no longer share the same hover over attribute. A user must click the warning icon to shop tooltip info.
- Removed div class `syn-nowrap` from step icon tooltip. Text now wraps and does not cause awkward right padding issue in tooltip box.
=> Changes to tooltip functionality on step icons.

app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
fixes #3806.
- multistep step icon lines no longer overlap parent step icon.
**Visual Fix**
=> refactor(IVP): multistep step icon lines no longer overlap

app/ui/src/app/core/providers/integration-support-provider.service.ts
Fixes https://github.com/syndesisio/syndesis/issues/3405
In the PR review I'd like to understand what the difference is between the deploymentVersion and the version. The deploymentVersion is undefined, but the version contains the correct version. Using that instead fixes the issue but I'm unclear why we have two pieces of data that seem to contain the same information. Maybe I'm missing something, or maybe there is larger issue.
@gashcrumb, @seanforyou23 maybe one of you can shed a light on this?
=> [fix] Failed to stop integration #3405

app/common/model/src/main/java/io/syndesis/common/model/validation/TargetWithDomain.java, app/common/model/src/main/java/io/syndesis/common/model/validation/connection/ConnectionWithDomain.java, app/common/model/src/main/java/io/syndesis/common/model/validation/extension/ExtensionWithDomain.java, app/common/model/src/main/java/io/syndesis/common/model/validation/integration/IntegrationWithDomain.java, app/server/dao/src/main/java/io/syndesis/server/dao/validation/extension/NoDuplicateExtensionValidator.java, app/server/dao/src/main/java/io/syndesis/server/dao/validation/integration/NoDuplicateIntegrationValidator.java, app/server/dao/src/test/java/io/syndesis/server/dao/validation/NoDuplicateValidatorTest.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/ExtensionHandler.java, app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java, app/server/update-controller/src/test/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandlerTest.java, install/generator/04-syndesis-server.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml, tools/bin/commands/util/openshift_funcs
* install/...
* tools/...
* Limit the cpu requirements of the syndesis server to 3/4 of a single
CPU, stopping it taking advantage of 3-4 CPUs otherwise.
* app/...
* Reduce the number of calls to the DataManager by fetching all the items
from it once at the beginning of each compute then pass these collections
into the requisite method calls using the TargetWithVector class.
* TargetWithVector pairs up the target with its search vector to allow
for Validator classes to not have to use the DataManager.
fixes #3717
=> fix(performance) Reduce CPU usage of syndesis server

app/connector/rest-swagger/src/main/resources/camel-connector.json
Fix #3800 by choosing the rest implementation explicitly in API consumer.
Thanks @zregvart for the hint. The library is transitively imported.
=> Fix #3800: choose a specific rest implementation

app/ui/src/app/integration/integration_detail/integration-description.component.html, app/ui/src/app/integration/list/list.component.html, app/ui/src/app/platform/types/integration/integration.models.ts, app/ui/src/app/store/integration/integration.service.ts
Fixes #3601
Only 1 of 12 operations is implemented
Only 1 of 12 operations is implemented
All operations are visible in the Operations page
=> fix: show the number of integrate flows, not the total count

app/ui/src/app/integration/edit-page/step-configure/templater/mustache-mode.ts, app/ui/src/assets/dictionary/en-GB.json
* The mustache symbols need to be prefixed with 'body.' and should not
include other punctuation in order to be valid. Updates the validation
routine to display errors if this format is not being followed.
#3854
=> fix(template step) - Add variable symbol validation

app/connector/rest-swagger/src/main/resources/camel-connector.json
We had the default endpoint option `consumes` set to `application/json` that would override any `produces` content type given in the OpenAPI specification. This is now removed and the content type is taken from the `produces` parameter in the OpenAPI specification.
Fixes #3388
=> fix(connector): don't set `application/json` as Accept by default

app/connector/support/processor/pom.xml, app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/HttpRequestUnwrapperProcessor.java, app/connector/support/processor/src/test/java/io/syndesis/connector/support/processor/HttpRequestUnwrapperProcessorTest.java
Removes quoting of body values within unified JSON schema. So
```json
{
"body": "value"
}
```
Is not returned as `"value"` with quotes, but rather as `value` without
quotes.
Fixes #3909
=> fix(connector): remove quotes from simple body values

app/ui/package.json, app/ui/patches/codemirror+5.40.0.patch, app/ui/yarn.lock
* ReferenceError occurs when codemirror's lint.js is uglified. Since it
will take some time for a PR to be accepted and a new version released,
uses package-patch to make the small code change and fix the problem.
* package-patch will auto-run on post-install to ensure the patch is
applied to the file. See https://www.npmjs.com/package/patch-package
for details.
#3760
=> fix(ui) Patch codemirror's lint script file

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss, app/ui/src/app/integration/integration_detail/integration-description.component.html, app/ui/src/app/integration/integration_detail/integration-description.component.scss
fixes https://github.com/syndesisio/syndesis/issues/3920
@gashcrumb I left the business logic in, and just reverted the view since @dongniwang said the goal is to re-introduce the icons at a later point. feel free to remove any of that as you see fit.
=> fix(step-icons): revert step icons in integration details and editor IVP

app/common/util/src/main/java/io/syndesis/common/util/Names.java, app/common/util/src/test/java/io/syndesis/common/util/NamesTest.java
Adds the replacement of `.` (dot) character with the `-` (dash) character in name sanitization.
Fixes #3925
=> fix(server): remove dot characters from OpenShift object names

app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.html, app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.ts
* Removes the ng2-codemirror DnD event handlers and places them directly
on the codemirror instance. The dragEnter event is handled far more
reliably this way.
* Allows for the codemirror instance to be initialised, the AfterViewInit
interface is employed to configure the DnD callback handlers.
* Uses @HostListener to wire up a dragenter event to the main document. This
will fire whenever a drag is on anything other than the drop target and
will therefore turn off the drop target's overlay.
* onEditorDragenter to stop propogation to stop the event propogating up
to the document callback.
* onEditorDrop does NOT stop propogration since it needs to both turn off
the overlay but also default to the native behaviour of actually dropping
the file contents.
#3763
=> fix(template-step) drag and drop overlay reliably displaying

install/generator/04-syndesis-db.yml.mustache, install/syndesis-dev.yml, install/syndesis.yml
This doubles th `autovacuum_vacuum_cost_limit` from `1000` to `2000`
which empirically looks like a good value so that the autovacuum is not
throttled.
Before (with 1000):
```
LOG:  automatic vacuum of table "syndesis.public.jsondb": index scans: 0
pages: 0 removed, 72236 remain, 1996 skipped due to pins
tuples: 0 removed, 855896 remain, 797779 are dead but not yet removable
buffer usage: 89805 hits, 70138 misses, 359 dirtied
avg read rate: 4.438 MB/s, avg write rate: 0.023 MB/s
system usage: CPU 0.55s/0.25u sec elapsed 123.46 sec
```
After (with 2000):
```
LOG:  automatic vacuum of table "syndesis.public.jsondb": index scans: 1
pages: 0 removed, 1859 remain, 0 skipped due to pins
tuples: 2915 removed, 22780 remain, 0 are dead but not yet removable
buffer usage: 2611 hits, 431 misses, 6 …
```
=>  fix(db): increase `autovacuum_vacuum_cost_limit` 

app/server/runtime/src/main/java/io/syndesis/server/runtime/SecurityConfiguration.java, app/server/runtime/src/main/java/io/syndesis/server/runtime/SyndesisCorsConfiguration.java
While working on some experiment, I noticed that the current implementation of CORS was broken due to CORS checks being handled through a filter instead of using the HttpSecurity model.
Long story short: using a filter it's not possible to skip some of the checks performed as by the HttpSecurity configuration; preflight requests (OPTIONS) where being refused because the CSRF check was performed on them (which is wrong).
Now cors checks are chained to other checks, and preflight requests are permitted as by the `CorsConfigurationSource` rules.
This doesn't mean that it's now possible to do CORS requests against the default entrypoint of the app (eg. https://syndesis.192.168.64.16.nip.io), since the oauth-proxy is doing something weird I haven't grasped yet.
If one needs to talk directly …
=> fix(server): make CORS great again

app/server/runtime/src/main/resources/application.yml, app/ui/docker/nginx-syndesis.conf
Gzip wasn't properly enabled on our server(s). This enables it on both the server and the UI's nginx proxy.
13.6Mb downloaded to show the dashboard with 4 integrations present in the system (not running).
4.0Mb for the same data, with gzip enabled.
_Hint: look at the `Size` and `Content-...` columns._
=> fix(ui): enable gzip for the most relevant mimetypes

app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
fixes #3954.
fix(IVP): adding a configuration change to the button div that will prevent odd overlap on the tooltip from other sections of the site.
=> fix(IVP): odd overlap over tooltip feature

doc/tutorials/topics/amq2api_create_rest_api_connector.adoc
When OpenShift is running without a trusted CA issuing the certificates REST API connector will fail with TLS error as the certificate for the TODO route will not be valid. This changes the scheme from `https` to `http` and adds a step to prompt the users to change it on their end also.
=> chore: use `http` instead of `https`

.circleci/config.yml
This updates the `curl`-ed Docker CE URL and version (17.04.0-ce) is no
longer available and `get.docker.com` serves a shell script.
=> chore: update the Docker download URL and version

app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
(cherry picked from commit 92c2e97744343d9f2df43856571478483b5f535a)
=> password should be marked as required (1.5.x backport)

app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/HttpRequestUnwrapperProcessor.java, app/connector/support/processor/src/test/java/io/syndesis/connector/support/processor/HttpRequestUnwrapperProcessorTest.java
When unwrapping, i.e. converting from Syndesis wrapped format with body and parameters, we should consider arrays as well as objects for JSON serialization of the body.
Fixes #3788
=> fix: consider all container objects when unwrapping response

app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/HttpRequestUnwrapperProcessor.java, app/connector/support/processor/src/test/java/io/syndesis/connector/support/processor/HttpRequestUnwrapperProcessorTest.java
When unwrapping, i.e. converting from Syndesis wrapped format with body and parameters, we should consider arrays as well as objects for JSON serialization of the body.
Fixes #3788
(cherry picked from commit 36e66918914f479f764faadde0ad25cb5e957c5c)
=> fix: consider all container objects when unwrapping response (1.5.x)

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/TemplateStepHandler.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/templater/MustacheTemplatePreProcessor.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/templater/TemplateMustacheConstants.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/templater/TemplateProcessingException.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/TemplateStepHandlerTest.java, app/ui/src/app/integration/edit-page/step-configure/templater/mustache-mode.ts
* TemplateStepHandler
* Adds preprocessing to the template content to add in the 'body.' prefix
to each symbol if not already present
* MustacheTemplatePreProcessor
* Parses each token in the template string to check validity and prepend
body prefix to symbols
* Update tests including adding extra tests that check the syntax of the
template
* mustache-mode.ts
* Modifies the regex for the symbol format in the UI's template step
editor. This removes the body prefix from being required in the symbols.
* Moves the syntax checking portion to the bottom of the loop since its
current position means the last word / symbol is never checked.
fixes #3894
=> fix(template-step): Removes need for body prefix in template

app/connector/api-provider/src/main/resources/spring.factories, app/connector/http/pom.xml, app/connector/http/src/main/resources/META-INF/spring.factories, app/connector/http/src/main/resources/META-INF/syndesis/connector/http4.json, app/connector/http/src/main/resources/META-INF/syndesis/connector/https4.json, app/connector/rest-swagger/pom.xml, app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/springboot/SwaggerConnectorConfiguration.java, app/connector/rest-swagger/src/main/resources/camel-connector.json, app/connector/support/processor/pom.xml, app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/SyndesisHeaderStrategy.java, app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/SyndesisHttpConfiguration.java, app/connector/support/processor/src/main/resources/META-INF/spring.factories, app/connector/webhook/src/main/resources/META-INF/syndesis/connector/webhook.json, app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/RestRouteConfiguration.java.mustache, app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/application.properties.mustache, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateApplicationWithRestDSL/RestRouteConfiguration.java, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/application.properties
Previous attempts of removing Camel message headers did not pan out successful, this is mainly because it's a race between the Activity tracing interceptor that adds this to around every interceptor and the header-removal logic.
With this, a new approach of using/configuring HeaderFilterStrategy to the servlet (webhook & API provider), HTTP and API client connector eliminates the need for removing Camel message headers and deals with the issue on the HTTP protocol binding level.
As the HTTP4 component RestProducerFactory implementation overwrites any HeaderFilterStrategy configured on the component/endpoint a subclass was necessary to make this function.
So with this fix all HTTP interactions: be it HTTP requests sent out of integrations (HTTP connector, API client connector) or any HTTP …
=> fix: use HeaderFilterStrategy with all HTTP

app/connector/api-provider/src/main/resources/spring.factories, app/connector/http/pom.xml, app/connector/http/src/main/resources/META-INF/spring.factories, app/connector/http/src/main/resources/META-INF/syndesis/connector/http4.json, app/connector/http/src/main/resources/META-INF/syndesis/connector/https4.json, app/connector/rest-swagger/pom.xml, app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/springboot/SwaggerConnectorConfiguration.java, app/connector/rest-swagger/src/main/resources/camel-connector.json, app/connector/support/processor/pom.xml, app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/SyndesisHeaderStrategy.java, app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/SyndesisHttpConfiguration.java, app/connector/support/processor/src/main/resources/META-INF/spring.factories, app/connector/webhook/src/main/resources/META-INF/syndesis/connector/webhook.json, app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/RestRouteConfiguration.java.mustache, app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/application.properties.mustache, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateApplicationWithRestDSL/RestRouteConfiguration.java, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/application.properties
Previous attempts of removing Camel message headers did not pan out successful, this is mainly because it's a race between the Activity tracing interceptor that adds this to around every interceptor and the header-removal logic.
With this, a new approach of using/configuring HeaderFilterStrategy to the servlet (webhook & API provider), HTTP and API client connector eliminates the need for removing Camel message headers and deals with the issue on the HTTP protocol binding level.
As the HTTP4 component RestProducerFactory implementation overwrites any HeaderFilterStrategy configured on the component/endpoint a subclass was necessary to make this function.
So with this fix all HTTP interactions: be it HTTP requests sent out of integrations (HTTP connector, API client connector) or any HTTP …
=> fix: use HeaderFilterStrategy with all HTTP (1.5.x backport)

app/ui/src/scss/utils/_overrides.scss
fixes: #4036 
- removing the cursor pointer to a lower div level. This is a UX improvement that alleviates registered click confusion on listed integration items.
**NOTE:**
This has been a known issue with Patternfly-ng since the beginning. The level of effort required to overhaul and correct the list items (JavaScript based) would cause a cascade of UI bugs through the system. For now, a minor UX improvement is the best solution. We can place greater attention to the list items when we build out and apply PF4 to Syndesis. Thanks to @seanforyou23 and @mcoker on their feedback for this issue.
@dongniwang, please verify the fix on your end and please delegate the shelf life of this ticket. Thanks!
=> refactor(integration list items): relocating cursor pointer

tools/upgrade/migration/resource/1.2/01_server_config_map_upgrade.sh
Fixes #4064
(cherry picked from commit 6a71497f8c9214e99d65a4f1aae849de8074a31e)
=> chore(upgrade): upgrade image stream tag in the syndesis-server-config ConfigMap (1.5.x backport)

app/common/model/src/main/java/io/syndesis/common/model/Dependency.java, app/integration/api/src/main/java/io/syndesis/integration/api/IntegrationResourceManager.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorIconHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/support/IntegrationSupportHandler.java
Fixes issue 4055. With this fix it exports the icon model as well as the image as file. On integration import the model is restored into the JSONDB and the image is restored into the (Sql)FileStore if it didn't exist already.
=> [fix] Missing icon custom connector after import #4055

tools/bin/commands/release
Removes the `git commit` call for files within `app/connector` as there
are no more changes there when we run the build.
=> fix: no need to commit anything from app/connector

app/ui/src/scss/utils/_overrides.scss
fixes #4094
- glyphicon css needed to be overwritten to help align itself with the tooltip on hover.
=> fix(tooltip glyphicon): tooltip misaligned with glyphicon.

tools/bin/commands/util/openshift_funcs
"syndesis install" accidentally fails when Server URL contains "oc"
=> Fix #4123: "syndesis install" accidentally fails

app/pom.xml, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelper.java, app/server/api-generator/src/test/resources/swagger/invalid/warning-petstore.swagger.json, app/server/api-generator/src/test/resources/swagger/petstore.unified_connector.json, app/server/api-generator/src/test/resources/swagger/petstore_xml.unified_connector.json, app/server/api-generator/src/test/resources/swagger/reverb.unified_connector.json, app/server/jsondb/src/test/java/io/syndesis/server/jsondb/impl/JsonDBTest.java
Bit of detail in the commit messages:
fix: include all nodes in JSONDB test
Seems that the test was written with the idea that all nodes, even
`null` ones will be included in serialization/deserialization, so this
configures the right inclusion. As surfaced by Jackson upgrade.
fix: preloads the Swagger 2.0 JSON schema
Seems that Jackson upgrade triggered Swagger 2.0 schema download from
`http://swagger.io/v2/schema.json#`, this is unwanted we provide the
schema file embeded in the artefact.
fix: remove accessTokenExpiresAt.description
It is empty and in `io.syndesis.common.util.Json` we serialize only non
empty nodes. Change introduced with Jackson 2.9.7
=> Upgrades Jackson to 2.9.7

app/pom.xml
It's one release beyond what we do on fuse, but I think the project can start using it no?
=> [chore in square brackets] upgrading sb

app/connector/activemq/pom.xml, app/connector/amqp/pom.xml, app/connector/api-provider/pom.xml, app/connector/aws-s3/pom.xml, app/connector/dropbox/pom.xml, app/connector/fhir/pom.xml, app/connector/ftp/pom.xml, app/connector/gmail/pom.xml, app/connector/google-calendar/pom.xml, app/connector/google-sheets/pom.xml, app/connector/http/pom.xml, app/connector/irc/pom.xml, app/connector/kafka/pom.xml, app/connector/log/pom.xml, app/connector/mqtt/pom.xml, app/connector/salesforce/pom.xml, app/connector/servicenow/pom.xml, app/connector/sftp/pom.xml, app/connector/slack/pom.xml, app/connector/sql/pom.xml, app/connector/support/maven-plugin/src/main/java/io/syndesis/connector/support/maven/GenerateConnectorInspectionsMojo.java, app/connector/telegram/pom.xml, app/connector/timer/pom.xml, app/connector/twitter/pom.xml, app/connector/webhook/pom.xml, app/extension/example/log-step/pom.xml
This helps with invoking maven goals that do not require Syndesis Maven
plugins (like `mvn clean`) when the said Maven plugins are not available
from the local repository (or for download).
I don't see us hosting a repository with SNAPSHOTS (we'll not at least
in the short-to-medium time), this at least helps invoking some Maven
phases when the Syndesis Maven plugins are not required.
Depending on Maven plugins from the same project/reactor is usually not
a good idea.
Fixes #1501 (sort of)
=> refactor: set the phases on for Syndesis Maven plugins

app/connector/activemq/pom.xml, app/connector/amqp/pom.xml, app/connector/api-provider/pom.xml, app/connector/aws-s3/pom.xml, app/connector/dropbox/pom.xml, app/connector/fhir/pom.xml, app/connector/ftp/pom.xml, app/connector/gmail/pom.xml, app/connector/google-calendar/pom.xml, app/connector/google-sheets/pom.xml, app/connector/http/pom.xml, app/connector/irc/pom.xml, app/connector/kafka/pom.xml, app/connector/log/pom.xml, app/connector/mqtt/pom.xml, app/connector/salesforce/pom.xml, app/connector/servicenow/pom.xml, app/connector/sftp/pom.xml, app/connector/slack/pom.xml, app/connector/sql/pom.xml, app/connector/support/maven-plugin/src/main/java/io/syndesis/connector/support/maven/GenerateConnectorInspectionsMojo.java, app/connector/telegram/pom.xml, app/connector/timer/pom.xml, app/connector/twitter/pom.xml, app/connector/webhook/pom.xml, app/extension/example/log-step/pom.xml, app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java, app/ui/yarn.lock
Make sure that connector meta `*.json` has been copied to target classes when plugin performs inspection generation. Bind plugin execution to phase `compile` because generation Mojo is using source class files for its inspection, too.
=> #4206 Fix generation of connector data shape inspections

app/server/builder/maven-plugin/pom.xml, app/server/runtime/pom.xml
Server builder maven plugin descriptor has not been created as descriptor generation was bound to `default-descriptor` phase which obviously does not exist in Maven.
In addition to that plugin usage in server runtime module was bound to phase `genrate-resources` which is obviously a typo.
Fixed both issues. 
Though I am wondering if we actually need this plugin as the descriptor and execution has been broken for the last 6 months.
=> Fixed server builder maven plugin usage

app/ui/package.json, app/ui/yarn.lock
Also upgrades Snyk to latest. Should squash high severity issues reported by Snyk.
=> chore: upgrade to latest v6-lts Angular dependencies

app/pom.xml
There is a security issue with 2.9.7.
=> chore: upgrade Jackson to 2.9.8

app/connector/irc/pom.xml, app/connector/irc/src/main/java/io/syndesis/connector/irc/IrcConnector.java, app/connector/irc/src/main/java/io/syndesis/connector/irc/IrcConnectorFactory.java, app/connector/irc/src/main/java/io/syndesis/connector/irc/IrcVerifier.java, app/connector/irc/src/main/java/io/syndesis/connector/irc/IrcVerifierAutoConfiguration.java, app/connector/irc/src/main/java/io/syndesis/connector/irc/IrcVerifierExtension.java, app/connector/irc/src/main/resources/META-INF/spring.factories, app/connector/irc/src/main/resources/META-INF/syndesis/connector/irc.json
- extract common parameters to connection level
- add irc verifier
- add new action to send messages to channel
This will require this commit from camel to be present in our camel version: https://github.com/apache/camel/commit/c29f083d86f53c18ca46c7de9f4ee99f26f4b114
currently there is one outstanding issue that the `channels` parameter is not passed to the endpoint - the `channels` property is [not defined as endpoint property at camel level](https://github.com/apache/camel/blob/master/components/camel-irc/src/main/java/org/apache/camel/component/irc/IrcConfiguration.java#L47) and thus it is ignored by [this code](https://github.com/syndesisio/syndesis/blob/master/app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentProxyComponent.java#L333-L342) …
=> [#3655] Tune IRC connector

app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesCustomizer.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsMetaDataExtension.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsMetadataRetrieval.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizer.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/meta/GoogleSheetsMetaDataHelper.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/RangeCoordinate.java, app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/stream/GoogleSheetsStreamConfiguration.java, app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesCustomizerTest.java, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesSplitResultsCustomizerTest.java, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsMetadataAdapterTest.java, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizerTest.java, app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/stream/SheetsStreamConsumerIntegrationTest.java
When data mapper does not set all values in a data range we need to auto fill in those gaps with "null" values in order to ensure proper value propagation to Google Sheets API. 
If not filling those gaps the update will result in a different outcome and the updated range does not match the required range.
**Example no AutoFill**
Range: A1:E1
Values: ["Test A", "Test B", "Test E"]
Result: 
```
A        B        C       D       E
Test A   Test B   Test E
```
UpdatedRange: A1:C1
**Example with AutoFill**
Range: A1:E1
Values: ["Test A", "Test B", null, null, "Test E"]
Result: 
```
A        B        C       D       E
Test A   Test B                   Test E
```
UpdatedRange: A1:E1
=> #4229 Auto fill missing values in value ranges

doc/tutorials/topics/amq2api_add_damage_reporter_step.adoc, doc/tutorials/topics/amq2api_add_mapping_step.adoc, doc/tutorials/topics/amq2api_choose_finish.adoc, doc/tutorials/topics/amq2api_choose_start.adoc, doc/tutorials/topics/amq2api_confirm_works.adoc, doc/tutorials/topics/amq2api_create_amq_connection.adoc, doc/tutorials/topics/amq2api_create_custom_step.adoc, doc/tutorials/topics/amq2api_create_integration.adoc, doc/tutorials/topics/amq2api_create_rest_api_connection.adoc, doc/tutorials/topics/amq2api_create_rest_api_connector.adoc, doc/tutorials/topics/amq2api_intro.adoc, doc/tutorials/topics/amq2api_name_and_publish.adoc, doc/tutorials/topics/amq2api_upload_todo_app_icon.adoc, doc/tutorials/topics/comparison_of_sample_integrations.adoc
Resolves FUSEDOC-2940 which requires an update to the procedure for uploading the icon for the Todo app. Adds a note about specification of http vs. https for obtaining OpenAPI documents. Adds a note about ignoring a data type mismatch warning on the IVP. Updates references to AMQ to be to "Red Hat AMQ" where appropriate. (FUSEDOC-2950) and Syndesis 4183.
=> Updates to AMQ to REST API tutorial

doc/connecting/topics/adding_amq_connection_finish.adoc, doc/connecting/topics/adding_amq_connection_middle.adoc, doc/connecting/topics/adding_amq_connection_start.adoc, doc/connecting/topics/connecting_to_amq.adoc, doc/connecting/topics/connecting_to_amqp.adoc, doc/connecting/topics/create_amq_connection.adoc, doc/connecting/topics/supported_connectors.adoc
I updated the connectors guide to refer to Red Hat AMQ. 
@gaughan or @gashcrumb could you review the updates and let me know if they are okay?
Thanks!
I updated instances in the tutorial in a different PR. 
In the integration guide, there are a bunch of generic AMQ references, which I think are okay, so not changes there.
=> WIP: user doc: Update to refer to Red Hat AMQ (#4183)

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/integration/edit-page/action-select/action-select.component.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts, app/ui/src/app/integration/edit-page/flow-functions.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts, app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
relates to #4294
@riccardo-forina FYI, feedback welcome!
planning on finishing up the last 4 event handler blocks that mutate the step array directly, then there's all the positional functions in the current flow service that controllers use to examine neighboring steps etc. like `filterConnectionsByPosition` and `getStartStep`, `getEndStep`, `getSubsequentConnections` and so on...
=> chore: refactor out the meat of the event handlers in current flow service

doc/integrating-applications/topics/r_how-to-specify-data-shapes.adoc
In the topic about how to specify data shapes in extensions, there are now examples of specifications of json-schema, json-instance, xml-schema, xml-instance, thanks to Zoran! There is also a link to the examples in the Concur connector code.
=> user doc: Add examples of data shape specifications

app/pom.xml
Fix for PR on Removing the dependency of the RouteBuilder on SpringBoot so it can be reused in CamelK #4232. First step is a simple refactoring.
=> [fix] Fixing module name for  version for integration-runtime-springboot

app/ui/src/app/store/step/step.store.ts
This just removes an "s" from "Sends" and adds a period at the end of the sentence. 
This makes the description of the log step consistent with the descriptions of the other steps.
=> Typo fix: Make description of log step consistent with other step descriptions

app/common/util/src/main/java/io/syndesis/common/util/cache/CacheManager.java, app/common/util/src/main/java/io/syndesis/common/util/cache/LRUCacheManager.java, app/server/endpoint/pom.xml, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/tests/TestSupportHandler.java
This uses `TRUNCATE` statement to remove all rows from `jsondb`,
`filestore` and `config` tables instead of looping through the database
entities and deleting each row individually or using `DELETE ... LIKE`.
This should eliminate database log use and speed up the database reset.
Fixes #4308
=> fix(server): optimize database reset

doc/pom.xml
Getting an error building doc 
[INFO] --- dependency-management-maven-plugin:0.7:analyze (default) @ syndesis-docs ---
[WARNING] Version mismatch for plugin org.asciidoctor:asciidoctor-maven-plugin, managed version 1.5.7.1 does not match project version 1.5.3
Should align asciidoctor-maven-plugin versions.
=> Match ascii-doctor-version with the version in app/pom.xml

doc/connecting/topics/as_connecting-to-rest-apis.adoc, doc/connecting/topics/r_supported-connectors.adoc, doc/integrating-applications/topics/as_adding-api-connectors.adoc, doc/integrating-applications/topics/as_customizing.adoc, doc/integrating-applications/topics/as_developing-rest-api-client-connectors.adoc, doc/integrating-applications/topics/c_about-api-provider-flows.adoc, doc/integrating-applications/topics/c_about-api-provider-urls.adoc, doc/integrating-applications/topics/c_description-kinds-extensions.adoc, doc/integrating-applications/topics/c_guidelines-for-openapi-documents.adoc, doc/integrating-applications/topics/c_overview-benefit-api-provider-integrations.adoc, doc/integrating-applications/topics/c_workflow-api-providers.adoc, doc/integrating-applications/topics/p_configure-publish-api-provider-quickstart.adoc, doc/integrating-applications/topics/p_create-api-provider-integration.adoc, doc/integrating-applications/topics/p_create-integration-operation-flows.adoc, doc/integrating-applications/topics/p_creating-api-connectors.adoc, doc/integrating-applications/topics/p_updating-api-connectors.adoc, doc/integrating-applications/topics/r_providing-client-credentials.adoc, doc/integrating-applications/topics/r_refreshing-access-tokens.adoc, doc/tutorials/topics/as_amq2api-intro.adoc, doc/tutorials/topics/p_sf2db-confirm-works.adoc
The user doc now consistently refers to OpenAPI documents. 
Sometimes, references are to OpenAPI schemas or OpenAPI files.
=> user doc: Consistently refer to OpenAPI documents, not specifications.

app/connector/sql/src/main/java/io/syndesis/connector/sql/common/JSONBeanUtil.java, app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlConnectorCustomizer.java, app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlStartConnectorCustomizer.java, app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlStoredConnectorCustomizer.java, app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlConnectorQueryTest.java
Sql connector now returning all rows of DB result set as a list of json beans. This is a base for implementing collection support on connectors introduced with https://github.com/syndesisio/syndesis/issues/3896
=> [3856] SQL connector should return all results as collection

app/integration/runtime-springboot/src/test/java/io/syndesis/integration/runtime/sb/capture/OutMessageCaptureProcessorTest.java
Remove unnecessary assertion on last message captured that causes flaky behavior. Last processor in an integration is not relevant for message capture outcome.
Yet that assertion on this last message capture caused flaky behavior in continuous build.
=> Fix flaky out message capture unit test

app/common/util/src/main/java/io/syndesis/common/util/backend/BackendController.java, app/server/controller/src/main/java/io/syndesis/server/controller/endpoint/EndpointController.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/IntegrationController.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/tests/TestSupportHandler.java, app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java, app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/KubernetesSupport.java, app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
This ensures that the controllers running on separate threads are stopped before database reset and restarted after database reset. Any database connections that might be opened at the point of a database reset are forcefully reset to make sure they're not preventing the `TRUNCATE`.
Fixes #4308
=> fix: make sure to perform the database reset

app/common/model/src/main/java/io/syndesis/common/model/WithConfigurationProperties.java, app/common/model/src/main/java/io/syndesis/common/model/connection/ConfigurationProperty.java, app/server/dao/src/main/java/io/syndesis/server/dao/manager/EncryptionComponent.java, app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/AbstractResourceUpdateHandler.java
We don't want to add methods to model interfaces that override the model property methods.
Fixes #4219
=> refactor(server): don't use overriding properties

app/ui/src/scss/utils/_overrides.scss
Using percentage seems to be causing Firefox to calculate the percentage
across the whole page width.
=> fix(ui): switch logo width from percentage to rem

app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/RestRouteConfiguration.java.mustache, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateApplicationWithRestDSL/RestRouteConfiguration.java
The use of `simple` expression made the content of the `src/main/resources/openapi.json` was reinterpreted and any quoted and escaped newline characters (`\n` within a quoted string) were expanded to newlines making the string span multiple lines and breaking the JSON syntax.
Fixes #4468
=> fix: ensure that the openapi.json is not reinterpreted

tools/misc/extract_integration.sh
The user needs to specify the full name of the pod, no need for greping
the output and making the tool fragile.
Ref #2911
=> refactor(tool): no need to list pods

tools/upgrade/migration/preflight.sh
Hopefully, this one will be alright:
```
/tmp :: ./test.sh "1.X"
ERROR: Cannot extract minor version from '1.X'
➤  /tmp :: ./test.sh "1.1.X"
1.1
➤  /tmp :: ./test.sh "1.5.0"
1.5
➤  /tmp :: ./test.sh "1.5.0-20190128"
1.5
➤  /tmp :: ./test.sh "1.5.0-redhat-123"
1.5
➤  /tmp :: ./test.sh "1.1"
1.1
➤  /tmp :: ./test.sh "10.1"
10.1
➤  /tmp :: ./test.sh "1.10"
1.10
➤  /tmp :: ./test.sh "1.101"
1.101
```
=> [Upgrade] Fix regex in preflight.sh

app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/UpdatesHelper.java
Adding `basePath` to Action metadata allows the EndpointController to generate the exposed URL including it.
Fixes #4471
=> feat(server): add basePath to action metadata

app/pom.xml
See https://github.com/FasterXML/jackson-databind/blob/jackson-databind-2.8.11.3/release-notes/VERSION#L6 for security related fixes
=> Bump version of jackson-databind to 2.8.11.3

install/addons/syndesis-db-prometheus-rule.yml, install/addons/syndesis-jvm-prometheus-rule.yml, install/addons/syndesis-rest-api-prometheus-rule.yml
Follow up to #4514. I missed some labels for the alert rules that are expected by the integr8ly operator.
=> fix(monitoring): Add missing labels to alert rules

app/common/model/pom.xml, app/common/util/pom.xml, app/common/util/src/main/java/io/syndesis/common/util/openapi/CapturingCodec.java, app/common/util/src/main/java/io/syndesis/common/util/openapi/OpenApiHelper.java, app/common/util/src/test/java/io/syndesis/common/util/immutable/SkipNullsTest.java, app/common/util/src/test/java/io/syndesis/common/util/openapi/OpenApiHelperTest.java, app/integration/project-generator/pom.xml, app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java, app/server/api-generator/pom.xml, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelper.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/BaseSwaggerConnectorGeneratorTest.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/UnifiedXmlDataShapeGeneratorRequestShapeTest.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/UnifiedXmlDataShapeGeneratorShapeValidityTest.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/UnifiedXmlDataShapeGeneratorTest.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelperTest.java
We need to make sure that the configuration changes and mixins of Jackson ObjectMapper used by SwaggerParser's are applied. And the way to make sure that they are is to make sure that all usage of SwaggerParser is done through `OpenApiHelper` which was created by refactoring bits of `SwaggerHelper` from `server-api-generator` into `common-util` as it is used in `integration-project-generator` also.
This should make sure that the observed flakiness of the `SwaggerHelperTest`, which is due to the order of execution/initialization of ObjectMapper used by SwaggerParser is fixed. I'll run the CircleCI workflow multiple times to make sure this is the case.
Ref #4477
=> refactor(server): additional fixes for #4477

app/ui/src/app/common/openapi/editor/editor.component.scss, app/ui/src/app/common/ui-patternfly/list-toolbar/list-toolbar.component.scss, app/ui/src/app/integration/api-provider/editor-page/index.ts, app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-page.component.html, app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-page.component.scss, app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-page.component.ts, app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.html, app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.scss, app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.ts, app/ui/src/app/integration/api-provider/index.ts, app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operation-description-component.ts, app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-list.component.html, app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-list.component.ts, app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-page.component.html, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html, app/ui/src/app/integration/edit-page/action-select/action-select.component.html, app/ui/src/app/integration/edit-page/edit-page.component.html, app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html, app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.ts, app/ui/src/app/integration/edit-page/list-actions/list-actions.component.html, app/ui/src/app/integration/edit-page/list-actions/list-actions.component.spec.ts, app/ui/src/app/integration/edit-page/step-select/step-select.component.html, app/ui/src/app/integration/edit-page/step-select/step-select.component.scss, app/ui/src/app/integration/integration-support.module.ts, app/ui/src/app/integration/integration.module.ts
* redone the layout of the pages to support scrollable panes
* wrapped editor steps in cards
In this screencap the browser started at ~1200px and got up to ~1300px, but the main content (the rightmost pane) doesn't work great with that little space that's left. 
@dongniwang any suggestion?
Also, the connections grid doesn't look great on a white BG.
=> feat(ui): API Provider editor pane-based layout

app/connector/kudu/src/main/java/io/syndesis/connector/kudu/KuduInsertCustomizer.java, app/connector/kudu/src/main/java/io/syndesis/connector/kudu/KuduMetadataRetrieval.java, app/connector/kudu/src/main/resources/META-INF/syndesis/connector/kudu.json
Kudu connector now using json-schema array collection type as output data shape for table scan action.
Also adjusted some things according to data shapes:
- Kudu insert action using no output data shape (insert does not have any output)
- Kudu scan does using no input data shape
Also removed state in insert customizer so subsequent calls to the customizer do always return a fresh message body.
=> Kudu connector returns collection data shape

app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlMetadataRetrieval.java, app/connector/sql/src/test/resources/sql/demo_add_metadata.json, app/connector/sql/src/test/resources/sql/name_sql_metadata.json, app/connector/sql/src/test/resources/sql/name_sql_no_param_metadata.json
SQL connector now using json-schema array collection type as output data shape for sql query actions.
Store procedure actions stay as is as the underlying Camel component is not able to provide a list of results but only a single entry as result set.
=> SQL connector returns collection data shape

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandler.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandlerTest.java, app/ui/src/app/integration/edit-page/current-flow.service.ts
Aggregate step should not only provide output shape of previous step but also the input shape of the subsequent step.
If subsequent step defines a collection shape the server step metadata lookup provides the single element variant of that shape.
=> #4405 Aggregate step should provide input shape of subsequent step

app/integration/runtime-springboot/src/test/java/io/syndesis/integration/runtime/sb/capture/OutMessageCaptureProcessorTest.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteBuilderTest.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteTest.java
Split step was using the wrong (previous step) step id when adding messages to the out message capture processor in integration route builder. Also aggregate step did not add its message to the processor at all.
This lead to failing mappings that map from/to split or aggregate data shapes.
Fixes #4568 and relates to #4405
=> #4586 Fix step id for split and aggregate in integration runtime

install/addons/syndesis-db-dashboard.yml
Currently our Grafana dashboard for Syndesis DB is based on [this](https://grafana.com/dashboards/455).
I noticed Percona have a demo site and a [dashboard](https://pmmdemo.percona.com/graph/d/IvhES05ik/postgresql-overview?refresh=1m&orgId=1) for Postgres instances.
The UX is way better than our current version and it looks a lot nicer. I stripped out any redundant stuff that is not relevant to Syndesis.
=> feat(monitoring): Improve Syndesis DB Grafana Dashboard

app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteNoSplitResultsTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java
* Broadens expected message count to minimum expected message count
since possible for empty messages to pass through the exchange
while the test is completing.
=> fix(#4562): Reduce flakiness of odata unit tests

app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
fixes https://github.com/syndesisio/syndesis/issues/4591
If you look in the original issue (https://github.com/syndesisio/syndesis/issues/4591), you'll see a data-mismatch icon by the aggregate step. I don't see an aggregate step on master. Is that new functionality, or am I missing something?
=> fix(IVP): create common class for IVP step badge icons

app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json
Fixes #4511 and removes include grid data option from connector action as this option is currently not supported
=> Fix #4511 include grid data option is ignored

app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsAddPivotTableCustomizer.java, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsAddPivotTableCustomizerTest.java
This PR fixes #4544 where with these changes pivot table should be placed to the beginning of the target sheet. This is when source data sheet and target sheet diverge. Otherwise the pivot table is places to the subsequent column of the source data range.
=> Fixes #4544 pivot table not placed at the beginning of the sheet

app/integration/runtime/pom.xml, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandler.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandlerTest.java
The problem was that Syndesis operates on List<String> bodies when dealing with topmost collections for Json schema based data shapes.
Atlasmap data mapper expects a Json array String representation of that topmost collection. So we need to convert the source documents marked as Json type documents that are passed to mapper in `OutMessageCaptureProcessor.CAPTURED_OUT_MESSAGES_MAP` or in the exchange itself.
Also we need to convert mapper output target document form Json array String representation back to List<String> where each element is a Json Object String.
I have added this conversion to the datamapper step handler. The handler is provided with the atlasmap mapping definition and reads all Json typed source and target document ids. Based on those and on the List<String> nature of the …
=> Fix Json type source and target conversion for topmost collection support

doc/connecting/topics/as_connecting-to-servicenow.adoc, doc/connecting/topics/p_add-servicenow-connection-finish.adoc, doc/connecting/topics/p_add-servicenow-connection-start.adoc, doc/connecting/topics/p_create-servicenow-import-set.adoc, doc/connecting/topics/p_create-servicenow-web-service.adoc, doc/connecting/topics/r_example-sf-servicenow-integration.adoc
Ready to merge.
This adds a description of a SF to ServiceNow example integration. It also adds instructions for how to create an import set in ServiceNow, which is required for a connection to update a ServiceNow table. 
Reviewed and approved by Luca and by QE - Matej.
=> User doc for ServiceNow example description

app/connector/odata/pom.xml, app/connector/odata/src/test/java/io/syndesis/connector/odata/AbstractODataTest.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationTestSupport.java
* Make all test dependencies in odata active if basepom.check.skip-all
is not defined or false, ie. if flash profile active.
=> fix(#4590): Fix dependency on integration-runtime-tests in odata

app/ui/src/app/app.component.html, app/ui/src/app/store/integration/integration.service.ts, app/ui/yarn.lock
fixes #4619
Also fixes an error message that pops up when the page renders due to an empty string being used in an SVG child element.
=> fix: use the right editor when there's only 1 operation

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandler.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandlerTest.java
This fixes #4631 topmost collection mappings that use single source documents. When only a single source document is provided in the atlas mapping definition the atlasmap camel component mapping runtime will always use the exchange itself as source document.
In that case we have to convert Json array typed exchange message body in addition to those messages captured with out message capture processor.
=> Fixes #4631 Topmost collection mapping errors

app/server/update-controller/src/main/java/io/syndesis/server/update/controller/ResourceUpdateController.java, app/server/update-controller/src/test/java/io/syndesis/server/update/controller/ResourceUpdateControllerTest.java
The reported NullPointerException seems to have been caused by the `scheduler` being `null`, this initializes the scheduler from the constructor and makes sure that it cannot be set to `null`.
Fixes #4523
=> fix(server): make sure that ResourceUpdateController is ready to process events

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandler.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandlerTest.java
When step data shape meta data lookup resolves to nothing preserve original shapes
=> [collection support] Fix to preserve original data shapes on meta lookup

app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java
Throw illegal state exception in case mapper is missing the mandatory mapping definition in configured properties
=> Project generator to report error when missing the data mapper mapping

app/server/runtime/src/main/resources/migrations/up-28.js, app/server/runtime/src/test/java/io/syndesis/server/runtime/migrations/UpgradeVersion28Test.java, app/server/runtime/src/test/resources/migrations/aws-s3-integration.json, app/server/runtime/src/test/resources/migrations/servicenow-integration.json, app/server/runtime/src/test/resources/migrations/simple-timer-integration.json, app/server/runtime/src/test/resources/migrations/sql-integration.json
- DB schema migration now sets proper step id for added split step (fixes #4515)
- migration now also sets proper split step input and output data shapes from previous step
- aggregate step is not added automatically as it causes some confusion to the user (see #4516)
New split step needs to use the step id of the previous step so that data mappers still work as expected. Previous step is provided with a newly generated id.
We can just copy the input and output shapes as in schema 27 and below no collection typed shapes did exist.
Fixes #4560
Fixes #4515
=> [collection support] Update database migration for schema 28

app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java
When importing an integration the connection might not be found in the DB. So avoiding NPE with an additional null check on the connection read from DB.
=> #4008 Avoid NPE when connection is not found in DB

app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/server/GoogleSheetsApiTestServer.java, app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/server/GoogleSheetsApiTestServerRule.java
So more analyzing brought some light to the issue on CircleCi:
- Google test server ran into timeouts waiting for the client to send create spreadsheet requests (server reporting `ActionTimeoutException`)
- Failed server mocking due to timeouts influenced further tests running after that (tests reporting `NullPointerException`)
- Google test server sending `Http 200 Ok` with empty response as default when running into timeouts caused Google Sheets client to error with `No JSON input found` which is quite misleading
Now I have increased the server timeout to give the Google Sheets client more time to fire the requests (CirlceCi is very slow sometimes). Also avoid other tests to be influenced by that timeout by purging the server inbound message queue between tests. Last not least set …
=> [flaky test] Fighting flaky test behavior on CircleCi

app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsCreateSpreadsheetCustomizer.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsGetSpreadsheetCustomizer.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsUpdateSpreadsheetCustomizer.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/GoogleSheet.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/GoogleSpreadsheet.java, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsCreateSpreadsheetCustomizerTest.java, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsGetSpreadsheetCustomizerTest.java, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsUpdateSpreadsheetCustomizerTest.java
Google Sheets connector handing all sheets and its properties when getting and updating spreadsheet properties.
Fixes #4672
=> fix: handle all sheets and its properties in a spreadsheet

app/ui/angular.json, app/ui/src/app/app.component.html, app/ui/src/app/app.component.scss, app/ui/src/scss/patternfly-base-alacarte.scss, app/ui/src/scss/utils/_overrides.scss, app/ui/yarn.lock
This PR makes an adjustment to what all we're importing from patternfly4-core. Previously, patternfly-base.css came with extra baggage that we didn't want (namely fonts). With these changes, the entire application again uses only PF3 fonts, and many of the various spacing issues should also be resolved.
To keep things clean on our end, a change in patternfly core was required - https://github.com/patternfly/patternfly-next/pull/1467 - we need this merged in pf-core before we can merge this PR. To see it all in action, pair these two branches together.
Fixes https://github.com/syndesisio/syndesis/issues/4608
Fixes https://github.com/syndesisio/syndesis/issues/4612
import only the pf4 css modules we need
clean up font styles
=> fix(fonts): consolidate font styles/sizes

app/ui/package.json, app/ui/yarn.lock
We need to upgrade due to a security issue.
Ref https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/
=> chore(ui): upgrade bootstrap to ~3.4

app/ui/src/scss/utils/_overrides.scss
fixes https://github.com/syndesisio/syndesis/issues/4520
fixes https://github.com/syndesisio/syndesis/issues/4594
I believe this was just added to help align tooltips, but it's not necessary since those items are already `inline-block`, and it would have only addressed the info icon, not any other icons. `display: block` was causing problems on pages where there is a `&nbsp;` followed by the glyphicon, pushing the glyphicon onto a second line.
=> fix(overrides): remove glyphicon from overrides

app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationTestSupport.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/CyclicValidationCheck.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SyndesisSwaggerValidationRules.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/CyclicValidationCheckTest.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/SyndesisSwaggerValidationRulesTest.java, app/server/api-generator/src/test/resources/swagger/openhab.swagger.json
We cannot support cyclic schema references due to the fact that we need to provide canonical schema for the data shape specification. This adds a validation for cyclic schema references and reports an error if such schema is used.
Fixes #4437
=> feat(server): cyclic schema references validation for OpenAPI documents

app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Consumer.java, app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Endpoint.java, app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Index.java, app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Producer.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteNoSplitResultsTest.java
* Syncs the forked olingo4 component code with the code in the upstream
camel-olingo4 2.x branch
* Most of the changes are the licence header. However, one change does
affect a test.
* ODataRead...ResultsTest
* Due to the change in Olingo4Consumer, only 1 message is returned and
empty messages are never created. Thus, the test should only expect 1
message and not 3.
=> chore(#4693): sync up odata forked code with 2.x branch of upstream

app/connector/fhir/src/main/resources/META-INF/syndesis/connector/fhir.json, app/connector/odata/src/main/resources/META-INF/syndesis/connector/odata.json, app/connector/salesforce/src/main/resources/META-INF/syndesis/connector/salesforce.json, app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json, app/connector/telegram/src/main/resources/META-INF/syndesis/connector/telegram.json
* To stop class names being used in the data mapper, provide names for all
java data shapes.
=> fix(#4459): Add names to java data shapes

doc/connecting/topics/p_create-gmail-connection.adoc, doc/connecting/topics/p_create-google-calendar-connection.adoc, doc/connecting/topics/p_create-google-sheets-connection.adoc
This new prerequisite is in the topics about creating  a Gmail connection, creating a Google Calendar connection, and creating a Google Sheets connection. 
This is related to https://github.com/syndesisio/syndesis/issues/4431
=> user doc: Add prereq that client ID and secret are in Settings page entry

app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsAddChartCustomizer.java, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsAddChartCustomizerTest.java
Fixes #4662 with overlay position being mandatory when a target sheet is set
=> fix: Google sheets chart target position

app/extension/bom/pom.xml, app/integration/bom/pom.xml, app/pom.xml
This fix should contains all the required stuff for the odata connector, in this way we can remove the camel bits from the connector and use directly the component.
FYI @phantomjinx
=> chore(version): Update camel to version 2.21.0.fuse-730054

app/ui/src/app/store/step/step.store.ts
Added some checks when adding steps of kind aggregate. Aggregate step should only get displayed when applicable according to the current position in the integration.
This is when a previous split step is present that has not yet a corresponding aggregate. This makes sure that each split has only one corresponding aggregate step. Logic supports nested split/aggregate as well as multiple subsequent split steps.
Fixes #4710
=> fix: Ensure consistent split/aggregate steps in UI

app/ui/src/app/common/card-tech-preview.component.ts
I don't see any tech previews in my list of connections, but this should address it. Could someone verify it, or let me know how I can get a connection with the tech preview icon/popover?
fixes https://github.com/syndesisio/syndesis/issues/4385
=> fix(card-tech-preview): change container to body to prevent popover from being cut off

app/connector/sql/src/main/java/io/syndesis/connector/sql/common/JSONBeanUtil.java, app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlConnectorCustomizer.java, app/connector/sql/src/test/java/io/syndesis/connector/sql/common/JSONBeanUtilTest.java
SQL connector needs to read query parameter information from exchange body. With this PR connector only reads that information when SQL query actually uses parameters and when body is of proper Json object type.
This ensures failsafe processing in (rare) cases where SQL connection step is not provided with proper Json parameter exchange body (e.g. static SQL queries without any parameters and consecutive SQL steps)
Fixes #4728
=> fix: SQL connector failsafe query parameter read from body

install/generator/04-syndesis-server.yml.mustache, install/syndesis.yml
Fix #4717.
Tested on local minishift. No more restarts.
=> Fix #4717: constrain permissions needed by the operator

app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderStartEndpointCustomizer.java, app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/HttpRequestWrapperProcessor.java, app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/SyndesisHeaderStrategy.java, app/connector/support/processor/src/test/java/io/syndesis/connector/support/processor/SyndesisHeaderStrategyTest.java, app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/RestRouteConfiguration.java.mustache, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateApplicationWithRestDSL/RestRouteConfiguration.java
Previously we only filtered out headers with names containing `Syndesis`, `Camel` or `org.apache.camel`. This allowed headers received from outside to be passed on to 3rd parties. To be on the safe side this filters out all headers except for the `Content-Type` header which we need internally when dealing with Syndesis HTTP message body containing both parameters and body (unified data shape).
Fixes #3727
Also one tiny formatting refactor for the generated sources.
=> fix: filter out all headers but Content-Type

app/server/inspector/src/main/java/io/syndesis/server/inspector/JsonInstanceInspector.java, app/server/inspector/src/main/java/io/syndesis/server/inspector/JsonSchemaInspector.java, app/server/inspector/src/test/java/io/syndesis/server/inspector/JsonInstanceInspectorTest.java, app/server/inspector/src/test/java/io/syndesis/server/inspector/JsonSchemaInspectorTest.java
Fixes #4162
Also adds nested Json array support for options in both Json instance and schema inspector.
=> fix: Missing Json instance inspection for basic filter options

app/ui/src/app/core/providers/form-factory-provider.service.ts
* Avoids assigning 'value' as it disrupts the evaluation and selection of
either value, field.value or field.defaultValue
* Fixes if logic.
=> fix(#4756): Make UI honour default values for checkboxes

app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.ts
fixes #4743
@christophd This works but we may want to consider a better bulk update API where I just send the whole integration flow perhaps to figure out data shapes.  This solution will start making the editor feel a bit sluggish I suspect when the flow gets longer.
I also wound up having to fetch metadata for connections as well when I found that I could remove the mismatch warning on the API provider flow by visiting the config page, as that's (before this PR) the only spot when the UI fetches updated data shapes for a connection.
=> feat: fetch updated datashapes and metadata from the backend when changes are done to the integration flow

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/AggregateStepHandler.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteBuilderTest.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/SplitStepHandlerJsonTest.java, app/integration/runtime/src/test/resources/syndesis/integration/filter-after-split.json, app/integration/runtime/src/test/resources/syndesis/integration/filter-in-split.json, app/integration/runtime/src/test/resources/syndesis/integration/inconsistent-split.json, app/integration/runtime/src/test/resources/syndesis/integration/integration.json, app/integration/runtime/src/test/resources/syndesis/integration/multiple-split.json, app/integration/runtime/src/test/resources/syndesis/integration/nested-split.json, app/integration/runtime/src/test/resources/syndesis/integration/split-aggregate.json, app/integration/runtime/src/test/resources/syndesis/integration/split-chain.json, app/integration/runtime/src/test/resources/syndesis/integration/split-to-end.json, app/integration/runtime/src/test/resources/syndesis/integration/subsequent-split.json
Make sure that aggregate step closes corresponding split and all other expression nodes (e.g. filter) that live inside split/aggregate.
With that you can use filter step inside a split/aggregate block.
Fixes #4752 
Also added some more unit tests on split/aggregate scenarios
=> fix: Filter step inside split/aggregate

app/ui/src/app/integration/edit-page/current-flow.service.ts
This improves the previous quick fix to not loose step position index when visiting steps for data shape reconciliation.
=> improve fix (#4768): add start connection broken

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/AggregateStepHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHandler.java
Make sure to set proper variant metadata on data shapes for split and aggregate during meta lookup. This ensures that subsequent lookup calls get the correct variant.
=> fix: Set proper data shape variant metadata for split/aggregate

app/connector/odata/src/main/java/io/syndesis/connector/odata/ODataConstants.java, app/connector/odata/src/main/java/io/syndesis/connector/odata/ODataUtil.java, app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java, app/connector/odata/src/main/java/io/syndesis/connector/odata/verifier/ODataVerifierExtension.java, app/connector/odata/src/main/resources/META-INF/syndesis/connector/odata.json, app/connector/odata/src/test/java/io/syndesis/connector/odata/AbstractODataTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/BaseOlingo4Test.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteNoSplitResultsTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrievalTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataCreateTests.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataDeleteTests.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataUpdateTests.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/server/ODataTestServer.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/verifier/ODataVerifierTest.java, app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-people-data-1.json, app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-people-data-2.json, app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-people-data-3.json
* Clarifies the odata connector certificate option as a SERVER certificate
option rather than client. This option provides facility for adding a
self-signed certificate from internal servers not registered with a known
certificate authority.
* ODataUtil
* Removes skipCertificateCheck and insecure certificate-trust code
* Loads the default keystore from JAVA_HOME that contains mainstream root
certificate authorities. These will allow most legitimate servers on the
internet to be verified and trusted for SSL comms.
* Use SERVER_CERTIFICATE option for any extra certificates to import into
keystore to allow trusting of servers not registered with certificate
authorities
* ODataVerifierExtension
* Removes assumption that SSL server requires a certificate.
* odata.json
* Removes …
=> fix(#4758): Fix use of certificate option in odata connector

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHandler.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandlerTest.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandlerTest.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandlerTest.java
Data shape meta data lookup for split/aggregate keeps all variants of original shapes and adds original shape as variant to the new shape in order to optimize subsequent lookups. 
In addition to that this ensures proper lookup round trip when transforming from collection to element and back again.
=> fix: Make sure to keep original data shape variants on metadata lookup

doc/managing_environments/topics/alerting_sop.adoc, install/addons/syndesis-db-prometheus-rule.yml
After #4674 was implemented, the FuseOnlineDatabaseInstanceDown Prometheus alert rule no longer works. So this PR fixes that issue, but with some caveats that I documented in #4762.
=> fix(monitoring): Fix FuseOnlineDatabaseInstanceDown alert rule

app/connector/sql/src/main/java/io/syndesis/connector/sql/common/JSONBeanUtil.java
When SQL DELETE or INSERT statement is used as a start connection for an integration the connector fails with some class cast exception. 
This was caused by the Camel exchange `in.getBody(List.class)` auto converting the (empty) body to a list as demanded. But the resulting list then causes a class cast exception as the list is not of required type `List<Map<String, Object>>`
This PR makes sure that exchange body is not auto converted to a list.
=> fix: #4811 SQL DELETE as start connection not working

app/pom.xml
No need to use Apache snapshots repository and we need to use the proper JBoss Early Access repository, not the origin-repository.
=> fix: remove Apache snapshots repository and stop using JBoss origin-repository

app/connector/support/maven-plugin/pom.xml, app/connector/support/maven-plugin/src/main/java/io/syndesis/connector/support/maven/GenerateConnectorInspectionsMojo.java, app/connector/support/maven-plugin/src/main/resources/connector-schema.json, app/connector/support/maven-plugin/src/test/java/io/syndesis/connector/support/maven/GenerateConnectorInspectionsMojoTest.java, app/connector/support/maven-plugin/src/test/resources/my-invalid-connector.json, app/connector/support/maven-plugin/src/test/resources/my-test-connector.json, app/connector/support/maven-plugin/src/test/resources/my-unformed-connector.json
* support/shared
* Creates a module that allows distribution of the single connector schema
* connector/*/pom.xml
* Uses maven-remote-resources plugin to bring in the support-shared
module that provides the connector schema
* Uses the yaml-json-validator plugin check the connector plugin is
well-formed then validates against the connector schema.
=> fix(#4718): Validate connector json files

app/ui/src/app/common/button.component.ts, app/ui/src/app/integration/api-provider/creation-page/step-validate/step-validate.component.html, app/ui/src/app/integration/api-provider/creation-page/step-validate/step-validate.component.ts
Kinda; there's a weird issue with `<button disabled="disabled">` that isn't really disabled. Not sure what's going on here. Can someone from @syndesisio/ui-api take a look at this?
Fixes #4437
=> fix: disable `Next` when the given OpenAPI document has errors

app/ui/package.json, app/ui/yarn.lock
* package.json
* post-install.sh
* Remove the older version of codemirror from ng2-codemirror to avoid a
conflict
* index.ts
* Suddenly codemirror linting and highlighting start to work correctly
after reverting this change.
=> fix(#4802) remove ng2-codemirror/node_modules during build

app/ui/package.json, app/ui/yarn.lock
* Aligns the ng2-codemirror dependency codemirror dependency with the main
dependency versioning in package.json. Without this, a node_modules
sub-directory is created in node_modules/ng2-codemirror and causes a
codemirror version conflict. The codemirror/lint.js addon fails to get
imported correctly and the performLint() function is never initialised.
This results in the templater step not linting or highlighting text.
(cherry picked from commit 147bc834a930995fac7d3cd419ff5b5328e64cc9)
```
#	app/ui/package.json
```
Fixes #4802
=> backport #4802

app/connector/google-sheets/src/test/resources/logback-test.xml
Enable debug logging for Google Sheets integration tests to analyze flaky CI builds
=> chore: Enable debug logging for Google Sheets

app/ui/src/app/app.component.html, app/ui/src/app/app.component.ts, app/ui/src/scss/utils/_overrides.scss
This PR applies some minor bug fixes, namely the dropdown toggles in the masthead and the misalignment of the operation names in the operation editor.
Should help close https://github.com/syndesisio/syndesis/issues/4609
=> fix(dropdowns): fix the user/help dropdown toggles

app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/flow-functions.ts, app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.ts
fixes #4866
Also reduces events posted by the template step and reworks the code where we evaluate split/aggregate so the logic is easier to follow.
@christophd lemme know if this change needs any adjusting.
=> fix: tidy up a bit and ensure the aggregate step properly gets the subsequent data shape

doc/sdh/cli/cmd_build.adoc, tools/bin/commands/build, tools/bin/commands/util/maven_funcs
Build script `syndesis build -m <module>` only supported top level modules (ui, server, connector, s2i, meta, integration, extension, common, operator, camel-k, upgrade)
With this PR you can also specify a very specific submodule with `[groupId]:artifactId` to just build a submodule exclusively. This is very useful when running a very specific module before push with style checks and tests enabled.
`syndesis build -m :connector-sql` just builds the SQL connector submodule.
You can also add `-d` dependency option in order to also build all dependent modules that are required for the submodule.
`syndesis build -m :connector-sql -d`
Also documented `--goals` option in the developer user guide.
=> chore: Add syndesis build script option to only build Maven submodules

app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java, app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/AbstractODataCustomizer.java, app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Consumer.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/AbstractODataReadRouteTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteNoSplitResultsTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrievalTest.java, app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-data-klax-location.json, app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-data-klax.json
Fixes #4848
* The connector should be able to handle more complex key predicates that
have subections but also return values rather than entities as their
query results.
* Checks the format and validity of the key predicate, including
* sub predicate, eg. (1)/Location
* ensures quote marks, if required, and brackets
* AbstractODataCustomizer
* Remove assumption of an entity being returned in the result since it can
be a value
* Olingo4Consumer
* Split should handle both entities and values
* Tests for more complex predicates and return of values.
=> fix(#4848): Odata Connector to handle more complex predicates

app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrieval.java
* If split property is set then the result of the query will be a single
entity or value and not a collection. Therefore, the json schema should
remain an Object Schema rather than an Array Schema.
=> backport fix(#4833): modify odata out-data-shape if using split

app/s2i/src/main/resources/settings.xml
* Restores the maven mirror options that are required if building s2i
using a maven mirror, eg. nexus.
=> fix: Partial revert of 53d5aadc2bc5f999fd6c08cd1fd92bf50237068b

doc/connecting/topics/p_create-gmail-connection.adoc, doc/connecting/topics/p_create-google-calendar-connection.adoc, doc/connecting/topics/p_create-google-sheets-connection.adoc, doc/shared/p_create-sf-connection.adoc, doc/shared/p_create-twitter-connection.adoc
Copies caution that was already in place for Google connections, to Twitter and Salesforce. This is the caution that when you go to create a connection, if you see the specific authorization fields, that while you can enter values in these fields and create a connection, it is not recommended.
=> user doc: Adds note to use the Settings page for oauth

app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftConfigurationProperties.java
There's no need to specify the `CaCertFile` on the Kubernetes Client
correct CA certificate file is automatically picked up if present.
Fixes #4854, #4462
=> refactor: cleanup OpenShiftConfigurationProperties

app/ui/src/assets/dictionary/en-GB.json
This updates the version number in the dictionary file from 7.2 to 7.3. 
Without this update, the doc links that are in the code will point to 7.2 doc when they should point to 7.3 doc. So this MUST be backported to the 7.3 release branch.
=> fix: Update version number in dictionary

app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationDeploymentBase.java, app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationDeploymentError.java, app/integration/api/src/main/java/io/syndesis/integration/api/IntegrationErrorHandler.java, app/integration/api/src/main/java/io/syndesis/integration/api/IntegrationProjectGenerator.java, app/integration/project-generator/pom.xml, app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java, app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/ProjectGeneratorTest.java, app/server/controller/src/main/java/io/syndesis/server/controller/StateUpdate.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/BaseIntegrationController.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationOverviewHelper.java, app/server/jsondb/src/main/java/io/syndesis/server/jsondb/dao/IntegrationDeploymentJsonDbDao.java, app/ui/src/app/integration/integration_detail/integration-detail.component.html, app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.html, app/ui/src/app/integration/list/status.component.ts, app/ui/src/assets/dictionary/en-GB.json
This PR fixes #4867 and adds proper error handling to the integration publishing process. 
When the integration project runtime .tar is created potential errors are now propagated as the deployment state marking the deployment as failed. 
In such a situation the s2i build is still triggered (could not avoid this as the .tar is immediately streamed to s2i build) but the initial project generating error is neither lost nor gets overwritten by subsequent integration state change checks.
I made sure that the deploy step is not triggered in this error situation and that the user is informed via the UI that something went wrong.
Also the integration deployment overview now properly reflects the deployment history with previous errors and the actual deployment state (pending indicator).
Also …
=> fix: #4867 Add proper error handling for integration publish process

app/ui/src/app/integration/edit-page/current-flow.service.ts
Input and output shape were mixed up when lookup aggregate step meta data
=> fix: #4905 #4879 Data shapes for aggregate step mixed up

app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.html, app/ui/src/app/integration/edit-page/edit-page.models.ts, app/ui/src/app/integration/edit-page/flow-page.service.ts, app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html, app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
=> fix: prevent the user from moving on until a mapping file is produced

install/operator/pkg/controller/syndesis/syndesis_controller.go
Upgrade didn't terminate because operator loop was interrupted.
=> Fix #4781: fix upgrade termination

app/ui/src/scss/utils/_overrides.scss
This PR updates `pf-c-page__main-section` to use the proper color reference so that the page background isn't different between various views of the app.
Should help close https://github.com/syndesisio/syndesis/issues/4765
=> fix(styles): ensure main page section container applies correct bg color

app/ui/src/app/app.component.html, app/ui/src/scss/utils/_overrides.scss
This PR removes the background image that's visible from the masthead. This change should affect both the productized version as well as upstream Syndesis.
Should help close: https://github.com/syndesisio/syndesis/issues/4953
=> fix(masthead): remove masthead bg image

app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.html, app/ui/src/app/integration/edit-page/edit-page.models.ts, app/ui/src/app/integration/edit-page/flow-page.service.ts, app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html, app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
=> fix: prevent the user from moving on until a mapping file is produced (1.6.x)

app/ui/src/app/integration/edit-page/flow-functions.ts, app/ui/src/app/platform/types/integration/integration.models.ts, app/ui/src/app/store/connection/connection.store.ts, app/ui/src/app/store/connector/connector.store.ts
fixes #4935 
Please make sure that this PR is indeed hiding the thing we want to hide, for reference:
Also this PR adds support to hide connections/steps via setting `hide-from-step-select` to true in the step or connection's metadata map.
@zregvart @christophd I wonder, should I be checking the connector too for this test?  I thought the connection metadata should be enough.
=> fix: hide the log connection in favor of the log step

install/addons/syndesis-db-servicemonitor.yml, install/addons/syndesis-meta-servicemonitor.yml, install/addons/syndesis-server-servicemonitor.yml, install/generator/04-syndesis-db.yml.mustache, install/generator/04-syndesis-meta.yml.mustache, install/generator/04-syndesis-server.yml.mustache, install/syndesis.yml
=> refactor(monitoring): Use targetPort instead of port for Prometheus ServiceMonitor resources

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHandler.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandlerTest.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandlerTest.java
When user defines data shape specifications for a connection (e.g. AMQ, Template, Webhook) the collection/single element meta data variant information is missing on the data shape.
The meta data shape lookup for split/aggregate was not able to handle these specifications and caused errors on Syndesis server. This caused the lookup to return the original non inspected data shapes for split/aggregate leading to inconsistent data shape display in UI.
This PR makes sure that the server is able to handle user defined specifications (json-schema, json-instance) that do not have proper meta data variant information set.
This fix needs to be backported to 1.6.x
=> fix: #4879 Data shape meta lookup (split/aggregate) for user defined specs

app/ui/src/app/integration/edit-page/current-flow.service.ts
This PR handles integrations where no step subsequent to aggregate provides a proper input shape
=> fix: #4969 Handle aggregate step when no input data shape is provided

app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
=> fix: don't trigger data shape reconciliation when the mapper initializes

app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java, app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/AbstractODataCustomizer.java, app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataDeleteCustomizer.java, app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataReadCustomizer.java, app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrieval.java, app/connector/odata/src/main/resources/META-INF/syndesis/connector/odata.json, app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrievalTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataDeleteTests.java
* odata.json
* Configure Delete to have a json-schema model on input in line with
Create and Patch
* ODataMetadateRetrieval
* Breaks shaping out into individual methods for better readability
* Modifies Delete datashape to use json-schema with key-predicate
* ...Customizer
* Delete to extract key predicate from json model
* Read to observe split property to ensure results are formatted in the
expected manner. Without this, Read will not map to Delete using the
DataMapper
* Tests
* Fixes tests so that, when split, results are not assumed to be in a list
as this makes little sense when there is most likely 1 result per message
=> fix(#4889): Redo input DataShape of OData Delete

app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesCustomizer.java, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesSplitResultsCustomizerTest.java
... by returning json bean string instead of single element list. Fixes #4994
=> fix: #4994 Fix data mapping when split option on GoogleSheets is enabled

app/connector/sql/src/main/java/io/syndesis/connector/sql/common/SqlStatementParser.java, app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlConnectorInputParamTest.java, app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlConnectorQueryTest.java, app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlConnectorTest.java, app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlStartConnectorTest.java, app/connector/sql/src/test/java/io/syndesis/connector/sql/common/SqlParserTest.java, app/connector/sql/src/test/java/io/syndesis/connector/sql/util/SqlConnectorTestSupport.java
This PR adds support for predicates like (!=,>,<,>=,<=,between ... and) to be used in SQL select statements in combination with parameter placeholders (:#param)
Fixes #5016
=> fix: #5016 Support predicates in combination with parameters in SQL select

doc/connecting/topics/p_add-google-sheets-connection-get-sheet-values.adoc
This adds a description of a known 7.3 problem in Google Sheets connector, get sheet values action. 
Setting of Max Results is ignored when Split Results is set to No. This is fixed in 7.4. 
Christoph approved the wording.
=> user doc: Add description of known issue

app/ui/src/scss/utils/_overrides.scss
This PR updates the background color of the masthead to align with PF4 spec.
Before:
After:
=> chore(bgcolor): update header bg color to path latest pf4

app/pom.xml
This is the version used in 2.21 version of the Fuse fork[1].
[1] https://repository.jboss.org/nexus/content/groups/ea/org/apache/camel/camel-parent/2.21.0.fuse-730072/camel-parent-2.21.0.fuse-730072.pom
=> chore: upgrade Spring Boot to 1.5.17.RELEASE

app/connector/google-sheets/pom.xml
Make sure 2.0.16.RELEASE is used as managed version 2.0.15 is having security issues
=> chore: Ensure spring security oauth2 2.0.16

doc/sdh/cli/cmd_release.adoc, tools/bin/commands/release
This adds `--skip-tests` and enables by default strict checksum policy (can be disabled with `--no-strict-checksums`.
This should speed up the release if run against the same local repository and with `--skip-tests`.
=> chore: release speed up

app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderStartEndpointCustomizer.java, app/connector/http/pom.xml, app/connector/http/src/main/java/io/syndesis/connector/http/HttpConnectorCustomizer.java, app/connector/http/src/main/resources/META-INF/syndesis/connector/http4.json, app/connector/http/src/main/resources/META-INF/syndesis/connector/https4.json, app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/HttpMessageToDefaultMessageProcessor.java, app/connector/webhook/src/main/java/io/syndesis/connector/webhook/WebhookConnectorCustomizer.java, app/connector/webhook/src/test/java/io/syndesis/connector/webhook/WebhookConnectorCustomizerTest.java
fixes #5096
This PR add Http request wrapper processors to Http based connectors in order to replace HttpMessage with DefaultMessage on the exchanges.
This is because the HttpMessage implementation raises stream closed errors when integration frequently replaces message bodies in out messages (e.g. with data mapper)
=> fix: #5096 Prevent stream already closed errors on Http based connectors

app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizer.java, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizerTest.java
Google Sheets update customizer now able to also handle Json Array String as message body. Before it was only handling list typed body. When doing a split in front of the connector we are provided with a Json String body representing the values to update.
=> fix: #5110 Add support for Json array Strings in Google Sheets

tools/bin/commands/build
Fix #5156 
This should at least replace the failing scripts with equivalent calls that work with recent versions of Camel K.
=> Fix #5156: update scripts for newer versions of camel k

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/action/DynamicActionSalesforceITCase.java
The meta data lookup for connection actions uses enums as property suggestions. This is even when only one single value has been added as property suggestion.
This PR changes the meta data lookup to only set the default value for the property when a single suggestion value is provided by the meta data retrieval. This has the effect to render a normal text field in the UI forms instead of having a single element drop down.
This way you can add a simple default value for a property as meta data lookup result based on a single value property suggestion.
=> chore: Use simple text field for single value property suggestion on meta lookup

app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java, app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/AbstractODataCustomizer.java, app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/json/ClientComplexValueSerializer.java, app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/EdmTypeConvertor.java, app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataExtension.java, app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrieval.java, app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetadata.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/BaseOlingo4Test.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/ODataSerializerTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/AbstractODataReadRouteTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrievalTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/server/ODataServerConstants.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/server/ProductsEdmProvider.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/server/Storage.java, app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-airport-data-1.json, app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-data-klax-location.json, app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-data-klax.json, app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-people-data-1.json, app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-people-data-2.json, app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-people-data-3.json, app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-1-with-count.json, app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-1.json, app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-2-with-count.json, app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-2.json, app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-3-with-count.json, app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-3.json, app/connector/odata/src/test/resources/io/syndesis/connector/odata/test-complex.json
* Support returning full odata metadata by overriding the http ACCEPT
header
* ClientComplexValueSerializer
* Correct implementation to return correctly formatted json object and
sub-objects
* EdmTypeConvertor
* OdataDataMetadata
* Extends to generate property metadata for property objects of complex
types
* ODataMetadataRetrieval
* Extend the json schema returned by the output datashape to allow for
complex types
* Updates test suite to provide complex types & values in test server and
tests to check accordingly.
=> fix(#5151): OData connector to correctly support EDM Complex Values

app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/AbstractGoogleSheetsTestSupport.java, app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/SheetsSpreadsheetsValuesIntegrationTest.java, app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/stream/SheetsStreamConsumerIntegrationTest.java
This PR separates test spreadsheet creation from pushing initial test data to the same spreadsheet. Before this was handled in parallel on the mocked test server and this caused some racing conditions. This could lead to messed up correlation ids on the test server and one of the operations did not get any response.
=> fix: #5014 Unstable Google Sheets integration tests

install/generator/04-syndesis-server.yml.mustache, install/generator/04-todo-example.yml.mustache, install/syndesis.yml
@heiko-braun if we're going to rebuild syndesis, we may add some markers so we can automatically remove the camel k stuff from the openshift online templates.
=> Related to #5194: add marker for camel k resources

doc/integrating-applications/topics/p_using-data-mapper-to-process-collections.adoc
Based on a comment from Andrej Smigala, I revised the section about mapping from a collection to a collection, clarifyin when collection fields are available for individual mapping, and what the runtime behavior is.
=> user doc: Rewrote section about mapping from collection to collection

app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsConnector.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsConnectorHelper.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesCustomizer.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsMetaDataExtension.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsMetadataRetrieval.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizer.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/meta/GoogleSheetsMetaDataHelper.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/meta/GoogleValueRangeMetaData.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/CellCoordinate.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/RangeCoordinate.java, app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsMetadataAdapterTest.java, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsNamedColumnsTest.java, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/model/CellCoordinateTest.java, app/connector/google-sheets/src/test/resources/meta/column_names_metadata.json, app/connector/google-sheets/src/test/resources/meta/column_names_split_metadata.json, app/connector/support/verifier/src/main/java/io/syndesis/connector/support/verifier/api/PropertyPair.java
This PR adds a meta data lookup for Google Sheets connector in order to provide custom column names. By default column names are simply named with their column letter (A,B,C,D). With the meta data lookup you can fetch a header row that contains custom column names. You have to specify the row number of the header row.
Next property definition step fetches the column names.
So you can use those names in data mapper which is more comfortable than just using A,B,C,D. See following source document using the custom column names vs. the target using the default column names.
Users can also skip fetching the header row and customize the names manually or just use the default names.
=> chore: Enhance google-sheets meta data with custom column names

app/s2i/pom.xml, app/s2i/src/main/assembly/repository.xml, app/ui/package.json, app/ui/pom.xml
We need the ability to be able to run the yarn build through a proxy.    I've added two profiles, proxy and noproxy, to app/ui/pom.xml.      
Have also added a profile to app/s2i for the inclusion of a necessary repository.xml and the license plugin.
=> Add a proxy profile for doing yarn build behind a firewall, add repository.xml

app/common/model/src/main/java/io/syndesis/common/model/choice/FlowOption.java, app/common/model/src/main/java/io/syndesis/common/model/expression/RuleBase.java, app/common/model/src/main/java/io/syndesis/common/model/filter/FilterRule.java, app/common/model/src/main/java/io/syndesis/common/model/integration/StepKind.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/ChoiceStepHandler.java, app/integration/runtime/src/main/resources/META-INF/services/io.syndesis.integration.runtime.IntegrationStepHandler, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/ChoiceStepHandlerTest.java
Integration runtime is able to handle content based router step with Camel choice-when-otherwise EIP.
The CBR step is configured with a condition expression and a flow identifier. The choice delegates to flows based on "direct:flowId" endpoint URI. The condition expression can be a simple language expression (like in advanced filter e.g. `${body} contains 'Hello'`) or a rule based expression using the properties path, operator and value (like in basic filter).
In case a default flow is configured on the step the otherwise branch in the choice delegates to this flow by default. When no default flow is configured a simple log message is done stating that no contend based route did actually match for the message. This log message is using the same pattern as the log step and should be …
=> Fix #5193 Add choice step handler representing content based router

app/integration/bom/pom.xml
spring-boot-dependencies brings in an old version of jackson-databind, we should make sure it brings in 2.8.11.3
=> ENTESB-9863 Upgrade jackson-databind version to 2.8.11.3 in integration-bom

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/edit-page.models.ts, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
This PR optimizes the number of requests to the backend regarding step meta data lookups.
In my opinion we can remove the fetch meta data calls from reconcile cycles completely. These calls are done explicitly for the currently selected step when going through the process of setting the configured properties for the step.
Fetch meta data calls for current step: 
https://github.com/syndesisio/syndesis/blob/b5d006c58b60f6df5b0430a912fadb375affa09f/app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts#L159
and
https://github.com/syndesisio/syndesis/blob/b5d006c58b60f6df5b0430a912fadb375affa09f/app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts#L223
I think these two calls (made only for the current selected step) are sufficient …
=> #5181 Removed fetch metadata calls from reconcile cycles

app/connector/odata/pom.xml, app/connector/odata/src/main/java/io/syndesis/connector/odata/ODataUtil.java, app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java, app/connector/odata/src/main/java/io/syndesis/connector/odata/verifier/ODataVerifierExtension.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/verifier/ODataVerifierTest.java
* ODataUtil
* Function for removing slashes
* Removes trailing slashes on setting of the base url
* ODataVerifierExtension
* Removes trailing slashes before verifying the metadata url
* Tests for both code changes
=> fix(5108): Ensure trailing slashes are removed from odata base url

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHelper.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandlerTest.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandlerTest.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandlerTest.java
This PR provides a bulk operation for UI to lookup step descriptors with updated data shapes (e.g. adapted shapes for split/aggregate). The backend operation receives the complete list of steps in an integration and performs descriptor lookup for each step. The result is a list of steps with maybe updated data shapes in action descriptors.
Each step descriptor lookup is provided with a dynamic meta data that is created by the respective step meta data handler depending on the step kind.
This way we optimize the number of requests sent form UI frontend to the server backend and improve the robustness of the UI editor.
=> #5181 Add bulk operation for step descriptor lookup

app/ui/src/app/core/providers/integration-support-provider.service.ts, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts, app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts, app/ui/src/app/platform/types/integration/integration-support.service.ts, app/ui/src/app/platform/types/integration/integration.api.ts, app/ui/src/app/platform/types/integration/integration.models.ts
Use new bulk operation for step descriptor lookup and optimize reconcile calls when integration changes.
The reconcile call is only executed when a step changes its meta data (which is only the case when a step is edited and changes its configured properties and its meta data) and when a step is removed. When reconcile is called the UI uses a bulk operation on server backend to send all steps and receive all steps with maybe adapted data shapes in one single operation.
=> chore: #5181 UI uses backend bulk operation for step descriptor lookup

app/common/model/src/main/java/io/syndesis/common/model/integration/Step.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/ChoiceMetadataHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHelper.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/ChoiceMetadataHandlerTest.java
Content based router (=choice) step adapts input/output data shapes from previous and subsequent steps during step descriptor meta data lookup.
Also moved some utility methods to step model class
Belongs to #5193
=> feat: Add choice step meta data handler

doc/connecting/topics/p_adding-amqp-connection-middle.adoc
Per FUSEDOC-3159, in the doc for the AMQP connector, when the user selects the Request Response Using Messages action, I removed the content for these fields:
- Named Reply To 
- Persistent checkbox
- Response Time Out
And I added content for this field:
- Durable Subscription ID
=> user doc: Remove incorrect config options for AMQP request/response

doc/connecting/topics/p_register-with-google.adoc
This Important note tells the user to create a new Google client application in order to obtain credentials that have the refresh token. Zoran, Torsten, and Christoph approved the wording.
=> user doc: Add note about OAuth limitation on connections to Google apps

app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/AuthenticationCustomizer.java, app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/AuthenticationType.java, app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/auth/apikey/ApiKey.java, app/connector/rest-swagger/src/main/resources/META-INF/syndesis/connector/rest-swagger.json, app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/AuthenticationCustomizerTest.java, app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/DescriptorTest.java, app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/RestSwaggerConnectorIntegrationTest.java
In a call a spade a spade decision, the `parameter` authentication method was renamed to `apiKey` to decrease the cognitive load and fix issues where the terminology clashes like in #5369.
Fixes #5369
=> refactor: rename parameter to apiKey

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/ActivityTrackingInterceptStrategy.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/ChoiceStepHandlerTest.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/FilterStepHandlerTest.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/SplitStepHandlerTest.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/logging/ActivityLoggingTest.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/logging/ActivityLoggingWithSplitTest.java
Ref #5213 
Fixes #4181 
As soon as the integration route uses blocks like `filter`, `choice` the activity logging is not working as expected. We see duplicate step activity entries and inconsistent activities as reported in #4181 
This PR fixes that activity logging by not reading the step id from exchange header anymore ([ActivityTrackingInterceptStrategy](https://github.com/syndesisio/syndesis/blob/13a5c8e8afe7de7042952707cd21d6293321cc21/app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/ActivityTrackingInterceptStrategy.java)). The stepId header is overwritten by nested steps that live inside blocks like filter and choice and this is why the logs get inconsistent. 
Instead use the static step id that the surrounding pipeline was created with. This ensures …
=> [fix] Avoid duplicate activity log entries

app/integration/runtime-camelk/readme.adoc
Updated camel-k-runtime to 0.3.2 (i.e. camel-k operator to 0.3.3).
=> Fix 5223: [camel-k] support api client

app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/BaseSwaggerConnectorGenerator.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerUnifiedShapeConnectorGenerator.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/SwaggerUnifiedShapeGeneratorExampleTests.java
When editing the OpenAPI document it is possible that the current operation ID algorithm of using the base of `operation-` and adding the monolithically increasing number (`operation-NNN`) will generate the same operation ID of a removed operation and in doing so inheriting that flow.
This uses random UUID instead so that two identical operation IDs cannot be generated.
Fixes #5310
=> fix(server): instead of `operation-NNN` use random UUID

app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/prometheus-config.yml, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/prometheus-config.yml, install/generator/01-header.yml.mustache, install/generator/02-syndesis-image-streams.yml.mustache, install/generator/04-syndesis-server.yml.mustache, install/generator/04-teiid-komodo-server.yml.mustache, install/generator/syndesis-template.go, install/syndesis.yml
Adds a template parameter `DATAVIRT_ENABLED` that corresponds to replica count for the `komodo-server` Pod. Having `0` by default disables (it's not running) and setting to `1` enables the Teiid Komodo server.
Fixes #5432
=> chore(install): make Data virtualization install optional and disabled by default

app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/ServiceNowMetadataRetrieval.java
MetadataRetrieval class needs to be public so factory finder mechanism can find and instantiate it in ConnectorEndpoint
=> fix: #5430 Servicenow connector meta data retrieval adapter lookup

install/generator/04-teiid-komodo-server.yml.mustache, install/syndesis.yml
This fixes the inclusion of DATAVIRT_ENABLED template parameter in the syndesis.yml template. The value needs to be inserted as a number and using double curly braces (`${{DATAVIRT_ENABLED}}`) makes sure that this is done.
For mustache template the delimiter needs to be changed so `{{...}}` is not interpreted so it's first changed to `((..))` and later changed back to `{{..}}`.
Fixes #5442
Thanks @astefanutti for the fix for this :+1:
=> fix: DATAVIRT_ENABLED parameter use in sydesis.yml

.pre-commit-config.yaml, install/operator/Gopkg.lock, install/operator/Gopkg.toml, install/operator/check-dep.sh
This upgrades operator-sdk to 0.8.0 and adds a pre-commit hook to check that the Gopkg.lock is in sync with Gopkg.toml.
=> Upgrade operator-sdk to 0.8.0

install/operator/Dockerfile, install/operator/Gopkg.lock, install/operator/cmd/syndesis-operator/main.go, install/operator/pkg/controller/syndesis/syndesis_controller.go, install/operator/pkg/syndesis/action/startup.go
This is based on #5445 (so take a look at that first)
Right now the operator is logging several log lines per second during the reconciliation, this adds support for specifying log level via command line parameter.
**HEADSUP: the `-template` parameter was renamed to `--template` this is due to the use of `github.com/spf13/pflag` instead `flag` package.**
cc @cunningt @djcoleman @orpiske
=> Cleanup operator logging

app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsMetadataRetrieval.java, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsRetrieveValuesCustomizer.java, app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsRetrieveValuesCustomizerTest.java
This PR adds a new google-sheets connector action that enables an integration to read values from a spreadsheet in the middle of an integration. Before the read values action was only available as a start connection in an integration
Fixes #5132
=> feat: Add Google Sheets get values operation as middle step

install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go, install/operator/pkg/openshift/template/templateprocessor.go, install/operator/pkg/syndesis/action/action.go, install/operator/pkg/syndesis/action/install.go, install/operator/pkg/syndesis/action/upgrade.go, install/operator/pkg/syndesis/action/upgradebackoff.go, install/operator/pkg/syndesis/action/upgradelegacy.go, install/operator/pkg/syndesis/configuration/util.go, install/operator/pkg/syndesis/legacy/controller.go, install/operator/pkg/syndesis/template/install.go, install/operator/pkg/util/resources.go, install/operator/pkg/util/resources_test.go
It was simple to implement this, thought now I'm faced with an issue and would like some help, so halp!
When I create a Syndesis object like:
```yaml
apiVersion: "syndesis.io/v1alpha1"
kind: "Syndesis"
metadata:
name: "example"
spec:
addons:
komodo:
```
I get this lovely error:
```
"level":"error","ts":1558512713.3689954,"logger":"controller","msg":"Error reconciling","action":"*action.installAction","phase":"Installing","error":"failed to decode json data with gvk(apps.openshift.io/v1, Kind=DeploymentConfig): v1.DeploymentConfig.Spec: v1.DeploymentConfigSpec.Replicas: readUint32: unexpected character: \ufffd, error found in #10 byte of ...|eplicas\":\"1\",\"select|..., bigger context ...|ure\"},\"name\":\"komodo-server\"},\"spec\":{\"replicas\":\"1\",\"selector\":{\"app\":\"syndesis\",\"s …
```
=> Faux addons feature in the operator

app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html, app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.ts, app/ui/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.html, app/ui/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.ts
Users can change the order of conditions in a conditional flows step. Also when the step configure page is left the step reconciles its flows in order to avoid left overs
=> feat: UI is able to reorder conditional flows

app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlMetadataRetrieval.java, app/connector/sql/src/main/java/io/syndesis/connector/sql/common/JSONBeanUtil.java, app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlConnectorCustomizer.java, app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlConnectorBatchUpdateTest.java, app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlMetadataAdapterTest.java, app/connector/sql/src/test/resources/sql/name_sql_metadata.json, app/connector/sql/src/test/resources/sql/name_sql_update_metadata.json, app/connector/sql/src/test/resources/sql/name_sql_update_no_param_metadata.json
Adds batch update support to sql connector for INSERT, UPDATE, DELETE
New collection support in Syndesis is used to pass a list of parameter sets to the connector. The updates will be executed as batch using prepared statements.
Fixes #5158
=> feat: Support batch update in SQL connector

app/connector/support/processor/pom.xml, app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/HttpRequestWrapperProcessor.java, app/connector/support/processor/src/test/java/io/syndesis/connector/support/processor/HttpRequestWrapperProcessorTest.java
When Camel Servlet component binds query parameters to the Camel message headers it uses the configured `HttpHeaderFilterStrategy`, and in Syndesis this is the `SyndesisHeaderStrategy` which will bind only the `Content-Type` header and will not bind the query parameters to Camel message headers.
With this in addition to Camel message headers the query parameter value is fetched from the `HttpServletRequest` if it is present in the Camel message headers, and when the Servlet component is used this is usually the case.
This also refines the support for query parameters allowing multiple query parameter values to be set for the parameter value making the parameter value a JSON array.
Fixes #5152
=> fix(connector): set parameters from HTTP request

app/connector/odata/src/main/java/io/syndesis/connector/odata/ODataUtil.java, app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java, app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataPatchCustomizer.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/AbstractODataTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataUpdateTests.java
* ODataPatchCustomizer
* Format the key predicate passed in by the data shape, quoting or not
depending on whether integer or string
* ODataUtil
* Share the formatKeyPredicate function
* Adds test that updates the reference odata service, which uses string
key predicates.
=> fix(5241): Quote string used as key predicate for update

app/ui-angular/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html, app/ui-angular/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.ts, app/ui-angular/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.html, app/ui-angular/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.ts, app/ui-angular/src/app/integration/edit-page/step-configure/step-configure.component.html, app/ui-angular/src/app/integration/edit-page/step-configure/step-configure.component.ts
Fixes #5489 #5491 #5484 #5487 #5488
Ref #5216 
Avoid loosing changes when applying configuration changes and directly opening a conditional flow before hitting the `Done` button.
Basically when hitting the `Apply` button things get persisted in the conditional step configuration and the flow gets saved, too.
=> [fix] Auto save changes when applying conditional flows config

app/integration/bom/pom.xml, app/pom.xml, app/ui-angular/package.json, app/ui-angular/yarn.lock, app/ui-react/packages/atlasmap-assembly/package.json, app/ui-react/yarn.lock
Hi @riccardo-forina, it seems [this yarn.lock](https://github.com/syndesisio/syndesis/compare/master...igarashitm:atlasmap-1.40.0-alpha2?expand=1#diff-ea95db000913ed9454fdab13745b9f2e) was updated once I run yarn add with [this package.json](https://github.com/syndesisio/syndesis/compare/master...igarashitm:atlasmap-1.40.0-alpha2?expand=1#diff-35b3a34961dde4306d53b3a854bc5cee), am I doing right?
=> chore: Update to AtlasMap 1.40.0-alpha2

app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json
I edited the Google Sheets json file so that values for "displayName" always have a lowercase for appropriate words after the first word. This should make all field names consistent. 
Christoph, could you please check this?
=> Edits field names to consistently lowercase words after the first word

.circleci/config.yml, app/ui-angular/pom.xml, app/ui-react/pom.xml, install/generator/03-syndesis-ui.yml.mustache, install/generator/04-syndesis-oauth-proxy.yml.mustache, install/syndesis.yml
This switches the `syndesis/syndesis-ui` image to React and publishes the Angular UI as `syndesis/syndesis-ui-legacy`. The fabric8 Maven plugin configuration was changed to reflect that and the CircleCI configuration was updated to build the two versions as separate jobs.
OAuth proxy configuration was switched to the configuration needed for the React UI.
Ref #5426
=> chore: switch the syndesis-ui image to React

install/addons/syndesis-legacy-ui-serviceaccount.yml, install/addons/syndesis-legacy-ui.yml
Angular UI can be installed via:
```shell
$ oc create -f syndesis-legacy-ui.yml
$ oc create -f syndesis-legacy-ui-serviceaccount.yml
$ oc new-app syndesis-legacy-ui \
-p ROUTE_HOSTNAME=syndesis-legacy.$(minishift ip).nip.io \
-p OPENSHIFT_PROJECT=$(oc project -q) \
-p OPENSHIFT_OAUTH_CLIENT_SECRET=$(oc sa get-token syndesis-oauth-client-legacy) \
-p SAR_PROJECT=$(oc project -q)
```
Ref #5426
=> chore: add addon for installing legacy UI

app/ui-angular/src/app/integration/edit-page/current-flow.service.ts
Makes sure that the integration held in the `CurrentFlowService` is updated if it has been updated on the backend.
Fixes #5332
=> fix(ui): update integration on changes

app/common/model/src/main/java/io/syndesis/common/model/integration/Flow.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/IntegrationActivityTrackingPolicyFactory.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java, app/ui-angular/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.html, app/ui-angular/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.scss, app/ui-angular/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.ts, app/ui-angular/src/app/integration/api-provider/operations-page/integration-api-provider-operations-list.component.ts, app/ui-angular/src/app/integration/edit-page/current-flow.service.ts, app/ui-angular/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html, app/ui-angular/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.ts, app/ui-angular/src/app/integration/edit-page/flow-view/flow-view.component.ts, app/ui-angular/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.ts, app/ui-angular/src/app/platform/types/integration/integration.models.ts
Fixes #5515
PR separating conditional flows from api provider operation flows in top level navigation and makes sure that navigation to/from primary flow is working for api provider integrations.
This is done in Angular code base but it may give some hints and ideas to solve this for the react code base, too.
=> fix: Support conditional flows in API provider integrations

app/ui-angular/src/app/integration/list/list.component.html, app/ui-angular/src/app/store/integration/integration.service.ts
Transforms the integration so that `Integration.flows` always returns a value. In case when the `flows` is `undefined` or `null` the value returned will be an empty array.
Fixes #4977
I'm not sure about the failure cases for this, i.e. when `Object.getOwnPropertyDescriptor` will return something unexpected (i.e. something that doesn't have `.value`) or the reference received from `Object.getOwnPropertyDescriptor` can change over time, so we end up with consistency errors between what was set and what this getter returns.
I've also found an inconsistency with the display of the start icon in the integration list vs integration details pages.
Can you take a look @gashcrumb @kahboom @riccardo-forina
=> fix(ui): make sure `Integration.flows` is never null

doc/connecting/topics/p_adding-fhir-connection-create.adoc, doc/connecting/topics/p_adding-fhir-connection-delete.adoc, doc/connecting/topics/p_adding-fhir-connection-patch.adoc, doc/connecting/topics/p_adding-fhir-connection-update.adoc
Updated the description of the results of various actions to add the name of the field that contains the resource ID. Rafal approved these updates. This is related to 
https://github.com/syndesisio/syndesis/pull/555
=> user doc: Add name of MethodOutcome field, id.idPart, that contains resource ID

app/ui-react/syndesis/package.json
Increasing the memory size to fix build failures on CI. Setting this in `.env` file is not helping, probably because it's read from Create React App at too late to influence `node` memory.
Fixes #5468
=> fix(build): increase `craco build` memory to 2GB

install/generator/04-syndesis-db.yml.mustache, install/syndesis.yml
Fix for #5528, now creating a sampledb schema - and creating the tables and functions inside of this schema.
=> fix for 5528 - Wrong schema in the default postgres connection

app/connector/email/src/main/resources/META-INF/syndesis/connector/email-send.json
* The protocol value is set programmatically using the configuredProperties.
However, the UI reads the hidden & required metadata and expects the
control to contain a value. By setting the default value this satisfies
the requirements.
=> fix(5560): Ensure a default value is set for email-send's protocol
