app/ui/src/app/common/modal/modal.component.html, app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-page.component.ts, app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.html, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts, app/ui/src/app/integration/edit-page/edit-page.component.html, app/ui/src/app/integration/edit-page/edit-page.component.ts, app/ui/src/app/integration/edit-page/flow-page.service.ts, app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html, app/ui/src/app/integration/edit-page/integration-basics/integration-basics.component.ts, app/ui/src/app/integration/integration.module.ts, app/ui/src/assets/dictionary/en-GB.json
=> fix: add a cancel prompt modal for the editor

app/ui/src/app/integration/edit-page/edit-page.component.ts
=> fix: avoid cancel prompt

.gitignore, app/common/util/src/main/java/io/syndesis/common/util/openapi/OpenApiHelper.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/BaseSwaggerConnectorGenerator.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelper.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGeneratorTest.java, app/ui/src/app/common/openapi/review/review.component.ts, app/ui/src/app/customizations/api-connector/api-connector.effects.ts, app/ui/src/app/customizations/api-connector/api-connector.models.ts, app/ui/src/app/customizations/api-connector/api-connector.reducer.ts
Adds more robustness to the OpenAPI parsing.
Fixes #4542
=> fix(server): robustly parse OpenAPI documents

app/ui/src/app/integration/edit-page/flow-functions.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
=> fix: hide a few steps at the finish spot

app/ui/src/app/app.component.ts, app/ui/src/app/integration/edit-page/flow-page.service.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.ts
also fix annoying change detection error
fixes #4485
=> fix: Ensure the user is brought back to the right spot when canceling

app/common/util/src/main/java/io/syndesis/common/util/Json.java, app/connector/timer/pom.xml, app/connector/timer/src/main/resources/META-INF/syndesis/connector/timer.json, app/connector/timer/src/test/java/io/syndesis/connector/timer/TimerIntegrationTest.java
This should give us a more usable value for the cron expression in the timer.
Fixes #4491
=> refactor(connector): update timer's `defaultValue`

install/operator/deploy/old/syndesis.1.5.6.csv.yaml, install/operator/deploy/syndesis-crd.yml, install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go, install/operator/pkg/syndesis/action/checkupdates.go, install/operator/pkg/syndesis/action/initialize.go, install/operator/pkg/syndesis/action/install.go, install/operator/pkg/syndesis/action/startup.go, install/operator/pkg/syndesis/action/upgrade.go, install/operator/pkg/syndesis/action/upgradebackoff.go, install/operator/pkg/syndesis/action/upgradelegacy.go, tools/bin/commands/util/openshift_funcs, tools/bin/install-syndesis
=> chore(operator): Revert renaming from syndeses to syndesises for compat reasons.

app/pom.xml
=> fix(build): restore git commit ID in META-INF/MANIFEST.MF

tools/upgrade/common.sh, tools/upgrade/migration/resource/any/02_db_metrics_config_map.sh
=> chore: Make creation of metrics configmap idem potent

app/ui/src/app/integration/edit-page/flow-functions.ts
=> fix: ensure step IDs are not left undefined

app/connector/timer/src/main/resources/META-INF/syndesis/connector/timer.json
=> fix: add quartz2 dependency for timer connector

install/addons/syndesis-db-dashboard.yml
=> fix(monitoring): Syndesis DB Grafana dashboard should be resilient to pod restarts

app/ui/src/app/integration/edit-page/current-flow.service.ts
fixes #4742
Will not handle nested split/aggregate though, trying to remove an outer split will result in an orphaned aggregate.
=> feat: remove the corresponding aggregate step if a split step is removed

app/ui/src/app/core/providers/integration-support-provider.service.ts, app/ui/src/app/integration/list/tag-cicd-modal.component.ts, app/ui/src/app/platform/types/integration/integration-support.service.ts, app/ui/src/app/platform/types/integration/integration.api.ts
=> fix: use the right endpoint for deleting environment names

app/ui/src/app/integration/edit-page/current-flow.service.ts
Quick fix for #4768 as QE is blocked by this
=> fix (#4768): add start connection not working

install/operator/pkg/syndesis/operation/attach.go
Fix #4781
There was an error in the selector used (field vs label) and when calling the list function at the end of the upgrade process.
=> Fix #4781: fix bug in upgrade completion

app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-page.component.ts
=> fix: trigger a save when switching flows

app/connector/fhir/src/main/resources/META-INF/syndesis/connector/fhir.json
Follow up for 9f458fe74c45f9eff377ac355d5a99c683520ea4
=> Fix ordering of FHIR action properties

app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/LocalResolver.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/UnifiedXmlDataShapeGeneratorShapeValidityTest.java, app/server/api-generator/src/test/resources/xsd/2001/XMLSchema.xsd, app/server/api-generator/src/test/resources/xsd/2001/xml.xsd, app/server/api-generator/src/test/resources/xsd/XMLSchema.dtd, app/server/api-generator/src/test/resources/xsd/datatypes.dtd
Makes sure that we're not trying to load remote resources when
validating XML schema in the tests.
=> fix: offline XML Schema validation

app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
=> fix: ensure the data mapper host area uses the right height in the api provider editor

app/integration/bom/pom.xml, app/pom.xml, app/ui/package.json, app/ui/yarn.lock
Release Notes:
https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-1.39.5
https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-1.39.4
=> chore: Update to AtlasMap 1.39.5

tools/bin/commands/build, tools/bin/syndesis
=> Graceful GOPATH checks

doc/connecting/topics/p_add-google-sheets-connection-add-chart.adoc, doc/connecting/topics/p_add-google-sheets-connection-add-pivot-table.adoc
Updates based on review by Matej.
=> user doc: Updates to doc for Sheets connector based on QE review

doc/shared/p_register-with-sf.adoc, doc/shared/p_register-with-twitter.adoc, doc/tutorials/master.adoc, doc/tutorials/topics/as_amq2api-intro.adoc, doc/tutorials/topics/as_sf2db-create-integration.adoc, doc/tutorials/topics/as_sf2db-intro.adoc, doc/tutorials/topics/as_t2sf-intro.adoc, doc/tutorials/topics/p_amq2api-add-damage-reporter-step.adoc, doc/tutorials/topics/p_amq2api-add-mapping-step.adoc, doc/tutorials/topics/p_amq2api-confirm-works.adoc, doc/tutorials/topics/p_amq2api-create-custom-step.adoc, doc/tutorials/topics/p_amq2api-name-and-publish.adoc, doc/tutorials/topics/p_amq2api-upload-todo-app-icon.adoc, doc/tutorials/topics/p_sf2db-add-mapping-step.adoc, doc/tutorials/topics/p_sf2db-choose-finish.adoc, doc/tutorials/topics/p_sf2db-choose-start.adoc, doc/tutorials/topics/p_sf2db-confirm-works.adoc, doc/tutorials/topics/p_sf2db-name-and-publish.adoc, doc/tutorials/topics/p_t2sf-add-filter-step.adoc, doc/tutorials/topics/p_t2sf-add-mapping-step.adoc, doc/tutorials/topics/p_t2sf-choose-finish.adoc, doc/tutorials/topics/p_t2sf-confirm-working.adoc, doc/tutorials/topics/p_t2sf-name-and-publish.adoc
Changed "Done" to "Next" as needed. I also updated behavior after publishing.
=> user doc: Update tutorials for combo of step and connection cards.

app/ui/package.json, app/ui/yarn.lock
Ref:
- https://github.com/patternfly/patternfly/issues/1167
- https://github.com/snapappointments/bootstrap-select/issues/2199
=> fix: force bootstrap-select version to 1.13.6

app/integration/runtime-camelk/pom.xml
=> [camel k] cannot find atlas component

app/ui/src/app/common/button.component.ts, app/ui/src/app/integration/api-provider/creation-page/step-validate/step-validate.component.html, app/ui/src/app/integration/api-provider/creation-page/step-validate/step-validate.component.ts
Fixes #4437
(cherry picked from commit 9b8e3e8)
(cherry picked from commit 0b49944)
=> backport #4437

app/integration/runtime-camelk/pom.xml
=> [camel k] cannot find atlas component #4834

app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java, app/server/controller/src/test/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandlerTest.java
=> AtlasMap is unable to find mapping 

app/ui/src/app/integration/edit-page/current-flow.service.ts
relates to stuff seen in #4840
@zregvart @lburgazzoli FYI
=> fix: suppress empty backend call to avoid HTTP 400

app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.html, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/edit-page.models.ts, app/ui/src/app/integration/edit-page/flow-page.service.ts
=> fix: ensure the flow page service state is set properly and some refinements

doc/integrating-applications/topics/as_trigger-integrations-with-api-calls.adoc, doc/integrating-applications/topics/p_create-api-provider-integration.adoc, doc/integrating-applications/topics/p_create-integration-operation-flows.adoc, doc/integrating-applications/topics/r_requirements-for-api-provider-integrations.adoc
This merge contains updates based on Zoran's review. I'm going to make this available for a QE review, but @KurtStam, @gashcrumb , and @riccardo-forina , your review would also be appreciated. This draft is up to date: 
https://docs.google.com/document/d/11Hp3c4fQXFHZ_exhE3UHR2Xn_xvYXySQXdJdNq7mAfA/edit?usp=sharing
=> Fusedoc 2988 apiprovider u iupdates

app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.html, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/edit-page.models.ts, app/ui/src/app/integration/edit-page/flow-page.service.ts
=> fix: ensure the flow page service state is set properly and some refinements (1.6.x)

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandlerTest.java
=> Fixes #4789, fixed public API deployment search when stopping integrations

app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/flow-functions.ts, app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.ts
=> fix: tidy up a bit and ensure the aggregate step properly gets the subsequent data shape (1.6.x

doc/shared/p_register-with-sf.adoc
(cherry picked from commit 94476d8a8ee6758374df6d3f6b6298cb0ba104f6)
backport of #4880 to 1.6.x
=> user doc: One small change that is needed downstream

doc/connecting/topics/p_add-kudu-connection-add-records.adoc, doc/integrating-applications/topics/c_about-processing-collections.adoc, doc/integrating-applications/topics/c_workflow-api-providers.adoc, doc/integrating-applications/topics/p_add-aggregate-step.adoc, doc/integrating-applications/topics/p_add-split-step.adoc, doc/integrating-applications/topics/p_create-api-provider-integration.adoc, doc/integrating-applications/topics/p_create-integration-operation-flows.adoc, doc/integrating-applications/topics/p_using-data-mapper-to-process-collections.adoc, doc/integrating-applications/topics/r_example-processing-collection.adoc, doc/integrating-applications/topics/r_requirements-for-api-provider-integrations.adoc, doc/tutorials/topics/p_sf2db-choose-finish.adoc, doc/tutorials/topics/p_t2sf-choose-start.adoc
Updates based on Christoph's review.
=> Fusedoc 3002 collections

app/ui/src/app/integration/api-provider/creation-page/integration-api-provider-creation-page.component.ts
=> fix: bring the user back to the regular editor if cancel is clicked

app/ui/src/app/integration/edit-page/current-flow.service.ts
=> fix: only try and refresh data shapes for dynamic actions

app/pom.xml, app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/customizer/CamelKIntegrationCustomizer.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/customizer/TemplatingCamelKIntegrationCustomizer.java, app/server/controller/src/test/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandlerTest.java, install/generator/02-syndesis-image-streams.yml.mustache, install/generator/04-syndesis-oauth-proxy.yml.mustache, install/generator/04-syndesis-server.yml.mustache, install/generator/syndesis-template.go, install/syndesis.yml
=> Some runtime fixes for 1.6.x

doc/connecting/topics/p_create-gmail-connection.adoc, doc/connecting/topics/p_create-google-calendar-connection.adoc, doc/connecting/topics/p_create-google-sheets-connection.adoc, doc/shared/p_create-sf-connection.adoc, doc/shared/p_create-twitter-connection.adoc
(cherry picked from commit b9309ba3e68268ef387f0955f9c0f2ae790cd5ed)
[ci skip]
=> user doc: Adds note to use the Settings page for oauth

app/ui/src/assets/dictionary/en-GB.json
(cherry picked from commit f7ac8b760603e3204aeb83df52d798e2e212cf07)
=> fix: Update version number in dictionary

app/pom.xml, app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/customizer/CamelKIntegrationCustomizer.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/customizer/TemplatingCamelKIntegrationCustomizer.java, app/server/controller/src/test/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandlerTest.java, install/generator/02-syndesis-image-streams.yml.mustache, install/generator/04-syndesis-oauth-proxy.yml.mustache, install/generator/04-syndesis-server.yml.mustache, install/generator/syndesis-template.go, install/syndesis.yml
Opening another PR for 1.6.x branch.
=> Some runtime fixes

app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationDeploymentBase.java, app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationDeploymentError.java, app/integration/api/src/main/java/io/syndesis/integration/api/IntegrationErrorHandler.java, app/integration/api/src/main/java/io/syndesis/integration/api/IntegrationProjectGenerator.java, app/integration/project-generator/pom.xml, app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java, app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/ProjectGeneratorTest.java, app/server/controller/src/main/java/io/syndesis/server/controller/StateUpdate.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/BaseIntegrationController.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationOverviewHelper.java, app/server/jsondb/src/main/java/io/syndesis/server/jsondb/dao/IntegrationDeploymentJsonDbDao.java, app/ui/src/app/integration/integration_detail/integration-detail.component.html, app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.html, app/ui/src/app/integration/list/status.component.ts, app/ui/src/assets/dictionary/en-GB.json
(cherry picked from commit 2abf55a84343e415b5bcfa9b8a28c49876db17a8)
backport fix to 1.6.x
=> fix: #4867 Add proper error handling for integration publish process

app/ui/src/app/integration/edit-page/current-flow.service.ts
=> fix: #4933 Error in UI when adding connections not providing any tags

install/operator/pkg/controller/syndesis/syndesis_controller.go
PR https://github.com/syndesisio/syndesis/pull/4947 for 1.6.x
=> Fix #4781: fix upgrade termination

install/generator/02-syndesis-service-accounts.yml.mustache, install/generator/03-syndesis-ui.yml.mustache, install/generator/04-syndesis-db.yml.mustache, install/generator/04-syndesis-oauth-proxy.yml.mustache, install/syndesis.yml
=>  Add default SA for DeploymentConfigs that dont have one

app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/BaseCamelKHandler.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKSupport.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKUnpublishHandler.java
=> Fix #4966: prepend a i- to the integration name

app/ui/src/app/integration/edit-page/flow-functions.ts, app/ui/src/app/platform/types/integration/integration.models.ts, app/ui/src/app/store/connection/connection.store.ts, app/ui/src/app/store/connector/connector.store.ts
(cherry picked from commit bb1941276ec933d7fce27db986fbcc00b64ffa3f)
=> fix: hide the log connection in favor of the log step; fixes issue-4935

app/integration/bom-camel-k/pom.xml, app/integration/pom.xml, app/integration/runtime-camelk/pom.xml, app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java, app/server/controller/src/test/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandlerTest.java
- added a bom for camel-k runtime
- requires camel-k built from master
Fixes #4926
=> Lib alignment errors in Camel K mode

app/integration/bom-camel-k/pom.xml, app/integration/pom.xml, app/integration/runtime-camelk/pom.xml, app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java, app/server/controller/src/test/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandlerTest.java
=> Lib alignment errors in Camel K mode #4926

app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/BaseCamelKHandler.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKSupport.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKUnpublishHandler.java
(cherry picked from commit 5e19bae)
Fix #4966: fix PMD
(cherry picked from commit 7770adc)
=>  Fix #4966: prepend a i- to the integration name

app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SyndesisSwaggerValidationRules.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/SyndesisSwaggerValidationRulesTest.java
=> feat: add OpenAPI validation that at least one path and operation are given

README.md
=> (Test) Update README.md

app/connector/salesforce/src/main/java/io/syndesis/connector/salesforce/SalesforceIdentifier.java, app/connector/salesforce/src/main/java/io/syndesis/connector/salesforce/customizer/DataShapeCustomizer.java, app/connector/salesforce/src/test/java/io/syndesis/connector/salesforce/customizer/DataShapeCustomizerTest.java
=> Unable to use fetches a record from Salesforce by external id

app/integration/bom/pom.xml, app/pom.xml, app/ui/package.json, app/ui/yarn.lock
Update to AtlasMap 1.39.6
Fixes: #5026
contains a fix for atlasmap/atlasmap#834
=> fix: Data Mapper Transformation is unexpectedly duplicated

app/ui/src/app/integration/edit-page/flow-functions.ts, app/ui/src/app/store/step/step.store.ts
=> fix: hide filters if there's a collection before it; also avoid saving unconfigured steps

tools/upgrade/migration/resource/REDME.adoc, tools/upgrade/migration/resource/any/03_ensure_service_account_setup.sh
and link them to a potentially exisiting "syndesis-pull-secret".
Fixes #4903.
=> feature(update): Update service accounts if not existing

doc/connecting/master.adoc, doc/connecting/topics/as_connecting-to-irc.adoc, doc/connecting/topics/p_adding-irc-connection-receive.adoc, doc/connecting/topics/p_adding-irc-connection-send.adoc, doc/connecting/topics/p_creating-irc-connections.adoc, doc/connecting/topics/r_supported-connectors.adoc
Reviewed by Zoran and Andrej V. 
Ready to merge.
=> user doc: IRC connector

doc/integrating-applications/topics/as_mapping-data.adoc, doc/integrating-applications/topics/p_identify-where-data-mapping-is-needed.adoc, doc/integrating-applications/topics/r_troubleshooting-data-mapping.adoc
This describes an error that requires the user to remove the data mapper step and replace it with a new data mapper step. Paul L. reviewed it. Ready to merge.
=> user doc: Add troubleshooting topic to data mapper doc

app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/UnifiedJsonDataShapeGenerator.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/SwaggerUnifiedShapeGeneratorExampleTests.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/TestHelper.java, app/server/api-generator/src/test/resources/swagger/machine_history.swagger.json, app/server/api-generator/src/test/resources/swagger/machine_history.unified_connector.json
=> fix: proper model generation for arrays of integers

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteTest.java
Fixes #5042 
It would be nice if the code around this fix has some comments since we may need to set the STEP_ID in some other places around there too..
=> fix: Multiple DataBuckets not accessible, source does not exist #5042

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteTest.java
fix: Multiple DataBuckets not accessible, source does not exist #5042
=> Manual Backport #5062 on 1.6.x: 

app/ui/src/app/app.component.html, app/ui/src/app/app.component.scss
=> fix: set the product logo wider

app/ui/src/app/app.component.html, app/ui/src/app/app.component.scss
=> fix: set the product logo wider (1.6.x)

app/pom.xml
fix for https://github.com/syndesisio/syndesis/issues/5086
=> rolling back spring-boot version to 1.5.16.RELEASE

tools/upgrade/migration/resource/1.3/01_server_config_map_upgrade.sh
@zregvart let's use the same way for 7.3 and we should finally solve it for 7.4 :-)
it's just copied from `1.2` folder with the change
=> [Upgrade] Add migration script for updating the s2i is tag

doc/connecting/master.adoc, doc/connecting/topics/as_connecting-to-fhir.adoc, doc/connecting/topics/p_adding-fhir-connection-create.adoc, doc/connecting/topics/p_adding-fhir-connection-delete.adoc, doc/connecting/topics/p_adding-fhir-connection-patch.adoc, doc/connecting/topics/p_adding-fhir-connection-read.adoc, doc/connecting/topics/p_adding-fhir-connection-search.adoc, doc/connecting/topics/p_adding-fhir-connection-transaction.adoc, doc/connecting/topics/p_adding-fhir-connection-update.adoc, doc/connecting/topics/p_creating-fhir-connections.adoc, doc/connecting/topics/r_supported-connectors.adoc
This is still in QA review, but I need to move 7.3 content along to get it downstream.
=> User doc for FHIR connector

doc/connecting/master.adoc, doc/connecting/topics/as_connecting-to-odata.adoc, doc/connecting/topics/p_add-google-sheets-connection-get-sheet-values.adoc, doc/connecting/topics/p_adding-odata-connections-read.adoc, doc/connecting/topics/p_adding-odata-connections-write.adoc, doc/connecting/topics/p_creating-odata-connections.adoc, doc/connecting/topics/r_supported-connectors.adoc
Reviewed by Paul R. Will merge this and get it downstream. 
Will ask for a QA review.
=> User doc for Odata connector

app/ui/.gitignore, app/ui/scripts/get-login-cookie.js
"Borrowed" @riccardo-forina's fix so you don't have to log in all the time when running against staging, thanks!
=> chore: set the data folder for chromium to persist the login cookies

app/integration/bom-camel-k/pom.xml
In master this should be part of #2436
=> issue #4926: removed unnecessary and harmful exclusions

app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/HttpClient.java, app/server/verifier/src/main/java/io/syndesis/server/verifier/ExternalVerifierService.java
This reverts commit 8be3dce0585664f4622817f4836415e18969323e.
Fixes #5147
=> Revert "chore: prepare for RESTEasy 4"

doc/connecting/topics/p_adding-odata-connections-read.adoc, doc/connecting/topics/p_adding-odata-connections-write.adoc, doc/connecting/topics/p_creating-odata-connections.adoc
=> user doc: Updates based on QA review of doc for OData connector

app/extension/maven-plugin/pom.xml, app/pom.xml
More details in commit messages. @cunningt I think this might help in the future.
=> Number of Maven issues

tools/bin/commands/build
=> Fix #5156: fix camel k build from vanilla repo

app/ui/src/scss/utils/_overrides.scss
fixes https://github.com/syndesisio/syndesis/issues/5153
=> fix(body): hide body vertical overflow, update content area padding

app/connector/http/src/main/resources/META-INF/spring.factories, app/connector/webhook/src/main/resources/META-INF/spring.factories, app/meta/src/main/resources/application.yml
=> Meta doesn't start on master

app/integration/runtime-springboot/pom.xml, app/integration/runtime-springboot/src/main/resources/META-INF/spring.factories, app/integration/runtime-springboot/src/test/java/io/syndesis/integration/runtime/sb/ApplicationTest.java
=> Integrations don't start on master

app/integration/bom/pom.xml
Upgrade jackson-databind version to 2.8.11.3 in integration-bom
=> ENTESB-9863 Upgrade jackson-databind version to 2.8.11.3 in integration-bom

app/integration/component-proxy/pom.xml, app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentProxyComponent.java, app/integration/component-proxy/src/test/java/io/syndesis/integration/component/proxy/CustomComponentTest.java, app/integration/pom.xml, app/integration/support/camel-acme/pom.xml, app/integration/support/camel-acme/src/main/java/com/acme/corp/AcmeComponent.java, app/integration/support/camel-acme/src/main/java/com/acme/corp/AcmeEndpoint.java, app/integration/support/camel-acme/src/main/resources/META-INF/services/org/apache/camel/component/acme
=> integration runtime: component-proxy to support custom components

app/connector/aws-sqs/pom.xml, app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/AWSSQSBatchMessagesCustomizer.java, app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/AWSSQSMessageCustomizer.java, app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/AWSSQSPollMessageCustomizer.java, app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/AWSSQSVerifier.java, app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/AWSSQSVerifierAutoConfiguration.java, app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/AWSSQSVerifierExtension.java, app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/SQSMessage.java, app/connector/aws-sqs/src/main/resources/META-INF/spring.factories, app/connector/aws-sqs/src/main/resources/META-INF/syndesis/connector/aws-sqs.json, app/connector/pom.xml, app/connector/support/catalog/pom.xml, app/extension/pom.xml, app/integration/bom-camel-k/pom.xml, app/integration/bom/pom.xml, app/meta/pom.xml, app/pom.xml
Related to #4843 and fixes #5204
=> feat(sqs-connector): AWS-SQS Connector

app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html, app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts, app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/flow-functions.ts
* Incorporates check for what step is being configured and differentiate
between input and output shapelessness since
a) input shape doesn't matter to start step
b) output shape doesn't matter to finish step
=> fix(5057): Correct determination of when to show Next or Done buttons

doc/integrating-applications/topics/as_trigger-integrations-with-api-calls.adoc, doc/integrating-applications/topics/c_about-api-provider-flows.adoc, doc/integrating-applications/topics/c_about-api-provider-urls.adoc, doc/integrating-applications/topics/c_overview-benefit-api-provider-integrations.adoc, doc/integrating-applications/topics/c_plan-integrations.adoc, doc/integrating-applications/topics/p_configure-publish-api-provider-quickstart.adoc, doc/integrating-applications/topics/p_create-api-provider-integration.adoc, doc/integrating-applications/topics/p_create-integration-operation-flows.adoc, doc/integrating-applications/topics/p_try-api-provider-quickstart.adoc
Updates based on minimalism review within customer content services. 
And based on comments from Melissa about the result of enabling discovery of APIs in 3scale.
=> user doc: updates to doc for creating api provider integrations

app/connector/odata/src/test/java/io/syndesis/connector/odata/AbstractODataTest.java, app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java, app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGeneratorConfiguration.java, app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/ProjectGeneratorTest.java, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/application-tracing.properties, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/redhat/application-tracing.properties, app/integration/runtime-camelk/src/main/java/io/syndesis/integration/runtime/camelk/IntegrationRouteLoader.java, app/integration/runtime-springboot/pom.xml, app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/IntegrationRuntimeAutoConfiguration.java, app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/logging/IntegrationLoggingAutoConfiguration.java, app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/tracing/TracingAutoConfiguration.java, app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/tracing/TracingCamelContextConfiguration.java, app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/tracing/TracingConfiguration.java, app/integration/runtime-springboot/src/main/resources/META-INF/spring.factories, app/integration/runtime-springboot/src/test/java/io/syndesis/integration/runtime/sb/tracing/IntegrationTracingDisabledTest.java, app/integration/runtime-springboot/src/test/java/io/syndesis/integration/runtime/sb/tracing/IntegrationTracingEnabledTest.java, app/integration/runtime/pom.xml, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/ActivityTrackingPolicyFactory.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/IntegrationLoggingActivityTrackingPolicy.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/IntegrationLoggingActivityTrackingPolicyFactory.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/IntegrationLoggingConstants.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/tracing/TracingActivityTrackingPolicy.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/tracing/TracingActivityTrackingPolicyFactory.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/tracing/TracingInterceptStrategy.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/tracing/TracingLogListener.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationTestSupport.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/logging/ActivityLoggingTest.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/logging/ActivityLoggingWithSplitTest.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/tracing/ActivityTracingWithSplitTest.java
- Add optional jaeger tracing for activity monitoring for the SB runtime.
=> feat: Add jaeger support so that syndesis and integrations can be traced.

app/integration/runtime-springboot/pom.xml, app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/SyndesisHttpConfiguration.java
=> No bean could be found in the registry for: syndesisHeaderStrategy 

app/extension/bom/pom.xml, app/integration/bom-camel-k/pom.xml, app/integration/bom/pom.xml, app/pom.xml
=> chore(update-camel): Bump Camel to version 2.21.0.fuse-740007

app/connector/aws-sqs/src/main/resources/META-INF/syndesis/connector/aws-sqs.json
=> fix(aws-sqs): [SQS] Issues with SQSMessage - Datamapper, Batch messages

app/connector/email/pom.xml, app/connector/email/src/main/java/io/syndesis/connector/email/EMailConstants.java, app/connector/email/src/main/java/io/syndesis/connector/email/EMailUtil.java, app/connector/email/src/main/java/io/syndesis/connector/email/component/EMailComponent.java, app/connector/email/src/main/java/io/syndesis/connector/email/customizer/EMailReceiveCustomizer.java, app/connector/email/src/main/java/io/syndesis/connector/email/customizer/EMailSendCustomizer.java, app/connector/email/src/main/java/io/syndesis/connector/email/meta/EMailMetaDataExtension.java, app/connector/email/src/main/java/io/syndesis/connector/email/meta/EMailMetaDataRetrieval.java, app/connector/email/src/main/java/io/syndesis/connector/email/meta/EMailMetadata.java, app/connector/email/src/main/java/io/syndesis/connector/email/model/EMailMessageModel.java, app/connector/email/src/main/java/io/syndesis/connector/email/verifier/EMailVerifierExtension.java, app/connector/email/src/test/java/io/syndesis/connector/email/AbstractEMailRouteTest.java, app/connector/email/src/test/java/io/syndesis/connector/email/AbstractEMailTest.java, app/connector/email/src/test/java/io/syndesis/connector/email/consumer/EMailReadRouteTest.java, app/connector/email/src/test/java/io/syndesis/connector/email/meta/EMailMetaDataTest.java, app/connector/email/src/test/java/io/syndesis/connector/email/producer/EMailSendRouteTest.java, app/connector/email/src/test/java/io/syndesis/connector/email/server/EMailTestServer.java, app/connector/email/src/test/java/io/syndesis/connector/email/verifier/EMailVerifierTest.java, app/connector/support/util/src/main/java/io/syndesis/connector/support/util/CertificateUtil.java, app/connector/support/util/src/main/java/io/syndesis/connector/support/util/KeyStoreHelper.java, app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentProxyComponent.java
* Addresses shortcomings of email-connector code.
see [PR#5329](https://github.com/syndesisio/syndesis/pull/5329) for comments.
=> chore: Resolve comments outlined in PR #5329

app/server/update-controller/src/main/java/io/syndesis/server/update/controller/usage/UsageUpdateHandler.java
=> fix: properly handle extensions change events

app/connector/aws-sqs/src/main/resources/META-INF/syndesis/connector/aws-sqs.json
=> refactor(aws-sqs): [SQS] Use nullDeduplicationStrategy by default

app/ui/src/app/integration/edit-page/current-flow.service.ts, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss, app/ui/src/app/integration/edit-page/flow-view/flow-view.component.ts
This PR adds a flow indicator to flow view when a sub-flow is opened.
My limited CSS skills ended up in a quite hacky solution. Maybe someone with more CSS love is subject to improve the layout.
=> [feat] UI add flow indicator

app/connector/aws-sns/pom.xml, app/connector/aws-sns/src/main/java/io/syndesis/connector/aws/sns/AWSSNSMessageCustomizer.java, app/connector/aws-sns/src/main/java/io/syndesis/connector/aws/sns/AWSSNSVerifier.java, app/connector/aws-sns/src/main/java/io/syndesis/connector/aws/sns/AWSSNSVerifierExtension.java, app/connector/aws-sns/src/main/java/io/syndesis/connector/aws/sns/SNSMessage.java, app/connector/aws-sns/src/main/resources/META-INF/syndesis/connector/aws-sns.json, app/connector/aws-sns/src/main/resources/META-INF/syndesis/connector/verifier/aws-sns, app/connector/pom.xml, app/connector/support/catalog/pom.xml, app/integration/bom-camel-k/pom.xml, app/integration/bom/pom.xml, app/meta/pom.xml, app/pom.xml
=> feature(aws-sns): Create an AWS-SNS connector

doc/integrating-applications/topics/r_mapping-between-collections-and-non-collections.adoc
Sean did a peer review of the topic about mapping between collections and non-collections. This PR just has some minor edits.
=> user doc: Peer review edits, minor stuff

app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
=> fix: avoid creating request loop

app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/PropertyGenerators.java
=> fix(server): NPE if no OAuth scopes defined in OpenAPI specification

app/ui/src/app/integration/edit-page/flow-functions.ts, app/ui/src/app/integration/edit-page/flow-page.service.ts, app/ui/yarn.lock
=> fix(ui): skip over connections that do not have the embedded connector property

tools/upgrade/Dockerfile
Seems that there's an issue with one of the repositories, to fix it local cache needs to be cleaned, packages updated and then we can proceed with installing packages.
Fixes #5417
=> fix(build): make sure to run cache clean and upgrade

app/connector/knative/pom.xml, app/connector/knative/src/main/java/io/syndesis/connector/knative/meta/KnativeMetaDataExtension.java, app/connector/knative/src/main/java/io/syndesis/connector/knative/meta/KnativeMetaDataRetrieval.java, app/connector/knative/src/main/java/io/syndesis/connector/knative/meta/KnativeMetaDataSupport.java, app/connector/knative/src/main/java/io/syndesis/connector/knative/meta/crd/KnativeResource.java, app/connector/knative/src/main/java/io/syndesis/connector/knative/meta/crd/KnativeResourceDoneable.java, app/connector/knative/src/main/java/io/syndesis/connector/knative/meta/crd/KnativeResourceList.java, app/connector/knative/src/main/resources/META-INF/syndesis/connector/knative.json, app/connector/knative/src/main/resources/META-INF/syndesis/connector/meta/knative, app/connector/support/verifier/src/main/java/io/syndesis/connector/support/verifier/api/ComponentMetadataRetrieval.java, app/meta/pom.xml, install/generator/04-syndesis-meta.yml.mustache, install/generator/04-syndesis-server.yml.mustache, install/operator/deploy/syndesis-operator.yml, install/syndesis.yml
And fix permissions.
Fix #5416 
Fix #5344
=> Adding auto-discovery of Knative resources

app/connector/box/pom.xml, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirDeleteTest.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirMetadataRetrievalTest.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirPatchTest.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirUpdateTest.java, app/connector/fhir/src/test/java/io/syndesis/connector/fhir/processor/FhirResourceProcessorTest.java, app/pom.xml, app/ui/package.json, app/ui/yarn.lock
I've created individual commits and I can remove any of them if there are objections. A lot of the versions had to be force resolved.
=> Dependency upgrades based on Snyk issues

app/extension/bom/pom.xml, app/integration/bom-camel-k/pom.xml, app/integration/bom/pom.xml, app/pom.xml
contains camel-jira @claudio4j @zregvart @heiko-braun
=> chor(camel): Bump Camel to version 2.21.0.fuse-740013

app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
`To` is not invoked periodically :-)
=> [SQL] Fix description of To: Stored procedure

tools/bin/commands/util/openshift_funcs
=> [closes #5442] Fix double dash for operator template parameter

app/connector/odata/src/main/java/io/syndesis/connector/odata/verifier/ODataVerifierExtension.java, app/connector/odata/src/main/resources/META-INF/syndesis/connector/verifier/odata
* Correct wrong package name in metadata file
* Improve detail of error messages when errors encountered during validation
=> fix(5385): Fixes regression in OData Connector validation

app/ui-angular/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html, app/ui-angular/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.html
Small fix for conditional flows seen through demo recording
=> fix: Show cancel/done buttons also on alternate flow navigation bar

.circleci/config.yml
=> fix: CircleCI build fails on the UI module

.circleci/config.yml, tools/bin/commands/util/openshift_funcs, tools/bin/install-syndesis
=> Fix #5436 Error when installing from sydesis.yml template

app/connector/twitter/pom.xml, app/connector/twitter/src/main/java/io/syndesis/connector/twitter/DirectMessageText.java, app/connector/twitter/src/main/java/io/syndesis/connector/twitter/SendDirectMessageCustomizer.java, app/connector/twitter/src/main/resources/META-INF/syndesis/connector/twitter.json, app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java, doc/connecting/topics/p_adding-twitter-connections.adoc
https://github.com/syndesisio/syndesis/issues/3521
=> Twitter Direct Message

install/addons/syndesis-integration-dashboard.yml
First version of a Grafana dashboard for integration apps. It will need to be integrated into a 'home' dashboard that lists all integrations.
fix #3918
=> Application dashboards

install/generator/03-syndesis-ui.yml.mustache, install/operator/syndesis-privileged.yml, install/operator/syndesis.yml, install/syndesis.yml
Am I following the correct workflow?
Doesn't feel right to modify the sort-of same file in 4 different places.
=> syndesis-ui, add entry to ConfigMap to support DataVirt

doc/integrating-applications/topics/p_add-template-step.adoc
Suggested by Martin. Reviewed and approved by Martin and Paul.
=> user doc: Added examples of Freemarker and Velocity templates

tools/bin/commands/util/openshift_funcs
Fixes https://github.com/syndesisio/syndesis/issues/4961
=> Fix to match changed output of oc version

app/connector/mqtt/pom.xml, app/extension/bom/pom.xml, app/extension/example/log-step/pom.xml, app/extension/example/simple-action-step/pom.xml, app/extension/maven-plugin/src/it/with-data-shape-variants/pom.xml, app/extension/maven-plugin/src/it/with-data-shape/pom.xml, app/integration/bom-camel-k/pom.xml, app/integration/bom/pom.xml, app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/pom.xml.mustache, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/pom.xml, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/pom.xml, app/pom.xml, app/server/credential/pom.xml, app/server/runtime/pom.xml
Add <name> tags to repositories
=> Add <name> to repositories

app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/ConnectorFactory.java, app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/RequestCustomizer.java, app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/SwaggerProxyComponent.java, app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/SyndesisRestSwaggerComponent.java, app/connector/rest-swagger/src/main/resources/META-INF/services/org/apache/camel/component/connector-rest-swagger-http4, app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/SwaggerProxyComponentTest.java, app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentProxyComponent.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/crd/ConfigurationSpec.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/crd/IntegrationSpec.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/customizer/ExposureCustomizer.java
=> API Client not working if multiple http compatible components are found in the camel registry or classpath

app/common/model/src/main/java/io/syndesis/common/model/Schema.java, app/server/runtime/src/main/resources/migrations/up-29.js, app/server/runtime/src/test/java/io/syndesis/server/runtime/migrations/UpgradeVersion29Test.java, app/server/runtime/src/test/resources/migrations/29/connection.json, app/server/runtime/src/test/resources/migrations/29/connector.json, app/server/runtime/src/test/resources/migrations/29/integration.json
=> Migrate old style API connectors

app/ui-react/syndesis/config.staging.json
Fixing an issue with git history I have introduced, sorry.
It's actually noisy on git history, but it's actually bringing in just a single file.
=> Merge react/master

doc/connecting/topics/as_connecting-to-fhir.adoc, doc/connecting/topics/p_adding-fhir-connection-create.adoc, doc/connecting/topics/p_adding-fhir-connection-patch.adoc, doc/connecting/topics/p_adding-fhir-connection-update.adoc, doc/integrating-applications/topics/p_add-aggregate-step.adoc
Peer review updates. 
Typo fix. 
Addition of examples of JSON patches for updating a resource. 
Removed the Technology Preview note, which was conditionalized to render in only Red Hat doc. 
Still some outstanding questions so still a WIP.
=> user doc for minor updates to doc for FHIR connector

app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelper.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGeneratorTest.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelperTest.java
=> chore(openapi): better error for unsupported versions

app/ui-angular/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.html, app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Reverts syndesisio/syndesis#5597
React codebase PR should go to `syndesis/syndesis-react` repo first
=> Revert "fix: Add simple language syntax examples in conditional flows config page"

app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/HttpRequestUnwrapperProcessor.java, app/connector/support/processor/src/test/java/io/syndesis/connector/support/processor/HttpRequestUnwrapperProcessorTest.java
=> chore: set Content-Type to text/plain for simple bodies

.circleci/config.yml, tools/bin/commands/build, tools/bin/commands/util/common_funcs, tools/bin/commands/util/maven_funcs
This adds the `--incremental` build flag that influences the build to remove any modules that do not have committed or uncomitted changes in them against a git ref (default `master`).
Also configures the use of it on CircleCI.
=> Incremental build option in Syndesis CLI

app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlConnectorMetaDataExtension.java
=> fix for #5603 SQL connector cannot access the sampledb tables

app/connector/timer/src/main/resources/META-INF/syndesis/connector/timer.json, app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json
I updated the description of the provided Timer connection, as well as the connection's action names and descriptions.
=> fixes #5625 Improve descriptions of timer actions

app/ui-angular/src/app/integration/edit-page/step-configure/templater/templater.component.ts
* Fixes angular UI template editor so that it updates the input
specification when modified.
* Note. react-ui version already fixed.
=> fix(5526): Regression in template step editor updating

app/connector/activemq/src/main/resources/META-INF/syndesis/connector/activemq.json
And corrects the hint for the Durable subscription ID field.
=> fixes #5625 partially - updates field labels for Red Hat AMQ connector

doc/connecting/topics/as_connecting-to-odata.adoc
=> user doc: remove Technology Preview note from OData connector doc

app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
Refines the description and labelHint for SQL connector.
Fixes #4878
=> chore: refine description and labelHint

app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlSupport.java, app/connector/sql/src/main/java/io/syndesis/connector/sql/common/SqlStatementMetaData.java, app/connector/sql/src/main/java/io/syndesis/connector/sql/common/SqlStatementParser.java
Related to #5603 
Also fixed the schema property for stored procedures lookup and added schema name to error messages.
=> fix: db schema property for stored procedures

app/connector/box/src/main/java/io/syndesis/connector/box/BoxFile.java, app/connector/box/src/main/java/io/syndesis/connector/box/customizer/BoxDownloadCustomizer.java, app/connector/box/src/main/resources/META-INF/syndesis/connector/box.json, app/connector/box/src/test/java/io/syndesis/connector/box/customizer/BoxDownloadCustomizerTest.java
=> fix(connector): Box - OutputDataShape java.io.OutputStream not needed as it can't be mapped to anything

install/operator/.gitignore, install/operator/deploy/manifests/1.7.0/syndesisoperator.1.7.0.clusterserviceversion.yaml
... and exclude my development files ...
=> Fix image for syndesis operator olm integration

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/SplitStepHandler.java
Split step should auto convert types if necessary in order to handle Json data properly.
At the moment the known types for auto conversion are:
- InputStream (used by APIProvider, WebHook and Http connector)
- RemoteFile (used by ftp connector)
These types get converted to String representation using the Camel type conversion strategy and if this data happens to be a Json array split step splits those to its elements. Any other data types (e.g. List, Scanner) are handled by the Camel splitter by default splitting those to its elements.
Fixes #5737
=> fix: Make split step work with ftp connector

doc/sdh/cli/cmd_install.adoc, doc/sdh/cli/cmd_minishift.adoc, install/generator/03-syndesis-ui.yml.mustache, install/operator/pkg/syndesis/template/install.go, install/syndesis.yml, tools/bin/commands/build, tools/bin/commands/install, tools/bin/commands/minishift, tools/bin/commands/util/openshift_funcs, tools/bin/install-syndesis
https://github.com/syndesisio/syndesis/issues/5475
=> Fixes #5475 Disable DataVirt UI when Komodo server isn't present

app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
=> feat: set the initial name and description for new connections as the connector

app/ui-react/packages/api/src/constants.ts, app/ui-react/packages/api/src/helpers/integrationFunctions.ts, app/ui-react/packages/models/src/models-internal.d.ts, app/ui-react/packages/models/swagger.internal.json, app/ui-react/packages/models/swagger.json
Updates the `swagger.*.json` to latest from `master`.
=> chore(ui): update OpenAPI documents

app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlStartConnectorCustomizer.java
=> fix for 5493 - also return keys when start connector

.circleci/config.yml
Removes the `filters` in the job defaults.
Fixes #5472
=> fix: CircleCI schema violations

.circleci/config.yml
Issue https://github.com/syndesisio/syndesis/issues/5777
=> Fixes #5777 Operator image is not being pushed to dockerhub

doc/integrating-applications/topics/as_creating-integrations.adoc, doc/integrating-applications/topics/c_about-adding-steps.adoc, doc/integrating-applications/topics/c_description-of-constructs.adoc, doc/integrating-applications/topics/c_how-it-works.adoc, doc/integrating-applications/topics/c_plan-integrations.adoc, doc/integrating-applications/topics/p_add-advanced-filter-step.adoc, doc/integrating-applications/topics/p_adding-conditional-execution-flows.adoc, doc/integrating-applications/topics/p_creating-api-connectors.adoc
Created the doc for conditional flows. Christoph has reviewed this. 
Now it needs a QA review. 
While this still needs a QA review, I'll merge it and update later as needed.
=> user doc: Conditional flows 

app/connector/twitter/src/main/resources/META-INF/syndesis/connector/twitter.json
This updates the twitter.json file to change the name of the Keyword input field to Query. 
It also updates the hint to: 
Return tweets that match this Twitter-format search expression.
=> updates Twitter search Keyword field to Query field

app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
Fixes https://github.com/syndesisio/syndesis/issues/5669
=> fix: update the validity function to the new values returned by the BE

app/ui-react/packages/api/src/useApiResource.tsx
Fixes https://github.com/syndesisio/syndesis/issues/5771
=> fix: deepmerge the returned resource with the defaultValue to cleanly deal with no-data responses

install/operator/deploy/syndesis-operator.yml, tools/bin/commands/util/openshift_funcs
Fixes https://github.com/syndesisio/syndesis/issues/5804.
I had to change the operator image to `docker.io/syndesis/syndesis-operator:1.8.1-20190618` because latest didn't build for the last 12 days, most likely https://github.com/syndesisio/syndesis/issues/5777
=> Fixes: problem with privileges during installation

app/ui-react/packages/ui/src/Layout/Breadcrumb.tsx
Fixes https://github.com/syndesisio/syndesis/issues/5754
=> fix: do not show a trailing arrow in the breadcrumb

install/generator/01-header.yml.mustache, install/syndesis.yml
similar to https://github.com/syndesisio/syndesis/pull/4589
=> fix: duplicated attributed "required"

install/operator/deploy/syndesis-operator.yml
Related: https://github.com/syndesisio/syndesis/issues/5804, https://github.com/syndesisio/syndesis/pull/5810
=> revert operator image to latest

app/server/runtime/src/test/java/io/syndesis/server/runtime/ExtensionsITCase.java
=> fix: remove the flaky bit from ExtensionsITCase

app/ui-react/packages/api/src/WithVirtualizationHelpers.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
- Fix issue with view deletion / recreation (TEIIDTOOLS-658).  Changes the explicit delete to call refresh views.
- Fix issue with page redirect (TEIIDTOOLS-662).  This was a regression in the previous commit - removed the incorrectly added redirect.
=> TTOOLS-658 Fix issue with view deletion

doc/connecting/topics/p_adding-twitter-connection-start.adoc
I updated the gdoc for review, but did not completely update the .adoc source file. *Sigh*
This has been reviewed.
=> user doc: Really add the updates for Twitter start connection actions

app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
Based on feedback in #5688
Fixes #4878
=> fix: refines description for periodic SQL invocation

app/ui-react/packages/api/src/WithFilterOptions.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/RuleFilterStepPage.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/WithRuleFilterForm.tsx
- See issue #5702
- Sets default operator to `contains`
- Updates default values to match server-side operator values
=> Minor UI changes to filter options

app/ui-react/syndesis/src/modules/extensions/locales/extensions-translations.en.json, app/ui-react/syndesis/src/modules/extensions/locales/extensions-translations.it.json, app/ui-react/syndesis/src/modules/extensions/pages/ExtensionImportPage.tsx
- see issue # syndesisio/syndesis-react#432
- Toast now displays extension name
- i18n'd the toast message
=> Fix toast notification for uploading extension shows ID

app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json, app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.it.json
- see issue #5721 
- added missing i18n keys
=> fix(5721) - Missing space in the ErrorsFound label

app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Closed original PR. Applied same patch on rebased branch for this one
=> TT-660 Fixed preview to use view defined sql (rebased)

app/ui-react/packages/api/src/WithEnvironments.tsx, app/ui-react/packages/ui/src/Integration/CiCd/CiCdListItem.tsx, app/ui-react/syndesis/src/modules/integrations/components/TagIntegrationDialogWrapper.tsx, app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json, app/ui-react/syndesis/src/modules/integrations/pages/cicd/ManageCiCdPage.tsx
follow on to #5267
@paoloantinori @zregvart you know, it's just finishing up this little thing, if we happen to do another build anyways I think it'd be worth backporting and getting into 7.4 :-)
=> feat: show environment usage

app/ui-react/syndesis/src/modules/extensions/pages/ExtensionImportPage.tsx
=> fix: extensions can have no actions

app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
fixes #5856
@paoloantinori @zregvart it's not a big fix but it's an annoying bug, I think it'd be worth trying to get this into 7.4...
=> fix: add validation/initial validation

app/connector/odata/src/test/java/io/syndesis/connector/odata/AbstractODataRouteTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataUpdateTests.java
* Ensure reference server that is actually modified is unique to the update
tests and doesn't affect results of other ref server read-tests.
=> fix(4562): Shore up odata update tests

doc/sdh/cli/cmd_minishift.adoc, tools/bin/commands/build, tools/bin/commands/minishift, tools/bin/commands/util/common_funcs
https://github.com/syndesisio/syndesis/issues/5860
=> Add --deploy-latest to 'syndesis minshift' command

app/ui-react/syndesis/src/modules/dashboard/locales/dashboard-translations.en.json, app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
It looks like this PR: https://github.com/syndesisio/syndesis/pull/5782
reverted the updates that I previously made in https://github.com/syndesisio/syndesis/pull/5764 but for only this fil: app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
So this PR re-updates that file, and I found one other file that needed text.
=> ui text: Updates text strings that appear in the UI (fixes #5869)

app/ui-react/packages/ui/src/Integration/CiCd/TagIntegrationDialogBody.tsx
=> fix: use the right array of items for ci/cd dialog

app/ui-react/packages/api/src/helpers/integrationFunctions.ts, app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
fixes #5215
@christophd found it :smile:
=> fix: use the right datashape when reconciling flows

install/generator/05-syndesis-security.yml.mustache
Fixes https://github.com/syndesisio/syndesis/issues/5833
=> Allow syndesis-server to manage routes

doc/connecting/topics/p_adding-twitter-connection-finish-middle.adoc, doc/connecting/topics/p_adding-twitter-connection-start.adoc
Updates based on QA review by Martin Muzikar. Needs to be approved by him so not ready to merge. 
Content is also in this gdoc: 
https://docs.google.com/document/d/1oQvhDMq9wuPnzT4i-yO5nUiSs1DiFixmnbtdVryiUCI/edit?usp=sharing
=> WIP: user doc: Add query examples. Remove repetitive text. Update Count param description

app/pom.xml, app/server/credential/src/main/java/io/syndesis/server/credential/AcquisitionMethod.java, app/server/credential/src/main/java/io/syndesis/server/credential/OAuth1CredentialProvider.java, app/server/credential/src/main/java/io/syndesis/server/credential/OAuth2CredentialProvider.java, app/server/credential/src/test/java/io/syndesis/server/credential/OAuth1CredentialProviderTest.java, app/server/credential/src/test/java/io/syndesis/server/credential/OAuth2CredentialProviderTest.java, app/server/runtime/pom.xml, app/server/runtime/src/main/java/io/syndesis/server/runtime/swagger/KindModelResolver.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/SetupITCase.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/credential/CredentialITCase.java, app/ui-react/packages/models/swagger.internal.json, app/ui-react/packages/models/swagger.json
This adds a ModelResolver that places enum values for the Kind enum based on the model name which is used for the value transfered in the JSON data.
Fixes #5924
=> fix: declare used enum values for Kind enum

install/operator/cmd/syndesis-operator/main.go, install/operator/pkg/syndesis/configuration/configuration.go, install/operator/pkg/syndesis/template/install.go, install/operator/pkg/util/resources.go
Fixes https://github.com/syndesisio/syndesis/issues/5925
=> Allow `syndesis-template.yml` to be downloaded from fuse-online-install

app/ui-react/syndesis/public/index.html, app/ui-react/syndesis/src/app/UI.tsx
Also remove reference to the manifest.json
Should help #5602
=> fix: actually disable the web worker

package.json
=> fix: point to the repo syndesis bin

app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
=> fix: ensure the configuredProperties object for a connection is built up from all values

app/ui-react/syndesis/src/setupProxy.js
adds service url for DV to setupProxy
=> updates setupProxy for DV

app/ui-react/syndesis/scripts/get-login-cookie.js
This will fix (hopefully) the automated browser staying stuck on the app homepage.
=> chore: fix puppeter cookie retrieval script

app/ui-react/packages/atlasmap-assembly/package.json, app/ui-react/yarn.lock
@cunningt FYI, also am I correct in thinking this needs to go into the 1.7.x branch?
=> fix: remove karma-jasmine-jquery and therefore the transitive bower dependencies

app/ui-react/yarn.lock
Fix the merge removal of tough-cookie version from 514bb515c25ecd082a…a3d59eb83ed49e690613c3
=> Fix the merge removal of tough-cookie version

RELEASING.adoc
Documents the required addition of a branch protection rule for bugfix branches.
=> chore: add branch protection rules

app/ui-react/packages/api/src/helpers/integrationFunctions.ts, app/ui-react/packages/api/src/useApiProviderIntegration.tsx, app/ui-react/packages/api/src/useApiProviderSpecification.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/ReviewActionsPage.tsx
Fixes https://github.com/syndesisio/syndesis/issues/5697
=> fix: get an updated integration when editing its definition using the new API introduced in #5724

app/ui-react/syndesis/src/modules/connections/pages/ConnectionDetailsPage.tsx
Fixes #6001
@heiko-braun 	not sure, should this be backported?
=> fix: re-render the connection edit form on location change

doc/connecting/topics/as_connecting-to-databases.adoc, doc/connecting/topics/c_about-parameter-placeholders-and-values.adoc, doc/connecting/topics/p_adding-db-connection-finish-middle.adoc, doc/connecting/topics/p_adding-db-connection-start.adoc
Adds doc for collections of input parameters when a database connection updates a database. Reviewed by Christoph.
=> user doc: Add doc for collections of input parameters 

doc/connecting/master.adoc, doc/connecting/topics/p_creating-rest-api-connections.adoc, doc/integrating-applications/master.adoc, doc/integrating-applications/topics/as_copying-integrations-to-other-environments.adoc, doc/integrating-applications/topics/as_managing-integrations.adoc, doc/integrating-applications/topics/c_about-api-connectors.adoc, doc/integrating-applications/topics/c_guidelines-for-openapi-documents.adoc, doc/integrating-applications/topics/p_creating-api-connectors.adoc, doc/shared/attributes-links.adoc, doc/shared/attributes.adoc, doc/tutorials/master.adoc
And a potpourri of other updates in the user doc. 
Zoran reviewed the API key doc.
=> user doc: Updates for API key

app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/application.properties.mustache, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/application-tracing.properties, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/application.properties, app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java, app/server/openshift/src/test/java/io/syndesis/server/openshift/OpenShiftServiceImplTest.java
=> fix: use separate Spring Boot management port for liveness probe

app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx, app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionsListView.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientForm.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/EmptyViewsState.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewHeader.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewHeaderBreadcrumb.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationPublishStatus.tsx
Conversion of some of the DV components in the ui package to React.FunctionComponent.  There will be subsequent PRs for additional work in the api package, etc.
=> TTOOLS-695 Conversion of DV components

app/pom.xml
Need to update spring-security on master
=> Upgrade spring-security to 4.2.13

app/ui-react/packages/api/src/WithVirtualizationHelpers.tsx, app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx, app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx, app/ui-react/syndesis/src/modules/data/resolvers.ts, app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Changed to pass array of tables to teiid-komodo via ViewEditor States when using the view creation wizard. This will allow validation to be done during manual DDL editing.
=> Backport 5998 to 1.7.x - TT-668

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-assembly/package.json, app/ui-react/yarn.lock
Fixes: #6053
cf. atlasmap/atlasmap#1078
=> chore: Update to AtlasMap 1.40.2

install/generator/05-syndesis-security.yml.mustache, install/operator/deploy/manifests/1.7.0/syndesisoperator.1.7.0.clusterserviceversion.yaml, install/operator/deploy/syndesis-operator.yml, install/syndesis.yml
=> Master security fix

doc/integrating-applications/topics/p_applying-conditions-to-mappings.adoc, doc/integrating-applications/topics/p_combine-multiple-source-fields-into-one-target-field.adoc, doc/integrating-applications/topics/p_separate-one-source-field-into-multiple-target-fields.adoc, doc/integrating-applications/topics/r_find-data-field-you-want-to-map.adoc
This expands the doc for conditional mapping. It describes supported functions and operators. 
Paul and Tomo reviewed this. Now it needs a QA review.
=> user doc: Adds doc for supported functions and operations in conditional mapping expressions

app/connector/twitter/pom.xml, app/connector/twitter/src/main/java/io/syndesis/connector/twitter/DirectMessage.java, app/connector/twitter/src/main/java/io/syndesis/connector/twitter/RetrieveDirectMessageCustomizer.java, app/connector/twitter/src/main/resources/META-INF/syndesis/connector/twitter.json
https://github.com/syndesisio/syndesis/issues/6017
=> 6017 - Twitter direct message doesn't work

app/extension/bom/pom.xml, app/integration/bom-camel-k/pom.xml, app/integration/bom/pom.xml, app/pom.xml
=> Bump camel and camel-k to pinned versions

doc/integrating-applications/topics/r_descriptions-of-user-interface-properties-in-extension-definitions.adoc, doc/integrating-applications/topics/r_example-camel-bean.adoc, doc/integrating-applications/topics/r_example-route-builder-spring-boot.adoc, doc/integrating-applications/topics/r_example-route-builder.adoc, doc/integrating-applications/topics/r_example-route-xml-fragment.adoc, doc/integrating-applications/topics/r_example-step-api.adoc
Plus small updates to the new topic about defining user interface properties. 
Plus cross-references from the step extension example code to the new topic about defining ui properties. Luca reviewed the new content.
=> user doc: Add doc for specifying ui properties in Java class files

app/ui-react/packages/ui/src/Shared/SimplePageHeader.css, app/ui-react/packages/ui/src/Shared/SimplePageHeader.tsx, app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json, app/ui-react/syndesis/src/modules/connections/components/Connections.tsx, app/ui-react/syndesis/src/modules/connections/locales/connections-translations.en.json, app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx, app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json, app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/EditorSteps.tsx
fixes https://github.com/syndesisio/syndesis/issues/6055
=> fix(datavirt): add tech preview popover to title text

doc/managing_environments/topics/monitoring_operator_installation.adoc, install/addons/syndesis-integrations-service.yml, install/addons/syndesis-integrations-servicemonitor.yml
We need those files in version 1.7.x
fix #4528
=> Monitoring: Create Service and ServiceMonitor for the integration pods

app/ui-react/packages/api/src/WithSteps.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
=> chore: mark the conditional flow as tech preview

doc/integrating-applications/topics/p_adding-conditional-execution-flows.adoc
Expands the introduction to correct the description of the behavior of a Conditional Flows step. 
Updates the procedure steps to reflect the react UI changes. 
QA Verified.
=> user doc: Updates based on Michael Cada review

app/ui-react/packages/api/src/useApiConnectorSummary.tsx, app/ui-react/packages/api/src/useApiProviderSummary.tsx, app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json, app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/ReviewActionsPage.tsx
Fixes #6101
Fixes #6102
Fixes #4910
=> fix: disable the next button on the Api Provider review page in case of errors in the definition

app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx, app/ui-react/syndesis/src/modules/data/shared/VirtualizationHandlers.ts, app/ui-react/syndesis/src/modules/data/shared/index.ts
Moved common code which was used on several pages into shared VirtualizationHandlers
=> TTOOLS-659 Consolidate virtualization handlers

install/generator/04-teiid-komodo-server.yml.mustache, install/syndesis.yml
https://github.com/syndesisio/syndesis/issues/6111
=> Fixes #6111 Komodo server doesn't start

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/support/IntegrationSupportHandler.java
Fixes flaky tests failing due to circular dependency issue introduced in #5917
=> Fixes #5917 Circular dependency issue

app/connector/aws-sqs/pom.xml, app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/AWSSQSMetaDataExtension.java, app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/AWSSQSMetaDataRetrieval.java, app/connector/aws-sqs/src/main/resources/META-INF/syndesis/connector/aws-sqs.json, app/connector/aws-sqs/src/main/resources/META-INF/syndesis/connector/meta/aws-sqs, app/connector/aws-sqs/src/test/java/io/syndesis/connector/aws/sqs/AWSSQSMetaDataExtensionTest.java
Related to #5464 
Spent the last 3 days, trying to test this is an a local Syndesis instance. Finally it works, but the developers experience must be improved.
=> AWS-SQS MetaData Extension

doc/integrating-applications/topics/c_about-extension-definitions.adoc, doc/integrating-applications/topics/p_adding-conditional-execution-flows.adoc, doc/integrating-applications/topics/r_descriptions-of-user-interface-properties-in-extension-definitions.adoc, doc/integrating-applications/topics/r_example-camel-bean.adoc, doc/integrating-applications/topics/r_example-route-builder-spring-boot.adoc, doc/integrating-applications/topics/r_example-route-builder.adoc, doc/integrating-applications/topics/r_example-route-xml-fragment.adoc, doc/integrating-applications/topics/r_example-step-api.adoc
Backport for #6082 #6105 #6120
=> Backport documentation changes to 1.7.x

app/ui-react/syndesis/src/app/UI.tsx
=> fix: Fuse online documentation links to 7.4

app/connector/box/src/main/java/io/syndesis/connector/box/customizer/BoxUploadCustomizer.java, app/connector/box/src/main/resources/META-INF/syndesis/connector/box.json
https://github.com/syndesisio/syndesis/issues/5233
=> Box - no property for fileName in upload action #5233

app/ui-react/packages/api/src/useApiConnectorSummary.tsx, app/ui-react/packages/api/src/useApiProviderSummary.tsx, app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json, app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/ReviewActionsPage.tsx
=> [Backport 1.7.x] fix: disable the next button on the Api Provider and Api Connector view page in case of errors in the definition

app/connector/aws-sns/pom.xml, app/connector/aws-sns/src/main/java/io/syndesis/connector/aws/sns/AWSSNSMetaDataExtension.java, app/connector/aws-sns/src/main/java/io/syndesis/connector/aws/sns/AWSSNSMetaDataRetrieval.java, app/connector/aws-sns/src/main/resources/META-INF/syndesis/connector/aws-sns.json, app/connector/aws-sns/src/main/resources/META-INF/syndesis/connector/meta/aws-sns, app/connector/aws-sns/src/test/java/io/syndesis/connector/aws/sns/AWSSNSMetaDataExtensionTest.java
=> AWS SNS MetaData Extension

app/ui-react/packages/ui/src/Dashboard/Dashboard.tsx, app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorsPage.tsx, app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx, app/ui-react/syndesis/src/modules/extensions/pages/ExtensionsPage.tsx, app/ui-react/syndesis/src/modules/integrations/pages/IntegrationsPage.tsx
=> fix: quick band-aid to bring back empty states

app/ui-react/packages/ui/src/Dashboard/Dashboard.tsx, app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorsPage.tsx, app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx, app/ui-react/syndesis/src/modules/extensions/pages/ExtensionsPage.tsx, app/ui-react/syndesis/src/modules/integrations/pages/IntegrationsPage.tsx
=> fix: quick band-aid to bring back empty states (1.7.x)

app/ui-react/packages/api/src/useIntegrationHelpers.tsx
=> fix: explicitly set IDs for steps too; add comments

doc/connecting/topics/p_adding-db-connection-finish-middle.adoc
Minor update to get the formatting right.
=> user doc: update to SQL batch update parameter

doc/connecting/topics/p_adding-amazon-sqs-connection-retrieve.adoc
Clarifies the behavior of the options for deleting messages from an SQS queue.
=> user doc: Updates based on QA review.

app/common/model/src/main/java/io/syndesis/common/model/action/ConnectorDescriptor.java, app/common/model/src/main/java/io/syndesis/common/model/connection/ConfigurationProperty.java, app/common/util/src/main/java/io/syndesis/common/util/Json.java, app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/action/DynamicActionSalesforceITCase.java
=> fix for DB procedure name changed to text input instead of dropdown

app/s2i/copy_mvn_repo.sh
#6209 - Just changing the script to be cross compatible. @christophd please make some test and approve as your test are positive.
=> #6209 - Replacing xargs -a to make it compatible with MacOS

app/ui-react/packages/api/src/helpers/integrationFunctions.ts, app/ui-react/packages/api/src/useIntegrationHelpers.tsx
=> fix: revisit fix for #6118, ensure step IDs are only overridden when undefined

doc/tutorials/topics/p_amq2api-create-rest-api-connection.adoc, doc/tutorials/topics/p_amq2api-create-rest-api-connector.adoc
=> user doc: Updates tutorial procedure for creating an api connector

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHelper.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandlerTest.java
=> fix: Make sure split data shape lookup adapts previous step

app/ui-react/packages/api/src/WithIntegrationMetrics.tsx, app/ui-react/packages/api/src/WithIntegrationsMetrics.tsx, app/ui-react/syndesis/src/modules/integrations/pages/detail/MetricsPage.tsx
https://github.com/syndesisio/syndesis/issues/6117
=> #6117 Last Processed shows the actual date when no messages were processed yet.

app/connector/knative/src/main/java/io/syndesis/connector/knative/meta/KnativeMetaDataExtension.java
Related to #6255.
This is the master version of #6259 .
=> Fix knative metadata retrieval logic on master

doc/connecting/topics/p_adding-fhir-connection-read.adoc, doc/connecting/topics/p_create-gmail-connection.adoc, doc/connecting/topics/p_create-google-calendar-connection.adoc, doc/connecting/topics/p_create-google-sheets-connection.adoc, doc/connecting/topics/r_supported-connectors.adoc
Corrections to target link text.
=> user doc: Updates flagged by the translator

.circleci/config.yml, app/test/integration-test/pom.xml
This PR fixes some issues regarding the integration-test config on CircleCi so job is able to run the tests now.
Tests are still failing though and fixing needs to be continued in subsequent PRs
=> fix: CircleCi integration-test config

app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationRelationshipPage.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
- The virtualization was incorrectly included in the route params - removed.  
- Fixed incorrect usage of virtualization in VirtualizationSqlClientPage
=> TTOOLS-725 Resolve invalid service call in DV

install/addons/syndesis-integration-dashboard.yml
fix #6281
The dashboard variables and panel queries have been fixed.
=> Fix #6281: Broken Integration grafana dashboard

app/ui-react/syndesis/src/setupProxy.js
=> chore: fix hot-reload for the UI dev server

doc/connecting/topics/p_add-google-sheets-connection-get-sheet-values.adoc
Matej Melko approved this update. Christoph agrees this is the correct behavior.
=> user doc: Correct the description of Google Sheets, get values, Max results parameter

doc/connecting/topics/p_add-google-sheets-connection-get-sheet-values.adoc
This adds info about Google Sheets, Get Values action when you set both major dimension in the Range field and Max results. Matej Melko approved this update.
=> user doc: Add info about behavior of Max results setting

app/ui-react/packages/auto-form/src/utils.ts, app/ui-react/packages/auto-form/src/widgets/AutoFormHelpBlock.tsx, app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx, app/ui-react/packages/auto-form/src/widgets/FormSelectComponent.tsx, app/ui-react/packages/auto-form/stories/Array.stories.tsx, app/ui-react/packages/auto-form/stories/KitchenSink.stories.tsx, app/ui-react/packages/auto-form/stories/SimpleExamples.stories.tsx, app/ui-react/packages/auto-form/stories/StoryWrapper.tsx, app/ui-react/packages/auto-form/tests/FormArrayComponent.spec.tsx, app/ui-react/packages/auto-form/tests/FormCheckboxComponent.spec.tsx, app/ui-react/packages/auto-form/tests/FormDurationComponent.spec.tsx, app/ui-react/packages/auto-form/tests/FormInputComponent.spec.tsx, app/ui-react/packages/auto-form/tests/FormSelectComponent.spec.tsx, app/ui-react/packages/auto-form/tests/FormTextAreaComponent.spec.tsx
Among other things it makes the auto-form storybook a bit more useful by showing the json alongside the output:
=> chore: Add some more tests and refactoring in autoform, re-order some stories

tools/bin/commands/util/openshift_funcs
=> Enable komodo addon in CR

install/operator/pkg/syndesis/configuration/configuration.go, install/operator/pkg/syndesis/configuration/configuration_test.go, install/operator/pkg/syndesis/template/install.go
Seems to fix #6314 but needs another set of eyes whether it makes sense (first time writing operator code or even go).
Also needs polishing
=> [operator] Fix datavirt installation

app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewOutputToolbar.css, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewOutputToolbar.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/index.ts, app/ui-react/packages/ui/stories/Data/Views/ViewOutputToolbar.stories.tsx, app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json, app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json, app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json, app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json, app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorOutputPage.tsx
- includes remove column dialog
- added toolbar to view output page
- did some i18n work
- added story for toolbar
- will need to implement table and callbacks when inline table editing from patterfly is available
=> First cut at view output table toolbar

app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlStartConnectorCustomizer.java, app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlStartConnectorTest.java
fix #5493: SQL connector doesn't return generated IDs when added as start step
=> fix #5493: SQL connector doesn't return generated IDs when added as start step

install/operator/.lib.sh, install/operator/build.sh, tools/bin/commands/build, tools/bin/commands/tests/test-oc-version.sh, tools/bin/commands/util/camel_k_funcs, tools/bin/commands/util/common_funcs, tools/bin/commands/util/maven_funcs, tools/bin/commands/util/openshift_funcs, tools/bin/commands/util/operator_funcs
Done a lot of testing with different permutations, including
1. go does not exist
2. go is too low a version
3. Neither docker nor go installed
4. go is a higher version (1.13)
5. docker does not exist
6. docker not running - docker info fails
7. operator-sdk not installed
8. GO_PATH not set
9. GO_PATH is wrong
10. Project not under GO_PATH
All or some of these will basically warn/stop the operator or camel-k from building.
=> Fixes for #6231 & #6315

app/ui-react/packages/auto-form/package.json, app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.css, app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx, app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx, app/ui-react/packages/auto-form/src/widgets/FormMapsetComponent.tsx, app/ui-react/packages/auto-form/src/widgets/FormSelectComponent.tsx, app/ui-react/packages/auto-form/src/widgets/FormTextAreaComponent.tsx, app/ui-react/packages/auto-form/stories/Array.stories.tsx, app/ui-react/packages/auto-form/stories/FormWrapper.tsx, app/ui-react/yarn.lock
This PR upgrades patternfly core in auto-form and also applies a few html/css adjustments to the auto-form array layout.
update pf react-core
form array layout adjustments
update auto-form types to align with latest pf
=> chore(auto-form): update auto-form array layout

app/ui-react/packages/auto-form/src/utils.ts, app/ui-react/packages/ui/src/Integration/IntegrationSaveForm.tsx
=> fix: avoid undefined initial value

app/ui-react/syndesis/package.json
=> fix(build): Further increase memory for craco build

app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/WithRuleFilterForm.css
fixes https://github.com/syndesisio/syndesis/issues/6336 and https://github.com/syndesisio/syndesis/issues/6222
@seanforyou23  there is an empty label for the trash icon. Should that have text, or can we remove it if it's empty?
=> fix(basicfilter): rework UI for bordered sections and sticky top condition

app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
=> feat: use the action descriptor in the integration definition for the API provider end connection

install/operator/pkg/cmd/internal/install/install.go, install/operator/pkg/generator/generator.go, install/operator/pkg/util/errors.go, install/operator/pkg/util/resources.go
adding additional stack trace info and fix a bug where updates of resources was not working properly for arrays (we were not truncating big arrays that would get updated to a smaller size)
=> A few Operator fixes

app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlMetadataRetrieval.java, app/connector/sql/src/test/resources/sql/demo_add_metadata.json
#6318 Always populate the stored procedure dropdown
=> fix for #6318 Invoke stored procedure action dropdown is empty

tools/bin/commands/build, tools/bin/commands/util/camel_k_funcs
I checked with Nicola and he agreed we should not be building camelk
=> chore: don’t build camel-k.  use camel-k build systems and instructions to develop/build camel-k. we should only build projects in this repo.

tools/bin/commands/release
This is kind of a workaround, but the issue is blocking QE and needs to be fixed asap
=> ENTESB-11274 change image versions in operator for daily builds

app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx, app/ui-react/packages/auto-form/stories/SyndesisUIs.stories.tsx
part of ENTESB-11238
@mmuzikar FYI, can't log into Jira today so far, but this will at least fix the buttons.  
Layout etc. for the conditional flow page is WIP still.
Also adds a storybook for the form used on the conditional flow page.
=> fix: ensure the view updates when you click the move buttons

app/ui-react/packages/auto-form/src/models.ts, app/ui-react/packages/auto-form/src/useFormBuilder.tsx, app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx, app/ui-react/packages/auto-form/src/widgets/FormCheckboxComponent.tsx, app/ui-react/packages/auto-form/src/widgets/FormInputComponent.tsx, app/ui-react/packages/auto-form/src/widgets/FormTextAreaComponent.tsx, app/ui-react/packages/auto-form/src/widgets/TextButton.tsx, app/ui-react/packages/auto-form/stories/Array.stories.tsx, app/ui-react/packages/auto-form/stories/SyndesisUIs.stories.tsx, app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
=> fix: better fix for move buttons and some cleanup here and there

app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx, app/ui-react/packages/auto-form/src/widgets/FormInputComponent.tsx, app/ui-react/packages/auto-form/src/widgets/FormSelectComponent.tsx, app/ui-react/packages/auto-form/src/widgets/FormTextAreaComponent.tsx, app/ui-react/packages/auto-form/src/widgets/helpers.ts, app/ui-react/packages/auto-form/stories/SyndesisUIs.stories.tsx
fix validation for arrays also
fixes #6460
=> fix: concatenate validation text instead of replacing field help text

app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/PreviewResults.tsx, app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor.stories.tsx, app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json, app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json, app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
- Convert DdlEditor to react FunctionComponent
- in ExpandablePreview, now imports IColumn from PreviewResults per previous PR suggestion
- i18n the validation results title in the DdlEditor
=> TEIIDTOOLS-746 DdlEditor improvements

app/connector/mongodb/pom.xml, app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoClientCustomizer.java, app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/mongodb3.json, app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerAllOptionsTest.java, app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerTest.java, app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCountTest.java, app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorFindAllTest.java, app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorFindByIdTest.java, app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorInsertTest.java, app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorRemoveTest.java, app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorSaveTest.java, app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorUpdateTest.java
Decorating the proxy by adding a method to convert any input/output to a json text, usable by other steps
closes #6290
=> feat(connector): convert input/output to json

doc/integrating-applications/topics/p_add-advanced-filter-step.adoc, doc/integrating-applications/topics/p_add-basic-filter-step.adoc
Also add a link to Camel Simple Language web page for info about operators and examples of what you can specify in the Keywords field. 
This relates to https://github.com/syndesisio/syndesis/issues/6222
=> user doc: Update Basic filter doc to reflect updated field names

app/common/model/src/main/java/io/syndesis/common/model/action/ConnectorDescriptor.java, app/common/model/src/main/java/io/syndesis/common/model/connection/ConfigurationProperty.java, app/common/util/src/main/java/io/syndesis/common/util/ErrorCategory.java, app/common/util/src/main/java/io/syndesis/common/util/Properties.java, app/common/util/src/main/java/io/syndesis/common/util/SyndesisConnectorException.java, app/connector/api-provider/pom.xml, app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderOnExceptionHandler.java, app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderReturnPathCustomizer.java, app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ErrorMapper.java, app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ErrorStatusInfo.java, app/connector/api-provider/src/main/resources/META-INF/syndesis/connector/api-provider.json, app/connector/api-provider/src/test/java/io/syndesis/connector/apiprovider/ErrorMapperTest.java, app/connector/api-provider/src/test/java/io/syndesis/connector/apiprovider/OnExceptionHandlerTest.java, app/connector/sql/src/main/java/io/syndesis/connector/sql/common/CamelSqlConstants.java, app/connector/sql/src/main/java/io/syndesis/connector/sql/common/JSONBeanUtil.java, app/connector/sql/src/main/java/io/syndesis/connector/sql/common/SqlStatementMetaData.java, app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlConnectorCustomizer.java, app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlErrorCategory.java, app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlStartConnectorCustomizer.java, app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json, app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlConnectorQueryTest.java, app/connector/twitter/pom.xml, app/connector/twitter/src/main/java/io/syndesis/connector/twitter/TwitterCustomizer.java, app/connector/twitter/src/main/java/io/syndesis/connector/twitter/TwitterErrorCategory.java, app/connector/twitter/src/main/resources/META-INF/syndesis/connector/twitter.json, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/BaseDataShapeGenerator.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/HttpStatus.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java
Maps exceptions to errors that can be used to set HTTP returncodes in the API-Provider.
Feature #4259
=> Feat #4259 API Provider: Improve Error Handling

doc/integrating-applications/topics/c_about-api-connectors.adoc
Zoran approved the wording for this addition to the section about requirements for creating REST API client connectors. 
This doc is the related to https://github.com/syndesisio/syndesis/issues/5592
=> user doc: Add requirement for setting flow to accessCode

app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx, app/ui-react/syndesis/src/modules/integrations/pages/IntegrationsPage.tsx
=> fix: bring back the integration list skeleton loader

install/operator/pkg/generator/assets/addons/todo/04-todo-example.yml.tmpl
https://issues.jboss.org/browse/ENTESB-11245
=> fix: ENTESB-11245 setting the schema in the environment

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationOverviewHelper.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationOverviewHelperTest.java
https://github.com/syndesisio/syndesis/issues/6506
=> Fixes #6506 Issue trying to save an integration

app/ui-react/packages/api/src/helpers/integrationFunctions.ts, app/ui-react/packages/ui/src/Integration/ConditionsDropdownItem.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/EditorBreadcrumb.tsx
=> fix [6086]: Highlight current selected flow in dropdown

app/ui-react/packages/ui/src/Integration/IntegrationsListView.tsx, app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx, app/ui-react/syndesis/src/modules/integrations/pages/IntegrationsPage.tsx
fixes #6177 the way I should have done it in the first place :smile:
=> fix: bring back the integration list empty state properly

app/ui-react/packages/api/src/helpers/integrationFunctions.ts, app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.ts, app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
=> fix [5456]: Warning on conditional flow step when default flow is required

app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/PodLogMonitor.java
Checking that the log line has the expected json format, otherwise just skipping
closes ENTESB-11374
=> fix(server): NPE on json log lines

tools/bin/commands/release
=> fix(build): add image tag via argument for release

app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionsListView.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewCreateLayout.css, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewCreateLayout.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewsImportLayout.css, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewsImportLayout.tsx
Modifications to the DV wizard layouts to make consistent with other syndesis wizards
- ViewCreateLayout and ViewsImportLayout - using layout css consistent with other syndesis wizards.  Most of the previous css could be eliminated.
=> ENTESB-10826, ENTESB-11252 - DV Wizard layout fixes

app/ui-react/packages/api/src/WithUser.tsx
This PR updates fallback text in a place where I missed it from a previous update. Small but impactful change!
=> chore(text): use more appropriate fallback text

app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DbEnum.java
=> fix #6077 Add support for any data source with valid JDBC Driver

app/integration/bom-camel-k/pom.xml, app/pom.xml
https://issues.jboss.org/browse/ENTESB-11571
=> ENTESB-11571 Update respective fuse artifacts to 7.4 versions

app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewCreateLayout.css, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewsImportLayout.css
changes button padding in the DV wizards to match the footer in the syndesis connections wizard.
=> ENTESB-11608 - correct inconsistent footer in DV wizards

app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
… in array definition auto form for better testability
=> fix(FUSEQE-6017): Add data-testid for "Add another" button

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-assembly/package.json, app/ui-react/packages/atlasmap-assembly/src/app/data-mapper-host.component.ts, app/ui-react/packages/atlasmap-assembly/src/environments/environment.prod.ts, app/ui-react/packages/atlasmap-assembly/src/environments/environment.ts
Contains:
ENTESB-11628 Data mapper steps doesn't contain any data
=> chore: Update to AtlasMap 1.42.1

app/ui-react/packages/api/src/useApiConnectorSummary.tsx, app/ui-react/packages/api/src/useApiProviderSummary.tsx
=> fix(ui/api): handle unrecoverable errors with the api provider/connector

app/ui-react/packages/api/src/WithEnvironmentHelpers.tsx, app/ui-react/packages/api/src/helpers/integrationFunctions.ts, app/ui-react/packages/api/src/useIntegrationHelpers.tsx, app/ui-react/packages/ui/src/Integration/CiCd/CiCdManagePageUI.tsx, app/ui-react/syndesis/src/modules/integrations/pages/cicd/ManageCiCdPage.tsx, app/ui-react/yarn.lock
fixes [ENTESB-11386](https://issues.jboss.org/browse/ENTESB-11386)
Refactors a few methods to work with the kinda standard Syndesis error object
=> fix: update ci/cd page validation and state handling

app/s2i/pom.xml
Using the profile won't trigger the S2I template project generation
closes ENTESB-11682
=> feat(s2i): add a PNC maven profile

app/ui-react/packages/ui/src/Integration/CiCd/CiCdManagePageUI.tsx, app/ui-react/syndesis/src/modules/integrations/pages/cicd/ManageCiCdPage.tsx
fixes [ENTESB-11674](https://issues.jboss.org/browse/ENTESB-11674)
=> fix: better communication between components

app/ui-react/pom.xml
Adding a profile to set a custom-cafile.
=> Add a profile to set a custom-cafile

app/ui-react/pom.xml
Add a property to suppress the installation of the cypress binaries.
=> Suppress the installation of cypress binaries

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/tracing/TracingActivityTrackingPolicy.java
Fixes #6671
Similar to: https://github.com/syndesisio/syndesis/blob/d2fcb71f7200f549ed16ec296b98613a23226867/app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/FlowActivityTrackingPolicy.java#L34
=> Fixes #6671: add check to verify tracer is given

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-assembly/package.json
https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-1.42.2
=> chore: Update to AtlasMap 1.42.2

app/ui-react/packages/auto-form/src/widgets/TextButton.tsx
Adds data testid to the "add another item" button on form arrays.
Fixes ENTESB-11697
=> fix(ENTESB-11697): Render data testid property in text buttons

app/ui-react/packages/auto-form/src/utils.ts, app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx, app/ui-react/yarn.lock
fixes [ENTESB-11665](https://issues.jboss.org/browse/ENTESB-11665)
=> fix: preserve select control semantics

app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/customizer/DDBConnectorCustomizer.java, app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/customizer/DDBConnectorCustomizerRemoveItem.java, app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataRetrieval.java, app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/util/Util.java, app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/aws-ddb.json, app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBConfiguration.java, app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBGenericOperation.java, app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBInsertItemTest.java, app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBQueryItemTest.java, app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataAdapterTest.java
Third operation added: delete items.
Refactor some common functionality on the Utils class and improved tests to include removal of items.
=> [ENTESB-11495] Adding Remove Operation

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-assembly/package.json, app/ui-react/yarn.lock
https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-1.42.3
=> chore: Update to AtlasMap 1.42.3

app/ui-react/syndesis/src/modules/connections/useOAuthFlow.ts
=> fix(ui): more user-friendly message with invalid oauth credentials

app/connector/box/src/main/java/io/syndesis/connector/box/BoxFileDownload.java, app/connector/box/src/main/java/io/syndesis/connector/box/customizer/BoxDownloadCustomizer.java, app/connector/box/src/main/resources/META-INF/syndesis/connector/box.json
https://issues.jboss.org/browse/ENTESB-11479
=> ENTESB-11479 - Box - allow to map something to the fileId in box connector

app/ui-react/README.md, app/ui-react/packages/auto-form/README.md
also add some syndesis ui usage to main readme too
=> chore: bring in some previously written config property docs for auto-form

app/connector/email/src/main/resources/META-INF/syndesis/connector/email-receive.json, app/connector/email/src/main/resources/META-INF/syndesis/connector/email-send.json
* Fixes a couple of tooltip wordings
=> ENTESB-11720: Removes preview banner from email connector

app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.css, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx, app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
- Fixes ENTESB-11644
- Fixes ENTESB-11630
=> ENTESB-11644 and 11630 - added FQN for table names and fixed title header layout

app/ui-react/packages/api/src/WithSteps.tsx, app/ui-react/packages/api/src/helpers/integrationFunctions.ts, app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx, app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/EditorRoutes.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/choice/DescribeChoiceDataShapePage.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/choice/SelectChoiceConfigModePage.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/choice/WithChoiceConfigurationForm.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.ts, app/ui-react/syndesis/src/modules/integrations/components/editor/makeEditorResolvers.ts, app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Adds a select config mode (basic, advanced) page to step configuration so user can choose how to provide condition expressions.
Fixes ENTESB-11578
=> fix(ENTESB-11578): Improve conditional flow usability

doc/assemblies/connecting/as_connecting-to-mongodb.adoc, doc/connecting/master.adoc, doc/modules/connecting/p_add-google-calendar-connection-add-event.adoc, doc/modules/connecting/p_adding-kafka-connection-start.adoc, doc/modules/connecting/p_adding-mongodb-connections-read.adoc, doc/modules/connecting/p_adding-mongodb-connections-write.adoc, doc/modules/connecting/p_create-gmail-connection.adoc, doc/modules/connecting/p_creating-jira-connections.adoc, doc/modules/connecting/p_creating-mongodb-connections.adoc, doc/modules/connecting/r_supported-connectors.adoc
Pasquale reviewed this doc, and it is now available for a QA review, but I need to test the updated script that we use downstream to fetch upstream content, so I'm pushing this now. 
@asmigala - just tagging you in case this is helpful. 
The content that needs review is in this gdoc: 
https://docs.google.com/document/d/1Z1crt5wJxSFwFW2CzFubx4-l_JlGsYYLCMWvWl3AngE/edit?usp=sharing
=> user doc: New doc for using MongoDB connector

install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go, install/operator/pkg/generator/assets/infrastructure/04-syndesis-oauth-proxy.yml.tmpl
This lets us support integrally better.  See: 
https://github.com/integr8ly/installation/blob/master/roles/fuse_managed/tasks/main.yml#L71
=> feat: Add a CR config option to disable SAR checking in the auth proxy.

app/ui-react/packages/models/src/extra.d.ts, app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
=> fix(ui): show the error message on failed saves

app/ui-react/syndesis/src/modules/integrations/components/editor/choice/SelectChoiceConfigModePage.tsx
=> fix(ENTESB-11769): Align data testid with other select action pages

app/ui-react/packages/ui/src/Integration/Editor/choice/ChoicePageCard.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/choice/SelectChoiceConfigModePage.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/choice/WithChoiceConfigurationForm.tsx
Back button is only enabled when no config on the step has been made yet.
=> fix(ENTESB-11578): Adds button that goes back to conditional flow choose action page

app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/PreviewResults.tsx
Improvement to SQL results table cell formatters.  If the cell string content is greater than 20chars, it is shortened and a tooltip is utilized.
=> ENTESB-11781 Fixes SQL results table row issue

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-assembly/package.json, app/ui-react/yarn.lock
https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-1.42.4
includes:
ENTESB-11715 Data mapper: Mapping preview fails to process Concatenate
=> chore: Update to AtlasMap 1.42.4

app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/customizer/DDBConnectorCustomizer.java, app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBConnectorMetaDataExtension.java, app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataRetrieval.java, app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/aws-ddb.json, app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataAdapterTest.java
Improving labels too to get better info on what to write there.
=> [ENTESB-11763] Adding minimal example for fields as auto-complete. 

app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
Fixes the documentation links for the next release
@TovaCohen this look okay?
=> chore: Update version number so doc URLs will be correct for 7.5

app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataRetrieval.java, app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataAdapterTest.java
AWSDDBMetadataAdapterTest was trying to connect to AWS DDB which results in different errors over time. Unit tests should not be connecting to foreign services. This mocks out the retrieval of AWS DDB table description.
Fixes #6808
=> fix: AWSDDBMetadataAdapterTest failures

install/operator/.lib.sh, install/operator/build/Dockerfile
Related https://github.com/syndesisio/syndesis/pull/6810
=> Change binary name from operator to syndesis-operator

app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientForm.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.css, app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.css, app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationCreateForm.tsx
Changes all DV buttons to pf3 style, per UX request.  Some style changes were required to get spacing between buttons correct.  Also made some css additions to improve the spacing around the DdlEditor.
=> ENTESB-11643 Revert all DV buttons to pf3

app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
https://issues.jboss.org/browse/ENTESB-11787
=> fix for ENTESB-11787 - Reconfiguration of SQL query step changes text to dropdown

app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DbMetaDataHelper.java
https://issues.jboss.org/browse/ENTESB-11633
=> Fix for ENTESB 11633 - setting limit to prevent timeout.

app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoClientCustomizer.java, app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCountTest.java, app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorFindByIdTest.java, app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorInsertTest.java, app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorRemoveTest.java, app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorSaveTest.java, app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorUpdateTest.java
=> fix(connector): converting all results in the same format

app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.css, app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx, app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionsGrid.tsx, app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionsGridCell.tsx
Improves layout and display of the DV cards in the 'import datasource' wizard.  Adopted same styling as Connection cards in syndesis, and also now use pf4 Gallery for the DvConnectionsGrid.
=> TEIIDTOOLS-783 Adjusts DV Connection card formatting

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-assembly/package.json, app/ui-react/yarn.lock
contains:
ENTESB-11870 Data mapper doesn't map anything when incoming data shape is a collection
=> chore: Update to AtlasMap 1.42.5

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-assembly/package.json, app/ui-react/yarn.lock
contains:
https://issues.jboss.org/browse/ENTESB-11870 Data mapper doesn't map anything when incoming data shape is a collection
=> chore: Update to AtlasMap 1.42.6

app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
fixes [ENTESB-11684](https://issues.jboss.org/browse/ENTESB-11684)
=> fix: suppress examining data shapes for extensions,

doc/sdh/cli/cmd_minishift.adoc, tools/bin/commands/crc, tools/bin/commands/minishift
Update bash scripts to use new syndesis-operator binary
=> chore: Update Minishift installation scripts to use the new operator binary

app/connector/mongodb/pom.xml, app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoClientCustomizer.java, app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoProducerCustomizer.java, app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/verifier/MongoConnectorVerifierExtension.java, app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorTestSupport.java, app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/verifier/MongoDBVerifierTest.java
* Using default connection database instead of "admin"
* Removed useless faulty integration creation in verifier test
fixes ENTESB-11853
=> fix(connector): default authentication database

app/ui-react/packages/auto-form/src/utils.ts
https://issues.jboss.org/browse/ENTESB-11911
=> ENTESB-11911 - FHIR- create: Error retrieving resource schema for type

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-assembly/package.json, app/ui-react/packages/atlasmap-assembly/src/app/data-mapper-host.component.ts, app/ui-react/yarn.lock
Contains:
https://issues.jboss.org/browse/ENTESB-11959 - Data mapper fails when editing already created integration
=> chore: Update to AtlasMap 1.42.9

app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
=> fix: unbreak the connection name validation

doc/modules/tutorials/p_t2sf-add-filter-step.adoc
=> user doc: Correct a typo - changes "contain" to "contains"

.github/workflows/rebase.yml
With this we can rebase pull requests with the `/rebase` comment.
=> chore(dev-workflow): add support for rebase

.github/PULL_REQUEST_TEMPLATE/complete.md
Which was missing here: https://github.com/syndesisio/syndesis/community
=> Adding a PR template

install/operator/pkg/cmd/internal/install/install_forge.go
* Fixes the ENDPOINTS_TEST_SUPPORT_ENABLED var as it has been renamed
to TEST_SUPPORT_ENABLED
* Sorts the parameters list
=> ENTESB-11772: Fixes for outstanding errors

doc/assemblies/connecting/as_connecting-to-box.adoc, doc/connecting/master.adoc, doc/modules/connecting/p_adding-box-connection-finish.adoc, doc/modules/connecting/p_adding-box-connection-middle.adoc, doc/modules/connecting/p_creating-box-connections.adoc, doc/modules/connecting/p_register-with-box.adoc, doc/modules/connecting/r_supported-connectors.adoc
Reviewed by Claudio and Andrej Vano
=> user doc: New doc for the Box connector 

tools/bin/commands/crc, tools/bin/commands/install, tools/bin/commands/util/openshift_funcs, tools/bin/commands/util/openshift_funcs.bats, tools/bin/commands/util/operator_funcs, tools/bin/commands/util/operator_funcs.bats, tools/bin/syndesis
This PR backports a series of changes from master to make the install scripts(`syndesis install`, `syndesis crc` and `syndesis minishift`) work with the operator binary
=> Update install scripts to use the syndesis operator binary

app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/customizer/DDBConnectorCustomizer.java, app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/customizer/DDBConnectorCustomizerQuery.java, app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBConfiguration.java, app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBGenericOperation.java, app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBInsertItemTest.java, app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBQueryItemTest.java, app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBRawOptionsTest.java, app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataAdapterTest.java, app/connector/aws-ddb/src/test/resources/logback-test.xml
Due to caching issues on the DDB side. 
Plus, some implementation improvements and test extensions I did while fixing this.
=> [ENTESB-11767] Fixing PutItem returning an empty json 

app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java
Using simple refactoring I was able to remove most of the complexity out of the ProjectGenerator, as can be seen in the removal of `@SuppressWarnings` targeting PMD issues.
=> refactor: reduce complexity in ProjectGenerator

app/common/util/src/main/java/io/syndesis/common/util/KeyGenerator.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/environment/EnvironmentHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/support/SupportHandler.java, app/server/filestore/src/main/java/io/syndesis/server/filestore/impl/FileStoreSupport.java
This removes `throws ...` from methods that throw unchecked exceptions.
=> refactor: remove needless exception declaration

doc/assemblies/connecting/as_connecting-to-amazon-dynamodb.adoc
=> user doc: Corrects a copy/paste mistake

app/server/credential/src/main/java/io/syndesis/server/credential/CredentialFlowState.java, app/server/credential/src/main/java/io/syndesis/server/credential/OAuth1CredentialFlowState.java, app/server/credential/src/main/java/io/syndesis/server/credential/OAuth2CredentialFlowState.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java
https://issues.jboss.org/browse/ENTESB-12038
ENTESB-12005 NullPointerException when saving an oauth connection description
https://issues.jboss.org/browse/ENTESB-12005
=> ENTESB-12038 credentials of a connector attached to a connection are plain text

app/ui-react/packages/ui/src/Integration/Editor/choice/ChoicePageCard.css, app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
fixes [ENTESB-11470](https://issues.jboss.org/browse/ENTESB-11470)
also makes the api error look slightly nicer when it's shown in the short term
while looking into another issue.
=> fix: tighten up the layout for the conditional flow form

app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/mongodb3.json
=> fix(connector): mongodb connector json

app/ui-react/packages/ui/stories/Data/DvConnection/DvConnectionsToolbarSkeleton.stories.tsx, app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
=> fix: dvconnectionSkeleton is not sized well TEIIDTOOLS784

doc/assemblies/connecting/as_connecting-to-email-servers.adoc, doc/connecting/master.adoc, doc/modules/connecting/p_creating-a-connection-to-an-imap-or-pop3-email-server.adoc, doc/modules/connecting/p_creating-a-connection-to-an-smtp-email-server.adoc, doc/modules/connecting/p_obtaining-email-to-trigger-integration-execution.adoc, doc/modules/connecting/p_sending-email-from-an-integration.adoc, doc/modules/connecting/r_supported-connectors.adoc
New doc for connecting to email servers. Reviewed by Paul Richardson and Alice Rum.
=> user doc: Email connector

app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/mongodb3.json, app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorNotSupportedCamelOperationTest.java, app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorNotSupportedSyndesisOperationTest.java
Adding proper customizer to check validity of operations
closes ENTESB-12091
=> feat(connector): mongodb operation validity check

doc/modules/connecting/p_adding-mongodb-connections-write.adoc, doc/modules/connecting/p_creating-mongodb-connections.adoc
Updates were reviewed by Pasquale.
=> user doc: Add operation descriptions for MongoDB connection producer action

doc/customizing/master.adoc, doc/modules/customizing/p_rebranding-the-user-interface.adoc
=> user doc: Add instructions for rebranding the UI

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-assembly/package.json, app/ui-react/yarn.lock
Contains:
- atlasmap/atlasmap#1432 upgrade to SpingBoot 1.5.19 and Spring Security 4.2.13
=> chore: Update to AtlasMap 1.42.10

app/connector/box/src/main/java/io/syndesis/connector/box/BoxConnector.java
https://issues.jboss.org/browse/ENTESB-11433
=> ENTESB-11433 Box - no property for fileName in upload action

tools/bin/commands/release
The tagging needs to happen before the docker_push ...
=> Move operator tagging section

tools/bin/commands/release
Force push the tags after they were created by the github release.
=> Push tags at the end of the release

app/connector/knative/pom.xml, app/pom.xml, app/server/openshift/src/test/java/io/syndesis/server/openshift/OpenShiftServiceImplTest.java
=> chore(deps): upgrade kubernetes/openshift client to 4.6.1

app/extension/bom/pom.xml, app/integration/bom-camel-k/pom.xml, app/integration/bom/pom.xml, app/pom.xml
* Adding first 7.6 camel fuse development release dependency
=> chore(deps): camel fuse bump

tools/misc/syndesisCamelVersion.sh
Those who uses mac, review please.
=> bash script to change camel version

app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DbMetaDataHelper.java
Seems that the order in which the columns are read is significant for some databases for certain combinations of Oracle Database / Oracle JDBC driver if we try to fetch `COLUMN_DEF` column after IS_AUTOINCREMENT we get: `java.sql.SQLException: Stream has already been closed`
The reason for this could like in the fact that the `IS_AUTOINCREMENT` column is the last column the table metadata ResultSet has, and once we try to read it we moved beyond the previous columns in the ResultSet coupled with the fact that reading could be unbuffered or that on reaching the end of the row data that bit of stream is closed automatically this issue was reported against Oracle 12.1 in: https://issues.jboss.org/browse/ENTESB-12159
=> chore(connector/sql): workaround for Oracle

app/server/metrics/prometheus/pom.xml, app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/Utils.java
https://issues.jboss.org/browse/ENTESB-12170
=> ENTESB-12170 Integration metrics don't work

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java
https://issues.jboss.org/browse/ENTESB-12204
* reverting ENTESB-12038 credentials of a connector attached to a connection are plain text
=> ENTESB-12204 Unable to authenticate Twitter OAuth connection

app/ui-react/package.json, app/ui-react/packages/auto-form/package.json, app/ui-react/packages/ui/package.json, app/ui-react/packages/ui/src/Layout/AppLayout.tsx, app/ui-react/yarn.lock
Fixes IUXD-28 by implementing dark vertical navigation theme.
=> feat(ui): change vertical navigation to dark nav

install/operator/deploy/crds/syndesis_v1alpha1_syndesis_crd.yaml, install/operator/go.mod, install/operator/pkg/syndesis/configuration/configuration.go, install/operator/pkg/syndesis/configuration/configuration_test.go, install/operator/vendor/github.com/spf13/cast/LICENSE, install/operator/vendor/github.com/spf13/cast/Makefile, install/operator/vendor/github.com/spf13/cast/README.md, install/operator/vendor/github.com/spf13/cast/cast.go, install/operator/vendor/github.com/spf13/cast/caste.go, install/operator/vendor/github.com/spf13/cast/go.mod, install/operator/vendor/github.com/spf13/cast/go.sum, install/operator/vendor/modules.txt
If an environement variable (ROUTE_HOSTNAME) is defined for routeHostname, take that and dont
figure it out based on the route.Host
=> Set routeHostname from env if available

app/pom.xml
=> enh: fix build log levels for react-ui module

app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/meta/MongoDBMetadataRetrieval.java
This makes the `isFilterAction` method static and removes the `@SuppressWarnings`
=> refactor(connector/mongodb): static method

app/connector/google-sheets/pom.xml, app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsConnectorHelper.java, app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesSplitResultsCustomizerTest.java
Fixes divergence in google-sheets connector as backport of camel component to 2.23.x is done
=> fix(ENTESB-12127): (camel-fuse-2.23.x) Fix divergence in google-sheets

app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.css, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoList.css, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoList.tsx
- Jira Issue https://issues.jboss.org/browse/TEIIDTOOLS-784
- With this pr add the vertical scroll property to ConnectionSchemaList with max-height of 45em.
- UI Look & feel
=> fix: added vertical max height and scroll TEIIDTOOLS-784

app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
fixes #7162
@squakez FYI, also with this fix I believe you'd need to delete and re-add the step.
=> fix: ensure we apply the updated descriptor

app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/user/UserHandlerTest.java
It'd doesn't seem to require the mock OpenShift API server.
=> refactor(server): cleanup user handler test

tools/bin/commands/build, tools/bin/commands/util/maven_funcs
Adds support for specifying `-s` or `--settings` to the `syndesis` shell
script to configure the Maven with specified Maven settings XML file.
=> chore(build): Maven settings support

app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.css, app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx, app/ui-react/packages/ui/stories/Data/Virtualizations/PublishStatusWithProgress.stories.tsx
- Jira Issue https://issues.jboss.org/browse/TEIIDTOOLS-849
- with this PR changes in VirtualizationDetailsHeader and VirtualizationListItem
-- Showing the modified both the places
--changes in UI for header and list view
=> Teiidtools 849

app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvCacheHitMetric.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvClientSessionMetric.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvMetricsContainer.css, app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvMetricsContainer.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvRequestMetric.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvUptimeMetric.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
- PR for Matrics layout changes.
- Stan review comment in PublishStatusWithProgress.tsx
=> fix: TEIIDTOOLS-846 DV Metrics Layout improvements

app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationBreadcrumb.tsx, app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json, app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json, app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json, app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx, app/ui-react/syndesis/src/modules/data/ViewsImportApp.tsx, app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json, app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json, app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json, app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationImportPage.tsx, app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
- shortened breadcrumb segment to 'Data' to match the left nav menu
- included 'Home' segment in VirtualizationImportPage breadcrumb for consistency with other pages
- added 'Virtualization' and 'View' text to the named virtualization and view breadcrumb segments
=> TEIIDTOOLS-819 DV Breadcrumb improvements

app/common/jaeger-spring-boot-starter/pom.xml, app/integration/runtime-camelk/pom.xml, app/integration/runtime-springboot/pom.xml, app/integration/runtime/pom.xml, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/tracing/TracingInterceptStrategy.java, app/pom.xml, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/activity/ActivityHandler.java, app/server/logging/jaeger/src/main/java/io/syndesis/server/logging/jaeger/service/JaegerActivityTrackingService.java, app/server/logging/jaeger/src/test/resources/expected-activities.json
https://issues.jboss.org/browse/ENTESB-11703
=> ENTESB-11703 Update to Jaeger 1.0.0 & OpenTracing API 0.33.0

install/operator/pkg/syndesis/action/upgrade.go
With https://github.com/syndesisio/syndesis/pull/7255 I accidentally deleted the most important part of the upgrade process: to create the upgrade pod.
=> Put back upgrade pod creation

app/ui-react/packages/ui/src/index.css, app/ui-react/syndesis/public/index.html, app/ui-react/syndesis/src/app/App.css
Add red hat font across entire UI
=> add red hat font to UI

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/tracing/TracingActivityTrackingPolicy.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/tracing/TracingInterceptStrategy.java, app/server/logging/jaeger/pom.xml, app/server/logging/jaeger/src/main/java/io/syndesis/server/logging/jaeger/service/JaegerActivityTrackingService.java, app/server/logging/jaeger/src/test/java/io/syndesis/server/logging/jaeger/service/JaegerActivityTrackingServiceTest.java, app/server/logging/jaeger/src/test/resources/example-jaeger-trace-result.json, app/server/logging/jaeger/src/test/resources/expected-activities.json
https://issues.jboss.org/browse/ENTESB-12380
Accordindly to https://opentracing.io/specification/conventions/ use `span.kind` tag instead of `kind`, as there could be other services using the `span.kind`
=> ENTESB-12380 Webhook step in activity log causes NPE on the server when Jaeger addon is enabled

install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
To keep aligned with 1.8 https://github.com/syndesisio/syndesis/pull/7310
=> Change DisableSarCheck name for CR

app/ui-react/packages/ui/stories/Data/Views/EmptyViewsState.stories.tsx, app/ui-react/packages/ui/stories/Data/Views/ViewList.stories.tsx, app/ui-react/packages/ui/stories/Data/Virtualizations/SqlClientContent.stories.tsx, app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationDetailHistoryTable.stories.tsx, app/ui-react/syndesis/src/modules/data/ViewsImportApp.tsx, app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json, app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json, app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json, app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx, app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
- Jira Issue https://issues.jboss.org/browse/ENTESB-12077
- With PR changed the nomenclature from 'Import Data Source' to 'Import Views' in Virtualization View pages.
- Screenshots
=> Entesb 12077

app/ui-react/packages/api/src/helpers/integrationFunctions.ts, app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
fixes [ENTESB-11680](https://issues.jboss.org/browse/ENTESB-11680)
And found a little unrelated bug while looking into the Jira, so this fixes that too.
=> fix: fix typo and fix a related issue with the error code gathering

app/.mvn/wrapper/maven-wrapper.properties, tools/bin/commands/build
Also makes the Maven less verbose when downloading dependencies
=> chore(deps): upgrade Maven version to 3.6.3

app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/tracing/TracingAutoConfiguration.java
https://issues.jboss.org/browse/ENTESB-11979
=> ENTESB-11979 Enabling Jaeger add-on causes errors in integrations

app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.css, app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx, app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor-styling.css, app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor.stories.tsx
- Jira Issue https://issues.jboss.org/browse/TEIIDTOOLS-810
- Fixed the UI for DdlEditor Page.
=> Teiidtools 810

app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiSecurityScheme.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiValidationRules.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v2/Oas20ValidationRulesTest.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRulesTest.java
=> [Backport 1.9.x]: Fix OpenAPI auth validation rules

app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.css, app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.css, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.css, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx, app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationDetailsHeader.stories.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
- Jira issue https://issues.redhat.com/browse/TEIIDTOOLS-874
- With this PR modified virtualization details header
- Screenshots
=> Teiidtools 874

.github/workflows/backport.yml
This replaces the `tibdex/backport` with `syndesisio/backport-action`.
=> chore: configure syndesisio/backport-action

app/dv/src/main/java/io/syndesis/dv/server/endpoint/MetadataService.java, app/dv/src/test/java/io/syndesis/dv/server/endpoint/MetadataServiceTest.java
backport of TEIIDTOOLS-861 to 1.9.x
=> TEIIDTOOLS-861 removing duplicate entries

app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.css, app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.css, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.css, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx, app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationDetailsHeader.stories.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
=> TEIIDTOOLS-874 backport

app/.mvn/maven.config, app/excluded_tests.txt
=> chore(test): exclude ServiceVdbGeneratorTest

app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/logging/IntegrationLoggingCamelContextConfiguration.java, app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/tracing/TracingCamelContextConfiguration.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/ActivityTrackingInterceptStrategy.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/tracing/TracingActivityTrackingPolicy.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/tracing/TracingInterceptStrategy.java, app/server/logging/jaeger/src/main/java/io/syndesis/server/logging/jaeger/service/JaegerActivityTrackingService.java, app/server/logging/jaeger/src/test/resources/example-jaeger-trace-result.json, app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java
https://issues.redhat.com/browse/ENTESB-12441
=> ENTESB-12441 The activity log doesn't show error step

app/connector/kafka/src/main/resources/META-INF/syndesis/connector/kafka.json, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java
* Retrieve the result of meta dynamic properties and enrich connector properties
* Enable dynamic properties on Kafka connector
Closes ENTESB-12559
Please, consider that we will improve the code introduced in this PR when working on [ENTESB-12498](https://issues.redhat.com/browse/ENTESB-12498)
=> feature(server): enrich connector with dynamic properties

app/dv/pom.xml, app/dv/src/main/java/io/syndesis/dv/openshift/TeiidOpenShiftClient.java, app/dv/src/main/java/io/syndesis/dv/server/endpoint/MetadataService.java, app/dv/src/main/java/io/syndesis/dv/server/endpoint/ServiceVdbGenerator.java, app/dv/src/test/java/io/syndesis/dv/server/endpoint/EditorServiceTest.java, app/dv/src/test/java/io/syndesis/dv/server/endpoint/MetadataServiceTest.java, app/dv/src/test/java/io/syndesis/dv/server/endpoint/ServiceVdbGeneratorTest.java, app/dv/src/test/resources/generated-pom.xml, app/excluded_tests.txt, app/pom.xml
teiid, tsb versions updates
along with the property change to support different metadata handling
and removing tabs
=> TEIIDTOOLS-840 TEIIDTOOLS-891 syndesisio#7393

app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiValidationRules.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/Oas20ValidationRules.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30DataShapeGeneratorHelper.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30FormDataHelper.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ModelHelper.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ParameterGenerator.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30PropertyGenerators.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRules.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30DataShapeGeneratorHelperTest.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30ParameterGeneratorTest.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRulesTest.java
Manual backport 
#7455 Add OpenAPI 3.x specific validation rule for server base path
#7459 Add support for OpenAPI 3.x global parameter definitions
=> [Backport-1.9.x] Add support for OpenAPI 3.x global parameter definitions

app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionListView.tsx, app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
- Can select the multiple tables from any connection available. 
- Screenshot
=> fix: multi select tables from diff connection issue

app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/logging/IntegrationLoggingCamelContextConfiguration.java, app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/tracing/TracingCamelContextConfiguration.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/ActivityTrackingInterceptStrategy.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/tracing/TracingActivityTrackingPolicy.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/tracing/TracingInterceptStrategy.java, app/server/logging/jaeger/src/main/java/io/syndesis/server/logging/jaeger/service/JaegerActivityTrackingService.java, app/server/logging/jaeger/src/test/resources/example-jaeger-trace-result.json, app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java
https://issues.redhat.com/browse/ENTESB-12441
=> ENTESB-12441 The activity log doesn't show error step - backport 1.9.x

app/ui-react/packages/api/src/useVirtualizationHelpers.tsx, app/ui-react/packages/models/src/dv.d.ts, app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionListView.tsx, app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx, app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx, app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx, app/ui-react/syndesis/src/modules/data/shared/ConnectionTables.tsx
Backporting TTOOLS-880 and TTOOLS-900 to 1.9.x
=> Create view backports

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-assembly/package.json
https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-1.43.0
=> chore: Update to AtlasMap 1.43.0

app/ui-react/yarn.lock
A followup on #7513 to update the `yarn.lock` file.
=> chore(deps): update yarn.lock

app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/aws-ddb.json
=> [Backport-1.9.x]: Change DDB connector name

app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
=> [Backport 1.9.x] fix: rework VirtualizationListItem

app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiSchemaValidator.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/Oas20SchemaValidator.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30SchemaValidator.java, app/server/api-generator/src/main/resources/schema/openapi-3.0-schema.json, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v2/Oas20SchemaValidatorTest.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30SchemaValidatorTest.java
=> [Backport 1.9.x]: Add schema validation for OpenAPI 3.x

app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
PMD was complaining. I did a couple refactorings more to avoid unused variable assignments. deprecated functions and such.
=> Fixing PMD rules. Reducing complexity and simplifying code.

app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
-- Removed the DV version details form the virtualization list page.
=> fix: removing the version details from the DV list view

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-assembly/package.json, app/ui-react/yarn.lock
Fixes ENTESB-12632 ENTESB-12599 ENTESB-12619
=> chore: Update to AtlasMap 1.43.1

app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/aws-ddb.json, app/connector/box/src/main/resources/META-INF/syndesis/connector/box.json, app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/mongodb3.json
https://issues.redhat.com/browse/ENTESB-12657
=> Connector consolidation. AWS Dynamo DB, Mongo DB and Box are no longer Tech Preview.

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-assembly/package.json, app/ui-react/yarn.lock
This should fix the problem that data mapper UI is frozen (un-clickable)
=> chore: Update to AtlasMap 1.43.2

app/ui-react/packages/api/src/index.ts, app/ui-react/packages/api/src/useVirtualizationRuntimeMetadata.tsx, app/ui-react/packages/models/src/dv.d.ts, app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.css, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx, app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaList.stories.tsx, app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaListItem.stories.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx, app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx, app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx, app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Backporting PR #7561, PR #7537, PR #7592 to 1.9.x branch
=> DV backports

app/pom.xml
Reverts syndesisio/syndesis#7642
=> Revert "chore(deps): bump aws-java-sdk-core from 1.11.415 to 1.11.712 in /app"

app/common/jaeger-spring-boot-starter/pom.xml, app/common/jaeger-spring-boot-starter/src/main/java/io/syndesis/common/jaeger/JaegerConfiguration.java, app/common/jaeger-spring-boot-starter/src/main/java/io/syndesis/common/jaeger/MicrosecondPrecisionClock.java, app/server/logging/jaeger/pom.xml, app/server/logging/jaeger/src/main/java/io/syndesis/server/logging/jaeger/service/JaegerActivityTrackingService.java, app/server/logging/jaeger/src/test/java/io/syndesis/server/logging/jaeger/service/JaegerActivityTrackingServiceTest.java, app/server/logging/jaeger/src/test/resources/example-jaeger-trace-result.json, app/server/logging/jaeger/src/test/resources/expected-activities.json
https://issues.redhat.com/browse/ENTESB-12598
=> ENTESB-12598 The order of steps in the activity log is not in order in which the steps are defined.

app/common/jaeger-spring-boot-starter/pom.xml, app/common/jaeger-spring-boot-starter/src/main/java/io/syndesis/common/jaeger/JaegerConfiguration.java, app/common/jaeger-spring-boot-starter/src/main/java/io/syndesis/common/jaeger/MicrosecondPrecisionClock.java, app/server/logging/jaeger/pom.xml, app/server/logging/jaeger/src/main/java/io/syndesis/server/logging/jaeger/service/JaegerActivityTrackingService.java, app/server/logging/jaeger/src/test/java/io/syndesis/server/logging/jaeger/service/JaegerActivityTrackingServiceTest.java, app/server/logging/jaeger/src/test/resources/example-jaeger-trace-result.json, app/server/logging/jaeger/src/test/resources/expected-activities.json
https://issues.redhat.com/browse/ENTESB-12598
=> ENTESB-12598 The order of steps in the activity log is not in order in which the steps are defined. 1.9.x

install/operator/.gitignore, install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go, install/operator/pkg/syndesis/versions/versions.go, install/operator/pkg/syndesis/versions/versions_test.go
chore: remove unused constant ReadWriteMany
chore: fix typo in Spec.Components.Database.URL
=> fix: unable to set memory limits for syndesis components in CR

doc/assemblies/integrating-applications/as_adding-api-connectors.adoc, doc/modules/customizing/c_about-api-connectors.adoc, doc/modules/customizing/r_develop-connector-extensions.adoc, doc/modules/integrating-applications/p_add-custom-step.adoc, doc/modules/integrating-applications/p_add-data-mapping-step.adoc, doc/modules/integrating-applications/p_add-split-step.adoc, doc/modules/integrating-applications/p_add-template-step.adoc, doc/modules/integrating-applications/p_adding-steps-to-conditional-flows.adoc, doc/modules/integrating-applications/p_create-api-provider-integration.adoc, doc/modules/integrating-applications/p_creating-api-connectors.adoc, doc/modules/integrating-applications/p_general-procedure-for-obtaining-authorization.adoc, doc/modules/integrating-applications/p_using-advanced-expression-builder.adoc, doc/modules/integrating-applications/p_using-basic-expression-builder.adoc, doc/modules/integrating-applications/r_about-json-schema-for-http-requests.adoc, doc/modules/integrating-applications/r_available-transformations.adoc, doc/modules/integrating-applications/r_example-missing-unwanted-data.adoc, doc/modules/integrating-applications/r_example-processing-collection.adoc, doc/modules/integrating-applications/r_how-requests-are-handled.adoc, doc/modules/integrating-applications/r_workflow-example.adoc
Translation of "Integrating Applications with Fuse Online" identified a number problems that needed fixing such as: 
- Link target text that is out of date.
- Links that are broken
- Sentences that need clarification. 
This fixes all the problems identifies by Junko Ito, the translator.
=> user doc: Fix issues identified by localization

app/test/integration-test/pom.xml, app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiprovider/TodoApi-export/model.json, app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiprovider/TodoListApi-export/model.json, app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiprovider/TodoOpenApiV3-export/model.json
- Add missing exceptionHandler to API provider integrations for proper error handling (Relates to ENTESB-12841)
- Fix dependency issue with javax.activation and javax.mail
=> fix: Fix nightly integration tests

install/operator/.gitignore, install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go, install/operator/pkg/syndesis/versions/versions.go, install/operator/pkg/syndesis/versions/versions_test.go
* fix: unable to set memory limits for syndesis components in CR
chore: remove unused constant ReadWriteMany
chore: fix typo in Spec.Components.Database.URL
* chore: migrate resources from v1alpha1 to v1beta1
* chore: comment out VAM instead of deleting
(cherry picked from commit 851b5f61190e3132a27b3135990708ee421c508e)
=> fix: unable to set memory limits for syndesis components in CR (#7653)

app/connector/rest-swagger/pom.xml, app/connector/rest-swagger/src/main/resources/META-INF/syndesis/connector/rest-swagger.json, app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/DescriptorTest.java, app/server/api-generator/src/test/resources/openapi/v2/basic_auth.unified_connector.json, app/server/api-generator/src/test/resources/openapi/v2/complex_xml.unified_connector.json, app/server/api-generator/src/test/resources/openapi/v2/damage_service.unified_connector.json, app/server/api-generator/src/test/resources/openapi/v2/kie-server.unified_connector.json, app/server/api-generator/src/test/resources/openapi/v2/machine_history.unified_connector.json, app/server/api-generator/src/test/resources/openapi/v2/petstore.unified_connector.json, app/server/api-generator/src/test/resources/openapi/v2/petstore_xml.unified_connector.json, app/server/api-generator/src/test/resources/openapi/v2/reverb.unified_connector.json, app/server/api-generator/src/test/resources/openapi/v2/todo.unified_connector.json, app/server/api-generator/src/test/resources/openapi/v3/basic_auth.unified_connector.json, app/server/api-generator/src/test/resources/openapi/v3/complex_xml.unified_connector.json, app/server/api-generator/src/test/resources/openapi/v3/damage_service.unified_connector.json, app/server/api-generator/src/test/resources/openapi/v3/kie-server.unified_connector.json, app/server/api-generator/src/test/resources/openapi/v3/machine_history.unified_connector.json, app/server/api-generator/src/test/resources/openapi/v3/petstore.unified_connector.json, app/server/api-generator/src/test/resources/openapi/v3/petstore_xml.unified_connector.json, app/server/api-generator/src/test/resources/openapi/v3/reverb.unified_connector.json, app/server/api-generator/src/test/resources/openapi/v3/todo.unified_connector.json, app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoOpenApiV2Connector-export/model.json, app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoOpenApiV3Connector-export/model.json, app/ui-react/packages/ui/stories/Customization/ApiConnectorListView.stories.tsx, app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json, app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.it.json, app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.ru.json
Manual backport of PRs #7667 #7668
=> [Backport-1.9.x] OpenAPI 3.x fixes

install/operator/go.mod, install/operator/go.sum, install/operator/pkg/apis/syndesis/v1beta1/register.go, install/operator/pkg/cmd/internal/run/run.go, install/operator/pkg/generator/generator.go
Also creates service monitor. Change configuration variable name to avoid collition with package name.
=> chore: add metrics for product and operator version

install/operator/go.mod, install/operator/go.sum, install/operator/pkg/apis/syndesis/v1beta1/register.go, install/operator/pkg/cmd/internal/run/run.go, install/operator/pkg/generator/generator.go
Also creates service monitor. Change configuration variable name to avoid collition with package name.
(cherry picked from commit a3c709a7d4c1cfa23bae5d08a8d2f3d8dd03915e)
=> chore(backport): add metrics for product and operator version (#7687)

app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiValidationRules.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/Oas20ValidationRules.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRules.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v2/Oas20ValidationRulesTest.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRulesTest.java
Add warnings when using
- links
- callbacks
- openIdConnect auth type (warning has been there already)
This PR also fixes an issue with validating request body schemas. We need to use different validation logic for Open API 2.x and 3.x when validating request body schemas.
=> fix(ENTESB-12793): Add warnings when using unsupported OpenAPI 3.x features

app/connector/kafka/pom.xml, app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaMetaDataRetrieval.java, app/connector/kafka/src/main/java/io/syndesis/connector/kafka/model/crd/Address.java, app/connector/kafka/src/main/java/io/syndesis/connector/kafka/model/crd/Kafka.java, app/connector/kafka/src/main/java/io/syndesis/connector/kafka/model/crd/KafkaResourceList.java, app/connector/kafka/src/main/java/io/syndesis/connector/kafka/model/crd/Listener.java, app/connector/kafka/src/main/java/io/syndesis/connector/kafka/model/crd/Status.java, app/connector/kafka/src/test/java/io/syndesis/connector/kafka/KafkaMetaDataRetrievalTest.java, app/connector/kafka/src/test/java/io/syndesis/connector/kafka/model/crd/AddressTest.java, app/connector/kafka/src/test/java/io/syndesis/connector/kafka/model/crd/KafkaResourceListTest.java, app/connector/kafka/src/test/java/io/syndesis/connector/kafka/model/crd/KafkaTest.java, app/connector/kafka/src/test/java/io/syndesis/connector/kafka/model/crd/ListenerTest.java, app/connector/kafka/src/test/java/io/syndesis/connector/kafka/model/crd/StatusTest.java, app/connector/kafka/src/test/resources/io/syndesis/connector/kafka/kafka-crd.yaml, app/connector/kafka/src/test/resources/io/syndesis/connector/kafka/kafka-topic-crd.yaml, app/connector/kafka/src/test/resources/io/syndesis/connector/kafka/kafkas.yaml
Adds tests and refactors to use typesafe access to the deserialized
custom resource DTOs.
=> refactor(c/kafka): cleanup Kafka connector

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-assembly/package.json, app/ui-react/yarn.lock
https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-1.43.3
Backport of #7711
=> chore: Update to AtlasMap 1.43.3

app/connector/debezium/pom.xml, app/connector/debezium/src/main/java/io/syndesis/connector/debezium/DebeziumConsumerCustomizer.java, app/connector/debezium/src/main/java/io/syndesis/connector/debezium/DebeziumMetaDataRetrieval.java, app/connector/debezium/src/test/java/io/syndesis/connector/debezium/DebeziumMetaDataRetrievalTest.java
Adds test (there were none), fixes issues reported by semantic checks,
makes sure not to log too much at levels that would cause confusion, and
formats code to look sane.
=> refactor(c/debezium): cleanup debezium connector

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/ExtensionHandler.java, app/ui-react/syndesis/src/shared/EntityIcon.tsx
https://issues.jboss.org/browse/ENTESB-12544
Fixes https://github.com/syndesisio/syndesis/issues/7419
=> ENTESB-12544 Syndesis step extension fails when included in an integration with an API endpoint

doc/connecting/master.adoc, doc/integrating-applications/master.adoc, doc/modules/connecting/p_enabling-connections-to-knative-resources.adoc, doc/shared/attributes.adoc, doc/tutorials/master.adoc
Updated to new procedure for enabling connections to Knative resources. Reviewed by Nicola. Approved by Martin Muzikar. 
This also contains updates to master.adoc files for all book just to update the release number. 
Also, an updated attributes file.
=> user doc: Update Knative connector doc

app/ui-react/packages/ui/src/Integration/Details/IntegrationActions.css, app/ui-react/packages/ui/src/Integration/Details/IntegrationActions.tsx, app/ui-react/packages/ui/src/Integration/IntegrationsListItem.css, app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx
- fixes [ENTESB-12325](https://issues.redhat.com/browse/ENTESB-12325)
=> fix(ENTESB-12325): mv edit action to int list row, rm check for canEdit

app/connector/mongodb/pom.xml, app/dv/pom.xml, app/dv/src/main/resources/s2i/template-pom.xml, app/dv/src/test/resources/generated-pom.xml, app/integration/bom/pom.xml, app/pom.xml
We had two different versions of MongoDB plus a third one coming from Camel dependencies.
=> [ENTESB-12785] Align MongoDB versions

app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiValidationRules.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/Oas20ValidationRules.java, app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRules.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v2/Oas20ValidationRulesTest.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRulesTest.java
Manual backport of #7709 
Add warnings when using
- links
- callbacks
- openIdConnect auth type (warning has been there already)
=> [Backport-1.9.x]: Add warnings when using unsupported OpenAPI 3.x features

app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
fixes [ENTESB-11976](https://issues.redhat.com/browse/ENTESB-11976)
=> fix: Hide steps that can't be used at the end of a flow

.circleci/config.yml, install/operator/.lib.sh, install/operator/go.sum, install/operator/vendor/github.com/operator-framework/operator-sdk/pkg/metrics/metrics.go, install/operator/vendor/github.com/operator-framework/operator-sdk/version/version.go, install/operator/vendor/modules.txt
chore(dep): use golang:1.13.7 to build operator
=> chore: add missing content to vendor folder

app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Reverts syndesisio/syndesis#7724
Gonna be a blocking issue for folks going by that end 2 end test result, this will need more investigation.
=> Revert "fix: Hide steps that can't be used at the end of a flow"

app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.css, app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
fixes [ENTESB-12659](https://issues.redhat.com/browse/ENTESB-12659)
=> fix(ENTESB-12659): integration editor list misalignment

app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
=> Fix: virtualization state not geting updated

app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.css, app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
backporting from https://github.com/syndesisio/syndesis/pull/7729
=> fix list style for integration editor (backport)

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/ExtensionHandler.java, app/ui-react/syndesis/src/shared/EntityIcon.tsx
https://issues.jboss.org/browse/ENTESB-12544
=> Fix ENTESB-12544 Syndesis step extension fails when included in an integration with an API endpoint - backport 1.9.x

app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
- Jira Issue https://issues.redhat.com/browse/TEIIDTOOLS-924
- Fixed intermittent UI issue with: virtualizationId used in API call
=> Fix: route param being directly used without resolving value

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-assembly/package.json, app/ui-react/yarn.lock
https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-1.43.4
=> chore: Update to AtlasMap 1.43.4

app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarEventModel.java, app/connector/google-calendar/src/test/java/io/syndesis/connector/calendar/GoogleCalendarEventModelTest.java, app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/AuthenticationCustomizerTest.java
=> [Backport-1.9.x]: Enhance Google calendar date time with seconds of hour

doc/modules/integrating-applications/p_configure-publish-api-provider-quickstart.adoc, doc/modules/integrating-applications/p_create-api-provider-integration.adoc, doc/modules/integrating-applications/p_create-integration-operation-flows.adoc, doc/modules/integrating-applications/p_updating-integrations.adoc
Updated a URL to have "1.9" instead of "1.8".
Changed "Create flow" to "Edit flow" where needed.
=> user doc: Ensure "1.9" in URLs, and "Edit flow" where needed.

app/connector/dropbox/src/main/resources/META-INF/syndesis/connector/dropbox.json
https://issues.jboss.org/browse/ENTESB-11791
=> ENTESB-11791 Dropbox upload mode looks initialized in the UI but isn't

app/connector/dropbox/src/main/resources/META-INF/syndesis/connector/dropbox.json
https://issues.jboss.org/browse/ENTESB-11791
=> ENTESB-11791 Dropbox upload mode looks initialized in the UI but isn't - backport 1.9.x

app/ui-react/syndesis/src/app/UI.tsx, app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
fixes [ENTESB-12868](https://issues.redhat.com/browse/ENTESB-12868)
@TovaCohen FYI
=> fix: Update template to use links from locale

app/ui-react/syndesis/src/app/UI.tsx, app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
fixes [ENTESB-12868](https://issues.redhat.com/browse/ENTESB-12868)
And also updates the commit to point to the 7.6 URLs
=> fix: Update template to use links from locale (backport)

app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorNothingToConfigure.tsx, app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorNothingToConfigureAlert.tsx, app/ui-react/packages/ui/src/Integration/Editor/index.ts, app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/NothingToConfigure.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx, app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
fixes [ENTESB-12888](https://issues.redhat.com/browse/ENTESB-12888)
=> fix: If a step has no configurable properties, show that and don't error out (backport)

app/ui-react/packages/auto-form/package.json, app/ui-react/packages/ui/package.json, app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx, app/ui-react/packages/ui/src/Layout/AppTopMenu.tsx, app/ui-react/yarn.lock
in preparation for [ENTESB-12896](https://issues.redhat.com/browse/ENTESB-12896)
=> chore: minor patternfly 4 upgrade and related changes 

app/test/integration-test/src/test/java/io/syndesis/test/itest/apiconnector/TodoApiV2ApiKeyInHeader_IT.java, app/test/integration-test/src/test/java/io/syndesis/test/itest/apiconnector/TodoApiV2ApiKeyInQuery_IT.java, app/test/integration-test/src/test/java/io/syndesis/test/itest/apiconnector/TodoApiV2BasicAuth_IT.java, app/test/integration-test/src/test/java/io/syndesis/test/itest/apiconnector/TodoOpenApiV3Connector_IT.java, app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoApiV2ApiKeyInHeader-export/model-info.json, app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoApiV2ApiKeyInHeader-export/model.json, app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoApiV2ApiKeyInQuery-export/model-info.json, app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoApiV2ApiKeyInQuery-export/model.json, app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoApiV2BasicAuth-export/model-info.json, app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoApiV2BasicAuth-export/model.json
- Add test to verify ApiKey authentication (in query and header)
- Add test to verify Basic authentication
=> chore: Add some integration tests on API connector authentication

app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx, app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx, app/ui-react/packages/ui/src/Integration/IntegrationStepsHorizontalItem.tsx, app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx, app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx, app/ui-react/packages/ui/src/Shared/AggregatedMetricCard.tsx, app/ui-react/packages/ui/src/Shared/ConfirmationDialog.tsx, app/ui-react/packages/ui/src/Shared/DndFileChooser.tsx, app/ui-react/packages/ui/src/Shared/InlineTextEdit.tsx, app/ui-react/packages/ui/src/Shared/ProgressWithLink.tsx, app/ui-react/packages/ui/src/Shared/SimplePageHeader.tsx
=> chore: migrate files from patternfly-react Icon to their pf4 equivalents

app/server/logging/jaeger/src/main/java/io/syndesis/server/logging/jaeger/service/JaegerActivityTrackingService.java, app/server/logging/jaeger/src/test/resources/expected-activities.json
https://issues.redhat.com/browse/ENTESB-12951
=> fix invalid date and time for steps in the activity log with Jaeger addon

install/operator/pkg/syndesis/backup/backup_test.go
* Test is too fragile depending on the platform it is executed on.
=> fix: Removes deficient backup test

app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx, app/ui-react/packages/ui/src/Connection/ConnectionDetailsForm.tsx, app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx, app/ui-react/packages/ui/src/Shared/models.ts
I know the validation alert looks the way it does, that's apparently just what it looks like at the moment.
I cannot avoid migrating components to function components.
=> chore: drop patternfly-react from connection/connector form cards & refactor

app/ui-react/packages/ui/src/Integration/IntegrationStatus.tsx, app/ui-react/packages/ui/src/Integration/IntegrationStatusDetail.tsx, app/ui-react/packages/ui/src/Integration/IntegrationsList.tsx, app/ui-react/packages/ui/src/Integration/IntegrationsListItem.css, app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx, app/ui-react/packages/ui/src/Integration/IntegrationsListItemBasic.tsx, app/ui-react/packages/ui/src/Integration/IntegrationsListItemUnreadable.tsx, app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx, app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json, app/ui-react/syndesis/src/modules/support/components/SelectiveIntegrationList.tsx, app/ui-react/syndesis/src/modules/support/pages/SupportPage.tsx
Also manages to look alright in the dashboard kinda
And the support page:
=> chore: migrate integration list from ListView to DataList

app/ui-react/packages/ui/src/Layout/PfNavLink.tsx, app/ui-react/packages/ui/src/Layout/TabBar.tsx
=> chore: migrate the tabbar component to pf4

app/ui-react/packages/ui/src/Shared/ConfirmationDialog.tsx, app/ui-react/packages/ui/src/Shared/Dialog.tsx
=> chore: migrate confirmation dialog to use pf4 modal

app/ui-react/packages/ui/src/Dashboard/ConnectionsMetric.tsx, app/ui-react/packages/ui/src/Dashboard/Dashboard.css, app/ui-react/packages/ui/src/Dashboard/Dashboard.tsx, app/ui-react/packages/ui/src/Dashboard/UptimeMetric.tsx, app/ui-react/packages/ui/src/Shared/AggregatedMetricCard.tsx, app/ui-react/syndesis/src/modules/dashboard/locales/dashboard-translations.en.json, app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
=> chore: migrate the aggregated metric card and resulting dashboard tweaks

doc/modules/integrating-applications/p_applying-conditions-to-mappings.adoc, doc/modules/integrating-applications/p_using-data-mapper-to-process-collections.adoc, doc/modules/integrating-applications/r_troubleshooting-data-mapping.adoc
=> user doc: Data mapper doc updates

app/ui-react/packages/ui/src/Shared/InlineTextEdit.tsx
=> chore: migrate inline text edit to pf4

app/ui-react/packages/api/src/useVirtualization.tsx, app/ui-react/packages/models/src/dv.d.ts, app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.css, app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/models.ts, app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationVersionsPage.tsx
- Master merge for #7879
- Jira https://issues.redhat.com/browse/TEIIDTOOLS-943
=> Teiidtools 943 m

doc/assemblies/connecting/as_connecting-to-mongodb.adoc, doc/modules/connecting/p_adding-mongodb-connections-read.adoc, doc/modules/connecting/p_adding-mongodb-connections-write.adoc, doc/modules/connecting/p_creating-mongodb-connections.adoc
Pasquale has reviewed this content.
=> user doc: updates to Mongodb connector doc

app/ui-react/packages/ui/src/Layout/ButtonLink.tsx, app/ui-react/packages/ui/src/Shared/ListViewToolbar.css, app/ui-react/packages/ui/src/Shared/ListViewToolbar.tsx
=> chore: migrate list view toolbar to pf4

app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvClientSessionMetric.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvRequestMetric.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvResultSetCacheMetric.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvUptimeMetric.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Versions/VirtualizationVersionsTable.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/PreviewResults.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
Updates DV spinner and label usages from pf3 to pf4
=> TEIIDTOOLS-925 DV pf3-pf4 spinner and label updates

app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.tsx
rebase and resubmit #7924 
TEIIDTOOLS-933
=> Fix: showing error msg for API failed in connectionschemalist

app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/EmptyViewsState.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx, app/ui-react/packages/ui/src/Integration/CiCd/CiCdListEmptyState.tsx, app/ui-react/packages/ui/src/Integration/CiCd/TagIntegrationDialogEmptyState.tsx
- converted to pf4 Tooltip and EmptyState for DV components
- converted TagIntegrationDialogEmptyState and CiCdListEmptyState to use pf4 EmptyState
- converted ExtensionDetail to use pf4 Tooltip
=> DV pf3-4 conversion, tooltip and emptystate - ENTESB-12896, TEIIDTOOLS-925

app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx, app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
fixes [ENTESB-12019](https://issues.redhat.com/browse/ENTESB-12019)
Moves the validity check into the app from the UI component.  Remaining item is
the OAuth 2.0 form, if there's more auth types that have specific forms I'd
suggest this page be composed a bit differently.
=> fix: rework the state managment for the API client security form

app/ui-react/packages/ui/src/Integration/Details/IntegrationActions.css, app/ui-react/packages/ui/src/Integration/Details/IntegrationActions.tsx, app/ui-react/packages/ui/src/Integration/IntegrationsListItem.css, app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx
Backporting fix to make editing a more obvious choice in the Integration list: https://github.com/syndesisio/syndesis/pull/7733
fixes https://issues.redhat.com/browse/ENTESB-12325
=> (backport): fix to make editing a more obvious choice in integration list (ENTESB-12325)

doc/modules/connecting/p_adding-mongodb-connections-read.adoc, doc/modules/connecting/p_adding-mongodb-connections-write.adoc, doc/modules/connecting/p_enabling-connections-to-knative-resources.adoc, doc/modules/integrating-applications/r_guidelines-for-service-sending-requests.adoc, doc/modules/tutorials/p_amq2api-create-custom-step.adoc
And updates to two other unrelated files.
=> user doc: updates to doc for Mongodb connector 

app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.css, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.css, app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.tsx
moved DV schema list to pf4 DataList
Before:
After:
=> Update DV SchemaLists to pf4 - TEIIDTOOLS-925, ENTESB-12896

doc/assemblies/connecting/as_connecting-to-kafka.adoc, doc/modules/connecting/p_creating-kafka-connections.adoc, doc/modules/connecting/p_enabling-auto-discovery-of-kafka-brokers.adoc, doc/modules/connecting/p_enabling-connections-to-knative-resources.adoc
Maria reviewed this doc, but it is still waiting for a QA review. 
But I need to move this along.
=> user doc: New doc for enabling auto-discovery of Kafka brokers

app/ui-react/packages/ui/src/Integration/CiCd/CiCdEditDialog.tsx, app/ui-react/packages/ui/src/Integration/CiCd/CiCdList.tsx, app/ui-react/packages/ui/src/Integration/CiCd/CiCdListItem.css, app/ui-react/packages/ui/src/Integration/CiCd/CiCdListItem.tsx, app/ui-react/packages/ui/src/Integration/CiCd/CiCdListView.tsx, app/ui-react/packages/ui/src/Integration/CiCd/CiCdManagePageUI.tsx, app/ui-react/packages/ui/src/Integration/CiCd/TagIntegrationDialog.tsx, app/ui-react/packages/ui/src/Integration/CiCd/TagIntegrationDialogBody.tsx, app/ui-react/packages/ui/src/Integration/CiCd/TagIntegrationListItem.css, app/ui-react/packages/ui/src/Integration/CiCd/TagIntegrationListItem.tsx, app/ui-react/packages/ui/stories/Integration/CiCd/CiCdEditDialog.stories.tsx, app/ui-react/packages/ui/stories/Integration/CiCd/CiCdListItem.stories.tsx, app/ui-react/packages/ui/stories/Integration/CiCd/TagIntegrationDialog.stories.tsx, app/ui-react/packages/ui/stories/Integration/CiCd/TagIntegrationListItem.stories.tsx
Updates cicd components for pf4
- list components now using pf4 DataList
- updated components to react FunctionComponents
- updated the associated stories
=> update cicd components for pf4 - ENTESB-12896

doc/modules/integrating-applications/p_create-api-provider-integration.adoc, doc/modules/integrating-applications/p_create-integration-operation-flows.adoc
ready for Tova review - these are exact same fixes as I made in the downstream MR
=> updating with fixes for two typos found downstream

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/support/SupportUtil.java
To read a pod log and if there is more than one container per pod,
it is required to set the container name.
https://issues.redhat.com/browse/ENTESB-12366
Also, reformart some sections.
=> Fix download diagnostics zip ENTESB-12366

app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvMetricsContainer.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvResultSetCacheMetric.tsx
Implements requested UX changes for the DV metrics cards [ENTESB-12899](https://issues.redhat.com/browse/ENTESB-12899)
- remove hoverable
- change to pf4 help icon for popover
=> Improve DV metrics cards

doc/modules/connecting/p_adding-kafka-connection-start.adoc, doc/modules/connecting/p_enabling-auto-discovery-of-kafka-brokers.adoc
Has been reviewed by Stefan Veres.
=> user doc: QA updates for doc for enabling auto-discovery of Kafka brokers

tools/bin/commands/minishift, tools/bin/commands/util/operator_funcs
Fixes issue #8027, plus adds more info for when things go wrong.
=> fix for issue #8027, where the operator binary download url cannot be constructed

app/ui-react/packages/ui/src/Shared/ProgressWithLink.tsx, app/ui-react/packages/ui/src/Shared/SyndesisAlert.tsx
related to [ENTESB-12896](https://issues.redhat.com/browse/ENTESB-12896)
The alert:
I neglected to grab a shot of the progress bar however.
=> chore: migrate progress with link and syndesis alert to pf4 

app/ui-react/packages/ui/stories/Integration/CiCd/CiCdListView.stories.tsx
=> fix: fix duplicate storybook tree

install/operator/.lib.sh
(cherry picked from commit 5bcc7c52dfedf974d94dccde7816e79b0dc9be90)
=> Call Go generator when using docker to build operator

app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorForm.tsx
=> chore: migrate integration editor form alert to pf4 and functional component

app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorActionsListItem.tsx, app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorStepsList.tsx, app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorStepsListItem.tsx, app/ui-react/packages/ui/src/Integration/Editor/choice/ChoiceConfigurationView.tsx
=> chore: migrate the editor step list to pf4

app/ui-react/packages/ui/src/Integration/Editor/endpoint/DescribeDataShapeForm.tsx
=> chore: migrate the describe data form to pf4

app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperations.tsx, app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperationsItem.tsx
=> chore: migrate the api provider operation list to pf4;

app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
=> chore: migrate API client connector security form thingie to pf4

app/ui-react/packages/ui/src/Dashboard/UptimeMetric.tsx, app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx, app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
=> chore: migrate integration detail page metrics to pf4

app/ui-react/packages/ui/src/Layout/Loader.css
- Jira Issue https://issues.redhat.com/browse/TEIIDTOOLS-955
- Screenshot
=> Fix: Handle Styling of UI Buttons in pf4

app/meta/src/main/java/io/syndesis/connector/meta/v1/VerifierEndpoint.java
* Wiring default CamelContext class and adapt to ExtendedCamelContext to find extension
Closes #8088
=> fix(meta): adapt default to ExtendedCamelContext

app/ui-react/packages/utils/src/WithLoader.tsx
- Jira Issue https://issues.redhat.com/browse/TEIIDTOOLS-954
- added the logic to check the unmounted component in the async method before status update.
=> Fix:UI console warning

app/ui-react/packages/ui/src/Shared/Notifications.tsx, app/ui-react/packages/ui/src/Shared/TimedAlert.tsx, app/ui-react/syndesis/src/app/UI.tsx
=> chore: migrate notifications to pf4

app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListItems.tsx
This resolves issue with Views Import wizard table - was logging a console warning upon refresh.  The data supplied to the pf4 table was not formatted correctly.  [TEIIDTOOLS-953](https://issues.redhat.com/browse/TEIIDTOOLS-953)
=> TTOOLS-953 Resolve issue with DV table refresh

app/connector/kafka/pom.xml, app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaConnectionCustomizer.java, app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaMetaDataExtension.java, app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaMetaDataRetrieval.java, app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaVerifierExtension.java, app/connector/kafka/src/main/java/io/syndesis/connector/kafka/service/KafkaBrokerService.java, app/connector/kafka/src/main/java/io/syndesis/connector/kafka/service/KafkaBrokerServiceException.java, app/connector/kafka/src/main/java/io/syndesis/connector/kafka/service/KafkaBrokerServiceImpl.java, app/connector/kafka/src/main/resources/META-INF/syndesis/connector/kafka.json, app/connector/kafka/src/test/java/io/syndesis/connector/kafka/KafkaConnectionCustomizerTest.java, app/connector/kafka/src/test/java/io/syndesis/connector/kafka/KafkaMetaDataRetrievalTest.java, app/connector/support/util/src/main/java/io/syndesis/connector/support/util/KeyStoreHelper.java
* Provided support for TLS protocol in transit
* Enhanced verification process
* Enhanced topic discovery
* Fallback topic discovery to empty list when any network issue appear
Ref: ENTESB-13132, ENTESB-13134, ENTESB-13195, #8052
=>  feat(connector/kafka): TLS encryption

app/server/runtime/pom.xml, app/server/runtime/src/test/java/io/syndesis/server/runtime/integration/ProjectDSLGeneratorTest.java, app/server/runtime/src/test/resources/io/syndesis/server/runtime/task-api.json
#8034
https://issues.redhat.com/browse/ENTESB-13085
=> fix 8034 Integration fails to start: prometheus config cannot be found

app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/embedded/EmbedMongoConfiguration.java
=> fix(connector/mongodb): Add a shutdown timeout

app/integration/bom-camel-k/pom.xml, app/integration/bom/pom.xml, app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/pom.xml.mustache, app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/redhat/pom.xml.mustache, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/pom.xml, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/redhat/pom.xml, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/pom.xml, app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/redhat/pom.xml, app/integration/runtime-camelk/pom.xml, app/integration/runtime-springboot/pom.xml, app/integration/runtime/pom.xml, app/pom.xml, app/test/test-support/src/main/resources/io/syndesis/test/integration/project/template/pom.xml.mustache, app/ui-react/packages/atlasmap-assembly/package.json, app/ui-react/yarn.lock
=> chore: Update to AtlasMap 1.44.0-M1

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/support/SupportUtil.java
To read a pod log and if there is more than one container per pod,
it is required to set the container name.
https://issues.redhat.com/browse/ENTESB-12366
Also, reformart some sections.
(cherry picked from commit 20f1abff7efc060e6829a1b9447104d0bd95c6d1)
=> Fix download diagnostics zip ENTESB-12366 - 1.9.x

app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.css, app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/ConnectionTreeComponent.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/KababActionComponent.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/TreeColumnNodeComponent.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/TreeTableNodeComponent.tsx, app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
- Jira Issue https://issues.redhat.com/browse/TEIIDTOOLS-964
- Used the React.Memo to optimize the component performance on polling, and used useMemo to memories the expensive function calls.
=> Using memo for performance

app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
follow-on for [ENTESB-13271](https://issues.redhat.com/browse/ENTESB-13271)
=> chore: fix typo for create connection string

install/operator/pkg/cmd/internal/install/generator/generator.go
Following #8181 use Tag instead of Image
=> Use the Tag instead of Image for database image

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/ExtensionHandler.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/ExtensionsITCase.java
* Overriding the extension API list to include an extensionType filter
* Add unit test to verify the new filter
Closes ENTESB-13247
Please, consider that this PR does not target a code refactory. This is in parallel [under discussion](https://groups.google.com/forum/#!topic/syndesis/PGJ1A6meKoQ)
=> feat(server): extension filter

app/common/model/src/main/java/io/syndesis/common/model/Schema.java, app/server/runtime/src/main/resources/migrations/up-40.js
Fixing migration scripts for camel 3.
Truth is: I am not 100% sure how to test this to be sure it is foolproof.
=> chore(migration): camel 3.1 changes

app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerTest.java
* Changed the implementation to run a single test and check for the results instead that two separate tests.
Should fix #8244
=> feat(connector/mongodb): Fix flaky test

app/test/integration-test/src/test/java/io/syndesis/test/itest/timer/TimerToLog_IT.java, app/test/integration-test/src/test/resources/io/syndesis/test/itest/mail/SendMail-export/model-info.json, app/test/integration-test/src/test/resources/io/syndesis/test/itest/mail/SendMail-export/model.json
Two minor fixes: removing a stacktrace I introduced wrongly on a previous commit and fix the email step on the email integration test.
Integration test still falls due to an atlasmap related bug I'm still hunting.
=> Itest timer

app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperationsItem.tsx, app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx, app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
Just added a few data-testids to PF4 data-list components to help QE with testsuite migration
=> Added data-testids

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/ExtensionHandler.java
Changing the extensionType parameter to be of the proper type instead of a String and later converting to Type.
Closes #8258
=> feature(server): extensions list explicit type

app/ui-react/craco.config.js, app/ui-react/packages/.storybook/webpack.config.js, app/ui-react/packages/ui/__tests__/AppLayout.spec.tsx, app/ui-react/packages/ui/__tests__/Integration/IntegrationsListItem.spec.tsx, app/ui-react/packages/ui/package.json, app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx, app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor.stories.tsx, app/ui-react/syndesis/craco.config.js, app/ui-react/syndesis/package.json, app/ui-react/syndesis/src/app/App.test.tsx, app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx, app/ui-react/yarn.lock
Initial UI changes for monaco editor
Part 1 includes all monaco services and connect code in DdlEditor.tsx and successfully communicates with the DV Language Server back-end web socket
=> Dv ls UI integration part 1

app/ui-react/packages/ui/src/Data/Virtualizations/SqlResultsTable.tsx
=> [Backport 1.10.x] Backport TEIIDTOOLS-898

app/ui-react/packages/auto-form/src/widgets/FormLabelHintComponent.tsx, app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorListItem.tsx, app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorListView.tsx
Backport of https://github.com/syndesisio/syndesis/pull/8282 to 1.10.x
=> (backport 1.10.x)[PF4 migration] Added test-ids to API connector page

app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderOnExceptionHandler.java, app/connector/api-provider/src/test/java/io/syndesis/connector/apiprovider/OnExceptionHandlerTest.java
Fixing #8215, failing integration tests due to upgrade to Camel 3
=> Fix for TodoOpenApiV3_IT #8215

install/operator/pkg/cmd/internal/install/generator/generator.go
backport of this [commit](https://github.com/syndesisio/syndesis/commit/155455af732a91631d2a4e349f02907e37a53eda)
=> Backport: Use the Tag instead of Image for database image

app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json, app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
changes the translation files to make consistent using 'CreateConnection' key in all.
=> (fix) ENTESB-13271 makes translation files consistent

app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx, app/ui-react/packages/ui/src/Dashboard/UptimeMetric.tsx, app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx, app/ui-react/packages/ui/src/Integration/CiCd/CiCdListItem.tsx, app/ui-react/packages/ui/src/Integration/CiCd/TagIntegrationListItem.tsx, app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
Added DataTestIds to activity, metrics and cicd pages to increase stability of QE test suite.
=> [PF4 migration] Added DataTestIds to activity, metrics and cicd pages

app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
Added some DataTestIds to DataVirtualization pages to increase stability of QE test suite.
=> [PF4 migration] Added DataTestIds to DataVirtualization pages

app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json, app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json, app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json, app/ui-react/syndesis/src/modules/connections/components/ConnectionsWithToolbar.tsx, app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx, app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx, app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx, app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx, app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx, app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/EditorStepsWithToolbar.tsx
This brings the 'CreateConnection' translation keys and usage back in sync with master.
=> (backport) ENTESB-13271 sync translation key usage

app/ui-react/packages/ui/src/Integration/BreadcrumbDropdown.tsx, app/ui-react/packages/ui/src/Integration/ConditionsDropdownItem.tsx, app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorStepsListItem.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/EditorBreadcrumb.tsx
Added test ids to conditional flow breadcrumb dropdown.
Also added test ids to step details for step name and step datashape
=> [PF4 migration] Added test-ids to integration editor step item

app/ui-react/packages/ui/src/Integration/BreadcrumbDropdown.tsx, app/ui-react/packages/ui/src/Integration/ConditionsDropdownItem.tsx, app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorStepsListItem.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/EditorBreadcrumb.tsx
Backport of https://github.com/syndesisio/syndesis/pull/8341
=> (backport 1.10.x)[PF4 migration] Added test-ids to integration editor step item 

app/ui-react/packages/api/src/constants.ts, app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
=> (backport) fix for ENTESB-11675 to add errorHandler field to the schema

app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
Backport of https://github.com/syndesisio/syndesis/pull/8352
=> (backport 1.10.x)[PF4 migration] Added test-ids to ApiClientConnectorSecurity

app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
Added test-ids to ApiClientConnectorSecurity
=> [PF4 migration] Added test-ids to ApiClientConnectorSecurity

app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.css, app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx
fixes [ENTESB-13253](https://issues.redhat.com/browse/ENTESB-13253)
maintains the format of the error message too.
=> fix: define table column widths, make data display size constrained

app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.css, app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx
=> (backport) fix: define table column widths, make data display size constrained

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-assembly/package.json, app/ui-react/yarn.lock
Backporting #8363
This has to go after #8327
=> chore: Update to AtlasMap 2.0.0-M.2

app/ui-react/packages/ui/src/Layout/AppLayout.tsx
=> (backport) fix: move the special classname to the dropdown item so the logout entry is hidden

app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx, app/ui-react/packages/ui/src/Integration/Editor/choice/ChoiceConfigurationView.tsx
Labeled test ids to rest of the conditional flows components.
=> Added test-ids to conditional flows elements

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-assembly/package.json, app/ui-react/yarn.lock
=> chore: Update to AtlasMap 2.0.0-M.3

app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx, app/ui-react/packages/ui/src/Integration/Editor/choice/ChoiceConfigurationView.tsx
Backport of https://github.com/syndesisio/syndesis/pull/8378
=> (backport 1.10.x)Added test-ids to conditional flows elements

app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.css, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionListItems.css, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionListItems.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionToolbar.css, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionToolbar.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/index.ts, app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json, app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json, app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json, app/ui-react/syndesis/src/modules/data/index.tsx, app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json, app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json, app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json, app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx, app/ui-react/syndesis/src/modules/data/pages/index.ts, app/ui-react/syndesis/src/modules/data/resolvers.ts, app/ui-react/syndesis/src/modules/data/routes.ts, app/ui-react/syndesis/src/modules/data/shared/VirtualizationNavBar.tsx, app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
- Jira Issue https://issues.redhat.com/browse/TEIIDTOOLS-979
- Implemented the data permission screen ui based on updated UX  
- Screenshots
=> Teiidtools 979

app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationList.tsx
- Jira Issue https://issues.redhat.com/browse/ENTESB-13653
- Removed the white background from the toolbar and empty state to make UI consistent across syndesis.
- screenshot
=> Fix: UI inconsistency by removing white background

app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/aws-ddb.json
Just a minor description update
=> [ENTESB-13000] Adding "update" to description of put aws-ddb operation

app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/aws-ddb.json
fix(aws-ddb): adding "update" to description of operation
=> [ENTESB-130000] Backport to 1.10.x 

app/common/util/src/main/java/io/syndesis/common/util/ErrorCategory.java
https://issues.redhat.com/browse/ENTESB-13104
=> fix for ENTESB-13104 addon fix

app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationList.tsx
=> [backport] UI inconsistency by removing white background

app/connector/api-provider/src/main/resources/META-INF/syndesis/connector/api-provider.json
https://issues.redhat.com/browse/ENTESB-12840
=> fix for ENTESB-12840 - removing quotes

app/connector/api-provider/pom.xml, app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderOnExceptionHandler.java
This pertains to the api-provider only
https://issues.redhat.com/browse/ENTESB-13431
=> fix for ENTESB-13431,  SQL connector exceptions are visible only in DEBUG mode

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-assembly/package.json, app/ui-react/yarn.lock
=> chore: Update to AtlasMap 2.0.0-M.4

app/connector/box/pom.xml, app/connector/box/src/main/java/io/syndesis/connector/box/customizer/BoxUploadCustomizer.java
https://issues.redhat.com/browse/ENTESB-12553
=> Fix Box connector upload from s3,dropbox,ftp ENTESB-12553

app/connector/box/src/main/java/io/syndesis/connector/box/customizer/BoxUploadCustomizer.java, install/operator/pkg/cmd/internal/install/install_defaults.go
https://issues.redhat.com/browse/ENTESB-12553
(cherry picked from commit 19e382cbbb1f9384001fb94eb2f2d67c0f2bcacc)
=> Fix Box connector upload from s3,dropbox,ftp ENTESB-12553 (1.10.x)

doc/connecting/master-docinfo.xml, doc/connecting/master.adoc, doc/customizing/master-docinfo.xml, doc/customizing/master.adoc, doc/developing_extensions/master-docinfo.xml, doc/developing_extensions/master.adoc, doc/integrating-applications/master-docinfo.xml, doc/integrating-applications/master.adoc, doc/managing_environments/master-docinfo.xml, doc/managing_environments/master.adoc, doc/shared/attributes-links.adoc, doc/shared/attributes.adoc, doc/tutorials/master-docinfo.xml, doc/tutorials/master.adoc
=> docs-administrative-updates cleanup doc files

app/common/model/src/main/java/io/syndesis/common/model/integration/Flow.java, app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationBase.java, app/integration/api/src/main/java/io/syndesis/integration/api/IntegrationResourceManager.java, app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java, app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/ProjectGeneratorTest.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/ExtensionHandler.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/ExtensionsITCase.java, app/server/update-controller/src/test/java/io/syndesis/server/update/controller/usage/UsageUpdateHandlerTest.java
Backporting features developed to support runtime libraries.
=> [Backport 1.10.x] Backend runtime libraries

app/dv/src/main/java/io/syndesis/dv/datasources/DataSourceDefinition.java, app/dv/src/main/java/io/syndesis/dv/datasources/SalesforceDefinition.java
also updating salesforce to not include extra metadata
=> TEIIDTOOLS-997 using full schema name if no schema is set

app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionToolbar.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
- Jira issue https://issues.redhat.com/browse/TEIIDTOOLS-1012
https://issues.redhat.com/browse/TEIIDTOOLS-1015
- Sync toolbar checkbox with view checkbox in the page.
- used the ButtonLink for save and cancel button to show the loading ionic while API call.
=> Fix: Sync the toolbar checkbox with rest of page view checkbox

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-adapter/package.json, app/ui-react/packages/atlasmap-adapter/src/DataMapperAdapter.tsx, app/ui-react/yarn.lock
Includes: https://issues.redhat.com/browse/ENTESB-13739
Backporting: #8468
=> chore: Update to AtlasMap 2.0.2

app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx
Backport of https://github.com/syndesisio/syndesis/pull/8491
=> Added classname to OpenApiSelectMethod

app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
- Jira issues https://issues.redhat.com/browse/TEIIDTOOLS-1018
https://issues.redhat.com/browse/TEIIDTOOLS-1017
- Fixed the sync issue in rolePermissionModel in ViewPermissionList component, by watching the previous value of "Selected" state and updating same in "ViewPermissionList".
- Getting the updatedRoles value on success of updatePermissionRole call.
=> Fix: Sync issue of rolepermissionmodel in viewpermissionlist

app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
backport for TEIIDTOOLS-1018 - Sync issue of rolepermissionmodel in viewpermissionlist
=> [backport 1.10.x] TEIIDTOOLS-1018

app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.css, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionListItems.tsx, app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor.stories.tsx, app/ui-react/packages/ui/stories/Data/Views/ViewInfoList.stories.tsx, app/ui-react/packages/ui/stories/Data/Views/ViewList.stories.tsx, app/ui-react/packages/ui/stories/Data/Views/ViewListItem.stories.tsx, app/ui-react/packages/ui/stories/Data/ViewsPermissions/RolePermissionList.stories.tsx, app/ui-react/packages/ui/stories/Data/ViewsPermissions/RolePermissionListItem.stories.tsx, app/ui-react/packages/ui/stories/Data/ViewsPermissions/ViewPermissionListItems.stories.tsx, app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx, app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx, app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json, app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json, app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json, app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
changes related to TEIIDTOOLS-979
- Adds stories for a few of the permission components
- other minor DV story updates
- a few i18n additions
- minor layout adjustments
=> DV permission component stories

app/server/dao/src/main/java/io/syndesis/server/dao/manager/DataManager.java, app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java
* Added a merge method to include existing and new configured properties instead of replacing the one coming from previous connector's version
* Added a couple of unit test to validate the merge
Ref #8466
=> fix(server): merge existing and new configured properties on server load

app/connector/debezium/src/main/resources/META-INF/syndesis/connector/debezium.json, app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaVerifierExtension.java
Enable kafka autodiscovery feature
Closes ENTESB-13745
=> feat(connector/debezium): kafka broker autodiscovery

app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.css, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx
- Jira Issue https://issues.redhat.com/browse/TEIIDTOOLS-1027
- Removed the role from availableRoles list once the user selects it, and checking if role already exist on create.
- Screenshot
=> Fix: dublicate permission role row

app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
fixes [ENTESB-13527](https://issues.redhat.com/browse/ENTESB-13527) as well
=> fixes issue with webhook error loading

app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx, app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
backport of https://github.com/syndesisio/syndesis/pull/8505 for [ENTESB-13527](https://issues.redhat.com/browse/ENTESB-13527)
=> [backport 1.10.x] ENTESB-13527 webhook error + token fix

app/ui-react/packages/ui/stories/Data/ViewsPermissions/RolePermissionList.stories.tsx, app/ui-react/packages/ui/stories/Data/ViewsPermissions/RolePermissionListItem.stories.tsx, app/ui-react/packages/ui/stories/Data/ViewsPermissions/ViewPermissionListItems.stories.tsx
=> Fix: Stories fixes

app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
Added test-ids to OpenApiReviewActionsPage
=> [PF4 migration] Added DataTestIds to OpenApiReviewActionsPage

app/common/model/src/main/java/io/syndesis/common/model/ModelData.java, app/common/model/src/main/java/io/syndesis/common/model/WithConfigurationProperties.java, app/common/model/src/main/java/io/syndesis/common/model/WithResourceId.java, app/common/model/src/main/java/io/syndesis/common/model/action/ActionDescriptor.java, app/common/model/src/main/java/io/syndesis/common/model/action/ConnectorDescriptor.java, app/common/model/src/main/java/io/syndesis/common/model/integration/Flow.java, app/common/model/src/main/java/io/syndesis/common/model/integration/step/template/TemplateStepPreProcessor.java, app/common/model/src/main/java/io/syndesis/common/model/support/EquivContext.java, app/common/model/src/main/java/io/syndesis/common/model/support/Equivalencer.java, app/common/model/src/test/java/io/syndesis/common/model/integration/step/template/TestFreeMarkerTemplatePreProcessor.java, app/common/model/src/test/java/io/syndesis/common/model/integration/step/template/TestMustacheTemplatePreProcessor.java, app/common/model/src/test/java/io/syndesis/common/model/integration/step/template/TestVelocityTemplatePreProcessor.java, app/connector/kudu/src/test/java/org/apache/camel/component/kudu/AbstractKuduTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/AbstractODataRouteTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/AbstractODataTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/AbstractODataReadRouteTest.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataCreateTests.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataDeleteTests.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataReadTests.java, app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataUpdateTests.java, app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/ActivityTrackingInterceptStrategy.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/AbstractTemplateStepHandlerTest.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/logging/AbstractActivityLoggingTest.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/template/velocity/AbstractVelocityTemplateStepHandlerTest.java, app/integration/runtime/src/test/java/io/syndesis/integration/runtime/tracing/ActivityTracingWithSplitTest.java, app/meta/src/test/java/io/syndesis/connector/meta/v1/ActionDefinitionEndpointTest.java, app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingControllerTest.java, app/server/runtime/src/test/java/io/syndesis/server/runtime/ActivityITCase.java
I run some of the code analysis on IntellijIDEA and cleaned up and improved the code a bit. 
Cleaned up many of the exceptions throws that were not really throwing any exception and changed some expressions using Java 8 to simplify the code and make it less error prone.
There's still many warnings pending but didn't want to do a bigger PR.
No bug fixes, no features, just rewriting code.
=> Cleanup code

app/dv/src/main/java/io/syndesis/dv/RepositoryManager.java, app/dv/src/main/java/io/syndesis/dv/openshift/TeiidOpenShiftClient.java
preserving the three-valued logic in teiidopenshift client
=> refactor(dv): follow-up to initial fix

app/server/runtime/src/main/resources/migrations/up-42.js
Additional PR for https://github.com/syndesisio/syndesis/issues/8325
=> Fix for #8325 adding missing migration function

app/connector/debezium/pom.xml, app/connector/debezium/src/main/java/io/syndesis/connector/debezium/DebeziumConsumerCustomizer.java, app/connector/debezium/src/main/java/io/syndesis/connector/debezium/DebeziumMetaDataRetrieval.java, app/connector/debezium/src/main/resources/META-INF/syndesis/connector/debezium.json, app/connector/debezium/src/test/java/io/syndesis/connector/debezium/DebeziumConsumerCustomizerTest.java, app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaVerifierExtension.java, app/connector/kafka/src/main/resources/META-INF/syndesis/connector/kafka.json
* Adding TLS support
* Refactorying metadata retrieval to take in account TLS parameters
* Improving kafka verification process
Closes ENTESB-13795
=> feat(connector/debezium): TLS support

app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx, app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorsPage.tsx, app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx, app/ui-react/syndesis/src/modules/extensions/pages/ExtensionDetailsPage.tsx, app/ui-react/syndesis/src/modules/extensions/pages/ExtensionImportPage.tsx, app/ui-react/syndesis/src/modules/extensions/pages/ExtensionsPage.tsx
fixes [ENTESB-11408](https://issues.redhat.com/browse/ENTESB-11408)
=> (backport) fix: add missing PageTitle component to pages

app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx, app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorsPage.tsx, app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx, app/ui-react/syndesis/src/modules/extensions/pages/ExtensionDetailsPage.tsx, app/ui-react/syndesis/src/modules/extensions/pages/ExtensionImportPage.tsx, app/ui-react/syndesis/src/modules/extensions/pages/ExtensionsPage.tsx
fixes [ENTESB-11408](https://issues.redhat.com/browse/ENTESB-11408)
=> fix: add missing PageTitle component to pages

app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json, app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json, app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
fixes [ENTESB-13763](https://issues.redhat.com/browse/ENTESB-13763)
=> chore: adjust version in doc links for 7.7

app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppExpanderBody.tsx, app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppListItem.tsx, app/ui-react/syndesis/src/modules/settings/pages/OAuthAppsPage.tsx
fixes [ENTESB-13406](https://issues.redhat.com/browse/ENTESB-13406)
Adds an Edit/Close button to better align it with the other list views, also makes the Remove button a link instead of a primary button
=> fix: polish up the oauth settings page and expander

app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppExpanderBody.tsx, app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppListItem.tsx, app/ui-react/syndesis/src/modules/settings/pages/OAuthAppsPage.tsx
=> (backport) fix: polish up the oauth settings page and expander

app/ui-react/packages/ui/src/Integration/Editor/template/TemplateStepTypeSelector.tsx
backports https://github.com/syndesisio/syndesis/pull/8570 to 1.10.x
=> (backport) fix: update template type selector to use the right markup

app/ui-react/packages/ui/src/Integration/Editor/template/TemplateStepTypeSelector.tsx
fixes [ENTESB-13639](https://issues.redhat.com/browse/ENTESB-13639)
=> fix: update template type selector to use the right markup

app/connector/webhook/pom.xml, app/connector/webhook/src/main/java/io/syndesis/connector/webhook/WebhookOnExceptionHandler.java
Fixes: https://github.com/syndesisio/syndesis/issues/8566, https://issues.redhat.com/browse/ENTESB-13811
=> fix #8566 Log Error in the WebHook when exception happens

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-adapter/package.json, app/ui-react/yarn.lock
=> chore: Update to AtlasMap 2.0.3

app/connector/webhook/src/main/java/io/syndesis/connector/webhook/WebhookOnExceptionHandler.java
This was caused by changed API in Camel-3
=> Fix for ENTESB-13812 - NPE when integration contains webhook step and an error

app/integration/bom/pom.xml
=> fix(integration): align mongodb integration bom deps

app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailHeader.tsx
fixes [ENTESB-13371](https://issues.redhat.com/browse/ENTESB-13371)
=> fix: re-align the detail page nav

app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/DataMapperPage.tsx
fixes [ENTESB-13935](https://issues.redhat.com/browse/ENTESB-13935)
//skip-ci
=> fix: ensure we preserve any previous mapping document when revisiting the data mapper

app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSelectMethod.tsx, app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderSelectMethod.tsx, app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
fixes [ENTESB-13842](https://issues.redhat.com/browse/ENTESB-13842)
=> fix: rework the validation checking and tidy up

app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Updating the documentation and noticed this UI text needs an edit.
=> edit the  message in UI about library extensions

app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSelectMethod.tsx, app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderSelectMethod.tsx, app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
fixes ENTESB-13842
Backports https://github.com/syndesisio/syndesis/pull/8593
=> (backport) fix: rework the validation checking and tidy up

app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailHeader.tsx
fixes ENTESB-13371
Backports https://github.com/syndesisio/syndesis/pull/8595
=> (backport) fix: re-align the detail page nav

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/tests/TestSupportHandler.java
=> [ResetDB] Remove DV related stuff

app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
backports https://github.com/syndesisio/syndesis/pull/8598
@MelissaFlinn FYI
=> (backport) edit the message in UI about library extensions

app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
fixes [ENTESB-11829](https://issues.redhat.com/browse/ENTESB-11829)
silly me :-)
=> fix: use the right type for the 'min' property

app/ui-react/packages/models/src/dv.d.ts, app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.css, app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.css, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionListView.tsx, app/ui-react/packages/ui/stories/Data/CreateViewWizard/ConnectionSchemaList.stories.tsx, app/ui-react/packages/ui/stories/Data/CreateViewWizard/ConnectionSchemaListItem.stories.tsx, app/ui-react/packages/ui/stories/Data/CreateViewWizard/SelectedConnectionListView.stories.tsx, app/ui-react/packages/ui/stories/Data/CreateViewWizard/SelectedConnectionTables.stories.tsx, app/ui-react/packages/ui/stories/Data/Views/SchemaNodeListItem.stories.tsx, app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx, app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx, app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx, app/ui-react/syndesis/src/modules/data/shared/ConnectionTables.tsx, app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Backport of DV UI fixes to 1.10.x
TEIIDTOOLS-1021
TEIIDTOOLS-1026
TEIIDTOOLS-765
=> (backport 1.10.x) fix: TEIIDTOOLS-1021, TEIIDTOOLS-1026, TEIIDTOOLS-765

app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationActions.tsx, app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json, app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json, app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json, app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
Adding tooltip message on the Publish button to better describe 
- what happens upon publish
- why the publish button may be disabled
=> fix: TEIIDTOOLS-1036 Add Publish messages

app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/ConnectionTreeComponent.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationActions.tsx, app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx, app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json, app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json, app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json, app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx, app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
Backports the following dv UI fixes to 1.10.x
TEIIDTOOLS-1036
TEIIDTOOLS-1037
TEIIDTOOLS-1040
=> (backport) fix: DV UI backports

.circleci/config.yml, app/ui-react/packages/.storybook/webpack.config.js, app/ui-react/packages/ui/package.json, app/ui-react/syndesis/craco.config.js, app/ui-react/syndesis/package.json
in support of #8561 and #8624 
And because the UI build seems to be generally failing all the time at the moment.
=> chore: adjust java & node heap setting for ui

.circleci/config.yml, app/ui-react/packages/.storybook/webpack.config.js, app/ui-react/packages/ui/package.json, app/ui-react/syndesis/craco.config.js, app/ui-react/syndesis/package.json
=> (backport) chore: adjust java and node heap for ui

app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
fixes [ENTESB-11829](https://issues.redhat.com/browse/ENTESB-11829)
=> fix: ensure the min property is properly overridden

app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/operations/PaginationOptionsFromQueryParams.java, app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandlerTest.java, app/ui-react/packages/api/src/WithApiConnectors.tsx
=> [backport master] - Fixes ENTESB-14002, added endpoint to list API connectors

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-adapter/package.json, app/ui-react/yarn.lock
https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.0.4
=> chore: Update to AtlasMap 2.0.4

app/connector/api-provider/src/main/resources/META-INF/syndesis/connector/api-provider.json, app/connector/webhook/src/main/resources/META-INF/syndesis/connector/webhook.json
=> fix for #8687 Webhook value setting incorrect when using default values

app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionListItems.tsx, app/ui-react/packages/ui/stories/Data/ViewsPermissions/RolePermissionList.stories.tsx, app/ui-react/packages/ui/stories/Data/ViewsPermissions/ViewPermissionListItems.stories.tsx, app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
- Jira Issue https://issues.redhat.com/browse/TEIIDTOOLS-1041
- Using the RolePermissionList component form ViewPermissionListItems to provide the view permission control from expandable view list.
- screenshot
=> Fix: view permissions to be managed via row expansion

app/ui-react/packages/auto-form/src/utils.ts, app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
=> fix: calculate the appropriate defaultValue setting from the current available error keys

app/pom.xml
https://github.com/syndesisio/syndesis/issues/8711
=> Upgrade undertow to 2.0.30 to fix CVE

app/pom.xml
https://github.com/syndesisio/syndesis/issues/8711
=> Upgrade undertow to 2.0.30 to fix CVE (1.10.x)

app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx, app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx, app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx, app/ui-react/syndesis/src/modules/data/resolvers.ts
minor cleanup of ViewEditorSqlPage routing.  An optional viewDefinition was included, but the only usages were providing undefined.
=> TEIIDTOOLS-1051 DV routing cleanup

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-adapter/package.json, app/ui-react/yarn.lock
Fixes: https://issues.redhat.com/browse/ENTESB-12362
Release note: https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.0.5
=> chore: Update to AtlasMap 2.0.5

app/dv/src/main/java/io/syndesis/dv/server/endpoint/EditorService.java, app/dv/src/test/java/io/syndesis/dv/server/endpoint/EditorServiceTest.java
ensuring that the parsable flag is always correctly set
=> fix(dv) ENTESB-14057 addressing scenarios that create invalid metadata

app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/crd/ConditionSpec.java, app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/crd/GeneratedResourceSpec.java, app/server/controller/src/test/java/io/syndesis/server/controller/integration/camelk/crd/IntegrationTest.java, app/server/controller/src/test/resources/io/syndesis/server/controller/integration/camelk/crd/last-known-camelk-integration.json
* Update camel-k CRD unit test
* Fix the model according the new spec
Fixes #8679
FYI @dhirajsb @Delawen @KurtStam
=> fix(server): update Camel-K CRD spec

app/pom.xml
A revert of https://github.com/syndesisio/syndesis/pull/8677 (it will be handled in later release)
=> Revert of [ENTESB-12963] Upgrade Spring to 5.1.13

app/integration/bom-camel-k/pom.xml
=> fix(integration): align camel-k runtime dependencies

app/ui-react/packages/auto-form/src/utils.ts
fixes [ENTESB-14198](https://issues.redhat.com/browse/ENTESB-14198)
=> fix: ensure we massage a mapset value to an object properly

install/operator/pkg/cmd/internal/run/run.go
Updated code generated by operator-sdk v15+ for service metrics and monitoring.
=> updated service metrics & monitoring logic generated by sdk

app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.tsx
fixes [ENTESB-14197](https://issues.redhat.com/browse/ENTESB-14197)
=> fix: bring back the green check

app/ui-react/packages/models/src/dv.d.ts, app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/ViewPermissionList.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/ViewPermissionListItems.css, app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/ViewPermissionListItems.tsx
- Jira issue https://issues.redhat.com/browse/TEIIDTOOLS-1060
- Added the SET value type to operation.
- screenshot
=> Fix:Add support for Set type operation

app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/ColumnPermissionItem.css, app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/ColumnPermissionItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/ColumnPermissionTab.css, app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/ColumnPermissionTab.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/EditPoliciesModal.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/RowFilteringItem.css, app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/RowFilteringItem.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/RowFilteringTab.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/ViewPermissionListItems.tsx, app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/index.ts, app/ui-react/packages/ui/stories/Data/ViewsPermissions/ViewPermissionListItems.stories.tsx, app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json, app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json, app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json, app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
- Jira Issue https://issues.redhat.com/browse/TEIIDTOOLS-1058
- Added the ColumnPermissionTab component for column tab.
- Screenshot
=> Teiidtools 1058

app/dv/src/main/java/io/syndesis/dv/server/endpoint/DataVirtualizationService.java, app/dv/src/test/java/io/syndesis/dv/server/endpoint/IntegrationRolesTest.java
Modified the roles service - if an empty set of privileges is provided, the role is removed.  Updated the IntegrationRolesTest for the scenario.
=> TEIIDTOOLS-1059 Modify DV roles logic for empty privileges

tools/bin/commands/completion, tools/bin/commands/integration-test, tools/bin/commands/release, tools/bin/commands/system-test, tools/bin/commands/ui
Necessary to fix daily builds.
=>  fix: Adds remaining ::init functions to syndesis command scripts

app/server/cli/pom.xml, app/server/monitoring/pom.xml, install/operator/.lib.sh, tools/bin/commands/util/openshift_funcs
=>  Fix over #8791

app/server/cli/pom.xml, app/server/monitoring/pom.xml, install/operator/.lib.sh, tools/bin/commands/util/openshift_funcs
* pom.xml
* Detected unused defined dependencies
* .lib.sh
* platform-detect must be built with the docker option as well as go
* openshift_funcs
* Syntax error on checking for command
=> Fix: More changes to get the release build working

.github/workflows/e2e.yml, .github/workflows/e2e_mainbranch.yml
Adding more options to the build (clean, build dependencies, make sure s2i is built,...).
=> fix(itest): Build docker images too

app/test/integration-test/src/test/java/io/syndesis/test/itest/conditional/ConditionalFlows_IT.java, app/test/integration-test/src/test/java/io/syndesis/test/itest/ftp/WebHookToFtp_IT.java, app/test/integration-test/src/test/java/io/syndesis/test/itest/mail/SendMail_IT.java, app/test/integration-test/src/test/java/io/syndesis/test/itest/quickstart/Webhook2DB_IT.java, app/test/integration-test/src/test/java/io/syndesis/test/itest/webhook/WebHookSplitToDB_IT.java, app/test/integration-test/src/test/java/io/syndesis/test/itest/webhook/WebHookToDB_IT.java
Updating integration tests to match new default.
=> fix(integration-tests): Fixing tests so they pass. HTTP changed from 204 to 200.

app/ui-react/packages/ui/src/Layout/AppLayout.tsx
Towards https://issues.redhat.com/browse/APPDUX-244 per @dlabaj
=> update filter with correct apps for cross-console navigation

app/test/integration-test/src/test/resources/io/syndesis/test/itest/mail/SendMail-export/model.json
=> fix for 8811 - SendMail integration test by fixing the default

app/ui-react/packages/auto-form/src/utils.ts
fixes [ENTESB-14198](https://issues.redhat.com/browse/ENTESB-14198)
backports #8753
=> (backport) fix: ensure we massage a mapset value to an object properly

app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.tsx
fixes [ENTESB-14197]
backports #8755
=> (backport) fix: bring back the green check

app/test/test-support/src/main/java/io/syndesis/test/integration/project/CamelKProjectBuilder.java, tools/bin/commands/integration-test
=> chore(#8855): Add CLI option to switch runtime for integration tests

app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSelectMethod.tsx
fixes [ENTESB-14025](https://issues.redhat.com/browse/ENTESB-14025)
Also renamed the function that formats the filename to be more reflective of what it actually does..
=> fix(UI): [ENTESB-14025] - fix handling of ?WSDL urls for SOAP

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-adapter/package.json, app/ui-react/yarn.lock
Includes: https://github.com/atlasmap/atlasmap/issues/2260
Cc: @christophd
=> chore: Update to AtlasMap 2.1.0-M.1

app/server/filestore/src/main/java/io/syndesis/server/filestore/impl/SqlFileStore.java
We were returning a closed handler that will be later used and closed by the caller. Reverting the logic not to use try-with-resource (and auto-close the handler).
Fixes #8888
=> fix(server): remove try-with-resource

app/meta/pom.xml, app/pom.xml, app/server/pom.xml, app/server/verifier/pom.xml, app/test/integration-test/pom.xml, app/test/pom.xml
=> fix(dependencies): bump resteasy to 4.5.6.Final

app/connector/sql/src/main/java/io/syndesis/connector/sql/common/SqlStatementParser.java, app/connector/sql/src/test/java/io/syndesis/connector/sql/common/SqlParserTest.java
fixes https://issues.redhat.com/browse/ENTESB-14452
=> fix for ENTESB-14452 - The correct SQL was treated as Invalid

app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSelectMethod.tsx
backport of https://github.com/syndesisio/syndesis/pull/8841 for [ENTESB-14025](https://issues.redhat.com/browse/ENTESB-14025)
=> [backport 1.11.x] - fix for SOAP url handling (ENTESB-14025)

app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKSupport.java
We will report an integration pending status during initialization and building kit phase
Fixes #8848
=> fix(server): include building kit phases

app/connector/sql/src/main/java/io/syndesis/connector/sql/common/SqlStatementParser.java, app/connector/sql/src/test/java/io/syndesis/connector/sql/common/SqlParserTest.java
backport https://issues.redhat.com/browse/ENTESB-14452
=> [backport to 1.11.x] fix for ENTESB-14452 - The correct SQL was treated as Invalid

install/operator/pkg/syndesis/action/install.go
Fixes https://issues.redhat.com/browse/ENTESB-14456
=> Reduce log output when installing addons

app/ui-react/syndesis/craco.config.js, app/ui-react/syndesis/package.json, app/ui-react/syndesis/src/setupProxy.js
Just some things I spotted today for [ENTESB-14421](https://issues.redhat.com/browse/ENTESB-14421)
=> chore: clean up some monaco/dv removal leftovers for ENTESB-14421

app/ui-react/syndesis/craco.config.js, app/ui-react/syndesis/package.json, app/ui-react/syndesis/src/setupProxy.js
backport for [ENTESB-14421](https://issues.redhat.com/browse/ENTESB-14421)
=> (backport) chore: clean up some monaco/dv removal leftovers for ENTESB-14421

install/operator/pkg/syndesis/action/install.go
chore: reduce log output when installing addons.
chore: typo
=> Reduce log output when installing addons.

install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml, install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
But leave the configuration itself since it is used further down.
=> Backport #8979

app/ui-react/packages/auto-form/src/utils.ts
relates to [ENTESB-14198](https://issues.redhat.com/browse/ENTESB-14198)
=> fix: correct value evaluation for select controls

app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfig.tsx, app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfigEdit.tsx
DataTestIds for ApiConnectorDetalConfig page
=> Added DataTestIds for ApiConnectorDetalConfig page

app/common/model/src/main/java/io/syndesis/common/model/connection/ConfigurationProperty.java, app/connector/debezium/pom.xml, app/connector/debezium/src/main/java/io/syndesis/connector/debezium/DebeziumConsumerCustomizer.java, app/connector/debezium/src/test/java/io/syndesis/connector/debezium/DebeziumConsumerCustomizerTest.java, app/connector/kafka/pom.xml, app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaConnectionCustomizer.java, app/connector/kafka/src/main/resources/META-INF/syndesis/connector/kafka.json, app/connector/kafka/src/test/java/io/syndesis/connector/kafka/KafkaConnectionCustomizerTest.java, app/ui-react/syndesis/src/modules/connections/components/WithConnectorForm.tsx, app/ui-react/syndesis/src/modules/connections/pages/ConnectionDetailsPage.tsx, app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx, app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx, app/ui-react/syndesis/src/modules/connections/utils.ts
Now Kafka connector has dynamic <key, value> pairs that allows us to add either additional properties defined explicitly in https://camel.apache.org/components/latest/kafka-component.html or even add additional properties as in "additionalProperties"[1] on the Kafka Camel connector.
[1] https://camel.apache.org/components/latest/kafka-component.html#_options
=> [ENTESB-13846] Adding extra options to Kafka

app/ui-react/packages/ui/src/Shared/InlineTextEdit.css, app/ui-react/packages/ui/src/Shared/InlineTextEdit.tsx
Backport of https://github.com/syndesisio/syndesis/pull/9021 for [ENTESB-14056](https://issues.redhat.com/browse/ENTESB-14056).
=> [backport 1.11.x] - ENTESB-14056 - inline editing

app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.css, app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
backporting https://github.com/syndesisio/syndesis/pull/9030
=> [BACKPORT 1.11.x] - fix(ui) - kafka connector disable fields

app/ui-react/packages/ui/src/Connection/ConnectionDetailsForm.tsx, app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx, app/ui-react/syndesis/src/modules/connections/locales/connections-translations.en.json, app/ui-react/syndesis/src/modules/connections/utils.ts
Backport this fix as requested by [ENTESB-14117](https://issues.redhat.com/browse/ENTESB-14117)
=> (backport) feat: don't show successful validation for unknown connectors

app/ui-react/docker/nginx-syndesis.conf, app/ui-react/nginx-syndesis.conf, app/ui-react/syndesis/src/setupProxy.js
=> fix(ui-react): change oauth cookie name

doc/assemblies/connecting/assembly-connecting-to-odata.adoc, doc/modules/connecting/proc-adding-odata-connections-write.adoc, doc/modules/connecting/proc-creating-odata-connections.adoc
=> doc-update-odata-v2

app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaConnectionCustomizer.java, app/connector/kafka/src/main/resources/META-INF/syndesis/connector/kafka.json, app/connector/kafka/src/test/java/io/syndesis/connector/kafka/KafkaConnectionCustomizerTest.java, app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java, app/server/update-controller/src/test/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandlerTest.java
Removing exception thrown when it shouldn't (re-casting something already casted) and backporting #8597
=> [ENTESB-13846] Kafka custom properties

doc/assemblies/integrating-applications/assembly-managing-integrations.adoc, doc/modules/connecting/proc-adding-odata-connections-write.adoc, doc/modules/integrating-applications/proc-adjusting-integration-configuration.adoc, doc/modules/integrating-applications/ref-troubleshooting-integration-execution.adoc
=> doc update for memory and cpu feature

app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
Fix for [ENTESB-13846](https://issues.redhat.com/browse/ENTESB-13846) - make validation + add buttons use the same class for styling.
cc @Delawen
=> fix(ui): ENTESB-13846 - kafka validate + add button fix

app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
backport of https://github.com/syndesisio/syndesis/pull/9088 for [ENTESB-13846](https://issues.redhat.com/browse/ENTESB-13846)
=> [backport 1.11.x] - fix(ui) - ENTESB-13846 kafka connector

app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderOnExceptionHandler.java, app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderReturnPathCustomizer.java, app/connector/api-provider/src/main/resources/META-INF/syndesis/connector/api-provider.json, app/connector/api-provider/src/test/java/io/syndesis/connector/apiprovider/OnExceptionHandlerTest.java, app/connector/webhook/src/main/java/io/syndesis/connector/webhook/WebhookConnectorCustomizer.java, app/connector/webhook/src/main/resources/META-INF/syndesis/connector/webhook.json, app/connector/webhook/src/test/java/io/syndesis/connector/webhook/WebhookConnectorCustomizerTest.java
https://issues.redhat.com/browse/ENTESB-13988
=> [backport ENTESB-13988] WebHook returns different response code as was set

app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaMetaDataExtension.java, app/connector/kafka/src/main/resources/META-INF/syndesis/connector/kafka.json
Now topic name is a text box with autocomplete using the lastest list of kafka topics.
=> fix(kafka): [ENTESB-14751] Refresh kafka topics on step configuration

app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
backport of https://github.com/syndesisio/syndesis/pull/9086 for [ENTESB-14562](https://issues.redhat.com/browse/ENTESB-14562)
cc @dhirajsb
=> [backport 1.11.x] - fix(ui) - ENTESB-14562

app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
fix for [ENTESB-14562](https://issues.redhat.com/browse/ENTESB-14562)
cc @dhirajsb
=> fix(ui) - ENTESB-14562 - select first option in array for ports + services

install/operator/pkg/syndesis/olm/csv.go
=> chore: fix image in deployment

install/operator/pkg/syndesis/olm/container.go
=> chore: include repository replacement for each fuse component

app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
fix for [ENTESB-14753](https://issues.redhat.com/browse/ENTESB-14753), where if a WSDL file upload times out, there is no indication to the user that any action is occurring, or an error at the end. This fix adds a loader for SOAP configurations and an error on timeout. See the recording/gif [here](https://www.dropbox.com/s/gv7937f1ttc742x/Kapture%202020-10-08%20at%2013.30.39.gif?dl=0).
=> fix(ui): ENTESB-14753 - show WSDL timeout error

app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
backport of https://github.com/syndesisio/syndesis/pull/9119 for [ENTESB-14753](https://issues.redhat.com/browse/ENTESB-14753)
=> [backport 1.11.x] - fix(ui) - ENTESB-14753 - show loader for SOAP + error on timeout

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-adapter/package.json, app/ui-react/yarn.lock
Release note: https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.1.0
=> chore: Update to AtlasMap 2.1.0

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-adapter/package.json, app/ui-react/yarn.lock
Includes:
https://issues.redhat.com/browse/ENTESB-14014
https://issues.redhat.com/browse/ENTESB-14953
https://issues.redhat.com/browse/ENTESB-14189
=> chore: Update to AtlasMap 2.0.9

install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml, install/operator/pkg/apis/syndesis/v1beta2/syndesis_types.go, install/operator/pkg/apis/syndesis/v1beta2/zz_generated.deepcopy.go, install/operator/pkg/syndesis/olm/assets/alm-examples, install/operator/pkg/syndesis/olm/container.go, install/operator/pkg/syndesis/versions/versions_test.go
chore: fixes for csv
chore: remove camelk from CRD
=> Fixes for CSV generation and remove camelk from CRd

app/ui-react/packages/history/modules/LocationUtils.js, app/ui-react/packages/history/modules/createBrowserHistory.js, app/ui-react/packages/history/package.json
=> Compress the data stored in the sessionStorage

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-adapter/package.json, app/ui-react/yarn.lock
Includes: https://issues.redhat.com/browse/ENTESB-10454 version alignment
=> chore: Update to AtlasMap 2.0.10 for 1.11.x

app/connector/aws-ddb/pom.xml, app/connector/pom.xml, app/meta/pom.xml, app/pom.xml, app/server/cli/pom.xml, install/operator/deploy/crds/syndesis.io_syndesis_crd.yaml
https://issues.redhat.com/browse/ENTESB-10454
- Update aws library accordingly to the camel 2.23.2.fuse-780030
- Operator build updated CRD
- Removed unused DynamoDBLocal dependency
=> Fixing dependencies versions: netty, tomcat, kafka-clients (1.11.x)

app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/DetailsPage.tsx
backport of https://github.com/syndesisio/syndesis/pull/9173 for [ENTESB-15132](https://issues.redhat.com/browse/ENTESB-15132)
=> [BACKPORT 1.11.X] - [ENTESB-15132] fix for basePath + host OpenAPI

app/ui-react/packages/api/src/WithApiConnectorHelpers.tsx, app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailBody.spec.tsx, app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailConfig.spec.tsx, app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailConfigEdit.spec.tsx, app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailBody.tsx, app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfig.tsx, app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfigEdit.tsx, app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
backport of https://github.com/syndesisio/syndesis/pull/9179 for [ENTESB-15273](https://issues.redhat.com/browse/ENTESB-15273)
=> [BACKPORT 1.11.X] - [ENTESB-15273] API connector

app/connector/fhir/src/main/java/io/syndesis/connector/fhir/customizer/FhirPatchCustomizer.java, app/connector/fhir/src/main/resources/META-INF/syndesis/connector/fhir.json
=> fix: Missing patch body in FHIR Patch operation

app/server/runtime/src/main/resources/application.yml
Removing example repository. This was getting added to all the custom repositories configured.
=> [ENTESB-15063] Removing default maven repository

app/server/runtime/src/main/resources/application.yml
=> Backport #9177

app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json, app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json, app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
backport of https://github.com/syndesisio/syndesis/pull/9211 for [ENTESB-15349](https://issues.redhat.com/browse/ENTESB-15349)
=> [BACKPORT 1.11.x] - fix(ui) ENTESB-15349: update doc links to version 7.8

app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json, app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json, app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
fixes [ENTESB-15349](https://issues.redhat.com/browse/ENTESB-15349), where version 7.7 is still used for the user docs.
=> fix(ui) - ENTESB-15349 - update version in doc links for 7.8

app/pom.xml
https://issues.redhat.com/browse/ENTESB-15145
=> Backport Fix for ENTESB-15145 - upgrade commons compress version

app/pom.xml
https://issues.redhat.com/browse/ENTESB-15145
=> Fix for ENTESB-15145 - upgrade commons compress version

.github/workflows/backport.yml
We don't need to pass the token.
=> refactor(ci): remove passing token

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-adapter/package.json, app/ui-react/yarn.lock
https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.1.1
=> chore: Update to AtlasMap 2.1.1

app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlConnectorVerifierExtension.java, app/pom.xml, app/server/dao/src/main/java/io/syndesis/server/dao/init/ReadApiClientData.java, app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
A number of false positives have been fixed.
=> chore: update spotbugs to 4.2.0

app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx, app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
backport of https://github.com/syndesisio/syndesis/pull/9284 to fix [ENTESB-11603](https://issues.redhat.com/browse/ENTESB-11603)
=> [BACKPORT 1.12.x] [ENTESB-11603] - prevent configured properties from being cleared in integration + API connector editors

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-adapter/package.json, app/ui-react/yarn.lock
Release Note: https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.1.3
=> chore: Update to AtlasMap 2.1.3

app/ui-react/syndesis/src/modules/integrations/components/editor/EditorSidebar.tsx
backport of https://github.com/syndesisio/syndesis/pull/9302 for [ENTESB-11411](https://issues.redhat.com/browse/ENTESB-11411)
=> [backport 1.12x] fix(UI): [ENTESB-11411] - display a generic step icon when replacing a step

app/connector/fhir/src/main/java/io/syndesis/connector/fhir/customizer/FhirPatchCustomizer.java, app/connector/fhir/src/main/resources/META-INF/syndesis/connector/fhir.json
https://issues.redhat.com/browse/ENTESB-14237
(cherry picked from commit 3bbb6c632acfe42ac3171235b88c5bd3ea5939a0)
=> ENTESB-14237 1.12.x

tools/bin/commands/release
=> fix(release): fix typo

tools/bin/commands/release
=> fix: typo in release script

tools/bin/commands/release
Backport of #9299, #9300, #9308, and #9312
=> Tagging operator image with moving tag and pushing to quay.io (1.12.x)

tools/bin/commands/release
Backport of #9299, #9300, #9308, and #9312
=> Tagging operator image with moving tag and pushing to quay.io (1.11.x)

app/integration/runtime-springboot/src/test/java/io/syndesis/integration/runtime/sb/jmx/CamelContextMetadataMBeanTest.java, app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/util/XmlSchemaHelperTest.java
=> refactor(cleanup): remove unused imports

app/integration/bom/pom.xml, app/pom.xml, app/ui-react/packages/atlasmap-adapter/package.json, app/ui-react/yarn.lock
https://issues.redhat.com/browse/ENTESB-15520
Succeeding #9295, #9287, #9263
Release Notes:
* https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.1.4
* https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.1.3
* https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.1.2
* https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.1.1
* https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.1.0
=> chore: Update to AtlasMap 2.1.4

app/common/util/src/main/java/io/syndesis/common/util/ErrorCategory.java, app/connector/ftp/pom.xml, app/connector/ftp/src/main/java/io/syndesis/connector/ftp/FtpConnectorCustomizer.java, app/connector/ftp/src/main/java/io/syndesis/connector/ftp/FtpPayload.java, app/connector/ftp/src/main/resources/META-INF/syndesis/connector/ftp.json, app/connector/ftp/src/test/java/io/syndesis/connector/ftp/PayLoadTest.java, app/connector/support/processor/src/test/java/io/syndesis/connector/support/processor/ErrorMapperTest.java, app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/Processors.java, app/pom.xml
https://issues.redhat.com/browse/ENTESB-14755
- fixing issue with the fileName filter by pulling in a new version of Camel
- Adding Customizer to support parsing the incoming body and set the CamelFileName Header
- QuickStart: https://github.com/syndesisio/syndesis-quickstarts/tree/trunk/api-provider-with-ftp
=> ENTESB-14755 Extend ftp connector
