- app/ui-angular/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.html
- app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Adds simple language expression examples to conditional flows configuration page.
Tried to fix for both angular and react
Fixes #5485
> fix: Add simple language syntax examples in conditional flows config page

- tools/bin/commands/release
- tools/upgrade/Dockerfile
fix(build): disable metalink for epel
Seems that the mirror selected by metalink in most cases ends up
returning `503 Service Unavailable` this disables metalink for the EPEL
repository making the build more robust.
fix(build): don't rebuild UI when staging Maven artifacts
Skips UI related modules when staging Maven artifacts.
Ref #5468
> More fixes for release builds

- tools/bin/commands/release
When building UI docker images for the release we don't need to invoke the whole build `fabric8:build` is enough. Also fixes a typo from previous commit.
Ref #5468
> fix(build): avoid UI builds when building docker images for release

- tools/bin/commands/util/common_funcs
When on CircleCI and running a build for the `master` branch the computation of incremental changes is not taken into account as it tries to determine differences between `master` and `master`, for this we need to check the `CIRCLE_SHA1` environment variable to gather the files changed for a particular commit.
> fix(ci): consider changes on `master` for commit

- .circleci/config.yml
Tries to filter out images that haven't been built from so that the build doesn't fail trying to push images that do not exist.
Kinda wrote this one blindly (no way to test really), might need a second pair of eyes.
> fix(ci): don't try to push images that do not exist

- .circleci/config.yml
We need to refine the incremental build on CircleCI a bit more before it is enabled. This disables it for now.
> fix(ci): disable incremental build

- doc/sdh/cli/cmd_install.adoc
permission grant command line is missing the `install` command. By default `build` command is executed in syndesis binary
> docs: Fix permission grant command line on arbitrary cluster install

- app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftConfigurationProperties.java
- app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
- app/server/openshift/src/test/java/io/syndesis/server/openshift/OpenShiftServiceImplTest.java
- install/generator/04-syndesis-server.yml.mustache
- install/syndesis.yml
The integration pod's initial delay to start the liveness probe is configurable via the `integrationLivenessProbeInitialDelaySeconds` property. Each integration app is different and we don't know exactly the maximum time an integration might take to start. Liveness probes must not start while the apps are still starting otherwise it risks restarting them before they are fully started.
fix #5328
> fix: Add liveness check to Spring Boot integrations

- app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java
- app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/AbstractODataReadRouteTest.java
- app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteNoSplitResultsTest.java
- app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java
- app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-people-data-1-expanded-trips.json
* ACCEPT header was overridden to include odata.metadata=full, which was
thought to be necessary to make complex values work correctly. This is
not the case with removal complex value work fine & queries work again.
* Specifically, despite odata.metadata=full being legitimate it appears
to cause an error on the reference server when added to the ACCEPT
header & since not necessary, removal is preferable.
* Adds test for filter & expand and removes hang-over increases in mock
result wait times which are only required for debugging.
> fix(5512): Fixes 500 response failure in odata queries

- app/ui-angular/src/app/integration/edit-page/step-configure/templater/codemirror/mustache-mode-lint.ts
* CodeMirror editor starts at line 0 (due to array index) so need to
increment in order to display correct line number to user.
* This only affects the mustache lint as both velocity and freemarker
already deal with this internally.
* Note. This fixes the angular UI only.
> fix(5273): Mustache errors showing wrong line number

- install/operator/deploy/manifests/1.7.x/syndesis.crd.yaml
- install/operator/deploy/manifests/1.7.x/syndesisoperator.1.7.x.clusterserviceversion.yaml
- install/operator/deploy/manifests/syndesis.package.yaml
Based on our previous discussions I created this new PR, some considerations:
- This is an operator for upstream, I have replaced Fuse Online references for Syndesis
- It is using the [manifests format](https://github.com/operator-framework/operator-registry#manifest-format) recommended by [operator-courier](https://github.com/operator-framework/operator-courier)
- All relevant files are now under `deploy` dir
- The package version is 1.7.x while the operator version will be the latest within 1.7.x range
Observations:
- I couldn't come up with that much for the description. Having a look at other operators, ppl have a sections describing the accepted values of the CR, but since we don't use the CR for reconciling (as far as I know), this section fell flat for us, unless we want to comment …
> Add olm integration files for syndesis

- app/connector/amqp/src/main/resources/META-INF/syndesis/connector/amqp.json
And today's connector is AMQP. This makes the names of the input fields have a consistent style, corrects a few incorrect hints, adds some periods.
> fixes #5626 partially. Updates UI text for AMQP connector.

- app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
I think this update corrects the description for the Periodic SQL Invocation action, which is available only as a SQL start connection, and supports only specification of a SELECT statement. 
I should have put "fixes: #4878 " in the commit message.
> fixes: #4878 Correct description of Periodic SQL invocation action

- app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlConnectorMetaDataExtension.java
- app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlSupport.java
- app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlConnectorCustomizer.java
- app/connector/sql/src/main/java/io/syndesis/connector/sql/db/DbDerby.java
- app/connector/sql/src/main/java/io/syndesis/connector/sql/db/DbOracle.java
Fixes #5647
SQL connector customizer was not using proper db schema property when parsing the given statement to its meta data. This caused parameters (e.g. for insert) to be missing for SQL statement execution
> fix: missing db schema handling in sql connector customizer

- app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/AbstractODataCustomizer.java
- app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteNoSplitResultsTest.java
- app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java
* If a null body is encountered (filtered out by consumer) then the
converter returns the message as the body. As such. the jackson object
mapper is unable to serialise this to json and present a stackoverflow
exception.
* Properly handles a null body and returns empty json without resorting to
the object mapper.
* Tests to verify the fix.
> fix(5533): Fix OData Read Customizer in the event of null message body

- install/generator/04-todo-example.yml.mustache
- install/syndesis.yml
todo sample application was not working after we have moved the tables in Postgres to a separate schema "sampledb". The todo app needs to use the schema in its SQL statements.
The corresponding todo app PR is https://github.com/syndesisio/todo-example/pull/17 and needs to be merged as well in order to fix this.
> fix: Add db schema support to sample todo app

- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/api/ApiGeneratorHelper.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/api/ApiHandler.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationSpecificationHandler.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/api/ApiGeneratorHelperTest.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationSpecificationHandlerTest.java
- app/server/runtime/src/test/java/io/syndesis/server/runtime/integration/ApiIntegrationUpdateITCase.java
When creating an integration from the OpenAPI document prior to saving the integration there is a need to modify the OpenAPI document and have the changes reflect in the integration.
This adds a `PUT /api/v1/apis/generator` that returns HTTP status `202` and the updated integration when the provided OpenAPI document produces changes to the integration; and HTTP status `304` with no content when there are no changes to the integration.
There's a side effect of storing the updated OpenAPI document and referencing it from the integration resources, if there was an update.
Fixes #5719
> feat(api): add `PUT /api/v1/apis/generator`

- app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx
- app/ui-react/packages/ui/src/Shared/TextEditor/TextEditor.css
- app/ui-react/syndesis/src/modules/data/shared/DvConnections.tsx
- app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
Fix issue with highlighting of selected connection in the DV import data wizard.
- DvConnections component maintains current connection selection.  The wizard allows a single connection to be selected
- Now allow setting of an initial selection on DvConnections
- also adding 'show-hint' import to TextEditor.css.  The SQL autocomplete hints are now displayed
> TT-624 Fix Connector selection in DV wizard

- app/connector/kafka/src/main/resources/META-INF/syndesis/connector/kafka.json
Adding more info to the tooltip to address #4234.
> fix #4234 kafka validation kills meta pod

- app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.css
- app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx
- app/ui-react/packages/ui/src/Integration/Details/IntegrationExposedURL.css
- app/ui-react/packages/ui/src/Integration/Details/IntegrationExposedURL.tsx
- app/ui-react/packages/ui/src/Integration/IntegrationStepsHorizontalItem.css
- app/ui-react/packages/ui/src/Integration/IntegrationStepsHorizontalItem.tsx
- app/ui-react/packages/ui/src/index.css
- app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailHeader.tsx
- app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailSteps.css
- app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailSteps.tsx
* wrap integration steps better when on multiple lines
* remove extra space under integration name when alert isn't present
* add label for external url copy to clipboard
* improve alignment in activity list view items
> fix(integrationdetails): various UI fixes

- app/connector/box/src/main/resources/META-INF/syndesis/connector/box.json
Fixes #5704 
SQS and SNS are not TP, Knative has already TP, mail connector too, odata I don't think is a TP.
> fix(box connector): Add Technology Preview label for Box connector

- app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
This updates the value of **product.version** from **7.1** to **7.4** in:
app/ui-react/syndesis/src/i18n/locales/shared-translations-en.json
Also in that file, there are user doc links that refer to **product.version**.
Currently, in the staging site, the help icon links still point to 7.3 doc, so the angular dictionary file must still be in use for staging. 
The links to 7.4 doc **WILL NOT WORK** until 7.4 GA, which is when the doc is published. 
These are the links that will work when 7.4 doc is published:
https://access.redhat.com/documentation/en-us/red_hat_fuse/7.4/html-single/fuse_online_sample_integration_tutorials/index
https://access.redhat.com/documentation/en-us/red_hat_fuse/7.4/html-single/integrating_applications_with_fuse_online/index …
> required update of project.version to 7.4 in dictionary file

- app/server/runtime/src/test/java/io/syndesis/server/runtime/ExtensionsITCase.java
- app/server/update-controller/pom.xml
- app/server/update-controller/src/main/java/io/syndesis/server/update/controller/usage/UsageUpdateHandler.java
Removing rxjava from the update handler should help with the determinism of the usage updates. Also changes the timeout in the test from 60 to 10 seconds.
Fixes #4827
> fix: remove rxjava from update handler

- doc/connecting/topics/p_add-google-sheets-connection-append-sheet-values.adoc
- doc/connecting/topics/p_add-google-sheets-connection-get-sheet-values.adoc
- doc/connecting/topics/p_add-google-sheets-connection-update-sheet-values.adoc
This updates the user doc for adding a Google Sheets connection that obtains values. There are several updates: 
- Specification of a Row header number, and then the Column names field. 
- Remove known issue about when Max results is ignored. 
- Change default value/behavior of Max results.
- Can obtain spreadsheet values in a middle connection in a flow
Christoph reviewed this content. Now it needs a QE review. But I'm merging this and will update later as needed.
> user doc: Update doc for Google Sheets connection that obtains values

- app/ui-react/packages/ui/src/Dashboard/TopIntegrationsCard.tsx
- app/ui-react/packages/ui/src/Integration/IntegrationsEmptyState.tsx
- app/ui-react/packages/ui/src/Integration/IntegrationsListView.tsx
- app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.css
- app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
- app/ui-react/packages/ui/src/Integration/index.ts
- app/ui-react/packages/ui/stories/Integration/IntegrationDetail.stories.tsx
- app/ui-react/packages/ui/stories/Integration/IntegrationsEmptyState.stories.tsx
- app/ui-react/packages/ui/stories/Integration/Metrics/IntegrationDetailsMetrics.stories.tsx
- app/ui-react/packages/utils/src/dateHelpers.ts
- app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
- app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
- app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.it.json
- app/ui-react/syndesis/src/modules/integrations/pages/IntegrationsPage.tsx
- app/ui-react/syndesis/src/modules/integrations/pages/detail/MetricsPage.tsx
- See #5715 and #5729 
- added empty state to dashboard's TopIntegrationCard
- added empty state to integrations list
- fixed issues in metrics page when not all metrics are available
- changed data helpers util to return '0 ms' when duration is zero.
> fix(5715,5729) and add empty state components for integration-related components

- tools/bin/commands/kamel
- tools/bin/commands/util/camel_k_funcs
While fixing some bugs with Camel K I've realized that configuring syndesis to use camel k and working with libraries is a half-nightmare, so I've added a "syndesis kamel" script with some useful commands to help syndesis developer. Don't know if this approach can be extended to be useful also for QE.
Note: all the commands require a full build of the backend `syndesis build -c -f -b`.
Basically:
- `syndesis kamel --activate` configures syndesis to use camel k as integration runtime (`--deactivate` restores `s2i`)
- `syndesis kamel --configure` makes sure that the camel k integration platform is ready to be used for syndesis development, no matter which version of Camel K you're using (0.3.4+). This includes loading the catalog and configuring maven mirrors
- `syndesis kamel …
> chore(dev): improve dev experience with Camel K

- app/ui-react/packages/.storybook/vendor.css
- app/ui-react/packages/auto-form/package.json
- app/ui-react/packages/auto-form/src/FormBuilder.tsx
- app/ui-react/packages/auto-form/src/widgets/FormCheckboxComponent.css
- app/ui-react/packages/auto-form/src/widgets/FormCheckboxComponent.tsx
- app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
- app/ui-react/packages/auto-form/src/widgets/FormInputComponent.tsx
- app/ui-react/packages/auto-form/src/widgets/FormSelectComponent.tsx
- app/ui-react/packages/auto-form/src/widgets/FormTextAreaComponent.tsx
- app/ui-react/packages/auto-form/src/widgets/helpers.ts
- app/ui-react/packages/auto-form/src/widgets/index.ts
- app/ui-react/packages/ui/src/Integration/Editor/endpoint/DescribeDataShapeForm.tsx
- app/ui-react/packages/ui/src/index.css
- app/ui-react/yarn.lock
This PR removes the green text highlighting and border from auto-form inputs in success states and replaces the pf3 style field level help with a pf4 variation. I've updated the shared widgets in auto-form as well as the describe data shape step.
What do we think about the new info icon. That was the closest match to what we had previously, can update if need be.
The only other thing is that I find it difficult to close the popover, my cursor is in within bounds of the button element but seem to only be able to close it when hovered over the svg inside. It's pretty annoying now that we have more of these popovers throughout the app. Does anyone else see this? I can investigate this on the pf side if so.
remove green input border for success state in auto-form
replace pf3 field level help …
> Auto form adjustments

- doc/connecting/topics/p_adding-db-connection-start.adoc
Previously, the doc for the Query input field for a SQL start connection, Periodic SQL Invocation action, said that you had to enter a SELECT statement. This was wrong. I updated it to indicate that you have to enter a SQL statement that returns one or more records.
> user doc: Correct Query input field description for SQL connection

- doc/connecting/topics/p_creating-kafka-connections.adoc
This adds the following note to the topic about creating a Kafka connection: 
In this release, connections to Kafka do not support SSL. It is expected that this will change in a future release.
> user doc: Add SSL limitation to doc for Kafka connector

- app/common/model/pom.xml
- app/common/model/src/main/java/io/syndesis/common/model/filter/Op.java
- app/common/model/src/test/java/io/syndesis/common/model/filter/OpTest.java
This adds labels for filter operations that had them set to empty string and fixes the operator for the not equal filter operation.
Fixes #5702
> fix: make sure that operation and label are unique

- app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
We should not invoke `POST /api/v1/connectors/{id}/credentials` when
`GET /api/v1/connectors/{id}/credentials` is not returning
`AcquisitionMethod` of type `OAUTH*`.
Fixes #5831
> fix: connection creation issue

- app/server/credential/src/main/java/io/syndesis/server/credential/AcquisitionMethod.java
- app/server/credential/src/main/java/io/syndesis/server/credential/CredentialProviderRegistry.java
- app/server/credential/src/main/java/io/syndesis/server/credential/OAuth1CredentialProvider.java
- app/server/credential/src/main/java/io/syndesis/server/credential/OAuth2CredentialProvider.java
- app/server/credential/src/main/java/io/syndesis/server/credential/UnconfiguredProperties.java
- app/server/credential/src/main/java/io/syndesis/server/credential/generic/OAuth2CredentialProviderFactory.java
- app/server/credential/src/main/java/io/syndesis/server/credential/salesforce/SalesforceCredentialProviderFactory.java
- app/server/credential/src/main/java/io/syndesis/server/credential/twitter/TwitterCredentialProviderFactory.java
- app/server/credential/src/test/java/io/syndesis/server/credential/OAuth1CredentialProviderTest.java
- app/server/credential/src/test/java/io/syndesis/server/credential/OAuth2CredentialProviderTest.java
- app/server/runtime/src/test/java/io/syndesis/server/runtime/SetupITCase.java
- app/server/runtime/src/test/java/io/syndesis/server/runtime/credential/CredentialITCase.java
- app/ui-react/packages/models/swagger.internal.json
- app/ui-react/packages/models/swagger.json
- app/ui-react/packages/ui/src/Connection/ConnectionSetupOAuthCard.tsx
- app/ui-react/packages/ui/src/Connection/index.ts
- app/ui-react/syndesis/src/modules/connections/locales/connections-translations.en.json
- app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
When creating OAuth-capable connections issues can arise when connection properties are configured by manual entry. For instance refresh token that is hidden from the UI will not be filled and the connection will not be valid as the access token for it will expire and could not be renewed.
This introduces a change in the connection creation that if a new OAuth-capable connection creation is attempted OAuth settings must be set. The user is prompted to enter the properties in OAuth settings and when those are set, connection creation via OAuth flow is allowed.
Fixes #5582
> feat: require OAuth settings for connection creation

- app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationBase.java
- app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationDeployment.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandlerTest.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandlerTest.java
* Rather than updating resources in jsondb with a deleted flag, actually
remove them instead.
* Deprecate delete flag methods, preserving for use by existing installs
* ConnectionHandler
* Remove ConectionBulletinBoards when deleting connections
* IntegrationHandler
* Remove Integrations, IntegationDeployments & IntegrationBulletinBoards
* Adds / updates tests
> fix(5321): Actually delete integrations and connections on delete

- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/credential/CredentialHandler.java
- app/ui-react/syndesis/src/modules/connections/pages/ConnectionDetailsPage.tsx
We need to save (invoke `PUT /api/v1/connections/{id}`) when reconnecting the OAuth-capable connection.
Fixes #5763
> fix: save the updated connection on OAuth reconnect

- app/ui-react/packages/api/src/useConnectorCredentials.tsx
When `GET /api/v1/connectors/{id}/credentials` response is `{}` the `useApiResource` will provide `undefined` as the the response. This causes an issue as `Object.keys(undefined)` throws an Error. Also there is no need to transform it to `undefined` as the code that handles the response handles both `{}` and `undefined` cases as the result from `useConnectionCredentials` is typed `<AcquisitionMethod | undefined>`.
The check later in the code tries to determine by accessing `AcquisitionMethod.type` and `AcquisitionMethod.configured`, but also handles when the returned `AcquisitionMethod` is `undefined`.
The very odd thing about this issue is that when running locally via `yarn watch:app:proxy` this issue did not occur, but could be reproduced when deployed on minishift.
Fixes #5831
> fix: handle credentials response without transformation

- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/PropertyGenerators.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SupportedAuthenticationTypes.java
- app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/PropertyGeneratorsTest.java
- app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/SupportedAuthenticationTypesTest.java
With #5669 we added support for adding a name of the security definition to distinguish between two authentication methods of the same type to the `authenticationType` configured property value. At the same time when the connector is to be created the authentication method selected by the end user needs to be paired with the security definition from the OpenAPI document.
Here we did not account for the additional name of the security definition that can be present in the value of the `authenticationType` configured property. This makes sure that we support both variants in the `authenticationType` configured property.
Fixes #5855
> fix: honor both syntaxes for authenticationType

- app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
@zregvart this will be a blocker when someone notices it :-)
Effectively by uploading a library extension I've made it so nobody using staging can really add connections to integrations.
> fix: not all extensions have actions (the sequel)

- app/connector/gmail/pom.xml
- app/connector/gmail/src/main/java/io/syndesis/connector/gmail/GmailSendEmailCustomizer.java
* Rather than allowing exceptions to occur while processing missing
properties, check them explicitly and bail out with exceptions
* For properties, subject & text, which are technically important but not
strictly required, provide warning messages.
> fix: provide better error descriptions in gmail customizer

- app/ui-react/packages/models/src/dv.d.ts
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewEditContent.tsx
- app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
- app/ui-react/syndesis/src/modules/data/pages/ViewEditPage.tsx
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
ENTESB-10845 - Addresses view DDL validation issues.
- adds 'isUserDefined' attribute to ViewDefinition.  For new views userDefined is false.  When the user edits/saves the viewDdl via the editor, userDefined is true
- ViewEditPage - the server call to get model ddl was eliminated.  The individual view ddl is now maintained in komodoServer.  It can be obtained directly from the viewDefinition.  Also added pushNotifications on this page
> TTOOLS-661 resolve issue with view name validation

- app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
When we create a connection in OAuth flow we need to pass the `configuredProperties` that have been pre-configured on the connector.
Another way to fix this would be to include `configuredProperties` from the connector when passing parameters to connection validation. This makes it in-line for OAuth based connectors as it does for non-OAuth based connectors.
Fixes #5891
> fix: pass `configuredProperties` from connector in OAuth flow

- app/ui-react/syndesis/src/modules/integrations/components/editor/makeEditorResolvers.ts
- app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
fixes #5887
I also had to hide the data mapper warning icon as well when the conditional flow step is involved, as the conditional flow also causes that to show up if the describe data warning isn't shown.
> fix: suppress showing editor warning icons for the conditional flow step

- install/operator/.lib.sh
- install/operator/pkg/generator/assets/assets_generate.go
- install/operator/pkg/generator/dev/dev.go
- install/operator/pkg/generator/generator.go
- install/operator/pkg/generator/generator_test.go
- install/operator/pkg/generator/mode_dev.go
- install/operator/pkg/generator/mode_prod.go
This lets you have quicker cycles on if your testing from your desktop.  But if if it’s compiled into prod mode, it panics since it can’t find the source files.
> Fixes #5888: Only compile in the dev mode logic if you build with “-—tags dev”

- app/server/endpoint/pom.xml
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/actuator/ConnectorsEndpoint.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/actuator/ConnectorsMvcEndpoint.java
- app/server/endpoint/src/main/resources/META-INF/spring.factories
- tools/bin/commands/dev
- tools/bin/commands/kamel
This is the `syndesis dev --update-manifest <connector>` command I've shown.
It uses spring-boot actuator under the hood to pass the new connector. Don't know if we should use a different strategy or we need to protect more the endpoint (management port is only exposed locally to the container and cannot be called from outside.. I port-forward in the pod to call it).
Wdyt?
> chore(dev): add a update-manifest dev command

- app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/AuthenticationCustomizer.java
- app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/AuthenticationCustomizerTest.java
Due to the change in how the values for `authenticationType` option are configured, the support for named security definitions, the connector customizer for authentication needs to handle conversion from String to `AuthenticationType` enum differently -- using `AuthenticationType::fromString` method.
Fixes #5900
> fix(connector): support named authentication type

- app/common/model/src/main/java/io/syndesis/common/model/Kind.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/resource/ResourceHandler.java
- app/server/runtime/pom.xml
- app/server/runtime/src/test/java/io/syndesis/server/runtime/resource/ResourceITCase.java
- app/ui-react/packages/models/swagger.internal.json
- app/ui-react/packages/models/swagger.json
This adds an endpoint at `GET /apis/v1/resources/{kind}/{id}` that can be used to fetch OpenAPI resources via `GET /apis/v1/resources/open-api/{id}`.
Fixes #5936
> chore: add handler to fetch OpenAPI resource

- app/connector/jira/pom.xml
- app/connector/jira/src/main/java/io/syndesis/connector/jira/JiraVerifierExtension.java
Fix Jira connector validation. Previously the angular-ui didn't send the "password" parameter, now the react-ui sends an empty username/password that needs to be checked. Without this fix, when the user correctly set the oauth parameters, as the username/password takes precedence and are only checked for null, the verify connection will fail.
> Fix Jira connector validation

- install/generator/04-syndesis-oauth-proxy.yml.mustache
- install/syndesis.yml
Seems that the request for `/config.json` is resulting in a 302 redirect to the HTML page served from oauth-proxy to authenticate. Parsing this response as JSON fails and we get an error in the UI.
This only seems to happen on a particular installation, and I think this should fix this issue. Having public `/config.json` doesn't seem like a security issue to me.
Fixes #5602
> fix: don't require authentication for /config.json

- app/common/model/src/main/java/io/syndesis/common/model/Schema.java
- app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationBase.java
- app/common/model/src/main/java/io/syndesis/common/model/openapi/OpenApi.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java
- app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGeneratorTest.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/api/ApiGeneratorHelper.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/api/ApiGeneratorHelperTest.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationSpecificationHandlerTest.java
- app/server/runtime/src/main/resources/migrations/up-30.js
- app/server/runtime/src/test/java/io/syndesis/server/runtime/integration/ApiIntegrationUpdateITCase.java
- app/server/runtime/src/test/java/io/syndesis/server/runtime/integration/IntegrationSpecificationITCase.java
- app/server/runtime/src/test/java/io/syndesis/server/runtime/migrations/MigrationsHelper.java
- app/server/runtime/src/test/java/io/syndesis/server/runtime/migrations/UpgradeVersion29Test.java
- app/server/runtime/src/test/java/io/syndesis/server/runtime/migrations/UpgradeVersion30Test.java
- app/server/runtime/src/test/resources/migrations/30/integration.json
Before this we correlated API operations from OpenAPI document by embedding the integration id and the operation id in the flow id. This stores the operation id in the flow metadata and uses key generator generated keys for flow ids.
List of endpoint changes:
- `POST /api/v1/apis/generator` doesn't set integration id, flow ids are key-generated, operation ids are placed in metadata
- `PUT /api/v1/apis/generator` and `PUT /api/v1/integrations/{id}/specification` correlate using operation id stored in the metadata
Schema was upgrated to 30 and a migration was added to change the flow ids and put the operation id in the flow metadata.
Fixes #5963
> refactor: don't use flow id to correlate API operations

- app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json
- app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json
In GMail connector, sets the configured property to `"me"`: to be on the safe side as the `userId` property can be used from the Camel component in some weird way. It's used in the verifier, though there it could be replaced with a constant of `"me"`.
In Google Calendar coonector, removes the `userId` property: the underlying Camel component doesn't have a `userId` property and it's not used in the connector.
Fixes #5891
> GMail and Google Calendar connector OAuth fixes

- doc/integrating-applications/topics/as_copying-integrations-to-other-environments.adoc
- doc/integrating-applications/topics/as_managing-integrations.adoc
- doc/integrating-applications/topics/p_importing-integrations.adoc
I updated the doc about export/import integrations to clarify the difference between using the UI and using environment tags. Some  content is relevant and correct only downstream, so I conditionalized it to render only downstream. Of course, it still appears in upstream source. At some point, we need to publish Syndesis user doc to the Syndesis community site. There, the content that is relevant only downstream, will not appear. Next release maybe. 
In the doc for importing integrations, I also added a link to the doc for the Jira connector. That doc does not yet exist, but it will.
> user doc: Conditionalize text that applies only downstream

- app/ui-react/packages/atlasmap-assembly/package.json
- app/ui-react/yarn.lock
was done manually.
@cunningt FYI
> [Backport 1.7.x]  fix: remove karma-jasmine-jquery and therefore the transitive bower dependencies

- app/server/credential/pom.xml
- app/server/credential/src/main/java/io/syndesis/server/credential/AcquisitionMethod.java
- app/server/credential/src/main/java/io/syndesis/server/credential/OAuth1CredentialProvider.java
- app/server/credential/src/main/java/io/syndesis/server/credential/OAuth2CredentialProvider.java
- app/server/credential/src/test/java/io/syndesis/server/credential/AcquisitionMethodTest.java
- app/server/credential/src/test/java/io/syndesis/server/credential/OAuth1CredentialProviderTest.java
- app/server/credential/src/test/java/io/syndesis/server/credential/OAuth2CredentialProviderTest.java
- app/server/runtime/src/test/java/io/syndesis/server/runtime/SetupITCase.java
- app/server/runtime/src/test/java/io/syndesis/server/runtime/credential/CredentialITCase.java
- app/ui-react/packages/models/swagger.internal.json
- app/ui-react/packages/models/swagger.json
With #5924 the `configured` was refactored to `isConfigured` so that the Swagger core JAX-RS support recognizes the property. This made the serialization to JSON serialize it as `isConfigured` instead of `configured` as declared in the internal OpenAPI document.
This reverts that refactor, and the adds `@JsonProperty` annotation to explicitly name the property as `configured`.
Fixes #6005
> fix: AcquisitionMethod JSON serialization

- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/BaseSwaggerConnectorGenerator.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/PropertyGenerators.java
- app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/BaseSwaggerConnectorGeneratorTest.java
- app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/PropertyGeneratorsTest.java
When two or more security definitions of the same type are present in the OpenAPI document allow properties to be defined only from the selected authentication type in the configured properties.
Fixes #5490
> fix(server): multiple authentication methods clash

- app/ui-react/syndesis/package.json
Remove cypress from dev-dependencies - it requires external binaries that are unavailable inside the proxy.  
Talked to @riccardo-forina about this and he said it was not used currently but would be in the future and that it would be okay in 1.7.x to build without the dependency on cypress.    I'll figure out how to get cypress installed for 1.8, but if we could remove it for 1.7.x that would be helpful.
> Remove cypress from dev-dependencies

- app/pom.xml
- app/ui-angular/pom.xml
- app/ui-react/pom.xml
Adding a number of changes here to support the build of the ui behind a proxy.      The execution phases needed to be changed so that yarn/npm install happened first, then downloads / config changes, and then the build.
yarnInheritsProxyConfigFromMaven needed to be added to a number of executions so that maven does not add in --proxy to yarn commands like lint where that option is not supported.
Some additional changes here to support the required downloads of node-sass and iltorb.
Similar changes need to go into master, but I will do them separately because I think there need to be other additions (cypress, etc).
> Changes to ui poms (phases, node-sass/iltorb) for proxies

- app/integration/bom/pom.xml
- app/pom.xml
- app/ui-react/packages/atlasmap-assembly/package.json
- app/ui-react/yarn.lock
This is a manual backport for #6061. I ran `yarn install` on `ui-react` and added the `yarn.lock`.
Ref #6053 https://github.com/atlasmap/atlasmap/issues/1078
chore: Update to AtlasMap 1.40.2
(cherry picked from commit df06692b459113e34ac2c5bfe85be4633ee3c954)
```
#	app/integration/bom/pom.xml
#	app/pom.xml
#	app/ui-react/packages/atlasmap-assembly/package.json
#	app/ui-react/yarn.lock
```
> chore: Update to AtlasMap 1.40.2 (#6061)

- doc/integrating-applications/topics/c_about-extension-definitions.adoc
- doc/integrating-applications/topics/r_descriptions-of-user-interface-properties-in-extension-definitions.adoc
This just adds a cross-reference from the topic that talks about the requirements in the extension definition json file to the topic that describes the user interface properties that the json file needs to specify.
> user doc: add xref from general json def file info to ui details

- app/ui-angular/pom.xml
- app/ui-react/pom.xml
I tested out the changes made in fa3cbe42637b33c1bf8015c2ac64862725224322 and would like to change the phases of the node-sass/iltorb download to generate-sources.     Keeping the phase as generate-sources makes debugging easier (all of the executions in the profile then happen back to back and the order that they are listed in the profile ensures that they execute correctly).
> Change phases of iltorb/node-sass download to generate-sources

- doc/integrating-applications/topics/p_adding-conditional-execution-flows.adoc
This note is conditionalized to be rendered in only downstream doc. 
So no need to backport this to 1.7.
> user doc: Add Tech Preview note to doc for conditional flows.

- app/extension/bom/pom.xml
- app/integration/bom-camel-k/pom.xml
- app/integration/bom/pom.xml
- app/pom.xml
- install/generator/05-syndesis-security.yml.mustache
- install/operator/deploy/manifests/1.7.0/syndesisoperator.1.7.0.clusterserviceversion.yaml
- install/operator/deploy/syndesis-operator.yml
- install/syndesis.yml
Fix #6028
Fix #5914
When installing upstream version from template (or legacy mode), some errors are thrown but they are related to camel k and knative and you can ignore them. This is the same behavior it was present before on upstream template.
Those errors will not be present in the final product release.
I've added back the viewer role to let prometheus scrape pods.
This fixes the problem with previous version, that only worked  with full cluster-admin permissions, because it required permissions that are normally not allowed to standard users.
> Fix syndesis permissions and legacy mode

- tools/upgrade/migration/resource/02_ui_config_map_upgrade.sh
- tools/upgrade/migration/resource/03_server_config_map_upgrade.sh
YAY! my first adventure in python! 
Add missing config map migration scripts adding following entries to config maps:
- syndesis-ui-config
```
"datavirt": {
"dvUrl": "/vdb-builder/v1/",
"enabled": 0
}
```
- syndesis-server-config
```
knative:
enabled: false
integrationLivenessProbeInitialDelaySeconds: 120
```
Not sure about idem potency for these scripts. At the moment the script will just overwrite existing values with these defaults.
> Fixes #6069 Add ui and server config map migration from 1.6.x to 1.7.x

- doc/integrating-applications/topics/c_guidelines-for-openapi-documents.adoc
- doc/integrating-applications/topics/p_creating-api-connectors.adoc
- doc/integrating-applications/topics/r_refreshing-access-tokens.adoc
Makes it clear that you cannot change an api client connector after Syndesis creates it.
> user doc: Updates to doc for API key security based on QA review

- app/server/jsondb/src/main/java/io/syndesis/server/jsondb/NativeJsonDB.java
- app/server/jsondb/src/main/java/io/syndesis/server/jsondb/impl/MemorySqlJsonDB.java
- app/server/jsondb/src/main/java/io/syndesis/server/jsondb/impl/SqlJsonDB.java
- app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java
- app/server/runtime/src/main/resources/migrations/up-31.js
- app/server/runtime/src/test/java/io/syndesis/server/runtime/migrations/UpgradeVersion31Test.java
Tries to improve performance of activity tracking persistence by:
- adding a ordered index on the JSONDB table, in order to help with
purging of old activity tracking entries during which we order the
rows by the PATH column
- explicitly trying to avoid locking when fetching the rows that need
to be deleted from the database by adding `FOR KEY SHARE SKIP LOCKED`
to the SELECT statement that's fetching the rows to be deleted
I'm mainly concerned about the change of `NOT IN` to `IN`, the subselect in the `NOT IN` variant will return 50 rows which will be checked against a the rows matching the `LIKE`, so we have a intersection of 50 against N; the changed version has an intersection of N-50 against N, but it doesn't have a `WHERE path LIKE ?` bit so the starting query could be N against N …
> fix(server): activity logging performance improvements

- app/ui-react/syndesis/src/modules/integrations/components/editor/template/useTemplater.tsx
* Bad request caused by no JSON.stringify when symbols length is 0
* Symbols length is being left as 0 since linter is not being changed back
due to language not being immediately updated during the function
handleTemplateTypeChange
* By adding a useEffect dependent on language, the linter is correctly
updated once language has been changed.
> fix(5955): Error after change of template step language type

- install/operator/pkg/generator/assets/install/04-syndesis-db.yml.mustache
We have two copies of this file now, and this PR is trying to manually resolve the differences.
fixes regressions: #5690 and #6014
> fix: DB procedure name changed to text input instead of dropdown #5690

- app/ui-angular/docker/Dockerfile
- app/ui-angular/docker/nginx-syndesis.conf
- app/ui-angular/docker/nginx.repo
- app/ui-angular/pom.xml
- app/ui-react/docker/Dockerfile
- app/ui-react/docker/nginx-syndesis.conf
- app/ui-react/docker/nginx.repo
- app/ui-react/pom.xml
- install/generator/03-syndesis-ui.yml.mustache
- install/generator/syndesis-template.go
- install/syndesis.yml
**HEADS UP** @syndesisio/ui-api @cunningt @djcoleman @orpiske
Switches the use of the Syndesis UI Docker base image from CentOS and Nginx installed from nginx.org RPM repository to SCLs Nginx[1].
Since SCLs Nginx is a S2I builder image the Dockerfile was modified to copy the distribution files and configuration to `/tmp/src` and run `assemble` as an S2I build would do.
`docker.base-image` Maven property can be used to change to a different SCLs Nginx base image (say `rhscl/nginx-114-rhel7` for RHEL 7 based base image).
[1] https://github.com/sclorg/nginx-container/blob/master/1.14/README.md
>  chore: use SCLs Nginx base image 

- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/PropertyGenerators.java
- app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/PropertyGeneratorsTest.java
Makes sure to return `No Security` when no supported security definitions are found.
Fixes #6123
> fix(server): handle unsupported security definitions

- app/ui-react/syndesis/src/setupProxy.js
- doc/sdh/development/local.adoc
Adds the additional header set by oauth-proxy required by the server when proxying via middleware. Updates the documentation on how to run the React UI against the locally started server.
> chore: update UI setup against local Syndesis

- app/ui-react/packages/api/src/useIntegrationHelpers.tsx
> fix: merge the previous step to the new one when updating a connection

- app/common/model/src/main/java/io/syndesis/common/model/integration/Step.java
- app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
- app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/AggregateStepHandler.java
- app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/SplitStepHandler.java
- app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/AggregateStepHandlerTest.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandler.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandler.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHelper.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandlerTest.java
- app/server/endpoint/src/test/resources/io/syndesis/server/endpoint/v1/handler/meta/person-list-unified-response-schema.json
- app/server/endpoint/src/test/resources/io/syndesis/server/endpoint/v1/handler/meta/person-unified-response-schema.json
Relates to #6118 
Dynamic data shape adaption for aggregate step now supports unified json body shapes where in this special case the collection of the unified body element is adapted to single elements.
In addition to that added an aggregation post processor that is added for unified json body shapes. The post processor is added after the aggregation and takes care on aggregating the unified json body elements to a single unified body collection.
```json
[
{"body": {"id":1,"name":"a"}},
{"body": {"id":2,"name":"b"}},
{"body": {"id":3,"name":"c"}},
]
```
```json
{
"body": [
{"id":1,"name":"a"},
{"id":2,"name":"b"},
{"id":3,"name":"c"},
]
}
```
> fix: Support unified json bodies with aggregate steps

- app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlConnectorMetaDataExtension.java
- app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlMetadataRetrieval.java
- app/connector/sql/src/main/java/io/syndesis/connector/sql/common/SqlStatementMetaData.java
- app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlConnectorCustomizer.java
- app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
- app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlMetadataAdapterTest.java
- app/connector/sql/src/test/resources/sql/name_sql_batch_update_metadata.json
... as it breaks existing data mappings in integrations
Introduced new configuration property `batch` (which is `false` by default) so existing integrations keep working with existing data mappings as the data shape is then still using single element parameters like before.
The user needs to enable the batch update support and then is provided with a collection of SQL input parameters as data shape.
Related to #6118
> fix: Do not use SQL batch update mode by default

- app/ui-react/packages/api/src/useIntegrationHelpers.tsx
Fixes a bug introduced with #6138
Part of #6118
> fix: when updating a connection, check if the previous step exist and has a valid id, else create a new one

- app/ui-react/packages/api/src/useApiResource.tsx
- app/ui-react/packages/ui/src/Shared/InlineTextEdit.tsx
Also, `useApiResource` re-fetches data when its default value or initial value changes
Fixes #6147
> fix: InlineTextEdit shows the controlled value in read mode

- app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
> fix: use band-aid to discard old action definition when a new connection is set  

- app/common/model/src/main/java/io/syndesis/common/model/integration/step/template/AbstractTemplatePreProcessor.java
- app/common/model/src/main/java/io/syndesis/common/model/integration/step/template/FreeMarkerTemplatePreProcessor.java
- app/common/model/src/main/java/io/syndesis/common/model/integration/step/template/MustacheTemplatePreProcessor.java
- app/common/model/src/main/java/io/syndesis/common/model/integration/step/template/VelocityTemplatePreProcessor.java
- app/common/model/src/test/java/io/syndesis/common/model/integration/step/template/TestFreeMarkerTemplatePreProcessor.java
- app/common/model/src/test/java/io/syndesis/common/model/integration/step/template/TestMustacheTemplatePreProcessor.java
- app/common/model/src/test/java/io/syndesis/common/model/integration/step/template/TestVelocityTemplatePreProcessor.java
- app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/AbstractTemplateStepHandlerTest.java
- app/integration/runtime/src/test/java/io/syndesis/integration/runtime/template/FreeMarkerTemplateStepHandlerTest.java
- app/integration/runtime/src/test/java/io/syndesis/integration/runtime/template/MustacheTemplateStepHandlerTest.java
- app/integration/runtime/src/test/java/io/syndesis/integration/runtime/template/velocity/AbstractVelocityTemplateStepHandlerTest.java
- app/integration/runtime/src/test/java/io/syndesis/integration/runtime/template/velocity/VelocityFormalSyntaxTest.java
* Better handles parsing the template syntax prior to passing it to the
camel-template components.
* Specifically:
* Identifies the named parts of a literal so the opening & closing tags,
symbol identifier and any leading text
* Allows for text to enclose the symbol, eg. brackets
* More tests trying out different syntax variations and mistakes
> fix(6149): Improve the robustness of template step pre-processor

- app/ui-react/packages/models/src/dv.d.ts
- app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.css
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewEditContent.tsx
- app/ui-react/packages/ui/stories/Data/Views/ViewEditContent.stories.tsx
- app/ui-react/syndesis/src/modules/data/pages/ViewEditPage.tsx
- Adds sourceTableInfos property to ViewEditContent component.  This allows user to supply the SQL source table/column info to the editor
- ViewEditPage supplies the source table/column info to the ViewEditContent component - there is a TODO to complete this once a service is available
- DvConnectionCard.css - added style changes so that the selected DV card accent is around the whole card.  (TEIIDTOOLS-677)
> TTOOLS-688 Enable tables for SQL auto complete

- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandler.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandlerTest.java
… when doing a step shape meta lookup
So this PR fixes the auto data shape adaption for split/aggregate and other steps. In particular a data shape change needs to propagate to the complete list of subsequent steps. For instance when the data shape of the 1st step changes this should also propagate to the steps 3 or 4 in line if required.
In detail the step adaption needs to reuse the enriched shapes for further propagation when walking through the set of steps. Before the fix it always used the old shapes as base for adaption.
Fixes #5215
> fix: propagate data shape changes to all subsequent steps

- app/test/pom.xml
Fixes #6173 
Skipping maven install and deploy executions for test module that only has test sources and no artifacts. This prevents the build to fail because no artifact has been attached in this module.
> fix: No artifact attached build error for test module

- install/operator/cmd/syndesis-operator/main.go
- install/operator/pkg/syndesis/configuration/configuration.go
- install/operator/pkg/syndesis/template/install.go
Use a different file for upstream installation, dont mess around the template installation file
Add a option to target a new github user, for testing purposes mainly, default to _syndesisio_
Fixes https://github.com/syndesisio/syndesis/issues/5925
> Dont use the same file that is used by template install

- app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionSkeleton.tsx
- app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionsToolbarSkeleton.tsx
- app/ui-react/packages/ui/src/Data/DvConnection/index.ts
- app/ui-react/packages/ui/src/Data/index.ts
- app/ui-react/packages/ui/stories/Data/DvConnection/DvConnectionsWithToolbarSkeleton.stories.tsx
- app/ui-react/syndesis/src/modules/data/shared/DvConnections.tsx
- app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
- see [TEIIDTOOLS-683](https://issues.jboss.org/browse/TEIIDTOOLS-683)
- added `DvConnectionsToolbarSkeleton` to the loader children that are displayed when the DV connections are being fetched
- moved the loader from `DvConnections` to `DvConnectionsWithToolbar`
- added story for the combined loader skeleton used by `DvConnectionsWithToolbar`
- redesigned `DvConnectionSkeleton` to look more like the DV connection card
> Fix for TEIIDTOOLS-683 Initialization of the Import Datasource wizard flashes "No connections available"

- install/generator/03-syndesis-ui.yml.mustache
- install/generator/04-syndesis-meta.yml.mustache
- install/generator/04-syndesis-oauth-proxy.yml.mustache
- install/generator/04-syndesis-server.yml.mustache
- install/generator/07-syndesis-upgrade.yml.mustache
- install/generator/syndesis-template.go
- install/operator/build/conf/template-config.yaml
- install/operator/pkg/generator/assets/install/03-syndesis-ui.yml.mustache
- install/operator/pkg/generator/assets/install/04-syndesis-meta.yml.mustache
- install/operator/pkg/generator/assets/install/04-syndesis-oauth-proxy.yml.mustache
- install/operator/pkg/generator/assets/install/04-syndesis-server.yml.mustache
- install/operator/pkg/generator/assets/upgrade/07-syndesis-upgrade.yml.mustache
- install/operator/pkg/generator/generator.go
Sending this as a proposed fix for https://issues.jboss.org/browse/ENTESB-11030. 
Doing it on the template generator is, IMHO, easier to maintain than implementing a bunch of regex on the productization scripts.
> Changes the pod names in the templates to match the actual container names

- app/connector/ftp/pom.xml
- app/connector/ftp/src/main/java/io/syndesis/connector/ftp/FtpVerifierExtension.java
- app/connector/support/util/src/main/java/io/syndesis/connector/support/util/ConnectorOptions.java
* ConnectorOptions
* Provides function for returning a default value rather than null if
property in options map is not present or if it is empty
* FtpVerifierExtension
* Uses the ConnectorOptions to extract options and ensure they are either
null or empty as required.
> fix(6141): FTP Verifier handles empty username & password properties

- app/ui-react/packages/api/src/usePolling.tsx
- app/ui-react/packages/api/src/useVirtualization.tsx
- app/ui-react/packages/api/src/useVirtualizations.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
- renamed `usePolling` function properties to be `delay` and `callback`
- changed `useVirtualization` and `useVirtualizations` to the new property names of `usePolling`
- removed unnecessary React effect in `VirtualizationsPage`
> Rewrite of polling function

- tools/upgrade/steps/upgrade_40_update_resources
@nicolaferraro the problem is that the migration script never worked (my bad at 7.3 times), because first the migration scripts are executed and then the SA are re-created, effectively reverting the change back:
```
=== * Update resources (upgrade_40_update_resources)
<migration scripts>
- Executing 01_server_config_map_upgrade.sh
configmap/syndesis-server-config patched
- Executing 02_ui_config_map_upgrade.sh
configmap/syndesis-ui-config patched
- Executing 03_server_config_map_upgrade.sh
configmap/syndesis-server-config patched
- BuildConfig: update (replace)
* todo
- ConfigMap: skipped
- DeploymentConfig: update (replace)
* broker-amq
* komodo-server
not existing --> trying to create
deploymentconfig.apps.openshift.io/komodo-server created
* syndesis-db
* syndesis-meta
* …
```
> [Upgrade] Link the secret back to SAs after re-creation

- .circleci/config.yml
PR adds a nightly job to run the integration tests.
For now run the tests every hour to see if that is working.
> chore: Add CircleCi job for integration tests

- app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftConfigurationProperties.java
- app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
This seems to be an issue when using flaky networks or Maven repositories with issues. At least this way the integrationbuild will fail instead of the integration failing at runtime.
> chore: enable strict checksums for integration builds

- app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
- app/ui-react/packages/ui/src/index.css
- app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/WithRuleFilterForm.css
- app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/WithRuleFilterForm.tsx
fixes https://github.com/syndesisio/syndesis/issues/6222
@gashcrumb this is as close as I could get while working with the existing markup. I couldn't figure out the auto form components to be able to modify the markup to make this layout easier/better. I'm also not sure where to inject the paragraph of description text that goes above the form fields.
In a perfect world, each of the `<fieldset>` elements would have a nested `<div>` that wraps the form groups so that I could give that a `grid` layout to place the the form groups inside of it.
A more flexible route would be to then wrap the 3 form group elements that create the condition in a `<div>`, then wrap the action/array controls in another element, that would allow me to use `flex` layout, which works in IE (since `grid` does not). …
> fix(basicfilter): rework condition set form UI

- app/ui-react/packages/api/src/useViewEditorStates.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
Adapting to backend service change.  Editor states service now accepts a virtualizationId, rather than a name pattern.
> TTOOLS-715 Adapt to backend changes

- .circleci/config.yml
PR uses parallel jobs for connectors on CircleCi. 
- connector-support modules are built first in sequential order
- all connectors are built in parallel to each other
- connector-support-catalog is built at the very end to collect all connectors
- nightly job still uses "old" way of running all connectors with single job
Relates to #5797
> chore: Update CircleCi config to use parallel connector jobs

- app/ui-react/packages/ui/package.json
- app/ui-react/packages/ui/src/Connection/ConnectionCard.css
- app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx
- app/ui-react/packages/ui/src/Connection/ConnectionsGrid.tsx
- app/ui-react/packages/ui/src/Connection/ConnectionsGridCell.tsx
- app/ui-react/packages/ui/src/Dashboard/ConnectionsMetric.tsx
- app/ui-react/packages/ui/src/Dashboard/Dashboard.css
- app/ui-react/packages/ui/src/Dashboard/Dashboard.tsx
- app/ui-react/packages/ui/src/Dashboard/IntegrationBoard.tsx
- app/ui-react/packages/ui/src/Dashboard/RecentUpdatesCard.tsx
- app/ui-react/packages/ui/src/Dashboard/TopIntegrations.css
- app/ui-react/packages/ui/src/Dashboard/TopIntegrationsCard.tsx
- app/ui-react/packages/ui/src/Dashboard/UptimeMetric.tsx
- app/ui-react/packages/ui/src/Shared/AggregatedMetricCard.tsx
- app/ui-react/packages/ui/src/index.css
- app/ui-react/syndesis/src/app/App.css
- app/ui-react/syndesis/src/app/App.tsx
- app/ui-react/syndesis/src/index.css
- app/ui-react/syndesis/src/index.tsx
- app/ui-react/syndesis/src/modules/connections/components/Connections.tsx
- app/ui-react/yarn.lock
This PR upgrades several Card views from PF3 to PF4. I also swapped out any usages of PF3 Card Grid while I was in there. There's a little bit of fine-tuning to do regarding spacing in the main dashboard layout but wanted to go ahead and raise this PR so we can start getting any feedback people may have.
It's an incremental step toward https://github.com/syndesisio/syndesis/issues/6240
Addresses card views in the following components.
- ConnectionCard
- ConnectionsGrid
- ConnectionsGridCell
- ConnectionsMetric
- Dashboard
- IntegrationBoard
- RecentUpdatesCard
- TopIntegrationsCard
- UptimeMetric
- AggregatedMetricCard
> chore(cards): replace dashboard/connection pf3 cards/layout with pf4

- .circleci/config.yml
Seems that the individual connector jobs fail on CI because of missing connector-parent artifact in the local Maven repository. This adds it to the list of modules being build in the connector-support job that precedes the individual connector jobs.
> fix: add connector-parent module to connector-support job

- app/pom.xml
https://github.com/syndesisio/syndesis/issues/6292
Excluding org.json:json from openshift-client.    I believe the reason that I'm seeing this in the dev build and it's not seen in syndesis ci is that we're building and aligning to a newer version of kubernetes-client (which produces io.fabric:openshift-client)
> Fix #6292 : exclude org.json:json from openshift-client

- tools/bin/commands/minishift
- tools/bin/commands/util/openshift_funcs
This configures Syndesis custom resource option `devImages` to `true`, to configure that the images for meta, server and ui are not pulled from Docker Hub but from the internal OpenShift registry.
When running `syndesis minishift --install` or `syndesis install --dev` this will result in no meta, server or ui pods being deployed as they first need to be built.
This is a start, perhaps a good follow up would be to import images from the Docker Hub initially, not sure where would that code be, seems natural that it would be in the operator.
> chore(tool): configure devImages: true

- tools/bin/commands/minishift
Often the easiest way for QE to deploy latest syndesis is with `syndesis minishift --install`. With the recent addition of the `devImages` flag (#6348 ), it would now also mean we'd have to build the images ourselves. 
Adding a `--nodev` flag to `syndesis minishift` that will restore the original behaviour.
> [chore] Add --nodev flag to syndesis minishift --install

- app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContentSkeleton.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/index.ts
- app/ui-react/packages/ui/stories/Data/Virtualizations/SqlClientContentSkeleton.stories.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
- removed the not needed `useVirtualization` call as the virtualization is available from the route state
- added a loader for when the SQL tab is loading
- created SqlClientContentSkeleton and story
> Fixes view header display issue when navigating back and forth from view output tab to SQL tab

- install/operator/pkg/generator/assets/addons/ops/addon-ops-integrations-home-dashboard.yml
Fixed "Top 5 by messages errors" panel in the Integration-home grafana dashboard.
fix #6327
> fix(monitoring): "Top 5 by messages errors" panel doesn't show data

- app/ui-react/packages/api/src/useViewDefinition.tsx
- app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
- app/ui-react/packages/models/src/dv.d.ts
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Adapting UI to further changes in teiid server interface
- removes need to explicitly refresh ViewDefinitions.  The views are refreshed upon save or import.  This removes the 'deleteView' and 'refreshVirtualizationViews' functions from useVirtualizationHelpers. 'updateViewDefinitions' was also renamed to 'saveViewDefinition'
- pages were modified to utilize the updated functions
- projectedColumns and compositions were removed from the ViewDefinition model.  compositions were not utilized and projectedColumns only minimally.  Design of projectedColumns for future release will be coordinated with teiid team.
> TEIIDTOOLS-726 Adapt to teiid backend changes

- app/ui-react/syndesis/src/modules/integrations/components/editor/template/TemplateStepPage.tsx
* Such an accept is problematic as there is no guarantee that files even
have a file-type property despite being 'text'. Thus, false-positives
are being generated resulting in legitimate files being rejected.
* Removal restores functionality of allowing files to be uploaded and
handled by the editor.
> fix(6316): Removes acceptance criteria on template editor file upload

- install/operator/go.mod
Needed in order to use `--local-operator-flags` when running [e2e](https://github.com/operator-framework/operator-sdk/blob/master/doc/sdk-cli-reference.md#test) test. The mentioned flag was introduced in v.0.9.0
> bump operator-sdk to v0.10.0

- app/ui-react/packages/utils/src/autoformHelpers.ts
For controls that need additional properties that ConfigurationProperty doesn't provide for in it's interface.
@KurtStam FYI
> feat: expand any extended properties into the property definition

- app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContentSkeleton.tsx
- app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationRelationshipPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
- removed `useVirtualization` API call from tab pages since the virtualization is available from the route state
- added a push notification if there was an error saving the description
- inline edit component now displays the new description while saving is in progress
- required changes be made in the 4 virtualization tab pages
- added `key` attributes to map results in `SqlClienContentSkeleton`
> Fix(TEIIDTOOLS-699) Fixes issues with inline edit of Virtualization descriptions

- app/ui-react/packages/models/src/dv.d.ts
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.tsx
- app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaList.stories.tsx
- app/ui-react/packages/ui/stories/Data/Views/SchemaNodeListItem.stories.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
- app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Adapt to change in source specification for viewDefinitions
- 'path' was removed from SchemaNode model and 'teiidName' added
- modified the SchemaNodeInfos generated in UI to account for changes
- removed functions no longer needed from VirtualizationUtils (there will be further simplifications after the next teiid PR)
- updated stories
> TEIIDTOOLS-726 adapt to change in teiid source path specification

- install/operator/.lib.sh
The docker-based build would fail when run on fresh clones of sydesis repo because the `dist` directory [did not exist](https://ci.fabric8.io/view/release%20builds/job/asmigala-syndesis-release-daily-dry-run/3/console).
> fix(build): Make operator docker build work on fresh clone

- app/connector/flow/src/main/resources/META-INF/syndesis/connector/flow.json
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/ChoiceMetadataHandler.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandler.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHelper.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/ChoiceMetadataHandlerTest.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandlerTest.java
- app/ui-react/packages/api/src/helpers/integrationFunctions.ts
When an integration uses conditional flows step the warning "Configuration Required" always showed up after save. This was because data shapes in connection descriptors were automatically adjusted for each subflow.
For some reason (I still do not understand the javascript magic) the data shape was adjusted not only in `flow->step->action->descriptor->datashape` but also in `flow->step->action->connection->descriptor->datashape`. The latter connection descriptor data shape should never be changed by a data shape auto adapt. This difference of the connection configuration caused the "Configuration Required" warning to always show up.
The data shape adjustment on the connector descriptor took place in https://github.com/syndesisio/syndesis/blob/master/app/ui-react/packages/api/src/helpers/int …
> fix: [6068] Configuration required warnings for conditional flows steps

- app/ui-react/packages/api/src/constants.ts
- app/ui-react/packages/api/src/useIntegrationHelpers.tsx
- app/ui-react/packages/auto-form/src/widgets/FormMapsetComponent.tsx
- app/ui-react/packages/models/src/extra.d.ts
- app/ui-react/packages/utils/src/autoformHelpers.ts
- app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
- app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
for #4259
Rough old screenshot, also still compatible with the old api provider end action definition kinda a little bit:
> feat: extract standardized errors from the flow and supply it to the error mapping form

- app/s2i/copy_mvn_repo.sh
sed option -i is different between linux and mac. Removing that in favour of file forward
fixes #6384
> fix(s2i): copy maven repo regression

- app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
related to PR #6415, meant to include this change in there and apparently neglected to actually push it to that branch.
> fix: ensure api provider return page can still work with the old form definition

- app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.css
- app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
- app/ui-react/packages/auto-form/src/widgets/FormHiddenComponent.tsx
- app/ui-react/packages/auto-form/src/widgets/FormLegendComponent.css
- app/ui-react/packages/auto-form/src/widgets/FormLegendComponent.tsx
- app/ui-react/packages/auto-form/stories/FormWrapper.tsx
- app/ui-react/packages/auto-form/stories/SyndesisUIs.stories.tsx
- app/ui-react/packages/ui/src/Integration/Editor/choice/ChoiceConfigurationView.tsx
- app/ui-react/packages/ui/src/Integration/Editor/choice/ChoicePageCard.css
- app/ui-react/packages/ui/src/Integration/Editor/choice/ChoicePageCard.tsx
- app/ui-react/packages/ui/src/Integration/Editor/choice/index.ts
- app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/choice/WithChoiceConfigurationForm.tsx
- app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
related to #6093 
Form now looks like:
very loosely based on [this design](https://marvelapp.com/7ai4d53/screen/60537627)
When you don't check the "use default flow box":
And when you do:
Also updates the storybook to use the same layout/css etc.
@mcoker kinda fought with the horizontal form grid layout there a bit, dunno if you might want to have a look.
> feat: various conditional flow improvements based on user feedback

- app/ui-react/packages/api/src/constants.ts
- app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.ts
- app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
for #6093
Was on my list for the last PR and totally forgot to do it.  This PR makes this happen for these two connections in the editor:
and
@christophd FYI
> fix: hide the configure buttons for the flow start/end connections

- app/common/model/src/main/java/io/syndesis/common/model/choice/FlowOption.java
- app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/ChoiceStepHandler.java
- app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/ChoiceStepHandlerTest.java
- app/ui-react/packages/api/src/helpers/integrationFunctions.ts
- app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepExpanderBody.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/choice/WithChoiceConfigurationForm.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/choice/interfaces.ts
- app/ui-react/syndesis/src/modules/integrations/components/editor/choice/utils.ts
- app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/RuleFilterStepPage.tsx
- app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Relates to #6094 
Adds rule based form controls to condition expressions in conditional flows step. At the moment just adds the controls next to the advanced expression input field. The user can either provide an advanced expression or use the rule based form components to build the condition expression.
We will need to add some advanced form validation so that user needs to fill in either advanced or rule based form controls.
Backend has already been prepared to handle both advanced and rule based configuration so conditions are evaluated correctly at runtime.
> feat [6094]: Add basic condition expression builder to conditional flows step

- doc/integrating-applications/topics/p_using-data-mapper-to-process-collections.adoc
This restriction came up in a Fuse Online Evaluation email. It was not documented.
So now it is. Gary approved the wording and the update.
> user doc: Add restriction that you cannot map from/to a nested collection

- install/operator/pkg/syndesis/action/checkupdates.go
- install/operator/pkg/syndesis/action/initialize.go
- install/operator/pkg/syndesis/action/install.go
- install/operator/pkg/syndesis/action/upgrade.go
- install/operator/pkg/syndesis/template/install.go
- install/operator/tests/e2e/install_with_defaults_test.go
This PR partially reverts https://github.com/syndesisio/syndesis/pull/6491
- It is still possible to define the operator image tag by using `--tag tagValue`, but this will only set the tag for the operator, as well as the tag name.
- The default value for images comes from file. What this value should be, is yet to be defined.
- e2e test are working again
> Get default value for syndesis components from conf file

- app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Adapt to minor change in teiid backend - UI should not supply an id for the view definition, if it has not yet been defined.
> TEIIDTOOLS-762 Adapt UI for view definition

- app/ui-react/packages/auto-form/package.json
- app/ui-react/packages/ui/package.json
- app/ui-react/packages/ui/src/Shared/PfDropdownItem.tsx
- app/ui-react/syndesis/package.json
- app/ui-react/syndesis/src/modules/integrations/components/IntegrationExposeVia.tsx
- app/ui-react/yarn.lock
This PR
- upgrades the main @patternfly/react-core dependency in `ui` and `auto-form`
- removes @patternfly/react-core as a dependency on `syndesis` (replacing its usage with raw pf4 markup)
- introduces @patternfly/react-table as a dependency
- ensures the test suite can run with these dependencies in place
- registers new glob pattern for jest nohoist config
After making the upgrades, the test suite failed to run with errors similar to those noted in https://github.com/syndesisio/syndesis/issues/6485 - adding the new glob pattern seems to have fixed it. @elvisisking can you give it a spin when you have time and let me know if it fixes it for you?
> Upgrade UI dependencies

- app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorLayout.css
- app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorLayout.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
Fixes #5673 
Hide `Cancel`, `Save` and `Publish` buttons when working on a conditional flows alternate flow and display `Back to Primary Flow` button instead. Also display current condition expression as page heading. Also works within API provider integrations.
> fix [5673]: Add back to primary flow button

- app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
- app/ui-react/packages/models/src/dv.d.ts
- app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.css
- app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.tsx
- app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor.stories.tsx
- app/ui-react/packages/ui/stories/Data/ViewEditor/ExpandablePreview.stories.tsx
- app/ui-react/syndesis/src/modules/data/index.tsx
- app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorOutputPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
- app/ui-react/syndesis/src/modules/data/resolvers.ts
- app/ui-react/syndesis/src/modules/data/routes.ts
Reorganization of the ViewEditor per feedback from F2F.
- Removed the ViewEditorNavBar (tabs) from ViewEditorSqlPage.  The current view editor will be a single page with DDL text editor.
- Removed ViewEditorNavBar from the ViewEditorOutputPage.  The page remains, but removed the route and resolver so the output page cannot be accessed - it will most likely be reinstated in some form.
- Removed capability to toggle between SQL and queryResults from the ExpandablePreview component.  It is no longer needed with a single page editor
- Rework DdlEditor - there are no longer separate Validate/Save buttons.  The user can save the view in any state (not required to be valid).  Validation is still done as part of the save process, and an error message is shown if the DDL is invalid.  The query …
> TEIIDTOOLS-761 Reorganize the ViewEditor

- .circleci/config.yml
The idea here is that the stored artifacts can be downloaded and then
imported into quay.io
Ref #6306
> chore(ci): store docker images as artifacts

- .circleci/config.yml
Adds the invocation of the webhook that triggers the invocation of image
artifacts to quay.io.
Fixes #6306
> chore(ci): triggers image transfer to quay.io

- app/ui-react/packages/api/src/helpers/integrationFunctions.ts
Alternate flows that are linked to conditional flow steps are updated with the new data shapes for flow start and flow end.
Fixes ENTESB-11398
> fix(ENTESB-11398): propagate datashape changes to alternate flows

- .circleci/config.yml
Builds were failing on master because of CIRCLE_PR_NUMBER env check. Just trigger quay image transfer on non-master branches
Belongs to #6578
> fix(ci): fix trigger image transfer on master branch

- .circleci/config.yml
- app/test/integration-test/pom.xml
- app/test/integration-test/src/test/java/io/syndesis/test/itest/ftp/WebHookToFtp_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/quickstart/Webhook2DB_IT.java
- app/test/pom.xml
- app/test/test-support/pom.xml
- app/test/test-support/src/main/java/io/syndesis/test/SyndesisTestEnvironment.java
- app/test/test-support/src/main/java/io/syndesis/test/container/dockerfile/SyndesisDockerfileBuilder.java
- app/test/test-support/src/main/java/io/syndesis/test/container/integration/SyndesisIntegrationRuntimeContainer.java
- app/test/test-support/src/main/java/io/syndesis/test/container/s2i/SyndesisS2iAssemblyContainer.java
- app/test/test-support/src/main/java/io/syndesis/test/integration/project/AbstractMavenProjectBuilder.java
- app/test/test-support/src/main/java/io/syndesis/test/integration/source/IntegrationExportSource.java
- tools/bin/commands/integration-test
PR fixes integration test execution on CircleCi
The issues were related to copying/mounting files (the Syndesis integration project) to the S2i image. The file permissions got messed up as the container is run with another user that is not the owner of the files copied/mounted.
For some reason this is not an issue on MacOS with Docker for desktop but it was on CircleCi. That made error analysis a bit more complicated.
I solved the issue with taking care of file permissions as recommended by S2i best practices.
> fix(ci): nightly CircleCi integration test execution

- app/ui-react/packages/api/src/useVirtualizationConnectionStatuses.tsx
- app/ui-react/packages/models/src/dv.d.ts
- app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx
- app/ui-react/packages/ui/stories/Data/DvConnection/DvConnectionCard.stories.tsx
- app/ui-react/syndesis/src/modules/data/shared/DvConnections.tsx
- app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Resolve issue with connection refresh in the import datasource wizard
- adapt VirtualizationSourceStatus model to backend changes.  The schemaStates were clarified and new loading attribute was added.
- VirtualizationUtils functions were corrected for the updated model and functions simplified
- useVirtualizationConnectionStatuses now includes a polling option, so that pages can update periodically.
- added loading spinner to the DvConnectionCard to show when connection load is in progress
- added story for the DvConnectionCard
> ENTESB-11251 Resolve connection refresh issue in import datasource wizard

- install/operator/pkg/cmd/internal/eject/eject.go
- install/operator/vendor/modules.txt
This enables the eject mode to correctly read a named syndesis custom resource.
How to use:
```
[lgarciaa@lgarciaa operator]$ oc get syndesis
NAME      PHASE      VERSION
app       Starting   latest
[lgarciaa@lgarciaa operator] ./dist/linux-amd64/operator eject --app app --operator-config build/conf/config.yaml
[lgarciaa@lgarciaa operator]
```
Mandatory parameters such as `syndesis.Spec.RouteHostname`, should be specified in the CR
> operator eject reads from CR

- app/connector/aws-ddb/pom.xml
- app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/customizer/DDBConnectorCustomizer.java
- app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/customizer/DDBConnectorCustomizerQuery.java
- app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBConnectorMetaDataExtension.java
- app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataRetrieval.java
- app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/util/Util.java
- app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/aws-ddb.json
- app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/meta/aws-ddb
- app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBConfiguration.java
- app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBGenericOperation.java
Extend the DynamoDB connector to have metadata included. Now you can map properties to query and put items on DDB.
#6298
> [ENTESB-11495] [AWS-DDB] Adding schema for input and output data

- app/ui-react/packages/ui/src/Connection/ConnectionDetailsForm.tsx
- app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
- app/ui-react/packages/ui/src/Customization/extensions/ExtensionDetail.tsx
- app/ui-react/packages/ui/src/Customization/extensions/ExtensionImportCard.tsx
- app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.css
- app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
- app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx
This PR upgrades another batch of PF3 cards as part of the work in https://github.com/syndesisio/syndesis/issues/6240
Upgrades Card view in the following components
- StoryWrapper
- ConnectionDetailsForm
- OpenApiSelectMethod
- IntegrationDetailMetrics
- ExtensionImportCard
- ExtensionDetail
- ApiClientConnectorCreateSecurity
There are still a couple of places that are still using PF3 CardGrid for layout (below), can replace those with PF4 layouts in a follow-up PR as it's not technically required until milestone 5 of the integration product suite PF4 adoption strategy.. and I'm out of time for today :) 
- DvConnectionsGridCell
- DvConnectionsGrid
> chore(cards): upgrade more cards to pf4

- app/common/jaeger-spring-boot-starter/src/main/java/io/syndesis/common/jaeger/JaegerConfiguration.java
- app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/application.properties.mustache
- app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/application-tracing.properties
Fix #6507
Randomly the tracer was being instantiated too late. I've used a high priority order instead of referencing a specific configuration class because the Jaeger starter has changed a lot recently. Priority is sufficient to instantiate the tracer before spring-web.
There was also a typo in the generator project.
> Fix #6507: fix jaeger configuration

- .circleci/config.yml
- tools/bin/commands/build
it went away when we switched to go modules.
> chore: remove the dead `syndesis build --ensure` option.

- app/ui-react/packages/atlasmap-assembly/src/app/app.module.ts
- app/ui-react/syndesis/scripts/minishift-restore.sh
- app/ui-react/syndesis/scripts/minishift-setup.sh
Since Atlasmap doesn't use the routing, we can avoid enabling it. This
gets rid of the warning we were having about the router not being happy
about being initialized in an iframe without an src attribute.
Also, fixes the minishift setup/restore script to work with the
operator. Since the operator reverts back any local change to operator's
managed resources, we have to scale it down to 0 when running the setup
script. The restore script brings the operator back to 1 replica.
Related to ENTESB-11628
> fix(atlasmap-assembly): remove routing related console warning

- install/operator/go.mod
- install/operator/go.sum
- install/operator/pkg/util/create_or_update.go
- install/operator/pkg/util/debug.go
Sometimes the operator can get into an update loop updating the same resource over and over, that’s not good.  Knowing what is being updated on the resources can help in fixing these types of issues.
> chore: Improve operator debug output by showing the update diff on the resources.

- app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
- app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
- app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
- See [TEIIDTOOLS-771](https://issues.jboss.org/projects/TEIIDTOOLS/issues/TEIIDTOOLS-771)
- The `Save` button in DDL Editor is now only enabled when the DDL has changed from the last successful save.
- The `Done` button in DDL Editor now disables during a save.
- A confirmation dialog is displayed when DDL changes exist in the editor and the user wants to navigate to a different page.
> fix(TEIIDTOOLS-771) - View Editor - prompt user for pending changes if navigating away

- tools/bin/commands/release
We no longer need to generate the templates during the release, the templates have been removed in favor of the operator.
> fix(build): remove template generation

- app/connector/aws-ddb/pom.xml
- app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataRetrieval.java
- app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataAdapterTest.java
Following #6593 now the mapping works fine in all the fields.
> [ENTESB-11495] Mapping variables also on options, not only from the body

- app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.css
- app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.tsx
- app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor-styling.css
- app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor.stories.tsx
- See [TEIIDTOOLS-769](https://issues.jboss.org/browse/TEIIDTOOLS-769)
- added styling such that the DDL editor expands to take up available space when the preview area is collapsed
- fixed a bug that DDL editor dirty flag wasn't getting set to `false` after a successful save
- changes to DdlEditor story to get editor to show and to add in missing `setDirty` property
> fix(TEIIDTOOLS-769) - View Editor sizing issues

- app/connector/aws-ddb/pom.xml
- app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataRetrieval.java
- app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataAdapterTest.java
> Port from #6619

- app/test/pom.xml
Currently the 1.8.0 release fails because of:
```
[ERROR] Repository "iosyndesis-1268" failures
[ERROR]   Rule "sources-staging" failures
[ERROR]     * Missing: no main jar artifact found in folder '/io/syndesis/test/integration-test/1.8.0'
[ERROR]     * Missing: no main jar artifact found in folder '/io/syndesis/test/system-test/1.8.0'
[ERROR]   Rule "javadoc-staging" failures
[ERROR]     * Missing: no main jar artifact found in folder '/io/syndesis/test/integration-test/1.8.0'
[ERROR]     * Missing: no main jar artifact found in folder '/io/syndesis/test/system-test/1.8.0'
```
This disables staging to OSS Maven repository of any artifacts from the
test modules.
> fix(build): prevent staging of test modules

- app/ui-react/packages/ui/src/Connection/ConnectionSkeleton.tsx
- app/ui-react/syndesis/src/modules/connections/components/Connections.tsx
- app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx
Adds the grid back and tweaks the skeletons to look more like the actual cards:
> chore: polish connection page skeleton loaders

- app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationCreateForm.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/index.ts
- app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationCreateForm.stories.tsx
- app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
Rework the virtualization create page based on feedback from UX
- The VirtualizationCreateForm component was created in packages/ui - now utilizes pf4 components
- The button positions follow pf4 guidelines (cancel button to the right of create button)
- created story for the component
- VirtualizationCreateForm was incorporated into the VirtualizationCreatePage.  Added handler for cancel button - redirects to virtualizations summary page.  Reworked error handling so that the error is more appropriately shown above the form - instead of a toast notification.
> ENTESB-11643 Rework of virtualization create form

- install/operator/pkg/generator/assets/infrastructure/02-syndesis-image-streams.yml.tmpl
This would be a problem with productized builds:
* QE needs to pull the productized images from either brew or quay
* the prometheus image is not built as part of the the productization, an already released image is used
This solves the problem:
* in upstream builds, nothing changes, since `docker.io` is the default when the registry is not specified
* for productized builds, `PrometheusImagePrefix` in `config.yaml` will be changed to `registry.redhat.io/openshift3` and the released image will be used
cc @orpiske
> [ENTESB-11669] Remove Syndesis registry from Prometheus image prefix

- app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
Disables the next button in the CreateView wizard if more than one table is selected.  Either no tables or one table are now allowed.  Previously multiple tables were allowed.
> ENTESB-11607 Limits selected tables in create view wizard

- app/common/model/src/main/java/io/syndesis/common/model/metrics/IntegrationDeploymentMetrics.java
- app/common/model/src/main/java/io/syndesis/common/model/metrics/IntegrationMetricsSummary.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/metrics/SQLMetricsProviderImpl.java
- app/server/metrics/jsondb/src/main/java/io/syndesis/server/metrics/jsondb/IntegrationMetricsHandler.java
- app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/PrometheusMetricsProviderImpl.java
- app/ui-react/packages/api/src/WithIntegrationMetrics.tsx
- app/ui-react/packages/api/src/WithIntegrationsMetrics.tsx
- app/ui-react/packages/models/swagger.internal.json
- app/ui-react/packages/ui/src/Dashboard/UptimeMetric.tsx
- app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
- app/ui-react/packages/ui/stories/Integration/IntegrationDetail.stories.tsx
- app/ui-react/packages/ui/stories/Integration/Metrics/IntegrationDetailsMetrics.stories.tsx
- app/ui-react/packages/utils/src/dateHelpers.ts
- app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
- app/ui-react/syndesis/src/modules/integrations/pages/detail/MetricsPage.tsx
… duration on deployment metrics
This fixes the situation where we have a integration deployment up and running but not yet have had any messages being processed (e.g. webhook integrations)
Fixes ENTESB-11388
> fix(ENTESB-11388): Use server side calculation for integration uptime

- doc/index.adoc
- doc/pom.xml
This adds a `index.adoc` to pull in all documents from modules within the `doc` directory. Currently the daily build is failing because of missing `master.adoc`.
@fbolton, @TovaCohen I don't think this makes a difference in the product doc build, but just to make sure...
> fix: documentation build in the daily release

- app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
When no column names are provided the dynamic json schema generation is not working. Therefore require column names setting. Also gives a default value to data list form object when only one single enum value is provided.
Fixes ENTESB-11273
> fix(ENTESB-11273): Fix required column names configuration for Google Sheets

- app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx
- app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
- See [ENTESB-11247](https://issues.jboss.org/browse/ENTESB-11247)
- added `useVirtualization` hook in order to get updates to the virtualization
- no longer need `state` from the `useRouteData` hook
- now refreshing the published state every 5 seconds to see if it has changed
> fix(ENTESB-11247) - Detail page of Virtualization doesn't contain state of publishing

- doc/customizing/assemblies/customizing
- doc/customizing/assemblies/integrating-applications
- doc/customizing/attributes-links.adoc
- doc/customizing/attributes.adoc
- doc/customizing/docinfo.xml
- doc/customizing/images/customizing
- doc/customizing/images/integrating-applications
- doc/customizing/master.adoc
- doc/customizing/modules/customizing
- doc/customizing/modules/integrating-applications
I created a new doc/customization directory. This directory contains a master.adoc file for creating a book that contains info for: 
- Developing an OpenAPI definition for a client connector
- Adding the client connector to Syndesis
- Developing extensions
- Adding the extensions to Syndesis
We do not yet publish doc to the community Syndesis site, but hopefully that will happen soon, and then this master.adoc file will be useful. 
The new "customization" directory has the same recently reorganized structure as the other directories that contain toplevel documents.
> user doc: Add directory for customization content

- install/operator/README.md
Documentation for CR fields. 
This is not the final documentation, but a temporally one so we can have some reference in the meanwhile. @phantomjinx is working in a dynamic way of generating the documentation from the Syndesis object itself
- Fixes ENTESB-11339
> add some documentation for syndesis CR

- tools/bin/commands/release
Tries to fix the issue with the operator release build:
```
tools/bin/commands/release: line 162: create_operator_image: command not found
```
This also removes two Maven builds and replaces it with a single Maven
build.
> fix: syndesis release command

- app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.css
- app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx
- See [ENTESB-11672](https://issues.jboss.org/browse/ENTESB-11672)
- the results panel can now be scrolled horizontally if all the columns aren't visible on the screen
- deleted `SqlClientContent.css` as it is no longer used
- added `Stack` layout for results panel
> fix(ENTESB-11672) - SQL Client results are not horizontally scrollable

- app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.css
- app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/PreviewResults.tsx
- app/ui-react/packages/ui/stories/Data/ViewEditor/ExpandablePreview.stories.tsx
- app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
- app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
- See [ENTESB-11647](https://issues.jboss.org/browse/ENTESB-11647)
- preview results empty state is now centered and uses full width
- updated preview empty results text as recommended
- changed preview results icon text as recommended
- added label above preview results as recommended to tell user the number of result rows
- added `min-height` to DdlEditor to prevent it from getting too small when query results exist
> fix(ENTESB-11647) - Preview section updates for improved usability

- app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
Tested that it works fine and that it can migrate old values of the connector cleanly.
> [ENTESB-11593] Forcing the channel to be selected from a list, no free text

- app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
- app/server/runtime/src/test/java/io/syndesis/server/runtime/action/DynamicActionSalesforceITCase.java
Restores old behavior (before data list feature) where we use select dropdown by default. Only use dataList for those fields marked accordingly in the connector json (just used by Google Sheets at the moment).
When only one single value is suggested pick this as default value so it is preselected in dropdowns and dataList components.
Fixes ENTESB-11758
> fix(ENTESB-11758): Fix form field rendering on metadata lookup

- install/operator/.lib.sh
- install/operator/build.sh
- tools/bin/commands/build
This allows you to build the operator offline.
> feat: support a `—source-gen skip` option in the operator build script.

- app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
Resolves issue with creating a virtualization.  The usedBy attribute must be initialized on create - it is expected to be present when the virtualization views page is initialized.
> ENTESB-11789 Resolves issue with create virtualization

- .circleci/config.yml
During the creation of backport PR the backport bot creates a temporary ref[1] that gets picked up by CircleCI to build. That build always fails so we get check failures on the PR. This adds ignores to all jobs so that there is no build of this temporary ref.
[1] https://github.com/tibdex/github-cherry-pick/blob/15767bab6cf1c60d2032f9d4ba89fe47e3a3c582/src/index.ts#L318
> fix(ci): ignore `cherry-pick-backport` branches

- app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
- app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
- app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
This adds an info `Alert` on the `Specify Security` page of the API Client Connectors wizard page.
Ref [ENTESB-11474](https://issues.jboss.org/browse/ENTESB-11474)
> chore(ui): description for the Specify Security

- doc/sdh/cli/cmd_crc.adoc
- doc/sdh/cli/cmd_dev.adoc
- doc/sdh/cli/cmd_install.adoc
- doc/sdh/cli/index.adoc
- tools/bin/commands/crc
- tools/bin/commands/dev
- tools/bin/commands/util/openshift_funcs
- tools/bin/syndesis
CodeReady Containers will replace Minishift in future. This PR adds basic CRC support to the syndesis binary so developers can setup a Syndesis local development environment using CRC.
```bash
syndesis crc --full-reset --install --project syndesis
```
Still the syndesis binary is using the legacy way of installing Syndesis (template based) for both Minishift and CRC. There is another PR coming to fix that and to use the new syndesis-operator Go binary for this particular Syndesis install task instead.
Also added the option to install the Maven mirror separately with
```bash
syndesis dev --install-maven-mirror
```
> chore: Add basic CodeReady Containers support to syndesis binary

- app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/PreviewResults.tsx
- app/ui-react/packages/ui/stories/Data/ViewEditor/PreviewResults.stories.tsx
- QE reported this issue while testing the [ENTESB-11672](https://issues.jboss.org/browse/ENTESB-11672) issue
- results table can now be horizontally scrolled when table is wider than the window
- changes to story to allow testing the scrolling
> Preview results in view editor are not horizontally scrollable

- .gitignore
- doc/sdh/cli/cmd_crc.adoc
- doc/sdh/cli/cmd_minishift.adoc
- tools/bin/commands/binaries/README.md
- tools/bin/commands/crc
- tools/bin/commands/util/operator_func.bats
- tools/bin/commands/util/operator_funcs
Use the operator binary instead of old templates. Download the operator binary if it is not present
- `--route` is not needed anymore, the operator takes care of figuring it out
- change defaults so it works properly with latest crc version
- the whole login to a different user logic is removed, why: Is it anyone really using it? With CRC it is needed to pass a password when login as kubeadmin, so the current logic just doesnt work. We can keep it and ask the user for a password, but I would like to challenge an argument whether this is really needed or not.
I am picking the binary from a manual release, which is far from optimal, but with https://github.com/syndesisio/syndesis/pull/6841 I will improve it later
> change syndesis installation to use the operator binary for crc

- app/connector/mongodb/pom.xml
- app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoClientCustomizer.java
- app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoProducerCustomizer.java
- app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/mongodb3.json
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorFindByIdTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorInsertTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorNotSupportedCamelOperationTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorNotSupportedSyndesisOperationTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorUpdateTest.java
* Converting input to raw text (as supported at the moment) or ObjectID (only for id related operations)
* Setting data type as json-instance (to be replaced eventually by ENTESB-11588)
* Improving exception checks unit test cases
fixes ENTESB-11867
> fix(connector): adapting producer input

- .circleci/config.yml
The [release section](https://github.com/syndesisio/syndesis/releases) has a zipped content of the github repo, which doesn't add much value. I want to start releasing the syndesis binaries instead of what it is released right now.
@zregvart suggested that currently this is set up in the github project. I didn't find how to disable this, but my access is restricted (I don't see the settings tab).
My long term goal is to use those binaries to replace the installation methods in `tools/bin/commands/minishift`, in [quickstart](http://syndesis.io/quickstart/) point users to the binaries.
> Release syndesis binaries for real

- app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.css
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.css
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
- see [TEIIDTOOLS-792](https://issues.jboss.org/browse/TEIIDTOOLS-792)
- the components used for viewing and editing the virtualization description will show a max of 5 lines and provide a scrollbar to view the rest if needed
- added a CSS to style the virtualization description on the `VirtualizationSqlClientPage`
- added a CSS to style the virtualization description on the `VirtualizationViewsPage`
- truncating the virtualization descriptions on the list items of the `VirtualizationsPage` if greater than 150 chars
> fix(TEIIDTOOLS-792) - Virtualization Description Issues

- app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlMetadataRetrieval.java
- app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
- app/connector/sql/src/test/resources/sql/name_sql_batch_update_metadata.json
- app/connector/sql/src/test/resources/sql/name_sql_metadata.json
- app/connector/sql/src/test/resources/sql/name_sql_no_param_metadata.json
- app/connector/sql/src/test/resources/sql/name_sql_update_metadata.json
- app/connector/sql/src/test/resources/sql/name_sql_update_no_param_metadata.json
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
Use dataList component for SQL query so we can revert meta data lookup on server to use the original logic. This way other connectors that rely on "text"/"string" getting automatically rendered as dropdown are not affected.
We will straighten the meta logic and the connector json property types on master as part of https://issues.jboss.org/browse/ENTESB-11969
> fix(ENTESB-11787): Reconfiguration of SQL query step changes text to dropdown

- app/connector/mongodb/pom.xml
Added an explicit dependency managment to override the imported from spring and be able to use the same version property for embedded-mongo and embedded-process libraries
fixes #6872
> fix(connector): embedded mongo align version

- app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationCreateForm.tsx
- app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationCreateForm.stories.tsx
- app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
The create button on the create virtualization page is now disabled if the name entry is empty.
- added isDisableCreate property to the VirtualizationCreateForm for disabling the button
- adapted the AutoForm in VirtualizationCreatePage to validate the required properties set the createForm property
- remove requiredPropertyText from our data translations and now using the shared equivalent
> TEIIDTOOLS-801 disables create virtualization button if name is empty

- app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx
- app/ui-react/packages/ui/src/Integration/Details/IntegrationActionSelectorCard.tsx
- app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorForm.tsx
- app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorNothingToConfigure.tsx
- app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderSetInfo.tsx
- app/ui-react/packages/ui/src/Integration/Editor/choice/ChoiceCardHeader.tsx
- app/ui-react/packages/ui/src/Integration/Editor/choice/ChoicePageCard.tsx
- app/ui-react/packages/ui/src/Integration/Editor/endpoint/DescribeDataShapeForm.tsx
- app/ui-react/packages/ui/src/Integration/Editor/shared/EditorPageCard.tsx
- app/ui-react/packages/ui/src/Integration/IntegrationSaveForm.tsx
- app/ui-react/packages/ui/src/index.css
fixes https://github.com/syndesisio/syndesis/issues/6240
@amysueg @dongniwang 
Here is a sample card using the PF3 card component
Here is that card updated to a PF4 card with no additional modifications to the card. Note that the PF4 card doesn't have a border below the title or a border/background color on the footer
Here is the PF4 card with additional styles to mimic the PF3 card
What do you think? I've included the last variation (PF4 cards updated to look like PF3) in this PR, but the additional styling on top of the base PF4 card component is an additional commit, so it's easy to revert if we just want to use the card styles provided by PF4.
---
Also for testing, I don't know how to find/test all of these locations in the application, but here is a list of the component that was …
> fix(cards): update static use of pf3 cards to pf4 react components

- app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/aws-ddb.json
Using dataList instead of the string type to make sure we have input type text.
> [ENTESB-11971] Fixing configuration of AWS DDB

- app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/ResponseCustomizer.java
- app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/ResponseCustomizerTest.java
- app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/RestSwaggerConnectorIntegrationTest.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/UnifiedJsonDataShapeGenerator.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/JsonSchemaHelper.java
- app/server/api-generator/src/test/resources/swagger/damage_service.unified_connector.json
- app/server/api-generator/src/test/resources/swagger/kie-server.unified_connector.json
- app/server/api-generator/src/test/resources/swagger/machine_history.unified_connector.json
- app/server/api-generator/src/test/resources/swagger/petstore.unified_connector.json
- app/server/api-generator/src/test/resources/swagger/petstore_xml.unified_connector.json
- app/server/api-generator/src/test/resources/swagger/reverb.unified_connector.json
- app/server/api-generator/src/test/resources/swagger/todo.unified_connector.json
- app/server/inspector/src/main/java/io/syndesis/server/inspector/JsonSchemaInspector.java
- app/server/inspector/src/test/java/io/syndesis/server/inspector/JsonSchemaInspectorTest.java
- app/server/inspector/src/test/resources/petstore-unified-schema.json
Json schema draft 6 was causing problems in jackson library when parsing unified Json data shapes. So roll back to using jackson compatible draft version.
Started to incorporate a library that supports Json schema draft 6 but this is a really big change as we use the jackson schema quite a lot in server, meta and connectors. so we would need a bigger refactoring. so being a little less hip might do the trick for us, too.
> fix(ENTESB-11945): roll back to use Json schema draft 4

- app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
- app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
- app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
When a new view is created via the 'Create a View' wizard, now redirects to the View Editor page rather than the Virtualization details page.
- Added getView function to useVirtualizationHelpers, to allow retrieval of View using the virtualization and view names
- Adapt SelectNamePage from the wizard - now redirects to editor page upon successful view creation.   Also removed the toast notification for success
> TEIIDTOOLS-803 Redirect to editor after view creation

- app/common/model/src/main/java/io/syndesis/common/model/ListResult.java
- app/common/model/src/test/java/io/syndesis/common/model/ListResultTest.java
- app/server/endpoint/pom.xml
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationDeploymentHandler.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandlerTest.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationDeploymentHandlerTest.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationOverviewHelperTest.java
`PublicApiHandlerTest` much like the whole public API is a convoluted mess. At least having the test cleaned could help with refactoring it to a smaller mess.
Several issues with the test:
- test mostly exercised mocks
- assertions tested to broadly (i.e. _some_ integration was updated)
- spaghetti mock usage, where by any change to a mock configuration
would introduce issues in several test cases
- no exception assertions were used
This refactors the test to use AssertJ instead of JUnit Hamcrest assertions which are much more versatile; cleans up mock usage and does general refactoring for code quality.
> refactor: cleanup PublicApiHandlerTest

- app/integration/bom/pom.xml
- app/pom.xml
- app/ui-react/packages/atlasmap-assembly/package.json
- app/ui-react/packages/atlasmap-assembly/src/app/data-mapper-host.component.ts
- app/ui-react/yarn.lock
Contains:
https://issues.jboss.org/browse/ENTESB-11959 - Data mapper fails when editing already created integration
> chore: Update to AtlasMap 1.42.9

- install/operator/build/conf/config.yaml
`v3.9` doesn't exist in upstream prometheus: https://hub.docker.com/r/prom/prometheus/tags , so changing it to latest stable available
> [Prometheus] Fix docker tag for Prometheus

- app/ui-react/packages/api/src/useViewDefinition.tsx
- app/ui-react/packages/api/src/useViewDefinitionDescriptors.tsx
- app/ui-react/packages/api/src/useVirtualization.tsx
- app/ui-react/packages/api/src/useVirtualizationConnectionSchema.tsx
- app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
- app/ui-react/packages/api/src/useVirtualizations.tsx
- app/ui-react/packages/models/src/dv.d.ts
- app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
- app/ui-react/syndesis/src/modules/data/ViewsImportApp.tsx
- app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectConnectionPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
- app/ui-react/syndesis/src/modules/data/resolvers.ts
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationNavBar.tsx
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Adapts the UI for service endpoint refactor in teiid-syndesis.  Also addressed TEIIDTOOLS-806, the special purpose view validation service was removed.
- endpoint name changes
- renamed RestDataService to Virtualization in models
- ViewEditorSqlPage adapt to removal of the view validation service.  The validation state is now included with the ViewDefinition.  adapted and consolidated ViewEditorSqlPage validate functionality
> TEIIDTOOLS-807 Adapt DV UI for service endpoint refactor

- app/ui-react/packages/auto-form/src/widgets/FormLegendComponent.css
- app/ui-react/packages/auto-form/src/widgets/FormLegendComponent.tsx
- app/ui-react/packages/auto-form/src/widgets/FormMapsetComponent.css
- app/ui-react/packages/auto-form/src/widgets/FormMapsetComponent.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
fixes [ENTESB-12004](https://issues.jboss.org/browse/ENTESB-12004)
Updates the layout of the error handling form a bit, had to really force a couple things too:
> fix: tidy up the api provider response error handling form thingy

- app/ui-react/packages/api/src/useConnection.tsx
- app/ui-react/syndesis/src/modules/connections/pages/ConnectionDetailsPage.tsx
for [ENTESB-11405](https://issues.jboss.org/browse/ENTESB-11405)
@claudio4j this is what I was thinking in regards to the server events.
Looking deeper I think I led you astray a bit, `useConnection` returns a `read()` function that can be used to trigger a fetch, so another option would have been to call `read()` after calling the save function.  But this approach should work as well, after going through the oauth dance once there's a change made to the connection the UI should then fetch an updated connection.
I can't seem to fully see this working in development mode though, it seems like the dev proxy isn't receiving the change events for some reason.  Can you test this in your environment?  You'd want to build the console and deploy it to verify I think, open the network tab and you …
> fix: fetch updates on the detail page when change events are received

- app/pom.xml
- tools/bin/commands/release
This adds a profile active when `stagingDescription` property is not defined to include docs, ui-react and test Maven modules; otherwise when it's defined, at the point we stage artifacts for publishing to Maven central those modules are excluded from the reactor.
> fix(release): non-staging profile

- app/ui-react/packages/api/src/useViewDefinition.tsx
- app/ui-react/packages/api/src/useVirtualization.tsx
- app/ui-react/packages/api/src/useVirtualizationConnectionSchema.tsx
- app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
- app/ui-react/packages/models/src/dv.d.ts
- app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
- app/ui-react/syndesis/src/modules/data/ViewsImportApp.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
- app/ui-react/syndesis/src/modules/data/resolvers.ts
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationHandlers.ts
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
The teiid-syndesis backend was refactored to adopt consistent naming of endpoints and attributes.  This adapts the UI endpoints and models to those changes.
- removal of tko__ and keng__ prefixes
- went to consistent camel case for naming
> TEIIDTOOLS-812 adapts DV UI for service naming changes

- install/operator/build/conf/config.yaml
Fixes https://issues.jboss.org/browse/ENTESB-12039
Fixes https://github.com/syndesisio/fuse-online-install/issues/188
> Bump db to 9.6

- app/common/util/src/main/java/io/syndesis/common/util/Json.java
Also relates to ENTESB-12042 as fix.
Fixes #6948
> fix(#6948): Jackson version clash between compile and integration runtime

- app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoClientCustomizer.java
Properly setting the administration database when the default one is chosen
> fix(connector): default admin db for mongo

- app/common/model/src/main/java/io/syndesis/common/model/metrics/IntegrationDeploymentMetrics.java
- app/common/model/src/main/java/io/syndesis/common/model/metrics/IntegrationMetricsSummary.java
- app/common/util/pom.xml
- app/common/util/src/main/java/io/syndesis/common/util/Json.java
- app/extension/maven-plugin/pom.xml
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/metrics/SQLMetricsProviderImpl.java
- app/server/metrics/jsondb/pom.xml
- app/server/metrics/jsondb/src/main/java/io/syndesis/server/metrics/jsondb/IntegrationMetricsHandler.java
- app/server/metrics/jsondb/src/main/java/io/syndesis/server/metrics/jsondb/JsonDBRawMetrics.java
- app/server/metrics/jsondb/src/main/java/io/syndesis/server/metrics/jsondb/PodMetricsReader.java
- app/server/metrics/jsondb/src/main/java/io/syndesis/server/metrics/jsondb/RawMetrics.java
- app/server/metrics/jsondb/src/test/java/io/syndesis/server/metrics/jsondb/MetricsCollectorTest.java
- app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/PrometheusMetricsProviderImpl.java
This removes instances of SimpleDateFormat that are used in a thread unsafe manner and refactors the use of java.util.Date to java.time.Instant.
Also changes the model not to require lombok as it provides no value in the trivial usage it's applied to.
> refactor: remove unsafe usage of SimpleDateFormat

- app/common/util/src/test/java/io/syndesis/common/util/RandomValueGeneratorTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorMissingDatabaseOptionsTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorNotSupportedCamelOperationTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorNotSupportedSyndesisOperationTest.java
- app/connector/sql/src/test/java/io/syndesis/connector/sql/common/SqlParserTest.java
- app/integration/component-proxy/src/test/java/io/syndesis/integration/component/proxy/ComponentDefinitionTest.java
- app/integration/component-proxy/src/test/java/io/syndesis/integration/component/proxy/CustomComponentTest.java
- app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/ProjectGeneratorTest.java
- app/integration/runtime/src/test/java/io/syndesis/integration/runtime/logging/ActivityLoggingTest.java
- app/integration/runtime/src/test/java/io/syndesis/integration/runtime/logging/ActivityLoggingWithSplitTest.java
- app/integration/runtime/src/test/java/io/syndesis/integration/runtime/tracing/ActivityTracingWithSplitTest.java
- app/server/credential/src/test/java/io/syndesis/server/credential/CredentialProviderRegistryTest.java
- app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/util/ReflectiveSorterTest.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/state/ClientSideStateTest.java
- app/server/jsondb/src/test/java/io/syndesis/server/jsondb/impl/JsonDBTest.java
- app/server/jsondb/src/test/java/io/syndesis/server/jsondb/impl/SqlJsonDBIntegrationTest.java
- app/server/runtime/src/test/java/io/syndesis/server/runtime/DataManagerITCase.java
Annotating tests with `@Test(expected = SomeException.class)` does poor assertion of the exception that's expected to be thrown and possibly fails the assertion as the exception can be thrown from any line in the test method and with any arbitrary message or cause.
This construct should be replaced with AssertJ's `assertThatExceptionOfType` et al. exception assertions[1].
[1] https://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html#exception-assertion
> refactor: proper exception assertion

- doc/assemblies/connecting/as_connecting-to-jira.adoc
This just removes the Tech Preview note from the doc for the Jira connector.
> user doc: Remove Tech Preview note

- tools/bin/commands/release
Allows us to have more console output for error analysis.
> chore: Make Maven quiet option optional on release scripts

- app/connector/kudu/src/test/java/io/syndesis/connector/kudu/KuduScanCustomizerTest.java
- app/connector/kudu/src/test/java/org/apache/camel/component/kudu/AbstractKuduTest.java
- app/connector/kudu/src/test/java/org/apache/camel/component/kudu/KuduProducerTest.java
This cleans up the kudu connector tests by making sure resources are
disposed using try-with-resources and proper exception handling is
performed.
> refactor: cleanup kudu connector tests

- app/pom.xml
Seems that the change in #6942 prevents the UI from being built as it's build with `-DstagingDescription` and the `deploy` Maven goal. This reinstates the `ui-react` module in that case.
> fix(release): build the UI

- app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirMetaDataExtension.java
- app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/AggregateStepHandler.java
- app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/ActivityTrackingInterceptStrategy.java
- app/integration/runtime/src/main/java/io/syndesis/integration/runtime/util/JsonSimplePredicate.java
`if` blocks that contain a `return` or a `throw` do not need to use the `else` block for the _otherwise_ case. This increases complexity and makes the code harder to read.
> refactor: remove needless else

- app/common/pom.xml
- app/connector/mqtt/pom.xml
- app/connector/pom.xml
- app/extension/bom/pom.xml
- app/server/pom.xml
This removes unneeded declarations of module versions when the version is inherited from the parent Maven module and declares the missing version for the maven-deploy-plugin plugin in the extension BOM.
> fix: warnings in Maven POM

- app/ui-react/pom.xml
This makes sure that the `non-ui-related-so-disabled` profile is active in cases where other profiles are activated via command line, as is the case in release when we specify `-Prelease`.
Unfortunately `<activeByDefault>` activates the profile only in the case other profiles are not activated[1].
Also ensures additional plugin executions, not related to the UI build are not performed by adding them to the non-phase.
[1] https://issues.apache.org/jira/browse/MNG-4917
> fix(release): don't perform Java release for UI

- app/pom.xml
One snag in upgrading was the false positive PMD issue, so the PMD plugin was manually downgraded.
> chore: upgrade basepom to 30 (from 29)

- tools/bin/commands/release
When we run `mvn nexus-staging:release` we do not wish to include the ui-react module. We don't wish to publish ui-react artefacts to Maven central and we don't have any configuration for the nexus-staging plugin to work with in the ui-react module.
> fix(release): exclude ui-react module from nexus

- app/ui-react/pom.xml
- tools/bin/commands/release
After quite some deliberations, trials and errors I think I understand
what the issue is with staging and releasing artifacts to Maven central
using nexus-staging plugin.
Disabling the nexus-staging plugin from ui-react module ends up not
uploading the artifacts to the staging repository when performing the
`deploy` goal via `nexus-staging:deploy`. This is because the upload to
the staging repository is deferred till the last module, and since the
ui-react is the last module in the reactor and the nexus-staging plugin
execution is skipped there the upload doesn not happen.
Then when we try to release the artifacts from the staging repository
using `nexus-staging:release` there is no staging repository and the
invocation again fails on the last module, which was `meta` and
previously …
> fix(release): perform remote staging

- app/ui-react/pom.xml
We do not wish to publish the `ui-react-x.y.z-dist.tar.gz` artefact to
Maven central, so we need to disable the attachment of artifact from the
Maven reactor. Being that the ui-react module is the last module in the
reactor and that staging of artefacts will happen on the last module
there is no way to escape staging of the POM file of the ui-react. So
for the staged repository to be released we can't skip the signing of
the POM file.
So this will in fact publish the ui-react module to Maven central, but
hopefully only of the POM.
[ci skip]
> fix(release): dist attachment and POM signature

- app/ui-react/packages/api/src/WithConnection.tsx
- app/ui-react/packages/api/src/helpers/connectionFunctions.ts
- app/ui-react/packages/api/src/useConnection.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/SelectActionPage.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
fixes #6978
With this you can see the request/response action from AMQ:
@squakez FYI
> feat: add semantics for actions with 'Pipe' pattern

- package.json
- yarn.lock
The 8.2 version of commitlint has issues working with git worktrees.
This upgrades to 8.3.3 which doesn't manifest these.
Ref https://github.com/conventional-changelog/commitlint/issues/787
> chore(hooks): upgrade commitlint

- app/connector/support/maven-plugin/src/main/resources/connector-schema.json
As highlighted in a [recent document](https://syndesis.io/docs/connector-schema/) we have in place a connector schema validation running at connector build time. However this is not strict, in the sense that any connector can add arbitrarily any additional configuration, allowing a non homogeneous growth.
With this PR we are limiting the possibility to add any further configuration without changing this file (and possibly without adding any documentation). We should see this file as a contract between UI and Backend, and we should keep documentation aligned.
Thanks @phantomjinx for the initial development of the schema.
> feat(connector): Adding "strict mode" connector validation

- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorNotSupportedCamelOperationTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorNotSupportedSyndesisOperationTest.java
- app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteNoSplitResultsTest.java
- app/connector/support/util/src/main/java/io/syndesis/connector/support/util/TrustAllTrustManager.java
- app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java
- app/integration/api/src/main/java/io/syndesis/integration/api/IntegrationResourceManager.java
- app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/IntegrationRuntimeAutoConfiguration.java
- app/meta/src/main/java/io/syndesis/connector/meta/Application.java
- app/pom.xml
- app/server/api-generator/src/test/java/io/syndesis/server/api/generator/util/IconGeneratorTest.java
- app/server/credential/src/main/java/io/syndesis/server/credential/salesforce/SalesforceConfiguration.java
- app/server/credential/src/test/java/io/syndesis/server/credential/CredentialsIntegrationTest.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationDeploymentHandler.java
Contains:
refactor: remove unused imports (e116d41)
refactor: warning suppression tuning (97d9c9c)
This removes unnecessary @SuppressWarnings and adds additional ones that
are needed to pass the stricter checks.
refactor: test cleanup (0ca4cb7)
refactor: field can be final (4a71242)
refactor: group overridden methods (15bd8be)
refactor: field could be final (4130261)
In this case since Plexus will initialize the field with the default
value when the Mojo is configured there's no need to initialize the
field at construction, that would be cleaner, but it would mark the
field for could be made final check.
chore: stricter errorprone checks (ac71470)
This adds additional errorprone checks by changing their severity from
suggestion to warning. And makes sure that the autofix profile can …
> More refactorings and stricter errorprone

- app/test/integration-test/src/test/java/io/syndesis/test/itest/sql/DBToHttp_IT.java
- app/test/integration-test/src/test/resources/io/syndesis/test/itest/sql/DBToHttp-export/model.json
DBToHttp_IT has had flaky behavior on CI builds. The order of contact entries has not been deterministic so the Http server validation sometimes failed. Now order entries by first name.
> fix: Flaky integration test on nightly CI

- app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx
- app/ui-react/packages/ui/stories/Data/Virtualizations/SqlClientContent.stories.tsx
- app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
- see [TEIIDTOOLS-813](https://issues.jboss.org/browse/TEIIDTOOLS-813)
- added `Spinner` to `SqlClientContent` that is shown when query is running
- updated story to include a loading scenario
> fix(TEIIDTOOLS-813) - Indicate results loading in-progress on SQL client page

- app/common/util/src/main/java/io/syndesis/common/util/thread/Threads.java
- app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java
This replaces one more ThreadGroup creation with the use of the Threads utility class, which also now logs any uncaught exceptions.
> refactor: more use of the Threads utility class

- app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
- app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaList.stories.tsx
- app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaListItem.stories.tsx
- app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
- app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
- Jira Issue https://issues.jboss.org/browse/TEIIDTOOLS-681
- With this PR here is the behavior of Create View Wizard:
when the user expands and selects connection and table on page 1 move to page 2 then decided to come back on page 1.
-- connection selection is maintained.
-- list with selected connection is maintained in an expanded state.
- Lifted selected nodes state up in ViewCreateApp component.
- Added haveSelectedSource props in ConnectionSchemaListItem to control the list expansion.
- Assumption: 
--"teiidName" info for a connection is always present and unique.
--"connectionName" is always unique.
> fix: maintain selection in create view wizard TEIIDTOOLS-681

- README.md
We already point to the developer handbook. The quickstart here should be targeted towards non-developers. If we don't have the `--nodev` option on the CLI then the image streams will point to local OpenShift registry that won't have any images until we build and push to that registry via S2I.
> chore: add `--nodev` option to README

- tools/bin/commands/util/operator_funcs
We renamed the operator binary from `operator` to `syndesis` to
`syndesis-operator` (I think that was how the lineage went). The current
binary is named `syndesis-operator`, so we need to use that name as it's
the filename that will be created when we untar the release from GitHub.
The linux platform tar archive has `linux-amd64` in it, we need the to
reflect that.
> fix(install): platform and binary name

- app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx
- app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
- app/ui-react/syndesis/src/modules/data/ViewsImportApp.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectConnectionPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
- app/ui-react/syndesis/src/modules/data/shared/DvConnections.tsx
- app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
- app/ui-react/syndesis/src/modules/data/shared/ViewInfosContent.tsx
- Jira Issue https://issues.jboss.org/browse/TEIIDTOOLS-679
- With this PR here is the behavior of Import Datasource Wizard
When the user selects some source on page 1 and moves to page 2 and selects few connections their
--If the user moves back to page 1, the selected source will be maintained selected there.
--If the user does not change selection on page 1 and move back to page 2 then the connections selected there will be maintained.
--If the user changes the selection on page 1 then connection selected on page 2 will be reset
- Lifted the selected source state and selected connection state form SelectConnectionPage and SelecViewPage respectively to ViewsImportApp.
> fix: maintain list item selections on back/next TEIIDTOOLS-679

- app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewList.tsx
Moves the ListViewToolbar inside of the hasListData check, so that the toolbar and buttons are hidden when there is no list data.
> TEIIDTOOLS-824 Hide list toolbar if no views

- app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx
- app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
- see [TEIIDTOOLS-827](https://issues.jboss.org/browse/TEIIDTOOLS-827)
- added route params to `VirtualizationEditorPage` so that virtualization name is immediately available to page
- reworked code that referenced `state.virtualization` since that is not available during cut/paste
- description initializes to the actual description when clicking from page to page. It was previously always initializing to `Draft`
- changed build status total steps from 4 to 3
- i18n'd the build status values
> fix(TEIIDTOOLS-827) - Cut/Paste URL of virtualization views page or SQL client page does not work

- app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
- Jira Issue https://issues.jboss.org/browse/TEIIDTOOLS-820
- with this PR here is the behaviour in Import Datasource wizard
-- Allowed selection of any ACTIVE connection, even if loading.
--Removed spinner for ACTIVE connections that are 'loading' (refreshing)
> fix: selection allowed for source of active status even for loading

- app/ui-react/syndesis/src/modules/data/index.tsx
- app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationDetailsPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/index.ts
- app/ui-react/syndesis/src/modules/data/resolvers.ts
- app/ui-react/syndesis/src/modules/data/routes.ts
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationNavBar.tsx
Adds the details tab to the virtualization page.  Content is 'coming soon...' for now, will be updated in subsequent PRs
- Add VirtualizationDetailsPage
- Add the new page to the VirtualizationNavBar
- update routes and resolvers to include details
- also include fix for TEIIDTOOLS-836 - modify PageSection on VirtualizationPages so that content margins agree with other pages.
> TEIIDTOOLS-829 Adds details tab to virtualization page

- app/integration/bom/pom.xml
- app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/pom.xml.mustache
- app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/pom.xml
- app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/pom.xml
With this PR we give Integration BOM priority over Spring Dependencies BOM, allowing to override dependencies by forcing its declaration in Integration BOM. Provided here with mongo-java-driver 3.6.3 needed to be aligned with camel upstream component version and overriding managed 3.4.3 provided by Spring.
Closes ENTESB-12244
PS: I've run a diff between the new and previous S2I to confirm the only changed library is the one highlighted
> feat(integration): dependency version override BOM

- tools/bin/commands/dev
This adds `--nuke` option to the `dev --cleanup` command:
syndesis dev --cleanup --nuke
When specified tables in the syndesis database with user data will be
truncated and any causal user created OpenShift object will be deleted;
effectively reseting the environment back to the initial state.
In the process the syndesis-server pod will be restarted, this is to
load the syndesis database with the initial data.
> chore(cli): add option to reset everything

- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerAllOptionsTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorChangeStreamConsumerTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorTestSupport.java
* Provided persistent tracking in repeating consumer tailing unit test
* Setting mock retain policy to check last message in other consumer unit tests
Fix #7115
> fix(connector/mongodb): flaky test cases fix

- install/operator/pkg/syndesis/configuration/configuration.go
- install/operator/pkg/syndesis/configuration/configuration_test.go
Allow `Config.Syndesis.Components.Server.Features.TestSupport` to be overwritten using environment variable "TEST_SUPPORT"
> Add env support for TestSupport

- app/connector/mongodb/pom.xml
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerAllOptionsTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorChangeStreamConsumerTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCountTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorFindAllTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorInsertTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorMissingDatabaseOptionsTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorProducerTestSupport.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorRemoveTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorSaveTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorTestSupport.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorUpdateTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/embedded/EmbedMongoConfiguration.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/meta/MongoDBMetadataTest.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/verifier/MongoDBVerifierTest.java
* Starting a unique static server instead of one for each testcase
* Reduced time to execute all testcases by half due to the above
`EmbedMongoConfiguration` will startup a unique server (with replicaset). Each unit test class will use its own collection to reduce resource consumption and limit possibility of test collisions.
Fixes #7164
> fix(connector/mongodb): embedded mongo refactory

- doc/modules/customizing/p_creating-jdbc-driver-library-extensions.adoc
- Refer to using the Maven wrapper in docs to make sure that the build is successful. It is required to use the exact same Maven version otherwise build of extension may fail.
- Add some information how to add the correct system path when custom driver file has been copied.
> chore: Improve docs about creating a JDBC driver library extension

- doc/modules/integrating-applications/p_create-api-provider-integration.adoc
Kurt approved this update to the doc for creating an api provider integration. The update states that you must download the raw version of the file, or specify the URL for the raw version.
> user doc: State that raw version of task-api.json is required

- doc/sdh/cli/cmd_install.adoc
- tools/bin/commands/install
This removes the `--nodev` option from `syndesis install`, development workflows are supported via `syndesis minishift` or `syndesis crc`. For installing to arbitrary cluster one needs to perform `syndesis install` followed by editing of the Syndesis custom resource to enable the dev mode or use the `syndesis-operator` binary with `--dev` option.
Updates the documentation.
> chore(install): remove `--nodev` from `syndesis install`

- tools/bin/commands/util/operator_funcs
The operator download fails for Mac as the OS calls itself 'darwin' and not 'mac-64'.
> fix for Community install is broken #7157

- app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/PrometheusMetricsProviderImpl.java
- app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/Utils.java
https://issues.jboss.org/browse/ENTESB-12268
> ENTESB-12268 Integration uptime doesn't contain any data

- app/ui-react/packages/ui/src/Shared/DndFileChooser.css
- app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
- app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.css
- app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx
- app/ui-react/packages/ui/stories/Integration/Editor/ApiProvider.stories.tsx
- app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
- app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx
- app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
- app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/ReviewActionsPage.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/SelectMethodPage.tsx
- app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
related to [ENTESB-12218](https://issues.jboss.org/browse/ENTESB-12218)
fixes #7195 
fixes #6457
Also fixes a couple typos and improves the create method component so it disables the file upload/URL input field instead of hiding them so the page layout stays consistent.
> feat: add a create OpenAPI 3.x option to the API provider wizard

- app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
Now that the Fuse 7.5 user doc has been published on the Red Hat customer portal, the staging site can link to the 7.5 Fuse Online documents. 
Stan already updated the 1.8 branch to have the 7.5 version number. So no need to backport this update. This just makes the links in the staging site display the latest doc.
> user doc: Update release number to 7.5 in UI links to downstream doc

- tools/bin/commands/release
When we do a release, set operand images to the version being released instead of latest
Fixes https://issues.jboss.org/browse/ENTESB-12176
> Set operand images to right tag when building

- .gitignore
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/embedded/EmbedMongoConfiguration.java
- app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/meta/DataShapeConnectorTest.java
- app/connector/mongodb/src/test/resources/logback-test.xml
This creates the database in a temporary directory instead of $HOME
making the tests repeatable and allow them to run concurrently and in
environments where $HOME is not writable (CI).
Redirects the output to `target/test.log` to speed up the build and keep
the output separate from the console output of the build.
> refactor(mongodb): database directory and output

- app/connector/email/src/test/resources/logback-test.xml
This redirects test output to `target/tests.log`.
> refactor(connector/mail): redirect test output

- doc/assemblies/tutorials/as_amq2api-intro.adoc
- doc/assemblies/tutorials/as_sf2db-intro.adoc
Evaluation versions of Fuse Online continue to provide the To Do app and the PostgresDB connection. But by default, installations of Fuse Online do not include these features. I added a prereguisite to the tutorials for the Salesforce to DB sample integration and for the AMQ to REST API sample integration, to say that you must be running an evaluation version of Fuse Online or you must be running a Fuse Online environment to which the sample data was added. This prerequisite is conditionalized to appear only downstream. Although the prerequisite is obviously in the upstream source, if and when the doc is published on the community web site, this prerequisite will not appear. Luis and Martin Stepanek reviewed/approved this update.
> user doc: Add downstream prereq for eval version or sample data installed

- app/pom.xml
This upgrades the git-commit-id-plugin to the current latest version
(4.0.0) and configures it so it's more performant, should lead to
noticeable build time improvements.
> chore(build): speed up git-commit-id-plugin

- app/server/runtime/src/test/java/io/syndesis/server/runtime/integration/IntegrationDeploymentITCase.java
The current state during an ongoing change of state might be either
`Pending` or the expected state (the `targetState`), in this test we
don't really care, what we want is that the state transitions, so rather
than rigidly expecting the state to be as expected as the `targetState`
we can tollerate it being `Pending` and assume the same level of
confidence in the test.
Fixes #4825
> fix(server): deflake IntegrationDeploymentITCase

- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/OpenApiGenerator.java
- app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/OpenApiGeneratorTest.java
Use uppercase Http method names in flow description as this is displayed in UI to show the different flows in an OpenAPI operation.
Fixes ENTESB-12310
> fix(ENTESB-12310): Fix spelling of API provider flow descriptions

- doc/assemblies/integrating-applications/as_trigger-integrations-with-api-calls.adoc
This corrects a URL so that a link will work in downstream rendered user doc. 
This link doesn't make sense upstream, so I conditionalized it to only appear in downstream rendered doc.
> user doc: Correct a broken link and conditionalize it to appear only downstream

- app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvCacheHitMetric.css
- app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvCacheHitMetric.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvClientSessionMetric.css
- app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvClientSessionMetric.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvMetricsContainer.css
- app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvMetricsContainer.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvRequestMetric.css
- app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvRequestMetric.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvUptimeMetric.css
- app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvUptimeMetric.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/index.ts
- app/ui-react/packages/ui/src/Data/Virtualizations/index.ts
- app/ui-react/syndesis/src/modules/data/index.tsx
- app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/index.ts
- app/ui-react/syndesis/src/modules/data/resolvers.ts
- app/ui-react/syndesis/src/modules/data/routes.ts
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationNavBar.tsx
- see [TEIIDTOOLS-846](https://issues.jboss.org/browse/TEIIDTOOLS-846)
- added new virtualization editor page for metrics
- created `DvMetricsContainer` as a container for individual metric components
- added metric components for cache hit ratio, client sessions, requests, and uptime
- i18n of metric components was not done as it is still unclear which metric components will be needed
> fix(TEIIDTOOLS-846) - Add a page for virtualization metrics

- app/connector/email/pom.xml
- app/connector/email/src/main/java/io/syndesis/connector/email/EMailUtil.java
- app/connector/email/src/test/java/io/syndesis/connector/email/consumer/EMailReadWithTLSRouteTest.java
- app/connector/email/src/test/java/io/syndesis/connector/email/verifier/EMailVerifierTest.java
- app/connector/odata/pom.xml
- app/dv/pom.xml
- app/dv/src/test/java/io/syndesis/dv/openshift/TestVDBPublisher.java
- app/dv/src/test/java/io/syndesis/dv/server/endpoint/ServiceVdbGeneratorTest.java
- app/pom.xml
- app/test/integration-test/pom.xml
- app/test/integration-test/src/test/java/io/syndesis/test/itest/ftp/FtpSplitToDB_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/ftp/FtpToDB_IT.java
This removes the use and forbids the Hamcrest dependency using the
enforcer plugin.
The reasoning behind that is that Hamcrest encourages poorly defined
assertions that fail with unhelpful messages whereas AssertJ encourages
verbose assertions that fail with more helpful messages.
> refactor: remove hamcrest dependency

- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/support/SupportUtil.java
* Without the Autowired annotation, spring appears unable to choose which
constructor to use.
> fix(#7214): spring cannot choose the correct constructor

- app/ui-react/packages/models/src/dv.d.ts
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.css
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.tsx
- app/ui-react/packages/ui/stories/Data/Views/ViewList.stories.tsx
- app/ui-react/packages/ui/stories/Data/Views/ViewListItem.stories.tsx
- app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
- see [TEIIDTOOLS-809](https://issues.jboss.org/browse/TEIIDTOOLS-809)
- added `valid` to the `ViewDefinitionDescriptor` model object
- added a red `Label` to `ViewListItem` with the text "Invalid" when a view is invalid
- updated stories
> fix(TEIIDTOOLS-809) - ViewListItem should show icon indicating if the view is invalid

- install/operator/build/conf/config-test.yaml
- install/operator/go.mod
- install/operator/pkg/syndesis/configuration/configuration_test.go
Fixes: https://github.com/syndesisio/syndesis/issues/7232
When building, the default values from the configuration file `conf/config.yaml` are changed to better fit the build, and test fails. It is better to have a test configuration file for the tests.
> Run configuration tests using a test file

- tools/bin/commands/crc
- tools/bin/commands/install
- tools/bin/commands/minishift
- tools/bin/commands/util/operator_funcs
Fixes https://github.com/syndesisio/syndesis/issues/7086
If that `--tag` is set, forde download of a new binary and download the binary from the specified release
> Fix install not taking the tag

- app/ui-react/packages/ui/src/Dashboard/Dashboard.css
- app/ui-react/packages/ui/src/Dashboard/Dashboard.tsx
This was bugging me yesterday.  Basically this PR makes the dashboard cards align better, so instead of:
it looks like:
> chore: fix the alignment of the dashboard cards

- app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationActions.tsx
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
- see [TEIIDTOOLS-853](https://issues.jboss.org/browse/TEIIDTOOLS-853)
- fixes a bug in `VirtualizationActions` that prevented the kebab menu item from being disabled
- reworked `VirtualizationActionContainer` to only construct actions that are actually being used (removed default actions)
- added logic in `VirtualizationActionContainer` to disable delete action when virtualization is published or being published
> fix(TEIIDTOOLS-853) - Disable delete action in virtualization details kebab if running or in-progress

- .github/workflows/backport.yml
The backporting bot has been migrated to github actions. This PR enables it (See https://github.com/marketplace/actions/backporting)
> Moving backporting bot to use actions

- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiFlowGenerator.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/UnifiedJsonDataShapeGenerator.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/UnifiedXmlDataShapeGenerator.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/UnifiedDataShapeGenerator.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/UnifiedJsonDataShapeGenerator.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/UnifiedXmlDataShapeGenerator.java
Fix wrong usage of `Optional.of()` in favor of using `Optional.ofNullable()`.
> fix(ENTESB-12218): Wrong usage of Optional.of() in server-api-generator

- app/connector/gmail/pom.xml
- app/test/integration-test/src/test/java/io/syndesis/test/itest/gmail/WebhookToGMail_IT.java
- app/test/integration-test/src/test/resources/io/syndesis/test/itest/gmail/webhook-to-gmail-export/model-info.json
- app/test/integration-test/src/test/resources/io/syndesis/test/itest/gmail/webhook-to-gmail-export/model.json
This reverts the upgrade of `com.google.apis:google-api-services-gmail`
which was causing a runtime exception at the integration startup:
```
Caused by: java.lang.NoSuchMethodError: com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient$Builder.setBatchPath(Ljava/lang/String;)Lcom/google/api/client/googleapis/services/AbstractGoogleClient$Builder;
at com.google.api.services.gmail.Gmail$Builder.setBatchPath (Gmail.java:9868)
at com.google.api.services.gmail.Gmail$Builder.<init> (Gmail.java:9847)
```
Also adds a integration test that only checks if the integration can be
started, as we have no way of stubbing the www.googleapis.com endpoint
that will be contacted otherwise.
Ref. https://issues.jboss.org/browse/ENTESB-12192
> fix: revert `google-api-services-gmail` upgrade

- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/DataShapeGenerator.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/UnifiedJsonDataShapeSupport.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/UnifiedXmlDataShapeSupport.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/Oas20ModelHelper.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/UnifiedJsonDataShapeGenerator.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/UnifiedXmlDataShapeGenerator.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ModelHelper.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/UnifiedJsonDataShapeGenerator.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/UnifiedXmlDataShapeGenerator.java
- app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v2/UnifiedXmlDataShapeGeneratorShapeValidityTest.java
Parameter defined as "in body" has been replaced by requestBody element in OpenAPI 3.x so we need to add specific logic to extract body schemas when working on OpenAPI 3.x
> fix(ENTESB-12218): Fix request body extraction for OpenAPI 3.x

- app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvMetricsContainer.tsx
- app/ui-react/packages/ui/stories/Data/Matrics/MatricsTab.stories.tsx
- Jira Issue https://issues.jboss.org/browse/TEIIDTOOLS-850.
- With this PR added the Empty state view for Matrics tab and added the story for Matrics.
- Screenshot
> fix: add EmptyState for the virtualization metrics display

- app/ui-react/packages/ui/src/Data/Virtualizations/Details/VirtualizationDetailHistoryTable.tsx
- app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationDetailHistoryTable.stories.tsx
- app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationDetailsPage.tsx
- see [TEIIDTOOLS-858 - Virtualization versions table - kebab actions should be justified to right](https://issues.jboss.org/browse/TEIIDTOOLS-858)
- see [TEIIDTOOLS-863 - Fix web console errors on virtualization details tab](https://issues.jboss.org/browse/TEIIDTOOLS-863)
- see [TEIIDTOOLS-864 - Fix VirtualizationDetailHistoryTable story](https://issues.jboss.org/browse/TEIIDTOOLS-864)
- added `aria-label` to version details `Table` to get rid of console log messages
- added format classes to each of the version details columns to move kebab to the right
- removed unneccessary `PageSection` and `Stack` from `VirtualizationDetailHistoryTable`
- in story, removed unused import and changed `historyItems` from fragment to div
> fix(TEIIDTOOLS-858, 863, and 864) - Changes to virtualization versions table layout and story

- app/ui-react/packages/ui/src/Shared/UnrecoverableError.tsx
- app/ui-react/packages/ui/stories/Shared/UnrecoverableError.stories.tsx
- app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
- app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ActionDescriptorFetchError.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
- app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
- app/ui-react/syndesis/src/shared/ApiError.tsx
fixes [ENTESB-11444](https://issues.jboss.org/browse/ENTESB-11444)
I also fixed the refresh button for the generic API error component that's used everywhere else.
> feat: better error page for the action configuration form when the connection is misconfigured

- app/ui-react/packages/ui/src/Layout/PfVerticalNavItem.tsx
- app/ui-react/syndesis/config.minishift.json
- app/ui-react/syndesis/config.proxy.json
- app/ui-react/syndesis/config.staging.json
- app/ui-react/syndesis/src/app/UI.tsx
- app/ui-react/syndesis/src/app/WithConfig.tsx
relates to [ENTESB-11500](https://issues.jboss.org/browse/ENTESB-11500)
This can be used to hide the "Extensions" nav item as needed, or any other item in the nav bar.  Note that this currently only works for the main navigation but this can be further built upon as needed to hide other elements as needed.
It's driven by the `features` attribute in the `config.json` file and I've added some examples:
The key name corresponds to the module name, i.e. "extensions" here is compared to the URL that the navigation item has for it's route.  So to hide the link to a section of the app you look at the URL bar, for example "extensions":
That's the key you'd use in the `features` map.  And it won't blow up if these keys aren't present.
Oh, and also the "logging" entry that's being removed from the …
> feat: add a mechanism to hide top-level nav items

- app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationActions.tsx
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
- see [TEIIDTOOLS-856](https://issues.jboss.org/browse/TEIIDTOOLS-856)
- it was determined in the meeting today that the revert action should never be shown in the breadcrumb actions
- added ability to add icons to `IVirtualizationAction`
- modified logic of `VirtualizationUtils.canRevert` so that it returns `false` if there is no revision passed in
- changed revert action in `VirtualizationActionContainer` to have an icon
> fix(TEIIDTOOLS-856) - Revert button/action does not display for virtualizaton running - modified

- app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
- see [TEIIDTOOLS-867](https://issues.jboss.org/browse/TEIIDTOOLS-867)
- if view name has non-alphanumeric characters the view name is wrapped in double quotes before requesting the preview results
> fix(TEIIDTOOLS-867) - Preview query fails when view name has a dash

- app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
- see [TEIIDTOOLS-862](https://issues.redhat.com/browse/TEIIDTOOLS-862)
- this is the UI work
- added optional revision parameter to `useVirtualizationHelpers.exportVirtualization`
- changed output zip file name to reference reference version if revision parameter was passed in
- changed `VirtualizationActionContainer` to pass revision to the export action
> fix(TEIIDTOOLS-862) - Export action only exports latest version

- app/pom.xml
We need to manually bump the AWS SDK library version in order to be aligned with the rest of libraries brought in by camel-aws component.
Closes ENTESB-12416
> fix(connector/aws): align sdk version

- app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
- Jira Issue https://issues.redhat.com/browse/TEIIDTOOLS-873
- With this PR 
--Removed the Version.
--Removed the Modified badge.
--Showing the 'Used by Integration' message only if it is used in an integration.
- Screenshot.
> fix: rework VirtualizationListItem

- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiSecurityScheme.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiValidationRules.java
- app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v2/Oas20ValidationRulesTest.java
- app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRulesTest.java
Also allow "http" alias for basic auth when validating an OpenAPI spec.
> fix(ENTESB-12218): Fix OpenAPI auth validation rules

- app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrievalTest.java
- app/connector/salesforce/src/test/java/io/syndesis/connector/salesforce/SalesforceMetadataRetrievalTest.java
- app/connector/support/verifier/pom.xml
- app/connector/support/verifier/src/main/java/io/syndesis/connector/support/verifier/api/MetadataRetrieval.java
- app/connector/support/verifier/src/main/java/io/syndesis/connector/support/verifier/api/SyndesisMetadata.java
- app/connector/support/verifier/src/main/java/io/syndesis/connector/support/verifier/api/SyndesisMetadataProperties.java
- app/connector/support/verifier/src/test/java/io/syndesis/connector/support/verifier/api/ConnectorMetadataTest.java
- app/connector/support/verifier/src/test/java/io/syndesis/connector/support/verifier/api/sample/SampleConnectorMetaDataRetrieval.java
- app/meta/src/main/java/io/syndesis/connector/meta/v1/ConnectorEndpoint.java
- app/meta/src/test/java/io/syndesis/connector/meta/v1/ActionDefinitionEndpointTest.java
- app/meta/src/test/java/io/syndesis/connector/meta/v1/PetstoreMetadataRetrieval.java
- app/server/endpoint/pom.xml
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorPropertiesHandler.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandlerTest.java
Goal of this PR is to expose a REST API that will be used by connection user interface to dynamically expose any connection property that can be retrieved dynamically by the connector.
During this first iteration I am leaving aside the resiliency of the meta http call from server: it will be provided during a following iteration ([ENTESB-12498](https://issues.redhat.com/browse/ENTESB-12498))
Originally required by #2828 
Needed to enable product feature [ENTESB-11952](https://issues.redhat.com/browse/ENTESB-11952)
> Dynamic connection properties retrieval

- app/test/integration-test/src/test/java/io/syndesis/test/itest/gmail/WebhookToGMail_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/googlecalendar/WebhookToGoogleCalendar_IT.java
Spring Boot 2.x uses a different health actuator endpoint.
> fix: Fix integration runtime health checks in nightly integration tests

- install/operator/pkg/syndesis/action/install.go
Operator CircleCi builds on master are broken because of this.
> fix(ENTESB-12222): Fixed operator build on CircleCi

- app/connector/kafka/pom.xml
- app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaMetaDataRetrieval.java
This takes the kubernetes configuration from the environment and tries to discover brokers. All plain discoverable brokers will be passed to the Kafka connector to auto-populate some suggestion dropdown box.
This needs some manual tweaking on privileges as the default environment user does not have privileges to discover any broker. Will just return an empty list.
> [ENTESB-12331] Adding auto-discovery for strimzi kafka/AMQ brokers

- app/test/integration-test/src/test/java/io/syndesis/test/itest/amq/AMQToHttp_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/http/HttpToHttp_IT.java
- app/test/test-support/src/main/java/io/syndesis/test/SyndesisTestEnvironment.java
- app/test/test-support/src/main/java/io/syndesis/test/container/integration/SyndesisIntegrationRuntimeContainer.java
Use maven.repo.local property instead of settings.localRepository to set the local Maven repository for integration runtime container.
> fix: Fixed nightly integration tests on CircleCi

- .mvn/extensions.xml
- app/.mvn/extensions.xml
- app/.mvn/maven.config
Seems that we were missing the setup for the maven-buildtime-extension.
The intent was there to configure, the configuration wasn't applied as
the `.mvn` directory was at the wrong level and the property needed to
configure it was missing.
Now timing information for each plugin/module will be printed to stdout.
> chore(build): setup maven-buildtime-extension

- app/connector/kafka/src/main/resources/META-INF/syndesis/connector/kafka.json
We're using new capabilities of Patternfly to have auto-complete
dropdowns, for that the `type` of the property needs to be `typeahead`.
This is added to the Kafka connector so when a Kafka connection is
created we can utilize the Strimzi discovery via the `syndesis-meta`.
> chore(c/kafka): change brokers type to `typeahead`

- .circleci/config.yml
In an effort to stabilize the operator (golang) build this configures
the use of proxy.golang.org for the operator build on CircleCI.
> chore(build): enable proxy.golang.org

- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiValidationRules.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/Oas20ValidationRules.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ModelHelper.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ParameterGenerator.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30PropertyGenerators.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRules.java
- app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30ParameterGeneratorTest.java
- app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRulesTest.java
Validate the specified server URLs share the same base path for OpenAPI 3.x APIs provided by Syndesis.
OpenAPI 3.x is able to specify multiple servers with host URLs. Validates that the specified server URLs share the same base path. Generated REST endpoint can only use one single base path and in case there are differing base paths defined in server URLs we raise a warning.
> fix(ENTESB-12218): Add OpenAPI 3.x specific validation rule

- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiValidationRules.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/Oas20ValidationRules.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30DataShapeGeneratorHelper.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30FormDataHelper.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ModelHelper.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ParameterGenerator.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30PropertyGenerators.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRules.java
- app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30DataShapeGeneratorHelperTest.java
- app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30ParameterGeneratorTest.java
- app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRulesTest.java
Based on PR #7455 
OpenAPI 3.x adds global reusable parameter definitions that can be referenced in the OpenAPI specification. We need to resolve the parameter references when extracting all operation parameters.
> fix(ENTESB-12218): Add support for OpenAPI 3.x global parameter definitions

- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/util/ReflectionUtils.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/util/ReflectiveSorterTest.java
This changes the `ReflectionUtils` to include all methods available on a
class rather than the methods that are declared on a class. This will
help in finding the `getVersion` method on `Integration` interface.
Fixes #7471
> fix(endpoint): all methods for reflective sorting

- app/.mvn/maven.config
The buildtime Maven extension generates a long list of plugin execution
times at the end ov Maven execution. When an error is reported in the
build it's followed by this long list of build plugin timings. This
makes it cumbersome to scroll to the error.
This makes the buildtime extension opt-in, i.e. to activate the
extension `-Dbuildtime.output.log=true` must be specified.
> chore(build): make buildtime extension opt-in

- doc/modules/customizing/r_develop-connector-extensions.adoc
In the user doc in Integrating Applications with Fuse Online, where it provides an overview of developing a connector extension, I added a link to the doc on the Syndesis community web site that describes in detail how to develop a connector.
> user doc: Add xref to Syndesis community doc for developing connectors

- app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
- app/server/openshift/src/test/java/io/syndesis/server/openshift/OpenShiftServiceImplTest.java
When deleting an integration the `Build` would be left over preventing
the future integration with the same name, and hence the same `Build`
name to be built and started. This makes sure that the deletion of
`BuildConfig` is propagated explicitly by using `Foreground`[1]
cascading deletion.
Ref. https://issues.redhat.com/browse/ENTESB-12493
[1] https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#foreground-cascading-deletion
> fix(openshift): cascade `BuildConfig` deletion

- app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
- app/server/openshift/src/test/java/io/syndesis/server/openshift/OpenShiftServiceImplTest.java
fix(openshift): cascade `BuildConfig` deletion
(cherry picked from commit 61cac5f17e308329642c9e40b825359e88c7a048)
> fix(openshift): cascade `BuildConfig` deletion (#7452)

- app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
- app/ui-react/packages/models/src/dv.d.ts
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionListView.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
- app/ui-react/syndesis/src/modules/data/shared/ConnectionTables.tsx
- Jira issue https://issues.redhat.com/browse/TEIIDTOOLS-900
- With this PR now we are also showing the column details for selected tables.
- Geeting the column details for /metadata/runtimeMetadata/{virtualizationName} 
- Screenshot
> fix: Show the column details for selected tables

- app/s2i/pom.xml
When the Maven build is run with `settings.xml` that contains mirror
configuration such that it mirrors every repository, i.e. the
settings.xml contains `<mirrorOf>*</mirrorOf>`, it'll be patched to
exclude `local-repository`, i.e. that setting would be changed to
`<mirrorOf>*,!local-repository</mirrorOf>`.
> chore(build): patch mirrorOf to exclude local-repository

- app/server/endpoint/pom.xml
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorPropertiesHandler.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandlerTest.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorPropertiesHandlerTest.java
This fixes and refactors connector properties fetching from the meta
pod. I've found the implementation to be overly optimistic and incorrect
in assumptions. As it was, any error from the meta pod would be
converted to a HTTP successful response and no error handling would be
performed. This would lead to issues when the meta pod would respond
with an error and the an attempt to parse the response to the expected
format would result in errors like `NullPointerException`.
Also adds the missing tests.
Fixes #7504
> fix: connector properties fetching

- app/ui-react/packages/auto-form/src/widgets/FormTypeaheadComponent.tsx
patternfly-react doesn't seem to allow us to have one value displayed
and another value bound/kept as value. That means that our `enum`
`label/value` can't be used as we intended: to have the `label`
displayed and to have the `value` kept as `configuredProperty`. So this
simply displays the `value` from the `enum` instead, which will make
that value bound to `configuredProperty` as well.
> fix(ui): `value` instead of `label` in typeahead

- app/pom.xml
- app/s2i/pom.xml
- app/ui-react/pom.xml
When we build downstream we need the archives from the `s2i` (the
repository) and `ui-react` (distribution archive) need to be deployed to
the Maven repository. This was removed for the `ui-react` in #7022.
This refactors this by reintroducing (opt-in) the archive deployment via
`deploy.archives` Maven property (i.e. `-Ddeploy.archives=true`), or
individually via `deploy.s2i.repository` and `deploy.ui.distribution`.
(cherry picked from commit 56a0145005a1b47ba2dd9faead2d018ba7d573b9)
Backport of #7554
> refactor: archive deployment configuration

- doc/modules/connecting/p_adding-mongodb-connections-read.adoc
- doc/modules/connecting/p_obtaining-email-to-trigger-integration-execution.adoc
- doc/modules/tutorials/p_register-with-twitter.adoc
Translation of the connector guide uncovered two typos and a very confusing sentence. I corrected these issues.
> user doc: Fix two typos and clarify one sentence.

- app/s2i/pom.xml
- app/ui-react/pom.xml
This changes the Maven configuration to remove the
`deploy.s2i.repository` and `deploy.ui.distribution` and instead rely on
the `deploy.archives` property. Which in turn activates the
`deploy-archives` profiles that include the assembly and deployment
Maven plugin configuration.
To build and deploy the build configuration needs to specify the
`-Ddeploy.archives=true` via command line, that way it's a system
property and it can activate the `deploy-archives` profile.
> refactor(build): archive deployment profile

- doc/assemblies/connecting/as_connecting-to-amazon-dynamodb.adoc
This just removes the conditionalized note that says the DynamoDB connector is a Technology Preview feature. Maria tells me that no other updates to the doc for the DynamoDB connector are needed for 7.6.
> user doc: Remove Tech Preview note for DynamoDB connector

- app/ui-react/packages/models/src/dv.d.ts
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
fix issue with initialization of virtualization status when transitioning between pages
- added 'modified' and 'version' attributes to VirtualizationPublishingDetails model
- VirtualizationEditorPages now uses routeState virtualization if available
> TEIIDTOOLS-899 fix virtualization status init issue with VirtualizationEditorPage

- doc/assemblies/connecting/as_connecting-to-box.adoc
- doc/modules/connecting/p_adding-box-connection-finish.adoc
- doc/modules/connecting/p_adding-box-connection-middle.adoc
- doc/modules/connecting/r_how-to-specify-the-schema-in-a-database-connection.adoc
For the 7.6 user doc for the Box connector, I removed the Tech Preview note, and I updated the description of the file name specification when uploading a file to Box. Claudio reviewed these updates. 
In an unrelated file, I removed a Tech Preview note about data virtualization, so I wouldn't forget to do it.
> user doc: update Box connector doc

- app/meta/src/main/java/io/syndesis/connector/meta/v1/V1.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/V1Application.java
This is a dirty fix to circumvent "clever" classpath scanning from
`swagger-jaxrs` that fails on Reflections tripping over closing a
directory in a JAR file which in turn closes the whole JAR file stream
and prevents the further scanning and fails the app startup.
A proper fix is upgrading to the 2.x line of `swagger-core` which
doesn't rely on Reflections to do classpath scanning.
Ref #7556
> fix: server/meta startup

- app/ui-react/packages/api/src/index.ts
- app/ui-react/packages/api/src/useVirtualizationRuntimeMetadata.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.css
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
- app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaList.stories.tsx
- app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaListItem.stories.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
- app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Resolving issues TTOOLS-837, TTOOLS-835, ENTESB-12364
Modify the SelectSourcesPage (first page of the CreateView wizard) to correct issues with display of connections and refresh of the connection schema.  The connections shown on the createView and importViews wizards were not consistent, and the schema in the createView wizard was not updating correctly
- adds 'useVirtualizationRuntimeMetadata' - allows usage of hook with polling interval
- 'SelectSourcesPage' now utilizing hooks to obtain the connections/dvSourceStatus/schema.  info is supplied to ConnectionSchemaContent
- 'ConnectionSchemaContent' now utilizes the Connection/status info to include the connection status
- 'ConnectionListItem' was improved to display the appropriate connection type icon / status / loading indicators
- …
> TEIIDTOOLS-837 fix connection display with Create View Wizard

- app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlSupport.java
- app/connector/sql/src/main/java/io/syndesis/connector/sql/db/DbPostgresql.java
- app/connector/sql/src/test/java/io/syndesis/connector/sql/stored/SqlStoredConnectorMetaDataExtensionTest.java
When fetching the list and input/output parameters of stored procedures
we're relying on `java.sql.DatabaseMetaData`.
For PostgreSQL database instead of the `DatabaseMetaData::getProcedures`
we were using `DatabaseMetaData::getFunctions`, this, by standard should
return `FUNCTION_NAME` and `FUNCTION_TYPE` columns. For other databases
we're using `DatabaseMetaData::getProcedures` returning `PROCEDURE_NAME`
and `PROCEDURE_TYPE` columns.
For all databases we're trying to read `PROCEDURE_NAME` and
`PROCEDURE_TYPE` columns, regardless of the `ResultSet`'s origin:
`DatabaseMetaData::getFunctions` or `DatabaseMetaData::getProcedures`.
The issue reported was caused by the missing `PROCEDURE_NAME` column for
the PostgreSQL database. So seemingly the
`DatabaseMetaData::getFunctions` for PostgreSQL …
> fix(c/sql): use standard column names

- package.json
Seems that in the Husky upgrade the hooks interact with the shell, and
that the shell expansion is now in place. That is, running the
pre-commit hook would fail with an error like:
"zsh:1: no matches found: pre-commit:*"
This simply adds quotes around the hooks so the arguments for
`npm-run-all` are taken verbatim and not expanded by the shell.
Also it seems that the `git add` is no longer required so this removes
it.
> fix(tools): fix pre-commit configuration

- app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlSupport.java
- app/connector/sql/src/main/java/io/syndesis/connector/sql/db/DbPostgresql.java
- app/connector/sql/src/test/java/io/syndesis/connector/sql/stored/SqlStoredConnectorMetaDataExtensionTest.java
fix(c/sql): use standard column names
(cherry picked from commit 3b77647d06e611abaf675495d4b6bde5c1c1166f)
> fix(c/sql): use standard column names (#7591)

- app/connector/rest-swagger/pom.xml
- app/connector/rest-swagger/src/main/resources/META-INF/syndesis/connector/rest-swagger.json
- app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/DescriptorTest.java
- app/server/api-generator/src/test/resources/openapi/v2/basic_auth.unified_connector.json
- app/server/api-generator/src/test/resources/openapi/v2/complex_xml.unified_connector.json
- app/server/api-generator/src/test/resources/openapi/v2/damage_service.unified_connector.json
- app/server/api-generator/src/test/resources/openapi/v2/kie-server.unified_connector.json
- app/server/api-generator/src/test/resources/openapi/v2/machine_history.unified_connector.json
- app/server/api-generator/src/test/resources/openapi/v2/petstore.unified_connector.json
- app/server/api-generator/src/test/resources/openapi/v2/petstore_xml.unified_connector.json
- app/server/api-generator/src/test/resources/openapi/v2/reverb.unified_connector.json
- app/server/api-generator/src/test/resources/openapi/v2/todo.unified_connector.json
- app/server/api-generator/src/test/resources/openapi/v3/basic_auth.unified_connector.json
- app/server/api-generator/src/test/resources/openapi/v3/complex_xml.unified_connector.json
- app/server/api-generator/src/test/resources/openapi/v3/damage_service.unified_connector.json
- app/server/api-generator/src/test/resources/openapi/v3/kie-server.unified_connector.json
- app/server/api-generator/src/test/resources/openapi/v3/machine_history.unified_connector.json
- app/server/api-generator/src/test/resources/openapi/v3/petstore.unified_connector.json
- app/server/api-generator/src/test/resources/openapi/v3/petstore_xml.unified_connector.json
- app/server/api-generator/src/test/resources/openapi/v3/reverb.unified_connector.json
- app/server/api-generator/src/test/resources/openapi/v3/todo.unified_connector.json
- app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoOpenApiV2Connector-export/model.json
- app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoOpenApiV3Connector-export/model.json
Used to have camel-rest-openapi as compile time dependency as workaround for ENTESB-12545 As ENTESB-12545 has been fixed we do not need this workaround in Syndesis anymore.
Relates to ENTESB-12218
> fix(ENTESB-12545): Revert workaround due to missing camel-rest-openapi in Camel BOMs

- app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/customizer/DDBConnectorCustomizer.java
- app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/util/Util.java
- app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBConfiguration.java
- app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBGenericOperation.java
- app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBInsertTwiceTest.java
Bug fix: the variable parameters of the connector were stored on the main properties of the connector instead of being really variable.
> [ENTESB-12774]  The AWS dynamo db connector seems to be unable to insert multiple items into the ddb table.

- app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/customizer/DDBConnectorCustomizer.java
- app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/util/Util.java
- app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBConfiguration.java
- app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBGenericOperation.java
- app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBInsertTwiceTest.java
Backport of #7647 
Bug fix: the variable parameters of the connector were stored on the main properties of the connector instead of being really variable.
> [ENTESB-12774] 1.9.x backport of #7647

- app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorForm.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/step/ConfigureStepPage.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
This PR fixes the bug that allows users to replace the API provider step when creating an integration.
- [Reference Jira](https://issues.redhat.com/browse/ENTESB-12352)
> fix(ENTESB-12352) api provider integration step can be replaced

- app/test/integration-test/src/test/java/io/syndesis/test/itest/amq/HttpToAMQ_IT.java
- Try to fix flaky tests by increasing the timeout settings on mocked Http server
[ci skip]
> fix: Stabilize nightly integration tests

- .circleci/config.yml
- app/test/integration-test/pom.xml
- app/test/integration-test/src/test/java/io/syndesis/test/itest/amq/AMQToHttp_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/amq/HttpToAMQ_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/ftp/FtpSplitToDB_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/ftp/FtpToDB_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/http/HttpToHttp_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/mail/SendMail_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/GoogleSheetsTestSupport.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/sql/DBToHttp_IT.java
- app/test/test-support/src/main/java/io/syndesis/test/SyndesisTestEnvironment.java
- tools/bin/commands/integration-test
Integration tests are flaky on CircleCi because of message receive timeouts
- Use default timeout setting for all mocked server components
- Make default timeout settable via system properties
- Add default message timeout setting on syndesis CLI
- Increase timeout setting for CircleCI build jobs to 180s
> fix: Increase default message timeout for integration tests

- doc/assemblies/customizing/as_developing-rest-api-client-connectors.adoc
- doc/assemblies/tutorials/as_amq2api-intro.adoc
- doc/modules/integrating-applications/c_how-it-works.adoc
- doc/modules/integrating-applications/c_overview-benefit-api-provider-integrations.adoc
- doc/modules/integrating-applications/p_create-api-provider-integration.adoc
- doc/modules/integrating-applications/r_access-token-strategy.adoc
- doc/modules/integrating-applications/r_alternatives-for-triggering-integration-execution.adoc
- doc/modules/integrating-applications/r_requirements-for-api-provider-integrations.adoc
- doc/modules/tutorials/p_amq2api-create-rest-api-connector.adoc
- doc/modules/tutorials/p_amq2api-upload-todo-app-icon.adoc
- doc/modules/tutorials/p_sf2db-confirm-works.adoc
This content is ready to merge.  Updates made to address the OpenAPI 3 support and changing "swagger" to "openapi". 
Google doc summary is here: https://docs.google.com/document/d/1ode8pCv03iiNCoGzOGvYIV6N9KLo87HZX5UH56XQCno
> user doc: Updates for OpenAPI 3 support

- app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
- Jira issue https://issues.redhat.com/browse/TEIIDTOOLS-919
- With this PR for rendering the Virtualization header, when we reload the `VirtualizationEditorPage` component we check if `currPublishedState` is set to the default value then we use the `props.routeState.virtualization`.
- screenshot
> Fix: virtualization state not geting updated

- app/server/runtime/src/main/resources/application.yml
Deleting an entity from the database causes notification to be sent to
the UI, upon which the UI tries to reload that entity causing a HTTP 404
error in that case. I have perceived this as the majority of cases when
`EntityNotFoundException` is thrown and logged.
These log messages add no value as they could be caused by any recently
deleted and then re-fetched entity in the database.
This removes logging from the `EntityNotFoundExceptionMapper` solely
responsible for those exceptions being logged.
> refactor(server): do not log 404 errors

- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRules.java
Unsupported features warnings are valid for both consumed and provided APIs in Syndesis.
> fix(ENTESB-12793): Add unsupported OpenAPI 3.x feature warnings for provided APIs

- app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarEventModel.java
- app/connector/google-calendar/src/test/java/io/syndesis/connector/calendar/GoogleCalendarEventModelTest.java
- app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/AuthenticationCustomizerTest.java
Need to enhance Google calendar datetime model representation with seconds in order to meet Rfc3339 standard in newer versions of google-http-client.
Fixes ENTESB-12856
> fix(ENTESB-12856): Enhance Google calendar date time with seconds of hour

- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRules.java
Manual backport #7745 
Unsupported features warnings are valid for both consumed and provided APIs in Syndesis.
> [Backport-1.9.x]: Add unsupported OpenAPI 3.x feature warnings for provided APIs

- app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarEventModel.java
- app/connector/google-calendar/src/test/java/io/syndesis/connector/calendar/GoogleCalendarEventModelTest.java
Event model was using date field instead of date time field in Google event API.
> fix(ENTESB-12856): Set Google calendar date time field properly

- app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
Backport to 1.9.x - 
Fix: route param being directly used without resolving value
> DV backport for TEIIDTOOLS-924

- tools/bin/commands/release
This uploads the `syndesis-cli.zip` file to the GitHub release making it
easier to download the content of the `tools/bin` directory associated
with a release.
> feat(release): upload the syndesis-cli to GitHub

- doc/assemblies/connecting/as_connecting-to-aws.adoc
- doc/modules/connecting/p_creating-amazon-dynamodb-connections.adoc
- doc/modules/connecting/p_obtaining-aws-credentials.adoc
I updated the name of the connector to "Amazon DynamoDB".
I ensured that the link to the section about obtaining AWS credentials is correct.
I reordered the sections to put the DynamoDB content first since it is alphabetically first as far as service names.
> user doc: Updates to doc for DynamoDB connector based on comments from Tomas

- doc/assemblies/integrating-applications/as_mapping-data.adoc
- doc/modules/integrating-applications/p_add-data-mapping-step.adoc
- doc/modules/integrating-applications/p_map-one-source-field-to-one-target-field.adoc
Matej Kralik identified a problem where a data mapper source field might not contain data. We agreed to add a troubleshooting tip to the doc to check the incoming payload to make sure that the field you are mapping to contains what you expect. Matej and Fintan approved the wording. The note is in three different places.
> user doc: Add note about source fields in data mapper - might not contain data

- app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorNothingToConfigure.tsx
- app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorNothingToConfigureAlert.tsx
- app/ui-react/packages/ui/src/Integration/Editor/index.ts
- app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/NothingToConfigure.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
- app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
fixes [ENTESB-12888](https://issues.redhat.com/browse/ENTESB-12888)
This also adds the same message for the split step as it also doesn't currently have configuration either.
@claudio4j FYI
> fix: If a step has no configurable properties, show that and don't error out

- install/operator/pkg/syndesis/backup/backup_test.go
Test passes locally and on circleci but fails on jenkins so shoring up to be more robust.
> fix: failing operator backup test

- .circleci/config.yml
There were two blocks doing apt get/install, I don't think it should be necessary to explicitly list all of those packages.
> chore: clean up UI prerequisite commands to minimize naming explicit packages

- app/test/integration-test/src/test/java/io/syndesis/test/itest/amq/AMQToHttp_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/amq/HttpToAMQ_IT.java
Nightly integration tests were failing for quite some time because of a Http request timeout in the Http-to-AMQ tests. I boiled this down to the integration runtime container wait strategy not being able to wait for the AMQ testcontainer to be pulled and started. Therefore the test logic started way too early (while container images still being pulled) and a Http request timeout causes the tests to fail.
Now using a static initializer for AMQ testcintainer instead of the @ClassRule
> chore: Fix integration tests to not wait for other containers to start

- app/connector/google-sheets/pom.xml
- app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/CustomGoogleSheetsVerifierExtension.java
- app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsVerifier.java
New Google API version returns a 404 error when the spreadsheet ID is not valid. Now we make sure that is not a validation error. A validation error will pop up when credentials are wrong (or some other unexpected issue).
> [ENTESB-11725] For Master: Google Sheets Validation was broken

- .circleci/config.yml
Since I see the same error is occuring for that branch of course.
> chore: clean up UI prerequisite commands to minimize naming explicit packages (on 1.9.x)

- app/test/integration-test/src/test/java/io/syndesis/test/itest/amq/AMQToHttp_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/amq/HttpToAMQ_IT.java
AMQ testcontainer was failing because of latest changes introducing duplicate initializing of the same container. Revert changes to using a JUnit ClassRule in combination with introducing dependsOn dependency so integration runtime container waits for the AMQ container to start properly.
> fix: Integration tests in nightly build

- install/operator/pkg/syndesis/backup/backup_test.go
* Test is too fragile depending on the platform it is executed on.
> BACKPORT fix: Removes deficient backup test

- app/ui-react/packages/ui/src/Integration/IntegrationFlowStep.tsx
- app/ui-react/packages/ui/src/Integration/IntegrationsEmptyState.tsx
new empty state for now:
I can't get the tooltip to capture, it's the one used in the unexpanded IVP like when looking at a data mapper step.
> chore: migrate integration flow step and integrations empty state

- tools/bin/commands/crc
- tools/bin/commands/dev
- tools/bin/commands/install
- tools/bin/commands/minishift
- tools/bin/commands/util/operator_funcs
Fix syndesis minishift install scripts to download syndesis-operator 2.x
when a tag is not specified
Enhance dev --cleanup removes dangling docker images
Enhance --full-reset also removes ~/.syndesis/bin/syndesis-operator
> Fix syndesis minishift install and dev --cleanup

- app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorListView.tsx
Epic: [ENTESB-12896](https://issues.redhat.com/browse/ENTESB-12896)
Drop `patternfly-react` (PF3) dependency to instead use `@patternfly/react-core` (PF4) stuffs in the `ApiConnectorListView` component.
Screenshot:
Includes:
- ListView => DataList
- Tooltip
- Empty state
- Icon, etc.
Note: Similar to https://github.com/syndesisio/syndesis/pull/7863 had some issues capturing the tooltip.
> chore: drop pf-react dep from ApiConnectorListView

- app/pom.xml
Seems that there are duplicate but different classes in
`javax.annotation:javax.annotation-api:1.3.2` vs
`org.jboss.spec.javax.annotation:jboss-annotations-api_1.2_spec:1.0.2.Final`.
This excludes the `javax.annotation:javax.annotation-api` as the JBoss
one seems to be used more.
Caveat, on `master` we have excluded both the javax ones and the JBoss
ones in favor of the Jakarta versions.
> fix(deps): exclude javax.annotation-api

- app/connector/google-sheets/pom.xml
- app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/CustomGoogleSheetsVerifierExtension.java
- app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsVerifier.java
New Google API version returns a 404 error when the spreadsheet ID is not valid. Now we make sure that is not a validation error. A validation error will pop up when credentials are wrong (or some other unexpected issue).
> [ENTESB-11725] For 1.9.x: Google Sheets Validation was broken

- app/ui-react/packages/api/src/useVirtualization.tsx
- app/ui-react/packages/models/src/dv.d.ts
- app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.css
- app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/models.ts
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationVersionsPage.tsx
- Backport for 1.9.x. These changes adapt the UI to changes on the DV backend to resolve virtualization publishing issues.
-model changes to add deployedState, deployedRevision, deployedMessage
-VirtualizationVersionsPage changes - the version table can now show published virtualization 
-version and in-progress virtualization simultaneously.
-PublishStatusWithProgress changed to utilize status label same as virtualizationListItem
> Teiidtools 943

- app/ui-react/packages/auto-form/package.json
- app/ui-react/packages/ui/package.json
- app/ui-react/syndesis/package.json
- app/ui-react/yarn.lock
This fixes `yarn build-storybook` by bringing in the polyfill that's needed with the version of babel being used.
> fix: make storybook work again by bringing in the right babel polyfill (1.9.x only)

- app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/customizer/DDBConnectorCustomizer.java
If no attributes were defined on the step, a NullPointer was thrown when customizing the variables.
> [ENTESB-12957] DynamoDB: No attributes to query throws NullPointer

- app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/customizer/DDBConnectorCustomizer.java
If no attributes were defined on the step, a NullPointer was thrown when customizing the variables.
Same as: #7883
> [ENTESB-12957] DynamoDB: No attributes to query throws NullPointer 

- app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorListItem.css
- app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorListItem.tsx
.. to drop patternfly-react usage, convert to functional component and use hooks.
Epic: [[ENTESB-12896] Migration from PF3 to PF4 for Fuse Online](https://issues.redhat.com/browse/ENTESB-12896)
> chore: migrate API connector list item

- doc/modules/tutorials/p_register-with-sf.adoc
This just updates two links so that the link text is consistent with the actual heading that it points to.
> user doc: Updated text in heading links to be consistent with the actual headings

- app/integration/bom/pom.xml
When building the image for an integration with Mongo, missing versino made it fail. 
Cherry picked from #7890
> fix(ENTESB-12960): Missing version placeholder.

- tools/bin/commands/build
The missing double quotes shows "install: missing file operand"
when invoking the syndesis build
> Fix Typo on EOT keyword build script

- tools/bin/commands/build
The missing double quotes shows "install: missing file operand"
when invoking the syndesis build
> Fix Typo on EOT keyword build script - 1.9.x

- app/ui-react/package.json
- app/ui-react/packages/history/.size-snapshot.json
- app/ui-react/yarn.lock
The stack trace on CI (when the UI fails to build for no obvious reason) comes up in a few search hits that linked to some bug fixes, it looked we were pulling in a kinda old version, this ensures we're not using a version from over a year ago.
> chore: force the version of terser to the current latest (4.6.3) to see if it sorts UI CI build issue

- install/operator/pkg/apis/syndesis/v1beta1/object.go
- install/operator/pkg/syndesis/backup/backup.go
* object.go
* Ensure all properties of syndesis are copied, ie. the ExternalDB
attribute.
* backup.go
* ExternalDatabase function must be called from configuration in order to
update the ...Database.URL attribute
* Fix incorrect constants used in backup that should be dependent on
target host
* Perform checks on backup file dump to see if it is empty
> ENTESB-12645: Fixes issues with scheduled backups of external database

- app/ui-react/packages/ui/src/Customization/extensions/ExtensionListItem.css
- app/ui-react/packages/ui/src/Customization/extensions/ExtensionListItem.tsx
- app/ui-react/packages/ui/src/Customization/extensions/ExtensionListView.tsx
Drops patternfly-react support from ExtensionListView + ExtensionListItem in favor of @patternfly/react-core. Other components from Extensions are missing, but coming up in a separate PR to keep reviewing easier.
EPIC: https://issues.redhat.com/browse/ENTESB-12896
> chore: Extensions List Migration

- .circleci/config.yml
- app/pom.xml
- app/ui-react/package.json
- app/ui-react/pom.xml
- app/ui-react/syndesis/craco.config.js
- app/ui-react/yarn.lock
Bumps yarn to the latest 1.x (1.22.0)
Also adds a workaround for https://github.com/facebook/create-react-app/issues/8320 to hopefully sort the terser error on CI.
Also skips the ui-doc job for now as it performs a second UI build but we don't currently do anything with the output.
> chore: bump yarn and add terser workaround

- test.py
This removes the javax/org.jboss.spec dependencies replaced with Jakarta
ones.
> chore: remove javax/org.jboss.spec dependency declarations

- app/ui-react/packages/history/.size-snapshot.json
- app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx
- app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailBreadcrumb.tsx
- app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.tsx
- app/ui-react/packages/ui/src/Integration/IntegrationStatus.tsx
- app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
- app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailHeader.tsx
Using the "default" color for stopped, "primary" for running and "danger" for error so at least there's different colors again:
Also fixed up the edit button in the detail header:
> chore: migrate some labels, revisit some label colors, migrate detail header dropdown

- app/ui-react/packages/ui/__tests__/Customization/ExtensionDetail.spec.tsx
- app/ui-react/packages/ui/package.json
- app/ui-react/packages/ui/src/Customization/extensions/ExtensionDetail.css
- app/ui-react/packages/ui/src/Customization/extensions/ExtensionDetail.tsx
- app/ui-react/packages/ui/src/Customization/extensions/ExtensionImportCard.tsx
- app/ui-react/packages/ui/src/Customization/extensions/ExtensionImportReview.tsx
- app/ui-react/yarn.lock
Epic: https://issues.redhat.com/browse/ENTESB-12896
This PR includes dropping `patternfly-react` (PF3) and adding support for PF4 for the following components:
- `ExtensionDetail`
- `ExtensionImportCard`
- `ExtensionImportReview`
Apologies in advance for some of the formatting changes, especially in `ExtensionImportReview`. 😅 
---
`ExtensionDetail`:
Alert for `ExtensionImportCard`:
`ExtensionImportReview`:
Tested with an extension that has no 'Actions' (e.g. Delay):
> chore: extensions list migration part II

- app/ui-react/packages/ui/src/Customization/extensions/ExtensionIntegrationsTable.tsx
- app/ui-react/packages/ui/stories/Customization/ApiConnectorListView.stories.tsx
- app/ui-react/packages/ui/stories/Customization/ExtensionIntegrationsTable.stories.tsx
**Epic**: https://issues.redhat.com/browse/ENTESB-12896
- Add a story for `ExtensionIntegrationsTable` component
- Drop `patternfly-react` support, migrate to `@patternfly/react-core` and `@patternfly/react-table`
- Remove annoying warning of React not supporting JS links in the future
**NOTE**: It's not currently possible to view this table other than in Storybook, so that's what the screenshots will be of.
**Before**
**After**
Some commments:
- I couldn't find anything in PF4 that had striped rows as an option.
- I used the 'compact' variant to make it look more like the current table.
- Lastly, it also seems it's not possible to omit the header row in the table, so it's there now, but the previous version looked weird with an empty header imo anyway.
> chore: drop pf-react support for extension integrations table

- doc/assemblies/customizing/as_developing-extensions.adoc
- doc/assemblies/integrating-applications/as_creating-integrations.adoc
- doc/modules/integrating-applications/c_description-of-constructs.adoc
- doc/modules/integrating-applications/c_workflow-overview.adoc
- doc/modules/integrating-applications/p_add-log-step.adoc
- doc/modules/integrating-applications/p_creating-api-connectors.adoc
- doc/modules/integrating-applications/p_deleting-extensions.adoc
- doc/modules/integrating-applications/p_importing-integrations.adoc
- doc/modules/integrating-applications/p_start-with-webhook-connection.adoc
- doc/modules/integrating-applications/p_viewing-integration-activity.adoc
- doc/modules/integrating-applications/r_alternatives-for-triggering-integration-execution.adoc
- doc/shared/attributes-links.adoc
Moving content around broke some cross-reference links that were identified by the localization folks. This fixes these out of date links.
> user doc: Updates to fix out of date links.

- .circleci/config.yml
Re-enables this build step and adjusts the link so the app works-ish.
> chore: bring back the ui-doc build step

- app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
deployment config of integrations are generated on syndesis-server,
so the JAEGER_ENDPOINT is extracted from ENV variable and set on
the generated integration
https://issues.redhat.com/browse/ENTESB-12570
> Set the JAEGER_ENDPOINT collector from ENV for integrations - 1.9.x

- app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
deployment config of integrations are generated on syndesis-server,
so the JAEGER_ENDPOINT is extracted from ENV variable and set on
the generated integration
https://issues.redhat.com/browse/ENTESB-12570
> Set the JAEGER_ENDPOINT collector from ENV for integrations

- app/ui-react/packages/api/src/constants.ts
- app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
Adding the web hook action as one that needs to display an error handling widget
> fix for ENTESB-11675 to add errorHandler field to the schema

- app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.css
- app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx
- app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionStatus.css
- app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionStatus.tsx
- app/ui-react/packages/ui/src/Data/DvConnection/index.ts
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.css
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
- app/ui-react/packages/ui/stories/Data/CreateViewWizard/ConnectionSchemaList.stories.tsx
- app/ui-react/packages/ui/stories/Data/CreateViewWizard/ConnectionSchemaListItem.stories.tsx
- app/ui-react/packages/ui/stories/Data/DvConnection/DvConnectionCard.stories.tsx
- app/ui-react/packages/ui/stories/Data/DvConnection/DvConnectionStatus.stories.tsx
- app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
- app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
- app/ui-react/syndesis/src/modules/data/shared/DvConnections.tsx
Implements requested changes from UX for the DV connection status.  The status error message is now shown in a popover  [ENTESB-12953](https://issues.redhat.com/browse/ENTESB-12953)
- created component 'DvConnectionStatus', which is now used in both the import views and create view wizards
- updated components to utilize DvConnectionStatus
- added / updated stories
> Improve DV connection status display

- app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.css
- app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientForm.css
- app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientForm.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationVersionsPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
Implement requested UX changes in [ENTESB-12898](https://issues.redhat.com/browse/ENTESB-12898)
- adjust vertical margin so that green check icon lines up better with virtualization name
- adjust padding around submit button on SqlClient page
- editor page actions - pulled publish action out of kebab menu and made it a secondary button so the upper right menu is more noticeable. The type for custom properties needed fix so that the custom properties could be applied properly.
> DV details page updates

- doc/modules/connecting/p_adding-amq-connection-finish.adoc
- doc/modules/connecting/p_adding-amq-connection-middle.adoc
- doc/modules/connecting/p_adding-amq-connection-start.adoc
- doc/modules/connecting/p_adding-amqp-connection-middle.adoc
- doc/modules/connecting/p_adding-amqp-connection-start.adoc
- doc/modules/connecting/p_adding-dropbox-connection-finish.adoc
- doc/modules/connecting/p_adding-dropbox-connection-middle.adoc
- doc/modules/connecting/p_adding-dropbox-connection-start.adoc
- doc/modules/connecting/p_adding-ftp-finish-middle-connection.adoc
- doc/modules/connecting/p_adding-ftp-start-connection.adoc
- doc/modules/connecting/p_adding-http-connections.adoc
- doc/modules/connecting/p_adding-irc-connection-receive.adoc
- doc/modules/connecting/p_adding-irc-connection-send.adoc
- doc/modules/connecting/p_adding-kafka-connection-finish-middle.adoc
- doc/modules/connecting/p_adding-kafka-connection-start.adoc
- doc/modules/connecting/p_adding-mongodb-connections-read.adoc
- doc/modules/connecting/p_adding-mqtt-connection-finish-middle.adoc
- doc/modules/connecting/p_adding-mqtt-connection-start.adoc
- doc/modules/connecting/p_adding-s3-connection-finish.adoc
- doc/modules/connecting/p_adding-s3-connection-middle.adoc
- doc/modules/connecting/p_adding-s3-connection-start.adoc
- doc/modules/connecting/p_calling-a-knative-service-from-a-simple-integration.adoc
- doc/modules/connecting/p_sending-messages-to-a-knative-channel.adoc
- doc/modules/connecting/p_subscribing-to-a-knative-channel-to-obtain-messages.adoc
- doc/modules/connecting/r_how-to-specify-the-schema-in-a-database-connection.adoc
- doc/modules/integrating-applications/p_configure-publish-api-provider-quickstart.adoc
- doc/modules/integrating-applications/p_try-api-provider-quickstart.adoc
When Stefan reviewed the new doc for enabling auto-discovery of Kafka brokers (AMQ Streams), he suggested adding a note to the doc that recommends that the user specify the connection's input/output type if they want to map fields. I added this note to all the instances of the procedure for specify the data type. 
I also update the description of how discovery in 3scale is set for API provider integrations. 
And I re-inserted the Tech Preview note for data virtualization. This note renders only downstream.
> user doc: Add note that recommends specifying data type

- app/common/model/src/main/java/io/syndesis/common/model/connection/ConfigurationProperty.java
- app/common/model/src/main/java/io/syndesis/common/model/connection/DynamicConnectionPropertiesMetadata.java
- app/common/model/src/main/java/io/syndesis/common/model/connection/WithDynamicProperties.java
- app/server/endpoint/pom.xml
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorPropertiesHandler.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/MetadataCommand.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/MetadataCommandAction.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/MetadataConnectionPropertiesCommand.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandlerTest.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorPropertiesHandlerTest.java
* Added circuit breaker instead of plain REST call to meta connection properties
* Refactored common-model to add dynamic metadata modeling
* Refactored MetadataCommand to be used as abstract base for MetadataCommandAction and MetadataConnectionPropertiesCommand
* Refactored unit test to use DynamicConnectionPropertiesMetadata instead of raw Response
* Removed useless pom dependencies
Closes ENTESB-12498
> feat(server): autodiscovery circuit breaker call

- app/ui-react/packages/ui/src/Data/Virtualizations/SqlResultsTable.tsx
This PR updates the rows definition for the `SqlResultsTable` component. The storybook entry now seems to run just fine without errors. I haven't yet tested this component within the app, looking into that now.
Should help close https://issues.redhat.com/browse/TEIIDTOOLS-898
> fix(table): adjust rows format for SqlResultsTable

- app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppExpanderBody.tsx
- app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppList.tsx
- app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppListItem.tsx
drops support for patternfly-react OAuth components, replace with @patternfly/react-core
related epic: [ENTESB-12896](https://issues.redhat.com/browse/ENTESB-12896)
> chore: upgrade pf for OAuth components

- install/operator/.lib.sh
CI builds the operator with docker mode and the code generator `./pkg/cmd/internal/install/generator` should be called at this point to generate the `pkg/cmd/internal/install/install_defaults.go`
> Call Go generator when using docker to build operator - 1.9.x

- app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorActionsListItem.tsx
- app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorChooseAction.tsx
- app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
- app/ui-react/syndesis/src/modules/integrations/components/editor/choice/SelectChoiceConfigModePage.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/SelectActionPage.tsx
- app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
I think we can save the text alignment for when we've removed patternfly-react and it's related stylesheet.
> chore: migrate action select list in the editor

- doc/modules/integrating-applications/r_available-transformations.adoc
It is expected that these transformations will be supported in the next release.
So I commented out the content rather than removing it.
> user doc: Comment out doc for unimplemented data mapper transformations.

- app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
- Jira issue https://issues.redhat.com/browse/TEIIDTOOLS-947
- Resolving the loading state in VirtualizationViewsPage component only after getting response form both "useVirtualization" and "useViewDefinitionDescriptors" API calls.
> Fix: Initial view creation in a bad state

- tools/bin/commands/release
When a snapshot release is run the version is set to X.Y.1-YYYYMMDD, the
1 patch version then is not semantically correct with the version that
will be released (X.Y.0). This changes the snapshot version to start
with a 0 patch version (X.Y.0-YYYYMMDD).
> fix(build): correct snapshot release version

- tools/bin/commands/release
Cleanup prereleases older than 40 days, one page at a time.
> Add cleanup to delete old prereleases

- app/meta/src/main/java/io/syndesis/connector/meta/EndpointMetricsFilter.java
Using a different name in order not to collide with the ones used by `server` pod.
Closes #8089
With the latest upgrade to Camel 3.1, probably because a new library update, it's not possible to register a meter with the [same name and different tags](https://github.com/syndesisio/syndesis/blob/master/app/server/runtime/src/main/java/io/syndesis/server/runtime/EndpointMetricsFilter.java#L66-L72). Actually `server` pod is already registering a meter, but with a different set of tags. Changing the name solves the problem, **but** I don't have visibility on the impact of such change. I don't know if those metrics are collected and if the name change is going to produce any disruptive change in any consumer.
> fix(meta): Prometheus resource name change

- tools/bin/commands/release
Instead of using `syndesisio/syndesis` this allows the detection of the
organization/repository based on the git remote origin or given
`--git-remote` (expected to be pointing to GitHub). Which is useful when
testing the release in a private repository without creating releases in
`syndesisio/syndesis`.
> chore(build): parameterize GitHub repository

- app/ui-react/packages/ui/src/Integration/Details/IntegrationActions.tsx
- app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailHistoryListViewItemActions.tsx
- app/ui-react/packages/ui/src/Integration/Details/IntegrationExposeVia.tsx
- app/ui-react/packages/ui/src/Integration/Details/IntegrationExposedURL.tsx
- app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx
- app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Epic: https://issues.redhat.com/browse/ENTESB-12896
> chore: upgrade pf for integration modal + dropdown components

- tools/bin/commands/release
The job syndesis-release-1.9.x-daily in ci.fabric8.org is failing for some builds, creating a tag with commits from master branch. For those builds that results in 1.9.x tags with commits from master it is observed the `publish_artifacts` function from `release` doesn't print any message or error, so I added some logging to see if it can help debug this problem. 
Related to #8024
> Add logging to syndesis release script

- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandlerTest.java
* Build the connector by replacing only dynamic properties
* Added a test to validate such behavior
Closes #8046
> fix(server): replace dynamic properties only

- app/dv/src/main/java/io/syndesis/dv/server/endpoint/MetadataService.java
- app/dv/src/main/java/io/syndesis/dv/server/endpoint/RestSyndesisSourceStatus.java
- app/dv/src/test/java/io/syndesis/dv/server/endpoint/RestSyndesisSourceStatusTest.java
- app/ui-react/packages/models/src/dv.d.ts
- app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
- app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
- app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
- app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
- app/ui-react/syndesis/src/modules/data/shared/ViewInfosContent.tsx
Resolve issue with syndesis connections that have spaces or other special chars in the names.
- add 'teiidName' to RestSyndesisSourceStatus so that the ui has access to the teiid name corresponding to the syndesis connection name
- utilize the connection teiidName in the ui for fetching and refreshing the source schema
> TEIIDTOOLS-960 Resolve issue with teiid source naming

- app/ui-react/packages/ui/package.json
- app/ui-react/packages/ui/src/index.css
- app/ui-react/syndesis/package.json
- app/ui-react/yarn.lock
fixes #8118
Turns out patternfly ships with it's own subset of icons, this brings back in fontawesome in the short term to sort views that directly use the fontawesome classes, for example:
> fix: install fontawesome free directly

- tools/bin/commands/release
When releasing a snapshot using `syndesis release --snapshot-release`
this deletes GitHub pre-releases and tags keeping up to 10 for each
snapshot tag.
So for 1.9 snapshot releases this will delete `1.9.0-YYYYMMDD` GitHub
pre-releases and tags, i.e. it will not affect any 1.8 snapshot
git tags or GitHub pre-releases.
A bit different than keeping last n days of snapshots as in #8087.
Created for discussion.
> chore(build): keep up to 10 snapshot

- app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizer.java
- app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizerTest.java
Null values are skipped according to the Google docs. This leads to invalid data in value ranges for update and append operation. Using empty String values to fill in gaps that were not mapped in data mapper or mapped as Null value.
> fix(#8125): Fix empty values handling in Google sheets

- app/ui-react/packages/ui/__tests__/Connection/ConnectionDetailsForm.spec.tsx
- app/ui-react/packages/ui/src/Connection/ConnectionDetailsForm.tsx
- app/ui-react/packages/ui/src/Connection/ConnectorNothingToConfigureAlert.tsx
- app/ui-react/packages/ui/src/Connection/index.ts
- app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorNothingToConfigureAlert.tsx
- app/ui-react/packages/ui/src/Shared/SyndesisAlert.tsx
- app/ui-react/syndesis/src/modules/connections/components/WithConnectorForm.tsx
- app/ui-react/syndesis/src/modules/connections/pages/ConnectionDetailsPage.tsx
- app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
fixes [ENTESB-13266](https://issues.redhat.com/browse/ENTESB-13266)
Relaxes the previous restriction that connectors have to have properties to guard
against NPE errors, adds an alert when a connector has no properties and updates
the existing "no properties" alert to use the SyndesisAlert wrapper
In the wizard:
Detail page:
> fix: guard against connectors that don't have properties

- app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizer.java
- app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizerTest.java
Manual backport of #8130 
Null values are skipped according to the Google docs. This leads to invalid data in value ranges for update and append operation. Using empty String values to fill in gaps that were not mapped in data mapper or mapped as Null value.
> [Backport-1.9.x]: Fix empty values handling in Google sheets

- tools/bin/commands/release
The version of Git we have on Fabric8 Jenkins nodes doesn't support
sorting in `git tag`. This uses `git for-each-ref` instead.
Solves this issue on the release build:
```
error: unknown option `sort=taggerdate'
```
> fix(build): support very old git version

- tools/bin/commands/release
The version of Git we have on Fabric8 Jenkins nodes doesn't support
`get-url` in `git remote get-url`. This uses `git config` instead.
Solves this issue on the release build:
```
curl: no URL specified!
```
> fix(build): support very old git version (2)

- app/ui-react/syndesis/src/app/App.test.tsx
for #8150
The test doesn't need to load the whole actual i18n framework, and it appears to be causing a problem for the nightly build.
> fix: swap out real i18n module with a dummy to help nightly build

- app/common/model/src/main/java/io/syndesis/common/model/integration/Flow.java
- app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationBase.java
- app/integration/api/src/main/java/io/syndesis/integration/api/IntegrationResourceManager.java
- app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java
- app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/ProjectGeneratorTest.java
* Providing the Flow the possibility to include a list of Dependencies
* Include the list of Flows dependencies into the Project generated from an Integration
Closes ENTESB-13246
> feat(integration): Enable Flows dependencies

- app/ui-react/packages/auto-form/src/widgets/FormLabelHintComponent.tsx
not sure if there's an issue open for it, but this PR fixes this:
after changes:
cc @gashcrumb
> fix weird button issue on connection detail page

- install/operator/pkg/syndesis/action/install.go
Lowering the log output might be the best, since the next iteration will find the route and the sa, leading to a desired result
Fixes https://issues.redhat.com/browse/ENTESB-11340
> [operator] lower log output for race condition

- tools/bin/commands/release
We need to `return 1` from functions in order for `set -e` to fail the
shell script. Added `-S` to `curl` invocations that had `--fail` in them
to print the error response.
Ref #8166
> fix(build): error handling in release command

- tools/bin/commands/release
Seems that on CI we're using git remote URLs not HTTP remote URLS, this
tries to support that. Should fix the snapshot releases that fail with:
```
curl: (6) Could not resolve host: origin; Unknown error
ERROR: Cannot create release on remote github repository. Check if a release with the same tag already exists.
```
Fixes #8166
> fix(build): git style remote in release command

- app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizer.java
The getOrDefault is not working when there is a key in the map with actual null value. So use Optional.ofNullable and make sure to handle null values and use empty String values instead.
Manual backport of #8178
> [Backport-1.9.x](#8125): Fix empty values handling in Google sheets

- tools/bin/commands/release
Even though the daily release passed, it did so due to poor error
handling. This should fix the error handling and the error that occurred
in the daily release.
For some reason (no error text so no way to know), fetching the version
from `pom.xml` via Maven failed. This uses the same `grep` based command
we use for incremental license format in `bin/misc/format-license.sh`
against the `app/pom.xml` to fetch the version instead of using Maven.
Should fix: `ERROR: Cannot extract version from app/pom.xml`
> fix(build): pom_version in release

- doc/modules/customizing/c_about-extension-definitions.adoc
- doc/modules/customizing/r_descriptions-of-user-interface-properties-in-extension-definitions.adoc
The user doc actually already said this. But there was a format glitch that obscured this. 
And now, the doc explicitly states that the toplevel "properties" attribute is required in the JSON description file of a connector extension. Stan approved this addition. Gary too.
> user doc: Make it crystal clear that the toplevel "properties" attribute is required

- app/ui-react/syndesis/src/modules/data/shared/ViewInfosContent.tsx
Resolves issue with loading of connection schema in the import views wizard.
- the teiid connection name is no longer passed into the service.  Now if the correct schema node is found, the list is set.
> TEIIDTOOLS-962 Resolve wizard issue with connection schema init

- tools/bin/commands/release
Turns out we were creating GitHub releases for `master` branch and then
force updating them to tag. This changes the process so we first push
the git tag and then create a GitHub release based off of the current
checked out commit.
Fixes #8024 (I hope finally)
> fix(build): release tagging

- app/dv/src/main/java/io/syndesis/dv/server/V1Constants.java
- app/dv/src/main/java/io/syndesis/dv/server/endpoint/MetadataService.java
- app/dv/src/test/java/io/syndesis/dv/server/endpoint/IntegrationTest.java
- app/dv/src/test/java/io/syndesis/dv/server/endpoint/MetadataServiceTest.java
- app/ui-react/packages/api/src/useVirtualizationConnectionSchema.tsx
- app/ui-react/packages/api/src/useVirtualizationConnectionStatuses.tsx
- app/ui-react/syndesis/src/modules/data/shared/ViewInfosContent.tsx
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Follow-up to TEIIDtOOLS-962.  Combines the schema service methods in MetadataService to make them consistent.
- removes the getSchema method and incorporates into getAllConnectionSchema so that returned schema structures are the same.  Renamed getAllConnectionSchema to getSourceSchema.
- renamed syndesisSourceStatuses service to sourceStatuses
- adapted the test cases and adapted the ui usages
> TTOOLS-962 combine dv schema services

- install/operator/deploy/manifests/1.9.0/syndesis.crd.yaml
- install/operator/deploy/manifests/1.9.0/syndesisoperator.1.9.0.clusterserviceversion.yaml
- install/operator/deploy/manifests/syndesis.package.yaml
I've copied from 1.7.0 manifests, adjusted the version where needed and
made sure that the permissions and the deployment config reflect the
current state for 1.9.
> chore: add OLM manifests for version 1.9

- app/connector/gmail/pom.xml
- app/connector/google-calendar/pom.xml
- app/connector/google-sheets/pom.xml
- app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/DBSplitToSheets_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/DBToSheets_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/GoogleSheetsTestSupport.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/MultiSqlToSheets_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/SheetsToSheets_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/sql/DBToHttp_IT.java
- app/test/integration-test/src/test/resources/io/syndesis/test/itest/sheets/DBSplitToSheets-export/model.json
- DBToHttp_IT
Order of queried entries in database seems to differ between environments (locally, CI). Added a message selector to make test more robust by selecting always the right message based on a JsonPath expression evaluated on the Http request payload.
- DBSplitToSheets_IT
Typo in model.json
- Google sheets tests
Tests need to cleanup the contact table between the tests
- Fix api client versions used in Google connectors
Revert dependabot update of api client versions. This leads to unexpected behavior and MethodNotFound errors because underlying Google Camel components still use 1.22.0 as client and api versions. If we want to update to 1.34.0 we need to update Camel components first. Otherwise we end up having mixed versions on the classpath leading to errors. Google sheets …
> fix[integration-test]: Fix some of the failing integration tests on master

- app/ui-react/pom.xml
- app/ui-react/syndesis/craco.config.js
Two changes:
chore: remove `yarn list` from build (46b5277)
This was generating a lot of output in the console/build logs, not sure
why it was added, most likely to troubleshoot an issue; and it seems no
longer needed.
fix(ui): build on ci.fabric8.io (4504ba6)
For whatever reason Jest is unable to resolve modules on ci.fabric8.io
with this error:
```
INFO] lerna ERR! yarn run test --coverage --color --runInBand stderr:
[INFO]  FAIL  src/app/App.test.tsx
[INFO]   ● Test suite failed to run
[INFO]
[INFO]     Cannot find module '/mnt/hudson_workspace/workspace/syndesis-release-daily/app/ui-react/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/interopRequireWildcard' from 'App.tsx'
[INFO]
[INFO]     However, Jest was able to find:
[INFO]     	'./App.css'
[INFO] …
```
> Fix daily builds on ci.fabric8.io

- app/test/test-support/src/main/java/io/syndesis/test/container/integration/SyndesisIntegrationRuntimeContainer.java
We were using `exec:java` debugging option instead of `spring-boot:run` option.
Fixes #8265
> fix(test): maven debug option fix

- app/pom.xml
Including both `javax.activation:activation` and
`com.sun.activation:jakarta.activation` is causing daily 1.10 builds to
fail.
> fix(deps): exclude javax.activation:activation

- app/ui-react/packages/auto-form/src/widgets/FormLabelHintComponent.tsx
- app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorListItem.tsx
- app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorListView.tsx
Added test id to the tooltip icon and to API Connector page to describe the different sections of the list.
> [PF4 migration] Added test-ids to API connector page

- app/ui-react/syndesis/src/modules/connections/components/ConnectionsWithToolbar.tsx
- app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
- app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx
- app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
- app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
- app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
- app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/EditorStepsWithToolbar.tsx
After this change https://github.com/syndesisio/syndesis/commit/d2375570b29048b08b80e0e0e162292d948dbef8#diff-38d54cc1ec6b270563c94153f356a568L49 , some references to CreateConnection translation property were out of date.
I have replaced all occurrence `shared:CreateConnection` to `shared:linkCreateConnection` in the `ui-react` package.
> Replaced old references of CreateConnection translation

- app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackMetaDataExtension.java
We should not be leaking the configured token to the logs or to the caller hierarchy.
> fix(c/slack): don't leak the token

- install/operator/go.mod
- install/operator/pkg/generator/generator.go
- install/operator/pkg/generator/generator_test.go
- install/operator/vendor/modules.txt
Generate the monitoring resources for database only if there is no external database defined
Fixes https://issues.redhat.com/browse/ENTESB-13532
Fixes https://github.com/syndesisio/syndesis/issues/8289
> [operator] Fix for ops addon

- install/operator/pkg/cmd/internal/grant/grant.go
If `syndesis-operator grant` command is called, the `--user` flag is mandatory, but it was ignoring this fact. Also, remove the default value from `--user` which made no sense at all.
Fixes: https://github.com/syndesisio/syndesis/issues/8296
> [operator] --user is mandatory when calling grant

- .circleci/config.yml
Seems that `CIRCLE_PR_NUMBER` is not getting set on pull requests that
originate from branches, `CI_PULL_REQUEST` seems to be set on both so
this changes to using that instead.
> refactor(ci): PR number from CI_PULL_REQUEST env

- app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
Backport of https://github.com/syndesisio/syndesis/pull/8319 to 1.10.x
> (backport-1.10.x)[PF4 migration] Added DataTestIds to DataVirtualization pages

- app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
- app/ui-react/packages/ui/src/Dashboard/UptimeMetric.tsx
- app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx
- app/ui-react/packages/ui/src/Integration/CiCd/CiCdListItem.tsx
- app/ui-react/packages/ui/src/Integration/CiCd/TagIntegrationListItem.tsx
- app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
Backport of https://github.com/syndesisio/syndesis/pull/8291 to 1.10.x
> (backport-1.10.x)[PF4 migration] Added DataTestIds to activity, metrics and cicd pages

- app/ui-react/packages/atlasmap-assembly/yarn.lock
manual backport of https://github.com/syndesisio/syndesis/pull/8203 as part of security maintenance
> [backport to 1.10.x] [security] bump request from 2.42.0 to 2.88.0 in /app/ui-react

- app/ui-react/packages/.storybook/webpack.config.js
- app/ui-react/syndesis/craco.config.js
Found when working with the DV folks that this setting is better set at 1 to avoid memory issues on CI nodes, should fix issues with the `ui` and `ui-doc` jobs.
> chore: turn down parallelism to 1 for CI

- tools/bin/commands/release
Seems that stale tags are preventing us from pushing new tags in the
release:
```
==== Pushing to GitHub
* Pushing 1.10.0-20200426
To https://****@github.com/syndesisio/syndesis.git
* [new tag]         1.10.0-20200426 -> 1.10.0-20200426
fatal: remote part of refspec is not a valid name in :1.10.0-20200410
1.10.0-20200411
1.10.0-20200412
1.10.0-20200413
```
This adds `git fetch --tags --prune` to remove tags from local clone
that have been removed at origin.
> fix(build): perform a `git fetch --tags --prune`

- app/s2i/src/main/docker/Dockerfile
- app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/DBSplitToSheets_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/DBToSheets_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/MultiSqlToSheets_IT.java
- app/test/test-support/src/main/java/io/syndesis/test/SyndesisTestEnvironment.java
- app/test/test-support/src/main/java/io/syndesis/test/container/integration/SyndesisIntegrationRuntimeContainer.java
- app/test/test-support/src/main/java/io/syndesis/test/container/s2i/SyndesisS2iAssemblyContainer.java
- app/test/test-support/src/main/resources/testcontainers.properties
- app/test/test-support/src/test/resources/logback-test.xml
This should fix issues with running testcontainers on CI where SELinux
is enabled. This solves the issue by adding the files of the integration
to the image at image build time instead of mounting the volume at
container runtime. When adding the files as a part of the build we can
control permissions whereas when mounting a volume we need to make sure
that the SELinux context is preserved and that the permissions on files
are sufficient enough taking into account the permissions of the user
running the container.
Also configures that the Ryuk container runs as privileged, this is
required so it can access the Docker socket mounted from host in
environments where SELinux is enabled.
This also contains small cleanup in 2eba92c
> fix(test): testcontainers on CI

- install/operator/.lib.sh
- install/operator/pkg/cmd/internal/operator.go
- install/operator/pkg/generator/generator_test.go
- install/operator/pkg/syndesis/action/install.go
- install/operator/pkg/syndesis/backup/backup.go
- install/operator/pkg/syndesis/configuration/configuration.go
- install/operator/pkg/util/postgresql.go
- install/operator/pkg/util/postgresql_test.go
* configuration.go
* GetProperties is the essential function called for initialising a
configuration object. However, ExternalDatabase is crucial for checking
if the db is external. Instead of calling this separately, include it as
part of GetProperties
* install.go
* ExternalDatabase function removed as now internal
* No need to try and call removePostgresUpgradeTrigger() since this is
only for internal db
* .lib.sh
* Fixes naming/tagging of operator imagestream
> fix(ENTESB-13518): Fix upgrading syndesis installed with an external db

- app/ui-react/syndesis/src/modules/integrations/components/editor/template/useTemplate.tsx
- app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
fixes [ENTESB-11393](https://issues.redhat.com/browse/ENTESB-11393)
> fix: use a different character sequence for interpolation for template editor

- app/ui-react/packages/ui/src/Layout/AppLayout.tsx
fixes [ENTESB-13404](https://issues.redhat.com/browse/ENTESB-13404)
Hard to screenshot but see there's less whitespace underneath the "About" entry.
> fix: move the special classname to the dropdown item so the logout entry is hidden

- app/ui-react/packages/.storybook/webpack.config.js
- app/ui-react/syndesis/craco.config.js
This brings the updated terser config over to 1.10.x so the UI jobs don't sporadically fail.
> fix: bring over CI fixes for the UI jobs

- .circleci/config.yml
Dependabot creates branches and then pull requests for those. Same as in
#8310 we can't rely on `CIRCLE_PR_NUMBER` for pull requests that are not
created from forks, and `CI_PULL_REQUEST` seems to be defined on both
pull requests from branches and pull requests from forks.
Fixes #8366
> fix(build): quay.io transfer for dependabot PRs

- tools/bin/commands/release
Having quotes around the tags that are to be deleted makes those tags a
single argument, i.e. single tag that needs to be deleted rather than
multiple tags, failing the build when there are more than one tag to
delete.
> fix(build): remove quotes around tags to delete

- tools/bin/commands/release
Having quotes around the tags that are to be deleted makes those tags a
single argument, i.e. single tag that needs to be deleted rather than
multiple tags, failing the build when there are more than one tag to
delete.
(cherry picked from commit 0d1b5c887672c21f7d3d5ec92db6ef9f47bdab10)
Backport of #8376 to `1.10.x`
> [skip ci] fix(build): remove quotes around tags to delete

- app/ui-react/syndesis/src/modules/integrations/components/editor/template/useTemplate.tsx
- app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
> (backport) fix: use a different character sequence for interpolation for template editor

- app/common/model/src/main/java/io/syndesis/common/model/Schema.java
- app/common/util/src/main/java/io/syndesis/common/util/CamelCase.java
- app/common/util/src/main/java/io/syndesis/common/util/ErrorCategory.java
- app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderOnExceptionHandler.java
- app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderReturnPathCustomizer.java
- app/connector/api-provider/src/main/resources/META-INF/syndesis/connector/api-provider.json
- app/connector/api-provider/src/test/java/io/syndesis/connector/apiprovider/OnExceptionHandlerTest.java
- app/connector/sql/pom.xml
- app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlConnectorCustomizer.java
- app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlStartConnectorCustomizer.java
- app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
- app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlConnectorQueryTest.java
- app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/ErrorMapper.java
- app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/ErrorStatusInfo.java
- app/connector/support/processor/src/test/java/io/syndesis/connector/support/processor/ErrorMapperTest.java
- app/connector/webhook/src/main/java/io/syndesis/connector/webhook/WebhookOnExceptionHandler.java
- app/server/runtime/pom.xml
- app/server/runtime/src/main/resources/migrations/up-42.js
- app/server/runtime/src/test/java/io/syndesis/server/runtime/migrations/MigrationsHelper.java
- app/server/runtime/src/test/java/io/syndesis/server/runtime/migrations/UpgradeVersion42Test.java
- app/server/runtime/src/test/resources/migrations/42/integration.json
- app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiprovider/TodoOpenApiV3-export/model.json
- app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
- app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
https://github.com/syndesisio/syndesis/issues/8325
Avoid putting classnames as keys in the standardizedErrors config. Ever since the i18n framework was introduced this caused issues. The classnames are now put into a hierarchical map of errors.
Also addresses: https://issues.redhat.com/browse/ENTESB-12908
> Fix to prevent className in the name field on a standardizedError configuration.

- install/operator/.lib.sh
- install/operator/pkg/syndesis/action/install.go
- install/operator/pkg/syndesis/backup/backup.go
- install/operator/pkg/syndesis/configuration/configuration.go
* configuration.go
* GetProperties is the essential function called for initialising a
configuration object. However, ExternalDatabase is crucial for checking
if the db is external. Instead of calling this separately, include it as
part of GetProperties
* install.go
* ExternalDatabase function removed as now internal
* No need to try and call removePostgresUpgradeTrigger() since this is
only for internal db
* .lib.sh
* Fixes naming/tagging of operator imagestream
> BACKPORT: fix(ENTESB-13518): Fix upgrading syndesis installed with an external db

- install/operator/.lib.sh
- install/operator/pkg/syndesis/action/install.go
- install/operator/pkg/syndesis/backup/backup.go
- install/operator/pkg/syndesis/configuration/configuration.go
* configuration.go
* GetProperties is the essential function called for initialising a
configuration object. However, ExternalDatabase is crucial for checking
if the db is external. Instead of calling this separately, include it as
part of GetProperties
* install.go
* ExternalDatabase function removed as now internal 
* No need to try and call removePostgresUpgradeTrigger() since this is
only for internal db
> BACKPORT fix(ENTESB-13518): Fix upgrading syndesis installed with an external db

- install/operator/pkg/syndesis/upgrade/backup.go
Upgrade fails with:
```
E0506 11:48:31.790954       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1517 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x18ebcc0, 0x2c6daf0)
/home/zregvart/tmp/syndesis-master/install/operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/home/zregvart/tmp/syndesis-master/install/operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x18ebcc0, 0x2c6daf0)
/usr/lib/golang/src/runtime/panic.go:969 +0x166
github.com/syndesisio/syndesis/install/operator/pkg/syndesis/clienttools.(*ClientTools).RuntimeClient(0x0, 0xc000bd2690, …
```
> fix(operator): nil pointer dereference in upgrade

- app/test/test-support/src/main/java/io/syndesis/test/container/s2i/S2iProjectBuilder.java
Added an explicit step to copy S2I assembly phase. As of 1b3a19c003576caffa25202543dc92fedf4fa6b7 we're no longer sharing the filesystem so we need to copy the result of a container to be used by other containers.
Fixes #8403
Locally all tests are passing again:
```
[INFO] Results:
[INFO] 
[INFO] Tests run: 54, Failures: 0, Errors: 0, Skipped: 0
```
Looking forward to see if CI/CD are also working.
> fix(test): explicit copy of S2I assembly project

- app/test/integration-test/README.md
I've noticed we don't explicitly say to use the skip variable. I've added a short note to highlight that ([here](https://github.com/syndesisio/syndesis/compare/master...squakez:chore/skip_variable?expand=1#diff-c79726c49ad01184f8a9eb453b5d3132R104)). Please disregard the rest of differences in the PR, it seems my editor is removing an empty space when it's not needed.
> doc(test): adding a note with the usage of skip variable

- doc/modules/connecting/proc-creating-kafka-connections.adoc
This doc update is ready for review.
It is an update to the Kafka Connector documentation - it updates the steps for creating a connection to a Kafka broker to include the options for specifying TLS as a Transfer Protocol and a broker certificate.
> kafka-connector-mf update for TLS option

- tools/bin/commands/integration-test
This should shrink the amount of log output on CircleCI significantly. We have reached log output limits of CircleCI before.
> chore: Use no-transfer-progress option on integration-test builds [ci skip]

- app/server/jsondb/src/main/java/io/syndesis/server/jsondb/impl/SqlJsonDB.java
- app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java
We're not supporting SQLite and CockroachDB, so this removes the dead
code dealing with those. We might support H2 so that code has been left
as is.
> refactor(server): remove dead database code

- app/s2i/src/main/docker/Dockerfile
- app/test/test-support/src/main/java/io/syndesis/test/container/s2i/S2iProjectBuilder.java
- app/test/test-support/src/main/java/io/syndesis/test/container/s2i/SyndesisS2iAssemblyContainer.java
Originally motivated to help with backward compatibility with OpenShift 3.11 this was implemented:
refactor(s2i): replace `ADD --chown` in Dockerfile (609208c)
Seems that the Dockerfile build on OpenShift 3.11 fails if the
`ADD --chown` syntax is used, this reverts to using `ADD` + `RUN chown`
instead to be backward compatible.
A race condition in test-support for integration tests was found and fixed in:
fix(test): copy project jar race condition (e1fa833)
The S2I test container is considered started when the output of the
container shows `... done`, that also coincides with the
`/usr/local/s2i/assemble` script finishing and the process stopping,
stopping the container with it. Using
`GenericContainer::copyFileFromContainer` on a stopped container fails
with `IllegalStateException: …
> S2I and integration test fixes

- app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java
- app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java
- app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftService.java
- app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
- app/server/openshift/src/test/java/io/syndesis/server/openshift/OpenShiftServiceImplTest.java
This moves the integration labels to `DeploymentData` labels, that are later copied to all resources of the integration
> [closes #8348] Move integration labels to deployment data

- install/operator/pkg/cmd/internal/install/generator/generator.go
Following https://github.com/syndesisio/syndesis/pull/8441
This reverts commit 155455af732a91631d2a4e349f02907e37a53eda.
> Revert "Use the Tag instead of Image for database image"

- install/operator/pkg/cmd/internal/install/generator/generator.go
This reverts commit 821340efa7c15e91753514e86d461145fffebff2.
> Revert "Use the Tag instead of Image for database image" (1.10.x branch)

- app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx
The classname was left out on accident and added test-id for test stability.
> Added classname to OpenApiSelectMethod

- app/pom.xml
- app/ui-react/pom.xml
Upgrade iltorb to 2.4.5, skip PUPPETEER CHROMIUM DOWNLOAD
> Upgrade iltorb to 2.4.5, skip PUPPETEER CHROMIUM DOWNLOAD

- app/pom.xml
- app/ui-react/pom.xml
backports https://github.com/syndesisio/syndesis/pull/8506
@cunningt FYI
> (backport) Upgrade iltorb to 2.4.5, skip PUPPETEER CHROMIUM DOWNLOAD

- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandlerTest.java
Connectors' configuredProperties are now loaded and merged with user parameters in verify request.
Fixes #8466
> fix(server): include configuredProperties in verify API request

- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java
- app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandlerTest.java
Giving priority to user properties to override any configuredProperty with same name in verification API
Fix #8466
> fix(server): user properties to override configuredProperties

- app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx
For now, users should _not_ be able to Review/Edit a WSDL file. This PR hides this button from the user if they are creating a SOAP connector. Merging this PR completes [ENTESB-13434](https://issues.redhat.com/browse/ENTESB-13434) as an MVP.
WSDL:
JSON:
> [ENTESB-13434] removes ability to review/edit for SOAP connector

- app/connector/debezium/src/main/java/io/syndesis/connector/debezium/DebeziumMetaDataRetrieval.java
- app/connector/debezium/src/main/java/io/syndesis/connector/debezium/metadata/DebeziumDatashapeStrategy.java
- app/connector/debezium/src/main/java/io/syndesis/connector/debezium/metadata/DebeziumMySQLDatashapeStrategy.java
- app/connector/debezium/src/test/java/io/syndesis/connector/debezium/metadata/DebeziumMySQLDatashapeStrategyTest.java
* Changing the design of datashape retrieval adding DebeziumDatashapeStrategy interface. It will be easier to include any different strategy for retrieval (based on the target database, for instance)
* Moving old metadata retrieval logic used in POC (targeted for mysql) into DebeziumMySQLDatashapeStrategy
Ref ENTESB-13752
> refactor(connector/debezium): mysql metadata retrieval

- app/common/model/src/main/java/io/syndesis/common/model/connection/ConfigurationProperty.java
- app/connector/webhook/src/main/resources/META-INF/syndesis/connector/webhook.json
- app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java
- app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/ConnectorStepHandler.java
- app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiConnectorGenerator.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthApp.java
- app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/AbstractResourceUpdateHandler.java
This to avoid quotes being put around the values during the maven-support-plugin validation step.
> Fix for Entesb 13816 - The defaultValue should be object not string

- install/operator/pkg/cmd/internal/olm/olm.go
(cherry picked from commit 13f47297412c7ba6a2b87bd3ab88bb80134d2add)
> Fix OLM subcommand to use correct property for operator-image parameter (1.10.x)

- app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx
backporting https://github.com/syndesisio/syndesis/pull/8536, which fixes the bug where users are able to edit WSDL files on upload in the API Client Connector wizard.
> [backport 1.10.x] removes ability to review/edit for SOAP connector

- app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
- app/ui-react/syndesis/src/app/UI.tsx
- app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
- Jira Issue https://issues.redhat.com/browse/TEIIDTOOLS-1023 https://issues.redhat.com/browse/TEIIDTOOLS-1024
- Console errors
Added the empty string as default if props.i18nPublishState is undefined in PublishStatusWithProgress.
used the updateHref function directly in context consumer.
- Create view loading
using the loading prop instead of error for showing loading.
- screenshot
> Fix: console errors and create view loading.

- app/dv/pom.xml
- app/dv/src/main/java/io/syndesis/dv/datasources/MongoDBDefinition.java
- app/dv/src/main/java/io/syndesis/dv/openshift/SyndesisConnectionSynchronizer.java
- app/dv/src/main/java/io/syndesis/dv/openshift/TeiidOpenShiftClient.java
- app/dv/src/main/resources/s2i/template-pom.xml
- app/dv/src/test/java/io/syndesis/dv/lsp/completion/TestDdlCompletionItemProvider.java
- app/dv/src/test/resources/generated-pom-security.xml
- app/dv/src/test/resources/generated-pom.xml
- app/pom.xml
making the assumption that we'll want to use the same teiid/tsb version in syndesis as in the generated image.
with this we can further simplify the version management in the template pom and the project pom
this also moves the tomcat dependency back up to 9.0.35 and the spring.version to 5.2.5 to match spring boot 2.2.6
> TEIIDTOOLS-996 updating to latest teiid / teiid spring boot

- app/dv/pom.xml
with the tomcat annotations excluded we need an explicit annotations
dependency
> fix(dv) ENTESB-13939 related to the refactor backport

- app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/DataMapperPage.tsx
Backports https://github.com/syndesisio/syndesis/pull/8589
//skip-ci
> (backport) fix: ensure we preserve any previous mapping document when revisiting the data mapper

- doc/modules/customizing/proc-creating-jdbc-driver-library-extensions.adoc
- doc/modules/customizing/ref-develop-library-extensions.adoc
- doc/modules/integrating-applications/proc-making-extensions-available.adoc
- doc/modules/integrating-applications/proc-procedure-for-creating-an-integration.adoc
Ready for review: update to the doc to address the new feature for selecting runtime libraries when the user saves an integration
> doc update for feature - select library extension at integration save

- app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
fixes ENTESB-11829
Backports https://github.com/syndesisio/syndesis/pull/8614
> (backport) fix: use the right type for the 'min' property

- app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.css
- app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.css
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx
- Jira Issue https://issues.redhat.com/browse/TEIIDTOOLS-1026 https://issues.redhat.com/browse/TEIIDTOOLS-1021
- Used React.memo to stop the re-rendering of RolePermissionListItem component. 
- In place of passing the new reference of the array in props updating the value to existing array.(selectedPermissions in RolePermissionList  && viewRolePermissionList, selectedRoles in ViewPermissionList)
- Reduced the spacing between the metadata tree and DDL editor.
> Fix: role permission dropdown issue and metadata tree spacing

- app/ui-react/packages/models/src/dv.d.ts
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.tsx
- app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionListView.tsx
- app/ui-react/packages/ui/stories/Data/CreateViewWizard/ConnectionSchemaList.stories.tsx
- app/ui-react/packages/ui/stories/Data/CreateViewWizard/ConnectionSchemaListItem.stories.tsx
- app/ui-react/packages/ui/stories/Data/CreateViewWizard/SelectedConnectionListView.stories.tsx
- app/ui-react/packages/ui/stories/Data/CreateViewWizard/SelectedConnectionTables.stories.tsx
- app/ui-react/packages/ui/stories/Data/Views/SchemaNodeListItem.stories.tsx
- app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
- app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
- app/ui-react/syndesis/src/modules/data/shared/ConnectionTables.tsx
- app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Adds the ability for new views created in the 'Create View' wizard to be based upon other views in the virtualization.  The existing virtualization views are displayed as a source for use in the new virtualization.
- adds 'isVirtualizationSource' attribute to the sourceStatuses.  The connection options are then utilized to tag a 'Virtualization Connection' for different handling.
- SelectSourcesPage adds a connection/sourceStatus for the virtualization, in addition to the other backend connections.
- The ConnectionSchemaListItem rows for the 'virtualization source' omit the refresh controls, since there is no need to refresh the virtualization like other backend sources.
- ViewDefinition 'sourcePaths' for the virtualization views utilize '$dv' for the schema.  A corresponding backend …
> (fix) TEIIDTOOLS-765 Allows layering of views in CreateView wizard

- app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
Resolves issue in the CreateView wizard - add/remove tables with same name from different connections was not working properly.
modified the index lookup to include both the table name and connection name.
> fix: TEIIDTOOLS-1040 Fix wizard issue removing tables with same name

- app/dv/src/main/java/io/syndesis/dv/metadata/internal/TeiidDataSourceImpl.java
- app/dv/src/test/java/io/syndesis/dv/metadata/internal/DefaultMetadataInstanceTest.java
the last load may be null if the source hasn't loaded
> fix(dv) addressing a regression from the refactoring

- app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
backports https://github.com/syndesisio/syndesis/pull/8653
fixes ENTESB-11829
> (backport) fix: ensure the min property is properly overridden

- app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
Removes the connection which represents the published Virtualization for the working view.  The working virtualization details are available, so removing the published virtualization connection eliminates some confusion of having two sources with same name.
> TEIIDTOOLS-1044 Remove duplicate connection from Create View wizard

- app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java
- app/server/update-controller/src/test/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandlerTest.java
* Added a condition to skip the connection properties comparison if we are marking the connector as dynamic. A dynamic connector will retrieve connection properties and fail the comparison as they meant to be read at runtime.
* Added a unit test to validate the fix.
Fixes #8519
> fix(server): skip connection properties comparison when dynamic

- app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionListView.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
- app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
- app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
- app/ui-react/syndesis/src/modules/data/shared/ConnectionTables.tsx
Now using the source specific icons for the selected tables in CreateView wizard.
- supplies map of the ConnectionIcons to ConnectionSchemaContent and ConnectionTables components.
- SelectSourcesPage generates the icons - optionally small or large size
- also removed console.log from ViewEditorSqlPage
> TEIIDTOOLS-1043 Use source specific icon in CreateView wizard selections

- app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSecurityForm.tsx
- app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/securityValidation.ts
- app/ui-react/packages/ui/stories/Customization/create/3-Security.stories.tsx
- app/ui-react/packages/ui/stories/Customization/create/soap.js
- app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
Validates connector security form for HTTP basic auth, no auth, and WS security. It's still unclear, but I don't think we need additional validation for OpenAPI specs that use API Key or OAuth, because, IIRC, the API is setting these using the spec, which is validated beforehand.
[ENTESB-14048](https://issues.redhat.com/browse/ENTESB-14048)
Screenshots:
> fix(ui): ENTESB-14048 validate api client connector security fields

- app/ui-react/packages/ui/src/Data/Virtualizations/Views/PreviewData.tsx
- app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
- app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
- Jira issue https://issues.redhat.com/browse/TEIIDTOOLS-1050
- used getConnectionIcons method in SelectSourcePage to pass the icon of the preview table connection.
- screenshot
> Fix: specific source icon in Create View wizard Preview table

- app/integration/bom/pom.xml
- app/pom.xml
- app/ui-react/packages/atlasmap-adapter/package.json
- app/ui-react/yarn.lock
Backporting: #8718
Fixes: https://issues.redhat.com/browse/ENTESB-12362
Release note: https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.0.5
Hi @claudio4j, can we get this backported before next build?
> chore: Update to AtlasMap 2.0.5

- tools/bin/commands/util/client_funcs
- tools/bin/commands/util/kube_funcs
- tools/bin/commands/util/openshift_funcs
* openshift_funcs
* Cannot call read -s as this seems to fail when called within a subshell
* Remove check for no password as in minishift context, no password is
legitimate
* Only add -p to `oc login` if a password is specified
* kube_funcs
* Only request admin password if specifically need it
* client_funcs
* Remove mistaken double-hyphen in caching filename
> Fix: Interactive read fails with -s switch for password

- .github/workflows/e2e.yml
- .github/workflows/e2e_mainbranch.yml
- README.md
Adds two github actions that runs integration tests: one on each PR and one on master after each push to check master stability (and adds the badge on README.md).
I would need someone with privileges to add the PR action as mandatory on all merges like the circleci task :) We will not ignore e2e anymore!
> feature(e2e): Run integration tests as github actions

- tools/bin/commands/util/common_funcs
- tools/bin/commands/util/operator_funcs
* common_funcs
* Modifies the get_platform_detect_bin function to correctly download the
latest platform-detect binary from the github release page
* operator_funcs
* Needs to filter to only the operator binaries and not include
platform-detect
> fix: Updates the download of platform-detect binary

- tools/bin/commands/completion
- tools/bin/commands/ui
calling "syndesis --help" outputs an error
/home/claudio/alphaworks/projects/syndesis/tools/bin/commands/completion: line 18: syntax error near unexpected token `}'
ERROR: Last command exited with 2
> Fix syndesis script

- install/kubernetes/README.md
- tools/bin/commands/build
- tools/bin/commands/minikube
- tools/bin/commands/util/kube_funcs
* README - updated with new detail on registries
* build script
* Expose operator-image so it can be pushed to quay.io
(requires prefix to be stripped)
* Fixes error of passing empty values as parameters
(doesn't substitute for defaults)
* minikube
* Fixes wrong function call
* kube_funcs
* Suppress output of openssl commands and check their exit codes
> fixes and updates to minikube installation

- app/pom.xml
The presence of the library is making many test expecting a json message to fail as they are parsed as xml messages
Fixes #8776
> fix(test): exclude citrus-validation-xml

- tools/bin/commands/util/common_funcs
Check for existing ggrep binary was not working properly on MacOS. 
The command hit the another error before actually doing the check:
`common_funcs: line 415: OK: command not found`
Fixed check to work on MacOS
> chore: Fix build CLI on MacOS

- install/operator/.lib.sh
- install/operator/build.sh
- install/operator/pkg/syndesis/upgrade/database_upgrade.go
- install/operator/pkg/syndesis/upgrade/database_upgrade_test.go
- tools/bin/commands/build
- tools/bin/commands/util/common_funcs
- tools/bin/commands/util/openshift_funcs
- tools/bin/commands/util/operator_funcs
* feature(operator): Add podman support to operator build scripts
* .lib.sh
* Breaks out operator image build function
* Adds podman support to both building the operator binary and image
* Makes references to registry neutral, removing "docker"
* When building operator binary, first check for oc then podman then docker
* build.sh
* Adds podman as an option to expected switches
* common_funcs
* Function for checking is podman is available
* build
* Support for podman when building the operator (cannot yet use it for building other images)
* fix(operator): build script should report all errors if oc version fails
* If oc available but not logged in, avoid the error being swallowed and ensure its displayed to the user and the build script stop
* Fix(scripts): Remove BuildConfig in build …
> Operator changes

- .circleci/config.yml
Nightly job that runs the integration tests is broken for quite some time due to the update to JDK 11. First analysis gave the impression that the job is not easy to fix because of the build executor being an ubuntu virtual machine that only supports Java 1.8 at the moment. As we also run the integration tests for each PR using github actions the effort to also fix the nightly on CircleCi might not be worth it.
> chore: Remove CircleCi nightly job

- app/pom.xml
- tools/bin/commands/build
- tools/bin/commands/integration-test
Maven assembly of `syndesis-parent-tools.jar` is run before each build. When using `--flash` option the tools.jar is not used because all checks are disabled. Adding new `assembly.skip` property and skip the assembly plugin when `--flash` option is given.
This saves me about 45 seconds for each flash build on my machine.
> chore: Skip syndesis-parent tools assembly with flash option

- app/meta/pom.xml
- app/pom.xml
- app/s2i/pom.xml
- app/server/runtime/pom.xml
- app/test/s2i-camelk/pom.xml
- app/ui-react/pom.xml
- install/operator/.lib.sh
- install/operator/build.sh
- tools/bin/commands/build
* commands/build
* build.sh
* .lib.sh
* Removes operator-image-name parameter as not necessary
* Adds image-namespace parameter so can be modified, eg. set namespace as
user-id -> quay.io/phantomjinx/syndesis-operator
* Splits image-namespace from image-name so former can be modified
* Full operator image name: registry/namespace/image-name
* Passes the image.tag into maven builds so correct tag is built and pushed
* app/pom.xml
* Modifies image-name properties to expose both namespace & tag
* s2i/pom.xml
* Extra config needed to ensure fabric8 pushes the correct named image
> fix(build): Allows pushing of images to quay.io

- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/exception/IllegalArgumentExceptionMapper.java
Illegal Argument on Call Given parameter is of unknown type/format: array/null
vs
Illegal Argument on Call: Given parameter is of unknown type/format: array/null
one might think "call-given-parameter"
> imp error message

- app/pom.xml
I'm suffering from this: https://github.com/Apicurio/apicurio-data-models/pull/158
See also: https://github.com/Apicurio/apicurio-data-models/releases/tag/1.1.4
> apicurio: 1.1.2 -> 1.1.4

- app/common/util/src/main/java/io/syndesis/common/util/openapi/CapturingCodec.java
- app/connector/email/pom.xml
- app/meta/pom.xml
- app/meta/src/main/java/io/syndesis/connector/meta/VerifierExceptionMapper.java
- app/pom.xml
- app/server/api-generator/pom.xml
- app/server/credential/pom.xml
- app/server/dao/pom.xml
- app/server/endpoint/pom.xml
- app/server/metrics/prometheus/pom.xml
- app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/HttpClient.java
- app/server/pom.xml
- app/server/runtime/pom.xml
- app/server/update-controller/pom.xml
- app/server/verifier/pom.xml
- app/server/verifier/src/main/java/io/syndesis/server/verifier/ExternalVerifierService.java
- app/test/integration-test/pom.xml
- app/test/pom.xml
* Bumped jackson libraries to 2.11.1 as resteasy depends on this one
* Adding exclusions with libraries clashing due to duplication
* Fixed a few classes for compilation failures due to jackson and resteasy new dependencies
Closes ENTESB-14310
* use javax.persistence-api instead of hibernate-jpa-2.1-api
Closes ENTESB-10680
> [backport 1.11.x] chore(dependencies): resteasy and persistence-api latest dependency upgrade

- app/connector/odata-v2/src/test/java/io/syndesis/connector/odata2/AbstractODataRouteTest.java
- app/connector/odata-v2/src/test/java/io/syndesis/connector/odata2/consumer/ODataReadRouteSplitResultsTest.java
- app/connector/odata-v2/src/test/resources/io/syndesis/connector/odata2/consumer/ref-server-supplier-data-2.json
Make sure to check for all split data returned from results. Was causing daily-release-build to fail.
> fix(ENTESB-13779): Fix connector-odata-v2 unit test

- app/connector/odata-v2/src/test/java/io/syndesis/connector/odata2/AbstractODataRouteTest.java
- app/connector/odata-v2/src/test/java/io/syndesis/connector/odata2/consumer/ODataReadRouteSplitResultsTest.java
- app/connector/odata-v2/src/test/resources/io/syndesis/connector/odata2/consumer/ref-server-supplier-data-2.json
Manual backport of #8953 
Make sure to check for all split data returned from results. Was causing daily-release-build to fail.
(cherry picked from commit 93160cd85b4d8da50778962d50da3e97770b38e0)
> [Backport-1.11.x]: Fix connector-odata-v2 unit test

- install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
- install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
Remove Spec.Components.Prometheus.Rules which is not used, but leave the configuration itself since it is used further down.
> Remove Spec.Components.Prometheus.Rules which is not used

- app/common/util/src/main/java/io/syndesis/common/util/json/JsonUtils.java
- app/integration/bom/pom.xml
- app/meta/src/main/java/io/syndesis/connector/meta/JacksonContextResolver.java
- app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/HttpClient.java
- app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/Utils.java
- app/server/runtime/pom.xml
- app/server/verifier/src/main/java/io/syndesis/server/verifier/ExternalVerifierService.java
- app/test/test-support/pom.xml
- install/operator/deploy/crds/syndesis.io_syndesis_crd.yaml
https://issues.redhat.com/browse/ENTESB-14584
There was an upgrade to resteasy 4.5 that requires jackson 2.11
https://github.com/syndesisio/syndesis/pull/8921
If there is any need to allow classes to be deserialized using Default Typing, it should be activated with Default Typing and setting a custom PolymorphicTypeValidator.
> upgrade jackson to 2.11 and disable default data typing

- app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfig.tsx
- app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfigEdit.tsx
DataTestIds for ApiConnectorDetalConfig page
backport for https://github.com/syndesisio/syndesis/pull/8994
> (backport-1.11.x) Added DataTestIds for ApiConnectorDetalConfig page

- app/integration/bom/pom.xml
- app/pom.xml
- app/ui-react/packages/atlasmap-adapter/package.json
- app/ui-react/yarn.lock
Includes: atlasmap/atlasmap#2318 Set BLOCK_UNSAFE_POLYMORPHIC_BASE_TYPES on jackson ObjectMapper
> chore: Update to AtlasMap 2.0.6

- app/connector/email/src/test/java/io/syndesis/connector/email/AbstractEmailTest.java
- app/connector/flow/pom.xml
- app/connector/kudu/pom.xml
- app/connector/odata-v2/src/main/java/io/syndesis/connector/odata2/component/ODataComponent.java
- app/connector/odata-v2/src/main/resources/META-INF/syndesis/connector/odata-v2.json
- app/connector/odata-v2/src/test/java/io/syndesis/connector/odata2/consumer/ODataReadRouteSplitResultsTest.java
- app/connector/soap/pom.xml
- app/extension/bom/pom.xml
- app/integration/bom-camel-k/pom.xml
- app/integration/bom/pom.xml
- app/pom.xml
Some OData V2 services do explicitly support content only payloads so we need to skip wrappers and metadata from Json payloads. Let user specify write properties such as contentOnly, omitEtag and omitJsonWrapper. This enables us to control the marshalled Json payloads when updating OData entries.
Update Camel dependency to latest 3.5.0 version as this contains the OData olingo2 component that supports custom entity provider write properties.
> fix(ENTESB-13779): Add entity provider write properties

- app/ui-react/packages/ui/src/Shared/InlineTextEdit.css
- app/ui-react/packages/ui/src/Shared/InlineTextEdit.tsx
Fix for [ENTESB-14056](https://issues.redhat.com/browse/ENTESB-14056) - inline editing to better reflect [pf4](https://www.patternfly.org/v4/documentation/react/components/table/#editable-rows).
This was the best I could do without updating the actual component and only sticking to styling changes.
Integration Details:
Connection Details:
> fix(ui) - [ENTESB-14056] update inline editing to better reflect pf4

- app/connector/odata-v2/src/main/java/io/syndesis/connector/odata2/component/ODataComponent.java
- app/connector/odata-v2/src/main/resources/META-INF/syndesis/connector/odata-v2.json
- app/connector/odata-v2/src/test/java/io/syndesis/connector/odata2/consumer/ODataReadRouteSplitResultsTest.java
Some OData V2 services do explicitly support content only payloads so we need to skip wrappers and metadata from Json payloads. Let user specify write properties such as contentOnly, omitEtag and omitJsonWrapper. This enables us to control the marshalled Json payloads when updating OData entries.
Update Camel dependency to latest 3.5.0 version as this contains the OData olingo2 component that supports custom entity provider write properties.
(cherry picked from commit eaa465364329bb8f5a3a895f4e20c56898467d5b)
> [Backport-1.11.x] fix(ENTESB-13779): Add entity provider write properties

- app/pom.xml
- app/server/openshift/src/test/java/io/syndesis/server/openshift/OpenShiftServiceImplTest.java
Related to Autodiscover Kafka broker doesn't work on OCP 4.5
https://issues.redhat.com/browse/ENTESB-14507
OCP 4.5 is based on k8s 1.18 and there are changes in k8s domain
model which fabric8 k8s client 4.6.1 throw errors trying to
deserialize
> Upgrade fabric8 k8s client

- app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.css
- app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
Also add some styling and hides buttons for adding/removing array fields when in disabled mode.
cc @Delawen
> fix(ui): Disable/enable array fields in Kafka Connector

- app/ui-react/docker/nginx-syndesis.conf
- app/ui-react/nginx-syndesis.conf
- app/ui-react/syndesis/src/setupProxy.js
Using the proper cookie name, `oauth_proxy` instead `_oauth_proxy` solved the issue.
Fix #9040
> fix(ui-react): change oauth cookie name

- app/integration/bom/pom.xml
- app/pom.xml
- app/ui-react/packages/atlasmap-adapter/package.json
- app/ui-react/yarn.lock
Includes: atlasmap/atlasmap#2372 XML schema doesn't load properly when anonymous complex type exists
> chore: Update to AtlasMap 2.0.8 

- install/operator/pkg/syndesis/versions/versions.go
* At the end of the migration CRD, if a migration has been performed then
a new CR is created. Avoid doing this if there was no migration.
> ENTESB-14768: Stop the migration routine creating a custom resource

- app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailBody.spec.tsx
- app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailConfig.spec.tsx
- app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailConfigEdit.spec.tsx
- app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailBody.tsx
- app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfig.tsx
- app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfigEdit.tsx
- app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
- app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
fix for [ENTESB-14905](https://issues.redhat.com/browse/ENTESB-14905):
- hide all fields on Detail page Edit view that don't contain an existing value
- show the Address field if a value for it exists
> fix(ui) - ENTESB-14905 - SOAP address not showing in detail page

- app/pom.xml
https://issues.redhat.com/browse/ENTESB-14258
The postgres driver version is brought in my spring-boot. With the current pull request we are overriding the 42.2.11 to 42.2.16 (currently the  latest)
> [fix] ENTESB-14258 overriding the postgres driver version from spring boot

- app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailBody.spec.tsx
- app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailConfig.spec.tsx
- app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailConfigEdit.spec.tsx
- app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailBody.tsx
- app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfig.tsx
- app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfigEdit.tsx
- app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
- app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
backport of https://github.com/syndesisio/syndesis/pull/9107 for [ENTESB-14905](https://issues.redhat.com/browse/ENTESB-14905)
(reopened due to conflict with squashing commits)
> [backport 1.11.x] - ENTESB-14905 - ui(fix) address SOAP connector detail page

- app/connector/mongodb/pom.xml
- app/pom.xml
Spring boot BOM is declaring a different set of mongodb drivers compared to the one declared and needed by Camel MongoDB component. We need to explicitly override those managed dependencies in order to align with Camel.
Fix #9106
> fix(meta): managed mongodb drivers

- install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
- install/operator/pkg/syndesis/capabilities/capabilities.go
- install/operator/pkg/syndesis/olm/assets/alm-examples
- install/operator/pkg/syndesis/olm/assets/productized/description
- install/operator/pkg/syndesis/olm/csv.go
- install/operator/pkg/syndesis/olm/csv_test.go
* capabilities.go
* Stop the olm generator bombing out with a null pointer
* alm-examples
* Enables jaeger by default in offered CR
* csv.go
* Fixes truncation of permissions
* Fixes marshalling of lowerCamelCase
* Adds RelatedImages creation
* Override ApiServer to set all to true
> ENTESB-13275: Updates OLM csv generator to latest permissions & settings

- app/extension/bom/pom.xml
- app/integration/bom/pom.xml
- app/pom.xml
Camel needed to be upgraded because `io.swagger:*` version that was
forked in Fuse and depended upon from `:camel-parent` is no longer
available in JBoss EA repository. This version should contain all forked
dependencies pinned in JBoss EA repository.
> chore: upgrade Camel to 2.23.2.fuse-780030

- app/s2i/pom.xml
Running the S2I image build as a part of a multi-module build would lead
to an error from Docker build:
```
Error while trying to build the image: Unable to build image [syndesis/syndesis-s2i:latest] : "ADD failed: no source files were specified"
```
The `ADD` in question was missing the license files that were to be
generated by the license-maven-plugin. The execution of plugin was
skipped, as can be seen in the Maven output:
```
[INFO] --- license-maven-plugin:2.0.0:aggregate-download-licenses (collect-licenses) @ s2i ---
[INFO] skip flag is on, will skip goal.
```
As by default license-maven-plugin would execute only on root (parent)
module of a multi-module build and at the same time if the
`skipAggregateDownloadLicenses` flag is set to `false`.
By default in the `syndesis` script we …
> fix: s2i image build

- app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java
- app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGeneratorConfiguration.java
- app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/mvn/PomContext.java
- app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/pom.xml.mustache
- app/s2i/pom.xml
- app/server/builder/image-generator/src/main/java/io/syndesis/server/builder/image/generator/Application.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/offline/OfflineS2IBuild_IT.java
From commit messages:
fix(s2i): broad inclusion of dependencies (4a025cf)
When two connectors, usually by means of transitive dependencies, depend
on the same artefact of different versions, Maven version resolution[1]
will pick the newest of version.
When we build the S2I image we generate an Integration that contains all
known Connectors and Connector templates, with the intent on gathering
all dependencies.
Because of the version resolution only one of the versions needed will
be included. This poses a problem when a Connector depending on a older
version of the artefact is used without the Connector depending on the
newer version of the artefact. The older version would then be fetched
from a Maven repository.
The S2I image should contain all artefacts needed in order to allow
for …
> ENTESB-15064: offline S2I build

- app/pom.xml
The ui-react and docs were ignored by a previous commit.
That was an accident, so reverting that change.
> Fix ignored modules

- app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java
- app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGeneratorConfiguration.java
- app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/mvn/PomContext.java
- app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/pom.xml.mustache
- app/s2i/pom.xml
- app/server/builder/image-generator/src/main/java/io/syndesis/server/builder/image/generator/Application.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/amq/AMQToHttp_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/amq/HttpToAMQ_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/offline/OfflineS2IBuild_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/DBSplitToSheets_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/DBToSheets_IT.java
- app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/MultiSqlToSheets_IT.java
- app/test/test-support/src/main/java/io/syndesis/test/SyndesisTestEnvironment.java
- app/test/test-support/src/main/java/io/syndesis/test/container/integration/SyndesisIntegrationRuntimeContainer.java
- app/test/test-support/src/main/java/io/syndesis/test/container/s2i/SyndesisS2iAssemblyContainer.java
In addition to what was mentioned in #9150, this includes:
chore(test): backport integration test fixes (fcdf65d)
This is a partial backport from `master` of these commits:
1b3a19c: fix(test): testcontainers on CI
e1fa833: fix(test): copy project jar race condition
609208c: refactor(s2i): replace `ADD --chown` in Dockerfile
This is needed for integration tests to run on my setup and as explained
on CI if SELinux is enabled.
Parts that are not backported were not needed to run integration tests
on my environemnt (but could be needed for CI):
app/test/test-support/src/main/resources/testcontainers.properties (added)
app/s2i/src/main/docker/Dockerfile (permission changes)
> ENTESB-15064: offline S2I build (1.11.x backport)

- install/operator/pkg/build/pkg.go
- install/operator/pkg/syndesis/olm/assets.go
- install/operator/pkg/syndesis/olm/dev/dev.go
- install/operator/pkg/syndesis/olm/mode_dev.go
- install/operator/pkg/syndesis/olm/mode_prod.go
Note: this does not affect syndesis builds since the bug only arises whilst running `syndesis-operator olm ...`, which is a one-time operation for generating the olm manifest. At the moment, the latter is being generated then committed to separate repos so therefore separately managed.
This allows `syndesis-operator olm ...` to be executed from any directory and not just the pkg/syndesis/olm directory.
* pkg.go
* Brought downstream - creates a var containing the process' directory
* generator/dev/dev.go
* Corrects http.Dir in line with upstream using the GoModDirectory var
* assets.go
* Removes the incorrect GetAssetsFS() function in favour of 2 versions,
ie. 1 dev and 1 prod.
* The dev version uses the existing real assets directory while building
the binary
* The prod version uses the …
> fix(olm): Incomplete assets generation for olm virtual filesystem

- app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderReturnPathCustomizer.java
A regression was introduced during latest code refactory. A missing check condition was always setting the output result to an empty string.
Fix ENTESB-15131
> fix(connector/api): check for error handling

- app/connector/pom.xml
- app/meta/pom.xml
- app/pom.xml
Camel 3.4.4 brings 1.11.714 while syndesis was using 1.11.415 and at runtime there were mixed versions.
This is to consolidate on 1.11.714
> Set AWS dependencies to 1.11.714

- app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/DetailsPage.tsx
Fix for [ENTESB-15132](https://issues.redhat.com/browse/ENTESB-15132) where the `basePath` + `host` fields are not filled in when creating an API Client Connector. Changed it for both OpenAPI + SOAP to first check `configuredProperties`, otherwise use `defaultValue` provided.
OpenAPI Connector
SOAP Connector
> fix(ui) [ENTESB-15132] - check defaultValue for address, basePath + host

- app/pom.xml
- app/s2i/pom.xml
- app/s2i/src/main/license/apache_license_2.0.txt
When building the s2i image, it downloads all licenses
however when building in jenkins there are many network errors
which we believe are related to apache infra avoiding
many request in a short time.
This way the apache license is cached locally and will speed up
the build process.
> Cache the apache license locally

- app/ui-react/packages/api/src/WithApiConnectorHelpers.tsx
- app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailBody.spec.tsx
- app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailConfig.spec.tsx
- app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailConfigEdit.spec.tsx
- app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailBody.tsx
- app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfig.tsx
- app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfigEdit.tsx
- app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
Fixes [ENTESB-15273](https://issues.redhat.com/browse/ENTESB-15273) - When the fields are empty during editing API Connector, they disappear.
Since we are not using Autoform for the API Client Connector wizard and we want to make as few drastic changes as possible, I grabbed the keys from the `properties` object to determine which fields should be shown/hidden in the respective UI components. Fields that have no value set are hidden from the View mode, but available in Edit mode. Name and description fields are always shown. It's not my favorite solution to this problem, but it's lower risk, because it ensures that the fields are only shown if they are specified within the `properties` property.
I also discovered another bug where you are not able to edit the Address field of a SOAP …
> fix(ui) ENTESB-15273 - API Client Connector

- app/server/runtime/pom.xml
- app/server/runtime/src/main/resources/application.yml
- app/server/runtime/src/main/resources/bootstrap.yml
Allow syndesis-server to reload the spring-context automatically in case the syndesis-server-config ConfigMap changes, as spring-boot application.yml is mapped from the ConfigMap.
This change allows higher availability of syndesis-server as there is no need to restart the pod to reload the changes in syndesis-server-config ConfigMap.
> Reload ConfigMaps to avoid manual pod respin

- .github/workflows/e2e.yml
The integration tests job is only available on the master branch. Let's enable it for 1.11.x too.
> feature(e2e): Run integration tests as github actions on each PR

- app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderReturnPathCustomizer.java
Integration tests were showing a different status code, because we only updated it if an error was raised. Moving the status code update outside the error check solves the issue.
Ref ENTESB-15131
> [Backport] fix(connector/api): status code setting

- app/test/test-support/src/main/java/io/syndesis/test/SyndesisTestEnvironment.java
The configuration for the tests was using an old version.
> fix(version-test): This 1.10 was was missing from the 1.11.x change

- app/server/builder/image-generator/src/main/java/io/syndesis/server/builder/image/generator/Application.java
Adds additional template steps to the list of steps that are used to
generate projects to gather dependencies that will be incorporated in
the S2I image.
ref. https://issues.redhat.com/browse/ENTESB-15064
> fix: include template step dependencies in s2i

- app/ui-react/packages/history/.size-snapshot.json
- app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
- app/ui-react/syndesis/src/modules/connections/__test__/utils.spec.tsx
- app/ui-react/syndesis/src/modules/connections/components/WithConnectorForm.tsx
- app/ui-react/syndesis/src/modules/connections/utils.ts
On the custom API Client Connector's detail page we want to show the
configured property value or if it doesn't exist the default value of
the property.
Similarly on the configuring a connection we want to use the
configured property first and then the the default value.
ref. https://issues.redhat.com/browse/ENTESB-15292
> fix: configured vs default values in API connector

- app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DbMetaDataHelper.java
- app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlMetadataRetrievalTest.java
- app/connector/sql/src/test/java/io/syndesis/connector/sql/common/PostgreSqlMetaDataITCase.java
When we encounter a column of JDBC type `OTHER` we now look at the type
name to see if it equals `UUID` (regardless of case), and report the
column having `VARCHAR` JDBC type instead.
Ref. https://issues.redhat.com/browse/ENTESB-13689
> chore(sql): support UUID column type in PostgreSQL

- app/server/runtime/pom.xml
- app/server/runtime/src/main/resources/application.yml
- app/server/runtime/src/main/resources/bootstrap.yml
When the user changes properties on syndesis custom resource
that changes values in ConfigMaps, the spring context or spring app
should be restarted to take the changes into effect, otherwise the
user must manually respin the pod.
> ENTESB-14875 Reload ConfigMaps to avoid manual pod respin

- app/server/endpoint/pom.xml
We no longer search the classpath for annotation processors (#8516).
Immutables is used in one of the tests, so this helps IDE auto-configure
for it.
> fix: define immutables annotation processor

- package.json
- tools/bin/commands/util/common_funcs
When husky runs pre-push script it often triggers on unstaged files in
the ui-react module, this adds `--incremental-staged` flag to `syndesis`
CLI so that build is run only for staged changes, i.e. unstaged changes
are ignored.
> chore: flag for incremental build of staged files

- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/DefaultVerifierExtensionUploader.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/NoopVerifierExtensionUploader.java
- app/server/runtime/src/main/java/io/syndesis/server/runtime/IntegrationConfiguration.java
I'm not exactly sure if this plays any effect in [ENTESB-12512](https://issues.redhat.com/browse/ENTESB-12512) as I cannot reproduce it. It might be an oversight, it might not be.
433af5e helps with running outside OpenShift/Kubernetes.
> fix: don't include deleted extensions

- app/ui-react/packages/api/src/helpers/__test__/integrationFunctions.spec.ts
- app/ui-react/packages/api/src/helpers/integrationFunctions.ts
For cases where action's descriptor has data shape of type 'none' we
would assert that the data shape does not exist. This would cause us not
to recommend adding a mapping step between a input step with data shape
of 'none' and a step containing a data shape other than 'none'. In that
case we do wish to suggest adding a mapping step as mapper can operate
without inputs, i.e. it can add constant values and map those to the
output.
Fixes #3807
Ref https://issues.redhat.com/browse/ENTESB-11568
> fix: consider 'none' data shape present

- app/integration/bom/pom.xml
- app/pom.xml
- app/ui-react/packages/atlasmap-adapter/package.json
- app/ui-react/yarn.lock
Release Note: https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.1.2
> chore: Update to AtlasMap 2.1.2

- app/extension/converter/pom.xml
- app/extension/converter/src/main/java/io/syndesis/extension/converter/DefaultBinaryExtensionAnalyzer.java
- app/extension/converter/src/test/java/io/syndesis/extension/converter/DefaultBinaryExtensionAnalyzerTest.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorIconHandler.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/DefaultVerifierExtensionUploader.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/ExtensionHandler.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/support/IntegrationSupportHandler.java
- app/server/filestore/src/main/java/io/syndesis/server/filestore/impl/SqlFileStore.java
When investigating ENTESB-15548[1] I've found several instances of
streams not being closed. Some of these streams are streams that are
obtained from the PostgreSQL JDBC driver and might lead to connection
leak. I haven't investigated if that's the case, other than what's
already noted on ENTESB-15548. I think this refactoring is safe.
[1] https://issues.redhat.com/browse/ENTESB-15548
> fix: make sure closable resources are closed

- app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
- app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
fixes [ENTESB-11603](https://issues.redhat.com/browse/ENTESB-11603)
- for the Create Connection fix, include `configuredProperties` in `backHref` of the `ReviewPage`, since there is already a check in place for configured fields in `ConfigurationPage`
- went ahead and fixed this for the Security step of the API client connector as well, which, conversely, did _not_ check for configured fields in `SecurityPage`, so this check was added
> fix(ui) [ENTESB-11603] prevent configured properties from being cleared in integration + API connector editors

- .github/workflows/e2e.yml
Just adding a github cache for the .m2 folder. First run of this will take some time but following runs should be faster.
> feature(itest): Cache maven packages to speed up action

- app/ui-react/syndesis/src/modules/integrations/components/editor/EditorSidebar.tsx
fixes [ENTESB-11411](https://issues.redhat.com/browse/ENTESB-11411) where the previous step still shows on the sidebar/vertical navigation after the user has selected for it to be replaced with a different step.
> fix(ui): [ENTESB-11411] display a generic step icon when replacing a step

- tools/bin/commands/release
For a reason that is lost on me, and could be no longer relevant, we do
not tag/push the operator image with the moving tag, i.e. with x.y, but
only with the release tag. This removes this peculiarity of the operator
release.
Also refactors tagging/pushing of the syndesis-upgrade image to
consolidate the logic.
> refactor: also tag the operator with moving tag

- tools/bin/commands/release
This implements tagging/pushing to quay.io in addition to existing
Docker Hub. Selection of the image registry to push to is based on what
username/password parameters are given. Light refactoring was performed
to remove duplication and functions were renamed to to reflect the
functionality within.
Based on and incorporates #9299 so that needs to be reviewed/merged first.
> chore: push container images to quay.io

- app/pom.xml
- app/test/integration-test/pom.xml
- app/test/integration-test/src/test/java/io/syndesis/test/itest/offline/OfflineS2IBuild_IT.java
- app/test/test-support/pom.xml
Not sure why we can't pull testcontainers/ryuk image in GitHub actions
perhaps upgrading testcontainers would help with this.
> chore(deps): upgrade testcontainers to 1.15.1

- app/common/model/src/main/java/io/syndesis/common/model/action/Action.java
- app/connector/support/maven-plugin/src/main/resources/connector-schema.json
- app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentProxyEndpoint.java
- app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/Processors.java
- app/integration/runtime/pom.xml
- app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/ConnectorStepHandler.java
- app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/ConnectorStepHandlerPollEnrichIT.java
- app/pom.xml
- app/server/api-generator/src/test/java/io/syndesis/server/api/generator/soap/SoapApiConnectorGeneratorExampleTest.java
- app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
- app/test/integration-test/pom.xml
- app/test/integration-test/src/test/java/io/syndesis/test/itest/offline/OfflineS2IBuild_IT.java
- app/test/test-support/pom.xml
- app/ui-react/packages/api/src/WithConnection.tsx
- app/ui-react/packages/api/src/helpers/__test__/connectionFunctions.spec.ts
- app/ui-react/packages/api/src/helpers/connectionFunctions.ts
- app/ui-react/packages/api/src/useConnection.tsx
- app/ui-react/packages/models/openapi.internal.json
- app/ui-react/packages/models/openapi.json
- app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/SelectActionPage.tsx
- app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
This adds support for Connector Actions with `PollEnrich` pattern placed
other than at first step of the Integration Flow by using Poll Enrich
EIP.
To utilize this support, Connector Action needs to declare the `pattern`
as `PollEnrich` and the connector's Camel component needs to support
`PollingConsumer`.
To support before/after consumers for poll enrich, we're not using the
`pollEnrich` Route DSL, but we're adding `PollEnricher` processor
directly to the route via `process` Route DSL method. This allows us
to add a pipeline of `before-PollEnricher-after` processors.
User interface now allows actions with the `PollEnrich` pattern in all
but the first step.
> feat(integration): support pollEnrich

- app/server/filestore/src/main/java/io/syndesis/server/filestore/impl/SqlFileStore.java
The stream we pass from the database to the HTTP client will be closed
by the HTTP client, it might be closed only for happy day cases or it
might be closed for both happy and error cases, we don't have control
over that. If we use try-with-resources, as we do currently, we might
try to close the same stream twice: once by the HTTP client once by the
try-with-resources.
This allows the stream to be closed multiple times.
Ref. https://issues.redhat.com/browse/ENTESB-15671
> fix: tolerate repeated close of extension stream
